(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"120x600_atlas_NP_", frames: [[645,0,254,600],[0,0,368,500],[370,0,273,600]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib._1b = function() {
	this.spriteSheet = ss["120x600_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["120x600_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._4b = function() {
	this.spriteSheet = ss["120x600_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.p3b = function() {
	this.initialize(img.p3b);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,131,220);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Path_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyRCbIAAk1MAkjAAAIAAE1g");
	this.shape.setTransform(117,15.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_1, new cjs.Rectangle(0,0,234,31), null);


(lib.tyu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1b();
	this.instance.parent = this;
	this.instance.setTransform(-137,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.tyu, new cjs.Rectangle(-137,-300,254,600), null);


(lib.t3b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AG9CTIAAg1IidAAIAAjuIAvAAIAADFIBRAAIAAjFIAuAAIAADFIAcAAIAABegAOEBaQgQgHgNgNQgJgKgFgMQgGgLgBgOQgCgNgBgPIgjAAIAABjIgvAAIAAjuIAvAAIAABhIAkAAQAAgRADgNQACgNAFgLQAFgKAIgJQANgNAQgHQARgGATAAQATAAARAGQAQAHANANQANANAFATQAGASgBAYIAAAZQABAUgCAPQgBAQgFAOQgFAOgLAMQgNANgQAHQgQAGgUAAQgTAAgRgGgAOXhlQgIADgFAGQgHAIgCAPQgDAPAAAWIAAAPIABAcQABALADAHQADAIAEAEQAGAHAHADQAIADAJAAQAJAAAIgDQAIgDAFgHQAIgIACgOQACgOAAgYIAAgOQAAgXgDgOQgCgOgHgIQgFgGgIgDQgIgEgJAAQgJAAgIAEgAr8BZQgQgGgNgNQgLgMgFgPQgFgPgBgPQgCgOABgOIAAgTQAAgYACgPQACgQAFgLQAFgLAJgJQANgNAQgHQARgGATAAQATAAARAGQAQAHANANQAMAMAGATQAGATAAAdIAAAZIgBAeQgCAQgFAOQgFAOgLAMQgNANgQAHQgQAGgUAAQgTAAgRgHgArphlQgHADgGAGQgIAJgCAQQgCARAAAWIAAAMQAAASACAQQACAPAIAJQAGAGAHADQAIADAJAAQAJAAAIgDQAIgDAFgGQAFgFACgIQADgHABgOIABglIgBgfQgBgMgDgIQgCgHgFgFQgFgGgIgDQgIgEgJAAQgJAAgIAEgAKWBeIAAiZIhdCZIgqAAIAAjuIAvAAIAACYIBdiYIAqAAIAADugADMBeIhUh8IAAB8IgvAAIAAjuIAvAAIAABxIBNhxIA4AAIhRBwIBZB+gAiCBeIAAjuICdAAIAAApIhuAAIAAA5IBdAAIAAApIhdAAIAAA6IBuAAIAAApgAjpBeIAAjFIg5AAIAABGQAAAlgFAZQgEAZgKAOQgJAOgOAGQgOAGgSAAIgTAAIAAgpIAHAAQAJAAAHgEQAIgDAFgKQAGgJADgSQADgRAAgcIAAhsICVAAIAADugAnQBeIAAjFIg5AAIAABGQAAAlgFAZQgEAZgKAOQgJAOgOAGQgOAGgSAAIgTAAIAAgpIAHAAQAJAAAHgEQAIgDAFgKQAGgJADgSQADgRAAgcIAAhsICVAAIAADugAt8BeIhUh8IAAB8IgvAAIAAjuIAvAAIAABxIBNhxIA4AAIhRBwIBZB+g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3b, new cjs.Rectangle(-102.4,-14.7,204.9,29.5), null);


(lib.t3a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AOmBLQgKgFgJgIQgGgHgDgHQgEgIgBgIQgBgJAAgKIgYAAIAABBIgeAAIAAibIAeAAIAAA/IAYAAQAAgLACgIQABgJADgHQAEgGAFgGQAIgJALgEQALgEAMAAQANAAALAEQAKAEAJAJQAIAIAEAMQADAMAAAQIAAAPQAAANgBALQAAAKgEAJQgDAJgHAIQgJAIgKAFQgLAEgMAAQgNAAgLgEgAOygxQgFACgDAEQgFAFgBAKQgCAKAAAOIAAAJIABATIACAMIAFAHQAEAEAFADQAFACAFAAQAGAAAFgCQAFgDAEgEQAFgFABgJQACgKAAgQIAAgIQAAgPgCgJQgCgJgEgFQgEgEgFgCQgFgCgGAAQgGAAgFACgAhdBLQgLgFgIgIQgHgIgEgKQgDgJgBgKIAAgTIAAgMIABgZQABgKAEgHQADgHAGgGQAIgJALgEQALgEAMAAQANAAAKAEQALAEAIAJQAIAIAEAMQAEAMAAATIAAAPIgBAVQgBAKgDAJQgDAJgIAIQgIAIgKAFQgLAEgNAAQgMAAgLgEgAhRgxQgFACgDAEQgFAGgCAKQgBALAAAPIAAAGQAAANABAKQABAKAGAGIAIAGQAFACAGAAQAGAAAFgCQAFgCAEgEQADgEABgFQACgFABgIIAAgYIAAgVQgBgHgCgFQgBgFgDgDQgEgEgFgCQgFgCgGAAQgGAAgFACgAoKBLQgKgFgIgIQgIgIgDgKQgDgJgBgKIgBgTIAAgMIABgZQACgKADgHQAEgHAGgGQAIgJAKgEQALgEANAAQAMAAALAEQALAEAIAJQAIAIAEAMQADAMAAATIAAAPIAAAVQgBAKgDAJQgEAJgHAIQgIAIgLAFQgLAEgMAAQgNAAgLgEgAn9gxQgFACgEAEQgFAGgBAKQgCALABAPIAAAGQgBANACAKQABAKAFAGIAJAGQAFACAGAAQAGAAAFgCQAFgCADgEQADgEACgFQACgFAAgIIABgYIgBgVQAAgHgCgFQgCgFgDgDQgDgEgFgCQgFgCgGAAQgGAAgFACgALPBOIAAgbIAMAAQAGAAAEgDQAEgCACgFIAFgLIgyhrIAfAAIAhBLIAehLIAfAAIg3CAQgDAIgFAFQgEAGgHAEQgHAEgJAAgAKMBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAIDBOIg0hRIAABRIgeAAIAAhRIg0BRIglAAIA4hSIgzhJIAkAAIAwBKIAAhKIAeAAIAABKIAwhKIAkAAIgzBJIA4BSgAEpBOIAAibIAeAAIAACbgACoBOIAAibIAeAAIAAA7IAfAAQAQAAALAGQALAGAGAKQAHALAAAOQAAAPgHAKQgGALgLAGQgMAHgPAAgADGAzIAdAAQAKgBAGgFQAGgGAAgKQAAgKgGgFQgGgGgKAAIgdAAgABlBOIAAiAIglAAIAAAtQAAAYgDAQQgDAQgGAKQgGAJgJAEQgJAEgMAAIgNAAIAAgbIAFAAQAGAAAFgDQAEgCAEgGQAEgGACgMQACgLAAgRIAAhHIBhAAIAACbgAi9BOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAmaBOIAAibIA9AAQAPAAAMAGQALAGAHALQAGALAAAOQAAAPgGALQgHAKgLAGQgMAGgPAAIgeAAIAAA7gAl7gHIAcAAQALAAAGgGQAGgGAAgKQAAgJgGgGQgGgGgLAAIgcAAgAqhBOIAAibIBiAAIAAAbIhDAAIAACAgAsHBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgAsZAYIgTg3IgTA3IAmAAgAujBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3a, new cjs.Rectangle(-101.5,-7.9,203,15.9), null);


(lib.t2c = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D7ABD").s().p("ALbFpQgigRgVggQgUgfgBgvIAAhnQABgvAUggQAVgfAigRQAhgOAqgBQAqABAhAOQAiARAVAfQAVAgAAAvIAABnQAAAvgVAfQgVAggiARQghAPgqAAQgqAAghgPgAL/BbQgOAOAAAfIAABeQAAAeAOAOQAOAPAZAAQAZAAAOgPQAOgOAAgeIAAheQAAgfgOgOQgOgPgZAAQgZAAgOAPgAkJFeQgygYgfgyQgegxgChHIAAk3QAChHAegwQAfgyAygZQA0gaA9AAQA9AAAzAaQAxAZAfAyQAfAwAABHIAAE3QAABHgfAxQgfAygxAYQgzAag9AAQg9AAg0gagAjZjjQgZAbgBAvIAAE0QABAvAZAaQAZAaAoABQAogBAZgaQAYgaAAgvIAAk0QAAgvgYgbQgZgagogBQgoABgZAagAtCFiQg1gWgigwQghgxgChNICHAAQADAyAdAXQAdAYAoAAQAsgBAcgaQAcgaAAgyQAAgvgbgbQgbgbgygBIgUAAIAAh1IAUAAQAwAAAYgbQAWgaAAgnQgBgugagYQgagZgmAAQgnABgZAXQgZAYgDAqIiHAAQAChCAfgwQAeguAzgaQAygZA/AAQBCAAAzAbQAzAbAcAvQAdAwAAA/QAAA8gXAkQgYAlglASQApAVAaAoQAbAoABBDQgBBKgfAwQggAyg2AYQg0AYhBAAQg9AAg1gWgAFXFzIFerkIBqAAIlfLkgAECgEQgigQgVgfQgTgggBgvIAAhnQABgvATgfQAVghAigPQAigQArAAQAoAAAjAQQAiAPAUAhQAUAfABAvIAABnQgBAvgUAgQgUAfgiAQQgjAQgoAAQgrAAgigQgAEmkRQgNAPAAAdIAABfQAAAdAOAPQAOAPAaAAQAYAAAOgPQAOgPAAgdIAAhfQAAgdgOgPQgOgPgYAAQgbAAgOAPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2c, new cjs.Rectangle(-95.7,-37.6,191.4,75.3), null);


(lib.t2b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ADyDRIAAhMIi8AAIAABMIg/AAIAAiHIAfAAQAOgWAJgeQAJgdAEgkQAEgkAAgnIAAhXIDNAAIAAEXIAnAAIAACHgAB+hhQAAAzgGArQgHAqgRAjIBpAAIAAjcIhLAAgAtSB+QgXgJgSgSQgRgRgHgUQgHgVgBgYQgCgXAAgdQAAgeACgYQABgYAHgUQAHgVARgRQASgRAXgKQAWgKAcAAQAgAAAaAMQAaAMASAYQARAYAGAjIhDAAQgFgUgOgOQgNgNgZgBQgOAAgLAFQgKAFgIAIQgGAHgEAKQgDAKgCASQgBATAAAgQAAAgABARQACATADAKQAEAKAGAGQAIAJAKAEQALAFAOAAQAZgBANgNQAOgNAFgVIBDAAQgGAjgRAYQgSAYgaAMQgaAMggAAQgcAAgWgKgANZCFIgUg8Ih5AAIgUA8IhFAAIB7lSIA0AAIB8FSgAMzARIgph6IgrB6IBUAAgAIhCFIh3iwIAACwIhCAAIAAlSIBCAAIAAChIBuihIBPAAIhyCfIB9CzgAh6CFIAAjZIiEDZIg7AAIAAlSIBDAAIAADYICEjYIA7AAIAAFSgAmvCFIh3iwIAACwIhDAAIAAlSIBDAAIAAChIBtihIBPAAIhyCfIB+Czg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2b, new cjs.Rectangle(-92.5,-20.8,185.1,41.8), null);


(lib.t2a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("ApRBLQgKgFgIgIQgIgIgDgJQgEgJAAgMIgBgYIABgYQAAgLAEgJQADgKAIgHQAIgJAKgEQALgEANAAQAOAAAMAFQAMAGAIALQAIAKADARIgfAAQgCgKgGgGQgHgGgLAAQgGAAgFACQgFACgEAEQgDADgBAEIgDANIAAAXIAAAXIADANQABAFADADQAEAEAFACQAFACAGAAQALAAAHgHQAGgGACgJIAfAAQgDAQgIALQgIALgMAFQgMAGgOAAQgNAAgLgEgAttBJQgLgFgIgLQgIgLgDgQIAeAAQACAKAHAGQAGAGAMABQAGAAAFgDQAFgCAEgEIAEgGQACgEAAgGIACgPIgxAAIAAgaIAwAAIgBgPIgCgJIgEgGQgEgEgFgDQgFgCgGAAQgLAAgHAGQgHAHgCAJIgeAAQADgQAHgLQAIgKAMgGQAMgFAPAAQANAAAKAEQALAEAIAJQAIAHADAKQADAJABALQABALgBANQABANgBALQgBAMgDAJQgDAJgIAIQgIAIgLAFQgKAEgNAAQgPAAgMgGgANuBOIAAg7IgZAAIgaA7IgkAAIAghBQgMgGgHgKQgHgLAAgPQAAgOAGgLQAHgLALgGQAMgGAPAAIA8AAIAACbgANBgtQgGAGAAAKQAAAKAGAGQAGAGAKAAIAdAAIAAgrIgdAAQgKAAgGAFgALwBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgALeAYIgTg3IgTA3IAmAAgAJUBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAF3BOIAAibIAfAAIAAA7IAfAAQAPAAALAGQAMAGAGAKQAGALAAAOQAAAPgGAKQgGALgMAGQgLAHgPAAgAGWAzIAcAAQALgBAGgFQAGgGAAgKQAAgKgGgFQgGgGgLAAIgcAAgAE1BOIAAiAIgmAAIAAAtQAAAYgDAQQgDAQgGAKQgGAJgJAEQgJAEgMAAIgMAAIAAgbIAEAAQAGAAAFgDQAFgCAEgGQADgGACgMQACgLAAgRIAAhHIBhAAIAACbgACvBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgACdAYIgTg3IgTA3IAmAAgAATBOIAAhaIgdA6IgUAAIgeg6IAABaIgfAAIAAibIAeAAIApBTIAohTIAeAAIAACbgAjfBOIAAibIBnAAIAAAbIhJAAIAAAlIA+AAIAAAaIg+AAIAAAmIBJAAIAAAbgAlpBOIAAibIA9AAQAPAAAMAGQALAGAHALQAGALAAAOQAAAPgGALQgHAKgLAGQgMAGgPAAIgeAAIAAA7gAlKgHIAcAAQALAAAGgGQAGgGAAgKQAAgJgGgGQgGgGgLAAIgcAAgAnIBOIAAiAIgpAAIAAgbIBwAAIAAAbIgpAAIAACAgAqkBOIg3hRIAABRIgeAAIAAibIAeAAIAABKIAzhKIAkAAIg0BJIA5BSg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2a, new cjs.Rectangle(-90.8,-7.9,181.6,15.9), null);


(lib.s3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.p3b();
	this.instance.parent = this;
	this.instance.setTransform(6,-60);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.s3, new cjs.Rectangle(6,-60,131,220), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AAiBEIgGgQIg3AAIgGAQIg5AAIA6iHIBBAAIA6CHgAAQATIgQgtIAAAAIgPAtIAfAAg");
	this.shape.setTransform(77.4,-1.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1D1E1C").s().p("AgaBEIAAhlIgyAAIAAgiICZAAIAAAiIgyAAIAABlg");
	this.shape_1.setTransform(52.4,-1.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1D1E1C").s().p("AAeBEIAAg2Ig7AAIAAA2Ig2AAIAAiHIA2AAIAAAvIA7AAIAAgvIA2AAIAACHg");
	this.shape_2.setTransform(25.5,-1.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1D1E1C").s().p("Ag9A7QgUgNAAggIAAhTIA2AAIAABRQAAAXAbAAQAcAAAAgXIAAhRIA2AAIAABTQAAAggUANQgTAMgrgBQgqABgTgMg");
	this.shape_3.setTransform(-3,-1.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1D1E1C").s().p("AhEBEIAAiHIA2AAIAABiIBTAAIAAAlg");
	this.shape_4.setTransform(-28.7,-1.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhNBBIAkhjQAEgLAMgJQANgLALABIgkBoIBzAAQgCAIgKAIQgNAJgRAAg");
	this.shape_5.setTransform(-67,-1.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0D7ABD").s().p("AiGCGQg3g3AAhPQAAhOA3g4QA4g3BOAAQBPAAA4A3QA3A4AABOQAABPg3A3Qg4A4hPAAQhOAAg4g4g");
	this.shape_6.setTransform(-67.4,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAiBEIgGgQIg3AAIgGAQIg5AAIA6iHIBBAAIA6CHgAAQATIgQgtIAAAAIgPAtIAfAAg");
	this.shape_7.setTransform(77.4,-1.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgaBEIAAhlIgyAAIAAgiICZAAIAAAiIgyAAIAABlg");
	this.shape_8.setTransform(52.4,-1.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAeBEIAAg2Ig7AAIAAA2Ig2AAIAAiHIA2AAIAAAvIA7AAIAAgvIA2AAIAACHg");
	this.shape_9.setTransform(25.5,-1.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag9A7QgUgNAAggIAAhTIA2AAIAABRQAAAXAbAAQAcAAAAgXIAAhRIA2AAIAABTQAAAggUANQgTAMgrgBQgqABgTgMg");
	this.shape_10.setTransform(-3,-1.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhEBEIAAiHIA2AAIAABiIBTAAIAAAlg");
	this.shape_11.setTransform(-28.7,-1.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiGCGQg3g3AAhPQAAhOA3g4QA4g3BOAAQBPAAA4A3QA3A4AABOQAABPg3A3Qg4A4hPAAQhOAAg4g4gAgVhCQgLAJgEALIgkBjIBxAAQARAAANgJQAKgIABgIIhyAAIAjhoIgCAAQgKAAgMAKg");
	this.shape_12.setTransform(-67.4,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-86.4,-19,173,38.1), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#ECF4F4","#B3CEE4"],[0,0.984],0,-157.1,0,166.1).s().p("AzhfeMAAAg+7MAnDAAAMAAAA+7g");
	this.shape.setTransform(120,200,0.96,0.993);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(0,0,240,400), null);


(lib.bbb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._4b();
	this.instance.parent = this;
	this.instance.setTransform(110,32);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bbb, new cjs.Rectangle(110,32,273,600), null);


(lib.aaa = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._2();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.2,1.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.aaa, new cjs.Rectangle(0,0,441.6,600), null);


(lib.s4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bbb();
	this.instance.parent = this;
	this.instance.setTransform(158.5,219,1,1,0,0,0,267.5,250);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:8.5},89).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,1,273,600);


(lib.s2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa();
	this.instance.parent = this;
	this.instance.setTransform(184,190,1,1,0,0,0,184,250);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:4},100).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-60,441.6,600);


(lib.s1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.tyu();
	this.instance.parent = this;
	this.instance.setTransform(116.5,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:34.5},79).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20.5,0,254,600);


(lib.legal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhQExIAAhBIAGAAIAAAGIADgDIACgCIADgBIAFAAQAIAAAEAFQAEAGAAAMQAAALgEAGQgFAFgHAAIgFAAIgDgBIgCgCIgDgCIAAAZgAhHD6QgDAEAAAJQAAAIADAFQACAEAHAAQAFAAADgEQADgFAAgIQAAgJgDgEQgDgEgGAAQgFAAgDAEgAntExIAAhBIAGAAIAAAGIADgDIACgCIADgBIAFAAQAIAAAEAFQAEAGAAAMQAAALgEAGQgFAFgHAAIgFAAIgDgBIgCgCIgDgCIAAAZgAnkD6QgDAEAAAJQAAAIADAFQACAEAHAAQAFAAADgEQACgFAAgIQAAgJgCgEQgDgEgGAAQgFAAgDAEgAG+EcIgFgDIgDgEIgBgFQAAgGAFgDQADgDAIgBIANAAIAAgEQAAgFgDgCQgCgCgGAAIgHABQgCABgCADIgEgEQACgEAEgCQADgBAGAAQAJAAAFAEQADADAAAIIAAAeIgGAAIAAgFQgCADgDABIgIABIgHgBgAG+EKQgCACAAAEQAAAEACACQADACAFAAIAGgBQACAAACgCIABgDIABgFIAAgFIgMAAQgFAAgDACgAE/EcIgFgDIgEgFIgBgHIAAgdIAHAAIAAAcQAAAGADADQADADAFAAQAFAAADgDQADgDAAgGIAAgcIAGAAIAAAtIgGAAIAAgFQgCADgDABQgEABgDAAIgHgBgAgdEXQgFgFAAgMQABgKAEgGQAFgGAJAAQAIAAAEAGQAFAFAAAKIAAADIgdAAIAAAFIABADQABAEADACQADACAFAAIADgBIADAAIACgCIADgCIAEADIgDAEIgEACIgDABIgGAAQgJAAgFgGgAgEEDIgBgDIAAgCQgBgEgDgCQgDgCgDgBIgHACQgDACgBADIgBADIAAAEIAXAAIAAAAgAh3EcQgEgBgCgDIgEgHIgBgKIABgLQACgEACgDIAGgEQADgBAEAAIAHABIAGAEQADADAAAEQACAEAAAGQAAAHgCAEQAAAEgDADQgDADgDABIgHABQgEAAgDgBgAh0D3IgEACQgCACgBADIgBAJIABAIIADAFIAEADIAEABIAFgBIADgDQACgCAAgDIABgIIgBgJQAAgDgCgCIgDgCIgFgBIgEABgAjJEdQgIAAgEgDQgEgDAAgHQAAgGAEgDQAEgEAHAAIAOAAIAAgEQAAgFgDgCQgDgCgGAAIgEAAIgCABIgDABIgCADIgEgEIADgDIACgCIAFgCIAFAAQAJAAAFAEQAEADAAAIIAAAeIgGAAIAAgFIgDADIgDABIgCABIgFAAgAjQEKQgCACgBAEQABAEACACQACACAGAAQAGAAADgDQADgCAAgGIAAgFIgNAAQgFAAgCACgAj+EcQgEgCgEgDIAEgEIAGAEIAHABIAFgBIAEgDQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAQAAgEgDgCQgCgBgEAAIgGAAIAAgGIAGAAQAEAAACgCQADgBAAgEQgBgDgDgCQgCgCgFAAIgGABIgGADIgDgEQADgDAFgBQAEgBAEAAQAEAAAEABQADACACACQACADAAAEQABADgCADQgCADgEABQAEABACADQACACAAAEQAAAEgCADQgDADgDACQgEABgFAAQgFAAgEgBgAmKEdQgIAAgFgDQgEgDAAgHQAAgGAEgDQAFgEAHAAIANAAIAAgEQABgFgDgCQgEgCgFAAIgEAAIgDABIgCABIgCADIgFgEIADgDIADgCIAEgCIAGAAQAJAAAEAEQAEADABAIIAAAeIgHAAIAAgFIgCADIgDABIgDABIgEAAgAmSEKQgCACAAAEQAAAEACACQADACAGAAQAGAAADgDQADgCgBgGIAAgFIgMAAQgFAAgDACgAoUEcQgDgBgDgDIgEgHIgBgKIABgLQABgEADgDIAGgEQADgBAEAAIAHABIAGAEQACADABAEQACAEAAAGQAAAHgCAEQgBAEgCADQgDADgDABIgHABQgEAAgDgBgAoRD3IgEACQgCACgBADIgBAJIABAIIADAFIAEADIAEABIAFgBIADgDQACgCAAgDIACgIIgCgJQAAgDgCgCIgDgCIgFgBIgEABgAIeEdIAAgtIAGAAIAAAtgAIDEdIAAgnIgGAAIAAgFIAGAAIAAgJIABgGQABgCACgCQADgBADAAIAGAAIAAAFIgEAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABQgCACAAADIAAAIIAKAAIAAAFIgKAAIAAAngAHpEdIAAgJIAIAAIAAAJgAGoEdQgFAAgCgCQgDgBAAgDQgCgDAAgDIAAgbIgFAAIAAgFIAFAAIAAgOIAGAAIAAAOIAKAAIAAAFIgKAAIAAAbQAAAAABABQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAAAABABQAAAAABAAQABAAABAAIADAAIAAAGgAGFEdIAAgcQAAgFgDgDQgDgDgFAAQgFAAgDADQgDADAAAFIAAAcIgGAAIAAhAIAGAAIAAAYIAFgEIAIgBQAHAAAEAEQAFAFAAAHIAAAdgAEmEdQgFAAgDgEQgCgDgBgFIAAg0IAHAAIAAA0IABAFQACABADAAIADAAIAAAGgAEDEdIAAgJIAIAAIAAAJgADmEdIgLgjIgMAjIgGAAIgOgtIAHAAIAKAkIAMgkIAFAAIAMAkIAKgkIAHAAIgOAtgAClEdIgLgjIgMAjIgGAAIgOgtIAHAAIAKAkIAMgkIAFAAIAMAkIAKgkIAHAAIgOAtgABkEdIgLgjIgMAjIgGAAIgOgtIAHAAIAKAkIAMgkIAGAAIALAkIAKgkIAHAAIgOAtgAASEdIAAgJIAIAAIAAAJgAieEdIAAgnIgPAAIAAgGIAkAAIAAAGIgOAAIAAAngAkXEdIAAgjIgYAjIgGAAIAAgtIAGAAIAAAjIAYgjIAGAAIAAAtgAlLEdIAAgUIgWAAIAAAUIgGAAIAAgtIAGAAIAAATIAWAAIAAgTIAGAAIAAAtgAm8EdIAAgtIAcAAIAAAGIgWAAIAAAngAASECIAAgJIAIAAIAAAJgAIeDkIAAgHIAHAAIAAAHgAiDDIIAAhBIAHAAIAAAGIACgDIACgCIAEgBIAEAAQAIAAAFAFQADAGAAAMQAAALgDAGQgFAFgIAAIgEAAIgEgBIgCgCIgCgCIAAAZgAh6CRQgDAEABAJQgBAIADAFQADAEAGAAQAFAAADgEQADgFAAgIQAAgJgDgEQgDgEgGAAQgFAAgDAEgAm7DIIAAhBIAGAAIAAAGIADgDIADgCIADgBIAEAAQAJAAAEAFQADAGAAAMQAAALgDAGQgFAFgIAAIgEAAIgDgBIgDgCIgDgCIAAAZgAmyCRQgCAEgBAJQABAIACAFQADAEAGAAQAFAAADgEQADgFAAgIQAAgJgDgEQgCgEgHAAQgFAAgDAEgABdDBIAAgNIghAAIAAANIgGAAIAAgTIAFAAIAEgHIACgKIAAgNIAAgJIAcAAIAAAnIAHAAIAAATgABICVIgBALIgCAHIgDAHIAUAAIAAghIgOAAgAk6DBIAAgNIghAAIAAANIgGAAIAAgTIAFAAIADgHIADgKIAAgNIAAgJIAcAAIAAAnIAGAAIAAATgAlQCVIgBALIgBAHIgCAHIATAAIAAghIgPAAgAHHCuQgFgFAAgMQAAgKAFgGQAFgGAJAAQAIAAAEAGQAGAFAAAKIAAADIgfAAIABAFIABADQABAEADACQADACAFAAIADgBIADAAIADgCIACgCIAFADIgEAEIgEACIgEABIgEAAQgKAAgFgGgAHgCaIgBgDIAAgCQgBgEgDgCQgCgCgEgBIgHACQgDACgBADIgBADIgBAEIAYAAIAAAAgAGXCuQgEgFgBgMQABgKAEgGQAFgGAJAAQAJAAAEAGQAFAFAAAKIAAADIgeAAIAAAFIABADQACAEADACQADACAFAAIACgBIADAAIADgCIADgCIAEADIgEAEIgDACIgEABIgFAAQgKAAgFgGgAGxCaIgBgDIAAgCQgCgEgDgCQgCgCgEgBIgGACQgDACgCADIgBADIAAAEIAYAAIAAAAgABxCuQgFgFAAgMQAAgKAFgGQAFgGAJAAQAIAAAEAGQAGAFAAAKIAAADIgfAAIABAFIABADQABAEADACQADACAFAAIADgBIADAAIADgCIACgCIAFADIgEAEIgEACIgEABIgEAAQgKAAgFgGgACKCaIgBgDIAAgCQgBgEgDgCQgCgCgEgBIgHACQgDACgBADIgBADIgBAEIAYAAIAAAAgAAPCuQgEgFAAgMQAAgKAEgGQAGgGAIAAQAJAAAEAGQAFAFAAAKIAAADIgeAAIABAFIABADQABAEADACQADACAEAAIADgBIADAAIADgCIADgCIAEADIgEAEIgDACIgEABIgFAAQgJAAgGgGgAAoCaIAAgDIgBgCQgBgEgCgCQgDgCgEgBIgHACQgCACgBADIgBADIgBAEIAXAAIAAAAgAhJCzQgDgBgDgDIgEgHIgBgKIABgLQABgEADgDIAGgEQADgBAEAAIAHABIAGAEQACADABAEQACAEAAAGQAAAHgCAEQgBAEgCADQgDADgDABIgHABQgEAAgDgBgAhGCOIgEACQgCACgBADIgBAJIABAIIADAFIAEADIAEABIAFgBIADgDQACgCAAgDIACgIIgCgJQAAgDgCgCIgDgCIgFgBIgEABgAj5CuQgFgFAAgMQABgKAEgGQAFgGAIAAQAJAAAFAGQAEAFAAAKIAAADIgeAAIABAFIABADQACAEADACQADACAEAAIADgBIACAAIAEgCIADgCIADADIgDAEIgEACIgEABIgEAAQgKAAgFgGgAjgCaIAAgDIgBgCQgBgEgDgCQgDgCgEgBIgGACQgCACgCADIgBADIgBAEIAYAAIAAAAgAniCzQgDgBgDgDIgDgHIgBgKIABgLQABgEACgDIAGgEQAEgBAEAAIAHABIAFAEQADADABAEQABAEABAGQgBAHgBAEQgBAEgDADQgCADgDABIgHABQgEAAgEgBgAnfCOIgEACQgBACgBADIgBAJIABAIIACAFIAEADIAFABIAEgBIAEgDQACgCAAgDIABgIIgBgJQAAgDgCgCIgEgCIgEgBIgFABgAFoC0IAAgjIgXAjIgHAAIAAgtIAHAAIAAAjIAXgjIAGAAIAAAtgAEdC0IAAgSIgLAAIgJASIgIAAIALgSQgFgBgCgEQgEgDAAgFQAAgGAFgEQADgDAHgBIATAAIAAAtgAEKCPQgCACAAAEQAAAEACACQACACAFAAIAMAAIAAgQIgMAAQgFAAgCACgADuC0IAAgjIgXAjIgGAAIAAgtIAGAAIAAAjIAXgjIAHAAIAAAtgAC6C0IAAgUIgWAAIAAAUIgGAAIAAgtIAGAAIAAATIAWAAIAAgTIAGAAIAAAtgAgiC0IAAgtIAUAAQAGABADADQAEADAAAFQAAAEgCACQgCADgDABQAEABACADQACACAAAEQAAAGgEADQgDAEgGAAgAgcCuIANAAQAFAAACgCQACgCAAgDQAAgDgCgCQgCgCgFAAIgNAAgAgcCaIANAAQAEAAACgBQACgCAAgDQAAgEgCgBQgCgCgEAAIgNAAgAiZC0IAAgnIgWAAIAAAnIgHAAIAAgtIAjAAIAAAtgAkMC0IgWgXIAUgWIAIAAIgUAVIAWAYgAkoC0IAAgtIAGAAIAAAWIAAAXgAlxC0IAAgSIgLAAIgKASIgHAAIALgSQgFgBgDgEQgDgDAAgFQAAgGAEgEQAEgDAGgBIAUAAIAAAtgAmECPQgCACgBAEQABAEACACQACACAEAAIANAAIAAgQIgNAAQgEAAgCACgAoBC0IAAgnIgWAAIAAAnIgGAAIAAgtIAiAAIAAAtgAkiCdgAHbB+IAAgIIAGAAIAAAIgAHIB+IAAgIIAGAAIAAAIgAlJBfIAAhBIAHAAIAAAGIACgDIACgCIAEgBIAEAAQAIAAAFAFQAEAGAAAMQAAALgEAGQgFAFgIAAIgEAAIgEgBIgCgCIgCgCIAAAZgAlAAoQgDAEABAJQgBAIADAFQADAEAGAAQAFAAADgEQADgFAAgIQAAgJgDgEQgDgEgGAAQgFAAgDAEgAmjBfIAAgUQgKAAgGgGQgGgGAAgKQAAgLAGgGQAFgGALAAIAAgTIAHAAIAAATQAKAAAHAGQAFAGAAALQAAAKgGAGQgFAGgLAAIAAAUgAmcBGQAHgBAEgEQAEgFABgHQAAgFgCgEQgBgEgEgCQgEgCgFAAgAmsAmQgEACgBAEQgCAEAAAFQAAAHAFAFQAEAEAHABIAAgiQgFAAgEACgAByBeIAAgGIACAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIADgFIAEgIIgRgsIAIAAIALAkIAMgkIAHAAIgTA3QgCAFgDACQgCACgFAAgAHpBDIAIAAIAAAOIgIAHgAiLBYIAAgNIgjAAIAAgtIAHAAIAAAnIAVAAIAAgnIAHAAIAAAnIAHAAIAAATgAEEBKQgEgBgCgDIgFgHIgBgKIABgLQACgEADgDIAGgEQADgBADAAIAHABIAGAEQADADABAEQABAEAAAGQAAAHgBAEQgBAEgDADQgDADgDABIgHABQgDAAgDgBgAEGAlIgEACQgCACgBADIgBAJIABAIIADAFIAEADIAEABIAFgBIADgDQACgCABgDIABgIIgBgJQgBgDgCgCIgDgCIgFgBIgEABgAChBFQgGgGAAgKQAAgLAGgGQAEgGAKAAIAEAAIADABIADACIAFAEIgFAEIgDgDIgCgBIgDgBIgCAAQgHAAgDAEQgEAEABAJQgBAIAEAEQADAFAHAAIACgBIADAAIACgCIADgCIAFAEIgFADIgDACIgDABIgEAAQgKAAgEgGgAA1BIQgEgDgCgFIgBgGIAAgHIAAgHIAAgLIABgHIABgGIADgEQAEgDAEgBIAJgBIAKgBIAAAGIgHABIgIABQgEAAgDADQgDACgBAEQgBAEAAAGQACgDADgCQAEgCAFAAIAGABIAEADQADADACAFQABAEABAHQgBAGgBAEQgBAFgDACIgFAEIgHABQgHAAgEgDgAA7AlIgDACQgCACgBADIgBAJIABAIIADAFIADADIAFABIAEgBIAEgDQABgCABgDIABgIIgBgJQgBgDgBgCIgEgCIgEgBIgFABgAAJBKQgEgBgDgDIgCgHIgCgKIACgLQAAgEACgDIAHgEQADgBADAAIAHABIAGAEQADADABAEQABAEAAAGQAAAHgBAEQgBAEgDADQgDADgDABIgHABQgDAAgDgBgAALAlIgDACQgDACgBADIgBAJIABAIIAEAFIADADIAEABIAFgBIADgDQACgCABgDIABgIIgBgJQgBgDgCgCIgDgCIgFgBIgEABgAjRBLQgIAAgEgDQgDgDAAgHQAAgGADgDQAEgEAIAAIANAAIAAgEQAAgFgCgCQgEgCgFAAIgEAAIgDABIgCABIgDADIgDgEIACgDIADgCIAEgCIAGAAQAIAAAFAEQAFADAAAIIAAAeIgHAAIAAgFIgCADIgDABIgDABIgFAAgAjXA4QgDACAAAEQAAAEADACQACACAGAAQAGAAADgDQACgCAAgGIAAgFIgMAAQgFAAgCACgAlvBKQgEgBgDgDIgDgHIgBgKIABgLQABgEACgDIAHgEQACgBAFAAIAGABIAGAEQADADABAEQACAEAAAGQAAAHgCAEQgBAEgDADQgCADgEABIgGABQgFAAgCgBgAltAlIgDACQgCACgCADIgBAJIABAIIAEAFIADADIAFABIAEgBIADgDQADgCAAgDIABgIIgBgJQAAgDgDgCIgDgCIgEgBIgFABgAHWBLIgKgRIgLARIgIAAIAPgXIgOgWIAIAAIAKARIAKgRIAIAAIgPAWIAPAXgAGoBLIAAgSIgLAAIgKASIgHAAIAKgSQgFgBgCgEQgDgDAAgFQAAgGADgEQAEgDAGgBIAUAAIAAAtgAGVAmQgDACAAAEQAAAEADACQACACAEAAIANAAIAAgQIgNAAQgEAAgCACgAF4BLIAAgjIgXAjIgHAAIAAgtIAHAAIAAAjIAXgjIAGAAIAAAtgAEqBLIAAgtIAUAAQAGABAEADQAEADAAAFQAAAEgCACQgCADgDABQADABACADQADACAAAEQAAAGgEADQgDAEgHAAgAExBFIANAAQAEAAACgCQACgCAAgDQAAgDgCgCQgCgCgEAAIgNAAgAExAxIAMAAQAFAAACgBQACgCAAgDQAAgEgCgBQgCgCgFAAIgMAAgADkBLIAAgnIgQAAIAAAPQAAAKgCAFQgBAFgDACQgEACgDAAIgEAAIAAgGIACAAIADAAIADgDIADgGIAAgLIAAgTIAdAAIAAAtgAgsBLIAAgSIgMAAIgJASIgHAAIAKgSQgFgBgCgEQgDgDAAgFQAAgGADgEQAEgDAGgBIAUAAIAAAtgAg/AmQgDACAAAEQAAAEADACQABACAFAAIANAAIAAgQIgNAAQgFAAgBACgAhcBLIAAgjIgXAjIgHAAIAAgtIAHAAIAAAjIAXgjIAGAAIAAAtgAjzBLIAAggIgNAZIgFAAIgNgZIAAAgIgGAAIAAgtIAGAAIAQAeIAPgeIAGAAIAAAtgAnNBLIAAgUIgWAAIAAAUIgGAAIAAgtIAGAAIAAATIAWAAIAAgTIAGAAIAAAtgAn/BLIAAgjIgYAjIgGAAIAAgtIAGAAIAAAjIAYgjIAGAAIAAAtgAEOgJIAAhBIAGAAIAAAGIADgDIACgCIADgBIAFAAQAIAAAEAFQAEAGAAAMQAAALgEAGQgFAFgHAAIgFAAIgDgBIgCgCIgDgCIAAAZgAEXhAQgDAEAAAJQAAAIADAFQACAEAHAAQAFAAADgEQADgFAAgIQAAgJgDgEQgDgEgGAAQgFAAgDAEgAkvgJIAAhBIAHAAIAAAGIACgDIACgCIAEgBIAEAAQAIAAAEAFQAFAGAAAMQAAALgFAGQgEAFgIAAIgEAAIgEgBIgBgCIgDgCIAAAZgAkmhAQgCAEAAAJQAAAIACAFQADAEAGAAQAGAAACgEQADgFAAgIQAAgJgDgEQgDgEgFAAQgGAAgDAEgAD8gQIAAgNIghAAIAAANIgGAAIAAgTIAGAAIACgHIADgKIAAgNIAAgJIAcAAIAAAnIAGAAIAAATgADmg8IgBALIgBAHIgCAHIATAAIAAghIgPAAgAn9gQIAAgNIggAAIAAANIgGAAIAAgTIAFAAIADgHIACgKIAAgNIAAgJIAcAAIAAAnIAHAAIAAATgAoSg8IgBALIgCAHIgCAHIAUAAIAAghIgPAAgAHdgdQgIAAgEgDQgEgDAAgHQAAgGAEgDQAEgEAIAAIAMAAIAAgEQABgFgDgCQgDgCgGAAIgEAAIgDABIgBABIgDADIgEgEIACgDIAEgCIADgCIAHAAQAIAAAEAEQAFADAAAIIAAAeIgHAAIAAgFIgCADIgCABIgEABIgEAAgAHWgwQgCACAAAEQAAAEACACQADACAFAAQAHAAACgDQADgCgBgGIAAgFIgLAAQgFAAgDACgAF0ggQgEgDgCgFIgBgGIgBgHIAAgHIAAgLIABgHIADgGIADgEQADgDAFgBIAJgBIAJgBIAAAGIgHABIgIABQgEAAgDADQgDACgBAEQgBAEABAGQABgDADgCQAEgCAEAAIAGABIAGADQACADACAFQACAEgBAHQABAGgCAEQgBAFgDACIgGAEIgHABQgFAAgFgDgAF6hDIgEACQgBACgBADIgBAJIAAAIIADAFIAEADIAEABIAFgBIADgDQACgCABgDIABgIIgBgJQgBgDgCgCIgDgCIgFgBIgEABgAFHgeQgDgBgDgDIgEgHIAAgKIAAgLQACgEACgDIAGgEQAEgBAEAAIAHABIAFAEQADADABAEQABAEABAGQgBAHgBAEQgBAEgDADQgCADgDABIgHABQgEAAgEgBgAFKhDIgEACQgBACgBADIgBAJIABAIIACAFIAEADIAFABIAEgBIAEgDQACgCAAgDIABgIIgBgJQAAgDgCgCIgEgCIgEgBIgFABgAC1geQgDgBgDgDIgEgHIgBgKIABgLQABgEADgDIAGgEQADgBAEAAIAHABIAFAEQADADABAEQACAEAAAGQAAAHgCAEQgBAEgDADQgCADgDABIgHABQgEAAgDgBgAC3hDIgDACQgCACgBADIgBAJIABAIIADAFIADADIAFABIAEgBIAEgDQACgCABgDIABgIIgBgJQgBgDgCgCIgEgCIgEgBIgFABgAglgfQgFgCgCgEQgDgEAAgGQABgFADgEQACgEAEgCIgGgGQgCgEAAgFQAAgFACgEQADgDAEgDQADgCAGAAQAEAAAFACQAEADACADQACAEAAAFQAAAFgCAEIgGAGQAEACACAEQAEAEAAAFQAAAGgDAEQgDAEgEACQgEACgFAAQgGAAgEgCgAgig6IgFAFQgBACAAAEQAAAEABACIAFAFIAHACIAGgCQACgCACgDQACgCAAgEQAAgEgCgCQgCgDgCgCQgDgBgDAAQgEAAgDABgAgjhVQgEADAAAFQAAAGAEADQACADAGAAQAEAAADgDQAEgDAAgGQAAgFgEgDQgDgDgEAAQgGAAgCADgAiDgfQgDgCgDgEQgCgEAAgFIAAgeQAAgGACgDQADgEADgDQAEgCAFAAQAFAAAEACQAEADADAEQACADAAAGIAAAeQAAAFgCAEQgDAEgEACQgEACgFAAQgFAAgEgCgAiChVQgDAEABAFIAAAdQgBAGADADQADADAFABQAGgBACgDQADgDAAgGIAAgdQAAgFgDgEQgCgDgGAAQgFAAgDADgAlZggQgEgDgCgFIgBgGIgBgHIAAgHIAAgLIACgHIACgGIACgEQAEgDAFgBIAIgBIAKgBIAAAGIgHABIgIABQgEAAgDADQgDACgBAEQgBAEAAAGQACgDAEgCQADgCAFAAIAFABIAGADQADADABAFQABAEAAAHQAAAGgBAEQgBAFgDACIgGAEIgHABQgGAAgEgDgAlThDIgDACQgDACAAADIgBAJIAAAIIAEAFIADADIAEABIAFgBIADgDQACgCABgDIABgIIgBgJQgBgDgCgCIgDgCIgFgBIgEABgAmCgdQgIAAgEgDQgEgDAAgHQAAgGAEgDQAEgEAIAAIAMAAIAAgEQABgFgDgCQgDgCgGAAIgEAAIgDABIgBABIgDADIgEgEIACgDIAEgCIADgCIAHAAQAIAAAEAEQAFADAAAIIAAAeIgHAAIAAgFIgCADIgCABIgEABIgEAAgAmJgwQgCACAAAEQAAAEACACQADACAFAAQAHAAACgDQADgCgBgGIAAgFIgLAAQgFAAgDACgAnpgjQgEgFAAgMQAAgKAEgGQAGgGAIAAQAIAAAFAGQAFAFAAAKIAAADIgeAAIABAFIABADQABAEADACQADACAEAAIADgBIADAAIADgCIADgCIAEADIgEAEIgDACIgEABIgFAAQgJAAgGgGgAnQg3IAAgDIgBgCQAAgEgDgCQgDgCgEgBIgHACQgCACgBADIgBADIgBAEIAXAAIAAAAgAIZgdIAAgSIgLAAIgKASIgHAAIAKgSQgFgBgCgEQgDgDAAgFQAAgGAEgEQADgDAHgBIAUAAIAAAtgAIGhCQgCACgBAEQABAEACACQACACAFAAIAMAAIAAgQIgMAAQgFAAgCACgAG6gdIAAgUIgWAAIAAAUIgGAAIAAgtIAGAAIAAATIAWAAIAAgTIAHAAIAAAtgACUgdIAAg6IgeAAIAAA6IgHAAIAAhAIAsAAIAABAgAA/gdIAAgJIAJAAIAAAJgAAagdIAAgtIAcAAIAAAGIgWAAIAAAngAhLgdIAAg5IgMAKIAAgHIAMgKIAGAAIAABAgAi6gdIAAgGIAaggQACgCAAgDIABgFQAAgFgDgDQgDgDgFAAQgDAAgDABQgCABgBADQgCACAAAFIgHAAQAAgGACgDQADgEAEgDQADgCAGAAQAFAAAEACQAEACACAEQACAEABAFIgBAHIgFAGIgWAdIAcAAIAAAGgAjlgdIAAgSIgLAAIgJASIgIAAIAKgSQgEgBgDgEQgDgDAAgFQAAgGAEgEQAEgDAGgBIAUAAIAAAtgAj4hCQgDACABAEQgBAEADACQACACAFAAIAMAAIAAgQIgMAAQgFAAgCACgAmggdIgVgXIAUgWIAIAAIgUAVIAWAYgAm7gdIAAgtIAGAAIAAAWIAAAXgABphyIAAhBIAHAAIAAAGIACgDIADgCIADgBIAFAAQAIAAAEAFQAEAGAAAMQAAALgEAGQgFAFgHAAIgFAAIgDgBIgCgCIgDgCIAAAZgAByipQgCAEAAAJQAAAIACAFQAEAEAFAAQAGAAACgEQAEgFAAgIQAAgJgEgEQgCgEgGAAQgGAAgDAEgAmdh5IAAgNIgjAAIAAgtIAGAAIAAAnIAWAAIAAgnIAGAAIAAAnIAGAAIAAATgAFfiIQgEgCgCgEQgCgFAAgFIABgHIADgIIAPgfIAIAAIgPAcIAHgBQAFAAAEACQADADADAEQACAEAAAFQgBAGgCAEQgCAEgEADQgEACgFAAQgGAAgEgCgAFhiiQgDAEAAAGQAAAFADAEQACADAGABQAFgBADgDQADgEAAgFQAAgEgBgDQgCgDgCgCQgCgBgEAAQgGAAgCADgAEciHQgDgBgDgDIgEgHIgBgKIABgLQACgEACgDIAGgEQADgBAEAAIAHABIAFAEQAEADABAEQABAEAAAGQAAAHgBAEQgBAEgEADQgCADgDABIgHABQgEAAgDgBgAEfisIgEACQgCACgBADIgBAJIABAIIADAFIAEADIAEABIAFgBIADgDQACgCAAgDIABgIIgBgJQAAgDgCgCIgDgCIgFgBIgEABgABAiJQgFgDgCgFIgBgGIAAgHIAAgHIAAgLIABgHIACgGIADgEQADgDAFgBIAJgBIAKgBIAAAGIgHABIgIABQgEAAgEADQgCACgBAEQgBAEAAAGQABgDAEgCQADgCAFAAIAGABIAFADQADADACAFQABAEAAAHQAAAGgBAEQgBAFgEACIgFAEIgHABQgGAAgEgDgABFisIgDACQgCACAAADIgBAJIAAAIIADAFIADADIAFABIAEgBIAEgDQACgCAAgDIABgIIgBgJQAAgDgCgCIgEgCIgEgBIgFABgAgbiHQgEgBgCgDIgFgHIgBgKIABgLQACgEADgDIAGgEQADgBADAAIAHABIAGAEQADADABAEQABAEAAAGQAAAHgBAEQgBAEgDADQgDADgDABIgHABQgDAAgDgBgAgZisIgEACQgCACgBADIAAAJIAAAIIADAFIAEADIAEABIAFgBIADgDQACgCABgDIABgIIgBgJQgBgDgCgCIgDgCIgFgBIgEABgAkLiMQgFgGgBgKQABgLAFgGQAFgGAKAAIADAAIAEABIADACIAEAEIgEAEIgEgDIgCgBIgCgBIgCAAQgHAAgEAEQgDAEAAAJQAAAIADAEQAEAFAHAAIACgBIACAAIACgCIAEgCIAEAEIgEADIgDACIgEABIgDAAQgKAAgFgGgAoQiGQgJAAgDgDQgFgDAAgHQAAgGAFgDQAEgEAHAAIANAAIAAgEQAAgFgDgCQgDgCgGAAIgDAAIgDABIgCABIgCADIgFgEIADgDIADgCIAEgCIAGAAQAIAAAFAEQAEADAAAIIAAAeIgGAAIAAgFIgDADIgCABIgDABIgEAAgAoYiZQgCACAAAEQAAAEACACQADACAFAAQAHAAACgDQADgCAAgGIAAgFIgMAAQgFAAgDACgAD9iGIAAgnIgWAAIAAAnIgGAAIAAgtIAiAAIAAAtgAC0iGIAAgSIgMAAIgJASIgHAAIAKgSQgFgBgCgEQgDgDAAgFQAAgGADgEQAEgDAGgBIAUAAIAAAtgAChirQgDACAAAEQAAAEADACQABACAFAAIANAAIAAgQIgNAAQgFAAgBACgAAjiGIAAgSIgLAAIgKASIgHAAIALgSQgFgBgDgEQgDgDAAgFQAAgGAEgEQAEgDAGgBIAUAAIAAAtgAAQirQgCACgBAEQABAEACACQACACAEAAIANAAIAAgQIgNAAQgEAAgCACgAg7iGIAAgUIgVAAIAAAUIgHAAIAAgtIAHAAIAAATIAVAAIAAgTIAHAAIAAAtgAiXiGIAWg7IgWAAIAAAKIgHAAIAAgPIAkAAIAAAFIgWA7gAjNiGIAAgGIAZggQACgCABgDIAAgFQABgFgDgDQgEgDgEAAQgDAAgDABQgDABgBADQgCACAAAFIgGAAQAAgGACgDQACgEAEgDQAEgCAGAAQAEAAAFACQADACACAEQADAEAAAFIgBAHIgEAGIgWAdIAbAAIAAAGgAk7iGIAAgjIgXAjIgHAAIAAgtIAHAAIAAAjIAXgjIAGAAIAAAtgAlviGIAAgjIgXAjIgGAAIAAgtIAGAAIAAAjIAXgjIAHAAIAAAtgAnRiGIgVgXIATgWIAIAAIgUAVIAWAYgAntiGIAAgtIAHAAIAAAWIAAAXgAnmidgAB7jbIAAhBIAGAAIAAAGIADgDIADgCIADgBIAEAAQAJAAAEAFQADAGAAAMQAAALgDAGQgFAFgIAAIgEAAIgDgBIgDgCIgDgCIAAAZgACEkSQgCAEgBAJQABAIACAFQADAEAGAAQAFAAADgEQADgFAAgIQAAgJgDgEQgCgEgHAAQgFAAgDAEgAiOjbIAAhBIAGAAIAAAGIADgDIACgCIADgBIAFAAQAIAAAEAFQAEAGAAAMQAAALgEAGQgFAFgHAAIgFAAIgDgBIgCgCIgDgCIAAAZgAiFkSQgDAEAAAJQAAAIADAFQACAEAHAAQAFAAADgEQACgFAAgIQAAgJgCgEQgDgEgGAAQgFAAgDAEgAFcjiIAAgNIggAAIAAANIgHAAIAAgTIAGAAIACgHIACgKIABgNIAAgJIAcAAIAAAnIAGAAIAAATgAFGkOIAAALIgCAHIgDAHIAVAAIAAghIgQAAgAlsjiIAAgNIgjAAIAAgtIAHAAIAAAnIAVAAIAAgnIAHAAIAAAnIAHAAIAAATgAFwj1QgFgFAAgMQABgKAEgGQAFgGAIAAQAJAAAFAGQAEAFAAAKIAAADIgdAAIAAAFIABADQACAEACACQADACAFAAIADgBIADAAIACgCIAEgCIAEADIgEAEIgEACIgDABIgGAAQgJAAgFgGgAGJkJIgBgDIAAgCQgBgEgDgCQgDgCgEgBIgGACQgCACgCADIgBADIAAAEIAXAAIAAAAgAEPj1QgGgFAAgMQABgKAFgGQAEgGAJAAQAIAAAFAGQAFAFAAAKIAAADIgeAAIAAAFIABADQACAEADACQADACAEAAIAEgBIACAAIADgCIADgCIAEADIgDAEIgFACIgDABIgFAAQgKAAgEgGgAEokJIgBgDIgBgCQgBgEgDgCQgCgCgEgBIgGACQgDACgCADIgBADIAAAEIAYAAIAAAAgAC1jwQgDgBgDgDIgEgHIgBgKIABgLQABgEADgDIAGgEQADgBAEAAIAHABIAFAEQADADABAEQACAEAAAGQAAAHgCAEQgBAEgDADQgCADgDABIgHABQgEAAgDgBgAC3kVIgDACQgCACgBADIgBAJIABAIIADAFIADADIAFABIAEgBIAEgDQACgCABgDIABgIIgBgJQgBgDgCgCIgEgCIgEgBIgFABgAhVjwQgDgBgCgDIgFgHIgBgKIABgLQACgEADgDIAFgEQADgBAFAAIAHABIAFAEQADADABAEQABAEAAAGQAAAHgBAEQgBAEgDADQgCADgDABIgHABQgFAAgDgBgAhSkVIgEACQgBACgBADIgBAJIABAIIACAFIAEADIAFABIAEgBIAEgDQACgCAAgDIABgIIgBgJQAAgDgCgCIgEgCIgEgBIgFABgAi7jwQgFgCgDgDQgDgDgCgEIgBgIIAAgLIAAgMIABgIQACgDADgDQADgDAFgCQAEgCAEAAQAJAAAGAFQAFAFACAJIgHAAQgBgGgEgDQgDgEgHAAIgGABIgFAEIgDAEIgBAHIgBALIABAKIABAHIADAFIAFADIAGABQAHAAAEgDQADgEABgGIAHAAQgBAGgCAFQgDAEgFACQgFACgGAAQgEAAgEgBgAIdjvIAAgSIgLAAIgKASIgHAAIAKgSQgFgBgDgEQgCgDAAgFQAAgGADgEQAEgDAGgBIAUAAIAAAtgAIKkUQgDACAAAEQAAAEADACQACACAEAAIANAAIAAgQIgNAAQgEAAgCACgAHtjvIAAgjIgXAjIgHAAIAAgtIAHAAIAAAjIAXgjIAGAAIAAAtgAG5jvIAAgUIgWAAIAAAUIgGAAIAAgtIAGAAIAAATIAWAAIAAgTIAGAAIAAAtgADbjvIAAgtIAVAAQAGABADADQAEADAAAFQAAAEgBACQgCADgEABQAEABACADQACACAAAEQAAAGgDADQgEAEgGAAgADij1IANAAQAFAAABgCQACgCAAgDQAAgDgCgCQgBgCgFAAIgNAAgADikJIANAAQAEAAACgBQACgCAAgDQAAgEgCgBQgCgCgEAAIgNAAgABljvIAAgnIgWAAIAAAnIgGAAIAAgtIAiAAIAAAtgAAcjvIAAgjIgYAjIgFAAIAAgtIAFAAIAAAjIAYgjIAGAAIAAAtgAgSjvIgVgXIATgWIAIAAIgUAVIAXAYgAgtjvIAAgtIAGAAIAAAWIAAAXgAj3jvIAAgJIAIAAIAAAJgAkNjvIAAgSIgMAAIgJASIgHAAIAKgSQgFgBgCgEQgDgDAAgFQAAgGAEgEQADgDAGgBIAUAAIAAAtgAkgkUQgDACAAAEQAAAEADACQABACAFAAIANAAIAAgQIgNAAQgFAAgBACgAk9jvIAAgjIgXAjIgHAAIAAgtIAHAAIAAAjIAXgjIAGAAIAAAtgAmgjvIgVgXIAUgWIAIAAIgUAVIAWAYgAm7jvIAAgtIAGAAIAAAWIAAAXgAnMjvIgFgPIgcAAIgFAPIgIAAIAYhAIAGAAIAXBAgAnTkEIgMgiIgMAiIAYAAgAgnkGgAm1kGgAoSkPIAAgNIgKAHIgDgFIALgGIgLgGIADgEIAKAHIAAgNIAFAAIgBANIALgHIADAEIgLAGIALAGIgDAFIgLgHIABANg");
	this.shape.setTransform(60.1,-0.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.instance = new lib.Path_1();
	this.instance.parent = this;
	this.instance.setTransform(61.1,-0.2,0.521,2.258,0,0,0,117.2,15.5);
	this.instance.alpha = 0.5;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal, new cjs.Rectangle(0,-35.2,229.9,71.7), null);


// stage content:
(lib._120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgJSguyISlAAMAAABdlIylAAg");
	this.shape.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(300));

	// logo
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(60.1,64.8,0.55,0.55,0,0,0,0.3,0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(221).to({regY:0.1,scaleX:0.63,scaleY:0.63,x:60.2,y:101},8,cjs.Ease.get(1)).wait(62).to({regX:0.2,regY:0.3,scaleX:0.52,scaleY:0.52,x:60.1,y:64.8},8,cjs.Ease.get(1)).wait(1));

	// legal
	this.instance_1 = new lib.legal();
	this.instance_1.parent = this;
	this.instance_1.setTransform(115,584.6,1,1,0,0,0,115,18.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(300));

	// 4a.jpg
	this.instance_2 = new lib.s4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(120,200,1,1,0,0,0,120,200);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(217).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(66).to({alpha:0},8,cjs.Ease.get(1)).wait(1));

	// t3b
	this.instance_3 = new lib.t3b();
	this.instance_3.parent = this;
	this.instance_3.setTransform(77.1,157.2,0.536,0.536,0,0,0,0.2,0);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(149).to({_off:false},0).wait(1).to({regX:0,x:76.7,alpha:0.019},0).wait(1).to({x:75.6,alpha:0.086},0).wait(1).to({x:73.4,alpha:0.226},0).wait(1).to({x:69.6,alpha:0.457},0).wait(1).to({x:65.5,alpha:0.716},0).wait(1).to({x:62.6,alpha:0.892},0).wait(1).to({x:61.3,alpha:0.977},0).wait(1).to({regX:0.1,x:61,alpha:1},0).wait(54).to({x:44.9,alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(80));

	// t3a
	this.instance_4 = new lib.t3a();
	this.instance_4.parent = this;
	this.instance_4.setTransform(77.1,140.1,0.536,0.536,0,0,0,0.2,0.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(145).to({_off:false},0).wait(1).to({regX:0,regY:0,x:76.7,y:140,alpha:0.019},0).wait(1).to({x:75.6,alpha:0.086},0).wait(1).to({x:73.4,alpha:0.226},0).wait(1).to({x:69.6,alpha:0.457},0).wait(1).to({x:65.5,alpha:0.716},0).wait(1).to({x:62.6,alpha:0.892},0).wait(1).to({x:61.3,alpha:0.977},0).wait(1).to({regX:0.1,regY:0.1,x:61,y:140.1,alpha:1},0).wait(54).to({x:44.9,alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(84));

	// 3a.png
	this.instance_5 = new lib.s3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(59.7,347.5,0.64,0.64,0,0,0,73,110.7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(152).to({_off:false},0).to({regY:110.6,scaleX:0.8,scaleY:0.8,x:59.6,alpha:1},8,cjs.Ease.get(1)).wait(52).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(79));

	// t2c
	this.instance_6 = new lib.t2c();
	this.instance_6.parent = this;
	this.instance_6.setTransform(76.9,203.5,0.525,0.525,0,0,0,0.1,0);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(73).to({_off:false},0).wait(1).to({regX:0,x:76.4,alpha:0.022},0).wait(1).to({x:75.2,alpha:0.102},0).wait(1).to({x:72.7,alpha:0.258},0).wait(1).to({x:69.1,alpha:0.491},0).wait(1).to({x:65.3,alpha:0.729},0).wait(1).to({x:62.7,alpha:0.893},0).wait(1).to({x:61.4,alpha:0.976},0).wait(1).to({regX:0.1,x:61.1,alpha:1},0).wait(57).to({regX:0,x:60.7,alpha:0.978},0).wait(1).to({x:59.5,alpha:0.899},0).wait(1).to({x:56.9,alpha:0.738},0).wait(1).to({x:53.1,alpha:0.494},0).wait(1).to({x:49.3,alpha:0.254},0).wait(1).to({x:46.8,alpha:0.098},0).wait(1).to({x:45.6,alpha:0.021},0).wait(1).to({regX:0.1,x:45.4,alpha:0},0).to({_off:true},1).wait(154));

	// t2b
	this.instance_7 = new lib.t2b();
	this.instance_7.parent = this;
	this.instance_7.setTransform(75,169.7,0.525,0.525,0,0,0,0.1,0.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(71).to({_off:false},0).wait(1).to({regX:0,regY:0,x:74.6,y:169.6,alpha:0.022},0).wait(1).to({x:73.4,alpha:0.102},0).wait(1).to({x:70.9,alpha:0.258},0).wait(1).to({x:67.2,alpha:0.491},0).wait(1).to({x:63.5,alpha:0.729},0).wait(1).to({x:60.9,alpha:0.893},0).wait(1).to({x:59.6,alpha:0.976},0).wait(1).to({regX:0.1,regY:0.1,x:59.3,y:169.7,alpha:1},0).wait(55).to({regX:0,regY:0,x:59,y:169.6,alpha:0.986},0).wait(1).to({x:58.2,alpha:0.939},0).wait(1).to({x:56.8,alpha:0.845},0).wait(1).to({x:54.4,alpha:0.694},0).wait(1).to({x:51.2,alpha:0.494},0).wait(1).to({x:48.1,alpha:0.296},0).wait(1).to({x:45.8,alpha:0.149},0).wait(1).to({x:44.4,alpha:0.059},0).wait(1).to({x:43.7,alpha:0.013},0).wait(1).to({regX:0.1,regY:0.1,x:43.5,y:169.7,alpha:0},0).to({_off:true},1).wait(156));

	// t2a
	this.instance_8 = new lib.t2a();
	this.instance_8.parent = this;
	this.instance_8.setTransform(75.5,149,0.525,0.525,0,0,0,0,0.1);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(69).to({_off:false},0).wait(1).to({regY:0,x:75.1,y:148.9,alpha:0.022},0).wait(1).to({x:73.9,alpha:0.102},0).wait(1).to({x:71.4,alpha:0.258},0).wait(1).to({x:67.8,alpha:0.491},0).wait(1).to({x:64,alpha:0.729},0).wait(1).to({x:61.4,alpha:0.893},0).wait(1).to({x:60.1,alpha:0.976},0).wait(1).to({regY:0.1,x:59.8,y:149,alpha:1},0).wait(55).to({regY:0,x:59.4,y:148.9,alpha:0.978},0).wait(1).to({x:58.2,alpha:0.899},0).wait(1).to({x:55.6,alpha:0.738},0).wait(1).to({x:51.8,alpha:0.494},0).wait(1).to({x:48,alpha:0.254},0).wait(1).to({x:45.5,alpha:0.098},0).wait(1).to({x:44.3,alpha:0.021},0).wait(1).to({regY:0.1,x:44,y:149,alpha:0},0).to({_off:true},1).wait(160));

	// 2.jpg
	this.instance_9 = new lib.s2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(120,260,1,1,0,0,0,120,200);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(62).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(61).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(160));

	// 1a.jpg
	this.instance_10 = new lib.s1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(120,200,1,1,0,0,0,120,200);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({alpha:1},8,cjs.Ease.get(1)).wait(54).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(229));

	// bg
	this.instance_11 = new lib.bg();
	this.instance_11.parent = this;
	this.instance_11.setTransform(60,300,0.5,1.5,0,0,0,120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(300));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(39.5,299.5,254,601.6);
// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/p3b.png", id:"p3b"},
		{src:"images/120x600_atlas_NP_.jpg", id:"120x600_atlas_NP_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;