(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib._1 = function() {
	this.initialize(img._1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,703,488);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.ygyhh = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAhEKIAzlUIi3FUIh1AAIBQoSIBoAAIgyFTIC2lTIB1AAIhQISg");
	this.shape.setTransform(186.8,38.3,0.353,0.353);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ai3EKIBQoSIBsAAIgeDIIA5AAQArAAAdAJQAfAIATAUQATASAHAgQAIAegHAtQgHAsgRAiQgQAfgaAVQgYATgiAKQgiAIgoABgAg+C5IAeAAQAwAAAXgTQAXgSAHgxQAEgYgDgQQgDgPgKgLQgJgJgQgEQgOgDgVgBIgiAAg");
	this.shape_1.setTransform(171.7,38.3,0.353,0.353);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABkEKIBAmnIgCAAIigGnIhTAAIghmnIgBAAIhAGnIhkAAIBQoSICiAAIAVF1IABAAICGl1IChAAIhQISg");
	this.shape_2.setTransform(155.4,38.3,0.353,0.353);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ai+EKIBQoSIEtAAIgNBYIjAAAIgTB8IC1AAIgOBXIi0AAIgWCPIDIAAIgNBYg");
	this.shape_3.setTransform(139.3,38.3,0.353,0.353);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiCD/QgigTgNglQgOgkACgyQACg1AJg7QAJg7ANgzQAOgzAYgkQAaglAngUQAngVA8AAQA6AAAfATQAeASAOAdQAMAdgBAhQAAAfgFAfIhtAAQAIg6gJgaQgKgbglAAQgVAAgOALQgOALgMAYQgLAYgJAnQgJAqgIA1QgJA8gCAlQgBAlAFAVQAGAVAMAGQANAHARAAQAPAAAMgFQAMgEAMgPQAMgQAIgZQAJgXAHguIBtAAQgHAsgMAmQgMAlgXAeQgYAdgkAQQgkARg0AAQg9AAgigUg");
	this.shape_4.setTransform(125.6,38.3,0.353,0.353);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAhFOIAzlTIi2FTIh2AAIBQoSIBoAAIgzFUIC2lUIB2AAIhQISgAgVkBQgYgbAGgxIAxAAQAAAWANANQAOAMAWAAQAYAAAQgMQARgNAGgWIAyAAQgJAxgfAbQggAcgxAAQgxAAgXgcg");
	this.shape_5.setTransform(104.4,35.9,0.353,0.353);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai+EKIBQoSIEtAAIgNBYIjAAAIgTB8IC1AAIgNBXIi1AAIgVCPIDHAAIgNBYg");
	this.shape_6.setTransform(90.6,38.3,0.353,0.353);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiCD/QgigTgNglQgOgkACgyQABguAKhCQAJg7ANgzQAOgzAYgkQAZgkAogVQAngVA8AAQA6AAAfATQAfASAMAdQANAdgBAhQgBAlgEAZIhtAAQAJg6gKgaQgLgbgkAAQgVAAgOALQgOALgMAYQgMAbgIAkQgJAqgIA1QgJA8gCAlQgBAlAFAVQAHAVALAGQANAHARAAQAOAAANgFQAMgEAMgPQAMgQAIgZQAKgbAGgqIBtAAQgGAqgNAoQgNAngXAcQgXAdgkAQQgkARg1AAQg8AAgigUg");
	this.shape_7.setTransform(76.9,38.3,0.353,0.353);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AjGEKIBQoSIC1AAQAhgBAcAIQAcAGARAPQASAQAIAbQAHAZgFAmQgHArgZAfQgZAfgrALIAAACQAsAGAWAfQAWAggIA1QgFAfgMAcQgNAdgXAVQgYAWghAMQgiANgvAAgAhNC6IAqAAQAnAAAagRQAbgQAHgvQADgYgEgOQgEgPgJgKQgKgJgOgDQgOgEgSAAIgvAAgAgqgvIAfAAQAsAAAYgQQAXgPAGgnQAFgmgQgPQgQgPgqAAIgmAAg");
	this.shape_8.setTransform(61.7,38.3,0.353,0.353);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAlEKIAfjNIgnAAIiFDNIh4AAICUjZQgpgQgUgkQgTgmAJg8QAGgrARgfQARggAZgTQAbgVAggIQAfgJAnAAICyAAIhQISgAgFimQgYATgHAuQgHAwASASQARASAqAAIAvAAIAZioIgrAAQgtgBgXAUg");
	this.shape_9.setTransform(40.5,38.3,0.353,0.353);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AjbEKIgVgDIAPhbIAIABIAGAAQAOAAAKgCQALgBALgNQAKgMALgbQALgdALgvQAMgvANhMQAOhKAQhwIEzAAIhQISIhtAAIBDm6IhgAAQgOBkgMBAQgPBNgMApQgNAzgQAfQgQAggUASQgSASgZAIQgZAHgdAAIgagCg");
	this.shape_10.setTransform(25.6,38.4,0.353,0.353);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("ABrE+IAQhpIkCAAIgRBpIhkAAIAdjBIArAAQAZglASglQAQgkALglQAJggAJguIAOhXIATiCIE4AAIhDG6IAyAAIgdDBgAAGhMQgGAegKAqQgLAmgNAeQgMAggQAdICOAAIA1liIhmAAg");
	this.shape_11.setTransform(8.9,40.2,0.353,0.353);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAlEJIhNjZIgyA8IgXCdIhtAAIBQoRIBtAAIggDUIABAAICpjUIB2AAIi1DjIB2Eug");
	this.shape_12.setTransform(192,9.7,0.353,0.353);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("ABhEJIgIhwIiPAAIgqBwIhxAAIDeoRICGAAIA/IRgAgWBBIBpAAIgQjtIgCAAg");
	this.shape_13.setTransform(175.3,9.7,0.353,0.353);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ai+EJIBQoRIEtAAIgNBXIjBAAIgSB9IC1AAIgOBXIi0AAIgWCPIDIAAIgOBXg");
	this.shape_14.setTransform(163.2,9.7,0.353,0.353);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AjGEJIBQoRIC+AAQAqAAAaANQAaAOAOAWQAOAXADAcQADAdgEAeQgGApgRAeQgSAfgZASQgYATgiAKQggAJgoAAIg5AAIggDUgAgtgYIAvAAQAhAAAXgUQAXgUAGgoQAGgogOgVQgOgVgqAAIgsAAg");
	this.shape_15.setTransform(149.6,9.7,0.353,0.353);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ai+EJIBQoRIEtAAIgNBXIjAAAIgTB9IC1AAIgOBXIi0AAIgWCPIDIAAIgNBXg");
	this.shape_16.setTransform(136.5,9.7,0.353,0.353);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AiCD/QgigUgNgkQgOgkACgzQACg2AJg5QAJg5ANg1QANgyAagmQAZglAngTQAngVA8AAQA7AAAfATQAfATAMAcQAMAegBAgQAAAcgFAiIhtAAQAJg8gKgZQgKgaglAAQgUAAgPALQgOALgMAYQgKAXgKAoQgHAfgKA/QgJA9gCAlQgBAlAGAUQAFAVAMAHQALAHATAAQAPAAAMgFQAMgFAMgOQALgPAKgaQAIgZAHgtIBtAAQgGApgNApQgNAngWAdQgXAdgkAQQglARg0AAQg9AAgigUg");
	this.shape_17.setTransform(122.7,9.7,0.353,0.353);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhdEJIBPoRIBsAAIhQIRg");
	this.shape_18.setTransform(112,9.7,0.353,0.353);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AirELIgKgBIgcgCIAMhRQARACAPAAQAaAAAOgNQAPgOAOgYIAHgMIhamEIB5AAIApEFIBykFIBxAAIi7F9QgTApgRAdQgRAdgVASQgUATgaAIQgaAIglAAg");
	this.shape_19.setTransform(96.1,9.8,0.353,0.353);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("ABrE+IAQhpIkCAAIgQBpIhlAAIAdjBIArAAQAbgoAQgiQAPgjAMgmQAMgpAFglQAKgvAFgpIATiBIE4AAIhDG6IAzAAIgdDBgAASiPQgFAhgHAiQgIAogJAfQgJAigNAjQgPAkgOAZICOAAIA1liIhmAAg");
	this.shape_20.setTransform(78.8,11.6,0.353,0.353);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("ACiEJIhEjVIgyBCIgXCTIhnAAIAWiTIgfhCIiEDVIh2AAIDIkxIhmjgIBxAAIBfDZIAhjZIBnAAIggDZICgjZIBxAAIiqDgIBsExg");
	this.shape_21.setTransform(60.9,9.7,0.353,0.353);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ai+EJIBQoRIEtAAIgNBXIjAAAIgTB9IC1AAIgOBXIi0AAIgWCPIDIAAIgNBXg");
	this.shape_22.setTransform(44.5,9.7,0.353,0.353);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("ABrE+IAQhpIkDAAIgPBpIhlAAIAdjBIArAAQAaglAQglQAQgjALgmQAKggAIguIAPhYIATiBIE4AAIhDG6IAzAAIgdDBgAAGhMQgGAegLApQgJAkgOAhQgLAfgRAeICOAAIA1liIhmAAg");
	this.shape_23.setTransform(28.2,11.6,0.353,0.353);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AiHD/QghgUgOgkQgOgkACgyQACgtAJhDQAJg7AOgzQANgzAZglQAZgkAngUQAmgVA+AAQA+AAAgAVQAiAUANAkQAOAlgCAzQgCA1gJA5QgJA9gNAzQgOAzgYAjQgZAkgnAUQgpAUg7AAQg8AAgjgUgAgKi4QgQAKgMAYQgLAZgIAkQgJAmgIA0QgIAzgDAoQgDAmAFAXQAEAYANAKQANALAZAAQAYAAAPgLQAQgKAMgYQALgXAJgmQAIgoAIgzQAJg9ACgdQADglgEgYQgFgXgNgLQgOgLgXAAQgXAAgRALg");
	this.shape_24.setTransform(13.9,9.7,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ygyhh, new cjs.Rectangle(0,0,199.8,51.4), null);


(lib.ttt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AH6COIAAhJIAIAAIAAAGQABgEADgCQAEgCADAAQARAAABAcQgBAegRAAQgHAAgEgHIAAAYgAIDBRQgCAFABAKQgBAKACAFQADAHAGAAQAGAAACgGQADgFgBgMQABgVgLAAQgGAAgDAHgAAYCOIAAhJIAIAAIAAAGQACgEAEgCQADgCADAAQASAAAAAcQAAAegRAAQgIAAgFgHIAAAYgAAiBRQgCAFAAAKQAAAKACAFQADAHAGAAQAFAAADgGQADgFAAgMQAAgVgLAAQgGAAgDAHgAmCCOIAAhJIAIAAIAAAGQACgEADgCQADgCAEAAQARAAABAcQAAAegSAAQgIAAgEgHIAAAYgAl4BRQgCAFAAAKQAAAKACAFQACAHAHAAQAFAAADgGQACgFAAgMQABgVgLAAQgHAAgCAHgAw/COIAAhJIAIAAIAAAGQACgEADgCQADgCADAAQASAAAAAcQAAAegSAAQgGAAgFgHIAAAYgAw1BRQgCAFAAAKQAAAKACAFQACAHAHAAQAFAAADgGQACgFAAgMQAAgVgKAAQgHAAgCAHgAtdCKIAAgPIghAAIAAAPIgHAAIAAgVIAFAAQAEgIABgGQABgGABgKIAAgSIAdAAIAAAwIAGAAIAAAVgAtyBbQAAAIgCAGQAAAFgEAHIAUAAIAAgqIgOAAgAQpCFQgFgDAAgHIAHAAQABAEACACQACABADAAQAHAAACgDQADgDAAgHIAAgFIgBAAQgCAEgCACQgDACgEAAQgJAAgEgHQgEgHAAgPIABgJQABgFACgEQABgEADgDQADgCAGgBQAEAAADACQADACACAEIAAgGIAHAAIAAA1QAAAKgEAEQgGAFgIgBIgCAAQgFAAgEgDgAQvBIQgCACgBADIgCAHIAAAHIABALQAAAFADADQACADAEAAQAHAAACgGQACgFAAgLIgBgHIgBgGQAAgEgDgCQgCgCgEAAQgDAAgCACgAJVBuQAAgHADgEQAEgDAHgDIAKgEQACgBAAgGQAAgEgBgCQgDgCgEAAQgJAAAAAJIgHAAQAAgQAQAAQAIAAAEAFQAEADAAAGIAAAgQAAAFADAAIABAAIAAAFIgCABIgGgBQgCgCgBgFIgBAAQgBAEgDACQgDADgEAAQgOAAgBgPgAJjBjQgFAEgBAGQABAJAHAAQAKAAAAgLIAAgNIgMAFgAIuB3QgFgHAAgQQAAgdASAAQAKAAAFAKQACAHAAAOIgbAAQABALABAEQACAFAGAAQAJAAAAgNIAIAAQAAAJgEAFQgEAGgJAAQgIAAgFgGgAIxBbIATAAQAAgRgJAAQgKAAAAARgAHPB3QgFgHAAgQQAAgdASAAQAKAAAEAKQADAHAAAOIgbAAQAAALACAEQACAFAGAAQAJAAAAgNIAIAAQAAAJgEAFQgFAGgHAAQgKAAgEgGgAHSBbIATAAQAAgRgJAAQgKAAAAARgAGgB0QgCgGAAgNQgBgeAUAAQAHAAAEAGQAFAFAAAIIgHAAQAAgMgKAAQgGAAgCAHQgCAFAAALQAAAJABAFQACAHAHAAQAGAAACgEIACgKIAHAAQAAAJgEAFQgEAHgIAAQgMAAgFgJgABNB3QgFgHAAgQQAAgdASAAQAKAAAEAKQADAHAAAOIgaAAQAAALABAEQACAFAHAAQAIAAAAgNIAIAAQAAAJgEAFQgFAGgHAAQgKAAgEgGgABRBbIASAAQAAgRgJAAQgJAAAAARgAgVB3QgGgHABgQQgBgdAVAAQASAAAAAdQAAAQgGAHQgEAGgIAAQgLAAgEgGgAgPBPQgDAFAAANQAAAKADAFQACAGAHAAQAGAAACgGQACgFAAgKQAAgNgCgFQgDgFgFAAQgHAAgCAFgAhwBuQAAgHAEgEQACgDAIgDIAKgEQABgBAAgGQAAgEgBgCQgCgCgFAAQgEAAgCACQgBACgBAFIgHAAQABgQAPAAQAIAAAEAFQADADABAGIAAAgQAAAFACAAIACAAIAAAFIgDABIgGgBQgCgCgBgFQgBAEgDACQgEADgDAAQgPAAAAgPgAhiBjQgFAEgBAGQAAAJAIAAQAKAAgBgLIAAgNIgLAFgAiXB4QgFgEgBgKIAIAAQAAAHACADQADACAFAAQAJAAAAgKQAAgFgCgCQgCgDgFAAIgDAAIAAgHIADAAQAEAAACgCQADgDgBgEQAAgDgBgDQgDgCgEAAQgJAAgBAJIgHAAQABgGAEgFQAFgFAHAAQAHAAAEAEQAFAEAAAGQAAAFgCAEQgDADgEABIAAABQAEAAADAEQADAEAAAGQAAAHgEAEQgEAFgJAAQgIAAgEgFgAkuBuQABgHADgEQADgDAIgDIAJgEQACgBABgGQgBgEgBgCQgCgCgFAAQgFAAgCACQgBACAAAFIgHAAQAAgQAPAAQAJAAADAFQAEADAAAGIAAAgQAAAFADAAIACAAIAAAFIgEABIgFgBQgCgCgBgFQgCAEgDACQgEADgDAAQgPAAAAgPgAkfBjQgGAEAAAGQAAAJAHAAQAKAAABgLIAAgNIgMAFgAmwB3QgGgHAAgQQAAgdAUAAQATAAAAAdQAAAQgEAHQgGAGgJAAQgKAAgEgGgAmrBPQgDAFABANQgBAKADAFQACAGAHAAQAGAAADgGQACgFAAgKQAAgNgCgFQgDgFgGAAQgGAAgDAFgAn3B3QgFgHAAgQQAAgdASAAQAKAAAFAKQACAHAAAOIgbAAQABALABAEQACAFAGAAQAJAAAAgNIAIAAQAAAJgEAFQgEAGgJAAQgIAAgFgGgAn0BbIATAAQAAgRgJAAQgKAAAAARgAokB3QgFgHAAgQQAAgdARAAQALAAAEAKQACAHAAAOIgaAAQAAALABAEQACAFAHAAQAJAAAAgNIAHAAQAAAJgDAFQgFAGgIAAQgJAAgEgGgAohBbIASAAQABgRgKAAQgJAAAAARgAtKB3QgFgHAAgQQAAgdASAAQAKAAAEAKQADAHAAAOIgbAAQAAALACAEQACAFAGAAQAJAAAAgNIAIAAQAAAJgEAFQgFAGgHAAQgKAAgEgGgAtHBbIATAAQAAgRgJAAQgKAAAAARgAuqB3QgFgHAAgQQAAgdASAAQAKAAAEAKQADAHAAAOIgbAAQAAALACAEQACAFAGAAQAJAAAAgNIAIAAQAAAJgEAFQgFAGgIAAQgJAAgEgGgAunBbIATAAQAAgRgJAAQgKAAAAARgAwKB3QgFgHgBgQQABgdATAAQAUAAAAAdQAAAQgFAHQgFAGgKAAQgJAAgFgGgAwFBPQgCAFAAANQAAAKACAFQADAGAGAAQAHAAACgGQADgFAAgKQAAgNgDgFQgCgFgHAAQgGAAgDAFgALnB7IAAg2IAIAAIAAA2gALOB7IAAgwIgIAAIAAgGIAIAAIAAgFQAAgIACgDQACgEAJAAIADABIAAAGIgDAAQgBAAAAAAQgBAAgBAAQAAAAAAABQgBAAAAAAQgCACAAAEIAAAGIAJAAIAAAGIgJAAIAAAwgAK0B7IAAgKIAJAAIAAAKgAKhB7IgOgbIgGAIIAAATIgIAAIAAhJIAIAAIAAAsIATgZIAJAAIgQAVIARAhgAGJB7IAAg2IAIAAIAAA2gAFxB7IAAgKIAJAAIAAAKgAFQB7IgIguIgBAAIgIAuIgJAAIgNg2IAIAAIAKAwIAJgwIAIAAIAJAwIAKgwIAHAAIgNA2gAEOB7IgIguIgJAuIgJAAIgOg2IAIAAIAKAwIAJgwIAIAAIAJAwIABAAIAJgwIAIAAIgMA2gADMB7IgJguIAAAAIgJAuIgJAAIgMg2IAHAAIAKAwIABAAIAIgwIAIAAIAKAwIAJgwIAIAAIgNA2gAB4B7IAAgKIAJAAIAAAKgAg3B7IAAgwIgOAAIAAgGIAkAAIAAAGIgPAAIAAAwgAivB7IAAgpIABgHIgBAAQABAEgCADIgSApIgKAAIAAg2IAIAAIAAApIAAAHIABgHIASgpIAKAAIAAA2gAjiB7IAAgZIgUAAIAAAZIgIAAIAAg2IAIAAIAAAWIAUAAIAAgWIAIAAIAAA2gAlQB7IAAg2IAdAAIAAAGIgWAAIAAAwgApXB7IAAgpIABgFIgCAFIgRApIgKAAIAAg2IAIAAIAAApIgBAHIACgHIASgpIAJAAIAAA2gAqiB7IAAgXIgJAAIgLAXIgIAAIALgYQgEgBgDgEQgDgEAAgGQAAgHAEgEQAFgEAGAAIAUAAIAAA2gAqyBOQgCACAAAFQAAAJAJAAIAJAAIAAgTIgJAAQgFAAgCADgArRB7IAAgpIABgHIgCAHIgTApIgJAAIAAg2IAIAAIAAApIgBAHIAAAAIACgHIASgpIAJAAIAAA2gAsEB7IAAgZIgTAAIAAAZIgIAAIAAg2IAIAAIAAAWIATAAIAAgWIAIAAIAAA2gAvbB7IAAg2IASAAQAFAAAFADQAEAEAAAGQAAAFgCADQgCAEgEABQAJACABAMQAAAGgFAEQgEAEgFAAgAvTB1IAJAAQAFAAACgCQACgDAAgFQgBgJgIAAIgJAAgAvTBbIAIAAQAEAAACgCQADgCAAgEQAAgIgJAAIgIAAgAxWB7IAAgwIgTAAIAAAwIgIAAIAAg2IAjAAIAAA2gAL0B5IAXhLIAGAAIgXBLgARbB1QgFgCgBgHQgCgGAAgLIAAgKIADgJQACgEADgCQADgDAGAAQAFAAAEADQADADABAEQACAEABAGIAAAKIgZAAIAAALQABAEACADQACACAEAAQADAAACgCQACgCABgDQABgCAAgEIAHAAQAAAGgCAEQgBAEgDADQgEADgGAAQgFAAgEgDgAReBJQgCACgBAEIAAAIIASAAIgBgIIgDgHQgCgCgDAAQgFAAgBADgAPPB1QgFgCgCgHQgCgGAAgLIABgKIADgJQABgEAEgCQAEgDAEAAQAGAAAEADQADADACAEQABAEABAGIABAKIgaAAIAAALQABAEABADQACACAFAAQAEAAACgCQABgCABgDQABgCAAgEIAIAAQAAAGgCAEQgCAEgEADQgDADgGAAQgGAAgDgDgAPRBJQgBACgBAEIAAAIIASAAIgBgIIgCgHQgCgCgFAAQgEAAgCADgANzB0QgEgEAAgHQAAgFACgDIAEgFIAIgEIADgBIAEgCIACgBIABgCIABgEQAAgEgCgCQgCgCgFAAQgDAAgCACQgCADAAAEIgHAAQAAgIAEgEQAEgEAHAAQAGAAADACQADACACADQABADAAAEIAAAgIABADIACABIABAAIABAAIAAAFIgCABIgBAAIgEgBIgDgCIgCgFQgBAEgDACQgEADgDAAQgIAAgCgEgAOCBcIgFADIgFAEQgBACAAAEQAAADABACQACADAEAAQAEAAACgCIADgEIABgFIAAgNIgGADgAMdB1QgDgCgCgEIgDgJIgBgKIABgKIADgJQACgFADgCQAEgDAGAAQAFAAAEADQADACACAEQACAFAAAFIgHAAIgBgGQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgDgCgDAAQgEAAgDADQgCADgBAFIgBALIAAAHIACAHIADAFQACACADAAQAFAAACgCQACgCAAgDIABgGIAHAAQAAAFgCAEQgBAFgEADQgDADgGAAQgGAAgEgDgAQPB2IAAgnQAAgEgBgDQgDgCgEAAQgFAAgDADQgDADAAAFIAAAlIgIAAIAAg1IAIAAIAAAGQADgEADgCQADgCAFAAQAGAAADAEQADADAAAHIAAApgAOzB2IAAhIIAIAAIAABIgAOeB2IAAhIIAHAAIAABIgANcB2IAAgnQAAgEgBgDQgCgCgFAAQgEAAgDADQgEADAAAFIAAAlIgHAAIAAhIIAHAAIAAAZQADgEAEgCQADgCAEAAQAGAAAEAEQADADAAAHIAAApgAB4BPIAAgJIAJAAIAAAJgALnA8IAAgKIAIAAIAAAKgAGJA8IAAgKIAIAAIAAAKgAnmA8IAAgKIAHAAIAAAKgAn1A8IAAgKIAIAAIAAAKgANbAvIAAhJIAIAAIAAAHQACgEADgCIAGgCQASAAAAAbQAAAegSAAQgGAAgFgIIAAAZgANkgNQgBAFAAAJQAAAKABAFQADAHAGAAQAGAAACgGQADgFAAgMQAAgUgLAAQgGAAgDAHgAh6AvIAAhJIAIAAIAAAHQACgEAEgCQADgCADAAQASAAAAAbQAAAegSAAQgHAAgFgIIAAAZgAhwgNQgBAFgBAJQABAKABAFQACAHAHAAQAGAAACgGQACgGAAgLQAAgUgKAAQgHAAgCAHgAqYAvIAAhJIAIAAIAAAHQABgEADgCIAHgCQARAAABAbQAAAegSAAQgHAAgEgIIAAAZgAqPgNQgBAFAAAJQAAAKABAFQADAHAGAAQAGAAACgGQACgFAAgMQABgUgLAAQgGAAgDAHgAFIAuIAAgHQADABAEAAQADAAADgDQABgDACgFIgSg3IAJAAIAMArIABAAIAMgrIAIAAIgRA2QgDAKgDADQgEAGgGAAIgHgBgAjdAvIAAgZQgFAIgGAAQgLAAgEgJQgDgIAAgNQAAgbASAAQAHAAAEAHIAAgZIAIAAIAAAaQAEgIAHAAQASAAAAAbQABAegTAAQgGAAgFgIIAAAZgAjUgNQgBAFAAAJQAAAKABAFQADAHAGAAQAGAAADgGQACgGAAgLQAAgUgLAAQgGAAgDAHgAjwgNQgCAFAAAJQAAAKACAFQACAHAHAAQAFAAADgGQACgFAAgMQAAgUgKAAQgHAAgCAHgAPeArIAAgPIghAAIAAAPIgHAAIAAgVIAFAAQAEgJABgFQACgHAAgJIAAgSIAeAAIAAAwIAFAAIAAAVgAPJgDQAAAHgCAFQgBAFgDAIIAUAAIAAgpIgOAAgABEArIAAgPIghAAIAAg2IAIAAIAAAwIAUAAIAAgwIAHAAIAAAwIAFAAIAAAVgAqpArIAAgPIghAAIAAAPIgGAAIAAgVIAEAAIAGgOIABgQIAAgSIAdAAIAAAwIAGAAIAAAVgAq9gDQAAAHgCAFIgEANIAUAAIAAgpIgOAAgALHAmQAEgBAAgJIgEAAIAAgKIAJAAIAAAMQAAAEgDAEQgCADgEABgAQfAXQgFgHgBgPQAAgcASAAQALAAAEAKQADAHgBANIgaAAQAAAKABAFQADAFAFAAQAJAAAAgNIAIAAQAAAIgDAGQgFAGgIAAQgJAAgEgHgAQigDIASAAQAAgRgJAAQgJAAAAARgAMtAYQgGgIAAgPQAAgcAUAAQATAAABAcQgBAQgFAHQgFAGgJAAQgKAAgEgGgAMygPQgDAFAAALQAAALADAFQACAGAHAAQAGAAADgGQACgFABgLQAAgLgDgFQgDgFgGAAQgHAAgCAFgAHaAYQgFgIAAgPQAAgcAUAAQATAAAAAcQABAPgGAIQgFAGgJAAQgJAAgGgGgAHggPQgDAFAAALQAAALADAFQACAGAHAAQAGAAADgGQACgFAAgLQAAgLgCgFQgDgFgGAAQgHAAgCAFgAF6AVQgEgHAAgNQAAgcATAAQAIAAAFAGQAEAEAAAJIgIAAQABgMgKAAQgHAAgCAHQgBAFgBAJQABAKABAFQACAHAGAAQAHAAABgFQACgCAAgHIAIAAQAAAJgEAFQgEAHgJAAQgLAAgEgJgAEEAVQgEgHgBgQQABgRAEgJQAEgIAJgDIAIgCQAEgBAAgDIAHAAQgBAGgEACQgDADgIABQgLADgCAOQAFgIAIAAQAJAAAFAHQAFAHAAALQAAAOgFAHQgFAIgKAAQgLAAgEgJgAEKgMQgDAFAAAIQAAAWAMAAQAMAAAAgWQAAgIgDgFQgDgGgGAAQgFAAgEAGgADTAYQgGgIABgPQgBgcAVAAQATAAAAAcQAAAQgGAHQgEAGgJAAQgLAAgEgGgADZgPQgDAFAAALQAAALACAFQADAGAHAAQAGAAADgGQACgFAAgLQAAgLgCgFQgDgFgGAAQgHAAgCAFgAgMAOQAAgHAEgDQACgDAHgCIAKgEQABgCAAgFQABgFgCgCQgCgBgFAAQgGAAgBAJIgGAAQAAgQAOAAQAIAAAEAEQADAEAAAGIAAAfQAAAEADAAIADAAIAAAGIgEABQgEAAgBgCQgDgBgBgFQgBADgDADQgEADgDAAQgOAAAAgQgAABAEQgEADgBAHQAAAIAGAAQALAAgBgKIAAgNIgLAFgAioAYQgFgIAAgPQAAgcAUAAQATAAAAAcQAAAPgFAIQgFAGgJAAQgKAAgFgGgAiigPQgDAFAAALQAAALADAFQACAGAHAAQAGAAADgGQACgFAAgLQAAgLgCgFQgEgFgFAAQgHAAgCAFgAnUAOQAAgHADgDQADgDAHgCIAKgEQACgCAAgFQAAgFgCgCQgBgBgGAAQgHAAAAAJIgHAAQgBgQARAAQAHAAAFAEQADAEAAAGIAAAfQAAAEADAAIACAAIAAAGIgEABQgEAAgBgCQgCgBgBgFIgFAGQgEADgEAAQgNAAAAgQgAnHAEQgFADgBAHQAAAIAIAAQAKAAAAgKIAAgNIgMAFgAozAVQgEgHAAgQQAAgRAEgJQAFgIAJgDIAIgCQADgBABgDIAHAAQgCAGgEACQgDADgHABQgMADgCAOQAFgIAJAAQAJAAAEAHQAFAHAAALQAAAOgFAHQgEAIgKAAQgLAAgFgJgAosgMQgDAFAAAIQAAAWAMAAQALAAAAgWQAAgIgCgFQgDgGgGAAQgGAAgDAGgApjAYQgGgIAAgPQAAgcATAAQAVAAgBAcQABAQgGAHQgEAGgLAAQgJAAgEgGgApegPQgCAFgBALQAAALACAFQADAGAGAAQAIAAACgGQADgFAAgLQgBgLgDgFQgCgFgHAAQgFAAgDAFgAr6AYQgGgIAAgPQAAgcAVAAQATAAAAAcQAAAPgGAIQgEAGgJAAQgKAAgFgGgAr0gPQgDAFAAALQAAALADAFQACAGAHAAQAGAAADgGQACgFAAgLQAAgLgCgFQgEgFgFAAQgHAAgCAFgAveAIQgBgIAFgFQAEgFAFgBQgFgBgEgFQgCgEAAgGQgBgHAFgFQAEgGAKAAQAIAAAFAGQAFAFAAAHQAAAGgDAEQgDAFgFABQAFABAEAFQAEAFAAAIQAAAKgGAGQgEAGgKAAQgVAAABgWgAvTgCQgDADAAAGQAAAIADADQACAEAHAAQAGAAADgEQADgDgBgIQAAgGgCgDQgDgFgGAAQgHAAgCAFgAvTgaQAAAMAJAAQAJAAAAgMQAAgLgJAAQgKAAABALgAw+ARQgDgIAAgQQAAgQADgIQAEgOANAAQAMAAAFAOQACAIAAAQQAAAQgCAIQgEANgNAAQgOAAgDgNgAw6gHQABANACAHQACAJAIAAQAGAAAEgJQABgHAAgNQAAgegLAAQgNAAAAAegAGfAcIAAgGIADAAQADAAACgEIABgRIAAgbIAgAAIAAA2IgHAAIAAgvIgRAAIAAAVQAAANgDAGQgCAIgIAAIgEgBgAQKAcIgOgbIgGAIIAAATIgHAAIAAg2IAHAAIAAAaIATgaIAKAAIgRAWIARAggAOlAcIAAgXIgJAAIgLAXIgIAAIAMgYQgFgBgCgEQgDgEgBgFQAAgHAFgEQAFgFAGAAIATAAIAAA2gAOVgRQgCADAAAEQAAAJAJAAIAJAAIAAgSIgJAAQgFAAgCACgAMSAcIAAgvIgSAAIAAAvIgJAAIAAg2IAkAAIAAA2gAK1AcIgNgWIgNAWIgIAAIARgcIgQgaIAIAAIAMAVIANgVIAIAAIgQAaIAQAcgAKDAcIAAgXIgJAAIgLAXIgIAAIALgYQgEgBgDgEQgCgEgBgFQAAgHAFgEQAEgFAHAAIASAAIAAA2gAJygRQgCADAAAEQAAAJAKAAIAJAAIAAgSIgJAAQgFAAgDACgAJUAcIAAgoIABgHIgBAAIgBAHIgSAoIgJAAIAAg2IAIAAIAAApIgBAHIACgHIASgpIAJAAIAAA2gAIJAcIAAg2IASAAQAGAAAFAEQADADAAAGQABAGgDADQgCADgEABIAAAAQAKACAAALQAAAHgEAEQgEAEgFAAgAIRAWIAJAAQAFAAACgDQACgCAAgFQAAgJgJAAIgJAAgAIRgDIAIAAQAEAAACgCQACgCAAgEQAAgIgIAAIgIAAgAChAcIAAgXIgJAAIgLAXIgJAAIAMgYQgEgBgDgEQgDgEAAgFQAAgHAEgEQAEgFAHAAIATAAIAAA2gACRgRQgDADAAAEQAAAJAKAAIAJAAIAAgSIgJAAQgFAAgCACgABxAcIAAgoIABgHIgCAHIgSAoIgJAAIAAg2IAIAAIAAApIgBAFIABgFIATgpIAJAAIAAA2gAgfAcIAAgvIgOAvIgFAAIgOgvIAAAvIgHAAIAAg2IAMAAIAJAjIACAMIADgMIAKgjIALAAIAAA2gAkOAcIAAgZIgUAAIAAAZIgIAAIAAg2IAIAAIAAAXIAUAAIAAgXIAHAAIAAA2gAlAAcIAAgoIAAgDIgBADIgSAoIgKAAIAAg2IAIAAIAAApIAAAEIABgEIASgpIAKAAIAAA2gAmMAcIAAgXIgIAAIgMAXIgJAAIAMgYQgEgBgDgEQgCgEAAgFQAAgHADgEQAFgFAGAAIATAAIAAA2gAmcgRQgCADAAAEQgBAJAKAAIAJAAIAAgSIgJAAQgFAAgCACgAnoAcIAAgZIgUAAIAAAZIgHAAIAAg2IAHAAIAAAXIAUAAIAAgXIAIAAIAAA2gAsVAcIAAhBIgcAAIAABBIgIAAIAAhJIAtAAIAABJgAtrAcIAAgKIAJAAIAAAKgAuSAcIAAg2IAeAAIAAAHIgWAAIAAAvgAv+AcIAAg1IgQAAIAAgGQAKAAADgDQAFgCAAgJIAGAAIAABJgAx0AcQABgKACgGQAEgHAMgJQAMgKAAgKQAAgNgLAAQgHAAgCAFQgCAEAAAIIgIAAIAAgDQAAgKAFgFQAFgHAJAAQAKAAAFAGQAFAGgBAJQABAIgEAGQgDAEgGAGIgPAMQgCADgBAGIAfAAIAAAHgAI2gvIAAhKIAIAAIAAAGQACgDADgCQAEgCADAAQARAAABAcQAAAdgSAAQgIAAgEgHIAAAZgAJAhsQgCAFAAAJQAAALACAFQACAHAHAAQAFAAADgGQACgGABgLQgBgWgKAAQgHAAgCAIgAnOgvIAAhKIAIAAIAAAGIAAAAQACgDAEgCQACgCADAAQATAAgBAcQAAAdgRAAQgHAAgFgHIAAAZgAnFhsQgBAFAAAJQAAALABAFQADAHAGAAQAHAAACgGQADgGAAgLQAAgWgMAAQgGAAgDAIgArdgvIAAhKIAIAAIAAAGQACgDAEgCQADgCADAAQASAAAAAcQAAAdgSAAQgHAAgFgHIAAAZgArThsQgBAFgBAJQABALABAFQACAHAHAAQAGAAACgGQACgGAAgLQABgWgLAAQgHAAgCAIgAB5gzIAAgPIgiAAIAAg3IAIAAIAAAwIAUAAIAAgwIAIAAIAAAwIAFAAIAAAWgAjsgzIAAgPIggAAIAAAPIgHAAIAAgWIAFAAIAEgNIABgRIAAgSIAfAAIAAAwIAFAAIAAAWgAkBhjQABAIgCAGIgFAMIAVAAIAAgpIgPAAgAu4gzIAAgPIgiAAIAAg3IAIAAIAAAwIAUAAIAAgwIAHAAIAAAwIAGAAIAAAWgAsShOQgDgIAAgSQgBglAYAAQAKAAAFAGQAGAHAAAKIgIAAQAAgQgOAAQgJAAgDALQgCAHAAAMQAAAPACAHQAEAKAIAAQAIAAADgGQACgEABgLIAIAAQgBAOgEAHQgFAIgLAAQgPAAgFgOgAPYhQQAAgHADgDQADgEAIgDIAKgEQACgBAAgFQgBgFgBgCQgCgCgFAAQgIAAAAAKIgHAAQAAgQAQAAQAIAAAEAEQADAEABAGIAAAgQAAAEACAAIACAAIAAAGIgDAAIgGgBQgCgBgBgGQgBAEgEADQgDACgEAAQgOAAAAgPgAPmhaQgGADAAAHQAAAIAIAAQAKAAAAgLIAAgNIgMAGgANShMQgDgIAAgPQAAgRADgJQAFgPANAAQAIAAAFAFQAFAFAAAIIgJAAQAAgGgCgCQgDgCgFAAQgKAAgCAcQAEgJAJAAQAKAAAGAHQAEAGAAAKQAAALgFAHQgGAHgJAAQgNAAgFgLgANYhbQAAATAMAAQAMAAgBgSQAAgQgMAAQgLAAAAAPgAMKhHQgFgHAAgQQAAgcAUAAQATAAABAcQgBAQgFAHQgEAGgKAAQgKAAgFgGgAMQhvQgDAGAAAMQAAALADAFQACAGAHAAQAGAAADgGQACgFAAgLQAAgMgCgGQgDgFgGAAQgGAAgDAFgAKMhQQABgHADgDQADgEAHgDIAKgEQACgBAAgFQAAgFgBgCQgCgCgFAAQgEAAgDADQgCACAAAFIgHAAQAAgQAQAAQAIAAAFAEQADAEAAAGIAAAgQAAAEADAAIABAAIAAAGIgDAAIgFgBQgCgBgBgGQgBAEgEADQgDACgEAAQgOAAgBgPgAKahaQgFADgBAHQABAIAHAAQAKAAAAgLIAAgNIgMAGgAIGhQQAAgHAEgDQADgEAHgDIAKgEQACgBAAgFQAAgFgCgCQgCgCgFAAQgEAAgCADQgCACAAAFIgGAAQAAgQAPAAQAIAAAEAEQADAEAAAGIAAAgQAAAEADAAIADAAIAAAGIgEAAIgFgBQgDgBgBgGQgBAEgDADQgEACgDAAQgPAAAAgPgAIUhaQgFADgBAHQAAAIAIAAQAKAAAAgLIAAgNIgMAGgAGEhFQgFgFAAgIIAIAAQAAAKAKAAQAHAAADgKQACgGABgNQgFAJgJAAQgJAAgFgGQgFgHAAgJQAAgMAGgHQAFgHAJAAQANAAAFAMQADAHAAAPQAAASgDAIQgFAPgOAAQgHAAgFgEgAGGh0QgBARAMAAQAMAAAAgPQAAgIgCgEQgEgGgGAAQgMAAABAQgAEKhJQgDgHAAgNQAAgdASAAQAJAAAEAFQAEAFABAIIgIAAQAAgMgKAAQgGAAgCAIQgCAFAAAKQAAAKACAEQACAIAGAAQAGAAACgFQABgDABgGIAIAAQAAAIgFAGQgDAGgKAAQgLAAgEgIgAgFhQQAAgHADgDQACgEAIgDIAKgEQACgBAAgFQAAgFgCgCQgCgCgFAAQgIAAAAAKIgGAAQAAgQAPAAQAIAAAEAEQADAEABAGIAAAgQAAAEACAAIACAAIAAAGIgDAAIgGgBQgCgBgBgGQgBAEgEADQgDACgDAAQgOAAAAgPgAAIhaQgFADgBAHQAAAIAIAAQAKAAAAgLIAAgNIgMAGgAjYhHQgGgHAAgQQAAgcASAAQAKAAAFAKQADAGAAAOIgbAAQAAALABAEQACAGAGAAQAKAAAAgNIAIAAQAAAIgFAFQgEAGgIAAQgJAAgEgGgAjVhiIASAAQAAgSgJAAQgJAAAAASgAk5hHQgFgHAAgQQAAgcASAAQALAAAEAKQACAHAAANIgbAAQABALABAEQACAGAGAAQAJAAAAgNIAIAAQAAAIgEAFQgEAGgJAAQgIAAgFgGgAk2hiIATAAQAAgSgJAAQgKAAAAASgAmZhHQgFgHAAgQQAAgcAUAAQAUAAgBAcQAAAQgFAHQgEAGgKAAQgKAAgFgGgAmThvQgDAGAAAMQAAALADAFQACAGAHAAQAHAAACgGQACgFAAgLQAAgMgCgGQgDgFgGAAQgGAAgDAFgAqohHQgFgHAAgQQAAgcAUAAQAUAAAAAcQAAAQgGAHQgEAGgKAAQgJAAgGgGgAqihvQgDAGAAAMQAAALADAFQADAGAGAAQAHAAACgGQACgFAAgLQAAgMgCgGQgDgFgGAAQgGAAgDAFgAQghCIAAgXIgIAAIgLAXIgJAAIAMgYQgFgCgDgEQgCgEAAgFQAAgHAEgFQAEgEAIAAIASAAIAAA3gAQQhwQgCACAAAFQAAAJAJAAIAJAAIAAgSIgJAAQgEAAgDACgAPFhCIAAgwIgOAwIgFAAIgOgwIAAAwIgIAAIAAg3IANAAIAKAkIABALIACgLIAKgkIANAAIAAA3gALwhCIAAgwIgTAAIAAAwIgIAAIAAg3IAjAAIAAA3gAJwhCIAAgwIgOAAIAAgHIAlAAIAAAHIgOAAIAAAwgAHzhCIAAgwIgNAwIgGAAIgOgwIAAAwIgHAAIAAg3IAMAAIAJAkIACALIABAAIACgLIAKgkIAMAAIAAA3gAFfhCIAAg2IgQAAIAAgGQAJAAADgDQAEgDABgIIAHAAIAABKgADahCIAAgqIAAgGIgBAGIgTAqIgJAAIAAg3IAIAAIAAAqIgCAGIABAAIACgGIASgqIAJAAIAAA3gACmhCIAAgqIAAgBIgBABIgSAqIgJAAIAAg3IAIAAIAAAqIgBAEIABgEIATgqIAJAAIAAA3gABFhCIgNgbIgGAHIAAAUIgIAAIAAg3IAIAAIAAAaIATgaIAJAAIgQAWIARAhgAgxhCIAAgXIgJAAIgLAXIgJAAIAMgYQgEgCgCgEQgEgEAAgFQABgHAEgFQAEgEAHAAIASAAIAAA3gAhBhwQgCACAAAFQAAAJAJAAIAJAAIAAgSIgJAAQgFAAgCACgAhghCIAAgqIABgBIgBABIgTAqIgJAAIAAg3IAIAAIAAAqIgBAEIACgEIASgqIAJAAIAAA3gAiThCIAAgaIgUAAIAAAaIgHAAIAAg3IAHAAIAAAXIAUAAIAAgXIAIAAIAAA3gAlqhCIAAg3IARAAQAHAAAFAEQADADAAAGQAAAFgCAEQgCADgEABQAKADAAALQAAAHgEAEQgEAEgFAAgAlihJIAJAAQAFAAACgCQACgCAAgFQAAgKgJAAIgJAAgAlihiIAIAAQAFAAACgCQABgCAAgFQABgHgJAAIgIAAgAnkhCIAAgwIgTAAIAAAwIgIAAIAAg3IAjAAIAAA3gAouhCIAAgqIAAgGIgCAGIgSAqIgKAAIAAg3IAIAAIAAAqIgBAGIABAAIABgGIASgqIAKAAIAAA3gApehCIgNgbIgGAHIAAAUIgIAAIAAg3IAIAAIAAAaIATgaIAJAAIgRAWIASAhgAtFhCIAAgKIAJAAIAAAKgAtdhCIAAgXIgIAAIgLAXIgIAAIALgYQgEgCgDgEQgCgEgBgFQAAgHAFgFQAEgEAHAAIATAAIAAA3gAtthwQgCACABAFQgBAJAKAAIAIAAIAAgSIgIAAQgFAAgDACgAuLhCIAAgqIABgGIAAAAQgBADgBADIgSAqIgJAAIAAg3IAIAAIAAAqIgCAGIACgGIATgqIAJAAIAAA3gAvshCIgNgbIgGAHIAAAUIgIAAIAAg3IAIAAIAAAaIATgaIAJAAIgRAWIARAhgAwZhCIgGgVIgXAAIgGAVIgJAAIAWhKIAKAAIAVBKgAw1hfIAUAAIgKgngAxgh5IgHAKIgEgDIAIgJIgLgFIABgEIALAEIAAgMIAGAAIAAAMIALgEIABAFIgLAEIAIAJIgFADg");
	this.shape.setTransform(114.1,14.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ttt, new cjs.Rectangle(0,0,228.1,28.5), null);


(lib.trtr = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABGCkIAjjoIheDoIhGAAIgYjoIgjDoIhRAAIAylHIB6AAIATDaIBVjaIB6AAIgxFHg");
	this.shape.setTransform(189.3,33.1,0.353,0.353);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhXCiQgYgKgMgWQgMgVgBggQgCggAHgsQAGgqAMggQALgfAUgXQATgWAagLQAcgLAjAAQAlAAAZALQAYALAMAWQALAUACAiQABAdgGAtQgHArgLAgQgMAggTAWQgTAVgaAKQgbALgkAAQgmAAgYgKgAgIhpQgKAIgHAQQgHANgFAXIgIAuIgGAuQgCAWACAPQADAQAIAIQAHAIAQAAQAaAAAOgbQAOgbAJg9QAJg8gGgcQgGgbgaAAQgPAAgKAJg");
	this.shape_1.setTransform(176.9,33.1,0.353,0.353);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ah+CkIAylHIDLAAIgKA/Ih1AAIgoEIg");
	this.shape_2.setTransform(167.9,33.1,0.353,0.353);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhdCdQgZgRgIgYQgIgXABggQADgiAEgcQAFgjAJgcQAJgfASgYQASgYAcgNQAdgPAqAAQAlAAAWAMQAWAMALAVQAKAYAAAdQABAegGAnIgDASIipAAIgEAaQgCAOAAAPQAAAOAEAKQADALAHAGQAHAGAMAAQAVABAMgQQANgQAIgeIBNAAQgLA5ghAeQggAeg+AAQgvAAgXgPgAgChsQgIAGgHAKQgGAKgFALQgEAMgBALIgCANIBXAAIACgiQAAgOgDgKQgDgKgIgFQgIgGgMAAQgNABgJAFg");
	this.shape_3.setTransform(158.1,33.1,0.353,0.353);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhXCkIApkIIhWAAIAKg/ID/AAIgJA/IhWAAIgmEIg");
	this.shape_4.setTransform(149.2,33.1,0.353,0.353);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhRCkQgXgIgNgUQgMgRgEgjQgDghAHgyQAJgyAOghQAQgjAUgSQAVgUAagIQAagIAdAAQA8AAAZAjQAZAhgJA7IhSAAIACgXQAAgOgDgIQgCgIgHgHQgGgFgNAAQgRgBgJAIQgKAGgHAOQgHAOgGAVIgJAwQgEAggCAVQgBAWADANQACAOAIAHQAIAGAPAAQAVAAAMgSQANgTAGgnIBSAAQgJA/gjAkQgiAhhEAAQghAAgWgIg");
	this.shape_5.setTransform(133.6,33.1,0.353,0.353);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAdDaIgyiHIglAnIgOBgIhWAAIBCmzIBWAAIgjDlIABAAIBoh5IBfAAIh0CAIBQDHg");
	this.shape_6.setTransform(118.1,31.2,0.353,0.353);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhXCiQgYgJgMgWQgMgXgBggQgBgiAGgpQAGgqAMggQAMggATgWQASgVAbgMQAcgLAjAAQAoAAAXAKQAXALAMAWQAMAXABAfQABAigGApQgGAqgMAgQgNAigSAUQgTAWgaALQgcAKgjAAIgGAAQgjAAgVgKgAgIhpQgLAJgGAPQgHAPgFAVIgOBcQgCAUADARQACAQAIAIQAIAIAQAAQAZAAAOgbQANgZAKg/QAJg9gGgbQgGgbgaAAQgPAAgKAJg");
	this.shape_7.setTransform(107,33.1,0.353,0.353);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhXCiQgZgKgLgVQgMgWgBghQgBgiAGgpQAHgqALggQAMggATgWQASgVAcgMQAbgLAjAAQAoAAAXAKQAXAKAMAXQAMAWABAgQABAjgGAoQgGAqgMAgQgMAhgTAVQgTAXgaAKQgcAKgjAAIgHAAQgiAAgVgKgAgIhpQgLAJgGAPQgHAPgFAVIgIAuIgGAuQgBAXACAOQACAQAIAIQAIAIAQAAQAZAAAOgbQANgZAKg/QAJg9gGgbQgFgbgbAAQgPAAgKAJg");
	this.shape_8.setTransform(96.4,33.1,0.353,0.353);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgdDVQgQgJgMgYIgBAAIgFAjIhSAAIBCmzIBUAAIgTCKIABAAQAPgUATgJQATgKAYAAQA0AAATAoQATAqgOBaQgNBbgfAoQgfAog1AAQgZgBgQgIgAgOgdQgMAcgJA0QgHA3AEAaQAEAbAdAAQAbAAAMgbQANgbAIg2QAHg2gEgaQgEgbgcAAQgcAAgMAbg");
	this.shape_9.setTransform(85.5,31.3,0.353,0.353);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AheCdQgYgQgIgZQgJgaACgdQABgaAGgkQAFgjAJgcQAJgeASgZQATgZAbgMQAcgPAqAAQAmAAAWAMQAVALALAWQALAWAAAfQAAAigFAjIgDASIipAAIgEAaQgCAOAAAPQAAAOAEAKQADALAHAGQAHAGAMAAQAVABAMgQQANgQAIgeIBNAAQgMA6ggAdQgiAeg8AAQgvAAgYgPgAgChsQgKAHgFAJQgHAKgEALQgEAMgBALIgCANIBWAAQADgWAAgMQAAgNgDgLQgEgKgHgFQgIgGgMAAQgNABgJAFg");
	this.shape_10.setTransform(75.1,33.1,0.353,0.353);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhRCkQgXgHgNgUQgNgTgDgiQgDghAHgyQAJgyAOghQAQgiAUgTQAVgUAagIQAbgIAcAAQA8AAAZAjQAZAhgJA7IhSAAQACgLAAgMQAAgOgDgIQgCgJgHgGQgGgFgNAAQgQgBgJAIQgLAGgHAOQgIAOgEAVQgFATgFAdQgEAggCAVQgBAWADANQADAPAIAGQAHAGAPAAQAVAAAMgSQANgTAGgnIBSAAQgJA/gjAkQgiAhhEAAQghAAgWgIg");
	this.shape_11.setTransform(65.1,33.1,0.353,0.353);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhqCkQgOgHgHgOQgIgNgBgRQgCgPACgSQAEgZAHgPQAIgRAMgMQALgLASgIQAQgHAYgGIAygOQAUgEAJgJQAJgJACgQQADgTgIgKQgHgMgWAAQgTAAgMAMQgLANgDASIgCAJIhNAAIACgIQAEgcAMgUQAMgTASgLQARgMAXgFQAWgGAXAAQAnAAAWAIQAXAHALANQALAOACATQACASgEAWIgaCsQgDAYAAAMQAAALAEARIhSAAQgDgKgBgHIgBgSIgBAAQgTAagUAHQgVAIgfAAQgWAAgPgIgAAWAMIgTAFQgaAHgNAMQgNANgDAWQgDASAFAOQAGANARAAQAIABALgDQAIgDAJgGQAIgGAHgKQAGgJADgOIAJhBQgJAHgLAEg");
	this.shape_12.setTransform(54.4,33.1,0.353,0.353);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AicDaIBCmzID3AAIgLBIIidAAIgQBnICUAAIgLBHIiUAAIgcC9g");
	this.shape_13.setTransform(45,31.2,0.353,0.353);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAZCkIAfjNIh5DNIhaAAIAylHIBQAAIgfDOIB5jOIBbAAIgyFHg");
	this.shape_14.setTransform(28.3,33.1,0.353,0.353);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AiZClIgUgDIAKg/IAPABQAIAAAIgCQAIgCAHgJQAHgJAGgRQAIgTAGgcQAHgaAIgvIARhrIDnAAIgxFIIhWAAIAokIIhBAAQgNBagOA0QgQA3gQAaQgRAcgVAJQgWAJgZAAg");
	this.shape_15.setTransform(16.4,33.2,0.353,0.353);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAZCkIAfjNIh5DNIhaAAIAylHIBQAAIgfDOIB5jOIBbAAIgyFHg");
	this.shape_16.setTransform(5.5,33.1,0.353,0.353);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAfDaIhAizIgoAyIgUCBIhZAAIBBmzIBaAAIgaCvIABAAICKivIBhAAIiUC7IBgD4g");
	this.shape_17.setTransform(168.5,7.7,0.353,0.353);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ah7DaIgjmzIBfAAIAPFBIABAAIBylBIBdAAIioGzg");
	this.shape_18.setTransform(157.5,7.7,0.353,0.353);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgwA2QAQgDALgOQAKgOACgRIACgHIghAAIAPhfIBRAAIgMBPQgFAagFAQQgHAVgLAPQgMAPgQAKQgSAJgZACg");
	this.shape_19.setTransform(141.6,15.4,0.353,0.353);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("ABmCoIAjjkQADgVgGgLQgHgLgRAAQgVAAgOAOQgOANgFAdIggDXIhVAAIAjjkQADgVgGgLQgHgLgRAAQgVAAgOAOQgOANgFAdIggDXIhWAAIAxlHIBTAAIgGAiIACAAQASgWAXgLQAVgKAdAAQAdABASANQASANADAaIABAAQAOgaAYgOQAZgNAeAAQAqAAARAaQAQAZgHAwIgkDtg");
	this.shape_20.setTransform(131.4,9.4,0.353,0.353);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhpClQgPgJgHgNQgHgMgCgSQgCgSADgQQACgVAJgSQAHgRAMgMQAMgLARgIQAUgJAVgFIAxgNQATgFAKgIQAIgIADgSQADgTgHgKQgIgKgWAAQgTAAgLALQgMAKgDAVIgBAKIhNAAIABgIQAEgdAMgUQAOgUAQgLQATgMAVgFQAUgFAaAAQAmAAAXAHQAWAHALAOQALANACATQACATgDAWIgaCsQgEAVAAAPQABAQAEALIhSAAQgDgGgBgLIgCgRIgBAAQgTAagUAIQgUAHgfAAQgXAAgOgHgAAWAMIgSAGQgbAFgMANQgOAMgDAWQgDATAGAOQAFAOARAAQAJgBAKgDQAJgCAIgHQAJgFAHgKQAGgLACgMIAKhBQgKAHgLAEg");
	this.shape_21.setTransform(117.7,9.5,0.353,0.353);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhwCoIAxlHIBRAAIgGAsIABAAQAQgXAWgPQAUgPAbAAIAPABIgMBRIgagBQgLAAgMADQgLADgLAHQgKAHgIALQgGAKgEATIgcDDg");
	this.shape_22.setTransform(109.5,9.4,0.353,0.353);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AiEDJQgagYAHgpIBSAAQgDAQAMAJQAHAEAFADQAIACAHAAQAbAAALgRQAOgPADgZIAHgsIgCAAQgPASgUALQgUAMgVAAQgzAAgUgnQgUgmANhZQAFgeAIgcQAHgfAPgXQAPgYAXgQQAXgPAiAAQASAAARAKQATAKAIAZIABAAIAGglIBSAAIgvE3QgKBBglAfQglAghKAAQg2AAgbgXgAgFiYQgJAGgHAOQgHAOgFAXQgEAOgGAqQgDAOgBARQAAANACAOQADAMAIAHQAIAHANAAQANAAAJgHQAKgHAIgNQAGgLAGgRIAIgmQAJg8gGgZQgGgZgaAAQgNgBgKAHg");
	this.shape_23.setTransform(99.7,11.4,0.353,0.353);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhpClQgOgJgIgNQgHgNgCgRQgCgPADgTQAEgXAHgQQAHgRAMgMQALgLASgIQAUgJAVgFIAxgNQAUgFAJgIQAIgIADgSQADgTgHgKQgIgKgWAAQgTAAgLALQgMAMgDATIgBAKIhNAAIABgIQAEgdAMgUQANgTARgMQATgMAVgFQAVgFAZAAQAmAAAXAHQAWAHALAOQALANACATQACATgDAWIgaCsQgEAVAAAPQABAMAEAPIhSAAQgEgIAAgJIgCgRIgBAAQgTAagUAIQgUAHgfAAQgXAAgOgHgAAXAMIgTAGQgbAFgMANQgOAMgDAWQgDATAGAOQAFAOASAAQAJgBAJgDQAJgBAIgIQAJgFAHgKQAGgKACgNIAKhBQgKAHgKAEg");
	this.shape_24.setTransform(88.9,9.5,0.353,0.353);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgzDRQgPgDgHgLQgHgJAAgRQgBgQADgaIAdi7IgsAAIAJg5IArAAIAPheIBUAAIgOBeIAyAAIgJA5IgxAAIgbCxQgDAUAEAIQAFAIATAAIAUgBIgJA6Ig4ACQgaAAgOgDg");
	this.shape_25.setTransform(81.4,7.9,0.353,0.353);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhRClQgXgGgMgOQgMgMgDgVQgDgSAEgZIACgLIBNAAIgCAKQgDAXAKAMQAJAOAWAAQASAAAOgLQANgJADgUQACgPgHgJQgJgJgLgEIg4gVQgigMgPgWQgOgWAFgjQADgVAKgRQAJgSARgNQASgPAYgHQAXgIAhAAQA7AAAYAYQAYAZgHAtIgCANIhNAAQAEgagGgMQgHgMgVABQgQAAgNAIQgOAJgCASQgCAMAGAKQAHAKAUAGIAxARQAmAOANAVQAOAWgGAkQgDAagNAUQgLASgTAOQgUAOgWAEQgZAGgZAAQgjAAgYgHg");
	this.shape_26.setTransform(72.4,9.5,0.353,0.353);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAVCoIAjjhQAEgagIgKQgGgKgUAAQgsAAgJA2IghDZIhVAAIAxlHIBSAAIgGAmIACAAQAQgYAXgLQAXgLAdgBQApABATAVQASAWgHAyIglDyg");
	this.shape_27.setTransform(62,9.4,0.353,0.353);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhNDaIBCmzIBYAAIhBGzg");
	this.shape_28.setTransform(54.2,7.7,0.353,0.353);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AiLCkIAylHICMAAQAVAAASAEQARAEANAKQAMALAFAPQAGAQgEAXQgEAbgQATQgPATgcAHQA9AMgLBDQgDAbgMATQgLASgRAKQgRALgVAEQgUAEgZAAgAguBqIAiAAQAXAAANgIQAOgJAEgZQAEgagLgIQgJgJgaAAIghAAgAgZggIAWAAIAUgBQAKgCAIgDQAHgDAFgIQAEgGADgOQACgMgDgHQgDgHgGgDQgGgEgKgBIgqgBg");
	this.shape_29.setTransform(40.2,9.6,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.trtr, new cjs.Rectangle(0,0,196.4,39.2), null);


(lib.rtet = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah0DbQgigMgSgbQgSgcgDgrQgDgvAKg8QAKhCARgpQARgtAbgbQAbgcAlgNQAlgMAyAAQAsAAAfAKQAgALATAZQASAYAFApQAFAogJA9IgHAsIjZAAIgJA6QgFAkAKAMQALAMAPAAQATAAANgQQAOgQAHgtICEAAQgOBSguApQguAphbAAQg1AAgigMgAgIh8QgLARgFAiIgDAUIBQAAIADgUQAFgigGgRQgGgRgYAAQgWAAgLARg");
	this.shape.setTransform(190.6,13.2,0.353,0.353);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AinDjIBEm6ICMAAIgKBHIACAAQASgpAegUQAegVAhAAIAYAAIgVCJIglgDQgoAAgXARQgYASgHAsIgjDwg");
	this.shape_1.setTransform(179.4,13,0.353,0.353);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ah0DbQgjgMgRgbQgSgcgDgrQgDgsAKg/QAJg+ARgtQARgsAcgcQAbgcAlgNQAlgMAyAAQAsAAAfAKQAgALATAZQASAZAFAoQAFArgJA6IgHAsIjZAAIgJA6QgFAkAKAMQALAMAPAAQATAAANgQQAOgQAHgtICEAAQgOBSguApQgvAphaAAQg1AAgigMgAgIh8QgKAPgGAkIgDAUIBQAAIADgUQAFgjgGgQQgGgRgYAAQgWAAgLARg");
	this.shape_2.setTransform(166.9,13.2,0.353,0.353);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAKEkIAskkQAEgagGgNQgHgMgTAAQgUAAgJAMQgKAMgEAbIgsEkIiTAAIBYpHICSAAIgcC/IACAAQAXgkAegMQAegNAbAAQAZAAASAGQAUAGAOANQAOAOAGAYQAFAYgFAhIgyFNg");
	this.shape_3.setTransform(152.2,10.7,0.353,0.353);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiaEkIBFnGIhxAAIATiBIF6AAIgTCBIhyAAIhEHGg");
	this.shape_4.setTransform(139.9,10.7,0.353,0.353);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhFEcQgXgDgNgLQgOgMgDgWQgEgVAGgmIAjjrIgxAAIAQhjIAwAAIAUiBICSAAIgUCBIA7AAIgQBjIg5AAIggDSQgDATAIAIQAHAIASAAIAWAAIgOBiIgpABIgmABQgiAAgYgDg");
	this.shape_5.setTransform(128,10.9,0.353,0.353);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiZDdQgUgEgOgOQgNgNgGgYQgFgXAFgjIAylNICTAAIgsEjQgEAdAHALQAGANAUAAQATAAAJgNQALgMADgcIAskjICTAAIhCG6IiOAAIAIg2IgCAAQgkA/hPAAQgZAAgUgFg");
	this.shape_6.setTransform(115.2,13.3,0.353,0.353);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AiMEeQgmgPgTglQgTgjgCg6QgCg6ANhSQAMhRATg5QATg5AeglQAegkArgSQAqgQA6AAQA6AAAlAQQAmASATAkQATAkACA6QACA5gNBRQgMBSgTA6QgUA6geAjQgdAlgrAPQgqAQg5AAQg7AAglgQgAABi9QgLAJgIAXQgJAXgHAmQgIAngJA6IgNBiQgEApACAUQACAYAJAJQAJAIARABQARgBAMgIQALgKAIgXQAIgWAIgnQAJgtAHg1QAJg6AFgnQAEgpgCgUQgCgXgJgJQgJgJgRAAQgRAAgMAJg");
	this.shape_7.setTransform(99.9,10.7,0.353,0.353);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AjQDuQgUg7ASh6QAKg+AQgrQAQgqAWgaQAVgaAbgMQAbgLAfAAQAfAAAWANQAXAOAGAiIABAAIAdi/ICTAAIhYJGIiNAAIAJg8IgBAAQgTAkgbARQgaAQgnAAQhKAAgVg6gAgagyQgJAGgHAOQgFAMgGAZIgLA8QgGAlgBAVQgCAWACAQQADAPAHAFQAHAGANAAQAMAAAJgGQAJgFAHgPQAHgPAEgXQAFgVAFglQAGgkACgYQACgVgDgQQgCgOgHgGQgHgGgMAAQgNAAgJAGg");
	this.shape_8.setTransform(84.5,10.9,0.353,0.353);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ah0DbQgigMgSgbQgSgcgDgrQgDgvAKg8QAKhCARgpQARgtAbgbQAbgcAlgNQAlgMAyAAQAsAAAfAKQAgALATAZQASAYAFApQAFAogJA9IgHAsIjZAAIgJA6QgFAkAKAMQALAMAPAAQATAAANgQQAOgQAHgtICEAAQgOBSguApQguAphbAAQg1AAgigMgAgIh8QgLARgFAiIgDAUIBQAAIADgUQAFgigGgRQgGgRgYAAQgWAAgLARg");
	this.shape_9.setTransform(69.7,13.2,0.353,0.353);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhEEcQgYgDgNgLQgOgNgDgVQgEgWAGglIAjjrIgxAAIAPhjIAxAAIAUiBICSAAIgUCBIA7AAIgPBjIg6AAIggDSQgDATAHAIQAIAIASAAIAXAAIgPBiIgpABIgnABQghAAgXgDg");
	this.shape_10.setTransform(59,10.9,0.353,0.353);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AifDCQgjgkALhJICBAAQgCAPABAJQABAMAEAHQAIAQAVAAQARAAANgKQAPgKACgSQADgUgPgKQgOgKgVgJIgxgRQgbgKgUgPQgVgOgNgaQgMgaAHgpQADgdAPgaQAPgYAYgTQAagUAhgKQAkgKArAAQCmAAgVCLIh/AAQADgdgIgKQgJgLgSAAQgRAAgLAJQgLAJgDARQgDATAPAJQAMAJAYAIIAwAPQAaAIAWAQQAWAPAMAYQALAagGArQgFAhgQAaQgQAbgaAUQgYATgkAKQgjAKgoAAQhdAAgiglg");
	this.shape_11.setTransform(46.7,13.2,0.353,0.353);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah0DbQgjgMgSgbQgRgcgDgrQgDgsAKg/QAJg+ARgtQARgsAcgcQAbgcAlgNQAlgMAyAAQAsAAAfAKQAgALASAZQATAYAFApQAFArgJA6IgHAsIjZAAIgJA6QgFAkAKAMQALAMAPAAQATAAANgQQAOgQAHgtICEAAQgOBSguApQgvAphaAAQg1AAgigMgAgIh8QgKAPgGAkIgDAUIBQAAIADgUQAFgjgGgQQgGgRgYAAQgWAAgLARg");
	this.shape_12.setTransform(33.4,13.2,0.353,0.353);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AiaEkIBFnGIhxAAIATiBIF6AAIgTCBIhyAAIhEHGg");
	this.shape_13.setTransform(23.4,10.7,0.353,0.353);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgpEcIAniOIhJAAIgnCOIhaAAIAniOIg8AAIAOhfIBIAAIAahdIg8AAIAPhfIBIAAIAniOIBZAAIgnCOIBIAAIAoiOIBaAAIgoCOIA9AAIgPBfIhHAAIgbBdIA8AAIgOBfIhIAAIgnCOgAgxAvIBIAAIAbhdIhJAAg");
	this.shape_14.setTransform(8,11,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.rtet, new cjs.Rectangle(0,0,197.4,21.3), null);


(lib.kkk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF691C").s().p("A4CJdQj+AAizi0Qi0izAAj9QAAj+C0izQCzi0D+AAMAwFAAQQD+AACzCzQC0CzAAD+QAAD+i0CzQizC0j+AAg");
	this.shape.setTransform(75.8,21.9,0.352,0.352);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.kkk, new cjs.Rectangle(0,0,151.6,43.8), null);


(lib.jkjklj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF691C").s().p("A4CJdQj+AAizizQi0i0AAj9QAAj+C0i0QCzizD+AAMAwFAAPQD+AACzC0QC0C0AAD9QAAD+i0C0QizCzj+AAg");
	this.shape.setTransform(75.9,21.9,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.jkjklj, new cjs.Rectangle(0,0,151.8,43.9), null);


(lib.hjkljkl = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AArGtIBBmzIjqGzIiXAAIBnqoICFAAIhCG0IDrm0ICWAAIhmKogAgblKQgegjAHg/IBAAAQgBAcARARQAQAQAeAAQAeAAAVgQQAWgRAIgcIBBAAQgMA/gpAjQgpAkg/AAQg/AAgdgkg");
	this.shape.setTransform(126.1,15.2,0.353,0.353);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AB8FVIgKiQIi3AAIg3CQIiRAAIEdqpICtAAIBRKpgAgdBUICHAAIgUkyIgCAAg");
	this.shape_1.setTransform(105.1,18.3,0.353,0.353);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Aj+FVIBnqpIDzAAQA3AAAhASQAhARASAdQASAdAFAkQAEAlgGAmQgIA2gWAnQgVAlghAZQghAZgqAMQgqANgyAAIhKAAIgpEQgAg6ggIA9AAQAqAAAdgYQAegZAIg1QAIgzgTgbQgSgbg0AAIg6AAg");
	this.shape_2.setTransform(88.5,18.3,0.353,0.353);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjsFVIBnqpIFyAAIgRBxIjmAAIhVI4g");
	this.shape_3.setTransform(72.7,18.3,0.353,0.353);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AArFVIBBm0IjrG0IiXAAIBnqpICGAAIhCG0IDrm0ICXAAIhnKpg");
	this.shape_4.setTransform(54.7,18.3,0.353,0.353);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AB+FVIBmqpICMAAIhnKpgAlvFVIBmqpICNAAIgoECIBLAAQAzAAAoALQAoALAYAZQAZAYAJAoQAKApgKA4QgJA6gVApQgUApghAaQghAagqALQgpAMg3AAgAjUDtIAnAAQA+AAAfgYQAcgWAKhAQAFghgEgTQgEgUgMgNQgMgMgUgEQgWgFgZAAIgrAAg");
	this.shape_5.setTransform(32,18.3,0.353,0.353);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Aj/FVIBnqpIDpAAQAtAAAhAJQAjAIAXAUQAYAVAJAhQAKAhgIAxQgIA3ggAoQggAng3APIAAACQA5AHAcAoQAcAqgLBEQgGAogQAlQgQAkgeAbQgdAbgtARQgsAQg8AAgAhkDwIA3AAQAxAAAjgWQAigWAJg7QAFgegGgUQgFgTgMgMQgNgMgSgFQgSgFgXAAIg9AAgAg2g8IAoAAQA4AAAfgVQAegUAHgxQAHgxgVgUQgVgUg1AAIgxAAg");
	this.shape_6.setTransform(9,18.3,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.hjkljkl, new cjs.Rectangle(0,0,136,30.3), null);


(lib.hjklhj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAAtIgtA/IgogdIAug/IhKgXIAPgvIBKAYIAAhNIAxAAIAABNIBKgYIAPAvIhKAXIAuA/IgpAdg");
	this.shape.setTransform(191.5,42,0.353,0.353);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAsE5IhckBIg6BHIgcC6IiAAAIBepxICBAAIgmD7IACAAIDHj7ICLAAIjWENICLFkg");
	this.shape_1.setTransform(175.7,50.5,0.353,0.353);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AifEtQgngXgRgrQgRgqADg7QACg6ALhLQAMhKAPg4QAQg8AdgqQAcgrAvgYQAugZBIAAQBJAAAnAZQAnAXAQAsQAQAqgCA8QgCA6gLBIQgLBGgQA/QgQA7gdAqQgdArguAXQguAXhHAAQhKAAgmgXgAgMjZQgSANgPAbQgNAcgKAsQgKAtgKA9QgJBDgDApQgEArAFAdQAFAbAQANQAQANAcAAQAcAAATgNQATgNANgbQAOgcAKgsQAJgrALhBQAJhCADgoQAEgsgGgcQgFgcgPgMQgQgNgcAAQgcAAgTANg");
	this.shape_2.setTransform(157.7,50.5,0.353,0.353);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AB2E5IBLnzIgCAAIi8HzIhjAAIgmnzIgCAAIhLHzIh2AAIBepxIC/AAIAZG5IABAAICem5IC+AAIheJxg");
	this.shape_3.setTransform(137.3,50.5,0.353,0.353);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAmE5IA9mPIjXGPIiLAAIBepxIB8AAIg9GQIDXmQICLAAIhfJxg");
	this.shape_4.setTransform(116.8,50.5,0.353,0.353);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAcE5IAqkWIiVAAIgqEWIiAAAIBdpxICBAAIgkDvICVAAIAkjvICBAAIhfJxg");
	this.shape_5.setTransform(99.1,50.5,0.353,0.353);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiaEtQgngXgQgrQgRgqADg7QAChAALhFQAKhDAQg/QAQg8AdgqQAdgsAvgXQAugZBIAAQBEAAAlAWQAjAVAQAjQAOAigBAnQAAAmgGAjIiAAAQAJhFgLgfQgMgfgrAAQgYAAgRANQgSAOgNAbQgNAdgLAtQgJApgLBHQgKBEgDAvQgBAqAGAaQAHAYAOAJQAPAIAUAAQARAAAQgGQAOgFAOgRQANgSALgfQAKgcAJg2ICAAAQgIA2gPArQgOAtgbAiQgbAigrAUQgqATg/AAQhIAAgogXg");
	this.shape_6.setTransform(82,50.5,0.353,0.353);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AifEtQgogXgQgrQgQgrACg6QACg8ALhJQALhHAPg7QAQg8AdgqQAdgrAvgYQAugZBIAAQBJAAAmAZQAoAXAQAsQAQAqgCA8QgCA6gLBIQgMBOgPA3QgQA7gdAqQgdArguAXQgtAXhJAAQhJAAgmgXgAgMjZQgTANgOAbQgOAegJAqQgLAxgIA5QgKA/gEAtQgDAtAFAbQAFAbAQANQAQANAcAAQAcAAATgNQAUgNANgbQANgbAKgtQAJgrAKhBQAJg2AEg0QAEgrgFgdQgFgbgQgNQgQgNgcAAQgdAAgSANg");
	this.shape_7.setTransform(64.6,50.5,0.353,0.353);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AiWE5IBPoKIiLAAIAPhnIGWAAIgPBnIiMAAIhNIKg");
	this.shape_8.setTransform(49.7,50.5,0.353,0.353);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AifEtQgogXgQgrQgQgrACg6QACg8ALhJQALhHAPg7QAQg8AdgqQAdgrAvgYQAugZBIAAQBJAAAmAZQAoAXAQAsQAQAqgCA8QgCA6gLBIQgMBOgPA3QgQA7gdAqQgdArguAXQgtAXhJAAQhJAAgmgXgAgMjZQgTANgOAbQgOAegJAqQgLAxgIA5QgKA/gEAtQgDAtAFAbQAFAbAQANQAQANAcAAQAcAAATgNQAUgNANgbQANgbAKgtQAJgrAKhBQAJg2AEg0QAEgrgFgdQgFgbgQgNQgQgNgcAAQgdAAgSANg");
	this.shape_9.setTransform(32,50.5,0.353,0.353);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhwFEIAMhSQh4AAg3hAQg4hAARh0QAJg4AXgsQAXgqAmgiQAkgfAygRQAxgRA7AAIAMhQICAAAIgMBQQA7AAAsARQAsARAcAfQAbAfAKAtQALAsgJA4QgRBzhMBBQhLBAh3AAIgNBSgAAmCRQBAgBAkgpQAkgpAJhAQAFgggDgbQgDgagNgTQgLgSgXgLQgVgLggABgAheiHQgZALgSASQgRATgMAaQgKAZgGAiQgJBBAXAoQAXApBAABIAskiQgggBgZALg");
	this.shape_10.setTransform(11.3,50.5,0.353,0.353);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAnGKIA9mPIjYGPIiLAAIBfpxIB6AAIg8GRIDYmRICJAAIhdJxgAgZkvQgcgfAIg7IA5AAQAAAaAQAPQAPAPAbAAQAbAAAUgPQAUgPAIgaIA6AAQgKA6gmAgQgmAhg5AAQg6AAgbghg");
	this.shape_11.setTransform(182.6,13.9,0.353,0.353);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AB0E5IBdpxICBAAIheJxgAlRE5IBfpxICAAAIgkDtIBEAAQAxAAAjAKQAlAKAXAWQAWAYAIAjQAIAlgIA1QgIA2gTAlQgUAlgdAYQgeAYgnALQgoAKgwAAgAjCDZIAjAAQA7AAAbgVQAbgWAIg6QAEgbgDgUQgEgSgLgMQgLgLgSgEQgRgFgbAAIgnAAg");
	this.shape_12.setTransform(161.8,16.8,0.353,0.353);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAcE5IApkWIiUAAIgqEWIiAAAIBdpxICBAAIgkDvICVAAIAkjvICAAAIheJxg");
	this.shape_13.setTransform(141.2,16.8,0.353,0.353);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AiWE5IBPoJIiLAAIAPhoIGWAAIgQBoIiLAAIhNIJg");
	this.shape_14.setTransform(126.3,16.8,0.353,0.353);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAsE5IAkjxIguAAIidDxIiOAAICvkAQgxgTgXgqQgWgsAKhIQAJg0ATgkQAUgkAdgXQAfgYAmgKQAmgLAuAAIDSAAIhfJxgAgGjFQgcAWgIA3QgJA4AVAWQAVAWAyAAIA2AAIAejHIgzAAQg1AAgbAWg");
	this.shape_15.setTransform(108.1,16.8,0.353,0.353);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AifEtQgngXgRgrQgQgpACg9QACg5ALhKQAMhLAPg4QAQg8AdgqQAcgqAvgaQAvgYBHAAQBIAAAoAYQAnAZAQArQARAqgDA8QgCA6gLBJQgLBGgPA9QgRA8gcAqQgeArguAXQguAXhIAAQhJAAgmgXgAgMjZQgTANgNAcQgOAagKAuQgJAqgLBAQgJBDgDAoQgEAtAGAbQAFAcAPAMQAQANAcAAQAcAAATgNQASgMAPgcQANgbAKgtQAKgsAKg/QAJhCADgoQADgtgEgbQgFgcgQgNQgQgNgcAAQgcAAgTANg");
	this.shape_16.setTransform(91.6,16.7,0.353,0.353);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AjpE5IBepxIDgAAQAxAAAfAQQAfAQAQAbQARAaAEAiQAEAigGAiQgHAzgUAiQgTAjgfAWQgeAYgnALQgmALgvAAIhDAAIgmD6gAg1gdIA4AAQAmAAAbgXQAbgXAIgwQAHgvgRgZQgRgYgwAAIg1AAg");
	this.shape_17.setTransform(74.7,16.8,0.353,0.353);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AjgE5IBepxIFjAAIgPBoIjjAAIgWCSIDVAAIgQBnIjVAAIgZCoIDrAAIgPBog");
	this.shape_18.setTransform(59.2,16.8,0.353,0.353);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AjqE5IBepxIDXAAQAoAAAfAIQAfAHAXATQAVASAJAfQAJAegHAuQgIAygdAlQgeAkgyANIAAACQA0AHAaAlQAZAlgJBAQgGAmgPAgQgPAigbAYQgaAZgqAPQgnAPg4AAgAhbDcIAyAAQAuAAAfgUQAfgUAIg3QAFgagFgTQgGgTgLgJQgLgMgRgEQgRgFgVABIg3AAgAgyg3IAlAAQA0AAAcgTQAbgTAHgsQAHgugUgRQgTgTgxAAIgtAAg");
	this.shape_19.setTransform(42.1,16.8,0.353,0.353);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AjgE5IBepxIFjAAIgPBoIjjAAIgWCSIDVAAIgPBnIjWAAIgZCoIDrAAIgPBog");
	this.shape_20.setTransform(26.6,16.8,0.353,0.353);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAcE5IAqkWIiVAAIgqEWIiAAAIBepxICBAAIgkDvICUAAIAkjvICBAAIhfJxg");
	this.shape_21.setTransform(10,16.8,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.hjklhj, new cjs.Rectangle(0,0,195.6,61.9), null);


(lib.hjkhj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF691C").s().p("A9JJlQj+AAi0i0QizizAAj+QAAj9CzizQC0i0D+AAMA6TAAAQD+AACzC0QC0CzAAD9QAAD+i0CzQizC0j+AAg");
	this.shape.setTransform(87.5,21.6,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.hjkhj, new cjs.Rectangle(0,0,174.9,43.3), null);


(lib.hjkh = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.hjkh, new cjs.Rectangle(0,0,703,488), null);


(lib.hjghj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAnGKIA8mQIjXGQIiLAAIBfpxIB6AAIg8GRIDXmRICLAAIhfJxgAgZkvQgbggAGg6IA6AAQAAAZAPAQQAQAPAbAAQAbAAAUgPQAUgPAHgaIA7AAQgKA6gmAgQgmAhg5AAQg6AAgbghg");
	this.shape.setTransform(95.6,13.9,0.353,0.353);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AByE5IgJiEIipAAIgxCEIiGAAIEGpxICeAAIBLJxgAgaBNIB8AAIgTkYIgCAAg");
	this.shape_1.setTransform(76.3,16.8,0.353,0.353);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AkCE6QgSgCgHgCIARhrIARABQARAAALgCQAOgCANgPQAMgPAMgfQAMgeAOg7QANg4ARhaQARhjATh4IFpAAIhdJxIiBAAIBOoJIhxAAQgSB1gNBMQgPBRgRA7QgPA6gTAmQgSAmgYAWQgYAVgbAIQgeAJgiAAQgPAAgPgCg");
	this.shape_2.setTransform(59.3,16.8,0.353,0.353);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjgE5IBepxIFjAAIgPBoIjjAAIgWCTIDVAAIgPBmIjWAAIgZCoIDsAAIgQBog");
	this.shape_3.setTransform(43.6,16.8,0.353,0.353);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AB/F3IASh8IkxAAIgSB8Ih3AAIAijkIAzAAQAfgtATgqQATgpANgtQAMgrAJgyIAoj/IFvAAIhOIJIA8AAIgjDkgAAVipQgEAbgKA0QgKAzgJAiQgLAngQApQgPApgUAfICoAAIA/mhIh4AAg");
	this.shape_4.setTransform(24.5,18.9,0.353,0.353);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AiZEtQgngXgRgrQgQgpACg9QACg7ALhJQAKhDARg/QAQg8AdgrQAdgrAugYQAwgYBGAAQBEAAAlAWQAkAWAPAiQAPAigBAmQgBAngFAjIiBAAQAKhFgLgfQgMgfgsAAQgXAAgSANQgSANgMAcQgOAcgKAuQgJAogMBIQgKBEgCAvQgCAtAHAXQAGAYAPAIQAOAJAVAAQAQAAAQgGQAPgGANgRQAOgRAKgfQAKgcAJg2ICBAAQgJA1gOAsQgPAugbAhQgbAigrATQgrAUg+AAQhHAAgogXg");
	this.shape_5.setTransform(7.9,16.7,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.hjghj, new cjs.Rectangle(0,0,104.6,32.2), null);


(lib.ghj = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAnE9IA9mVIjaGVIiNAAIBgp5IB9AAIg9GWIDamWICNAAIhgJ5g");
	this.shape.setTransform(111.8,11.6,0.352,0.352);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiYE9IBQoRIiNAAIAQhoIGbAAIgPBoIiOAAIhPIRg");
	this.shape_1.setTransform(96.5,11.6,0.352,0.352);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AicExQgogYgQgrQgRgqADg9QACg5ALhNQALhHAQg9QAPg8AegsQAegsAvgYQAvgZBJAAQBGAAAkAXQAlAWAPAiQAPAigBAoQgBAngFAjIiDAAQALhFgMggQgMgfgtAAQgZAAgQAMQgSAOgNAcQgOAegKAuQgMAzgJA+QgKBDgDAyQgBAtAGAYQAHAYAPAJQAOAIAVAAQASAAAPgGQAPgGANgRQAOgSALgfQALggAIgzICCAAQgIA2gPAsQgPAvgbAhQgbAigsAVQgsAUg+AAQhJAAgpgYg");
	this.shape_2.setTransform(79,11.6,0.352,0.352);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AihExQgpgYgQgrQgQgrACg8QACg7ALhLQALhHAQg9QAQg9AegrQAcgrAwgZQAvgZBJAAQBJAAAoAZQAoAZAQArQARArgDA9QgCA7gLBJQgLBKgQA8QgPA7geAsQgdArgwAYQgvAYhIAAQhJAAgogYgAgMjdQgUAPgNAbQgOAdgKAsQgKArgJBAQgKBAgEAtQgDAtAFAcQAGAdAPAMQAQANAdAAQAcAAATgNQATgMAPgdQAOgcAJgtQAKgsAKhBQAKhBADgqQAEgtgGgcQgFgcgQgOQgPgMgdAAQgeAAgSAMg");
	this.shape_3.setTransform(61.5,11.6,0.352,0.352);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAcE9IBQoRIiXAAIhQIRIiCAAIBfp5IGcAAIhgJ5g");
	this.shape_4.setTransform(43.8,11.6,0.352,0.352);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AB0E9IgKiGIirAAIgyCGIiHAAIEJp5IChAAIBMJ5gAgaBPIB+AAIgUkdIgCAAg");
	this.shape_5.setTransform(24.3,11.6,0.352,0.352);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiPE9QgmgMgUgYQgVgYgFgmQgGgmAIgyIABgIICDAAIgBAGQgEAVAAAUQAAAUAHAOQAHAPAOAJQANAJAbAAQAoAAAYgYQAYgXAHg0QAJg2gTgXQgSgWgwAAIgTAAIgXABIAPhjIAYABQA2AAAZgXQAagYAIg0QAGgpgPgSQgQgRgfAAQgfAAgVAMQgXANgJAdIgIAkIh/AAIAAgFQAOhaA8gtQA8gtBlAAQBdAAAtArQArAsgMBQQgDAWgKAZQgKAXgOATQgPATgVAQQgUAOgZAHQA0ALAZAjQAYAlgKA/QgPBlhBAxQhBAxhoAAQg4AAgngMg");
	this.shape_6.setTransform(8.1,11.6,0.352,0.352);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ghj, new cjs.Rectangle(0,0,121,23.2), null);


(lib.fghfgh = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkyEeQAOhHCHg3IDEAAIAYhXIk5AAQArhqBmgSIDLAAIAehsIlKAAQAahgBvgeIF0AAIifI7g");
	this.shape.setTransform(-42.2,0,0.353,0.353);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF691C").s().p("AjHDLQhThVAAh2QAAh2BThTQBThUB0AAQB1AABTBUQBTBTAAB2QAAB2hTBVQhTBTh1AAQh0AAhThTg");
	this.shape_1.setTransform(70.5,0.1,0.353,0.353);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAEeQgfiNgSgoQgcg+ggAAIhqAAIAmh6IBzAAIAjgHQAlgPAQgrQAQgsAOg1IALgsICUAAIhJDsIgOAdQgUAfgnARIAjBtIAuCVg");
	this.shape_2.setTransform(49,0.1,0.353,0.353);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AiXEcICeo3ICQAAIiYI3g");
	this.shape_3.setTransform(37,0,0.353,0.353);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3EeIAliBIjTAAIAhhwIDTAAIA3i9Ih+AAQhSACgiASQgoAVgRA6IhfFFIiRAAIB0mWQAShOBDgsQA5glBGAAIGIAAIihI7g");
	this.shape_4.setTransform(21,0.1,0.353,0.353);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AlZEeICdo7IIWAAIhYDqQgPAzgwAbQgqAZg1ABIitgBIAjh9IB4AAQAqAAAZgtIAQgtIjrAAIh+HBg");
	this.shape_5.setTransform(-21,0.1,0.353,0.353);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AkyEeQAOhHCHg2IDEAAIAYhYIk6AAQAshqBmgSIDLAAIAehsIlKAAQAahgBvgeIF0AAIifI7g");
	this.shape_6.setTransform(-0.1,0.1,0.353,0.353);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AjLEeQgkAAgWgRQgVgRAAgcQAAgJACgJIBrmXQAQguAjgUQAegSBEAAIEzAAQgKAxg8AsQgeAVgcAMIiTAAQgUAAgOAIQgNAJgJATIhKEaQgCACAnAAIEDAAIgSAqQgVAvgdASQgOAJgsAEQgmAFglAAg");
	this.shape_7.setTransform(-61.1,0.1,0.353,0.353);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AiUEeICUo7ICVAAIiUI7g");
	this.shape_8.setTransform(-75.2,0.1,0.353,0.353);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("Egg1AIWQkaAAhwjiQgkhGgNhVIgIhGIAAilQAAkaDihwQBGgkBUgOQArgHAcAAMBBqAAAQEaAABxDiQA4BxAABwIAAClQAAEajhBwQhxA5hxAAg");
	this.shape_9.setTransform(0,0,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90,-18.8,180.1,37.7);


(lib.fghf = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkyEeQAOhHCHg3IDEAAIAYhXIk5AAQArhqBmgSIDLAAIAehsIlKAAQAahgBvgeIF0AAIifI7g");
	this.shape.setTransform(-42.2,0,0.353,0.353);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF691C").s().p("AjHDLQhThVAAh2QAAh2BThTQBThUB0AAQB1AABTBUQBTBTAAB2QAAB2hTBVQhTBTh1AAQh0AAhThTg");
	this.shape_1.setTransform(70.5,0.1,0.353,0.353);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAEeQgfiNgSgoQgcg+ggAAIhqAAIAmh6IBzAAIAjgHQAlgPAQgrQAQgsAOg1IALgsICUAAIhJDsIgOAdQgUAfgnARIAjBtIAuCVg");
	this.shape_2.setTransform(49,0.1,0.353,0.353);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AiXEcICeo3ICQAAIiYI3g");
	this.shape_3.setTransform(37,0,0.353,0.353);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3EeIAliBIjTAAIAhhwIDTAAIA3i9Ih+AAQhSACgiASQgoAVgRA6IhfFFIiRAAIB0mWQAShOBDgsQA5glBGAAIGIAAIihI7g");
	this.shape_4.setTransform(21,0.1,0.353,0.353);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AlZEeICdo7IIWAAIhYDqQgPAzgwAbQgqAZg1ABIitgBIAjh9IB4AAQAqAAAZgtIAQgtIjrAAIh+HBg");
	this.shape_5.setTransform(-21,0.1,0.353,0.353);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AkyEeQAOhHCHg2IDEAAIAYhYIk6AAQAshqBmgSIDLAAIAehsIlKAAQAahgBvgeIF0AAIifI7g");
	this.shape_6.setTransform(-0.1,0.1,0.353,0.353);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AjLEeQgkAAgWgRQgVgRAAgcQAAgJACgJIBrmXQAQguAjgUQAegSBEAAIEzAAQgKAxg8AsQgeAVgcAMIiTAAQgUAAgOAIQgNAJgJATIhKEaQgCACAnAAIEDAAIgSAqQgVAvgdASQgOAJgsAEQgmAFglAAg");
	this.shape_7.setTransform(-61.1,0.1,0.353,0.353);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AiUEeICUo7ICVAAIiUI7g");
	this.shape_8.setTransform(-75.2,0.1,0.353,0.353);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("Egg1AIWQkaAAhwjiQgkhGgNhVIgIhGIAAilQAAkaDihwQBGgkBUgOQArgHAcAAMBBqAAAQEaAABxDiQA4BxAABwIAAClQAAEajhBwQhxA5hxAAg");
	this.shape_9.setTransform(0,0,0.353,0.353);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90,-18.8,180.1,37.7);


// stage content:
(lib._240x400 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 17
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Ayq/KMAlVAAAMAAAA+VMglVAAAg");
	this.shape.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(240));

	// ygyhh
	this.instance = new lib.ygyhh();
	this.instance.parent = this;
	this.instance.setTransform(330,96.9,1,1,0,0,0,99.9,25.7);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(172).to({_off:false},0).to({x:120},10,cjs.Ease.get(1)).wait(47).to({rotation:45,x:223.1,y:-7.7,alpha:0},7,cjs.Ease.get(-1)).to({_off:true},1).wait(3));

	// hjkljkl
	this.instance_1 = new lib.hjkljkl();
	this.instance_1.parent = this;
	this.instance_1.setTransform(333.7,40.6,1,1,0,0,0,68,15.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(164).to({_off:false},0).to({x:123.7},10,cjs.Ease.get(1)).wait(54).to({regX:67.9,regY:15.1,rotation:45,x:265.4,y:-45,alpha:0},7,cjs.Ease.get(-1)).to({_off:true},2).wait(3));

	// hjkhj
	this.instance_2 = new lib.hjkhj();
	this.instance_2.parent = this;
	this.instance_2.setTransform(333.1,43.6,1,1,0,0,0,87.5,21.6);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(166).to({_off:false},0).to({regY:21.7,rotation:-5.5,x:113,y:43.7},10,cjs.Ease.get(1)).to({regY:21.6,rotation:0,x:123.1,y:43.6},3,cjs.Ease.get(1)).wait(48).to({rotation:45,x:262.8,y:-43.2,alpha:0},7,cjs.Ease.get(-1)).to({_off:true},3).wait(3));

	// rtet
	this.instance_3 = new lib.rtet();
	this.instance_3.parent = this;
	this.instance_3.setTransform(101.3,119.5,0.733,0.733,21.3,0,0,99,10.9);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(83).to({_off:false},0).to({regX:98.7,regY:10.7,scaleX:1,scaleY:1,rotation:0,x:117.7,y:131.3,alpha:1},8,cjs.Ease.get(1)).wait(69).to({x:-122.3},6,cjs.Ease.get(1)).to({_off:true},1).wait(73));

	// trtr
	this.instance_4 = new lib.trtr();
	this.instance_4.parent = this;
	this.instance_4.setTransform(111.1,93.6,0.733,0.733,21.3,0,0,98.4,19.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(81).to({_off:false},0).to({regX:98.2,regY:19.6,scaleX:1,scaleY:1,rotation:0,x:117.4,y:93.3,alpha:1},8,cjs.Ease.get(1)).wait(70).to({x:-122.6},6,cjs.Ease.get(1)).to({_off:true},1).wait(74));

	// icepeak
	this.instance_5 = new lib.fghfgh("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(120,341.2);

	this.instance_6 = new lib.fghf("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(340,341.2);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(77).to({startPosition:0},0).to({scaleX:1.53,scaleY:1.53,y:419.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(92).to({_off:false,scaleX:0.98,scaleY:1,x:116.8,y:341.2,alpha:1},8,cjs.Ease.get(1)).to({scaleX:1,x:120},4,cjs.Ease.get(1)).wait(52));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(176).to({_off:false},0).to({_off:true,scaleX:0.98,x:116.8},8,cjs.Ease.get(1)).wait(56));

	// ghj
	this.instance_7 = new lib.ghj();
	this.instance_7.parent = this;
	this.instance_7.setTransform(320.6,42.8,1,1,0,0,0,60.5,11.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(80).to({_off:false},0).to({x:120.6},8,cjs.Ease.get(1)).wait(70).to({x:-79.4},7,cjs.Ease.get(1)).to({_off:true},1).wait(74));

	// kkk
	this.instance_8 = new lib.kkk();
	this.instance_8.parent = this;
	this.instance_8.setTransform(320.6,43.6,1,1,0,0,0,75.8,21.9);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(80).to({_off:false},0).to({rotation:-1.5,x:117.6},8,cjs.Ease.get(1)).to({rotation:0,x:120.6},2,cjs.Ease.get(1)).wait(69).to({regX:75.7,rotation:3,x:-79.5,y:43.5},7,cjs.Ease.get(1)).to({_off:true},1).wait(73));

	// Символ 1
	this.instance_9 = new lib.hjklhj();
	this.instance_9.parent = this;
	this.instance_9.setTransform(320.1,220.8,1,1,0,0,0,95.8,30.9);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(7).to({_off:false},0).to({x:120.1},9,cjs.Ease.get(1)).wait(63).to({regY:31,scaleX:1.53,scaleY:1.53,rotation:-41,x:96.9,y:189.4,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(154));

	// hjghj
	this.instance_10 = new lib.hjghj();
	this.instance_10.parent = this;
	this.instance_10.setTransform(317.4,166.7,1,1,0,0,0,52.3,16.1);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(2).to({_off:false},0).to({x:117.4},9,cjs.Ease.get(1)).wait(67).to({regX:52.4,scaleX:1.53,scaleY:1.53,rotation:-41,x:52.6,y:144.3,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(155));

	// jkjklj
	this.instance_11 = new lib.jkjklj();
	this.instance_11.parent = this;
	this.instance_11.setTransform(318,166.9,1,1,0,0,0,75.9,21.9);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(4).to({_off:false},0).to({rotation:-3.9,x:116},8,cjs.Ease.get(1)).to({rotation:0,x:118},2,cjs.Ease.get(1)).wait(63).to({scaleX:1.53,scaleY:1.53,rotation:-41,x:53.3,y:144.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(156));

	// legal
	this.instance_12 = new lib.ttt();
	this.instance_12.parent = this;
	this.instance_12.setTransform(120.1,381.5,1,1,0,0,0,114.1,14.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(240));

	// bg
	this.instance_13 = new lib.hjkh();
	this.instance_13.parent = this;
	this.instance_13.setTransform(187.5,170,1,1,0,0,0,351.5,213);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(77).to({regX:351.4,regY:213.1,scaleX:1.13,scaleY:1.13,rotation:-45,x:155,y:165.1},5).to({regY:212.9,scaleX:0.57,scaleY:0.57,rotation:-90,x:100,y:200.1},5).wait(138).to({regX:351.2,regY:213,scaleX:1.13,scaleY:1.13,rotation:-45,x:144,y:185.1},7).to({regX:351.5,scaleX:1,scaleY:1,rotation:0,x:187.5,y:170},7).wait(1));

	// Слой 10
	this.instance_14 = new lib.hjkh();
	this.instance_14.parent = this;
	this.instance_14.setTransform(100,200.1,0.569,0.569,-90,0,0,351.4,212.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(240));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44,157,703,488);
// library properties:
lib.properties = {
	width: 240,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"imgs/1.jpg", id:"_1"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;