(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"300x600_atlas_NP_", frames: [[0,602,404,600],[0,1204,368,500],[0,0,442,600]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib._1b = function() {
	this.spriteSheet = ss["300x600_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["300x600_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._4b = function() {
	this.spriteSheet = ss["300x600_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.p3b = function() {
	this.initialize(img.p3b);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,270);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Path_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyRCbIAAk1MAkjAAAIAAE1g");
	this.shape.setTransform(117,15.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_1, new cjs.Rectangle(0,0,234,31), null);


(lib.t3b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AG9CTIAAg1IidAAIAAjuIAvAAIAADFIBRAAIAAjFIAuAAIAADFIAcAAIAABegAOEBaQgQgHgNgNQgJgKgFgMQgGgLgBgOQgCgNgBgPIgjAAIAABjIgvAAIAAjuIAvAAIAABhIAkAAQAAgRADgNQACgNAFgLQAFgKAIgJQANgNAQgHQARgGATAAQATAAARAGQAQAHANANQANANAFATQAGASgBAYIAAAZQABAUgCAPQgBAQgFAOQgFAOgLAMQgNANgQAHQgQAGgUAAQgTAAgRgGgAOXhlQgIADgFAGQgHAIgCAPQgDAPAAAWIAAAPIABAcQABALADAHQADAIAEAEQAGAHAHADQAIADAJAAQAJAAAIgDQAIgDAFgHQAIgIACgOQACgOAAgYIAAgOQAAgXgDgOQgCgOgHgIQgFgGgIgDQgIgEgJAAQgJAAgIAEgAr8BZQgQgGgNgNQgLgMgFgPQgFgPgBgPQgCgOABgOIAAgTQAAgYACgPQACgQAFgLQAFgLAJgJQANgNAQgHQARgGATAAQATAAARAGQAQAHANANQAMAMAGATQAGATAAAdIAAAZIgBAeQgCAQgFAOQgFAOgLAMQgNANgQAHQgQAGgUAAQgTAAgRgHgArphlQgHADgGAGQgIAJgCAQQgCARAAAWIAAAMQAAASACAQQACAPAIAJQAGAGAHADQAIADAJAAQAJAAAIgDQAIgDAFgGQAFgFACgIQADgHABgOIABglIgBgfQgBgMgDgIQgCgHgFgFQgFgGgIgDQgIgEgJAAQgJAAgIAEgAKWBeIAAiZIhdCZIgqAAIAAjuIAvAAIAACYIBdiYIAqAAIAADugADMBeIhUh8IAAB8IgvAAIAAjuIAvAAIAABxIBNhxIA4AAIhRBwIBZB+gAiCBeIAAjuICdAAIAAApIhuAAIAAA5IBdAAIAAApIhdAAIAAA6IBuAAIAAApgAjpBeIAAjFIg5AAIAABGQAAAlgFAZQgEAZgKAOQgJAOgOAGQgOAGgSAAIgTAAIAAgpIAHAAQAJAAAHgEQAIgDAFgKQAGgJADgSQADgRAAgcIAAhsICVAAIAADugAnQBeIAAjFIg5AAIAABGQAAAlgFAZQgEAZgKAOQgJAOgOAGQgOAGgSAAIgTAAIAAgpIAHAAQAJAAAHgEQAIgDAFgKQAGgJADgSQADgRAAgcIAAhsICVAAIAADugAt8BeIhUh8IAAB8IgvAAIAAjuIAvAAIAABxIBNhxIA4AAIhRBwIBZB+g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3b, new cjs.Rectangle(-102.4,-14.7,204.9,29.5), null);


(lib.t3a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AOmBLQgKgFgJgIQgGgHgDgHQgEgIgBgIQgBgJAAgKIgYAAIAABBIgeAAIAAibIAeAAIAAA/IAYAAQAAgLACgIQABgJADgHQAEgGAFgGQAIgJALgEQALgEAMAAQANAAALAEQAKAEAJAJQAIAIAEAMQADAMAAAQIAAAPQAAANgBALQAAAKgEAJQgDAJgHAIQgJAIgKAFQgLAEgMAAQgNAAgLgEgAOygxQgFACgDAEQgFAFgBAKQgCAKAAAOIAAAJIABATIACAMIAFAHQAEAEAFADQAFACAFAAQAGAAAFgCQAFgDAEgEQAFgFABgJQACgKAAgQIAAgIQAAgPgCgJQgCgJgEgFQgEgEgFgCQgFgCgGAAQgGAAgFACgAhdBLQgLgFgIgIQgHgIgEgKQgDgJgBgKIAAgTIAAgMIABgZQABgKAEgHQADgHAGgGQAIgJALgEQALgEAMAAQANAAAKAEQALAEAIAJQAIAIAEAMQAEAMAAATIAAAPIgBAVQgBAKgDAJQgDAJgIAIQgIAIgKAFQgLAEgNAAQgMAAgLgEgAhRgxQgFACgDAEQgFAGgCAKQgBALAAAPIAAAGQAAANABAKQABAKAGAGIAIAGQAFACAGAAQAGAAAFgCQAFgCAEgEQADgEABgFQACgFABgIIAAgYIAAgVQgBgHgCgFQgBgFgDgDQgEgEgFgCQgFgCgGAAQgGAAgFACgAoKBLQgKgFgIgIQgIgIgDgKQgDgJgBgKIgBgTIAAgMIABgZQACgKADgHQAEgHAGgGQAIgJAKgEQALgEANAAQAMAAALAEQALAEAIAJQAIAIAEAMQADAMAAATIAAAPIAAAVQgBAKgDAJQgEAJgHAIQgIAIgLAFQgLAEgMAAQgNAAgLgEgAn9gxQgFACgEAEQgFAGgBAKQgCALABAPIAAAGQgBANACAKQABAKAFAGIAJAGQAFACAGAAQAGAAAFgCQAFgCADgEQADgEACgFQACgFAAgIIABgYIgBgVQAAgHgCgFQgCgFgDgDQgDgEgFgCQgFgCgGAAQgGAAgFACgALPBOIAAgbIAMAAQAGAAAEgDQAEgCACgFIAFgLIgyhrIAfAAIAhBLIAehLIAfAAIg3CAQgDAIgFAFQgEAGgHAEQgHAEgJAAgAKMBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAIDBOIg0hRIAABRIgeAAIAAhRIg0BRIglAAIA4hSIgzhJIAkAAIAwBKIAAhKIAeAAIAABKIAwhKIAkAAIgzBJIA4BSgAEpBOIAAibIAeAAIAACbgACoBOIAAibIAeAAIAAA7IAfAAQAQAAALAGQALAGAGAKQAHALAAAOQAAAPgHAKQgGALgLAGQgMAHgPAAgADGAzIAdAAQAKgBAGgFQAGgGAAgKQAAgKgGgFQgGgGgKAAIgdAAgABlBOIAAiAIglAAIAAAtQAAAYgDAQQgDAQgGAKQgGAJgJAEQgJAEgMAAIgNAAIAAgbIAFAAQAGAAAFgDQAEgCAEgGQAEgGACgMQACgLAAgRIAAhHIBhAAIAACbgAi9BOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAmaBOIAAibIA9AAQAPAAAMAGQALAGAHALQAGALAAAOQAAAPgGALQgHAKgLAGQgMAGgPAAIgeAAIAAA7gAl7gHIAcAAQALAAAGgGQAGgGAAgKQAAgJgGgGQgGgGgLAAIgcAAgAqhBOIAAibIBiAAIAAAbIhDAAIAACAgAsHBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgAsZAYIgTg3IgTA3IAmAAgAujBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3a, new cjs.Rectangle(-101.5,-7.9,203,15.9), null);


(lib.t2c = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D7ABD").s().p("ALbFpQgigRgVggQgUgfgBgvIAAhnQABgvAUggQAVgfAigRQAhgOAqgBQAqABAhAOQAiARAVAfQAVAgAAAvIAABnQAAAvgVAfQgVAggiARQghAPgqAAQgqAAghgPgAL/BbQgOAOAAAfIAABeQAAAeAOAOQAOAPAZAAQAZAAAOgPQAOgOAAgeIAAheQAAgfgOgOQgOgPgZAAQgZAAgOAPgAkJFeQgygYgfgyQgegxgChHIAAk3QAChHAegwQAfgyAygZQA0gaA9AAQA9AAAzAaQAxAZAfAyQAfAwAABHIAAE3QAABHgfAxQgfAygxAYQgzAag9AAQg9AAg0gagAjZjjQgZAbgBAvIAAE0QABAvAZAaQAZAaAoABQAogBAZgaQAYgaAAgvIAAk0QAAgvgYgbQgZgagogBQgoABgZAagAtCFiQg1gWgigwQghgxgChNICHAAQADAyAdAXQAdAYAoAAQAsgBAcgaQAcgaAAgyQAAgvgbgbQgbgbgygBIgUAAIAAh1IAUAAQAwAAAYgbQAWgaAAgnQgBgugagYQgagZgmAAQgnABgZAXQgZAYgDAqIiHAAQAChCAfgwQAeguAzgaQAygZA/AAQBCAAAzAbQAzAbAcAvQAdAwAAA/QAAA8gXAkQgYAlglASQApAVAaAoQAbAoABBDQgBBKgfAwQggAyg2AYQg0AYhBAAQg9AAg1gWgAFXFzIFerkIBqAAIlfLkgAECgEQgigQgVgfQgTgggBgvIAAhnQABgvATgfQAVghAigPQAigQArAAQAoAAAjAQQAiAPAUAhQAUAfABAvIAABnQgBAvgUAgQgUAfgiAQQgjAQgoAAQgrAAgigQgAEmkRQgNAPAAAdIAABfQAAAdAOAPQAOAPAaAAQAYAAAOgPQAOgPAAgdIAAhfQAAgdgOgPQgOgPgYAAQgbAAgOAPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2c, new cjs.Rectangle(-95.7,-37.6,191.4,75.3), null);


(lib.t2b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ADyDRIAAhMIi8AAIAABMIg/AAIAAiHIAfAAQAOgWAJgeQAJgdAEgkQAEgkAAgnIAAhXIDNAAIAAEXIAnAAIAACHgAB+hhQAAAzgGArQgHAqgRAjIBpAAIAAjcIhLAAgAtSB+QgXgJgSgSQgRgRgHgUQgHgVgBgYQgCgXAAgdQAAgeACgYQABgYAHgUQAHgVARgRQASgRAXgKQAWgKAcAAQAgAAAaAMQAaAMASAYQARAYAGAjIhDAAQgFgUgOgOQgNgNgZgBQgOAAgLAFQgKAFgIAIQgGAHgEAKQgDAKgCASQgBATAAAgQAAAgABARQACATADAKQAEAKAGAGQAIAJAKAEQALAFAOAAQAZgBANgNQAOgNAFgVIBDAAQgGAjgRAYQgSAYgaAMQgaAMggAAQgcAAgWgKgANZCFIgUg8Ih5AAIgUA8IhFAAIB7lSIA0AAIB8FSgAMzARIgph6IgrB6IBUAAgAIhCFIh3iwIAACwIhCAAIAAlSIBCAAIAAChIBuihIBPAAIhyCfIB9CzgAh6CFIAAjZIiEDZIg7AAIAAlSIBDAAIAADYICEjYIA7AAIAAFSgAmvCFIh3iwIAACwIhDAAIAAlSIBDAAIAAChIBtihIBPAAIhyCfIB+Czg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2b, new cjs.Rectangle(-92.5,-20.8,185.1,41.8), null);


(lib.t2a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("ApRBLQgKgFgIgIQgIgIgDgJQgEgJAAgMIgBgYIABgYQAAgLAEgJQADgKAIgHQAIgJAKgEQALgEANAAQAOAAAMAFQAMAGAIALQAIAKADARIgfAAQgCgKgGgGQgHgGgLAAQgGAAgFACQgFACgEAEQgDADgBAEIgDANIAAAXIAAAXIADANQABAFADADQAEAEAFACQAFACAGAAQALAAAHgHQAGgGACgJIAfAAQgDAQgIALQgIALgMAFQgMAGgOAAQgNAAgLgEgAttBJQgLgFgIgLQgIgLgDgQIAeAAQACAKAHAGQAGAGAMABQAGAAAFgDQAFgCAEgEIAEgGQACgEAAgGIACgPIgxAAIAAgaIAwAAIgBgPIgCgJIgEgGQgEgEgFgDQgFgCgGAAQgLAAgHAGQgHAHgCAJIgeAAQADgQAHgLQAIgKAMgGQAMgFAPAAQANAAAKAEQALAEAIAJQAIAHADAKQADAJABALQABALgBANQABANgBALQgBAMgDAJQgDAJgIAIQgIAIgLAFQgKAEgNAAQgPAAgMgGgANuBOIAAg7IgZAAIgaA7IgkAAIAghBQgMgGgHgKQgHgLAAgPQAAgOAGgLQAHgLALgGQAMgGAPAAIA8AAIAACbgANBgtQgGAGAAAKQAAAKAGAGQAGAGAKAAIAdAAIAAgrIgdAAQgKAAgGAFgALwBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgALeAYIgTg3IgTA3IAmAAgAJUBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAF3BOIAAibIAfAAIAAA7IAfAAQAPAAALAGQAMAGAGAKQAGALAAAOQAAAPgGAKQgGALgMAGQgLAHgPAAgAGWAzIAcAAQALgBAGgFQAGgGAAgKQAAgKgGgFQgGgGgLAAIgcAAgAE1BOIAAiAIgmAAIAAAtQAAAYgDAQQgDAQgGAKQgGAJgJAEQgJAEgMAAIgMAAIAAgbIAEAAQAGAAAFgDQAFgCAEgGQADgGACgMQACgLAAgRIAAhHIBhAAIAACbgACvBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgACdAYIgTg3IgTA3IAmAAgAATBOIAAhaIgdA6IgUAAIgeg6IAABaIgfAAIAAibIAeAAIApBTIAohTIAeAAIAACbgAjfBOIAAibIBnAAIAAAbIhJAAIAAAlIA+AAIAAAaIg+AAIAAAmIBJAAIAAAbgAlpBOIAAibIA9AAQAPAAAMAGQALAGAHALQAGALAAAOQAAAPgGALQgHAKgLAGQgMAGgPAAIgeAAIAAA7gAlKgHIAcAAQALAAAGgGQAGgGAAgKQAAgJgGgGQgGgGgLAAIgcAAgAnIBOIAAiAIgpAAIAAgbIBwAAIAAAbIgpAAIAACAgAqkBOIg3hRIAABRIgeAAIAAibIAeAAIAABKIAzhKIAkAAIg0BJIA5BSg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2a, new cjs.Rectangle(-90.8,-7.9,181.6,15.9), null);


(lib.s3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.p3b();
	this.instance.parent = this;
	this.instance.setTransform(-10,-32);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.s3, new cjs.Rectangle(-10,-32,160,270), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AAiBEIgGgQIg3AAIgGAQIg5AAIA6iHIBBAAIA6CHgAAQATIgQgtIAAAAIgPAtIAfAAg");
	this.shape.setTransform(77.4,-1.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1D1E1C").s().p("AgaBEIAAhlIgyAAIAAgiICZAAIAAAiIgyAAIAABlg");
	this.shape_1.setTransform(52.4,-1.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1D1E1C").s().p("AAeBEIAAg2Ig7AAIAAA2Ig2AAIAAiHIA2AAIAAAvIA7AAIAAgvIA2AAIAACHg");
	this.shape_2.setTransform(25.5,-1.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1D1E1C").s().p("Ag9A7QgUgNAAggIAAhTIA2AAIAABRQAAAXAbAAQAcAAAAgXIAAhRIA2AAIAABTQAAAggUANQgTAMgrgBQgqABgTgMg");
	this.shape_3.setTransform(-3,-1.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1D1E1C").s().p("AhEBEIAAiHIA2AAIAABiIBTAAIAAAlg");
	this.shape_4.setTransform(-28.7,-1.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhNBBIAkhjQAEgLAMgJQANgLALABIgkBoIBzAAQgCAIgKAIQgNAJgRAAg");
	this.shape_5.setTransform(-67,-1.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0D7ABD").s().p("AiGCGQg3g3AAhPQAAhOA3g4QA4g3BOAAQBPAAA4A3QA3A4AABOQAABPg3A3Qg4A4hPAAQhOAAg4g4g");
	this.shape_6.setTransform(-67.4,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAiBEIgGgQIg3AAIgGAQIg5AAIA6iHIBBAAIA6CHgAAQATIgQgtIAAAAIgPAtIAfAAg");
	this.shape_7.setTransform(77.4,-1.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgaBEIAAhlIgyAAIAAgiICZAAIAAAiIgyAAIAABlg");
	this.shape_8.setTransform(52.4,-1.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAeBEIAAg2Ig7AAIAAA2Ig2AAIAAiHIA2AAIAAAvIA7AAIAAgvIA2AAIAACHg");
	this.shape_9.setTransform(25.5,-1.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag9A7QgUgNAAggIAAhTIA2AAIAABRQAAAXAbAAQAcAAAAgXIAAhRIA2AAIAABTQAAAggUANQgTAMgrgBQgqABgTgMg");
	this.shape_10.setTransform(-3,-1.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhEBEIAAiHIA2AAIAABiIBTAAIAAAlg");
	this.shape_11.setTransform(-28.7,-1.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiGCGQg3g3AAhPQAAhOA3g4QA4g3BOAAQBPAAA4A3QA3A4AABOQAABPg3A3Qg4A4hPAAQhOAAg4g4gAgVhCQgLAJgEALIgkBjIBxAAQARAAANgJQAKgIABgIIhyAAIAjhoIgCAAQgKAAgMAKg");
	this.shape_12.setTransform(-67.4,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-86.4,-19,173,38.1), null);


(lib.df = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1b();
	this.instance.parent = this;
	this.instance.setTransform(-202,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.df, new cjs.Rectangle(-202,-300,404,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#ECF4F4","#B3CEE4"],[0,0.984],0,-157.1,0,166.1).s().p("AzhfeMAAAg+7MAnDAAAMAAAA+7g");
	this.shape.setTransform(120,200,0.96,0.993);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(0,0,240,400), null);


(lib.bbb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._4b();
	this.instance.parent = this;
	this.instance.setTransform(38,-18);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bbb, new cjs.Rectangle(38,-18,442,600), null);


(lib.aaa = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._2();
	this.instance.parent = this;
	this.instance.setTransform(0,50);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.aaa, new cjs.Rectangle(0,50,368,500), null);


(lib.s4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bbb();
	this.instance.parent = this;
	this.instance.setTransform(178.5,219,1,1,0,0,0,267.5,250);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:48.5},99).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51,-49,442,600);


(lib.s2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa();
	this.instance.parent = this;
	this.instance.setTransform(184,190,1,1,0,0,0,184,250);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:64},100).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-10,368,500);


(lib.s1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.df();
	this.instance.parent = this;
	this.instance.setTransform(202,301);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:112},89).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,1,404,600);


(lib.legal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("At2CTIAAhAIAGAAIAAAFIADgCIACgCIAEgBIAEgBQAIAAAEAGQAEAGAAALQAAAMgEAFQgEAGgIAAIgEgBIgEgBIgCgBIgDgDIAAAZgAttBcQgDAEAAAJQAAAJADAEQADAEAGAAQAFAAADgEQADgEAAgJQAAgJgDgEQgDgEgGAAQgFAAgDAEgA0TCTIAAhAIAGAAIAAAFIADgCIACgCIAEgBIAEgBQAIAAAEAGQAEAGAAALQAAAMgEAFQgEAGgIAAIgEgBIgEgBIgCgBIgDgDIAAAZgA0KBcQgDAEAAAJQAAAJADAEQADAEAGAAQAFAAADgEQADgEAAgJQAAgJgDgEQgDgEgGAAQgFAAgDAEgAlnB/IgFgDIgCgEIgBgFQAAgGAEgEQAEgDAHAAIANAAIAAgEQABgFgDgDQgDgCgGAAIgHABQgCABgCADIgEgEQACgEAEgBQAEgCAFAAQAJABAFADQAEAEAAAHIAAAeIgHAAIAAgEQgCADgDABIgHABIgIgBgAlmBtQgDACAAAEQAAADADACQACACAFAAIAGAAQACgBACgCIACgDIAAgEIAAgFIgMAAQgFAAgCACgAnmB/IgFgDIgDgGIgBgHIAAgcIAGAAIAAAbQAAAGADADQADADAFAAQAFAAADgDQADgDAAgGIAAgbIAHAAIAAAsIgHAAIAAgFQgCADgDABQgDACgEAAIgHgBgAtDB6QgFgGAAgLQABgLAEgGQAFgFAJgBQAIABAFAFQAFAGAAAKIAAADIgeAAIAAAFIABADQACAEADABQADACAEAAIADAAIADgBIADgBIADgDIAEAEIgEADIgEACIgDABIgFABQgKAAgFgGgAsqBmIAAgEIgBgCQgBgEgDgCQgCgCgEAAIgHACQgCABgCAEIgBADIAAAEIAXAAIAAAAgAudB+QgDgBgDgCIgEgHIgBgLIABgKQACgFACgCIAGgEQADgCAEAAIAHACIAGAEQADACABAFQABAEAAAGQAAAGgBAFQgBAEgDADQgDACgDABIgHACQgEAAgDgCgAuaBZIgEACQgCACgBAEIgBAIIABAJIADAFIAEACIAEABIAFgBIADgCQACgCABgDIABgJIgBgIQgBgEgCgCIgDgCIgFgBIgEABgAvvCAQgIAAgEgEQgEgDAAgGQAAgGAEgEQAEgDAIAAIANAAIAAgEQAAgFgDgDQgDgCgGAAIgDAAIgDABIgCACIgDACIgEgEIADgDIADgCIAEgBIAGgBQAIAAAFAEQAEAEAAAHIAAAeIgGAAIAAgEIgDACIgCACIgDABIgFAAgAv2BtQgCACAAAEQAAAEACABQADACAFAAQAHAAACgCQADgDAAgFIAAgFIgMAAQgFAAgDACgAwkB+QgEgBgEgEIAEgEIAGAEIAHABIAFgBIAFgCQAAgBAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBQAAgDgCgCQgDgCgEAAIgGAAIAAgFIAGAAQAEAAACgCQADgCAAgDQAAgEgDgBQgDgCgEAAIgHABIgFADIgEgFQAEgCAEgBQAEgCAEAAQAFAAADACQAEABACADQACADAAADQAAAEgCACQgCADgDABQADABACADQADADAAAEQAAAEgDADQgCADgEABQgEACgEAAQgFAAgFgCgAywCAQgIAAgEgEQgEgDAAgGQAAgGAEgEQAEgDAHAAIANAAIAAgEQABgFgDgDQgDgCgGAAIgEAAIgDABIgCACIgCACIgEgEIACgDIADgCIAEgBIAGgBQAJAAAEAEQAFAEAAAHIAAAeIgHAAIAAgEIgCACIgDACIgDABIgEAAgAy3BtQgDACAAAEQAAAEADABQACACAGAAQAGAAADgCQADgDgBgFIAAgFIgMAAQgFAAgCACgA06B+QgDgBgDgCIgEgHIgBgLIABgKQACgFACgCIAGgEQADgCAEAAIAHACIAGAEQADACABAFQABAEAAAGQAAAGgBAFQgBAEgDADQgDACgDABIgHACQgEAAgDgCgA03BZIgEACQgCACgBAEIgBAIIABAJIADAFIAEACIAEABIAFgBIADgCQACgCABgDIABgJIgBgIQgBgEgCgCIgDgCIgFgBIgEABgAkHB/IAAgsIAGAAIAAAsgAkiB/IAAgnIgGAAIAAgFIAGAAIAAgIIABgGQABgDADgBQACgCAEAAIAFAAIAAAGIgEAAQAAAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAADIAAAIIAKAAIAAAFIgKAAIAAAngAk8B/IAAgIIAIAAIAAAIgAl9B/QgEAAgDgBQgCgCgBgDQgCgCAAgEIAAgbIgFAAIAAgFIAFAAIAAgOIAHAAIAAAOIAJAAIAAAFIgJAAIAAAbQAAABAAABQAAAAAAABQAAAAABABQAAAAAAABQABAAAAABQABAAAAAAQABAAAAABQABAAABAAIADAAIAAAFgAmgB/IAAgbQAAgGgDgDQgDgDgFAAQgFAAgDADQgDADAAAGIAAAbIgGAAIAAhAIAGAAIAAAZIAGgEIAHgCQAHABAEAEQAFAEAAAIIAAAcgAn+B/QgGAAgDgDQgCgDAAgGIAAg0IAGAAIAAA0IABAFQACACADAAIAEAAIAAAFgAoiB/IAAgIIAJAAIAAAIgAo/B/IgLgiIgMAiIgGAAIgOgsIAHAAIAKAkIAMgkIAGAAIALAkIAKgkIAHAAIgOAsgAqAB/IgLgiIgMAiIgGAAIgOgsIAHAAIAKAkIAMgkIAGAAIALAkIAKgkIAHAAIgOAsgArBB/IgLgiIgMAiIgGAAIgOgsIAHAAIAKAkIAMgkIAGAAIALAkIAKgkIAHAAIgOAsgAsTB/IAAgIIAIAAIAAAIgAvEB/IAAgmIgPAAIAAgGIAkAAIAAAGIgOAAIAAAmgAw9B/IAAgiIgXAiIgHAAIAAgsIAHAAIAAAiIAXgiIAGAAIAAAsgAxxB/IAAgUIgWAAIAAAUIgGAAIAAgsIAGAAIAAATIAWAAIAAgTIAGAAIAAAsgAziB/IAAgsIAcAAIAAAGIgVAAIAAAmgAsTBkIAAgIIAIAAIAAAIgAkHBGIAAgHIAHAAIAAAHgAJkAqIAAg/IAGAAIAAAFIADgCIACgCIAEgBIAEgBQAIAAAEAGQAEAGAAAKQAAAMgEAFQgEAGgIAAIgEgBIgEgBIgCgBIgDgDIAAAZgAJtgMQgDAEAAAIQAAAJADAEQADAEAGAAQAFAAADgEQADgEAAgJQAAgIgDgEQgDgEgGAAQgFAAgDAEgAEsAqIAAg/IAGAAIAAAFIADgCIACgCIAEgBIAEgBQAIAAAEAGQAEAGAAAKQAAAMgEAFQgEAGgIAAIgEgBIgEgBIgCgBIgDgDIAAAZgAE1gMQgDAEAAAIQAAAJADAEQADAEAGAAQAFAAADgEQADgEAAgJQAAgIgDgEQgDgEgGAAQgFAAgDAEgAqXAqIAAg/IAHAAIAAAFIACgCIADgCIADgBIAEgBQAJAAAEAGQAEAGAAAKQAAAMgEAFQgFAGgIAAIgEgBIgDgBIgCgBIgDgDIAAAZgAqOgMQgCAEAAAIQAAAJACAEQADAEAGAAQAGAAACgEQADgEAAgJQAAgIgDgEQgCgEgGAAQgGAAgDAEgArwAqIAAgTQgLgBgGgFQgGgGAAgLQAAgKAGgFQAGgGALgBIAAgTIAGAAIAAATQALABAGAGQAFAFAAAKQAAALgGAGQgFAFgLABIAAATgArqARQAIAAAEgFQAEgEAAgIQAAgEgCgDQgBgEgEgCQgDgDgGAAgAr6gNQgDACgCAEQgBADAAAEQAAAIAEAEQAEAFAIAAIAAghQgGAAgEADgAyjAqIAAg/IAGAAIAAAFIADgCIACgCIAEgBIAEgBQAIAAAEAGQAEAGAAAKQAAAMgEAFQgEAGgIAAIgEgBIgEgBIgCgBIgDgDIAAAZgAyagMQgDAEAAAIQAAAJADAEQADAEAGAAQAFAAADgEQADgEAAgJQAAgIgDgEQgDgEgGAAQgFAAgDAEgAjbApIAAgGIACAAQABAAABAAQAAAAABAAQAAAAABAAQAAAAABgBIADgEIADgJIgQgqIAHAAIAMAjIAMgjIAHAAIgUA2QgCAEgDACQgCACgFAAgANFAjIAAgNIghAAIAAANIgGAAIAAgSIAFAAIADgIIACgJIABgNIAAgIIAcAAIAAAmIAGAAIAAASgAMvgHIgBAJIgBAIIgDAHIAUAAIAAggIgPAAgAGtAjIAAgNIghAAIAAANIgGAAIAAgSIAFAAIADgIIACgJIABgNIAAgIIAcAAIAAAmIAGAAIAAASgAGXgHIgBAJIgBAIIgDAHIAUAAIAAggIgPAAgACbAOIAIAAIAAAOIgIAHgAnYAjIAAgNIgjAAIAAgrIAGAAIAAAmIAWAAIAAgmIAGAAIAAAmIAHAAIAAASgAy1AjIAAgNIggAAIAAANIgHAAIAAgSIAGAAIADgIIACgJIAAgNIAAgIIAcAAIAAAmIAHAAIAAASgAzKgHIgBAJIgCAIIgCAHIAUAAIAAggIgPAAgASvARQgFgGAAgLQAAgKAFgGQAFgFAIgBQAJABAEAFQAFAGAAAKIAAACIgeAAIABAFIABADQABAEADABQADACAFAAIADAAIACgBIADgBIADgDIAEAEIgDADIgEACIgEABIgFABQgJAAgFgGgATIgCIgBgEIAAgCQgBgEgDgCQgDgCgEAAIgGACQgDABgBAEIgBADIgBAEIAYAAIAAAAgAR/ARQgFgGAAgLQABgKAEgGQAFgFAJgBQAIABAFAFQAFAGAAAKIAAACIgeAAIAAAFIABADQACAEADABQADACAEAAIADAAIADgBIADgBIADgDIAEAEIgEADIgEACIgDABIgFABQgKAAgFgGgASYgCIAAgEIgBgCQgBgEgDgCQgCgCgEAAIgHACQgCABgCAEIgBADIAAAEIAXAAIAAAAgANZARQgFgGAAgLQAAgKAFgGQAFgFAIgBQAJABAEAFQAFAGAAAKIAAACIgeAAIABAFIABADQABAEADABQADACAFAAIADAAIACgBIADgBIADgDIAEAEIgDADIgEACIgEABIgFABQgJAAgFgGgANygCIgBgEIAAgCQgBgEgDgCQgDgCgEAAIgGACQgDABgBAEIgBADIgBAEIAYAAIAAAAgAL3ARQgFgGAAgLQABgKAEgGQAFgFAJgBQAIABAFAFQAFAGAAAKIAAACIgeAAIAAAFIABADQACAEADABQADACAEAAIADAAIADgBIADgBIADgDIAEAEIgEADIgEACIgDABIgFABQgKAAgFgGgAMQgCIAAgEIgBgCQgBgEgDgCQgCgCgEAAIgHACQgCABgCAEIgBADIAAAEIAXAAIAAAAgAKeAVQgEgBgCgCIgEgHIgBgLIABgJQABgFADgCIAGgEQADgCAEAAIAHACIAFAEQADACABAFQACAEAAAFQAAAGgCAFQgBAEgDADQgCACgDABIgHACQgEAAgDgCgAKggPIgDACQgCACgBAEIgBAHIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgHQAAgEgCgCIgEgCIgEgBIgFABgAHuARQgFgGAAgLQAAgKAFgGQAFgFAIgBQAJABAEAFQAFAGAAAKIAAACIgeAAIABAFIABADQABAEADABQADACAFAAIADAAIACgBIADgBIADgDIAEAEIgDADIgEACIgEABIgFABQgJAAgFgGgAIHgCIgBgEIAAgCQgBgEgDgCQgDgCgEAAIgGACQgDABgBAEIgBADIgBAEIAYAAIAAAAgAEFAVQgDgBgDgCIgEgHIgBgLIABgJQACgFACgCIAGgEQADgCAEAAIAHACIAGAEQADACABAFQABAEAAAFQAAAGgBAFQgBAEgDADQgDACgDABIgHACQgEAAgDgCgAEIgPIgEACQgCACgBAEIgBAHIABAJIADAFIAEACIAEABIAFgBIADgCQACgCABgDIABgJIgBgHQgBgEgCgCIgDgCIgFgBIgEABgAhJAVQgEgBgCgCIgEgHIgBgLIABgJQABgFADgCIAGgEQADgCAEAAIAHACIAFAEQADACABAFQACAEAAAFQAAAGgCAFQgBAEgDADQgCACgDABIgHACQgEAAgDgCgAhHgPIgDACQgCACgBAEIgBAHIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgHQAAgEgCgCIgEgCIgEgBIgFABgAisARQgFgGgBgLQABgKAFgGQAFgFAJgBIAEABIAEABIADACIAEADIgFAEIgDgCIgCgCIgCgBIgDAAQgGAAgEAEQgDAFAAAHQAAAIADAFQAEAEAGAAIADAAIACgBIACgBIADgDIAFAEIgEAEIgDABIgEABIgEABQgJAAgFgGgAkYAUQgEgDgCgGIgBgGIAAgGIAAgHIAAgKIABgIIACgFIADgEQADgDAFgBIAJgCIAJAAIAAAGIgHAAIgIABQgEABgDACQgDADgBAEQgBAEABAFQABgDAEgBQADgCAFAAIAGABIAFADQADADABAEQACAFAAAFQAAAHgCAEQgBAEgDADIgFAEIgHABQgGAAgFgDgAkSgPIgDADQgCACgBADIgBAHIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgHQAAgDgCgCIgEgDIgEgBIgFABgAlEAVQgEgBgCgCIgEgHIgBgLIABgJQABgFADgCIAGgEQADgCAEAAIAHACIAFAEQADACABAFQACAEAAAFQAAAGgCAFQgBAEgDADQgCACgDABIgHACQgEAAgDgCgAlCgPIgDACQgCACgBAEIgBAHIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgHQAAgEgCgCIgEgCIgEgBIgFABgAoeAXQgIAAgEgEQgEgDAAgGQAAgGAEgEQAEgCAHAAIANAAIAAgEQABgFgDgDQgDgCgGAAIgEAAIgDABIgCACIgCACIgEgEIACgDIADgCIAEgBIAGgBQAJAAAEAEQAFAEAAAHIAAAdIgHAAIAAgEIgCACIgDACIgDABIgEAAgAolAEQgDACAAAEQAAAEADABQACACAGAAQAGAAADgCQADgDgBgFIAAgFIgMAAQgFAAgCACgAq9AVQgEgBgCgCIgEgHIgBgLIABgJQABgFADgCIAGgEQADgCAEAAIAHACIAFAEQADACABAFQACAEAAAFQAAAGgCAFQgBAEgDADQgCACgDABIgHACQgEAAgDgCgAq7gPIgDACQgCACgBAEIgBAHIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgHQAAgEgCgCIgEgCIgEgBIgFABgAvUAXQgIAAgEgEQgEgDAAgGQAAgGAEgEQAEgCAIAAIANAAIAAgEQAAgFgDgDQgDgCgGAAIgDAAIgDABIgCACIgDACIgEgEIADgDIADgCIAEgBIAGgBQAIAAAFAEQAEAEAAAHIAAAdIgGAAIAAgEIgDACIgCACIgDABIgFAAgAvbAEQgCACAAAEQAAAEACABQADACAFAAQAHAAACgCQADgDAAgFIAAgFIgMAAQgFAAgDACgAw9AUQgEgDgCgGIgBgGIAAgGIAAgHIAAgKIABgIIACgFIADgEQADgDAFgBIAJgCIAJAAIAAAGIgHAAIgIABQgEABgDACQgDADgBAEQgBAEABAFQABgDAEgBQADgCAFAAIAGABIAFADQADADABAEQACAFAAAFQAAAHgCAEQgBAEgDADIgFAEIgHABQgGAAgFgDgAw3gPIgDADQgCACgBADIgBAHIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgHQAAgDgCgCIgEgDIgEgBIgFABgAxpAVQgEgBgCgCIgEgHIgBgLIABgJQABgFADgCIAGgEQADgCAEAAIAHACIAFAEQADACABAFQACAEAAAFQAAAGgCAFQgBAEgDADQgCACgDABIgHACQgEAAgDgCgAxngPIgDACQgCACgBAEIgBAHIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgHQAAgEgCgCIgEgCIgEgBIgFABgAz8AVQgDgBgDgCIgEgHIgBgLIABgJQACgFACgCIAGgEQADgCAEAAIAHACIAGAEQADACABAFQABAEAAAFQAAAGgBAFQgBAEgDADQgDACgDABIgHACQgEAAgDgCgAz5gPIgEACQgCACgBAEIgBAHIABAJIADAFIAEACIAEABIAFgBIADgCQACgCABgDIABgJIgBgHQgBgEgCgCIgDgCIgFgBIgEABgARQAWIAAghIgXAhIgHAAIAAgrIAHAAIAAAhIAXghIAGAAIAAArgAQFAWIAAgRIgLAAIgJARIgIAAIALgSQgFgBgDgDQgDgDAAgFQAAgGAEgDQAEgEAGAAIAUAAIAAArgAPygOQgCADAAADQAAAEACACQACACAFAAIAMAAIAAgQIgMAAQgFAAgCACgAPWAWIAAghIgXAhIgHAAIAAgrIAHAAIAAAhIAXghIAGAAIAAArgAOiAWIAAgUIgWAAIAAAUIgGAAIAAgrIAGAAIAAATIAWAAIAAgTIAGAAIAAArgALEAWIAAgrIAVAAQAGAAADADQAEADAAAGQAAADgCADQgCACgDABQAEABACACQACADAAAEQAAAGgEADQgDADgGAAgALLARIANAAQAEAAACgCQACgCAAgEQAAgDgCgCQgCgCgEAAIgNAAgALLgCIANAAQAEAAACgCQACgCAAgDQAAgDgCgCQgCgBgEAAIgNAAgAJNAWIAAglIgVAAIAAAlIgHAAIAAgrIAjAAIAAArgAHaAWIgVgWIAUgVIAIAAIgUAVIAWAWgAG/AWIAAgrIAGAAIAAAVIAAAWgAF2AWIAAgRIgLAAIgKARIgHAAIAKgSQgFgBgCgDQgDgDAAgFQAAgGAEgDQADgEAHAAIAUAAIAAArgAFjgOQgDADAAADQAAAEADACQACACAEAAIANAAIAAgQIgNAAQgEAAgCACgADmAWIAAglIgWAAIAAAlIgGAAIAAgrIAiAAIAAArgACIAWIgKgRIgLARIgIAAIAPgWIgOgVIAIAAIAKAQIAKgQIAIAAIgPAVIAPAWgABaAWIAAgRIgLAAIgKARIgHAAIAKgSQgFgBgCgDQgDgDAAgFQAAgGAEgDQADgEAHAAIAUAAIAAArgABHgOQgDADAAADQAAAEADACQACACAEAAIANAAIAAgQIgNAAQgEAAgCACgAAqAWIAAghIgXAhIgGAAIAAgrIAGAAIAAAhIAXghIAHAAIAAArgAgjAWIAAgrIAVAAQAGAAADADQAEADAAAGQAAADgCADQgCACgDABQAEABACACQACADAAAEQAAAGgEADQgDADgGAAgAgcARIANAAQAEAAACgCQACgCAAgEQAAgDgCgCQgCgCgEAAIgNAAgAgcgCIANAAQAEAAACgCQACgCAAgDQAAgDgCgCQgCgBgEAAIgNAAgAhpAWIAAglIgPAAIAAAPQAAAIgCAFQgCAFgDACQgDACgEAAIgDAAIAAgFIABAAIADgBIADgCIADgGIAAgKIAAgTIAdAAIAAArgAl6AWIAAgRIgLAAIgKARIgHAAIAKgSQgFgBgCgDQgDgDAAgFQAAgGAEgDQADgEAHAAIAUAAIAAArgAmNgOQgDADAAADQAAAEADACQACACAEAAIANAAIAAgQIgNAAQgEAAgCACgAmqAWIAAghIgXAhIgGAAIAAgrIAGAAIAAAhIAXghIAHAAIAAArgApBAWIAAgeIgNAXIgFAAIgMgXIAAAeIgHAAIAAgrIAHAAIAPAdIAPgdIAGAAIAAArgAsbAWIAAgUIgVAAIAAAUIgHAAIAAgrIAHAAIAAATIAVAAIAAgTIAHAAIAAArgAtNAWIAAghIgXAhIgHAAIAAgrIAHAAIAAAhIAXghIAGAAIAAArgAuYAWIAAgRIgLAAIgJARIgIAAIALgSQgFgBgDgDQgDgDAAgFQAAgGAEgDQAEgEAGAAIAUAAIAAArgAurgOQgCADAAADQAAAEACACQACACAFAAIAMAAIAAgQIgMAAQgFAAgCACgAv3AWIAAgUIgVAAIAAAUIgHAAIAAgrIAHAAIAAATIAVAAIAAgTIAHAAIAAArgA0cAWIAAg5IgfAAIAAA5IgGAAIAAg/IAsAAIAAA/gATDgfIAAgIIAGAAIAAAIgASwgfIAAgIIAGAAIAAAIgAPOg+IAAhAIAHAAIAAAFIACgCIADgCIADgBIAEgBQAJAAAEAGQAEAGAAALQAAAMgEAFQgFAGgIAAIgEgBIgDgBIgCgBIgDgDIAAAZgAPXh1QgCAEAAAJQAAAJACAEQADAEAGAAQAGAAACgEQADgEAAgJQAAgJgDgEQgCgEgGAAQgGAAgDAEgAGrg+IAAhAIAHAAIAAAFIACgCIADgCIADgBIAEgBQAJAAAEAGQAEAGAAALQAAAMgEAFQgFAGgIAAIgEgBIgDgBIgCgBIgDgDIAAAZgAG0h1QgCAEAAAJQAAAJACAEQADAEAGAAQAGAAACgEQADgEAAgJQAAgJgDgEQgCgEgGAAQgGAAgDAEgAqqg+IAAhAIAHAAIAAAFIACgCIADgCIADgBIAEgBQAJAAAEAGQAEAGAAALQAAAMgEAFQgFAGgIAAIgEgBIgDgBIgCgBIgDgDIAAAZgAqhh1QgCAEAAAJQAAAJACAEQADAEAGAAQAGAAACgEQADgEAAgJQAAgJgDgEQgCgEgGAAQgGAAgDAEgAu0g+IAAhAIAGAAIAAAFIADgCIACgCIAEgBIAEgBQAIAAAEAGQAEAGAAALQAAAMgEAFQgEAGgIAAIgEgBIgEgBIgCgBIgDgDIAAAZgAurh1QgDAEAAAJQAAAJADAEQADAEAGAAQAFAAADgEQADgEAAgJQAAgJgDgEQgDgEgGAAQgFAAgDAEgAMBhFIAAgNIghAAIAAANIgGAAIAAgSIAFAAIADgIIACgJIABgOIAAgIIAcAAIAAAnIAGAAIAAASgALrhwIgBAKIgBAIIgDAHIAUAAIAAghIgPAAgAhchFIAAgNIgjAAIAAgsIAHAAIAAAnIAVAAIAAgnIAHAAIAAAnIAGAAIAAASgAnJhFIAAgNIggAAIAAANIgHAAIAAgSIAGAAIADgIIACgJIAAgOIAAgIIAcAAIAAAnIAHAAIAAASgAnehwIgBAKIgCAIIgCAHIAUAAIAAghIgPAAgAyRhFIAAgNIgjAAIAAgsIAGAAIAAAnIAWAAIAAgnIAGAAIAAAnIAHAAIAAASgATYhUQgEgCgDgEQgCgEAAgFQAAgGADgEQACgEAEgCIgGgGQgCgDAAgFQAAgFACgEQADgEAEgCQAEgCAFAAQAFAAAEACQAEACACAEQACAEAAAFQAAAFgCADIgGAGQAEACADAEQADAEAAAGQAAAFgDAEQgCAEgFACQgEADgFAAQgGAAgEgDgATbhuIgEAEQgCADAAADQAAAEACADIAEAEIAHACIAGgCQADgBABgDQACgDAAgEQAAgDgCgDQgBgDgDgBQgDgCgDAAQgEAAgDACgATaiJQgDADAAAFQAAAFADADQADADAFAAQAFAAADgDQADgDAAgFQAAgFgDgDQgDgEgFAAQgFAAgDAEgAR7hTQgEgDgCgEQgDgEAAgFIAAgeQAAgFADgEQACgEAEgCQAEgCAFAAQAFAAAEACQAEACACAEQACAEAAAFIAAAeQAAAFgCAEQgCAEgEADQgEACgFAAQgFAAgEgCgAR7iJQgCADAAAGIAAAdQAAAFACAEQADADAGAAQAFAAADgDQADgEAAgFIAAgdQAAgGgDgDQgDgEgFAAQgGAAgDAEgAOkhUQgEgDgCgGIgBgGIAAgHIAAgHIAAgKIABgIIACgFIADgEQADgDAFgBIAJgCIAJAAIAAAGIgHAAIgIABQgEABgDACQgDADgBAEQgBAEABAFQABgDAEgBQADgCAFAAIAGABIAFADQADADABAEQACAFAAAGQAAAHgCAEQgBAEgDADIgFAEIgHABQgGAAgFgDgAOqh4IgDADQgCACgBADIgBAIIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgIQAAgDgCgCIgEgDIgEgBIgFABgAN7hRQgIAAgEgEQgEgDAAgGQAAgGAEgEQAEgDAIAAIANAAIAAgEQAAgFgDgDQgDgCgGAAIgDAAIgDABIgCACIgDACIgEgEIADgDIADgCIAEgBIAGgBQAIAAAFAEQAEAEAAAHIAAAeIgGAAIAAgEIgDACIgCACIgDABIgFAAgAN0hkQgCACAAAEQAAAEACABQADACAFAAQAHAAACgCQADgDAAgFIAAgFIgMAAQgFAAgDACgAMVhXQgFgGAAgLQAAgLAFgGQAFgFAIgBQAJABAEAFQAFAGAAAKIAAADIgeAAIABAFIABADQABAEADABQADACAFAAIADAAIACgBIADgBIADgDIAEAEIgDADIgEACIgEABIgFABQgJAAgFgGgAMuhrIgBgEIAAgCQgBgEgDgCQgDgCgEAAIgGACQgDABgBAEIgBADIgBAEIAYAAIAAAAgAKhhUQgEgCgCgEQgCgEAAgGIABgHIADgHIAPggIAHAAIgOAdIAGgBQAGAAADACQAEACACAEQACAEAAAGQAAAFgCAFQgCAEgEACQgEADgGAAQgFAAgEgDgAKihtQgDADAAAGQAAAGADADQADAEAFAAQAGAAADgEQADgDAAgGQAAgEgCgCQgBgDgCgCQgDgCgEAAQgFAAgDAEgAJehTQgEgBgCgCIgEgHIgBgLIABgKQABgFADgCIAGgEQADgCAEAAIAHACIAFAEQADACABAFQACAEAAAGQAAAGgCAFQgBAEgDADQgCACgDABIgHACQgEAAgDgCgAJgh4IgDACQgCACgBAEIgBAIIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgIQAAgEgCgCIgEgCIgEgBIgFABgAGBhUQgEgDgCgGIgBgGIAAgHIAAgHIAAgKIABgIIACgFIADgEQADgDAFgBIAJgCIAJAAIAAAGIgHAAIgIABQgEABgDACQgDADgBAEQgBAEABAFQABgDAEgBQADgCAFAAIAGABIAFADQADADABAEQACAFAAAGQAAAHgCAEQgBAEgDADIgFAEIgHABQgGAAgFgDgAGHh4IgDADQgCACgBADIgBAIIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgIQAAgDgCgCIgEgDIgEgBIgFABgAElhTQgDgBgDgCIgEgHIgBgLIABgKQACgFACgCIAGgEQADgCAEAAIAHACIAGAEQADACABAFQABAEAAAGQAAAGgBAFQgBAEgDADQgDACgDABIgHACQgEAAgDgCgAEoh4IgEACQgCACgBAEIgBAIIABAJIADAFIAEACIAEABIAFgBIADgCQACgCABgDIABgJIgBgIQgBgEgCgCIgDgCIgFgBIgEABgAA2hXQgFgGgBgLQABgLAFgGQAFgFAJgBIAEABIAEABIADACIAEADIgFAEIgDgCIgCgCIgCgBIgDAAQgGAAgEAEQgDAFAAAIQAAAIADAFQAEAEAGAAIADAAIACgBIACgBIADgDIAFAEIgEAEIgDABIgEABIgEABQgJAAgFgGgAjPhRQgIAAgEgEQgEgDAAgGQAAgGAEgEQAEgDAIAAIANAAIAAgEQAAgFgDgDQgDgCgGAAIgDAAIgDABIgCACIgDACIgEgEIADgDIADgCIAEgBIAGgBQAIAAAFAEQAEAEAAAHIAAAeIgGAAIAAgEIgDACIgCACIgDABIgFAAgAjWhkQgCACAAAEQAAAEACABQADACAFAAQAHAAACgCQADgDAAgFIAAgFIgMAAQgFAAgDACgAm1hXQgFgGAAgLQABgLAEgGQAFgFAJgBQAIABAFAFQAFAGAAAKIAAADIgeAAIAAAFIABADQACAEADABQADACAEAAIADAAIADgBIADgBIADgDIAEAEIgEADIgEACIgDABIgFABQgKAAgFgGgAmchrIAAgEIgBgCQgBgEgDgCQgCgCgEAAIgHACQgCABgCAEIgBADIAAAEIAXAAIAAAAgAoWhXQgFgGAAgLQAAgLAFgGQAFgFAIgBQAJABAEAFQAFAGAAAKIAAADIgeAAIABAFIABADQABAEADABQADACAFAAIADAAIACgBIADgBIADgDIAEAEIgDADIgEACIgEABIgFABQgJAAgFgGgAn9hrIgBgEIAAgCQgBgEgDgCQgDgCgEAAIgGACQgDABgBAEIgBADIgBAEIAYAAIAAAAgApwhTQgDgBgDgCIgEgHIgBgLIABgKQACgFACgCIAGgEQADgCAEAAIAHACIAGAEQADACABAFQABAEAAAGQAAAGgBAFQgBAEgDADQgDACgDABIgHACQgEAAgDgCgApth4IgEACQgCACgBAEIgBAIIABAJIADAFIAEACIAEABIAFgBIADgCQACgCABgDIABgJIgBgIQgBgEgCgCIgDgCIgFgBIgEABgAt6hTQgEgBgCgCIgEgHIgBgLIABgKQABgFADgCIAGgEQADgCAEAAIAHACIAFAEQADACABAFQACAEAAAGQAAAGgCAFQgBAEgDADQgCACgDABIgHACQgEAAgDgCgAt4h4IgDACQgCACgBAEIgBAIIABAJIADAFIADACIAFABIAEgBIAEgCQACgCAAgDIABgJIgBgIQAAgEgCgCIgEgCIgEgBIgFABgAvhhTQgFgCgDgDQgDgDgBgDIgCgIIAAgMIAAgLIACgIQABgEADgDQADgDAFgCQAEgBAEAAQAJAAAGAFQAGAFACAJIgHAAQgCgGgEgEQgDgDgHAAIgGABIgFADIgDAFIgBAGIAAALIAAALIABAHIADAEIAFADIAGACQAHAAAEgEQAEgDABgGIAHAAQgBAGgDAEQgDAEgFACQgFADgGAAQgEAAgEgCgAU9hSIAAgIIAJAAIAAAIgAUYhSIAAgsIAcAAIAAAGIgVAAIAAAmgASyhSIAAg5IgLALIAAgHIALgLIAHAAIAABAgARDhSIAAgGIAaggQACgCAAgCIABgFQAAgFgDgDQgDgEgFAAQgDAAgCACQgDABgBACQgCADAAAEIgHAAQABgFACgEQACgEAEgCQAEgCAFAAQAFAAAEACQAEACACAEQADAEAAAFIgBAHIgEAGIgXAcIAcAAIAAAGgAQYhSIAAgRIgLAAIgJARIgIAAIALgSQgFgBgDgDQgDgEAAgFQAAgGAEgDQAEgEAGAAIAUAAIAAAsgAQFh3QgCADAAADQAAAEACACQACADAFAAIAMAAIAAgRIgMAAQgFAAgCACgANehSIgVgXIATgVIAIAAIgUAVIAWAXgANChSIAAgsIAHAAIAAAVIAAAXgAI+hSIAAgmIgVAAIAAAmIgHAAIAAgsIAjAAIAAAsgAH1hSIAAgRIgLAAIgJARIgIAAIALgSQgFgBgDgDQgDgEAAgFQAAgGAEgDQAEgEAGAAIAUAAIAAAsgAHih3QgCADAAADQAAAEACACQACADAFAAIAMAAIAAgRIgMAAQgFAAgCACgAFlhSIAAgRIgLAAIgKARIgHAAIAKgSQgFgBgCgDQgDgEAAgFQAAgGAEgDQADgEAHAAIAUAAIAAAsgAFSh3QgDADAAADQAAAEADACQACADAEAAIANAAIAAgRIgNAAQgEAAgCACgAEGhSIAAgUIgWAAIAAAUIgGAAIAAgsIAGAAIAAATIAWAAIAAgTIAGAAIAAAsgACqhSIAWg6IgXAAIAAAKIgGAAIAAgQIAkAAIAAAGIgXA6gABzhSIAAgGIAaggQACgCAAgCIABgFQAAgFgDgDQgDgEgFAAQgDAAgCACQgDABgBACQgCADAAAEIgHAAQABgFACgEQACgEAEgCQAEgCAFAAQAFAAAEACQAEACACAEQADAEAAAFIgBAHIgEAGIgXAcIAcAAIAAAGgAAGhSIAAgiIgWAiIgHAAIAAgsIAHAAIAAAiIAWgiIAGAAIAAAsgAgthSIAAgiIgXAiIgHAAIAAgsIAHAAIAAAiIAXgiIAGAAIAAAsgAiQhSIgVgXIAUgVIAIAAIgUAVIAWAXgAirhSIAAgsIAGAAIAAAVIAAAXgAkIhSIAAgRIgLAAIgKARIgHAAIAKgSQgFgBgCgDQgDgEAAgFQAAgGAEgDQADgEAHAAIAUAAIAAAsgAkbh3QgDADAAADQAAAEADACQACADAEAAIANAAIAAgRIgNAAQgEAAgCACgAk4hSIAAgiIgXAiIgGAAIAAgsIAGAAIAAAiIAXgiIAHAAIAAAsgAlshSIAAgUIgVAAIAAAUIgHAAIAAgsIAHAAIAAATIAVAAIAAgTIAHAAIAAAsgApJhSIAAgsIAUAAQAGAAAEADQADADAAAGQAAADgBADQgCACgEABQAEACACACQACADAAAEQAAAGgDADQgEADgGAAgApDhXIAOAAQAEAAACgCQACgCAAgEQAAgDgCgCQgCgCgEAAIgOAAgApDhrIANAAQAEAAACgCQACgCAAgDQAAgDgCgCQgCgBgEAAIgNAAgArAhSIAAgmIgWAAIAAAmIgGAAIAAgsIAiAAIAAAsgAsJhSIAAgiIgXAiIgHAAIAAgsIAHAAIAAAiIAXgiIAGAAIAAAsgAs4hSIgVgXIAUgVIAIAAIgUAVIAWAXgAtThSIAAgsIAGAAIAAAVIAAAXgAwdhSIAAgIIAJAAIAAAIgAwzhSIAAgRIgLAAIgKARIgHAAIAKgSQgFgBgCgDQgDgEAAgFQAAgGAEgDQADgEAHAAIAUAAIAAAsgAxGh3QgDADAAADQAAAEADACQACADAEAAIANAAIAAgRIgNAAQgEAAgCACgAxjhSIAAgiIgXAiIgGAAIAAgsIAGAAIAAAiIAXgiIAHAAIAAAsgAzFhSIgVgXIATgVIAIAAIgUAVIAWAXgAzhhSIAAgsIAHAAIAAAVIAAAXgAzyhSIgFgOIgcAAIgFAOIgHAAIAXhAIAGAAIAYBAgAz5hmIgMgiIgMAiIAYAAgAtNhpgA04hyIAAgMIgKAGIgDgEIALgGIgLgGIADgEIAKAGIAAgMIAFAAIAAAMIAKgGIADAEIgLAGIALAGIgDAEIgKgGIAAAMg");
	this.shape.setTransform(140.6,19.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.instance = new lib.Path_1();
	this.instance.parent = this;
	this.instance.setTransform(145.5,19,1.241,1.097,0,0,0,117.2,15.7);
	this.instance.alpha = 0.5;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal, new cjs.Rectangle(0,0,290.5,36.5), null);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(300));

	// logo
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(149.8,58.3,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(221).to({regX:0.1,regY:0.1,scaleX:1.52,scaleY:1.51,y:145.8},8,cjs.Ease.get(1)).wait(62).to({regX:0,regY:0,scaleX:1.25,scaleY:1.25,y:58.3},8,cjs.Ease.get(1)).wait(1));

	// legal
	this.instance_1 = new lib.legal();
	this.instance_1.parent = this;
	this.instance_1.setTransform(120.4,577.6,1,1,0,0,0,115,18.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(300));

	// 4a.jpg
	this.instance_2 = new lib.s4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(167.1,249.3,1,1,0,0,0,120.1,200);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(217).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(66).to({alpha:0},8,cjs.Ease.get(1)).wait(1));

	// t3b
	this.instance_3 = new lib.t3b();
	this.instance_3.parent = this;
	this.instance_3.setTransform(187.3,170.8,1.25,1.25);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(149).to({_off:false},0).wait(1).to({x:186.6,alpha:0.019},0).wait(1).to({x:184.1,alpha:0.086},0).wait(1).to({x:178.8,alpha:0.226},0).wait(1).to({x:170.1,alpha:0.457},0).wait(1).to({x:160.4,alpha:0.716},0).wait(1).to({x:153.8,alpha:0.892},0).wait(1).to({x:150.7,alpha:0.977},0).wait(1).to({x:149.8,alpha:1},0).wait(54).to({x:112.3,alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(80));

	// t3a
	this.instance_4 = new lib.t3a();
	this.instance_4.parent = this;
	this.instance_4.setTransform(187.3,130.8,1.25,1.25);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(145).to({_off:false},0).wait(1).to({x:186.6,alpha:0.019},0).wait(1).to({x:184.1,alpha:0.086},0).wait(1).to({x:178.8,alpha:0.226},0).wait(1).to({x:170.1,alpha:0.457},0).wait(1).to({x:160.4,alpha:0.716},0).wait(1).to({x:153.8,alpha:0.892},0).wait(1).to({x:150.7,alpha:0.977},0).wait(1).to({x:149.8,alpha:1},0).wait(54).to({x:112.3,alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(84));

	// 3a.png
	this.instance_5 = new lib.s3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(149.9,368.9,0.8,0.8,0,0,0,73.2,110.7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(152).to({_off:false},0).to({regX:73,regY:110.6,scaleX:1,scaleY:1,x:149.8,alpha:1},8,cjs.Ease.get(1)).wait(52).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(79));

	// t2c
	this.instance_6 = new lib.t2c();
	this.instance_6.parent = this;
	this.instance_6.setTransform(187.6,275.9,1.25,1.25);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(73).to({_off:false},0).wait(1).to({x:186.7,alpha:0.022},0).wait(1).to({x:183.7,alpha:0.102},0).wait(1).to({x:177.9,alpha:0.258},0).wait(1).to({x:169.1,alpha:0.491},0).wait(1).to({x:160.2,alpha:0.729},0).wait(1).to({x:154.1,alpha:0.893},0).wait(1).to({x:150.9,alpha:0.976},0).wait(1).to({x:150.1,alpha:1},0).wait(57).to({x:149.2,alpha:0.978},0).wait(1).to({x:146.3,alpha:0.899},0).wait(1).to({x:140.2,alpha:0.738},0).wait(1).to({x:131.1,alpha:0.494},0).wait(1).to({x:122.1,alpha:0.254},0).wait(1).to({x:116.2,alpha:0.098},0).wait(1).to({x:113.3,alpha:0.021},0).wait(1).to({x:112.6,alpha:0},0).to({_off:true},1).wait(154));

	// t2b
	this.instance_7 = new lib.t2b();
	this.instance_7.parent = this;
	this.instance_7.setTransform(183.1,195.3,1.25,1.25);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(71).to({_off:false},0).wait(1).to({x:182.3,alpha:0.022},0).wait(1).to({x:179.3,alpha:0.102},0).wait(1).to({x:173.4,alpha:0.258},0).wait(1).to({x:164.7,alpha:0.491},0).wait(1).to({x:155.8,alpha:0.729},0).wait(1).to({x:149.6,alpha:0.893},0).wait(1).to({x:146.5,alpha:0.976},0).wait(1).to({x:145.6,alpha:1},0).wait(55).to({x:145.1,alpha:0.986},0).wait(1).to({x:143.3,alpha:0.939},0).wait(1).to({x:139.8,alpha:0.845},0).wait(1).to({x:134.1,alpha:0.694},0).wait(1).to({x:126.6,alpha:0.494},0).wait(1).to({x:119.2,alpha:0.296},0).wait(1).to({x:113.7,alpha:0.149},0).wait(1).to({x:110.3,alpha:0.059},0).wait(1).to({x:108.6,alpha:0.013},0).wait(1).to({x:108.1,alpha:0},0).to({_off:true},1).wait(156));

	// t2a
	this.instance_8 = new lib.t2a();
	this.instance_8.parent = this;
	this.instance_8.setTransform(184.4,146.1,1.25,1.25);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(69).to({_off:false},0).wait(1).to({x:183.5,alpha:0.022},0).wait(1).to({x:180.5,alpha:0.102},0).wait(1).to({x:174.7,alpha:0.258},0).wait(1).to({x:165.9,alpha:0.491},0).wait(1).to({x:157,alpha:0.729},0).wait(1).to({x:150.9,alpha:0.893},0).wait(1).to({x:147.7,alpha:0.976},0).wait(1).to({x:146.9,alpha:1},0).wait(55).to({x:146,alpha:0.978},0).wait(1).to({x:143.1,alpha:0.899},0).wait(1).to({x:137,alpha:0.738},0).wait(1).to({x:127.9,alpha:0.494},0).wait(1).to({x:118.9,alpha:0.254},0).wait(1).to({x:113,alpha:0.098},0).wait(1).to({x:110.1,alpha:0.021},0).wait(1).to({x:109.4,alpha:0},0).to({_off:true},1).wait(160));

	// 2.jpg
	this.instance_9 = new lib.s2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(149.8,249.5,1.25,1.25,0,0,0,120,200);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(62).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(61).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(160));

	// 1a.jpg
	this.instance_10 = new lib.s1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(120.1,200,1,1,0,0,0,120.1,200);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({alpha:1},8,cjs.Ease.get(1)).wait(54).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(229));

	// bg
	this.instance_11 = new lib.bg();
	this.instance_11.parent = this;
	this.instance_11.setTransform(150,300,1.25,1.5,0,0,0,120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(300));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149.5,299.5,404.5,601.5);
// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/p3b.png", id:"p3b"},
		{src:"images/300x600_atlas_NP_.jpg", id:"300x600_atlas_NP_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;