(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"120x600_atlas_", frames: [[0,192,160,190],[162,0,160,190],[0,0,160,190],[162,192,160,190]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib._1 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._3 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib._5 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AmnCwIAAgVIhQAAIAAAVIgVAAIAAgoIALAAIAphbIASAAIApBbIALAAIAAAogAm0CIIgbg/IgcA/IA3AAgACnCZQgKgGgIgJQgHgIgDgKQgEgLAAgJQAAgJAEgKQADgKAHgJQAIgIAKgGQALgGAPABQALAAAKADQAKAEAIAIQAIAIAFAKIgYAAQgDgDgEgDQgEgEgFgBQgFgCgHAAQgLgBgIAGQgJAFgFAJQgEAIAAAKQAAAKAEAJQAGAJAIAFQAIAFALAAQAIABAHgEQAHgDAFgGIAYAAQgFAJgHAIQgIAHgKAEQgJAEgMAAQgPAAgLgFgAicCXQgNgIgHgNQgJgNAAgRQAAgPAJgOQAHgNANgIQANgHARAAQARAAANAHQANAIAHANQAJAOgBAPQABARgJANQgHANgNAIQgOAHgQAAQgQAAgOgHgAiSBDQgIAGgFAIQgFAJAAAKQAAAKAFAJQAFAJAIAFQAJAFALAAQALAAAJgFQAIgFAFgJQAFgJAAgKQAAgKgFgJQgFgIgIgGQgJgEgLAAQgLAAgJAEgAlwCXQgOgIgHgNQgIgNAAgRQAAgPAIgOQAHgNAOgIQANgHARAAQAQAAANAHQANAIAIANQAIAOAAAPQAAARgIANQgIANgNAIQgNAHgQAAQgRAAgNgHgAlmBDQgIAGgGAIQgEAJAAAKQAAAKAEAJQAGAJAIAFQAJAFALAAQALAAAIgFQAIgFAGgJQAEgJAAgKQAAgKgEgJQgGgIgIgGQgIgEgLAAQgLAAgJAEgArRCZQgLgGgHgJQgIgIgDgKQgEgLABgJQgBgJAEgKQADgKAIgJQAHgIALgGQALgGAOABQAMAAAKADQAKAEAIAIQAHAIAFAKIgYAAQgCgDgEgDQgEgEgFgBQgGgCgHAAQgLgBgIAGQgJAFgEAJQgFAIAAAKQAAAKAFAJQAFAJAIAFQAJAFALAAQAHABAIgEQAGgDAFgGIAZAAQgFAJgHAIQgIAHgKAEQgKAEgMAAQgOAAgLgFgALeCbIAAgTIAUAAIAAATgAK1CbIAAhSIgeBSIgRAAIgehSIAABSIgUAAIAAhuIAcAAIAeBUIAghUIAcAAIAABugAIFCbIAAhuIA8AAIAAAUIgnAAIAAAZIAmAAIAAAUIgmAAIAAAaIAnAAIAAATgAHdCbIAAhOIgyBOIgUAAIAAhuIAUAAIAABNIAyhNIAVAAIAABugAE/CbIAAhuIAbAAIAHAAIAKABQAGACAEADQAFADADAFQAEAGAAAJQAAAGgDAFQgCAEgDADIgEADQAJADAFAHQAEAIABAJQAAAIgEAHQgEAJgJAFQgKAEgSAAgAFUCIIAOAAIADAAIAHgCQACgCADgDQACgCAAgGQAAgCgBgDQgBgDgEgDQgEgDgHAAIgOAAgAFUBXIAKAAQAGAAAEgCQADgDABgCIAAgEQAAgGgCgCQgDgCgEgBIgFAAIgKAAgAEMCbIAAhaIgUAAIAAgUIA+AAIAAAUIgVAAIAABagAA2CbIAAhuIAVAAIAAAqIAQAAQAOABAHAEQAJAFADAIQADAIABAIQAAALgGAHQgEAIgIAEQgJAEgKAAgABLCIIAQAAQAHgBAEgDQAFgEAAgHQAAgGgFgEQgEgEgHAAIgQAAgAAUCbIgehSIgeBSIgWAAIArhuIASAAIArBugAkKCbIAAhuIAbAAIAHAAIAKABQAFACAFADQAFADADAFQAEAGgBAJQABAGgDAFQgCAEgEADIgDADQAJADAEAHQAFAIAAAJQAAAIgDAHQgEAJgKAFQgKAEgRAAgAj1CIIANAAIAEAAIAGgCQADgCACgDQADgCAAgGQAAgCgBgDQgCgDgDgDQgEgDgIAAIgNAAgAj1BXIAJAAQAHAAADgCQADgDABgCIABgEQgBgGgCgCQgCgCgEgBIgGAAIgJAAgAo/CbIAMgcIgqhSIAYAAIAeA6IAZg6IAXAAIgyBugALeB/IAAhSIAUAAIAABSgADYgqIAAgUIhQAAIAAAUIgVAAIAAgoIALAAIAohcIASAAIAqBcIAKAAIAAAogADLhSIgcg/IgbA/IA3AAgAEOhEQgNgHgIgNQgHgNgBgQQABgRAHgNQAIgNANgIQANgHARgBQARABANAHQANAIAIANQAHANAAARQAAAQgHANQgIANgNAHQgNAIgRAAQgRAAgNgIgAEZiXQgJAFgFAJQgFAJAAAKQAAAKAFAKQAFAIAJAFQAIAFALABQALgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgJgJgFQgIgEgLgBQgLABgIAEgAlDhEQgNgHgIgNQgHgNgBgQQABgRAHgNQAIgNANgIQANgHARgBQARABANAHQANAIAIANQAHANAAARQAAAQgHANQgIANgNAHQgNAIgRAAQgRAAgNgIgAk4iXQgJAFgFAJQgFAJAAAKQAAAKAFAKQAFAIAJAFQAIAFALABQALgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgJgJgFQgIgEgLgBQgLABgIAEgAn5hEQgNgHgHgNQgIgNAAgQQAAgRAIgNQAHgNANgIQAOgHARgBQAQABANAHQANAIAIANQAIANAAARQAAAQgIANQgIANgNAHQgNAIgQAAQgRAAgOgIgAnuiXQgJAFgFAJQgEAJAAAKQAAAKAEAKQAFAIAJAFQAJAFALABQALgBAIgFQAJgFAEgJQAGgIgBgLQABgKgGgJQgEgJgJgFQgIgEgLgBQgLABgJAEgAJMg+IgLgdIgqAAIgLAdIgXAAIAuhwIARAAIAuBwgAI5hvIgNggIgMAgIAZAAgAHWg+IAAhTIgeBTIgRAAIgehTIAABTIgVAAIAAhwIAcAAIAgBWIAehWIAcAAIAABwgAALg+IAAhwIA7AAIAAAVIgmAAIAAAZIAlAAIAAAUIglAAIAAAaIAmAAIAAAUgAgng+IAAhbIgUAAIAAgVIA8AAIAAAVIgUAAIAABbgAiFg+IAAhwIAUAAIAAArIARAAQAOAAAHAGQAJAEADAIQADAIABAIQAAAKgGAIQgEAIgIAEQgIAEgLABgAhxhSIARAAQAHAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgHAAIgRAAgAjdg+IAAhwIAbAAIAHAAIAKADQAGABAEADQAFADAEAFQADAGAAAJQAAAGgDAFQgCAFgDACIgEADQAJADAFAHQAEAHABAKQAAAIgEAIQgEAHgJAFQgKAGgSAAgAjIhSIAOAAIADAAIAHgDQADgBACgCQACgEAAgFQAAgCgBgDQgBgEgEgCQgEgCgHgBIgOAAgAjIiDIAKAAQAGAAADgCQAEgDABgCIAAgEQAAgFgCgDQgDgDgEAAIgFAAIgKAAgAmKg+IAAhbIgVAAIAAgVIA+AAIAAAVIgVAAIAABbgApRg+IAAhwIA3AAIAAAVIgiAAIAABbg");
	this.shape.setTransform(-0.3,1.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t5, new cjs.Rectangle(-78.3,-21.9,156.6,43.8), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AlLCMQgNgHgHgNQgJgNAAgRQAAgQAJgOQAHgMANgIQANgIARAAQARAAANAIQANAIAHAMQAJAOgBAQQABARgJANQgHANgNAHQgOAIgQAAQgQAAgOgIgAlBA5QgIAFgFAIQgFAJAAAKQAAALAFAJQAFAJAIAFQAJAEALABQALgBAJgEQAIgFAFgKQAFgIAAgLQAAgKgFgJQgFgIgIgFQgJgFgLAAQgLAAgJAFgAGnCRIgLgdIgpAAIgLAdIgXAAIAuhvIAQAAIAvBvgAGUBgIgMggIgNAgIAZAAgAEtCRIAAhbIgVAAIAAgUIA+AAIAAAUIgUAAIAABbgAD8CRIgjgxIAAAxIgUAAIAAhvIAUAAIAAAwIAjgwIAZAAIgrA2IArA5gAB2CRIAAhvIA8AAIAAAUIgmAAIAAAZIAlAAIAAAUIglAAIAAAaIAmAAIAAAUgABVCRIgfhTIgeBTIgXAAIAshvIASAAIAtBvgAgdCRIAAhbIgpAAIAABbIgUAAIAAhvIBRAAIAABvgAiECRIAAhTIgdBTIgRAAIgdhTIAABTIgVAAIAAhvIAcAAIAeBVIAghVIAcAAIAABvgAl+CRIgigxIAAAxIgWAAIAAhvIAWAAIAAAwIAigwIAYAAIgpA2IApA5gAgwgmQgNgIgIgNQgHgNgBgRQABgPAHgOQAIgNANgHQANgJARABQARgBAMAJQANAHAIANQAHAOAAAPQAAARgHANQgIANgNAIQgMAHgRAAQgRAAgNgHgAglh5QgJAEgFAJQgFAIAAALQAAALAFAIQAFAJAJAFQAIAFALABQALgBAHgFQAJgFAFgJQAFgIAAgLQAAgLgFgIQgFgJgJgEQgHgGgLAAQgLAAgIAGgAG/giIAAhvIA7AAIAAAUIgnAAIAAAaIAlAAIAAAUIglAAIAAAZIAnAAIAAAUgAGZgiIgigwIAAAwIgWAAIAAhvIAWAAIAAAwIAigwIAYAAIgpA3IApA4gAE5giIAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvgACogiIAMgcIgqhTIAYAAIAeA8IAZg8IAXAAIgyBvgABtgiIgjgwIAAAwIgUAAIAAhvIAUAAIAAAwIAjgwIAZAAIgrA3IArA4gAhvgiIAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvgAj5giIAAhNIgxBNIgVAAIAAhvIAVAAIAABPIAxhPIAVAAIAABvgAmTgiIAAhvIAfAAQANAAAIAFQAJADADAGQAFAGABAGIABAJIgBALQgCAHgFAEQgEAGgIADQgIADgMABIgKAAIAAApgAl+hfIAMAAIAHgBQAEgBADgDQADgEABgGQgBgHgDgDQgDgDgEgBIgHgBIgMAAgAm7giIAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvg");
	this.shape.setTransform(0.1,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-53.6,-19.9,107.2,39.9), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AgNCMQgOgHgHgNQgIgNAAgRQAAgQAIgOQAHgMAOgIQANgIAQAAQAQAAANAIQAOAIAHAMQAIAOAAAQQAAARgIANQgHANgOAHQgNAIgQAAQgQAAgNgIgAgDA5QgIAFgGAIQgEAJAAAKQAAALAEAJQAGAJAIAFQAHAEAMABQALgBAIgEQAIgFAGgKQAEgIAAgLQAAgKgEgJQgGgIgIgFQgIgFgLAAQgMAAgHAFgAjlCOQgLgFgHgJQgHgJgEgKQgDgKgBgKQABgJADgKQAEgKAHgIQAHgJALgGQALgFAPAAQALAAAKAEQAKAEAIAIQAHAHAFALIgXAAQgDgEgEgDQgEgDgFgCQgFgCgHAAQgLAAgJAGQgIAEgFAJQgFAIAAAKQAAALAFAIQAFAKAIAFQAJAEALABQAIAAAGgEQAHgDAGgGIAXAAQgEAJgHAIQgIAIgKADQgKAFgLAAQgQAAgKgGgAFQCRIAAgrIgBAAIgeArIgXAAIAegpQgJgBgHgFQgGgDgEgIQgEgHAAgKIACgKQABgGAEgGQAEgGAJgEQAIgEAOAAIAgAAIAABvgAE3A5QgFACgCADQgBAFAAADQAAAEABAEQACAEAFADQAEACAIAAIANAAIAAghIgNAAQgIAAgEADgAD1CRIAAhOIgxBOIgVAAIAAhvIAVAAIAABOIAxhOIAVAAIAABvgABYCRIAAhvIAbAAIAHAAIAKACQAFACAFADQAFADADAFQAEAGgBAIQAAAHgCAFQgDAEgDACIgEAEQAJACAGAIQAEAHAAAKQAAAHgDAIQgEAIgKAFQgKAFgRAAgABtB9IANAAIAEAAIAGgCQADgBADgDQACgDAAgFQAAgCgBgDQgBgEgEgDQgEgCgIgBIgNAAgABtBNIAJAAQAHAAADgCQADgDABgDIABgDQgBgGgCgCQgCgDgEgBIgGAAIgJAAgAhBCRIgehTIgfBTIgWAAIAshvIASAAIArBvgAlLCRIAOgcIgrhTIAZAAIAdA7IAZg7IAXAAIgyBvgAizgMIAAgWIhKAAIAAhvIAVAAIAABbIApAAIAAhbIAUAAIAABbIANAAIAAAqgAoKglQgLgFgHgIQgHgJgEgKQgDgLAAgJQAAgJADgLQAEgKAHgIQAHgJALgFQALgFAOAAQAMAAAKADQAKAFAHAHQAJAIAEALIgYAAQgCgFgEgCQgEgEgGgCQgEgCgIAAQgLABgIAFQgIAFgFAIQgFAJAAAKQAAALAFAIQAFAJAJAFQAIAFALABQAHAAAIgEQAHgDAEgHIAZAAQgFAKgIAHQgHAIgKAEQgKAEgMAAQgPAAgKgGgAHwgiIAAhvIA7AAIAAAUIgmAAIAAAaIAlAAIAAAUIglAAIAAAZIAmAAIAAAUgAHIgiIAAhvIAUAAIAABvgAFygiIAAhvIAWAAIAAArIAQAAQANAAAJAFQAIAGADAHQAEAIAAAJQgBAJgFAJQgEAHgIAEQgJAFgKgBgAGIg2IAQAAQAHABAFgEQAEgEAAgGQAAgIgEgDQgFgEgHAAIgQAAgAFKgiIAAguIgpAAIAAAuIgVAAIAAhvIAVAAIAAAtIApAAIAAgtIAUAAIAABvgAC1giIAAhvIAWAAIAAArIAQAAQANAAAJAFQAIAGADAHQAEAIAAAJQgBAJgFAJQgEAHgIAEQgJAFgKgBgADLg2IAQAAQAHABAFgEQAEgEAAgGQAAgIgEgDQgFgEgHAAIgQAAgACUgiIgfhSIgeBSIgXAAIAshvIASAAIAsBvgAAogiIgMgcIgnAAIgMAcIgXAAIAuhvIAQAAIAuBvgAAVhSIgNghIgLAhIAYAAgAhNgiIAAhNIgyBNIgUAAIAAhvIAUAAIAABPIAyhPIAVAAIAABvgAlLgiIAAhvIA8AAIAAAUIgmAAIAAAaIAlAAIAAAUIglAAIAAAZIAmAAIAAAUgAlzgiIAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvg");
	this.shape.setTransform(-0.2,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-58.3,-19.9,116.6,39.9), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AEhETIgMgcIgpAAIgLAcIgXAAIAuhuIAQAAIAvBugAENDjIgNghIgMAhIAZAAgACtETIgigwIAAAwIgVAAIAAhuIAVAAIAAAvIAigvIAZAAIgqA2IAqA4gABNETIAAhNIgxBNIgVAAIAAhuIAVAAIAABOIAxhOIAVAAIAABugAghETIAAguIgoAAIAAAuIgVAAIAAhuIAVAAIAAAsIAoAAIAAgsIAVAAIAABugAiAETIgbgmIgaAmIgZAAIAng3Igng3IAZAAIAaAmIAbgmIAXAAIgmA3IAmA3gAkSETIAAhuIA7AAIAAATIgmAAIAAAaIAlAAIAAAUIglAAIAAAZIAmAAIAAAUgAlFETIAAhbIgVAAIAAgTIA+AAIAAATIgVAAIAABbgAhjAzQgNgHgHgNQgIgNAAgQQAAgPAIgOQAHgNANgIQANgHARgBQARABANAHQANAIAIANQAHAOABAPQgBAQgHANQgIANgNAHQgOAIgQAAQgRAAgNgIgAhZgfQgIAFgFAJQgFAIAAAKQAAAKAFAKQAFAIAIAFQAJAFALAAQALAAAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgIQgFgJgJgFQgIgEgLAAQgLAAgJAEgAFvA5IAAgsIAAAAIgeAsIgYAAIAegqQgJAAgGgFQgGgEgFgHQgDgHAAgJIABgLQABgFAFgHQAEgFAIgFQAIgDAOAAIAhAAIAABugAFWgfQgEADgCADQgCAEAAAEQAAAEACAEQACADAEADQAFACAHAAIANAAIAAggIgNAAQgHgBgFADgAEcA5IgMgdIgoAAIgMAdIgWAAIAuhuIAQAAIAuBugAEIAIIgMgfIgMAfIAYAAgACmA5IAAgvIgoAAIAAAvIgVAAIAAhuIAVAAIAAAsIAoAAIAAgsIAVAAIAABugABAA5IAAgvIgoAAIAAAvIgWAAIAAhuIAWAAIAAAsIAoAAIAAgsIAUAAIAABugAidA5IgagnIgaAnIgYAAIAmg4Igmg2IAYAAIAaAmIAagmIAYAAIgmA2IAmA4gAk0A5IANgcIgrhSIAZAAIAdA5IAag5IAXAAIgzBugAlvA5IgigxIAAAxIgVAAIAAhuIAVAAIAAAwIAigwIAZAAIgqA1IAqA5gACkilQgLgFgHgIQgHgJgDgKQgEgKAAgKQAAgKAEgKQADgKAHgIQAHgIALgGQALgFAPgBQALAAAKAEQAKAFAIAHQAIAIAFALIgYAAQgDgFgEgDQgEgCgFgDQgFgCgHAAQgLABgIAFQgJAFgFAIQgEAJAAAKQAAAKAEAJQAGAJAIAFQAIAFALABQAIAAAHgEQAHgDAFgHIAYAAQgFAKgHAHQgIAIgKAEQgJAEgMAAQgPAAgLgGgAH7ihIAAgrIAAAAIgdArIgZAAIAfgqQgJgBgHgEQgGgEgEgIQgEgGAAgLIACgKQAAgFAFgGQAEgHAJgDQAIgFAOAAIAgAAIAABwgAHjj6QgFACgBAEQgCAEAAAEQAAAEACAEQABADAFADQAEADAIgBIAMAAIAAghIgMAAQgIAAgEADgAGoihIgLgdIgpAAIgMAdIgWAAIAuhwIAQAAIAvBwgAGVjSIgMggIgNAgIAZAAgAE1ihIgigxIAAAxIgVAAIAAhwIAVAAIAAAxIAigxIAZAAIgqA3IAqA5gABhihIAAgvIgpAAIAAAvIgUAAIAAhwIAUAAIAAAtIApAAIAAgtIAVAAIAABwgAgEihIAAgrIgBAAIgdArIgYAAIAfgqQgKgBgGgEQgHgEgDgIQgEgGgBgLIACgKQABgFAEgGQAFgHAIgDQAJgFANAAIAgAAIAABwgAgdj6QgEACgCAEQgCAEAAAEQAAAEACAEQACADAEADQAEADAIgBIANAAIAAghIgNAAQgIAAgEADgAiNihIAAhwIAWAAIAAArIAPAAQAOAAAJAGQAHAFAEAHQADAIAAAJQAAAKgEAIQgFAHgIAEQgJAFgLAAgAh3i2IAQAAQAHABAFgEQAEgEAAgGQAAgIgEgDQgFgEgHAAIgQAAgAiuihIgfhTIgeBTIgXAAIAshwIASAAIAsBwgAkaihIgMgdIgoAAIgMAdIgWAAIAthwIARAAIAuBwgAkujSIgMggIgMAgIAYAAgAmUihIAAhcIgVAAIAAgUIA9AAIAAAUIgUAAIAABcgAnJihIAAhOIgxBOIgVAAIAAhwIAVAAIAABPIAxhPIAVAAIAABwg");
	this.shape.setTransform(1.8,0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-57.6,-32.9,115.3,65.8), null);


(lib.pic5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._5();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic5, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._3();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic3, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._2();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic2, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic1, new cjs.Rectangle(-120,-100,160,190), null);


(lib.legal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AGJCwIgGgEIgDgEIgEgHIAEgBIACAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAEAGIADACIAFABIAFgBIAFgCIADgHIgBgFIgCgDIgFgCIgIgBIAAgFIAMgDIACgEIAAgEIAAgDIgCgEIgEgBIgDgBIgFABIgDABIgCADIgBAEIgDABIgCAAIgDAAIACgIIADgEIAGgEIAIgBIAHABIAFAEIAEAEIABAHIgBAEIgCAEIgDADIgEABQAGACACAEQADAEAAAFQAAAEgCADQgBACgDADQgDADgEABIgHABgAFaCwIgEgBIgHgFIADgDIABAAIACAAIADABIADABIAFABIAFgBIAEgCIADgFIABgFIgBgFIgDgDIgDgDIgGgBIgKABIgEgBIAEgbIAcAAIAAAEQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgSAAIgCAPIAHgBQAFAAADACQAEAAADADQACADABADIABAHIgBAHIgFAHQgDADgEABQgDABgFABgAD8CvQgEgBgDgFQgDgEgBgFQgCgFABgHQgBgJACgFQABgFADgEIAHgGQADgBAFgBIAJACQAEABACAFQADACACAHQABAFAAAJQAAAHgBAFQgCAHgDACQgCAEgEACIgJACQgFgBgDgBgAEAB9IgFAEIgDAHIAAAWIADAHIAFAEIAEABIAGgBIADgEIADgHIACgKIgCgMIgDgHIgDgEIgGgBgACfCvQgFgCgCgEQgEgEgBgFQgCgFAAgHQAAgJACgFQABgFAEgEQAEgFADgBQADgBAFgBQAFABADABQADABAEAFQADAEACAFIAAAOIAAAMQgCAFgDAEQgDAEgEACQgDABgFABQgFgBgDgBgAChB9IgDAEIgEAHIgBAMIABAKIAEAHIADAEIAGABIAEgBQAEgCABgCQACgEABgDIABgKIgBgMQgBgEgCgDQgBgCgEgCIgEgBgABwCvQgEgBgCgDIgDgGQgDgEAAgEIADgIIAEgKIAQgTIABgCIACAAIAHAAIgRAWIgDADIAFgCIAFAAIAHABQACAAADADIAEAFIABAIIgBAHIgFAGQgDADgDABQgDABgFABQgFgBgDgBgABzCUIgDACIgDADIgBAFIAAAFIADAEIAEACIAFABIAFgBIAEgCIADgEIABgFIgBgFIgDgDIgEgCIgFgCgAh5CvQgEgCgDgEQgDgCgCgHQgBgFAAgHQAAgJABgFQACgHADgCQADgFAEgBIAIgCIAIACQACABAFAFQADACABAHQACAFAAAJQAAAHgCAFQgBAHgDACQgDAEgEACIgIACIgIgCgAh2B9IgEAEQgCADgBAEQgBADAAAJQAAAHABADQABADACAEIAEAEIAFABIAFgBIAEgEQACgBABgGQABgDAAgHQAAgJgBgDQgBgFgCgCIgEgEIgFgBgAmSCvIgJgGQgEgGgBgEQgDgHAAgEQAAgGADgHQABgFAEgEQADgEAGgDQAIgCAEAAQAFAAAGACQAHADACAEQAFAEACAFQACAFAAAIQAAAGgCAFQgCAEgFAGQgEAEgFACQgEACgHAAQgHAAgFgCgAmOB+QgDABgEAEQgCACgBAEQgCAFAAAGQAAAEACAFQAAADADADQAEAEADABIAIABIAJgBIAGgFQACgCACgEIABgJIgBgLIgEgGIgGgFIgJgBgAE5CwIAAgPIgZAAIgCgBIAAAAIgBgFIAcglIAHAAIAAAlIAIAAIAAAFIgCABIgGAAIAAAPgAElCbIAUAAIAAgZIABgDgADHCwIAZgvIACgEIgeAAIgBAAIAAgCIAAgFIAmAAIAAAGIAAABIgYAwIgCACIgCABgAA8CwIATgZIACgCIgFADIgGAAIgHAAIgEgEIgEgFIgBgIIABgGIAEgGIAGgEQAEgBAEgBQAEABAEABQADABADADQACACABAEQACADAAAEIgCAJIgTAeIgBABIgDAAgABFB9IgEACIgDAEIgBAEQABAFACADQADADAGAAIAFgBIADgCIADgDIABgFIgCgEIgCgEIgDgCIgFgBgAANCwIAXgvIADgEIgeAAIgBAAIgBgCIAAgFIAnAAIAAAGIAAABIgYAwIgCACIgCABgAgiCwIAYgvIADgEIgeAAIgBAAIAAgCIAAgFIAmAAIAAAGIAAABIgYAwIgBACIgDABgAg9CwIAAgPIgYAAIgDgBIAAAAIgBgFIAcglIAHAAIAAAlIAJAAIAAAFIgBAAIAAABIgIAAIAAAPgAhRCbIAUAAIAAgZIABgDgAitCwIAAgGIAMAAIAAgmIAAgEIgKAIIgBABIgCAAIAAgBIgDgDIARgPIAHAAIAAA0IALAAIAAAGgAjbCwIAAgaIgfAAIAAAaIgIAAIAAg6IAIAAIAAAaIAfAAIAAgaIAIAAIAAA6gAkzCwIAAg6IASAAQAFAAAEABQAFACACACIAEAGIABAHIgBAIIgEAGQgDACgEABQgEACgFAAIgJAAIAAAVgAkqCUIAOAAIAEgEQABAAAAAAQABAAAAgBQAAAAAAgBQABAAAAgBIABgFIgBgFIgDgEIgDgCIgPAAgAlfCwIAAg6IAkAAIAAAHIgbAAIAAAzgAktBaIAAgOIgiAAIAAAMIAAABIgCABIgFAAIAAgUIACAAIACAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAAAIACgEIACgGIADgXIAaAAIAAAjIAHAAIAAASIAAABIgCABgAlFA8IgBAHIgCADIATAAIAAgdIgNAAgAlvBXIAAgBIAAgBIAFgHIAAAAIgCgBIgCgBIgBgCIAAgCIABgDQAAgBAAAAQABAAAAAAQABAAAAAAQABAAABAAIABAAIACABIABACIAAACIAAAFIgBADIgDAEIgEADgAmBBOIAAgdIAAgDIAAACIgCACIgSAaIgDACIgFAAIAAgqIAIAAIAAAfIACgEIASgZIABgBIADgBIAEAAIAAAqgAnrBOIAAgGIAUgTIAHgJIACgEIABgFIgBgEIgDgEQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAIgDAAIgFAAQAAAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAAAIgCADIgDAEQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAIgCABIgEgBIACgIIAEgEIAGgEIAHgBIAHABQADACACACQADACABADIACAHIgCAGIgCAFIgEAFIgTAUIAGgBIASAAIADAAIABACIAAAGgAHSBMIgFgBIgGgFIACgDIABAAIACAAIADABIADABIAFABIAFgBIAFgCIACgFIABgGIgBgEIgCgDIgEgDIgFgBIgKABIgEgBIAEgbIAcAAIAAAEQAAAAgBAAQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQAAAAgBABIgSAAIgCAOIAIgCQAFABADACQADAAACADQADACABAEQABACABAEIgCAIQgBAEgEADQgDAEgEAAQgDACgFAAgAFzBLQgEgCgCgEQgDgCgCgHQgCgFAAgIQAAgIACgFQACgGADgDQAEgFACgBQAEgBAEgBIAJACQAEACACAEQADADACAGQACAFAAAIQAAAIgCAFQgCAHgDACQgCAEgEACIgJACQgEAAgEgCgAF3AZIgFAEIgCAHIAAAWIACAHIAFAEIAEABIAGgBIADgEQADgEABgDQABgCAAgJQAAgIgBgDQgBgEgDgDIgDgEIgGgBgADoBMIgFgBIgGgFIACgDIABAAIADAAIACABIAEABIAEABIAFgBIAFgCIACgFIABgGIgBgEIgCgDIgEgDIgGgBIgJABIgEgBIAEgbIAcAAIAAAEQAAAAgBAAQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABIgSAAIgCAOIAIgCQAFABADACQADAAACADQADACABAEQABACABAEQAAAFgCADQgBAEgEADQgDAEgEAAQgDACgFAAgACJBLQgDgBgDgFQgEgEgBgFQgCgFAAgIQAAgIACgFQABgEAEgFQAEgFACgBQAEgBAEgBIAJACQAEACACAEQADADACAGQACAFAAAIQAAAIgCAFQgCAHgDACQgCAEgEACIgJACQgEAAgEgCgACNAZIgFAEIgDAHIAAAWIADAHIAFAEIAEABIAGgBIADgEQADgEABgDIABgLIgBgLQgBgEgDgDIgDgEIgGgBgAjuBMQgDgBgDgDQgEgCAAgDQgCgCAAgFQAAgFAEgEQACgDAGgDQgGAAgBgEQgCgDAAgFQAAgEABgDQABgDACgBIAGgEIAHgBIAHABIAGAEIADAEIACAHQAAAFgDADQgCAEgFAAQAHADABADQAEADAAAGIgBAHQgDAEgCABQgCACgEACIgIABgAjrAyIgDACIgDADIgBAFIABAEIADAEIADACIAFAAIAFAAIADgCQABgBAAAAQABAAAAgBQAAAAAAgBQABAAAAgBIABgEIgBgFIgDgDIgEgCIgEgBgAjqAYIgDACIgDADIAAAEIAAADIADAEIACACIAFABIAEgBIAEgCIACgEIABgDIgBgEIgDgDIgDgCIgEgBgAkeBMIgBgBIgBgCIAAgEIABgBIABgBIAFAAIABABIABABIABACIgBACIgBACIgBABIgCABgAGdBMIAAgGIAMAAIAAgqIgJAIIgCABIgBAAIgBgBIgCgDIARgPIAGAAIAAA0IAMAAIAAAGgAE5BMIAAgDIABgCIAAgBIAXgXIAEgEIABgFIABgEIgBgFIgBgDIgEgBIgEgBIgEABIgDABIgDADIAAAEIgCABIgCABIgFgBIACgIIAFgEIAFgEIAHgBIAIABQACABADADIADAFIABAHIAAAGIgHAKIgTAUIAHgBIASAAIACAAIABACIAAAFgAERBMIAAgGIAMAAIAAgqIgKAIIgBABIgCAAIgBgBIgCgDIASgPIAGAAIAAA0IALAAIAAAGgADGBMIAAgPIgZAAIgCAAIAAgBIgCgFIAdglIAHAAIAAAlIAJAAIAAAGIgCAAIgHAAIAAAPgACyA3IAUAAIAAgcgABVBMIAYgvIADgDIgfAAIgBgBIAAgCIAAgFIAnAAIAAAGIgBACIgXAvIgCACIgDABgAAmBMIAYgvIADgDIgeAAIgBgBIgBgCIAAgFIAnAAIAAAGIgBACIgZAxIgDABgAgGBMIAAgaIgfAAIAAAaIgJAAIAAg6IAJAAIAAAaIAfAAIAAgaIAHAAIAAA6gAhEBMIAAgaIgfAAIAAAaIgIAAIAAg6IAIAAIAAAaIAfAAIAAgaIAIAAIAAA6gAiCBMIAAgpIABgDIAAgFIgBAEIgfAsIgCABIgGAAIAAg6IAIAAIAAAxIABgEIAegsIACgBIAHAAIAAA6gAm7A4IAAgGIAUAAIAAAGgAmPAeIgFgDIgCgBIAAgEIAAgCIABgBIAFAAIAAAEIABACIACABIAFAAIADgBIABgGIAEAAIACABIAAACIgCAEIgCABIgDADIgGABgAEcgKIAAgNIg5AAIAAgpIAIAAIAAAjIAQAAIAAgjIAIAAIAAAjIAQAAIAAgjIAIAAIAAAjIAHAAIAAASIgBABIgBAAgABkgKIAAgNIghAAIAAAMIgBABIgCAAIgEAAIAAgTIABAAIADAAIADgCIACgFIABgGIADgWIAaAAIAAAjIAIAAIAAASIgBABIAAAAgABMghIgDAEIATAAIAAgdIgMAAgAhpgKIAAg2IAFAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIABAFQADgDAEgCQADgCAEABQAFAAABAAIAFAEIADAHIABAJIgBAIIgDAHIgGAEQgDACgEABIgGgCIgFgDIAAARgAhcg5IgFAEIAAAUIAEAEIAFABQAGAAADgFQADgEAAgHIgBgHIgCgEIgDgDIgEgBQgDAAgDACgAjKgPIAAAAIAAgBIABgBIAAgBIACgBIABgDIAAgCIAAAAIgCgBIgBgBIgBgBIAAgCIABgEIADgBIACAAIACABIABADIAAACIAAAEIgCAEIgFAHgAGOgZQgCAAgDgDIgFgHIgBgJIABgIIAEgHIAGgFIAIAAIAIAAIAGAEIgCAEIgBAAIgCAAIgCgBIgCgBIgFgBIgEABIgEADIgCAEIgCAHIACAHIACAEIAEAEIAEABIAHgCIACgCIACgBIABABIADADIgEADIgHADIgFABQgEgBgDgCgAC+gZQgDAAgCgDQgDgDgCgFIgBgIIABgJIAFgGQABgCAEgDIAIAAIAIAAQAFACACADIAEAGIABAJIgBAIQgBAFgDADQgEADgDAAQgCACgGABQgEgBgEgCgAC+g3QgDAEAAAHQAAAIADADQADAEAFAAQAHAAADgEQADgEAAgHQAAgGgDgFQgDgEgHAAQgFAAgDAEgAAjgXIgIgDIgCgDIACgDIABgBIACABIACACIAHACIAEgBIACgBIACgDIACgDQgBgDgDgBQgBgCgGAAIgEAAIAAgFIAEAAQAFgBACgBQABgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgCIgCgCIgCgBIgEgBIgEABIgEACIgCAAIgBAAIgCgEIAFgEIAIAAIAHAAIAFACIACAEIABADIAAADIgBADIgCACIgEACQADABADACQACADAAADIgBAGQAAACgDACIgGACIgFACgAgEgZQgDAAgDgDQgDgCgCgGIgBgJIABgIIAFgGIAFgFIAHAAQAFAAACAAQADABADADIADAFIABAJIAAACIgCAAIgaAAIACAHIACAEIAEAEIAFAAIAEAAIADgBIADgCIACgBIAAABIADADIgDADIgJADIgFABIgGgDgAgEg4QgDACgCAGIAWAAIgBgFIgCgDIgDgCIgFgCQgDABgDADgAgzgZQgBAAgEgDQgDgEgBgEQgCgDAAgFIACgJQABgDADgDQACgDADgCIAJAAIAIAAIAGAFQAEADAAADIACAJQAAAFgCADQAAAEgEAEQgEADgCAAQgDACgFABQgEgBgFgCgAgzg3QgDAFAAAGQAAAHADAEQADAEAGAAQAFAAAEgEQADgEAAgHQAAgGgDgFQgEgEgFAAQgHAAgCAEgAIhgXIAAggIgBACIAAABIgCABIgTAaIgCACIgEAAIAAgpIAHAAIAAAcIgBACIADgCIABgBIACgDIADgFIANgSIABgBIACAAIAEAAIAAApgAHygXIAAggIgCADIgBABIgSAaIgBABIgBABIgFAAIAAgpIAHAAIAAAeIACgCIABgBIASgaIABgBIACAAIAEAAIAAApgAHKgXIgDgBIgCgCIgHgMIgDgDIgDgBIgEAAIAAATIgIAAIAAgpIAIAAIAAARIADAAIADAAIACgCIAJgOIABgBIADAAIAGAAIgNASIgDABIADABIADAEIAKARgAFygXIAAgTIgTAAIAAATIgHAAIAAgpIAHAAIAAAQIATAAIAAgQIAIAAIAAApgAFFgXIAAgdIAAgDIgBACIgBACIgCAEIgEAEIgNASIAAABIgCABIgFAAIAAgpIAHAAIAAAeIACgCIABgBIASgaIABgBIACAAIAEAAIAAApgACIgXIAAg7IARAAQAHAAADACQAFABACADIAFAFIABAIIgBAIIgFAGQgDACgEABQgDABgHAAIgIAAIAAAWgACRg0IAPAAIAEgDQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBABAAIABgFIgBgFIgDgEIgEgCIgPAAgAh+gXIAAgzIgcAAIAAAzIgIAAIAAg7IAtAAIAAA7gAjugYIgEgDIgCgDIgBgFIABgEQACgCADgCIAHgDIANgBIAAgEQAAgDgDgDQgCgDgDAAIgFAAIgHAFIgBgBIgCgBIgBgDQADgDAFgBIAJgBIAGAAIAEADIADAFIABAGIAAAbIgEAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgBgBIgBgEIgEADIgCABIgEACIgFAAgAjkgqIgGACIgCACIgBADIACAFIABABIADAAIAEAAIACgBIAGgFIAAgIgAlhgaQgDAAgEgDIgDgHIgBgJIABgIIADgHIAHgEIAIgBIAIABIAFADIgCAEIAAAAIgDAAIgEgDIgEAAIgGABIgCADQgDADAAABIgBAHIABAHIADAEIACAEIAGABIAHgCIACgCIABgBIABABIADADIgDADIgIADIgFAAQgDAAgDgCgAmPgaQgDAAgEgDQgCgDgBgEQgCgEAAgFIACgJQABgDACgDQACgCAFgCIAIgBIAIABQAEABACADIAFAGIABAJQAAAGgBADQgCAEgDADQgDADgDAAQgEACgEAAQgFAAgDgCgAmQg4QgDAEAAAHQAAAIADADQADAEAGAAQAGAAADgEQADgEAAgHQAAgGgDgFQgDgEgGAAQgGAAgDAEgAoIgYIgCgCIgBgBIAAgCIAAgCIABgCIACgBIAFAAIABABIABACIAAAEIgBABIgBACIgDAAgAkZgYIAAgpIAUABIAGABIACADIAAAFIAAACIgBADIgCADIgFABQAGABACACQADACgBAFIgBAFIgDAEIgFACIgGABgAkTgdIAJAAQADAAADgCQACgDAAgCIAAgDIgBgCIgDgBIgEgBIgJAAgAkTgwIAIAAIADAAIACgBQABgBAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIABgCIAAgCIgEgEIgEAAIgIAAgAkmgYIgDgBIgCgCIgIgMQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAIgDgBIgEAAIAAATIgIAAIAAgpIAIAAIAAARIADAAIADAAIADgCIAIgOIABAAIACgBIAHAAIgNASIgDABIAEABIACADIAKASgAmrgYIAAgsIAAgCIgUAjIgBACIgCAAIgBAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIgVgkIAAAvIgGAAIAAg6IAGAAIABAAIABABIAWAnIAAgCIAVglIABgBIACAAIAGAAIAAA6gAongYIAAgpIAbAAIAAAFIgTAAIAAAkgAIShHIgHgEIgBgEIABgCIABgBIAFAAIAAAEIABADIACABIAGAAIABgBIABgDIAAgEIAFAAIABABIABACIgBAEIgCACIgEACIgFABgAhZhnIAAgOIguAAIAAAMIgBACIgBAAIgGAAIAAgVIAHAAIACgCIACgDIACgHIADgJIACgeIAiAAIAAAzIAJAAIAAATIAAACIgBAAgAh3iYIgFAXIgDAFIAbAAIAAgsIgSAAgAInhsIAAAAIAAgBIACgBIABgCIABgDIABgCIgDgBIgBAAIgBgCIgBgCIACgEQAAAAAAAAQABAAAAAAQABAAAAAAQABgBABAAIACAAIABACIABAFIAAADIgEAIIgDADgAF3h1IgIgDIgDgDIACgDIACgBIAFACQAAAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAEABIAFgBQABAAAAAAQABAAAAgBQABAAAAAAQABgBAAgBIADgDIABgGIgBgFIgDgEIgDgBIgGgCQgEAAgFACIgEgBIAEgcIAcAAIAAADIgCADIgDABIgSAAIgCAPIAIgBQAEAAAEABQADABADADQADADABADIABAHQAAAEgCAEIgEAGIgHAEQgDACgFAAgADGh1IgCgBIAAgDIAAgFIACgBIAFAAIABABIABACIAAADIAAACIgBABIgBABIgDABgACQh1IgDgCIAAgCIAAgDIABgCIACgBIAEAAIACABIABACIAAAFIgBABIgCABIgCABgAA/h1IgCgBIAAgBIgBgCIABgDIAAgCIACgBIAFAAIABABIABAFIAAACIgCACIgDABgAAWh2QgEgCgFgEQgEgEgCgGQgBgFAAgGQAAgIABgEIAGgKQADgDAHgDQAGgCAFAAQAGAAAFACQAEABAEAEIgCAEIgBABIgBAAIgDgBIgCgBIgEgDIgGAAIgIABIgHAEIgDAIIgCAKQAAAFACAEIADAHQACACAFACQACABAGAAIAEAAIAHgCIAEgCIAAgBIACAAIADAEQgDAEgGADQgEACgHAAQgIAAgEgCgAmeh2QgDgCgGgEQgEgGgCgEQgCgHAAgEQAAgFACgHQADgGADgEQAEgDAFgDQAIgCAEAAQAEAAAJACQAFADADADQADADACAHQADAEAAAIQAAAGgDAFQgBAGgEAEQgEAEgEACQgGACgHAAQgHAAgFgCgAmainIgGAEQgDADgCAFIgBAKQAAAFABAEQABADAEAEQADADADABIAIABIAJgBIAGgEQADgCABgFIACgJIgCgKIgEgIIgGgEIgJgBgAneh2QgFgCgEgEQgEgGgCgEQgCgFAAgGQAAgIACgEQACgGAEgEQACgDAHgDQAHgCAEAAQAFAAAHACQAHADADADQAEAEABAGQACAHAAAFQAAAEgCAHQgBAEgEAGQgFAEgFACQgEACgIAAQgGAAgFgCgAnbinIgGAEIgFAIIgBAKIABAJQACAFADACIAGAEIAIABIAIgBQADgBAEgDQAEgEAAgDQACgEAAgFQAAgFgCgFQgBgFgDgDIgHgEIgIgBgAofh2QgEgCgEgEQgFgEgCgGQgBgFAAgGQAAgIABgEQADgHAEgDQACgDAGgDQAIgCAEAAQAFAAAGACQAHADADADIAFAKQACAEAAAIQAAAGgCAFIgFAKQgGAEgEACQgEACgHAAQgHAAgFgCgAocinIgGAEIgEAIIgBAKIABAJIAEAHIAGAEIAJABIAIgBIAHgEQADgEAAgDQACgEAAgFIgCgKQgBgFgCgDIgHgEIgIgBgAH+h1IAUgbIgEACIgGABIgHgBIgEgDIgEgFIgCgHIACgHIAEgHIAGgDQADgBAEAAQAFAAAEABIAGADIADAHIABAIIAAAEIgDAJIgRAZIgEABgAIGioQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBABIgCACIgBAGQAAAEADADQADAEAFAAIAGgBIADgDIACgDIABgEIgBgGIgCgCIgDgDIgGgBgAHPh1IAAgGIAMAAIAAgpIgKAIIgBAAIgCAAIgBAAIgCgEIARgPIAHAAIAAA0IALAAIAAAGgAGzh1IAAgPIgZAAIgCgBIgBgBIAAgDIAbgmIAIAAIAAAlIAIAAIAAAEIAAABIgBABIgHAAIAAAPgAGfiKIAUAAIAAgZIABgCgAFCh1IAAgGIANAAIAAgpIgLAIIgBAAIgBAAIgBAAIgCgEIARgPIAGAAIAAA0IALAAIAAAGgAEUh1IAAgGIALAAIAAgpIgJAIIgBAAIgCAAIAAAAIgDgEIARgPIAHAAIAAA0IAKAAIAAAGgACih1IAAg6IAjAAIAAAHIgaAAIAAAzgAB5h1IAAgaIgfAAIAAAaIgIAAIAAg6IAIAAIAAAaIAfAAIAAgaIAIAAIAAA6gAghh1IAAgwIgBADIgeAsIgCABIgGAAIAAg6IAIAAIAAAoIAAAFIAAADIABgDIAegsIACgBIAGAAIAAA6gAifh1IAAgaIgeAAIAAAaIgJAAIAAg6IAJAAIAAAaIAeAAIAAgaIAIAAIAAA6gAjTh1QgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIgBgBIgFgOIgaAAIgGAOIgBABIgBABIgHAAIAYg6IAIAAIAXA6gAjpijIgKAZIAVAAIgIgXIgCgCIgBgEgAkMh1IgCgBIgBgBIgPgWIgDgCIgDAAIgGAAIAAAaIgJAAIAAg6IAJAAIAAAZIAIAAIABgBIASgXIACgBIAHAAIgRAXQgCADgCACIADACIAUAcgADkh7IgBgCIAAgCIAHgKIABgBIgBAAIAAgCIgHgKIAAgCIABgBIADgBIAKAQIAAAAIgKAQgADYh7IgBgCIAAgCIAHgKIABgBIAAAAIgBgCIgHgKIAAgCIABgBIADgBIAKAQIAAAAIgKAQgAlNiKIAAAAIAKgQIADABIABABIAAACIgIAMIABABIAHAKIAAACIgBACIgDABgAlZiKIAAAAIAKgQIADABIABABIgBACIgHAMIABABIAGAKIABACIgBACIgDABg");
	this.shape.setTransform(-1,0.2,1,1,0,0,0,20,-4.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal, new cjs.Rectangle(-79.6,-17.9,157.2,40.7), null);


(lib.butt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYAvIAAhdIAxAAIAAARIggAAIAAAWIAfAAIAAAPIgfAAIAAAWIAgAAIAAARg");
	this.shape.setTransform(47,0.8,1.333,1.333);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAvIAAhdIAxAAIAAARIggAAIAAAWIAfAAIAAAPIgfAAIAAAWIAgAAIAAARg");
	this.shape_1.setTransform(38.2,0.8,1.333,1.333);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARAvIAAgoIghAAIAAAoIgSAAIAAhdIASAAIAAAmIAhAAIAAgmIASAAIAABdg");
	this.shape_2.setTransform(28,0.8,1.333,1.333);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfAvIAAhdIA2AAIAAARIgkAAIAAATIAOAAQATAAAIAMQAEAHAAAJQAAANgJAIQgIAIgOAAgAgNAeIAOAAQAGAAAEgEQAEgDAAgFQAAgFgDgCQgEgFgHAAIgOAAg");
	this.shape_3.setTransform(17.4,0.8,1.333,1.333);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiAjQgPgOAAgVQAAgTAPgOQAOgPAUAAQAVAAAPAPQANAOAAATQAAAVgNAOQgPAOgVAAQgUAAgOgOgAgWgWQgJAKAAAMQAAANAJAKQAJAJANAAQANAAAKgJQAKgKgBgNQABgMgKgKQgJgJgOAAQgNAAgJAJg");
	this.shape_4.setTransform(4.9,0.8,1.333,1.333);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdAvIAAhdIAaAAQASAAAKAMQAFAHAAALQAAALgHAHQgIAKgSgBIgJAAIAAAkgAgMgFIALAAQAOAAgBgMQABgMgOAAIgLAAg");
	this.shape_5.setTransform(-6.5,0.8,1.333,1.333);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAiA4IAAgSIhDAAIAAASIgRAAIAAgjIAJAAIAihMIAPAAIAiBMIAJAAIAAAjgAgWAVIAtAAIgXg0g");
	this.shape_6.setTransform(-18.6,2,1.333,1.333);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgiAjQgPgOAAgVQAAgTAPgOQAOgPAUAAQAVAAAOAPQAOAOABATQgBAVgOAOQgOAOgVAAQgUAAgOgOgAgWgWQgJAKAAAMQAAANAJAKQAKAJAMAAQAOAAAJgJQAKgKgBgNQAAgMgJgKQgJgJgOAAQgMAAgKAJg");
	this.shape_7.setTransform(-32.7,0.8,1.333,1.333);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AARAvIAAhMIghAAIAABMIgSAAIAAhdIBEAAIAABdg");
	this.shape_8.setTransform(-45.6,0.8,1.333,1.333);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7E0").s().p("An6CDIAAkFIP1AAIAAEFg");
	this.shape_9.setTransform(0,-0.1,1.333,1.333);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.butt, new cjs.Rectangle(-67.5,-17.4,135.1,34.9), null);


// stage content:
(lib._120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgJSguyISlAAMAAABdlIylAAg");
	this.shape.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(219));

	// t5
	this.instance = new lib.t5();
	this.instance.parent = this;
	this.instance.setTransform(60.6,404.1,0.575,0.575,0,0,0,0.3,0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(159).to({_off:false},0).to({regX:0.1,scaleX:0.72,scaleY:0.72,y:404.2,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.3,scaleX:0.57,scaleY:0.57,y:404.1,alpha:0},6,cjs.Ease.get(1)).wait(1));

	// t3
	this.instance_1 = new lib.t3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(60.6,404.1,0.575,0.575,0,0,0,0.3,0.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(106).to({_off:false},0).to({regX:0.1,scaleX:0.72,scaleY:0.72,y:404.2,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.3,scaleX:0.57,scaleY:0.57,y:404.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(53));

	// t2
	this.instance_2 = new lib.t2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(60.6,404.1,0.575,0.575,0,0,0,0.3,0.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(53).to({_off:false},0).to({regX:0.1,scaleX:0.72,scaleY:0.72,y:404.2,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.3,scaleX:0.57,scaleY:0.57,y:404.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(106));

	// t1
	this.instance_3 = new lib.t1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(60.5,405.2,0.575,0.575,0,0,0,0.1,0.1);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({regX:0,regY:0,scaleX:0.72,scaleY:0.72,y:404.1,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.1,regY:0.1,scaleX:0.57,scaleY:0.57,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(159));

	// 5.jpg
	this.instance_4 = new lib.pic5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(100,245);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(159).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).wait(1));

	// 3.jpg
	this.instance_5 = new lib.pic3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(100,245);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(106).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(53));

	// 2.jpg
	this.instance_6 = new lib.pic2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(100,245);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(53).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(106));

	// 1.jpg
	this.instance_7 = new lib.pic1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(100,245);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(159));

	// Слой 3
	this.instance_8 = new lib.butt();
	this.instance_8.parent = this;
	this.instance_8.setTransform(60.5,482.9,0.75,0.75);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(159).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({x:80.5,alpha:0},6,cjs.Ease.get(1)).wait(1));

	// fon
	this.instance_9 = new lib.legal();
	this.instance_9.parent = this;
	this.instance_9.setTransform(81.4,562.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00A7E0").s().p("ApDBSQgqgmAZg3QAWgzBFgdQBNggB9AAQAcAAAZADIAhAEIANADIgSAgQgngKghAAQhAAAgzASQhHAZgKAyQgHAdAWAbQAcAiA8gDQAUgBAkgMQAtgQAagVIBAg3IAMgHQAIgDAKAAIBEAAIAWBcIAqhcIBLAAIArBHIAghHIBFAAIg9CDIhGAAIgthMIghBMIgsAAIAAAAIhRAAIgDgXIhKAAIgYAWIgwAAQg5AUhJAAQhpAAgugqgAjGA3IAsAAIgEglgAGFB1IAsgsIgshjIBDAAIATA1IA3g1IBNAAIiFCEQgGAGgFACIgQADgAD9BpIhuAAIA8iDIBuAAQA2AAATAaQAQATgMAaQgLAYgdAQQgkAUg6AAIgDAAgADoBIIATAAQAXAAARgGQAcgIAGgVQAIgfg1AAIgTAAg");
	this.shape_1.setTransform(61.8,73,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.instance_9}]}).wait(219));

	// bg
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("EgJXAu4MAAAhdvISvAAMAAABdvg");
	this.shape_2.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(219));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(40,299.5,160,601);
// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/120x600_atlas_.jpg", id:"120x600_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;