(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"480x320_atlas_P_", frames: [[608,0,59,59],[0,0,606,187]]},
		{name:"480x320_atlas_NP_", frames: [[0,0,600,398],[0,400,600,398]]}
];


// symbols:



(lib._1Ресурс122x = function() {
	this.spriteSheet = ss["480x320_atlas_P_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._1Ресурс82x = function() {
	this.spriteSheet = ss["480x320_atlas_P_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._1 = function() {
	this.spriteSheet = ss["480x320_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["480x320_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglApQgRgRAAgYQAAgXARgRQARgRAXAAQASAAANAJQAOAKAHAPIgXAAQgHgHgGgDQgHgEgIAAQgQAAgKALQgLALAAAPQAAAPALAMQALALAPAAQAIAAAGgDQAIgDAEgHIAYAAQgGAPgOAJQgOAJgRAAQgXAAgRgRg");
	this.shape.setTransform(54.3,7.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgA3IgLgdIgpAAIgLAdIgXAAIAvhuIAPAAIAvBugAgMAHIAZAAIgNggg");
	this.shape_1.setTransform(43.2,7.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AASA3IAAgpIgSAAQgLAAgGgDQgFgBgFgDQgFgFgDgFQgCgGAAgKIAAgkIAUAAIAAAhIABAJQABACACACQACACADAAIAIABIASAAIAAgxIAUAAIAABug");
	this.shape_2.setTransform(32.8,7.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAZBFIAAhNIgxBNIgUAAIAAhuIAUAAIAABNIAxhNIAUAAIAABugAgRg1QgIgGgBgJIARAAQAAADADACQADACADAAQAEAAADgCQACgCABgDIARAAQgCAJgHAGQgHAGgLAAQgKAAgHgGg");
	this.shape_3.setTransform(22.8,6.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdA3IAAhuIA7AAIAAAUIgmAAIAAAaIAkAAIAAATIgkAAIAAAZIAmAAIAAAUg");
	this.shape_4.setTransform(13.5,7.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AglApQgRgRAAgYQAAgXARgRQARgRAXAAQASAAANAJQAOAKAHAPIgYAAQgFgHgHgDQgHgEgIAAQgQAAgKALQgLALAAAPQAAAPALAMQALALAPAAQAIAAAGgDQAIgDAEgHIAYAAQgHAQgNAIQgOAJgRAAQgXAAgRgRg");
	this.shape_5.setTransform(3.7,7.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgpApQgRgSABgXQAAgXAQgRQARgRAYAAQAZAAARARQARARAAAXQAAAXgRASQgRARgZAAQgXAAgSgRgAgagaQgLAMAAAOQAAAQALALQALALAPAAQAQAAALgLQALgMAAgPQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_6.setTransform(-12,7.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAmA3IAAhSIgdBSIgRAAIgdhSIAABSIgVAAIAAhuIAcAAIAeBUIAfhUIAcAAIAABug");
	this.shape_7.setTransform(-25.2,7.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AARA3IAAgrIgBAAIgcArIgYAAIAegoQgNgCgIgJQgJgJAAgNQAAgSALgJQAKgJAUgBIAgAAIAABugAgKgeQgFAEAAAIQAAAIAFAEQAFAEAJAAIANAAIAAghIgNAAQgJAAgFAFg");
	this.shape_8.setTransform(-36.9,7.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAgAAQATABAJAJQAKAJAAAQQABAPgLAJQgKAKgSAAIgKAAIAAApgAgNgGIALAAQAIAAAEgDQAFgDAAgIQAAgHgFgEQgDgEgJAAIgLAAg");
	this.shape_9.setTransform(-45,7.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAUA3IAAhaIgnAAIAABaIgVAAIAAhuIBRAAIAABug");
	this.shape_10.setTransform(-54.6,7.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVFnQgPgPAAgUQAAgVAPgPQAOgPAVAAQAVAAAPAPQAOAPAAAVQAAAUgOAPQgPAPgVAAQgVAAgOgPgAgJEsQgJAKAAANQAAAOAJAKQAJAJAOAAQAOAAAJgJQAKgLAAgNQAAgMgKgLQgJgJgOAAQgOAAgJAJgAjVFnQgOgPAAgVQAAgUAOgPQAQgPAUAAQAQAAALAIQAMAIAGAOIgUAAQgEgGgHgDQgGgDgIAAQgOAAgJAJQgJAKAAANQAAAOAJAKQAKAJAOAAQAGAAAGgCQAGgDAFgGIAUAAQgGANgLAIQgMAIgPAAQgVAAgPgPgAEjFzIAAglIAAAAIgaAlIgVAAIAbgjQgMgCgHgHQgHgIAAgMQAAgPAJgIQAJgJASAAIAcAAIAABggAELEoQgEAEAAAHQAAAHAEADQAFAEAJAAIAKAAIAAgdIgKAAQgJAAgFAEgADVFzIAAhDIgrBDIgSAAIAAhgIASAAIAABEIArhEIASAAIAABggABNFzIAAhgIAXAAQARAAAIAHQAJAHAAALQAAAHgDAFQgDAFgFACQAIADAEAGQAEAGAAAIQAAAOgJAIQgKAHgTAAgABfFiIALAAQAIAAAEgDQAEgDAAgGQAAgFgEgEQgEgDgIgBIgLAAgABfE4IAIAAQAGAAADgDQAEgCAAgFQAAgEgEgDQgDgDgGAAIgIAAgAg4FzIgbhHIgaBHIgUAAIAmhgIAQAAIAmBggAkfFzIALgYIgkhIIAVAAIAZAzIAXgzIATAAIgrBggAibDSIAAgTIhAAAIAAhgIASAAIAABPIAjAAIAAhPIASAAIAABPIALAAIAAAkgAnTCzQgOgPAAgVQAAgUAOgPQAQgPAUAAQAQAAALAIQAMAIAGAOIgVAAQgEgGgGgDQgGgDgIAAQgOAAgJAJQgJAKAAANQAAAOAJAKQAJAJAOAAQAHAAAGgCQAGgDAFgGIAUAAQgGANgLAIQgMAIgPAAQgVAAgPgPgAGuC/IAAhgIA0AAIAAARIgiAAIAAAXIAhAAIAAARIghAAIAAAWIAiAAIAAARgAGLC/IAAhgIASAAIAABggAFBC/IAAhgIASAAIAAAlIAOAAQAQAAAIAIQAIAIAAAOQAAANgJAIQgIAIgPAAgAFTCuIAOAAQAGAAAEgDQAEgDAAgGQAAgGgEgDQgEgEgGAAIgOAAgAEeC/IAAgoIgjAAIAAAoIgSAAIAAhgIASAAIAAAnIAjAAIAAgnIARAAIAABggACdC/IAAhgIASAAIAAAlIAOAAQAQAAAIAIQAIAIAAAOQAAANgJAIQgIAIgPAAgACvCuIAPAAQAFAAAFgDQAEgDAAgGQgBgHgDgCQgFgEgFAAIgPAAgACAC/IgahHIgbBHIgTAAIAmhgIAPAAIAmBggAAiC/IgJgZIgjAAIgKAZIgTAAIAnhgIAOAAIAoBggAgDCVIAVAAIgLgcgAhDC/IAAhDIgrBDIgSAAIAAhgIASAAIAABEIArhEIASAAIAABggAkeC/IAAhgIAzAAIAAARIgiAAIAAAXIAhAAIAAARIghAAIAAAWIAiAAIAAARgAlCC/IAAhPIgjAAIAABPIgSAAIAAhgIBHAAIAABggAisjoIAAgWIhVAAIAAAWIgWAAIAAgsIALAAIAshhIATAAIAsBhIALAAIAAAsgAj0kUIA7AAIgdhCgAEjj+IAAhUIg1BUIgWAAIAAh3IAWAAIAABTIA1hTIAWAAIAAB3gACSj+IAAh3IA7AAIAAAWIglAAIAABhgAA1j+IAAh3IAWAAIAAAuIARAAQASAAALAKQALAKAAAQQAAAQgLALQgMAKgRAAgABLkUIASAAQAIAAAEgEQAFgDAAgIQAAgHgFgEQgEgEgIAAIgSAAgAAJj+IAAgyIgqAAIAAAyIgWAAIAAh3IAWAAIAAAwIAqAAIAAgwIAWAAIAAB3gAiKj+IAAh3IA/AAIAAAWIgpAAIAAAbIAoAAIAAAVIgoAAIAAAbIApAAIAAAWg");
	this.shape_11.setTransform(0,20.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4, new cjs.Rectangle(-58.7,-16.5,118.6,74.8), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUA4IANgcIgrhTIAZAAIAcA7IAag7IAWAAIgyBvg");
	this.shape.setTransform(54.9,7.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBCIAAgVIhPAAIAAAVIgUAAIAAgpIAKAAIAphaIARAAIApBaIAKAAIAAApgAgaAZIA2AAIgcg+g");
	this.shape_1.setTransform(43.5,8.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoApQgSgQABgZQgBgXASgRQAQgRAYAAQAZAAARARQAQARABAXQgBAZgQAQQgQARgaAAQgYAAgQgRgAgagaQgLALAAAPQAAAQALALQALALAPAAQAPAAAMgLQALgLAAgQQAAgPgLgLQgMgLgPAAQgPAAgLALg");
	this.shape_2.setTransform(31.1,7.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA4IAAhvIA3AAIAAAVIgiAAIAABag");
	this.shape_3.setTransform(21.9,7.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAnA4IAAhSIgfBSIgPAAIgehSIAABSIgVAAIAAhvIAcAAIAeBUIAfhUIAcAAIAABvg");
	this.shape_4.setTransform(4.3,7.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpApQgRgQAAgZQAAgXARgRQARgRAYAAQAZAAARARQAQARAAAXQABAZgSAQQgQARgZAAQgYAAgRgRgAgagaQgLAMAAAOQAAAPALAMQALALAPAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgOAAgMALg");
	this.shape_5.setTransform(-8.9,7.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA4IAAhvIAbAAQASACAKAGQAKAIAAAOQAAAHgEAGQgDAEgGAEQAKAEAEAFQAFAHAAAKQAAAQgLAJQgKAJgWAAgAgOAkIANAAQAHAAAFgEQAEgEAAgGQAAgHgEgEQgFgDgHAAIgNAAgAgOgMIAKAAQAFAAAEgDQAEgCAAgGQAAgGgEgDQgEgCgFAAIgKAAg");
	this.shape_6.setTransform(-19.3,7.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgoApQgSgQABgZQgBgXASgRQAQgRAYAAQAZAAARARQARARAAAXQAAAZgRAQQgQARgaAAQgYAAgQgRgAgagaQgLAMAAAOQAAAPALAMQALALAPAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgOAAgMALg");
	this.shape_7.setTransform(-30.2,7.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUA4IAAgvIgoAAIAAAvIgUAAIAAhvIAUAAIAAAtIAoAAIAAgtIAVAAIAABvg");
	this.shape_8.setTransform(-41.6,7.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA4IAAhvIAbAAQASACAKAGQAKAIAAAOQAAAHgEAGQgCAEgHAEQAKAEAEAFQAFAHAAAKQAAAQgLAJQgKAJgWAAgAgOAkIANAAQAHAAAFgEQAEgEAAgGQAAgHgEgEQgFgDgHAAIgNAAgAgOgMIAKAAQAFAAAEgDQAEgCAAgGQAAgGgEgDQgEgCgFAAIgKAAg");
	this.shape_9.setTransform(-54.3,7.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AASFrQgOgPAAgUQAAgVAOgPQAPgPAWAAQAUAAAQAPQAOAPAAAVQAAAUgOAPQgPAOgVAAQgXAAgOgOgAAfEwQgJAJAAAOQAAAOAJAJQAKAKANAAQAOAAAKgKQAJgKAAgNQAAgOgJgJQgJgKgOAAQgPAAgJAKgAi0FrQgOgPAAgUQAAgVAOgPQAPgPAVAAQAWAAAPAPQAOAPAAAVQABAUgQAPQgOAOgWAAQgVAAgPgOgAinEwQgJAJAAAOQAAAOAJAJQAKAKANAAQAOAAAKgKQAJgJAAgOQAAgOgJgJQgKgKgOAAQgOAAgJAKgAE4F3IAMgZIglhIIAWAAIAZA0IAWg0IATAAIgrBhgAEDF3IAAgoIgjAAIAAAoIgSAAIAAhhIASAAIAAAoIAjAAIAAgoIASAAIAABhgACqF3IAAgoIgiAAIAAAoIgSAAIAAhhIASAAIAAAoIAiAAIAAgoIASAAIAABhgAgQF3IgahIIgaBIIgUAAIAmhhIAQAAIAlBhgAjWF3IgegrIAAArIgSAAIAAhhIASAAIAAAqIAegqIAVAAIgkAwIAkAxgAlvF3IAAhhIAXAAQARABAIAGQAJAIAAALQAAAHgDAEQgDAEgFADQAHACAFAHQAEAHAAAIQAAAOgKAHQgJAIgTAAgAldFlIALAAQAHAAAEgCQAEgDABgGQgBgHgEgCQgDgEgIAAIgLAAgAldE7IAIAAQAGAAADgCQADgCABgFQAAgFgDgCQgFgDgFAAIgIAAgAAvC3QgPgPAAgUQAAgVAPgPQAPgPAVAAQAVAAAPAPQAOAPAAAVQAAAUgOAPQgPAOgVAAQgWAAgOgOgAA7B8QgJAJAAAOQAAAOAJAJQAKAKAOAAQAOAAAJgKQAJgJAAgOQAAgOgJgJQgJgKgOAAQgPAAgJAKgAkgC3QgOgOAAgWQAAgVAOgOQAPgPAVAAQAPAAAMAHQAMAJAFANIgUAAQgFgGgFgDQgHgDgHAAQgOAAgJAKQgJAJAAAOQAAANAJAKQAJAKAOAAQAHAAAGgDQAGgCAEgHIAVAAQgGAOgMAHQgKAIgQAAQgWAAgOgOgAFxDDIgKgZIgkAAIgJAZIgUAAIAohhIAOAAIApBhgAFKCYIAXAAIgMgcgAENDDIgegrIAAArIgSAAIAAhhIASAAIAAAqIAegqIAWAAIgkAwIAkAxgACSDDIAAhhIAXAAQAQABAJAGQAJAHAAAMQgBAHgCAEQgCAEgGADQAHACAFAHQAFAHAAAIQAAANgKAIQgKAIgTAAgACkCxIALAAQAIAAADgCQAFgDAAgGQAAgHgFgCQgDgEgIAAIgLAAgACkCHIAIAAQAHAAADgCQACgCABgFQAAgFgDgCQgEgDgGAAIgIAAgAACDDIAAgoIgjAAIAAAoIgRAAIAAhhIARAAIAAAoIAjAAIAAgoIARAAIAABhgAhQDDIgKgZIgkAAIgJAZIgUAAIAphhIANAAIApBhgAh3CYIAXAAIgMgcgAi6DDIAAhPIgSAAIAAgSIA2AAIAAASIgSAAIAABPgAlqDDIALgZIglhIIAWAAIAaA0IAVg0IAUAAIgsBhgAC6kOQgRgSgBgaQABgaARgRQATgTAaAAQAaAAASATQASARAAAaQAAAagSASQgRARgbAAQgaAAgTgRgADKlXQgLAMAAAQQAAARALANQAMALARABQARgBAMgLQAMgNAAgRQAAgQgMgMQgMgMgRABQgRgBgMAMgAgBkPQgSgRAAgbQAAgaASgRQARgSAaAAQASAAAPAKQAOAJAIARIgZAAQgFgGgIgFQgIgDgJAAQgRgBgLAMQgMANAAAPQAAASAMAMQALALARABQAIgBAIgDQAJgEAEgHIAZAAQgHARgOAJQgOAJgTAAQgaABgRgTgAB7j/IAAhiIgWAAIAAgUIBCAAIAAAUIgWAAIAABigAhgj/IAAh2IBAAAIAAAUIgqAAIAAAcIAoAAIAAAWIgoAAIAAAbIAqAAIAAAVgAiLj/IAAhZIggBZIgTAAIgfhZIAABZIgWAAIAAh2IAeAAIAgBaIAhhaIAeAAIAAB2g");
	this.shape_10.setTransform(0,20.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-57.9,-17.1,118,75.4), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVA3IANgcIgqhSIAZAAIAcA7IAag7IAWAAIgyBug");
	this.shape.setTransform(54.9,-1.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBCIAAgVIhPAAIAAAVIgVAAIAAgpIALAAIAphaIARAAIApBaIALAAIAAApgAgaAZIA2AAIgcg+g");
	this.shape_1.setTransform(43.5,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpApQgRgRABgYQAAgWAQgSQARgRAYAAQAZAAARARQARASAAAWQAAAYgRARQgRARgZAAQgXAAgSgRgAgagaQgLAMAAAOQAAAQALALQALALAPAAQAQAAALgLQALgLAAgQQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_2.setTransform(31,-1.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA3IAAhuIA3AAIAAAUIgiAAIAABag");
	this.shape_3.setTransform(21.9,-1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAmA3IAAhSIgdBSIgRAAIgdhSIAABSIgVAAIAAhuIAcAAIAeBUIAfhUIAcAAIAABug");
	this.shape_4.setTransform(4.2,-1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpApQgQgQAAgZQAAgWAQgSQARgRAYAAQAZAAARARQARARAAAXQAAAZgRAQQgSARgYAAQgYAAgRgRgAgagaQgLALAAAPQAAAQALALQAKALAQAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgQAAgKALg");
	this.shape_5.setTransform(-8.9,-1.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAaAAQATABAKAHQAJAIAAANQAAAIgDAGQgEAFgFADQAJADAFAGQAFAHAAAKQAAAQgLAJQgLAIgVAAgAgOAjIANAAQAIABAEgEQAFgEgBgGQABgHgFgEQgEgDgIgBIgNAAgAgOgMIAJAAQAGAAAEgDQADgDAAgFQAAgGgDgCQgEgEgGAAIgJAAg");
	this.shape_6.setTransform(-19.3,-1.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgpApQgQgQAAgZQAAgWAQgSQARgRAYAAQAaAAAQARQAQARABAXQgBAZgQAQQgRARgZAAQgYAAgRgRgAgagaQgLALAAAPQAAAQALALQALALAPAAQAQAAALgLQALgMAAgPQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_7.setTransform(-30.2,-1.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUA3IAAguIgnAAIAAAuIgVAAIAAhuIAVAAIAAAtIAnAAIAAgtIAVAAIAABug");
	this.shape_8.setTransform(-41.7,-1.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAbAAQASABAKAHQAJAIAAANQAAAIgDAGQgEAFgFADQAJADAFAGQAFAHAAAKQAAAQgLAJQgLAIgVAAgAgOAjIANAAQAIABAEgEQAFgEgBgGQABgHgFgEQgEgDgIgBIgNAAgAgOgMIAJAAQAGAAAEgDQAEgDAAgFQAAgGgEgCQgEgEgGAAIgJAAg");
	this.shape_9.setTransform(-54.3,-1.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AASA7IAAguIgBAAIgeAuIgaAAIAhgrQgPgDgIgJQgJgIAAgPQAAgSALgLQAMgKAVAAIAiAAIAAB1gAgLggQgFAEAAAJQAAAJAFAEQAGAEAKAAIANAAIAAgjIgNAAQgKAAgGAFg");
	this.shape_10.setTransform(21,-19.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AApA7IAAhXIggBXIgRAAIgghXIAABXIgWAAIAAh1IAeAAIAgBZIAhhZIAeAAIAAB1g");
	this.shape_11.setTransform(9.1,-19.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgfA7IAAh1IA/AAIAAAVIgpAAIAAAbIAnAAIAAAVIgnAAIAAAbIApAAIAAAVg");
	this.shape_12.setTransform(-2.4,-19.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AglA7IAAh1IAhAAQATAAAMAKQALAJAAASQAAAQgLAJQgLAKgUAAIgLAAIAAAtgAgPgGIANAAQAIAAAFgEQAFgDAAgIQAAgIgFgEQgEgEgJAAIgNAAg");
	this.shape_13.setTransform(-10.7,-19.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AglA7IAAh1IAcAAQATAAALAIQAKAJAAAOQAAAHgDAHQgDAEgGAFQAJADAFAGQAFAJAAAJQABASgMAJQgMAJgXAAgAgPAmIAOAAQAIAAAEgEQAFgEABgHQgBgHgFgEQgEgEgIAAIgOAAgAgPgNIAKAAQAGAAAEgDQADgDACgGQAAgGgFgDQgEgDgGAAIgKAAg");
	this.shape_14.setTransform(-19.9,-19.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("ABkDXQgOgOAAgVQAAgVAPgPQAOgOAVAAQAPAAAMAHQAMAJAGANIgUAAQgFgGgGgCQgGgDgHAAQgPgBgJAKQgJAKAAANQAAAMAJALQAKAKAOAAQAGAAAGgDQAGgCAFgGIAUAAQgGANgLAIQgLAHgQAAQgVAAgPgPgAotDXQgPgOAAgVQAAgUAPgQQAPgOAVAAQAPAAALAHQAMAJAGANIgUAAQgFgFgGgDQgGgDgHAAQgOgBgKAKQgJAKAAANQAAAOAKAJQAIAKAPAAQAHAAAGgDQAGgCAEgGIAVAAQgGANgMAIQgMAHgPAAQgVAAgOgPgAIrDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAHNDkIgegqIAAAqIgSAAIAAhgIASAAIAAApIAegpIAVAAIgkAvIAkAxgAEbDkIAAhgIASAAIAABPIAeAAIAAhPIARAAIAABPIAeAAIAAhPIASAAIAABggADSDkIAMgYIglhIIAVAAIAaAzIAWgzIATAAIgrBggAAZDkIAAhDIgqBDIgSAAIAAhgIASAAIAABDIAqhDIASAAIAABggAhkDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAjCDkIgegqIAAAqIgSAAIAAhgIASAAIAAApIAegpIAVAAIgkAvIAkAxgAk6DkIAAhgIAaAAQARABAJAHQAJAIAAANQAAAOgJAIQgJAJgRgBIgJAAIAAAlgAkpCuIALAAQAHAAAEgDQAEgDAAgHQAAgFgEgEQgEgDgHAAIgLAAgAleDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAnIDkIAAhPIgRAAIAAgRIA1AAIAAARIgSAAIAABPgAB+AjQgOgOAAgVQAAgTAOgQQAQgOAVAAQAVAAAPAOQAOAQAAATQAAAVgOAOQgPAPgVAAQgWAAgPgPgACLgWQgJAJAAANQAAAOAJAKQAKAJANAAQAPAAAJgKQAJgJAAgOQAAgNgJgJQgJgKgOABQgPgBgJAKgAhmAjQgOgOAAgVQAAgTAOgQQAQgOAUAAQAQAAALAHQAMAJAGANIgVAAQgFgFgFgDQgGgDgIAAQgOgBgJAKQgJAKAAAMQAAAOAJAJQAJAKAOAAQAHAAAGgDQAGgCAFgGIAUAAQgGANgLAIQgMAHgPAAQgWAAgOgPgAEfAwIAAhCIgrBCIgSAAIAAhfIASAAIAABCIArhCIARAAIAABfgAAsAwIAAhfIAbAAQARABAIAHQAJAIAAANQAAAOgJAHQgIAJgRgBIgJAAIAAAlgAA+gFIAKAAQAIAAADgDQAEgDAAgHQAAgFgEgEQgDgDgIAAIgKAAgAAAAwIAAhOIgSAAIAAgRIA0AAIAAARIgRAAIAABOgAiTAwIAAhfIASAAIAABfgAjcAwIAAhfIARAAIAAAlIAPAAQAOgBAJAJQAJAHAAANQAAANgJAJQgKAIgNAAgAjLAfIAPAAQAGgBAEgDQAEgDAAgGQAAgGgEgDQgEgDgGAAIgPAAgAkqAwIAAhfIA4AAIAAARIgnAAIAAAUIAQAAQAQgBAIAKQAIAIAAALQAAANgJAJQgKAIgNAAgAkZAfIAQAAQAGgBAEgDQAEgDAAgGQAAgFgEgEQgEgDgGAAIgQAAgAD5g5QgGgGgBgIIAPAAQAAADACACQADACADAAQAEAAACgCQACgCABgDIAPAAQgCAIgGAGQgGAEgKAAQgKAAgGgEgAjqiQQgPgNAAgWQAAgUAPgQQAPgOAVAAQAWAAAOAOQAPAPAAAVQAAAVgPAOQgOAPgWAAQgWAAgOgPgAjdjKQgKAJAAAOQAAAOAKAKQAKAJANAAQAOAAAKgKQAJgJAAgOQAAgNgJgKQgKgKgOABQgOgBgJAKgAGJiDIAAhgIASAAIAABggAE/iDIAAhgIASAAIAAAlIAOAAQAPgBAJAJQAIAHAAAOQAAANgJAJQgJAIgOAAgAFRiUIAPAAQAGgBAEgDQAEgDAAgGQgBgGgDgDQgEgDgGAAIgPAAgAEciDIAAhIIgaBIIgPAAIgZhIIAABIIgSAAIAAhgIAYAAIAbBJIAahJIAZAAIAABggACkiDIAAhIIgZBIIgPAAIgahIIAABIIgSAAIAAhgIAYAAIAbBJIAbhJIAYAAIAABggAAziDIgKgZIgkAAIgIAZIgUAAIAnhgIAOAAIAoBggAAMitIAWAAIgLgcgAhNiDIAAhgIAbAAQARABAIAHQAJAIAAANQAAAOgJAIQgIAJgRgBIgJAAIAAAlgAg7i5IAKAAQAIAAADgDQAEgDAAgHQAAgFgEgEQgDgDgIAAIgKAAgAiGiDIAAhgIAwAAIAAARIgfAAIAABPgAk9iDIAAhgIAbAAQARABAJAHQAJAIAAANQAAANgJAJQgJAJgRgBIgJAAIAAAlgAkri5IALAAQAHAAAEgDQADgDABgHQAAgFgEgEQgEgDgHAAIgLAAgAlgiDIAAhPIgjAAIAABPIgSAAIAAhgIBHAAIAABgg");
	this.shape_15.setTransform(0,42.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-57.9,-25.8,118,91.8), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmpCaQgRgSAAgaQAAgaASgSQARgSAbAAQASAAAOAKQAPAJAIARIgZAAQgHgHgHgEQgHgDgJAAQgRAAgMAMQgLALAAARQAAARALALQAMAMARAAQAJAAAHgDQAHgDAFgHIAaAAQgHAPgPAKQgPAKgSAAQgaAAgSgSgAIRCpIAAh3IBAAAIAAAWIgqAAIAAAbIAoAAIAAAVIgoAAIAAAbIAqAAIAAAWgAHmCpIAAh3IAWAAIAAB3gAGLCpIAAh3IAWAAIAAAuIARAAQASAAALAKQALAKAAAQQAAAQgLALQgMAKgRAAgAGhCTIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAFfCpIAAgyIgrAAIAAAyIgWAAIAAh3IAWAAIAAAwIArAAIAAgwIAWAAIAAB3gADBCpIAAh3IAWAAIAAAuIASAAQASAAALAKQAKAKAAAQQAAAQgLALQgLAKgRAAgADXCTIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgACdCpIgghYIghBYIgYAAIAvh3IATAAIAvB3gAAiCpIAAhTIgzBTIgWAAIAAh3IAWAAIAABUIAzhUIAWAAIAAB3gAjHCpIAAh3IAWAAIAABhIAkAAIAAhhIAWAAIAABhIAkAAIAAhhIAWAAIAAB3gAkhCpIAOgeIguhZIAbAAIAfA/IAbg/IAYAAIg1B3gAoFCpIAAhTIg1BTIgWAAIAAh3IAWAAIAABUIA1hUIAWAAIAAB3gAoEhBQgSgSAAgaQAAgZASgTQASgSAaAAQATAAAOAKQAOAJAIARIgZAAQgHgHgGgEQgHgDgKAAQgRAAgMAMQgLALAAARQAAARAMALQAMAMAQAAQAJAAAHgDQAHgDAGgHIAZAAQgHAPgPAKQgOAKgSAAQgaAAgSgSgAGsgyIAAh3IA/AAIAAAWIgpAAIAAAbIAoAAIAAAVIgoAAIAAAbIApAAIAAAWgAGAgyIAAh3IAWAAIAAB3gAElgyIAAh3IAWAAIAAAuIASAAQASAAALAKQAKAKAAAQQAAAQgLALQgLAKgRAAgAE7hIIASAAQAIAAAFgEQAEgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAD6gyIAAgyIgrAAIAAAyIgWAAIAAh3IAWAAIAAAwIArAAIAAgwIAWAAIAAB3gABcgyIAAh3IAWAAIAAAuIARAAQASAAALAKQALAKAAAQQAAAQgLALQgMAKgRAAgAByhIIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAA4gyIghhYIgfBYIgYAAIAuh3IATAAIAvB3gAg7gyIgMgfIgrAAIgMAfIgZAAIAyh3IARAAIAyB3gAhqhmIAbAAIgNgjgAjZgyIAAh3IAhAAQAUAAALAKQALAKAAARQAAAQgKALQgLAKgVAAIgLAAIAAAtgAjDh0IANAAQAIAAAFgEQAFgEAAgIQAAgIgFgDQgEgEgJAAIgNAAgAkFgyIAAhTIg1BTIgWAAIAAh3IAWAAIAABUIA1hUIAWAAIAAB3gAmHgyIAAhhIgWAAIAAgWIBCAAIAAAWIgWAAIAABhg");
	this.shape.setTransform(0,-13.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AElAwIAAhfIASAAIAABfgADcAwIAAhfIARAAIAAAlIAOAAQAPAAAJAIQAIAHABAOQAAANgKAIQgJAIgOAAgADtAfIAOAAQAHAAAEgEQADgDAAgFQAAgGgDgEQgEgDgHAAIgOAAgAC4AwIAAgoIgjAAIAAAoIgSAAIAAhfIASAAIAAAmIAjAAIAAgmIASAAIAABfgABfAwIAAhDIgrBDIgSAAIAAhfIASAAIAABCIArhCIASAAIAABfgAheAwIAAhfIASAAIAABOIAdAAIAAhOIARAAIAABOIAeAAIAAhOIARAAIAABfgAh7AwIgKgZIgkAAIgKAZIgUAAIAphfIAOAAIAoBfgAijAGIAXAAIgLgbgAjiAwIAAhHIgaBHIgOAAIgahHIAABHIgSAAIAAhfIAYAAIAbBIIAbhIIAYAAIAABfg");
	this.shape_1.setTransform(0,25.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-59.2,-30.4,118.6,61), null);


(lib.p4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1Ресурс122x();
	this.instance.parent = this;
	this.instance.setTransform(93,-36);

	this.instance_1 = new lib._2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-150,-50);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.p4, new cjs.Rectangle(-150,-50,600,398), null);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-99.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1, new cjs.Rectangle(-150,-99.5,600,398), null);


(lib.know = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AgXAtIAAhZIAvAAIAAAQIgeAAIAAAVIAdAAIAAAPIgdAAIAAAVIAeAAIAAAQg");
	this.shape.setTransform(46,0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00A7E0").s().p("Ag0AtIAAhZIARAAIAABJIAbAAIAAhJIAQAAIAABJIAcAAIAAhJIAQAAIAABZg");
	this.shape_1.setTransform(36.7,0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00A7E0").s().p("AgdAtIAAhZIARAAIAAAjIAMAAQAOAAAIAHQAIAGAAANQAAANgJAHQgIAIgNAAgAgMAdIAMAAQAGAAADgDQAEgDAAgGQAAgFgEgDQgDgDgGAAIgMAAg");
	this.shape_2.setTransform(27.4,0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00A7E0").s().p("AAZAtIgZhCIgXBCIgTAAIAkhZIANAAIAkBZg");
	this.shape_3.setTransform(19.2,0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00A7E0").s().p("AghAhQgNgNAAgUQAAgSANgOQAOgOATAAQAUAAAOAOQANAOAAASQAAAUgNANQgNAOgVAAQgTAAgOgOgAgVgVQgJAJAAAMQAAANAJAIQAJAKAMgBQAOABAIgKQAJgIAAgNQAAgMgJgJQgIgIgOgBQgMABgJAIg");
	this.shape_4.setTransform(9.7,0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00A7E0").s().p("AgeAtIAAhZIA0AAIAAAQIgiAAIAAATIAMAAQAQAAAHAIQAIAGAAAMQAAANgJAHQgIAIgOAAgAgMAdIAMAAQAHAAADgDQADgDABgGQAAgFgDgDQgFgDgGAAIgMAAg");
	this.shape_5.setTransform(1.2,0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00A7E0").s().p("AgdAtIAAhZIARAAIAAAjIAMAAQAOAAAIAHQAIAGAAANQAAANgIAHQgIAIgOAAgAgMAdIAMAAQAGAAAEgDQADgDAAgGQAAgFgDgDQgEgDgGAAIgMAAg");
	this.shape_6.setTransform(-8.7,0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00A7E0").s().p("AgHAtIAAhJIgRAAIAAgQIAxAAIAAAQIgRAAIAABJg");
	this.shape_7.setTransform(-15,0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7E0").s().p("AAZAtIgJgXIggAAIgJAXIgSAAIAlhZIANAAIAlBZgAgKAGIAUAAIgKgag");
	this.shape_8.setTransform(-21.5,0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7E0").s().p("AAQAtIAAgmIgfAAIAAAmIgRAAIAAhZIARAAIAAAkIAfAAIAAgkIARAAIAABZg");
	this.shape_9.setTransform(-30.1,0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00A7E0").s().p("AgVAnQgJgIABgOIARAAQAAAGADADQADAFAGAAQAHAAADgEQAEgDAAgFQAAgGgDgDQgEgDgFAAIgIAAIAAgQIAGAAQAGABACgDQADgDAAgFQAAgFgDgDQgDgCgEAAQgFAAgCACQgDADAAAEIgRAAQAAgLAHgHQAHgHANgBQALAAAIAIQAIAGAAAMQAAAGgEAFQgDAFgGADQAHABAFAGQAEAGAAAIQAAAMgJAIQgJAGgNAAQgNAAgIgHg");
	this.shape_10.setTransform(-37.6,0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00A7E0").s().p("AgRAtIALgXIgihCIAUAAIAWAvIAVgvIATAAIgqBZg");
	this.shape_11.setTransform(-44.8,0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AolBvIAAjdIRKAAIAADdg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.know, new cjs.Rectangle(-54.9,-11.1,109.9,22.3), null);


(lib.eko = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMBZQgkgkAAg0QAAgyAkglQAkglA0AAQA0AAAlAlQAkAlAAAyQAAA0gkAkQgkAig1AAQg0AAgkgigAASg4QgWAXAAAhQAAAgAWAZQAYAZAiAAQAiAAAYgZQAXgZAAggQAAghgXgXQgYgXgiAAQgiAAgYAXgAnyBZQgkgkAAg0QAAgyAkglQAlglA0AAQAzAAAlAlQAkAlAAAyQAAA0gkAkQgkAig0AAQg0AAglgigAnTg4QgXAWAAAiQAAAiAXAXQAXAZAiAAQAkAAAWgZQAYgYAAghQAAghgYgXQgWgXgjAAQgjAAgXAXgAuYBoQgdgSgNggIAyAAQALANAQAHQASAIARAAQAZgBAWgQQAXgRAEgcIhqAAIAAgpIBqAAQgHgbgUgPQgUgRgbABQgSgBgSAIQgOAGgOAPIgyAAQAPggAcgUQAcgRAogDQA0AAAiAkQAjAjAAA0QAAA2gjAjQgjAig0AAQgmABgcgUgANGB2IAAjrIB/AAIAAApIhTAAIAAA3IBQAAIAAAqIhQAAIAAA2IBTAAIAAArgALYB2IAAjCIgsAAIAAgpICDAAIAAApIgsAAIAADCgAIOB2IAAjrIAsAAIAABbIAkAAQAlgBAUAUQAVASAAAjQAAAggWAUQgVATgjABgAI6BLIAkAAQAOABALgJQAJgGAAgPQAAgPgKgIQgJgIgPgBIgkAAgAG3B2IAAixIg/CxIglAAIg/ixIAACxIgsAAIAAjrIA7AAIBDC0IBBi0IA8AAIAADrgAh7B2IAAhjIhXAAIAABjIgsAAIAAjrIAsAAIAABeIBXAAIAAheIAsAAIAADrgApHB2IhJhoIAABoIgsAAIAAjrIAsAAIAABmIBJhmIA1AAIhZBzIBYB4g");
	this.shape.setTransform(96.5,12.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.eko, new cjs.Rectangle(0,0,193,24.7), null);


// stage content:
(lib._480x320 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EglagY6MBK1AAAMAAAAx1MhK1AAAg");
	this.shape.setTransform(240,160);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(305));

	// Слой 1
	this.instance = new lib.eko();
	this.instance.parent = this;
	this.instance.setTransform(369.7,98.3,0.72,0.72,0,0,0,96.6,12.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(75).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(215).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// t4
	this.instance_1 = new lib.t4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(369.6,145.1,1.44,1.44);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(225).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// t3
	this.instance_2 = new lib.t3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(369.6,145.6,1.44,1.44);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(150).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(75));

	// t2
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(369.6,158.3,1.44,1.44);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(75).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(150));

	// t1
	this.instance_4 = new lib.t1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(564,132.9,1.44,1.44);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:369.6},13,cjs.Ease.get(1)).wait(59).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(225));

	// Слой 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AoyBQQgpglAYg2QAVgxBDgcQBLggB6ABQAaAAAZADIAgAEIANADIgSAfQgmgLggAAQg9AAgzASQhEAYgKAwQgHAdAVAaQAbAhA7gDQATAAAkgNQArgPAagUIA9g1IAEgDIAIgEIAMgDIAGgBIBCAAIAVBbIAphaIBJAAIAqBFIAfhFIBCAAIg6B/IhEAAIgshJIghBJIgqAAIAAAAIhOAAIgDgWIhIAAIgYAVIgvAAQg2AThHAAQhnAAgsgogAjAA2IAqgBIgEgjgAF6ByIArgrIgrhgIBBAAIATA0IA1g1IBKAAIiACAQgHAHgEACIgQADgAD2BmIhrAAIA6h/IBsAAQAzAAATAZQAPATgLAZQgLAYgcAPQgjATg4AAIgDAAgADhBGIATAAQA/AAAJgiQAHgegzAAIgTAAg");
	this.shape_1.setTransform(369.7,42.7,1.4,1.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(305));

	// Слой 2
	this.instance_5 = new lib._1Ресурс82x();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,-16,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(305));

	// legal
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AEzAgIgHgEIgDgFIgEgHIAEgBQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAEAGIAEADIAGABIAFgBIAFgDIACgEIABgEIgBgFIgCgDIgFgDIgIgBIAAgFIAGgBIAGgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgEIAAgFQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAAAgBIgEgBIgFgBIgIACIgCADIgBAEIgCADIgDAAIgEgBIACgIIAFgGIAGgEIAIAAIAIAAIAGAEIAEAFIABAHIgBAGIgCAEIgDADIgFACQAGABAEADQADAHAAAEQAAAFgDADIgDAGIgHAEIgJABgAD/AhIgKgEIgDgCIACgEIADgCIACABIAGADIAGABIAGgBIAEgDIADgFIABgGIgBgGIgDgEIgDgBIgHgBIgKABIgGgBIAGgfIAfAAIAAAEIgCADQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgVAAIgCAQIAJAAIAIABIAIAEIAEAGIAAAIQAAAGgBADIgFAHIgIAEQgCACgGAAgACUAfQgEgCgEgEQgEgGAAgEQgCgEAAgLQAAgKACgEQAAgFAEgFQAEgEAEgDIAJgBIAKABQAFADADAEIAFAKIABAOIgBAPIgFAKQgDAEgFACIgKACgACYgYIgFAEIgDAIIAAAYIADAIIAFAFIAFABIAGgBQAEgCAAgDQACgBACgHIACgMIgCgMIgEgIQAAgCgEgCIgGgBgAAqAfQgFgDgCgDQgDgDgCgHQgDgGABgJQgBgIADgGQACgHADgDQACgEAFgDIAKgBIAJABQAHAEAAADQADACADAIIABAOIgBAPQgDAIgDACQAAACgHAEIgJACgAAugYIgFAEIgDAIIgBAMIABAMQACAHABABIAFAFIAGABIAFgBIAFgFQABgBACgHIACgMIgCgMIgDgIIgFgEIgFgBgAgJAfIgHgEIgEgHIgCgJIACgJIAGgKIAPgWIACgCIALAAIgTAYIgCAEIAEgCIAFgBIAHACIAHADIADAFQACADAAAGQAAAGgCACIgDAHIgHAEQgEACgFAAQgHAAgCgCgAgGAAIgEADIgDAEIgBAFIABAGIADAFIAEACIAGABIAEgBIAFgCIACgFIACgGIgCgFIgCgEQgCgDgDAAIgEAAgAkSAfQgFgCgDgEQgDgDgBgHQgCgEAAgLQAAgKACgEQABgHADgDQADgEAFgDIAJgBIAJABQAGADACAEIAGAKIABAOIgBAPIgGAKQgCAEgGACIgJACgAkOgYIgGAEIgCAIIgBAMIABAMIACAIIAGAFIAFABIAGgBQADgCABgDQACgBACgHIABgMIgBgMIgEgIQgBgCgDgCIgGgBgADZAgIAAgRIgeAAIgBgBIgBgFIAggpIAIAAIAAApIAJAAIAAAGIgJAAIAAARgADCAJIAXAAIAAgfgABZAgIAbg0IADgEIgiAAIgCAAIAAgCIAAgGIAtAAIAAAHIgcA3IgCABIgDABgAhEAgIAUgZIADgFIgFADIgHABQgFAAgBgCIgHgDIgEgFIgBgIQAAgFACgDIAEgHIAHgEQADgBAGAAQAGAAADABIAGAEIAEAHIACAIIgCALIgCAEIgTAcIgCABgAg7gYIgDACQgBABgBAAQAAABAAAAQgBABAAAAQAAABAAAAIgCAGQAAAFAFAEQADADAFAAIAGgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABgBIADgEIABgEIgCgGQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBIgEgCIgFgBgAh6AgIAeg4IgiAAIgBAAIAAgIIArAAIAAAHIgbA3IgCABQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAgAivAgIAeg4IghAAIgCAAIAAgIIAsAAIAAAHIgbA3IgFACgAjNAgIAAgRIgeAAIgBgBIgBgFIAfgpIAIAAIAAApIAKAAIAAAGIgKAAIAAARgAjkAJIAXAAIAAgfgAlNAgIAAgGIAOAAIAAguIgLAJIgBAAIgBABIgCgBIAAgBIgDgDIAUgRIAGAAIAAA6IANAAIAAAGg");
	this.shape_2.setTransform(355.4,310.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ADNAfIgIgEIADgFIACgBIACAAIADACIAEACIAFABIAGgBIAFgEIADgEIABgGIgBgGIgCgEIgFgBIgHgBIgKABIgFgBIAFgfIAfAAIAAAEIgBADIgEABIgUAAIgDAQIAKAAIAJABIAGAEIAEAFIACAJIgCAJIgGAHIgHAFIgJACgAg7AfIgHgEIADgFIACgBIACAAIAHAEIAFABIAGgBIAEgEIADgEIABgGIgBgGIgCgEIgFgBIgGgBIgKABIgGgBIAGgfIAfAAIAAAEIgBADQgBAAAAAAQAAAAgBABQAAAAgBAAQgBAAAAAAIgUAAIgEAQIAKAAIAJABQADAAADAEQADACABADQACADAAAGIgCAJIgFAHIgIAFIgIACgAHyAgIAAgdIgiAAIAAAdIgKAAIAAhAIAKAAIAAAdIAiAAIAAgdIAKAAIAABAgAGPAgIAAhAIAUAAQAHAAADABIAIAFIAFAGIABAIQAAAGgCADIgEAFIgIAFQgDABgHAAIgLAAIAAAYgAGYABIARgBIAFgDQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIACgFIgBgFIgDgFIgFgCIgRAAgAFeAgIAAhAIAnAAIAAAIIgdAAIAAA4gAEkAeQgGgCgEgEQgFgFgCgGQgDgGAAgHQAAgGADgHQADgHAEgDQAEgFAGgDQAGgCAHAAQAHAAAGACQAHAEADAEQAEADADAHQACAHAAAGQAAAHgCAGQgDAHgEAEIgKAGQgGACgHAAQgHAAgGgCgAEogXIgIAGIgEAHIgCAKIACALIAEAIIAIAEQADACAGAAQAHAAADgCIAHgEIAEgIQACgEAAgHQAAgHgCgDIgEgHIgHgGIgKgBgACXAgIAAgGIANAAIAAgqIABgFIgLAKIgCABIAAAAIgCgBIgBgBIgCgDIATgRIAHAAIAAA6IANAAIAAAGgABoAfIgIgGQgDgEgCgHIgCgOIACgPIAFgJIAIgHIAJgCIAKACIAHAHQAEAEABAFQACAHAAAIQAAAJgCAFQgBAGgEAFIgHAGQgDABgHAAQgGAAgDgBgABsgYIgFAEIgDAIIgCAMIACAMQABAGACACIAFAFIAFABIAGgBIAFgFQABgCACgGIABgMIgBgMIgDgIIgFgEIgGgBgAAmAgIAAgEIACgCIAZgaIAGgIIABgHIgBgEIgDgEIgEgBIgEgBIgEABIgEABIgCADIgDAGIgDAAIgFgBIADgIQABgDAEgCIAGgEIAHgBIAIABIAHAEIAEAFQABADAAAFIAAAHIgEAHIgEAEIgWAXIAIgCIAVAAIACABIABACIAAAFgAgHAgIAAgGIANAAIAAgvIgKAKIgBABIgCAAIgEgFIATgRIAHAAIAAA6IANAAIAAAGgAhbAgIAAgRIgeAAIgBgCIgBgEIAggpIAIAAIAAApIAJAAIAAAGIgJAAIAAARgAhyAJIAXAAIAAgggAifAfQgFgCgDgEQgEgFgBgGQgDgFAAgJQAAgIADgHQABgFAEgEIAIgHIAIgCIAKACQAFADACAEIAGAJIABAPIgBAOQgDAHgDAEQgBAEgGACQgDABgHAAQgGAAgCgBgAicgYIgFAEIgDAIIAAAYIADAIIAFAFIAFABIAGgBIAFgFQABgCACgGIACgMIgCgMIgDgIIgFgEIgGgBgAjbAgIAbg0IADgEIgiAAIgBAAIgBgCIAAgGIAtAAIAAAEIgBADIgbA2IgCADIgDAAgAkQAgIAbg0IADgEIghAAIgCAAIgBgCIAAgGIAtAAIAAAEIgBADIgbA2IgCADIgDAAgAlDAgIAAgdIgjAAIAAAdIgJAAIAAhAIAJAAIAAAdIAjAAIAAgdIAJAAIAABAgAmJAgIAAgdIgiAAIAAAdIgKAAIAAhAIAKAAIAAAdIAiAAIAAgdIAKAAIAABAgAnPAgIAAg1IgDAHIgdArIgFADIgHAAIAAhAIAJAAIAAA1IADgHIAggtIADgBIAGAAIAABAg");
	this.shape_3.setTransform(266.8,310.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AVGApIAAgQIgLgBIgHgFIgGgHIgBgKIABgIQADgFADgDIAHgFIALgCIAAgSIAIAAIAAASIAKACIAIAFQAEADABAFQACACAAAGQAAAHgCADIgFAHIgIAFIgKABIAAAQgAVOATIAHgCIAEgDIAEgFIABgHIgBgGIgEgGIgEgDIgHgBgAU6gKQgFAGAAAGQAAAHAFAFQAEAFAIAAIAAghQgGAAgGAEgAReApIAAgQIglAAIAAANIgBACIgBABIgGAAIAAgWIABAAIAEgBIADgCIACgEIADgHIACgZIAdAAIAAAmIAJAAIAAAUIgBADgARHgBIgFAPIgDAFIAWAAIAAghIgOAAgAIrApIAAgQIg/AAIAAgtIAIAAIAAAmIATAAIAAgmIAIAAIAAAmIATAAIAAgmIAJAAIAAAmIAHAAIAAAXgAFZApIAAgQIglAAIAAANIgBACIgBABIgGAAIAAgWIABAAIAEgBIADgCIACgEIADgHIACgZIAeAAIAAAmIAIAAIAAAUIAAADgAFCgBIgFAPIgCAFIAWAAIAAghIgOAAgABxApIAAg9IAFAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIABAFIAHgGIAJgCQAEAAADACIAGAEIADAIIAAASIgEAIQgEAEgCABQgDABgGAAIgIAAIgFgEIAAAUgAB/gMQgDABgDAEIAAAVIAFAEIAGABQAGAAAEgFQADgDAAgKIgBgGIgBgFQgBgBgBAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIgEgBQgFAAgCACgAyZApIAAgQIg0AAIAAANIgBACIgCABIgGAAIAAgYIAHAAIADgBIADgFIAEgRIADghIAnAAIAAA4IAKAAIAAAVIAAACIgCABgAy+ABIgCAKIgEAGIAgAAIAAgxIgWAAgATPAkIAAgBIACgDIABgCIABgCIACgDIgBAAIgDAAIgBgBIgBgFIABgDQAAgBABAAQAAAAAAAAQABgBABAAQAAAAABAAIADAAIACACIABACIAAAHIgDAEQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAIgEAEgAQKAkIgBAAIAAgBIACgDIABgCIABgCIABgDIgBAAIgDgBIgCgFIACgDQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAIAEAAIACACIABAFIgCAIQgCAEgCAAIgDAEgAABAkIAAAAIAAgBIABgDIACgCIACgCIABgDIgBAAIgDAAIgCgBIgBgFIABgDQABgBAAAAQAAAAABAAQAAgBABAAQABAAABAAIACAAIACACIABACIAAAHIgCAEIgHAIgAm7AkIgBAAIAAgBIABgCIACgBIACgEIABgDIgCAAIgCgBIgCgDIAAgCQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAABAAIACAAIACACIACAFIgDAIIgDAEIgDAEgASmAZIgHgEIgEgGIgCgIQAAgEADgFQAFgFAEgBIgIgGQgCgDAAgGIACgHIAEgFIAGgDQACgCAGAAQAGAAACACIAHADIADAFIACAHQAAAGgCADQgCADgGADQAEABAFAFQAEAFAAAEIgCAIIgFAGQgDADgEABIgJABgASlgCIgCADIAAAGIAAAFQAAAAAAABQAAAAABAAQAAABAAABQABAAAAABIAFACIAFABIAGgBIAEgCIADgEIABgFIgCgGIgCgDIgFgCIgJAAgASrghIgFADIgCAIIACAIIAEACIAFABIAGgBIADgCIACgEIAAgIIgCgEIgEgDIgFgBgAgmAZIgEgCIgDgEIgBgGIACgEQAAgDAEgCIAJgDIANgBIAAgDIgCgIQgDgDgEAAIgFAAIgFAEIgDAAIgCAAIAAgBIgCgDIAIgFQAEgCAGAAIAHABIAFAEIAEAGIABAjIgFAAIgBAAIgBgCIgBgEIgDADIgIADIgGABgAgbAFIgHACIgCACIgCAEIABADIABACIAFACIAHgCIAEgBIACgEIAAgIgAqIAYIgIgFIADgEQAAAAABAAQAAAAAAgBQAAAAABAAQAAAAABAAIACAAIAGADIAFABIAGgBQAEgBABgCIADgFIABgGIgBgEIgDgEIgEgDIgGgBIgLACIgFgCIAFgeIAfAAIAAADIgBADIgDACIgUAAIgEAQIAKgBIAIACIAHAEIAEAGIACAHIgCAKIgFAHIgIAFIgKABgAwbAXQgIgEgCgCIgGgLQgCgFAAgHQAAgIACgGQADgHAEgDQAEgFAGgDQAGgCAHAAQAHAAAGACIAJAGIgDAFIgBABIgCAAIgJgFIgHgBIgJACIgHAFIgFAHIgCAMQAAAFACAEIAFAIIAHAFQADABAGAAIAFAAIAEAAIAEgDQAAAAAAAAQABAAAAAAQABgBAAAAQABgBAAAAIABAAIABgBIAFAFQgEAFgGACQgIADgGAAQgIAAgFgDgAaLAZIAAgHIAPAAIAAguIgMAKIgCAAIAAAAIgFgEIAUgRIAIAAIAAA5IALAAIAAAHgAZcAYQgFgDgDgEQgDgEgBgGQgCgGgBgHQABgJACgHQABgFADgFIAIgGIAKgCIAJACQAFACADAEIAFAKIACAQIgCANQgCAHgDADQgCAEgGADQgDABgGAAQgHAAgDgBgAZggfIgFAEIgDAIIgBANIABALIADAIIAFAEIAGABIAFgBIAFgEQACgCABgGIACgLIgCgNIgDgIIgFgEIgFgCgAYnAYIgHgHQgEgEgBgGQgDgGAAgHQAAgJADgHQABgFAEgFIAHgGIAJgCIAKACIAIAGIAFAKIACAQIgCANQgCAHgDADQgBADgHAEQgDABgHAAQgFAAgEgBgAYrgfIgEAEIgEAIIgCANIACALQACAGACACIAEAEIAFABIAHgBIAEgEQABgCADgGIABgLIgBgNIgEgIIgEgEIgHgCgAXsAZIAAgHIAOAAIAAgqIABgEIgMAKIAAAAIgDAAIgDgEIATgRIAHAAIAAA5IANAAIAAAHgAW3AZQgFAAgDgBIgHgEIgEgIIgCgKIACgIIAEgIIAHgFIAJgCIAJACIAHAEIgDADIgBACIgEgDIgHgBIgGABIgEADIgDAGIgBAGIABAHIADAFIAEAEIAGABIAEgBIADgBIADgCIABgBIABABIADADIgEAEIgIADgAWQAZIAAgiIgCAFIgVAbIgCACIgCAAIgEAAIAAgtIAIAAIAAAhIACgDIAAgBIACgEIATgXIABgBIACgBIAFAAIAAAtgAUHAYIgIgFQgDgDgBgEQgCgDAAgHQAAgGACgDIAEgHIAIgFIAJgCIAJACIAHAFIAEAHQABADAAAGQAAAHgBADQgBAEgDADIgHAFQgCABgHAAQgHAAgCgBgAUGgKQgDAEgBAIQABAJADADQAEAFAGAAQAHAAACgFQAEgDAAgJQAAgIgEgEQgCgEgHAAQgGAAgEAEgARxAZIgDgBIAAgCIgBgCIABgDIAAgBIADgCIAFAAIABACIABABIABADIgBACIgBACIgBABgAP1AZIAAgiIgDAFIgUAbIgCACIgBAAIgGAAIAAgtIAJAAIAAAhIABgDIABgBIAVgbIACgBIABgBIAFAAIAAAtgAN8AZIAAgDIABgBIAAgDIAegdIADgFIABgGIgCgEQAAgBAAAAQAAAAgBgBQAAAAAAgBQgBAAgBgBIgDgCIgEgBIgIADIgDADIgCAEIgBACIgCAAIgGgBIADgIIAFgFIAGgEIAIgBIAIABIAGAEIAFAFIABAIIgEANIgaAbIAHgBIAVAAIACAAIABADIAAAFgANSAZIAAgiIgCAFIgDADIgSAYIgBACIgCAAIgFAAIAAgtIAIAAIAAAhIACgDIAAgBIADgEIASgXIACgBIACgBIAEAAIAAAtgAMeAZIAAgiIgDAFIgVAbIgBACIgCAAIgFAAIAAgtIAIAAIAAAhIACgDIABgBIAVgbIABgBIACgBIAGAAIAAAtgALxAZIgEAAIgLgRIgCgDIgEAAIgFAAIAAAUIgIAAIAAgtIAIAAIAAAUIAEAAIAEgBIACgCIAKgPIABgBIACgBIAHAAIgLASIgDACIgDABIAEACIADADIALATgAK1AZQgGAAgCgBIgHgEIgEgIIgCgKIACgIIADgIIAIgFIAJgCIAJACIAHAEIgDADIgCACIgDgDIgDgBIgFAAIgFABIgEADIgDAGIgBAGIACAHQgBAEADABIAEAEIAFABIAFgBIAEgBIABgCIABgBIADABIADADIgFAEIgJADgAKOAZIAAgVIgWAAIAAAVIgJAAIAAgtIAJAAIAAASIAWAAIAAgSIAJAAIAAAtgAJbAZIAAgiIgDAFIgVAbIgCACIgBAAIgGAAIAAgtIAJAAIAAAhIACgDIABgBIACgEIATgXIABgBIABgBIAGAAIAAAtgAHCAYQgEgBgDgEQgDgDgBgEQgBgDAAgHQAAgGABgDIAEgHQADgEAEgBIAJgCIAKACIAHAFIAEAHIABAJIgBAKQgBAEgDADIgHAFQgEABgGAAQgGAAgDgBgAHCgKQgDAEAAAIQAAAJADADQADAFAGAAQAIAAACgFQAEgDAAgJQAAgIgEgEQgCgEgIAAQgGAAgDAEgAGDAZIAAhAIATAAQAJAAACABIAIAEQADADACAEIABAIIgBAJIgFAGIgIAEQgEABgHAAIgKAAIAAAYgAGMgGIARAAIAEgEIAEgEIABgFIgBgGIgEgEIgEgCIgRgBgAEIAWIgEgEIACgDIACgBIADABIABACIAIACIAFgBIADgBIADgDIAAgDQgBgDgCgDQgDgBgGAAIgFAAIAAgFIAFAAQAGAAACgCQADgCABgDIgBgCIgCgCIgDgCIgFAAIgHABIgEADIgCgCIgCgDIAGgEQADgCAHAAIAHABIAFADIAEADIABAFIAAADIgCADIgDACIgDACIAHAEIACAHIgBAFIgFAFIgFADIgLAAgADrAZQgGAAgDgBIgHgFQgDgDgBgEQgBgDAAgIIABgIIAEgHIAGgFIAKgCQAFAAADACQAEABACADIAEAGIABAJIgBABIgBABIgeAAIABAHIACAGIAGADIAFABIAGgBIAIgEIABABIACADIgCADIgGADIgEABgADigLQgDAEAAAFIAXAAIgBgFIgBgEIgEgDIgFAAQgGAAgDADgACuAYIgHgFQgDgDgBgEQgCgDABgHQgBgGACgDIAEgHIAHgFIAKgCIAJACQADABAEAEIAEAHQABADABAGQgBAHgBADQgBAEgDADQgEAEgDABQgDABgGAAQgGAAgEgBgACtgKQgCAEAAAIQAAAJACADQAFAFAGAAQAGAAADgFQAEgDAAgJQAAgIgEgEQgDgEgGAAQgGAAgFAEgABZAZIAAg5IggAAIAAA5IgKAAIAAhAIA0AAIAABAgAhZAZIAAgtIAZABIAGACIACADIABAFIAAADIgBADIgDADIgFABQAHABABADQADACAAAFIgBAFIgEAEIgGAEIgGAAgAhQATIAKAAQAEAAADgCQADgBgBgFIAAgCIgCgDIgCgBIgPAAgAhQAAIAJAAIAHgCIABgDIABgDIgBgCIgBgCIgDgCIgEAAIgJAAgAhlAZIgFAAIgKgRIgDgDIgDAAIgFAAIAAAUIgJAAIAAgtIAJAAIAAAUIAEAAIADgBIADgCIAJgPIACgBIACgBIAHAAIgLASIgDACIgDABIAEACIAOAWgAihAZQgGAAgDgBIgGgEIgEgIIgCgKIACgIIADgIIAHgFIAKgCIAJACIAHAEIgDADIgCACIgDgDIgDgBIgFAAIgGABIgEADIgCAGIgBAGIABAHIACAFIAEAEIAGABIAFgBIADgBIADgDIACABIADADIgEAEIgJADgAjdAYQgFgBgCgEIgFgHIgBgKIABgJIAFgHQACgEAFgBIAJgCIAKACIAHAFIAEAHIACAJIgCAKQgBAEgDADIgHAFQgEABgGAAQgGAAgDgBgAjegKQgCAEAAAIQAAAJACADQADAFAHAAQAHAAADgFQAEgFAAgHQAAgFgEgHQgDgEgHAAQgHAAgDAEgAj+AZIAAgwIABgDIgXAnIgCACIgBABIgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgWgnIAAAzIgIAAIAAhAIAJAAIABABIAYArIAYgrIACgBIAJAAIAABAgAlnAZIgBgBIgBgCIgBgCIABgDIABgBIABgCIAFAAIACACIABABIABADIgBACIgBACIgCABgAmPAZIAAgtIAfAAIAAAGIgWAAIAAAngAnqAZIAXgeIgGADIgGABIgGgBIgHgEIgEgFIgBgIIABgIIAFgHQADgEAEAAIAJgCIAIACIAHAEIAEAHIACAIIgBAFIgEALIgSAaIgDACIgCAAgAnhggIgDACIgEAFIAAAFQAAAFADAFQADADAGAAIAGgBIAEgDQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIABgFIgBgGIgCgEIgEgCIgGgBgAofAZIAAgHIAOAAIAAguIgLAKIgCAAIgBAAIgEgEIATgRIAHAAIAAA5IANAAIAAAHgAo+AZIAAgRIgeAAIgBgCIgBgFIAfgoIAIAAIAAAoIAKAAIAAAHIgKAAIAAARgApWABIAYAAIAAgfgAq+AZIAAgHIAOAAIAAguIgLAKIgCAAIAAAAIgCAAIgBgBIgCgDIAUgRIAGAAIAAA5IANAAIAAAHgArzAZIAAgHIANAAIAAgqIACgEIgNAKIgBAAIgBAAIgEgEIATgRIAHAAIAAA5IANAAIAAAHgAtKAZIgDgDIAAgFIADgDIAFAAIADADIAAAFIgDADgAt8AZIAAhAIAoAAIAAAHIgeAAIAAA5gAuRAZIgDgDIgBgCIABgDIADgDIAFAAIADADIAAAFIgDADgAurAZIAAgcIgiAAIAAAcIgKAAIAAhAIAKAAIAAAdIAiAAIAAgdIAKAAIAABAgAvsAZIgCgBIgBgCIgBgCIABgDIABgBIACgCIAFAAIABACIABABIABADIgBACIgBACIgBABgAxaAZIAAgxIAAgEIgBAEIggAuIgCACIgCABIgHAAIAAhAIAJAAIAAAwIgBAFIAFgHIAfgtIACgBIAHAAIAABAgAzoAZIAAgcIgiAAIAAAcIgKAAIAAhAIAKAAIAAAdIAiAAIAAgdIAKAAIAABAgA0jAZIgDAAIgGgRIgeAAIgFAPIgBACIgCAAIgHAAIAZhAIAKAAIAaBAgA08gYIgLAZIAYAAIgMgfgA1jAZIgDAAIgUgcIgEgBIgHAAIAAAdIgKAAIAAhAIAKAAIAAAcIAJAAIADgDIARgXIACgBIACgBIAIAAIgUAaQAAADgFACIADACIAYAfgA4IAXIgKgGIgHgLQgCgGAAgGQAAgIACgGIAHgKQAEgFAGgDQAGgCAIAAQAHAAAFACQAGADAFAFIAGAKQADAGAAAIQAAAGgDAGIgGALIgLAGQgFACgHAAQgIAAgGgCgA4EgeQgEACgDADQgDADgCAEIgCAMIACAJQABAEAEAEQADAEAEABQACABAIAAQAGAAADgBQAEgBADgEQAEgEAAgEIACgJIgCgMQgBgEgDgDQgCgDgFgCIgJgCgA5RAXIgKgGQgEgEgDgHQgCgGAAgGQAAgIACgGQAEgIADgCQADgEAHgEQAHgCAGAAQAIAAAGACQAFADAFAFIAGAKQADAGAAAIQAAAGgDAGIgGALIgKAGQgGACgIAAQgGAAgHgCgA5NgeIgHAFIgFAHQgBAEAAAIQAAAGABADIAFAIIAHAFQADABAGAAQAHAAADgBIAHgFIAFgIIABgJIgBgMIgFgHIgHgFIgKgCgA6aAXQgGgCgEgEQgEgFgDgGQgDgGABgGQgBgIADgGQADgHAEgDQAEgFAGgDQAGgCAIAAQAGAAAGACQAIAEACAEQAEACADAIQADAGgBAIQABAGgDAGQgDAHgEAEIgKAGQgGACgGAAQgIAAgGgCgA6WgeIgHAFIgFAHIgCAMIACAJIAFAIIAHAFQADABAHAAQAGAAADgBIAHgFIAEgIQACgDAAgGQAAgIgCgEIgEgHIgHgFIgJgCgAsoASIgBgBIAAgDIAHgMIACgBIgBAAIgBgBIgHgLIAAgDIABgBIACgCIAMASIAAAAIgMASgAs2ASIgBgBIAAgDIAHgMIACgBIgBAAIgIgMIAAgDIABgBIADgCIALASIAAAAIgLASgA2tABIAAAAIAMgSIADACIAAABIAAADIgHALIgBABIABABIAHAMIAAADIAAABIgDABgA26ABIAAAAIALgSIADACIABABIAAADIgHALIgCABIACABIAHAMIAAADIgBABIgDABgAOyABIAAgGIAYAAIAAAGgAPkgbIgEgDQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIgCgEIABgBIABgBIAFAAIAAADIACACIACACIACABIAEgBIACgCIACgFIAFAAIABABIAAABIAAAEIgDADIgFADIgGABgANCgbIgFgDIgCgDIgBgEIABgBIAAgBIAGAAIAAADIADAEIADABIAEgBIACgCIABgCIAAgDIAFAAIABABIABABIgBAEIgDADIgEADIgGABg");
	this.shape_4.setTransform(302.4,300.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(305));

	// know
	this.instance_6 = new lib.know();
	this.instance_6.parent = this;
	this.instance_6.setTransform(367.9,257.7,1.28,1.28,0,0,0,0.1,0.1);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(237).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(53).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// p4
	this.instance_7 = new lib.p4();
	this.instance_7.parent = this;
	this.instance_7.setTransform(121.4,55.5,0.8,0.8);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(225).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// p1
	this.instance_8 = new lib.p1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(121.4,95.1,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(305));

	// fg
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2291CB").s().p("A3fEMIAAoXMAu/AAAIAAIXg");
	this.shape_5.setTransform(240.7,42.9,1.6,1.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(305));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(239.5,144,649.9,349.9);
// library properties:
lib.properties = {
	id: 'EB27A67236891744958EFB8121C8AB00',
	width: 480,
	height: 320,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/480x320_atlas_P_.png", id:"480x320_atlas_P_"},
		{src:"images/480x320_atlas_NP_.jpg", id:"480x320_atlas_NP_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EB27A67236891744958EFB8121C8AB00'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;