(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"468x60_atlas_NP_", frames: [[0,0,500,393],[502,0,368,500],[0,502,800,90]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib._1a = function() {
	this.spriteSheet = ss["468x60_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["468x60_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._4a = function() {
	this.spriteSheet = ss["468x60_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.p3a = function() {
	this.initialize(img.p3a);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,146,221);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Path_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyRCbIAAk1MAkjAAAIAAE1g");
	this.shape.setTransform(117,15.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_1, new cjs.Rectangle(0,0,234,31), null);


(lib.t3b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AG9CTIAAg1IidAAIAAjuIAvAAIAADFIBRAAIAAjFIAuAAIAADFIAcAAIAABegAOEBaQgQgHgNgNQgJgKgFgMQgGgLgBgOQgCgNgBgPIgjAAIAABjIgvAAIAAjuIAvAAIAABhIAkAAQAAgRADgNQACgNAFgLQAFgKAIgJQANgNAQgHQARgGATAAQATAAARAGQAQAHANANQANANAFATQAGASgBAYIAAAZQABAUgCAPQgBAQgFAOQgFAOgLAMQgNANgQAHQgQAGgUAAQgTAAgRgGgAOXhlQgIADgFAGQgHAIgCAPQgDAPAAAWIAAAPIABAcQABALADAHQADAIAEAEQAGAHAHADQAIADAJAAQAJAAAIgDQAIgDAFgHQAIgIACgOQACgOAAgYIAAgOQAAgXgDgOQgCgOgHgIQgFgGgIgDQgIgEgJAAQgJAAgIAEgAr8BZQgQgGgNgNQgLgMgFgPQgFgPgBgPQgCgOABgOIAAgTQAAgYACgPQACgQAFgLQAFgLAJgJQANgNAQgHQARgGATAAQATAAARAGQAQAHANANQAMAMAGATQAGATAAAdIAAAZIgBAeQgCAQgFAOQgFAOgLAMQgNANgQAHQgQAGgUAAQgTAAgRgHgArphlQgHADgGAGQgIAJgCAQQgCARAAAWIAAAMQAAASACAQQACAPAIAJQAGAGAHADQAIADAJAAQAJAAAIgDQAIgDAFgGQAFgFACgIQADgHABgOIABglIgBgfQgBgMgDgIQgCgHgFgFQgFgGgIgDQgIgEgJAAQgJAAgIAEgAKWBeIAAiZIhdCZIgqAAIAAjuIAvAAIAACYIBdiYIAqAAIAADugADMBeIhUh8IAAB8IgvAAIAAjuIAvAAIAABxIBNhxIA4AAIhRBwIBZB+gAiCBeIAAjuICdAAIAAApIhuAAIAAA5IBdAAIAAApIhdAAIAAA6IBuAAIAAApgAjpBeIAAjFIg5AAIAABGQAAAlgFAZQgEAZgKAOQgJAOgOAGQgOAGgSAAIgTAAIAAgpIAHAAQAJAAAHgEQAIgDAFgKQAGgJADgSQADgRAAgcIAAhsICVAAIAADugAnQBeIAAjFIg5AAIAABGQAAAlgFAZQgEAZgKAOQgJAOgOAGQgOAGgSAAIgTAAIAAgpIAHAAQAJAAAHgEQAIgDAFgKQAGgJADgSQADgRAAgcIAAhsICVAAIAADugAt8BeIhUh8IAAB8IgvAAIAAjuIAvAAIAABxIBNhxIA4AAIhRBwIBZB+g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3b, new cjs.Rectangle(-102.4,-14.7,204.9,29.5), null);


(lib.t3a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AOmBLQgKgFgJgIQgGgHgDgHQgEgIgBgIQgBgJAAgKIgYAAIAABBIgeAAIAAibIAeAAIAAA/IAYAAQAAgLACgIQABgJADgHQAEgGAFgGQAIgJALgEQALgEAMAAQANAAALAEQAKAEAJAJQAIAIAEAMQADAMAAAQIAAAPQAAANgBALQAAAKgEAJQgDAJgHAIQgJAIgKAFQgLAEgMAAQgNAAgLgEgAOygxQgFACgDAEQgFAFgBAKQgCAKAAAOIAAAJIABATIACAMIAFAHQAEAEAFADQAFACAFAAQAGAAAFgCQAFgDAEgEQAFgFABgJQACgKAAgQIAAgIQAAgPgCgJQgCgJgEgFQgEgEgFgCQgFgCgGAAQgGAAgFACgAhdBLQgLgFgIgIQgHgIgEgKQgDgJgBgKIAAgTIAAgMIABgZQABgKAEgHQADgHAGgGQAIgJALgEQALgEAMAAQANAAAKAEQALAEAIAJQAIAIAEAMQAEAMAAATIAAAPIgBAVQgBAKgDAJQgDAJgIAIQgIAIgKAFQgLAEgNAAQgMAAgLgEgAhRgxQgFACgDAEQgFAGgCAKQgBALAAAPIAAAGQAAANABAKQABAKAGAGIAIAGQAFACAGAAQAGAAAFgCQAFgCAEgEQADgEABgFQACgFABgIIAAgYIAAgVQgBgHgCgFQgBgFgDgDQgEgEgFgCQgFgCgGAAQgGAAgFACgAoKBLQgKgFgIgIQgIgIgDgKQgDgJgBgKIgBgTIAAgMIABgZQACgKADgHQAEgHAGgGQAIgJAKgEQALgEANAAQAMAAALAEQALAEAIAJQAIAIAEAMQADAMAAATIAAAPIAAAVQgBAKgDAJQgEAJgHAIQgIAIgLAFQgLAEgMAAQgNAAgLgEgAn9gxQgFACgEAEQgFAGgBAKQgCALABAPIAAAGQgBANACAKQABAKAFAGIAJAGQAFACAGAAQAGAAAFgCQAFgCADgEQADgEACgFQACgFAAgIIABgYIgBgVQAAgHgCgFQgCgFgDgDQgDgEgFgCQgFgCgGAAQgGAAgFACgALPBOIAAgbIAMAAQAGAAAEgDQAEgCACgFIAFgLIgyhrIAfAAIAhBLIAehLIAfAAIg3CAQgDAIgFAFQgEAGgHAEQgHAEgJAAgAKMBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAIDBOIg0hRIAABRIgeAAIAAhRIg0BRIglAAIA4hSIgzhJIAkAAIAwBKIAAhKIAeAAIAABKIAwhKIAkAAIgzBJIA4BSgAEpBOIAAibIAeAAIAACbgACoBOIAAibIAeAAIAAA7IAfAAQAQAAALAGQALAGAGAKQAHALAAAOQAAAPgHAKQgGALgLAGQgMAHgPAAgADGAzIAdAAQAKgBAGgFQAGgGAAgKQAAgKgGgFQgGgGgKAAIgdAAgABlBOIAAiAIglAAIAAAtQAAAYgDAQQgDAQgGAKQgGAJgJAEQgJAEgMAAIgNAAIAAgbIAFAAQAGAAAFgDQAEgCAEgGQAEgGACgMQACgLAAgRIAAhHIBhAAIAACbgAi9BOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAmaBOIAAibIA9AAQAPAAAMAGQALAGAHALQAGALAAAOQAAAPgGALQgHAKgLAGQgMAGgPAAIgeAAIAAA7gAl7gHIAcAAQALAAAGgGQAGgGAAgKQAAgJgGgGQgGgGgLAAIgcAAgAqhBOIAAibIBiAAIAAAbIhDAAIAACAgAsHBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgAsZAYIgTg3IgTA3IAmAAgAujBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3a, new cjs.Rectangle(-101.5,-7.9,203,15.9), null);


(lib.t2c = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D7ABD").s().p("ALbFpQgigRgVggQgUgfgBgvIAAhnQABgvAUggQAVgfAigRQAhgOAqgBQAqABAhAOQAiARAVAfQAVAgAAAvIAABnQAAAvgVAfQgVAggiARQghAPgqAAQgqAAghgPgAL/BbQgOAOAAAfIAABeQAAAeAOAOQAOAPAZAAQAZAAAOgPQAOgOAAgeIAAheQAAgfgOgOQgOgPgZAAQgZAAgOAPgAkJFeQgygYgfgyQgegxgChHIAAk3QAChHAegwQAfgyAygZQA0gaA9AAQA9AAAzAaQAxAZAfAyQAfAwAABHIAAE3QAABHgfAxQgfAygxAYQgzAag9AAQg9AAg0gagAjZjjQgZAbgBAvIAAE0QABAvAZAaQAZAaAoABQAogBAZgaQAYgaAAgvIAAk0QAAgvgYgbQgZgagogBQgoABgZAagAtCFiQg1gWgigwQghgxgChNICHAAQADAyAdAXQAdAYAoAAQAsgBAcgaQAcgaAAgyQAAgvgbgbQgbgbgygBIgUAAIAAh1IAUAAQAwAAAYgbQAWgaAAgnQgBgugagYQgagZgmAAQgnABgZAXQgZAYgDAqIiHAAQAChCAfgwQAeguAzgaQAygZA/AAQBCAAAzAbQAzAbAcAvQAdAwAAA/QAAA8gXAkQgYAlglASQApAVAaAoQAbAoABBDQgBBKgfAwQggAyg2AYQg0AYhBAAQg9AAg1gWgAFXFzIFerkIBqAAIlfLkgAECgEQgigQgVgfQgTgggBgvIAAhnQABgvATgfQAVghAigPQAigQArAAQAoAAAjAQQAiAPAUAhQAUAfABAvIAABnQgBAvgUAgQgUAfgiAQQgjAQgoAAQgrAAgigQgAEmkRQgNAPAAAdIAABfQAAAdAOAPQAOAPAaAAQAYAAAOgPQAOgPAAgdIAAhfQAAgdgOgPQgOgPgYAAQgbAAgOAPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2c, new cjs.Rectangle(-95.7,-37.6,191.4,75.3), null);


(lib.t2b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ADyDRIAAhMIi8AAIAABMIg/AAIAAiHIAfAAQAOgWAJgeQAJgdAEgkQAEgkAAgnIAAhXIDNAAIAAEXIAnAAIAACHgAB+hhQAAAzgGArQgHAqgRAjIBpAAIAAjcIhLAAgAtSB+QgXgJgSgSQgRgRgHgUQgHgVgBgYQgCgXAAgdQAAgeACgYQABgYAHgUQAHgVARgRQASgRAXgKQAWgKAcAAQAgAAAaAMQAaAMASAYQARAYAGAjIhDAAQgFgUgOgOQgNgNgZgBQgOAAgLAFQgKAFgIAIQgGAHgEAKQgDAKgCASQgBATAAAgQAAAgABARQACATADAKQAEAKAGAGQAIAJAKAEQALAFAOAAQAZgBANgNQAOgNAFgVIBDAAQgGAjgRAYQgSAYgaAMQgaAMggAAQgcAAgWgKgANZCFIgUg8Ih5AAIgUA8IhFAAIB7lSIA0AAIB8FSgAMzARIgph6IgrB6IBUAAgAIhCFIh3iwIAACwIhCAAIAAlSIBCAAIAAChIBuihIBPAAIhyCfIB9CzgAh6CFIAAjZIiEDZIg7AAIAAlSIBDAAIAADYICEjYIA7AAIAAFSgAmvCFIh3iwIAACwIhDAAIAAlSIBDAAIAAChIBtihIBPAAIhyCfIB+Czg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2b, new cjs.Rectangle(-92.5,-20.8,185.1,41.8), null);


(lib.t2a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("ApRBLQgKgFgIgIQgIgIgDgJQgEgJAAgMIgBgYIABgYQAAgLAEgJQADgKAIgHQAIgJAKgEQALgEANAAQAOAAAMAFQAMAGAIALQAIAKADARIgfAAQgCgKgGgGQgHgGgLAAQgGAAgFACQgFACgEAEQgDADgBAEIgDANIAAAXIAAAXIADANQABAFADADQAEAEAFACQAFACAGAAQALAAAHgHQAGgGACgJIAfAAQgDAQgIALQgIALgMAFQgMAGgOAAQgNAAgLgEgAttBJQgLgFgIgLQgIgLgDgQIAeAAQACAKAHAGQAGAGAMABQAGAAAFgDQAFgCAEgEIAEgGQACgEAAgGIACgPIgxAAIAAgaIAwAAIgBgPIgCgJIgEgGQgEgEgFgDQgFgCgGAAQgLAAgHAGQgHAHgCAJIgeAAQADgQAHgLQAIgKAMgGQAMgFAPAAQANAAAKAEQALAEAIAJQAIAHADAKQADAJABALQABALgBANQABANgBALQgBAMgDAJQgDAJgIAIQgIAIgLAFQgKAEgNAAQgPAAgMgGgANuBOIAAg7IgZAAIgaA7IgkAAIAghBQgMgGgHgKQgHgLAAgPQAAgOAGgLQAHgLALgGQAMgGAPAAIA8AAIAACbgANBgtQgGAGAAAKQAAAKAGAGQAGAGAKAAIAdAAIAAgrIgdAAQgKAAgGAFgALwBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgALeAYIgTg3IgTA3IAmAAgAJUBOIAAhBIg1AAIAABBIgeAAIAAibIAeAAIAABAIA1AAIAAhAIAfAAIAACbgAF3BOIAAibIAfAAIAAA7IAfAAQAPAAALAGQAMAGAGAKQAGALAAAOQAAAPgGAKQgGALgMAGQgLAHgPAAgAGWAzIAcAAQALgBAGgFQAGgGAAgKQAAgKgGgFQgGgGgLAAIgcAAgAE1BOIAAiAIgmAAIAAAtQAAAYgDAQQgDAQgGAKQgGAJgJAEQgJAEgMAAIgMAAIAAgbIAEAAQAGAAAFgDQAFgCAEgGQADgGACgMQACgLAAgRIAAhHIBhAAIAACbgACvBOIgKgcIg3AAIgJAcIggAAIA5ibIAXAAIA5CbgACdAYIgTg3IgTA3IAmAAgAATBOIAAhaIgdA6IgUAAIgeg6IAABaIgfAAIAAibIAeAAIApBTIAohTIAeAAIAACbgAjfBOIAAibIBnAAIAAAbIhJAAIAAAlIA+AAIAAAaIg+AAIAAAmIBJAAIAAAbgAlpBOIAAibIA9AAQAPAAAMAGQALAGAHALQAGALAAAOQAAAPgGALQgHAKgLAGQgMAGgPAAIgeAAIAAA7gAlKgHIAcAAQALAAAGgGQAGgGAAgKQAAgJgGgGQgGgGgLAAIgcAAgAnIBOIAAiAIgpAAIAAgbIBwAAIAAAbIgpAAIAACAgAqkBOIg3hRIAABRIgeAAIAAibIAeAAIAABKIAzhKIAkAAIg0BJIA5BSg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2a, new cjs.Rectangle(-90.8,-7.9,181.6,15.9), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1E1C").s().p("AAiBEIgGgQIg3AAIgGAQIg5AAIA6iHIBBAAIA6CHgAAQATIgQgtIAAAAIgPAtIAfAAg");
	this.shape.setTransform(77.4,-1.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1D1E1C").s().p("AgaBEIAAhlIgyAAIAAgiICZAAIAAAiIgyAAIAABlg");
	this.shape_1.setTransform(52.4,-1.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1D1E1C").s().p("AAeBEIAAg2Ig7AAIAAA2Ig2AAIAAiHIA2AAIAAAvIA7AAIAAgvIA2AAIAACHg");
	this.shape_2.setTransform(25.5,-1.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1D1E1C").s().p("Ag9A7QgUgNAAggIAAhTIA2AAIAABRQAAAXAbAAQAcAAAAgXIAAhRIA2AAIAABTQAAAggUANQgTAMgrgBQgqABgTgMg");
	this.shape_3.setTransform(-3,-1.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1D1E1C").s().p("AhEBEIAAiHIA2AAIAABiIBTAAIAAAlg");
	this.shape_4.setTransform(-28.7,-1.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhNBBIAkhjQAEgLAMgJQANgLALABIgkBoIBzAAQgCAIgKAIQgNAJgRAAg");
	this.shape_5.setTransform(-67,-1.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0D7ABD").s().p("AiGCGQg3g3AAhPQAAhOA3g4QA4g3BOAAQBPAAA4A3QA3A4AABOQAABPg3A3Qg4A4hPAAQhOAAg4g4g");
	this.shape_6.setTransform(-67.4,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAiBEIgGgQIg3AAIgGAQIg5AAIA6iHIBBAAIA6CHgAAQATIgQgtIAAAAIgPAtIAfAAg");
	this.shape_7.setTransform(77.4,-1.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgaBEIAAhlIgyAAIAAgiICZAAIAAAiIgyAAIAABlg");
	this.shape_8.setTransform(52.4,-1.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAeBEIAAg2Ig7AAIAAA2Ig2AAIAAiHIA2AAIAAAvIA7AAIAAgvIA2AAIAACHg");
	this.shape_9.setTransform(25.5,-1.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag9A7QgUgNAAggIAAhTIA2AAIAABRQAAAXAbAAQAcAAAAgXIAAhRIA2AAIAABTQAAAggUANQgTAMgrgBQgqABgTgMg");
	this.shape_10.setTransform(-3,-1.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhEBEIAAiHIA2AAIAABiIBTAAIAAAlg");
	this.shape_11.setTransform(-28.7,-1.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiGCGQg3g3AAhPQAAhOA3g4QA4g3BOAAQBPAAA4A3QA3A4AABOQAABPg3A3Qg4A4hPAAQhOAAg4g4gAgVhCQgLAJgEALIgkBjIBxAAQARAAANgJQAKgIABgIIhyAAIAjhoIgCAAQgKAAgMAKg");
	this.shape_12.setTransform(-67.4,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-86.4,-19,173,38.1), null);


(lib.hn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1a();
	this.instance.parent = this;
	this.instance.setTransform(-250,-255);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.hn, new cjs.Rectangle(-250,-255,500,393), null);


(lib.fg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.p3a();
	this.instance.parent = this;
	this.instance.setTransform(-73,-110.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fg, new cjs.Rectangle(-73,-110.5,146,221), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#ECF4F4","#B3CEE4"],[0,0.984],0,-157.1,0,166.1).s().p("AzhfeMAAAg+7MAnDAAAMAAAA+7g");
	this.shape.setTransform(120,200,0.96,0.993);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(0,0,240,400), null);


(lib.bbb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._4a();
	this.instance.parent = this;
	this.instance.setTransform(-221,231);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bbb, new cjs.Rectangle(-221,231,800,90), null);


(lib.aaa = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._2();
	this.instance.parent = this;
	this.instance.setTransform(882.6,-309,1.2,1.2,0,0,180);

	this.instance_1 = new lib._2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(1,-309,1.2,1.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.aaa, new cjs.Rectangle(1,-309,881.6,600), null);


(lib.s4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bbb();
	this.instance.parent = this;
	this.instance.setTransform(168.5,159,1,1,0,0,0,267.5,250);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:98.5},99).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-320,140,800,90);


(lib.s3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.fg();
	this.instance.parent = this;
	this.instance.setTransform(73,110.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-49.5},75).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,146,221);


(lib.s2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.aaa();
	this.instance.parent = this;
	this.instance.setTransform(184,190,1,1,0,0,0,184,250);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:64},100).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,-369,881.6,600);


(lib.s1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.hn();
	this.instance.parent = this;
	this.instance.setTransform(240,253);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-35},79).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,-2,500,393);


(lib.legal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EAmcAAvIAAhGIAHAAIAAAFIADgCIADgCIADgCIAEAAQAKAAAEAGQAFAHAAALQAAAOgFAFQgEAHgJAAIgFgBIgDgBIgDgBIgDgEIAAAcgEAmmgANQgDAEAAAJQAAAKADAFQADAEAGAAQAHAAADgEQADgFAAgKQAAgJgDgEQgDgEgHgBQgGABgDAEgEAgSAAvIAAhGIAHAAIAAAFIADgCIADgCIAEgCIAEAAQAJAAAFAGQAEAHAAALQAAAOgEAFQgFAHgJAAIgEgBIgEgBIgDgBIgDgEIAAAcgEAgcgANQgDAEAAAJQAAAKADAFQADAEAHAAQAGAAADgEQADgFAAgKQAAgJgDgEQgDgEgGgBQgHABgDAEgAV5AvIAAhGIAHAAIAAAFIADgCIADgCIAEgCIAEAAQAJAAAFAGQAEAHAAALQAAAOgEAFQgFAHgJAAIgEgBIgEgBIgDgBIgDgEIAAAcgAWDgNQgDAEAAAJQAAAKADAFQADAEAHAAQAGAAADgEQADgFAAgKQAAgJgDgEQgDgEgGgBQgHABgDAEgARRAvIAAhGIAHAAIAAAFIADgCIADgCIADgCIAEAAQAKAAAEAGQAFAHAAALQAAAOgFAFQgEAHgJAAIgFgBIgDgBIgDgBIgDgEIAAAcgARbgNQgDAEAAAJQAAAKADAFQADAEAGAAQAHAAADgEQADgFAAgKQAAgJgDgEQgDgEgHgBQgGABgDAEgADAAvIAAhGIAHAAIAAAFIADgCIADgCIADgCIAEAAQAKAAAEAGQAFAHAAALQAAAOgFAFQgEAHgJAAIgFgBIgDgBIgDgBIgDgEIAAAcgADKgNQgDAEAAAJQAAAKADAFQADAEAGAAQAHAAADgEQADgFAAgKQAAgJgDgEQgDgEgHgBQgGABgDAEgABqAvIAAgVQgMgBgGgHQgHgFAAgNQAAgLAHgGQAGgGAMgBIAAgVIAHAAIAAAVQAMABAHAGQAGAGAAALQAAANgGAFQgHAHgMABIAAAVgABxATQAJAAAFgFQAEgFAAgJQAAgEgCgEQgCgEgDgDQgEgCgHgBgABggPQgEADgCAEQgCAEAAAEQAAAJAFAFQAEAFAJAAIAAglQgGABgEACgAk3AvIAAhGIAHAAIAAAFIADgCIADgCIAEgCIAEAAQAJAAAFAGQAEAHAAALQAAAOgEAFQgFAHgJAAIgEgBIgEgBIgDgBIgDgEIAAAcgAktgNQgDAEAAAJQAAAKADAFQADAEAHAAQAGAAADgEQADgFAAgKQAAgJgDgEQgDgEgGgBQgHABgDAEgAtQAvIAAhGIAHAAIAAAFIADgCIADgCIADgCIAEAAQAKAAAEAGQAFAHAAALQAAAOgFAFQgEAHgJAAIgFgBIgDgBIgDgBIgDgEIAAAcgAtGgNQgDAEAAAJQAAAKADAFQADAEAGAAQAHAAADgEQADgFAAgKQAAgJgDgEQgDgEgHgBQgGABgDAEgA1TAvIAAhGIAHAAIAAAFIADgCIADgCIAEgCIAEAAQAJAAAFAGQAEAHAAALQAAAOgEAFQgFAHgJAAIgEgBIgEgBIgDgBIgDgEIAAAcgA1JgNQgDAEAAAJQAAAKADAFQADAEAHAAQAGAAADgEQADgFAAgKQAAgJgDgEQgDgEgGgBQgHABgDAEgEglxAAvIAAhGIAHAAIAAAFIADgCIADgCIAEgCIAEAAQAJAAAFAGQAEAHAAALQAAAOgEAFQgFAHgJAAIgEgBIgEgBIgDgBIgDgEIAAAcgEglngANQgDAEAAAJQAAAKADAFQADAEAHAAQAGAAADgEQADgFAAgKQAAgJgDgEQgDgEgGgBQgHABgDAEgEgpuAAvIAAhGIAHAAIAAAFIADgCIADgCIADgCIAEAAQAKAAAEAGQAFAHAAALQAAAOgFAFQgEAHgJAAIgFgBIgDgBIgDgBIgDgEIAAAcgEgpkgANQgDAEAAAJQAAAKADAFQADAEAGAAQAHAAADgEQADgFAAgKQAAgJgDgEQgDgEgHgBQgGABgDAEgAJlAuIAAgGIACAAQAEAAACgCIADgEIADgKIgSgvIAIAAIAOAnIANgnIAIAAIgXA8QgBAEgDADQgEACgFAAgAZXAoIAAgPIglAAIAAAPIgGAAIAAgVIAFAAIAEgJIACgKIABgOIAAgJIAfAAIAAAqIAHAAIAAAVgAY/gIIgBAKIgCAJIgDAIIAXAAIAAgkIgRAAgATSAoIAAgPIglAAIAAAPIgHAAIAAgVIAGAAIADgJIACgKIABgOIAAgJIAfAAIAAAqIAHAAIAAAVgAS5gIIgBAKIgBAJIgDAIIAWAAIAAgkIgRAAgAPNAQIAJAAIAAAQIgJAIgAF9AoIAAgPIgmAAIAAgwIAHAAIAAAqIAYAAIAAgqIAHAAIAAAqIAHAAIAAAVgAlDAoIAAgPIglAAIAAAPIgGAAIAAgVIAFAAIAEgJIACgKIABgOIAAgJIAfAAIAAAqIAHAAIAAAVgAlbgIIgBAKIgCAJIgDAIIAXAAIAAgkIgRAAgAwQAoIAAgPIglAAIAAAPIgHAAIAAgVIAGAAIADgJIACgKIABgOIAAgJIAfAAIAAAqIAHAAIAAAVgAwpgIIgBAKIgBAJIgDAIIAWAAIAAgkIgRAAgA84AoIAAgPIgnAAIAAgwIAHAAIAAAqIAYAAIAAgqIAHAAIAAAqIAIAAIAAAVgEgiTAAoIAAgPIglAAIAAAPIgGAAIAAgVIAFAAIAEgJIACgKIABgOIAAgJIAfAAIAAAqIAHAAIAAAVgEgirgAIIgBAKIgCAJIgDAIIAXAAIAAgkIgRAAgEgs5AAoIAAgPIgmAAIAAgwIAHAAIAAAqIAYAAIAAgqIAHAAIAAAqIAHAAIAAAVgEAuRAAZQgEgCgCgCIgDgFIgBgFQAAgHAFgDQAEgDAIAAIAPAAIAAgFQAAgFgDgDQgDgCgGgBIgIABQgDACgCADIgFgFQAEgEAEgBQAEgCAGAAQAKABAEAEQAFAEAAAHIAAAhIgHAAIAAgFIgGAFIgIABIgIgBgEAuRAAFQgDACAAAEQAAAEADACQADACAGAAIAGAAQACAAADgDIACgDIAAgFIAAgGIgOAAQgFABgDACgEAsZAAZIgFgEIgEgGIgBgIIAAgeIAHAAIAAAdQAAAHADADQADADAGAAQAGAAADgDQADgDAAgHIAAgdIAHAAIAAAwIgHAAIAAgGQgCAEgEABQgDABgFABIgHgBgEAnOAATQgFgHAAgMQAAgLAFgGQAFgHAKAAQAJABAGAFQAFAHAAALIAAACIghAAIAAAGIABADQACAEADACQAEACAFAAIADAAIADgBIADgCIADgCIAFAEIgEAEIgEACIgFABIgFABQgKgBgGgGgEAnqgACIgBgEIAAgDQgBgEgEgDQgDgCgEAAQgEAAgDACQgDACgCAEIgBADIAAAFIAaAAIAAAAgEAl4AAYIgGgEQgDgDgCgFQgBgEAAgIQAAgFABgFQACgFADgDQACgDAEgBIAIgCIAIACQADABADADQADADABAFQACAEAAAGQAAAIgCAEQgBAFgDADIgGAEIgIACIgIgCgEAl7gARIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgEAkrAAaQgIgBgFgDQgEgEAAgHQAAgGAEgFQAFgCAIAAIAPAAIAAgFQAAgGgDgCQgEgCgGgBIgEABIgEABIgCABIgCADIgFgFIADgDIADgCIAFgCIAGAAQAKAAAFAFQAFAEAAAHIAAAhIgHAAIAAgFIgDADIgDACIgEABIgFAAgEAkkAAFQgDACAAAEQAAAEADACQADACAGAAQAHAAADgDQADgCAAgGIAAgGIgOAAQgGABgCACgEAj4AAYQgFgBgEgFIAEgEQAEADADABQADABAFAAIAGgBQADgBABgBQABgBAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgEgDgCQgCgCgFgBIgHAAIAAgEIAHAAQAEAAADgCQACgDAAgDQAAgEgDgCQgDgBgFgBIgHABIgGAEIgEgGQAEgCAFgBQAEgCAFAAQAFAAAEACQAEABACADQACADAAAFQAAADgCADQgCADgDABQAEABACADQACADAAAEQAAAFgCADQgDADgEACQgEABgFABQgGgBgFgBgEAhyAAaQgJgBgEgDQgFgEAAgHQAAgGAFgFQAEgCAIAAIAPAAIAAgFQAAgGgDgCQgDgCgHgBIgEABIgDABIgDABIgCADIgFgFIADgDIADgCIAFgCIAGAAQAKAAAFAFQAFAEAAAHIAAAhIgHAAIAAgFIgDADIgCACIgEABIgFAAgEAhqAAFQgDACAAAEQAAAEADACQADACAGAAQAHAAADgDQADgCAAgGIAAgGIgOAAQgFABgDACgAfuAYIgGgEQgDgDgBgFQgCgEAAgIQAAgFACgFQABgFADgDQADgDADgBIAIgCIAIACQAEABACADQADADACAFQABAEAAAGQAAAIgBAEQgBAFgEADIgGAEIgIACIgIgCgAfxgRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgAeoATQgFgHAAgMQAAgLAFgGQAFgHAKAAQAJABAGAFQAFAHAAALIAAACIghAAIAAAGIABADQACAEADACQAEACAFAAIADAAIADgBIADgCIADgCIAFAEIgEAEIgEACIgFABIgFABQgKgBgGgGgAfEgCIgBgEIAAgDQgBgEgEgDQgDgCgEAAQgEAAgDACQgDACgCAEIgBADIAAAFIAaAAIAAAAgAd7ATQgGgHAAgMQAAgLAFgGQAGgHAJAAQAKABAFAFQAFAHAAALIAAACIghAAIABAGIABADQABAEAEACQADACAFAAIADAAIADgBIADgCIAEgCIAFAEIgFAEIgEACIgEABIgFABQgLgBgFgGgAeWgCIAAgEIgBgDQgBgEgDgDQgDgCgFAAQgEAAgDACQgDACgBAEIgBADIgBAFIAaAAIAAAAgAZmATQgFgHAAgMQAAgLAFgGQAFgHAKAAQAJABAGAFQAFAHAAALIAAACIghAAIAAAGIABADQACAEADACQAEACAFAAIADAAIADgBIADgCIADgCIAFAEIgEAEIgEACIgFABIgFABQgKgBgGgGgAaCgCIgBgEIAAgDQgBgEgEgDQgDgCgEAAQgEAAgDACQgDACgCAEIgBADIAAAFIAaAAIAAAAgAYIATQgFgHAAgMQAAgLAFgGQAFgHAKAAQAJABAGAFQAFAHAAALIAAACIghAAIAAAGIABADQACAEADACQAEACAFAAIADAAIADgBIADgCIADgCIAFAEIgEAEIgEACIgFABIgFABQgKgBgGgGgAYkgCIgBgEIAAgDQgBgEgEgDQgDgCgEAAQgEAAgDACQgDACgCAEIgBADIAAAFIAaAAIAAAAgAWyAYIgGgEQgDgDgBgFQgCgEAAgIQAAgFACgFQABgFADgDQADgDADgBIAIgCIAIACQAEABACADQADADACAFQABAEAAAGQAAAIgBAEQgBAFgEADIgGAEIgIACIgIgCgAW1gRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgAUMATQgGgHAAgMQAAgLAFgGQAGgHAJAAQAKABAFAFQAFAHAAALIAAACIghAAIABAGIABADQABAEAEACQADACAFAAIADAAIADgBIADgCIAEgCIAFAEIgFAEIgEACIgEABIgFABQgLgBgFgGgAUngCIAAgEIgBgDQgBgEgDgDQgDgCgFAAQgEAAgDACQgDACgBAEIgBADIgBAFIAaAAIAAAAgAQtAYIgGgEQgDgDgCgFQgBgEAAgIQAAgFABgFQACgFADgDQACgDAEgBIAIgCIAIACQADABADADQADADABAFQACAEAAAGQAAAIgCAEQgBAFgDADIgGAEIgIACIgIgCgAQwgRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgALyAYIgGgEQgDgDgCgFQgBgEAAgIQAAgFABgFQACgFADgDQACgDAEgBIAIgCIAIACQADABADADQADADABAFQACAEAAAGQAAAIgCAEQgBAFgDADIgGAEIgIACIgIgCgAL1gRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgAKSATQgGgHAAgMQAAgLAGgGQAGgHAKAAIAFAAIADACIAEACIAEADIgFAFIgDgDIgCgCIgDAAIgDgBQgHAAgEAGQgEAEAAAIQAAAJAEAGQAEAEAHAAIADAAIACgBIADgCIADgCIAFAEIAAABIABAAIAEgBIADgCIADgHIABgLIAAgVIAfAAIAAAwIgHAAIAAgqIgRAAIAAARQAAAJgCAGQgCAGgEACQgDACgFAAIgDAAIAAgGIgEADIgEACIgDABIgFABQgKgBgGgGgAIvAWQgEgDgCgGIgCgHIAAgHIAAgIIAAgLIABgIIACgHIAEgEQADgDAFgCQAFgBAGAAIAKgBIAAAHIgIABIgJABIgHACQgEADgBAFIgBALQACgDAEgCQAEgCAFgBIAHACIAFADQAEADABAGQACAFAAAFQAAAIgCAFQgBAEgDADQgDADgDABQgEABgEABQgHgBgFgDgAI2gRIgEAEQgCABgBAEQgBAEAAAEIABAKIADAGIAEACIAFABIAFgBIAEgCQACgCABgEIABgJIgBgJQgBgDgCgCIgEgEIgFgBIgFABgAIFAYIgGgEQgDgDgCgFQgBgEAAgIQAAgFABgFQACgFADgDQACgDAEgBIAIgCIAIACQADABADADQADADABAFQACAEAAAGQAAAIgCAEQgBAFgDADIgGAEIgIACIgIgCgAIIgRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgAE3AaQgIgBgFgDQgEgEAAgHQAAgGAEgFQAFgCAIAAIAPAAIAAgFQAAgGgDgCQgEgCgGgBIgEABIgEABIgCABIgCADIgFgFIADgDIADgCIAFgCIAGAAQAKAAAFAFQAFAEAAAHIAAAhIgHAAIAAgFIgDADIgDACIgEABIgFAAgAEwAFQgDACAAAEQAAAEADACQADACAGAAQAHAAADgDQADgCAAgGIAAgGIgOAAQgGABgCACgACcAYIgGgEQgDgDgCgFQgBgEAAgIQAAgFABgFQACgFADgDQACgDAEgBIAIgCIAIACQADABADADQADADABAFQACAEAAAGQAAAIgCAEQgBAFgDADIgGAEIgIACIgIgCgACfgRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgAhtAaQgIgBgFgDQgEgEAAgHQAAgGAEgFQAFgCAIAAIAPAAIAAgFQAAgGgDgCQgEgCgGgBIgEABIgEABIgCABIgCADIgFgFIADgDIADgCIAFgCIAGAAQAKAAAFAFQAFAEAAAHIAAAhIgHAAIAAgFIgDADIgDACIgEABIgFAAgAh0AFQgDACAAAEQAAAEADACQADACAGAAQAHAAADgDQADgCAAgGIAAgGIgOAAQgGABgCACgAjTAWQgFgDgCgGIgBgHIgBgHIAAgIIABgLIABgIIACgHIADgEQAEgDAFgCQAFgBAFAAIALgBIAAAHIgIABIgJABIgIACQgDADgBAFIgBALQACgDAEgCQAEgCAFgBIAHACIAFADQADADACAGQABAFAAAFQAAAIgBAFQgBAEgEADQgCADgEABQgDABgEABQgHgBgFgDgAjMgRIgEAEQgCABgBAEQgCAEAAAEIABAKIAEAGIAEACIAFABIAEgBIAEgCQACgCABgEIABgJIgBgJQAAgDgDgCIgEgEIgEgBIgFABgAj+AYIgGgEQgDgDgBgFQgCgEAAgIQAAgFACgFQABgFADgDQADgDADgBIAIgCIAIACQAEABACADQADADACAFQABAEAAAGQAAAIgBAEQgBAFgEADIgGAEIgIACIgIgCgAj7gRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgAmLAYIgGgEQgDgDgCgFQgBgEAAgIQAAgFABgFQACgFADgDQACgDAEgBIAIgCIAIACQADABADADQADADABAFQACAEAAAGQAAAIgCAEQgBAFgDADIgGAEIgIACIgIgCgAmIgRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgApUAXQgFgCgDgFQgDgFAAgFQAAgGADgEQADgEAFgDQgEgDgDgDQgCgEAAgGQAAgFACgFQADgEAEgDQAFgCAFAAQAGAAAEACQAFADACAEQADAFAAAFQAAAGgDAEQgCADgEADQAEADADAEQADAEAAAGQAAAFgDAFQgCAFgFACQgFACgGABQgGgBgEgCgApRgGQgDACgCADQgBACAAAFQAAADABAEIAFAEQADACAEAAQAEAAADgCIAFgEQACgEAAgDQAAgFgCgCQgCgDgDgCQgDgCgEAAQgEAAgDACgApTgkQgDAEAAAFQAAAGADADQAEAEAFAAQAGAAADgEQAEgDAAgGQAAgFgEgEQgDgEgGABQgFgBgEAEgAquAXQgEgDgDgEQgCgEAAgGIAAggQAAgGACgFQADgEAEgDQAFgCAFAAQAGAAAEACQAFADACAEQADAFAAAGIAAAgQAAAGgDAEQgCAEgFADQgEACgGABQgFgBgFgCgAqtgkQgDAEAAAGIAAAgQAAAGADAEQADADAGAAQAGAAAEgDQADgEAAgGIAAggQAAgGgDgEQgEgDgGAAQgGAAgDADgAt4AWQgFgDgCgGIgBgHIgBgHIAAgIIABgLIABgIIACgHIADgEQAEgDAFgCQAFgBAFAAIALgBIAAAHIgIABIgJABIgIACQgDADgBAFIgBALQACgDAEgCQAEgCAFgBIAHACIAFADQADADACAGQABAFAAAFQAAAIgBAFQgBAEgEADQgCADgEABQgDABgEABQgHgBgFgDgAtxgRIgEAEQgCABgBAEQgCAEAAAEIABAKIAEAGIAEACIAFABIAEgBIAEgCQACgCABgEIABgJIgBgJQAAgDgDgCIgEgEIgEgBIgFABgAueAaQgJgBgEgDQgFgEAAgHQAAgGAFgFQAEgCAIAAIAPAAIAAgFQAAgGgDgCQgDgCgHgBIgEABIgDABIgDABIgCADIgFgFIADgDIADgCIAFgCIAGAAQAKAAAFAFQAFAEAAAHIAAAhIgHAAIAAgFIgDADIgCACIgEABIgFAAgAumAFQgDACAAAEQAAAEADACQADACAGAAQAHAAADgDQADgCAAgGIAAgGIgOAAQgFABgDACgAwBATQgGgHAAgMQAAgLAFgGQAGgHAJAAQAKABAFAFQAFAHAAALIAAACIghAAIABAGIABADQABAEAEACQADACAFAAIADAAIADgBIADgCIAEgCIAFAEIgFAEIgEACIgEABIgFABQgLgBgFgGgAvmgCIAAgEIgBgDQgBgEgDgDQgDgCgFAAQgEAAgDACQgDACgBAEIgBADIgBAFIAaAAIAAAAgAxtAXQgEgCgDgFQgCgEAAgHIABgGIADgJIASgjIAHAAIgQAgQAEgCAEAAQAFAAAFADQAEACACAFQACAEAAAGQAAAGgCAFQgDAEgEADQgEACgGABQgHgBgEgCgAxsgEQgDADAAAGQAAAHADADQAEAEAFAAQAGAAAEgEQADgDAAgHQAAgEgBgCQgCgEgDgCQgCgCgFAAQgFAAgEAFgAyqAYIgGgEQgDgDgBgFQgCgEAAgIQAAgFACgFQABgFADgDQADgDADgBIAIgCIAIACQAEABACADQADADACAFQABAEAAAGQAAAIgBAEQgBAFgEADIgGAEIgIACIgIgCgAyngRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgA17AWQgEgDgCgGIgCgHIAAgHIAAgIIAAgLIABgIIACgHIAEgEQADgDAFgCQAFgBAGAAIAKgBIAAAHIgIABIgJABIgHACQgEADgBAFIgBALQACgDAEgCQAEgCAFgBIAHACIAFADQAEADABAGQACAFAAAFQAAAIgCAFQgBAEgDADQgDADgDABQgEABgEABQgHgBgFgDgA10gRIgEAEQgCABgBAEQgBAEAAAEIABAKIADAGIAEACIAFABIAFgBIAEgCQACgCABgEIABgJIgBgJQgBgDgCgCIgEgEIgFgBIgFABgA3SAYIgGgEQgDgDgCgFQgBgEAAgIQAAgFABgFQACgFADgDQACgDAEgBIAIgCIAIACQADABADADQADADABAFQACAEAAAGQAAAIgCAEQgBAFgDADIgGAEIgIACIgIgCgA3PgRIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgA6yATQgFgHAAgMQAAgLAFgGQAGgHALAAIAEAAIAEACIADACIAFADIgFAFIgDgDIgDgCIgDAAIgCgBQgIAAgEAGQgDAEAAAIQAAAJADAGQAEAEAHAAIADAAIADgBIACgCIAEgCIAFAEIgFAEIgDACIgEABIgEABQgLgBgGgGgA+pAaQgJgBgEgDQgFgEAAgHQAAgGAFgFQAEgCAIAAIAPAAIAAgFQAAgGgDgCQgDgCgHgBIgEABIgDABIgDABIgCADIgFgFIADgDIADgCIAFgCIAGAAQAKAAAFAFQAFAEAAAHIAAAhIgHAAIAAgFIgDADIgCACIgEABIgFAAgA+xAFQgDACAAAEQAAAEADACQADACAGAAQAHAAADgDQADgCAAgGIAAgGIgOAAQgFABgDACgEgiEAATQgFgHAAgMQAAgLAFgGQAFgHAKAAQAJABAGAFQAFAHAAALIAAACIghAAIAAAGIABADQACAEADACQAEACAFAAIADAAIADgBIADgCIADgCIAFAEIgEAEIgEACIgFABIgFABQgKgBgGgGgEghogACIgBgEIAAgDQgBgEgEgDQgDgCgEAAQgEAAgDACQgDACgCAEIgBADIAAAFIAaAAIAAAAgEgjiAATQgFgHAAgMQAAgLAFgGQAFgHAKAAQAJABAGAFQAFAHAAALIAAACIghAAIAAAGIABADQACAEADACQAEACAFAAIADAAIADgBIADgCIADgCIAFAEIgEAEIgEACIgFABIgFABQgKgBgGgGgEgjGgACIgBgEIAAgDQgBgEgEgDQgDgCgEAAQgEAAgDACQgDACgCAEIgBADIAAAFIAaAAIAAAAgEgk4AAYIgGgEQgDgDgBgFQgCgEAAgIQAAgFACgFQABgFADgDQADgDADgBIAIgCIAIACQAEABACADQADADACAFQABAEAAAGQAAAIgBAEQgBAFgEADIgGAEIgIACIgIgCgEgk1gARIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgEgo1AAYIgGgEQgDgDgCgFQgBgEAAgIQAAgFABgFQACgFADgDQACgDAEgBIAIgCIAIACQADABADADQADADABAFQACAEAAAGQAAAIgCAEQgBAFgDADIgGAEIgIACIgIgCgEgoygARIgEAEQgCABgBAEIgBAIIABAKQABAEACACIAEACIAFABIAFgBIAEgCQACgCABgEIABgKIgBgIQgBgEgCgBIgEgEIgFgBIgFABgEgqZAAYQgFgCgDgEQgEgDgBgEQgCgEAAgFIAAgMIAAgMQAAgGACgDQABgEAEgDQADgEAFgCQAEgCAGAAQAJABAHAFQAHAGABAJIgHAAQgCgGgEgEQgFgEgGAAIgHACQgDABgDACIgDAFIgBAIIgBALIABALIABAHIADAGIAGADIAHACQAGAAAFgEQAEgEACgGIAHAAQgBAGgDAFQgEAFgFACQgFACgGABQgGgBgEgBgEAvlAAZIAAgwIAHAAIAAAwgEAvOAAZIAAgrIgGAAIAAgFIAGAAIAAgJQAAgEABgDQACgDACgCQADgCAEAAIAGAAIAAAHIgEAAQgEAAgBACQgCACAAADIAAAJIALAAIAAAFIgLAAIAAArgEAu4AAZIAAgJIAJAAIAAAJgEAt/AAZQgEAAgDgCQgDgCgBgDQgCgDAAgDIAAgeIgGAAIAAgFIAGAAIAAgPIAIAAIAAAPIAKAAIAAAFIgKAAIAAAdQAAAEABACQACACADAAIAEAAIAAAGgEAtgAAZIAAgdQAAgHgDgDQgEgDgFgBQgGABgDADQgDADgBAHIAAAdIgHAAIAAhGIAHAAIAAAbQADgDAEgBQADgCAEAAQAJABAEAEQAFAFAAAIIAAAfgEAsFAAZQgGAAgDgEQgDgEAAgFIAAg5IAHAAIAAA4QAAAEACACQABACAEAAIAEAAIAAAGgEArlAAZIAAgJIAJAAIAAAJgEArMAAZIgNglIgNAlIgHAAIgNgoIgNAoIgHAAIgNglIgMAlIgHAAIgNgoIgNAoIgHAAIgNglIgNAlIgHAAIgPgwIAIAAIALAnIANgnIAGAAIANAnIALgnIALAAIALAnIANgnIAHAAIANAnIALgnIALAAIALAnIANgnIAGAAIANAnIALgnIAIAAIgPAwgEAn7AAZIAAgJIAKAAIAAAJgEAlUAAZIAAgqIgRAAIAAgGIAoAAIAAAGIgQAAIAAAqgEAjjAAZIAAglIgaAlIgHAAIAAgwIAHAAIAAAlIAaglIAHAAIAAAwgEAiwAAZIAAgXIgYAAIAAAXIgHAAIAAgwIAHAAIAAAVIAYAAIAAgVIAHAAIAAAwgEAhCAAZIAAgwIAfAAIAAAGIgYAAIAAAqgAdUAZIAAglIgaAlIgHAAIAAgwIAHAAIAAAlIAaglIAHAAIAAAwgAcQAZIAAgTIgMAAIgLATIgIAAIALgUQgFgCgDgDQgDgDAAgGQAAgGAEgEQAEgEAHAAIAXAAIAAAwgAb7gPQgDACAAAFQAAAEADADQACABAFAAIAOAAIAAgSIgOAAQgFABgCACgAbiAZIAAglIgZAlIgHAAIAAgwIAHAAIAAAlIAZglIAHAAIAAAwgAawAZIAAgXIgYAAIAAAXIgHAAIAAgwIAHAAIAAAVIAYAAIAAgVIAHAAIAAAwgAXWAZIAAgwIAXAAQAHAAAEAEQAEADAAAGQAAADgCAEQgCACgEABQAEABACADQACADAAAEQAAAHgDAEQgEADgHAAgAXdATIAPAAQAFAAACgDQACgBAAgFQAAgDgCgCQgCgDgFAAIgPAAgAXdgCIAPAAQAEgBACgBQADgCAAgEQAAgDgDgCQgCgCgEAAIgPAAgAVnAZIAAgqIgYAAIAAAqIgHAAIAAgwIAmAAIAAAwgAT9AZIgYgZIAWgXIAJAAIgWAXIAYAZgATeAZIAAgwIAHAAIAAAXIAAAZgAScAZIAAgTIgMAAIgLATIgIAAIALgUQgFgCgDgDQgDgDAAgGQAAgGAEgEQAEgEAHAAIAXAAIAAAwgASHgPQgDACAAAFQAAAEADADQACABAFAAIAOAAIAAgSIgOAAQgFABgCACgAQRAZIAAgqIgYAAIAAAqIgHAAIAAgwIAmAAIAAAwgAO/AZIgMgTIgMATIgIAAIAQgZIgQgXIAJAAIALASIALgSIAJAAIgQAXIARAZgAOTAZIAAgTIgMAAIgLATIgIAAIALgUQgFgCgDgDQgDgDAAgGQAAgGAEgEQAEgEAHAAIAXAAIAAAwgAN+gPQgDACAAAFQAAAEADADQACABAFAAIAOAAIAAgSIgOAAQgFABgCACgANlAZIAAglIgZAlIgHAAIAAgwIAHAAIAAAlIAZglIAHAAIAAAwgAMWAZIAAgwIAXAAQAGAAAEAEQAEADAAAGQAAADgCAEQgCACgEABQAEABADADQACADAAAEQAAAHgEAEQgEADgHAAgAMdATIAPAAQAEAAACgDQADgBAAgFQAAgDgDgCQgCgDgEAAIgPAAgAMdgCIAOAAQAFgBACgBQACgCAAgEQAAgDgCgCQgCgCgFAAIgOAAgAHYAZIAAgTIgMAAIgLATIgIAAIALgUQgFgCgDgDQgDgDAAgGQAAgGAEgEQAEgEAHAAIAXAAIAAAwgAHDgPQgDACAAAFQAAAEADADQACABAFAAIAOAAIAAgSIgOAAQgFABgCACgAGqAZIAAglIgZAlIgHAAIAAgwIAHAAIAAAlIAZglIAHAAIAAAwgAEYAZIAAgiIgOAaIgGAAIgOgaIAAAiIgHAAIAAgwIAHAAIARAgIARggIAHAAIAAAwgABCAZIAAgXIgYAAIAAAXIgHAAIAAgwIAHAAIAAAVIAYAAIAAgVIAHAAIAAAwgAARAZIAAglIgYAlIgHAAIAAgwIAHAAIAAAlIAYglIAHAAIAAAwgAgyAZIAAgTIgMAAIgKATIgJAAIAMgUQgFgCgDgDQgDgDgBgGQABgGAEgEQAEgEAHAAIAWAAIAAAwgAhHgPQgCACAAAFQAAAEACADQADABAEAAIAOAAIAAgSIgOAAQgEABgDACgAiMAZIAAgXIgYAAIAAAXIgHAAIAAgwIAHAAIAAAVIAYAAIAAgVIAHAAIAAAwgAmpAZIAAg/IghAAIAAA/IgIAAIAAhGIAxAAIAABGgAn5AZIAAgJIAJAAIAAAJgAobAZIAAgwIAfAAIAAAGIgYAAIAAAqgAp3AZIAAg+IgNALIAAgIIANgLIAHAAIAABGgArkAZIAAgHIAcgiIADgFIABgGQAAgFgDgEQgDgEgGABQgEAAgCABQgDABgCADQgCADAAAEIgHAAQAAgFADgFQACgEAEgCQAFgCAGgBQAGAAAEACQAEADADAEQACAFAAAFQAAAEgBAEIgEAHIgZAeIAeAAIAAAHgAsFAZIAAgTIgMAAIgLATIgIAAIALgUQgFgCgDgDQgDgDAAgGQAAgGAEgEQAEgEAHAAIAXAAIAAAwgAsagPQgDACAAAFQAAAEADADQACABAFAAIAOAAIAAgSIgOAAQgFABgCACgAu4AZIgXgZIAWgXIAIAAIgWAXIAYAZgAvWAZIAAgwIAHAAIAAAXIAAAZgAzFAZIAAgqIgYAAIAAAqIgHAAIAAgwIAmAAIAAAwgA0IAZIAAgTIgMAAIgKATIgJAAIAMgUQgFgCgDgDQgDgDgBgGQABgGAEgEQAEgEAHAAIAWAAIAAAwgA0dgPQgCACAAAFQAAAEACADQADABAEAAIAOAAIAAgSIgOAAQgEABgDACgA2TAZIAAgTIgMAAIgKATIgJAAIAMgUQgFgCgDgDQgDgDgBgGQABgGAEgEQAEgEAHAAIAWAAIAAAwgA2ogPQgCACAAAFQAAAEACADQADABAEAAIAOAAIAAgSIgOAAQgEABgDACgA3uAZIAAgXIgYAAIAAAXIgHAAIAAgwIAHAAIAAAVIAYAAIAAgVIAHAAIAAAwgA5GAZIAZhAIgZAAIAAAMIgHAAIAAgSIAnAAIAAAGIgYBAgA57AZIAAgHIAcgiIADgFIABgGQAAgFgDgEQgDgEgGABQgEAAgCABQgDABgCADQgCADAAAEIgHAAQAAgFADgFQACgEAEgCQAFgCAGgBQAGAAAEACQAEADADAEQACAFAAAFQAAAEgBAEIgEAHIgZAeIAeAAIAAAHgA7ZAZIAAglIgZAlIgHAAIAAgwIAHAAIAAAlIAZglIAHAAIAAAwgA8LAZIAAglIgaAlIgHAAIAAgwIAHAAIAAAlIAaglIAHAAIAAAwgA9rAZIgXgZIAWgXIAIAAIgWAXIAYAZgA+JAZIAAgwIAHAAIAAAXIAAAZgA/aAZIAAgTIgMAAIgLATIgIAAIALgUQgFgCgDgDQgDgDAAgGQAAgGAEgEQAEgEAHAAIAXAAIAAAwgA/vgPQgDACAAAFQAAAEADADQACABAFAAIAOAAIAAgSIgOAAQgFABgCACgEggIAAZIAAglIgZAlIgHAAIAAgwIAHAAIAAAlIAZglIAHAAIAAAwgEgg6AAZIAAgXIgYAAIAAAXIgHAAIAAgwIAHAAIAAAVIAYAAIAAgVIAHAAIAAAwgEgkUAAZIAAgwIAXAAQAHAAAEAEQAEADAAAGQAAADgCAEQgCACgEABQAEABACADQACADAAAEQAAAHgDAEQgEADgHAAgEgkNAATIAPAAQAFAAACgDQACgBAAgFQAAgDgCgCQgCgDgFAAIgPAAgEgkNgACIAPAAQAEgBACgBQADgCAAgEQAAgDgDgCQgCgCgEAAIgPAAgEgmDAAZIAAgqIgYAAIAAAqIgHAAIAAgwIAmAAIAAAwgEgnGAAZIAAglIgZAlIgHAAIAAgwIAHAAIAAAlIAZglIAHAAIAAAwgEgnyAAZIgYgZIAWgXIAJAAIgWAXIAYAZgEgoRAAZIAAgwIAHAAIAAAXIAAAZgEgrNAAZIAAgJIAJAAIAAAJgEgreAAZIAAgTIgMAAIgLATIgIAAIALgUQgFgCgDgDQgDgDAAgGQAAgGAEgEQAEgEAHAAIAXAAIAAAwgEgrzgAPQgDACAAAFQAAAEADADQACABAFAAIAOAAIAAgSIgOAAQgFABgCACgEgsMAAZIAAglIgZAlIgHAAIAAgwIAHAAIAAAlIAZglIAHAAIAAAwgEgtrAAZIgYgZIAWgXIAJAAIgWAXIAYAZgEguKAAZIAAgwIAHAAIAAAXIAAAZgEguVAAZIgGgQIgfAAIgGAQIgIAAIAahGIAHAAIAaBGgEgudAACIgOglIgNAlIAbAAgATlAAgA+CAAgEguDAAAgEAn7gAEIAAgJIAKAAIAAAJgEgvdgAKIAAgOIgLAHIgDgEIAMgGIgMgIIADgEIALAHIAAgOIAGAAIgBAOIAMgHIADAEIgMAIIAMAGIgDAEIgMgHIABAOgAe+giIAAgJIAHAAIAAAJgAepgiIAAgJIAHAAIAAAJgEAvkgAlIAAgIIAIAAIAAAIg");
	this.shape.setTransform(310.9,8.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.instance = new lib.Path_1();
	this.instance.parent = this;
	this.instance.setTransform(317,8.4,2.692,0.452,0,0,0,117.2,15.6);
	this.instance.alpha = 0.5;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal, new cjs.Rectangle(1.4,-1.7,660.7,17), null);


// stage content:
(lib._468x60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgkegEmMBI9AAAIAAJNMhI9AAAg");
	this.shape.setTransform(234,30);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(300));

	// logo
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(80.3,29.6,0.666,0.666,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(221).to({regX:0.2,scaleX:0.81,scaleY:0.81,x:120.3},8,cjs.Ease.get(1)).wait(62).to({regX:0.1,scaleX:0.67,scaleY:0.67,x:80.3},8,cjs.Ease.get(1)).wait(1));

	// legal
	this.instance_1 = new lib.legal();
	this.instance_1.parent = this;
	this.instance_1.setTransform(86.6,62.7,0.75,0.75,0,0,0,115.2,18.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(300));

	// 4a.jpg
	this.instance_2 = new lib.s4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(293.5,39.6,0.666,0.666,0,0,0,120.2,199.8);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(217).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(66).to({alpha:0},8,cjs.Ease.get(1)).wait(1));

	// t3b
	this.instance_3 = new lib.t3b();
	this.instance_3.parent = this;
	this.instance_3.setTransform(280.1,37.6,0.666,0.666,0,0,0,0.1,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(149).to({_off:false},0).wait(1).to({regX:0,regY:0,x:279.7,alpha:0.019},0).wait(1).to({x:278.3,alpha:0.086},0).wait(1).to({x:275.5,alpha:0.226},0).wait(1).to({x:270.9,alpha:0.457},0).wait(1).to({x:265.7,alpha:0.716},0).wait(1).to({x:262.2,alpha:0.892},0).wait(1).to({x:260.5,alpha:0.977},0).wait(1).to({regX:0.1,regY:0.1,x:260.1,alpha:1},0).wait(54).to({x:240.2,alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(80));

	// t3a
	this.instance_4 = new lib.t3a();
	this.instance_4.parent = this;
	this.instance_4.setTransform(280.1,16.3,0.666,0.666,0,0,0,0.1,0.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(145).to({_off:false},0).wait(1).to({regX:0,regY:0,x:279.7,y:16.2,alpha:0.019},0).wait(1).to({x:278.3,alpha:0.086},0).wait(1).to({x:275.5,alpha:0.226},0).wait(1).to({x:270.9,alpha:0.457},0).wait(1).to({x:265.7,alpha:0.716},0).wait(1).to({x:262.2,alpha:0.892},0).wait(1).to({x:260.5,alpha:0.977},0).wait(1).to({regX:0.1,regY:0.1,x:260.1,y:16.3,alpha:1},0).wait(54).to({x:240.2,alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(84));

	// 3a.png
	this.instance_5 = new lib.s3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(413.3,84.6,0.533,0.533,0,0,0,73.2,110.7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(152).to({_off:false},0).to({regY:110.6,scaleX:0.67,scaleY:0.67,x:413.4,alpha:1},8,cjs.Ease.get(1)).wait(52).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(79));

	// t2c
	this.instance_6 = new lib.t2c();
	this.instance_6.parent = this;
	this.instance_6.setTransform(400.2,29.3,0.485,0.485,0,0,0,0.1,0.3);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(73).to({_off:false},0).wait(1).to({regX:0,regY:0,x:399.8,y:29.1,alpha:0.022},0).wait(1).to({x:398.6,alpha:0.102},0).wait(1).to({x:396.3,alpha:0.258},0).wait(1).to({x:393,alpha:0.491},0).wait(1).to({x:389.5,alpha:0.729},0).wait(1).to({x:387.1,alpha:0.893},0).wait(1).to({x:385.9,alpha:0.976},0).wait(1).to({regX:0.2,regY:0.3,x:385.6,y:29.3,alpha:1},0).wait(57).to({regX:0,regY:0,x:385.2,y:29.1,alpha:0.978},0).wait(1).to({x:384,alpha:0.899},0).wait(1).to({x:381.7,alpha:0.738},0).wait(1).to({x:378.2,alpha:0.494},0).wait(1).to({x:374.7,alpha:0.254},0).wait(1).to({x:372.4,alpha:0.098},0).wait(1).to({x:371.3,alpha:0.021},0).wait(1).to({regX:0.3,regY:0.3,x:371.1,y:29.3,alpha:0},0).to({_off:true},1).wait(154));

	// t2b
	this.instance_7 = new lib.t2b();
	this.instance_7.parent = this;
	this.instance_7.setTransform(275.6,38.5,0.599,0.599,0,0,0,0.1,0.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(71).to({_off:false},0).wait(1).to({regX:0,regY:0,x:275.1,y:38.4,alpha:0.022},0).wait(1).to({x:273.7,alpha:0.102},0).wait(1).to({x:270.9,alpha:0.258},0).wait(1).to({x:266.7,alpha:0.491},0).wait(1).to({x:262.5,alpha:0.729},0).wait(1).to({x:259.5,alpha:0.893},0).wait(1).to({x:258,alpha:0.976},0).wait(1).to({regX:0.1,regY:0.1,x:257.6,y:38.5,alpha:1},0).wait(55).to({regX:0,regY:0,x:257.3,y:38.4,alpha:0.986},0).wait(1).to({x:256.5,alpha:0.939},0).wait(1).to({x:254.8,alpha:0.845},0).wait(1).to({x:252.1,alpha:0.694},0).wait(1).to({x:248.5,alpha:0.494},0).wait(1).to({x:244.9,alpha:0.296},0).wait(1).to({x:242.3,alpha:0.149},0).wait(1).to({x:240.7,alpha:0.059},0).wait(1).to({x:239.8,alpha:0.013},0).wait(1).to({regX:0.1,regY:0.1,x:239.7,y:38.5,alpha:0},0).to({_off:true},1).wait(156));

	// t2a
	this.instance_8 = new lib.t2a();
	this.instance_8.parent = this;
	this.instance_8.setTransform(276.2,15.5,0.599,0.599,0,0,0,0.1,0.1);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(69).to({_off:false},0).wait(1).to({regX:0,regY:0,x:275.7,alpha:0.022},0).wait(1).to({x:274.3,alpha:0.102},0).wait(1).to({x:271.5,alpha:0.258},0).wait(1).to({x:267.3,alpha:0.491},0).wait(1).to({x:263,alpha:0.729},0).wait(1).to({x:260.1,alpha:0.893},0).wait(1).to({x:258.6,alpha:0.976},0).wait(1).to({regX:0.3,regY:0.1,x:258.3,alpha:1},0).wait(55).to({regX:0,regY:0,x:257.7,alpha:0.978},0).wait(1).to({x:256.3,alpha:0.899},0).wait(1).to({x:253.4,alpha:0.738},0).wait(1).to({x:249,alpha:0.494},0).wait(1).to({x:244.7,alpha:0.254},0).wait(1).to({x:241.9,alpha:0.098},0).wait(1).to({x:240.5,alpha:0.021},0).wait(1).to({regX:0.1,regY:0.1,x:240.3,alpha:0},0).to({_off:true},1).wait(160));

	// 2.jpg
	this.instance_9 = new lib.s2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(80.3,132.9,0.666,0.666,0,0,0,120,200.1);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(62).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(61).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(160));

	// 1a.jpg
	this.instance_10 = new lib.s1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(247.2,122.4,0.599,0.599,0,0,0,120.3,200.1);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({alpha:1},8,cjs.Ease.get(1)).wait(54).to({alpha:0},8,cjs.Ease.get(1)).to({_off:true},1).wait(229));

	// bg
	this.instance_11 = new lib.bg();
	this.instance_11.parent = this;
	this.instance_11.setTransform(242.8,30.3,2.02,0.25,0,0,0,120,199.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(300));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(233.5,10.4,485.7,256.4);
// library properties:
lib.properties = {
	width: 468,
	height: 60,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/p3a.png", id:"p3a"},
		{src:"images/468x60_atlas_NP_.jpg", id:"468x60_atlas_NP_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;