(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"160x600_atlas_", frames: [[0,0,160,190],[162,0,160,190],[162,192,160,190],[0,192,160,190]]}
];


// symbols:



(lib._1 = function() {
	this.initialize(ss["160x600_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.initialize(ss["160x600_atlas_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._3 = function() {
	this.initialize(ss["160x600_atlas_"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib._5 = function() {
	this.initialize(ss["160x600_atlas_"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AmnCwIAAgVIhQAAIAAAVIgVAAIAAgoIALAAIAphbIASAAIApBbIALAAIAAAogAm0CIIgbg/IgcA/IA3AAgACnCZQgKgGgIgJQgHgIgDgKQgEgLAAgJQAAgJAEgKQADgKAHgJQAIgIAKgGQALgGAPABQALAAAKADQAKAEAIAIQAIAIAFAKIgYAAQgDgDgEgDQgEgEgFgBQgFgCgHAAQgLgBgIAGQgJAFgFAJQgEAIAAAKQAAAKAEAJQAGAJAIAFQAIAFALAAQAIABAHgEQAHgDAFgGIAYAAQgFAJgHAIQgIAHgKAEQgJAEgMAAQgPAAgLgFgAicCXQgNgIgHgNQgJgNAAgRQAAgPAJgOQAHgNANgIQANgHARAAQARAAANAHQANAIAHANQAJAOgBAPQABARgJANQgHANgNAIQgOAHgQAAQgQAAgOgHgAiSBDQgIAGgFAIQgFAJAAAKQAAAKAFAJQAFAJAIAFQAJAFALAAQALAAAJgFQAIgFAFgJQAFgJAAgKQAAgKgFgJQgFgIgIgGQgJgEgLAAQgLAAgJAEgAlwCXQgOgIgHgNQgIgNAAgRQAAgPAIgOQAHgNAOgIQANgHARAAQAQAAANAHQANAIAIANQAIAOAAAPQAAARgIANQgIANgNAIQgNAHgQAAQgRAAgNgHgAlmBDQgIAGgGAIQgEAJAAAKQAAAKAEAJQAGAJAIAFQAJAFALAAQALAAAIgFQAIgFAGgJQAEgJAAgKQAAgKgEgJQgGgIgIgGQgIgEgLAAQgLAAgJAEgArRCZQgLgGgHgJQgIgIgDgKQgEgLABgJQgBgJAEgKQADgKAIgJQAHgIALgGQALgGAOABQAMAAAKADQAKAEAIAIQAHAIAFAKIgYAAQgCgDgEgDQgEgEgFgBQgGgCgHAAQgLgBgIAGQgJAFgEAJQgFAIAAAKQAAAKAFAJQAFAJAIAFQAJAFALAAQAHABAIgEQAGgDAFgGIAZAAQgFAJgHAIQgIAHgKAEQgKAEgMAAQgOAAgLgFgALeCbIAAgTIAUAAIAAATgAK1CbIAAhSIgeBSIgRAAIgehSIAABSIgUAAIAAhuIAcAAIAeBUIAghUIAcAAIAABugAIFCbIAAhuIA8AAIAAAUIgnAAIAAAZIAmAAIAAAUIgmAAIAAAaIAnAAIAAATgAHdCbIAAhOIgyBOIgUAAIAAhuIAUAAIAABNIAyhNIAVAAIAABugAE/CbIAAhuIAbAAIAHAAIAKABQAGACAEADQAFADADAFQAEAGAAAJQAAAGgDAFQgCAEgDADIgEADQAJADAFAHQAEAIABAJQAAAIgEAHQgEAJgJAFQgKAEgSAAgAFUCIIAOAAIADAAIAHgCQACgCADgDQACgCAAgGQAAgCgBgDQgBgDgEgDQgEgDgHAAIgOAAgAFUBXIAKAAQAGAAAEgCQADgDABgCIAAgEQAAgGgCgCQgDgCgEgBIgFAAIgKAAgAEMCbIAAhaIgUAAIAAgUIA+AAIAAAUIgVAAIAABagAA2CbIAAhuIAVAAIAAAqIAQAAQAOABAHAEQAJAFADAIQADAIABAIQAAALgGAHQgEAIgIAEQgJAEgKAAgABLCIIAQAAQAHgBAEgDQAFgEAAgHQAAgGgFgEQgEgEgHAAIgQAAgAAUCbIgehSIgeBSIgWAAIArhuIASAAIArBugAkKCbIAAhuIAbAAIAHAAIAKABQAFACAFADQAFADADAFQAEAGgBAJQABAGgDAFQgCAEgEADIgDADQAJADAEAHQAFAIAAAJQAAAIgDAHQgEAJgKAFQgKAEgRAAgAj1CIIANAAIAEAAIAGgCQADgCACgDQADgCAAgGQAAgCgBgDQgCgDgDgDQgEgDgIAAIgNAAgAj1BXIAJAAQAHAAADgCQADgDABgCIABgEQgBgGgCgCQgCgCgEgBIgGAAIgJAAgAo/CbIAMgcIgqhSIAYAAIAeA6IAZg6IAXAAIgyBugALeB/IAAhSIAUAAIAABSgADYgqIAAgUIhQAAIAAAUIgVAAIAAgoIALAAIAohcIASAAIAqBcIAKAAIAAAogADLhSIgcg/IgbA/IA3AAgAEOhEQgNgHgIgNQgHgNgBgQQABgRAHgNQAIgNANgIQANgHARgBQARABANAHQANAIAIANQAHANAAARQAAAQgHANQgIANgNAHQgNAIgRAAQgRAAgNgIgAEZiXQgJAFgFAJQgFAJAAAKQAAAKAFAKQAFAIAJAFQAIAFALABQALgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgJgJgFQgIgEgLgBQgLABgIAEgAlDhEQgNgHgIgNQgHgNgBgQQABgRAHgNQAIgNANgIQANgHARgBQARABANAHQANAIAIANQAHANAAARQAAAQgHANQgIANgNAHQgNAIgRAAQgRAAgNgIgAk4iXQgJAFgFAJQgFAJAAAKQAAAKAFAKQAFAIAJAFQAIAFALABQALgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgJgJgFQgIgEgLgBQgLABgIAEgAn5hEQgNgHgHgNQgIgNAAgQQAAgRAIgNQAHgNANgIQAOgHARgBQAQABANAHQANAIAIANQAIANAAARQAAAQgIANQgIANgNAHQgNAIgQAAQgRAAgOgIgAnuiXQgJAFgFAJQgEAJAAAKQAAAKAEAKQAFAIAJAFQAJAFALABQALgBAIgFQAJgFAEgJQAGgIgBgLQABgKgGgJQgEgJgJgFQgIgEgLgBQgLABgJAEgAJMg+IgLgdIgqAAIgLAdIgXAAIAuhwIARAAIAuBwgAI5hvIgNggIgMAgIAZAAgAHWg+IAAhTIgeBTIgRAAIgehTIAABTIgVAAIAAhwIAcAAIAgBWIAehWIAcAAIAABwgAALg+IAAhwIA7AAIAAAVIgmAAIAAAZIAlAAIAAAUIglAAIAAAaIAmAAIAAAUgAgng+IAAhbIgUAAIAAgVIA8AAIAAAVIgUAAIAABbgAiFg+IAAhwIAUAAIAAArIARAAQAOAAAHAGQAJAEADAIQADAIABAIQAAAKgGAIQgEAIgIAEQgIAEgLABgAhxhSIARAAQAHAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgHAAIgRAAgAjdg+IAAhwIAbAAIAHAAIAKADQAGABAEADQAFADAEAFQADAGAAAJQAAAGgDAFQgCAFgDACIgEADQAJADAFAHQAEAHABAKQAAAIgEAIQgEAHgJAFQgKAGgSAAgAjIhSIAOAAIADAAIAHgDQADgBACgCQACgEAAgFQAAgCgBgDQgBgEgEgCQgEgCgHgBIgOAAgAjIiDIAKAAQAGAAADgCQAEgDABgCIAAgEQAAgFgCgDQgDgDgEAAIgFAAIgKAAgAmKg+IAAhbIgVAAIAAgVIA+AAIAAAVIgVAAIAABbgApRg+IAAhwIA3AAIAAAVIgiAAIAABbg");
	this.shape.setTransform(-0.35,1.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t5, new cjs.Rectangle(-78.3,-21.9,156.6,43.9), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AlLCMQgNgHgHgNQgJgNAAgRQAAgQAJgOQAHgMANgIQANgIARAAQARAAANAIQANAIAHAMQAJAOgBAQQABARgJANQgHANgNAHQgOAIgQAAQgQAAgOgIgAlBA5QgIAFgFAIQgFAJAAAKQAAALAFAJQAFAJAIAFQAJAEALABQALgBAJgEQAIgFAFgKQAFgIAAgLQAAgKgFgJQgFgIgIgFQgJgFgLAAQgLAAgJAFgAGnCRIgLgdIgpAAIgLAdIgXAAIAuhvIAQAAIAvBvgAGUBgIgMggIgNAgIAZAAgAEtCRIAAhbIgVAAIAAgUIA+AAIAAAUIgUAAIAABbgAD8CRIgjgxIAAAxIgUAAIAAhvIAUAAIAAAwIAjgwIAZAAIgrA2IArA5gAB2CRIAAhvIA8AAIAAAUIgmAAIAAAZIAlAAIAAAUIglAAIAAAaIAmAAIAAAUgABVCRIgfhTIgeBTIgXAAIAshvIASAAIAtBvgAgdCRIAAhbIgpAAIAABbIgUAAIAAhvIBRAAIAABvgAiECRIAAhTIgdBTIgRAAIgdhTIAABTIgVAAIAAhvIAcAAIAeBVIAghVIAcAAIAABvgAl+CRIgigxIAAAxIgWAAIAAhvIAWAAIAAAwIAigwIAYAAIgpA2IApA5gAgwgmQgNgIgIgNQgHgNgBgRQABgPAHgOQAIgNANgHQANgJARABQARgBAMAJQANAHAIANQAHAOAAAPQAAARgHANQgIANgNAIQgMAHgRAAQgRAAgNgHgAglh5QgJAEgFAJQgFAIAAALQAAALAFAIQAFAJAJAFQAIAFALABQALgBAHgFQAJgFAFgJQAFgIAAgLQAAgLgFgIQgFgJgJgEQgHgGgLAAQgLAAgIAGgAG/giIAAhvIA7AAIAAAUIgnAAIAAAaIAlAAIAAAUIglAAIAAAZIAnAAIAAAUgAGZgiIgigwIAAAwIgWAAIAAhvIAWAAIAAAwIAigwIAYAAIgpA3IApA4gAE5giIAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvgACogiIAMgcIgqhTIAYAAIAeA8IAZg8IAXAAIgyBvgABtgiIgjgwIAAAwIgUAAIAAhvIAUAAIAAAwIAjgwIAZAAIgrA3IArA4gAhvgiIAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvgAj5giIAAhNIgxBNIgVAAIAAhvIAVAAIAABPIAxhPIAVAAIAABvgAmTgiIAAhvIAfAAQANAAAIAFQAJADADAGQAFAGABAGIABAJIgBALQgCAHgFAEQgEAGgIADQgIADgMABIgKAAIAAApgAl+hfIAMAAIAHgBQAEgBADgDQADgEABgGQgBgHgDgDQgDgDgEgBIgHgBIgMAAgAm7giIAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvg");
	this.shape.setTransform(0.05,0.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-53.6,-19.9,107.2,39.9), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AgNCMQgOgHgHgNQgIgNAAgRQAAgQAIgOQAHgMAOgIQANgIAQAAQAQAAANAIQAOAIAHAMQAIAOAAAQQAAARgIANQgHANgOAHQgNAIgQAAQgQAAgNgIgAgDA5QgIAFgGAIQgEAJAAAKQAAALAEAJQAGAJAIAFQAHAEAMABQALgBAIgEQAIgFAGgKQAEgIAAgLQAAgKgEgJQgGgIgIgFQgIgFgLAAQgMAAgHAFgAjlCOQgLgFgHgJQgHgJgEgKQgDgKgBgKQABgJADgKQAEgKAHgIQAHgJALgGQALgFAPAAQALAAAKAEQAKAEAIAIQAHAHAFALIgXAAQgDgEgEgDQgEgDgFgCQgFgCgHAAQgLAAgJAGQgIAEgFAJQgFAIAAAKQAAALAFAIQAFAKAIAFQAJAEALABQAIAAAGgEQAHgDAGgGIAXAAQgEAJgHAIQgIAIgKADQgKAFgLAAQgQAAgKgGgAFQCRIAAgrIgBAAIgeArIgXAAIAegpQgJgBgHgFQgGgDgEgIQgEgHAAgKIACgKQABgGAEgGQAEgGAJgEQAIgEAOAAIAgAAIAABvgAE3A5QgFACgCADQgBAFAAADQAAAEABAEQACAEAFADQAEACAIAAIANAAIAAghIgNAAQgIAAgEADgAD1CRIAAhOIgxBOIgVAAIAAhvIAVAAIAABOIAxhOIAVAAIAABvgABYCRIAAhvIAbAAIAHAAIAKACQAFACAFADQAFADADAFQAEAGgBAIQAAAHgCAFQgDAEgDACIgEAEQAJACAGAIQAEAHAAAKQAAAHgDAIQgEAIgKAFQgKAFgRAAgABtB9IANAAIAEAAIAGgCQADgBADgDQACgDAAgFQAAgCgBgDQgBgEgEgDQgEgCgIgBIgNAAgABtBNIAJAAQAHAAADgCQADgDABgDIABgDQgBgGgCgCQgCgDgEgBIgGAAIgJAAgAhBCRIgehTIgfBTIgWAAIAshvIASAAIArBvgAlLCRIAOgcIgrhTIAZAAIAdA7IAZg7IAXAAIgyBvgAizgMIAAgWIhKAAIAAhvIAVAAIAABbIApAAIAAhbIAUAAIAABbIANAAIAAAqgAoKglQgLgFgHgIQgHgJgEgKQgDgLAAgJQAAgJADgLQAEgKAHgIQAHgJALgFQALgFAOAAQAMAAAKADQAKAFAHAHQAJAIAEALIgYAAQgCgFgEgCQgEgEgGgCQgEgCgIAAQgLABgIAFQgIAFgFAIQgFAJAAAKQAAALAFAIQAFAJAJAFQAIAFALABQAHAAAIgEQAHgDAEgHIAZAAQgFAKgIAHQgHAIgKAEQgKAEgMAAQgPAAgKgGgAHwgiIAAhvIA7AAIAAAUIgmAAIAAAaIAlAAIAAAUIglAAIAAAZIAmAAIAAAUgAHIgiIAAhvIAUAAIAABvgAFygiIAAhvIAWAAIAAArIAQAAQANAAAJAFQAIAGADAHQAEAIAAAJQgBAJgFAJQgEAHgIAEQgJAFgKgBgAGIg2IAQAAQAHABAFgEQAEgEAAgGQAAgIgEgDQgFgEgHAAIgQAAgAFKgiIAAguIgpAAIAAAuIgVAAIAAhvIAVAAIAAAtIApAAIAAgtIAUAAIAABvgAC1giIAAhvIAWAAIAAArIAQAAQANAAAJAFQAIAGADAHQAEAIAAAJQgBAJgFAJQgEAHgIAEQgJAFgKgBgADLg2IAQAAQAHABAFgEQAEgEAAgGQAAgIgEgDQgFgEgHAAIgQAAgACUgiIgfhSIgeBSIgXAAIAshvIASAAIAsBvgAAogiIgMgcIgnAAIgMAcIgXAAIAuhvIAQAAIAuBvgAAVhSIgNghIgLAhIAYAAgAhNgiIAAhNIgyBNIgUAAIAAhvIAUAAIAABPIAyhPIAVAAIAABvgAlLgiIAAhvIA8AAIAAAUIgmAAIAAAaIAlAAIAAAUIglAAIAAAZIAmAAIAAAUgAlzgiIAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvg");
	this.shape.setTransform(-0.2,0.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-58.3,-19.9,116.6,39.9), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AEhETIgMgcIgpAAIgLAcIgXAAIAuhuIAQAAIAvBugAENDjIgNghIgMAhIAZAAgACtETIgigwIAAAwIgVAAIAAhuIAVAAIAAAvIAigvIAZAAIgqA2IAqA4gABNETIAAhNIgxBNIgVAAIAAhuIAVAAIAABOIAxhOIAVAAIAABugAghETIAAguIgoAAIAAAuIgVAAIAAhuIAVAAIAAAsIAoAAIAAgsIAVAAIAABugAiAETIgbgmIgaAmIgZAAIAng3Igng3IAZAAIAaAmIAbgmIAXAAIgmA3IAmA3gAkSETIAAhuIA7AAIAAATIgmAAIAAAaIAlAAIAAAUIglAAIAAAZIAmAAIAAAUgAlFETIAAhbIgVAAIAAgTIA+AAIAAATIgVAAIAABbgAhjAzQgNgHgHgNQgIgNAAgQQAAgPAIgOQAHgNANgIQANgHARgBQARABANAHQANAIAIANQAHAOABAPQgBAQgHANQgIANgNAHQgOAIgQAAQgRAAgNgIgAhZgfQgIAFgFAJQgFAIAAAKQAAAKAFAKQAFAIAIAFQAJAFALAAQALAAAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgIQgFgJgJgFQgIgEgLAAQgLAAgJAEgAFvA5IAAgsIAAAAIgeAsIgYAAIAegqQgJAAgGgFQgGgEgFgHQgDgHAAgJIABgLQABgFAFgHQAEgFAIgFQAIgDAOAAIAhAAIAABugAFWgfQgEADgCADQgCAEAAAEQAAAEACAEQACADAEADQAFACAHAAIANAAIAAggIgNAAQgHgBgFADgAEcA5IgMgdIgoAAIgMAdIgWAAIAuhuIAQAAIAuBugAEIAIIgMgfIgMAfIAYAAgACmA5IAAgvIgoAAIAAAvIgVAAIAAhuIAVAAIAAAsIAoAAIAAgsIAVAAIAABugABAA5IAAgvIgoAAIAAAvIgWAAIAAhuIAWAAIAAAsIAoAAIAAgsIAUAAIAABugAidA5IgagnIgaAnIgYAAIAmg4Igmg2IAYAAIAaAmIAagmIAYAAIgmA2IAmA4gAk0A5IANgcIgrhSIAZAAIAdA5IAag5IAXAAIgzBugAlvA5IgigxIAAAxIgVAAIAAhuIAVAAIAAAwIAigwIAZAAIgqA1IAqA5gACkilQgLgFgHgIQgHgJgDgKQgEgKAAgKQAAgKAEgKQADgKAHgIQAHgIALgGQALgFAPgBQALAAAKAEQAKAFAIAHQAIAIAFALIgYAAQgDgFgEgDQgEgCgFgDQgFgCgHAAQgLABgIAFQgJAFgFAIQgEAJAAAKQAAAKAEAJQAGAJAIAFQAIAFALABQAIAAAHgEQAHgDAFgHIAYAAQgFAKgHAHQgIAIgKAEQgJAEgMAAQgPAAgLgGgAH7ihIAAgrIAAAAIgdArIgZAAIAfgqQgJgBgHgEQgGgEgEgIQgEgGAAgLIACgKQAAgFAFgGQAEgHAJgDQAIgFAOAAIAgAAIAABwgAHjj6QgFACgBAEQgCAEAAAEQAAAEACAEQABADAFADQAEADAIgBIAMAAIAAghIgMAAQgIAAgEADgAGoihIgLgdIgpAAIgMAdIgWAAIAuhwIAQAAIAvBwgAGVjSIgMggIgNAgIAZAAgAE1ihIgigxIAAAxIgVAAIAAhwIAVAAIAAAxIAigxIAZAAIgqA3IAqA5gABhihIAAgvIgpAAIAAAvIgUAAIAAhwIAUAAIAAAtIApAAIAAgtIAVAAIAABwgAgEihIAAgrIgBAAIgdArIgYAAIAfgqQgKgBgGgEQgHgEgDgIQgEgGgBgLIACgKQABgFAEgGQAFgHAIgDQAJgFANAAIAgAAIAABwgAgdj6QgEACgCAEQgCAEAAAEQAAAEACAEQACADAEADQAEADAIgBIANAAIAAghIgNAAQgIAAgEADgAiNihIAAhwIAWAAIAAArIAPAAQAOAAAJAGQAHAFAEAHQADAIAAAJQAAAKgEAIQgFAHgIAEQgJAFgLAAgAh3i2IAQAAQAHABAFgEQAEgEAAgGQAAgIgEgDQgFgEgHAAIgQAAgAiuihIgfhTIgeBTIgXAAIAshwIASAAIAsBwgAkaihIgMgdIgoAAIgMAdIgWAAIAthwIARAAIAuBwgAkujSIgMggIgMAgIAYAAgAmUihIAAhcIgVAAIAAgUIA9AAIAAAUIgUAAIAABcgAnJihIAAhOIgxBOIgVAAIAAhwIAVAAIAABPIAxhPIAVAAIAABwg");
	this.shape.setTransform(1.75,0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-57.6,-32.9,115.30000000000001,65.8), null);


(lib.pic5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._5();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic5, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._3();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic3, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._2();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic2, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic1, new cjs.Rectangle(-120,-100,160,190), null);


(lib.legal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("ALiB9IgGgDIgDgFIgDgGIAEgBIABAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAEAGIADACIAGABIAFgBIAEgCIACgEIABgEIgBgEIgCgDIgFgCIgIgBIAAgFIALgDIADgEIABgEIgBgEIgDgDQAAAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIgDAAIgFAAIgDACIgCADIgBADIgCACIgDAAIgDAAIACgIIAEgFIAGgDIAHgBIAGABIAGADIAEAFIABAGIAAAFIgFAHIgFABQAGACACADQADAEAAAFQAAAFgBACQgBACgEAEQgDADgDAAIgHABgAK0B+IgFgBIgHgFIADgDIACgBIACABIACABIAEABIAEABIAGgBIADgDIACgEIACgGIAAgEIgDgEIgEgCIgGgBIgJABIgEgBIAEgbIAbAAIAAADIgBADQAAAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgSAAIgCAOIAIgBQAFAAADACQADABADADQADACAAADQABADAAAEIgBAIQgBADgDAEQgEADgDABQgEABgFAAgAJVB9QgDgBgEgFQgDgFAAgEQgCgGAAgHQAAgIACgFQAAgFADgFQAGgFABAAQAEgCAEAAIAJACQADABAEAEQADADABAHQACAFAAAIQAAAHgCAGQgBAGgDADQgDADgEADIgJABQgEAAgEgBgAJZBKIgEAFIgDAHIAAAWIADAHIAEAEIAEABIAGgBIAEgEIACgHIACgLIgCgLQAAgEgCgDIgEgFIgGgBgAH4B9QgEgCgDgEQgDgEgCgFQgBgGAAgHQAAgIABgFQACgFADgFQAEgEADgBQADgCAFAAQAFAAAEACQADABADAEQADAFACAFIABANIgBANQgCAFgDAEQgCAEgEACQgEABgFAAQgFAAgDgBgAH7BKIgEAFQgCADgBAEIgBALIABALQABADACAEIAEAEIAFABIAFgBQAEgCABgCIADgHIAAgLIAAgLIgDgHIgFgFIgFgBgAHKB9QgEgBgDgDIgEgGQgBgEAAgFIABgIIAGgJIAPgTIACgCIACAAIAHAAIgRAVIgCACIgBACIAEgCIAGgBIAFABQAEABACADIAEAFIABAHIgBAIIgEAGQgDADgEABQgDABgFAAQgEAAgDgBgAHNBhIgEACIgDAEIgBAFIABAFIACAEIAFACIAEABIAFgBIAEgCIADgEIABgFIgBgFIgDgEIgEgCIgFgBgADfB9QgEgDgCgDQgDgDgCgGQgCgGAAgHQAAgIACgFQACgHADgDQADgEADgBQAEgCAEAAIAIACQADABAEAEQADADACAHQACAFAAAIQAAAHgCAGQgCAGgDADQgCAEgFACIgIABIgIgBgADjBKIgFAFQgCADgBAEQAAADgBAIQABAIAAADQABADACAEIAFAEIAEABIAFgBIAEgEQACgCABgFQABgDAAgIQAAgIgBgDQgBgGgCgBIgEgFIgFgBgAg4B8IgKgGQgEgFgBgEQgDgHAAgFQAAgFADgHQABgFAEgEQAEgEAGgDQAGgCAGAAQAEAAAHACQAGADADAEQAEAEACAFQACAEAAAIQAAAHgCAFQgBAEgFAFQgEAFgFABQgFACgGAAQgIAAgEgCgAg0BMQgDABgEADQgDADgBAEQgCAFAAAFQAAAFACAEQAAAEAEADQAEAEADABIAIABIAIgBIAGgFIAFgHIABgJIgBgKIgFgHIgGgEIgIgCgAiBB+IgEgBIgEgDIgDgCIACgDIADgBIACABIACABIADABIAFABIAFgBIAEgDIACgEIABgGIAAgEIgCgEIgEgCIgGgBIgJABIgFgBIAFgbIAbAAIAAADIAAADQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgRAAIgEAOIAIgBQAFAAAEACQACABAEADQADACAAADIABAHIgBAIQgBADgDAEQgEADgDABQgEABgEAAgAjeB9QgFgCgDgEQgCgDgBgGQgCgGgBgHQABgIACgFQABgHACgDQAFgEADgBQACgCAGAAIAIACQADABADAEQADADACAHQACAFgBAIQABAHgCAGQgCAGgDADQgCADgEADIgIABQgGAAgCgBgAjcBKIgEAFIgDAHIAAAWIADAHIAEAEIAGABIAEgBIAFgEQACgEAAgDQABgDAAgIQAAgIgBgDQAAgEgCgDIgFgFIgEgBgAlrB+IgEgBIgEgDIgDgCIACgDIADgBIACABIACABIADABIAFABIAFgBIAEgDIACgEIABgGIAAgEIgCgEIgEgCIgGgBIgJABIgFgBIAFgbIAbAAIAAADIAAADQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgSAAIgDAOIAIgBQAFAAAEACQACABAEADQADACAAADIABAHQAAAFgCADQAAADgDAEQgEADgDABQgEABgEAAgAnIB9QgEgBgEgFQgDgFAAgEQgCgGgBgHQABgIACgFQAAgFADgFQAFgFADAAQADgCAFAAIAIACQADABADAEQADADACAHQACAFgBAIQABAHgCAGQgCAGgDADQgCADgEADIgIABQgFAAgDgBgAnFBKIgFAFIgDAHIAAAWIADAHIAFAEIAFABIAEgBIAFgEQACgEAAgDIABgLIgBgLQAAgEgCgDIgFgFIgEgBgAKTB+IAAgPIgaAAIgBgBIgBgBIgBgEIAcglIAIAAIAAAkIAIAAIAAAGIgCABIgGAAIAAAPgAJ/BoIAUAAIAAgZIAAgCgAIhB+IAYgvIACgEIgdAAIgBgBIgBgBIAAgFIAnAAIAAAFIgBACIgXAwIgCACIgDABgAGWB+IATgaIABgBIgFACIgFABIgHgBIgFgDIgEgGIgBgHIABgGIAFgHIAGgDQADgCAEAAQAFAAADACQADAAADADQACACABAFQACADAAAEIgCAJIgSAdIgCABIgCABgAGeBKIgEADIgCADIgBAFQAAAFACADQAEADAFAAIAFgBIAEgCIACgEIABgEIgCgFIgCgDIgDgDIgFgBgAFlB+IAZgvIACgEIgeAAIgBgBIAAgBIAAgFIAmAAIAAAFIAAACIgXAwIgCACIgDABgAE3B+IAYgvIACgEIgdAAIgBgBIgBgBIAAgFIAnAAIAAAFIAAACIgYAwIgCACIgCABgAEcB+IAAgPIgaAAIgBgBIgBgBIgBgEIAcglIAIAAIAAAkIAJAAIAAAFIgBABIgBABIgHAAIAAAPgAEIBoIAUAAIAAgZIAAgCgACrB+IAAgGIAMAAIAAgnIAAgDIgKAIIgBABIgBAAIgBgBIgDgDIASgPIAGAAIAAA0IALAAIAAAGgAB9B+IAAgbIgfAAIAAAbIgIAAIAAg6IAIAAIAAAaIAfAAIAAgaIAJAAIAAA6gAAmB+IAAg6IARAAQAGAAAEABQAEABADADIADAGIABAHIgBAIIgEAFQgDADgDABQgEABgGAAIgJAAIAAAWgAAuBiIAOgBIAFgDIACgDIABgFIgBgFIgCgEIgEgCIgPgBgAgFB+IAAg6IAjAAIAAAGIgcAAIAAA0gAi1B+IAAgGIANAAIAAgqIgKAIIgBABIgDAAIgBgBIgCgDIARgPIAHAAIAAA0IALAAIAAAGgAkZB+IAAgDIAAgCIABgBIAWgXIAHgJIAAgEIgBgFQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgEgCIgDAAIgFAAIgCACIgCADIgCADIgCACIgCAAIgEAAIADgIIADgFIAHgDIAGgBIAHABQADABADADQADACAAADIACAGIgBAGIgDAGIgDAEIgUAUIAGgBIATAAIACABIABACIAAAFgAlBB+IAAgGIAMAAIAAgqIgKAIIgBABIgCAAIAAgBIgCgDIAQgPIAGAAIAAA0IAMAAIAAAGgAmLB+IAAgPIgaAAIgBgBIgBgBIgCgEIAdglIAGAAIAAAkIAJAAIAAAGIgCABIgHAAIAAAPgAmgBoIAVAAIAAgbgAn9B+IAYgvIACgEIgdAAIgBgBIgCgBIAAgFIAoAAIAAAFIAAACIgZAwIgBACIgDABgAosB+IAYgvIADgEIgfAAIgBgBIAAgBIAAgFIAnAAIAAAFIgZA0IgEABgApZB+IAAgbIgfAAIAAAbIgJAAIAAg6IAJAAIAAAaIAfAAIAAgaIAIAAIAAA6gAqXB+IAAgbIgeAAIAAAbIgJAAIAAg6IAJAAIAAAaIAeAAIAAgaIAIAAIAAA6gArVB+IAAgpIAAgEIAAgEIgBAEIgcAqIgCACIgCABIgGAAIAAg6IAIAAIAAAwIACgDIAdgsIACgBIAGAAIAAA6gAhCAoIAAgOIg3AAIAAgoIAHAAIAAAiIARAAIAAgiIAHAAIAAAiIAQAAIAAgiIAIAAIAAAiIAHAAIAAASIAAABIgBABgAj5AoIAAgOIghAAIAAAMIgBABIgCABIgEAAIAAgUIACAAIACAAQAAAAABAAQAAgBABAAQAAAAAAAAQABgBAAAAIADgEIABgGIADgWIAaAAIAAAiIAIAAIAAASIgBABIgBABgAkQAKIgCAGIgCAEIAUAAIAAgcIgMAAgAnHAoIAAg2IAGAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAAAIABAFQACgDAEgCQADgCAEAAQAFAAACACIAFAEIADAGIABAIIgBAIIgDAHIgHAFQgDACgEAAIgGgCIgFgDIAAASgAm6gHIgFAFIAAASIAEAEIAFABQAGAAADgEQADgFAAgHIgBgGIgCgEIgDgDIgEgBQgEAAgCACgAGnAnIAAgOIgiAAIAAALIAAACIgCABIgFAAIAAgUIABAAIADgBIADgBIACgEIACgHIADgVIAaAAIAAAiIAHAAIAAARIgBACIgBABgAGPAJIgBAGIgCAEIATAAIAAgcIgNAAgAFkAjIAAAAIAAgBIACgCIAEgGIgBAAIgCgBIgCgBIgBgBIAAgCIABgEIAEgBIACAAIABACIACACIAAACIgBAEIgDAIIgEADgAAwAZQgCgBgEgDIgEgHIAAgJIAAgHIAEgHIAGgEIAIgCQAGAAADACIAGAEIgDADIgBAAIgCAAIgBgBIgDgBIgEgBIgFABIgEADIgCAFIgBAFIABAHIACAFIAEADIAFABIAHgCIABgCIACAAIABAAIADADIgEADIgHADIgEABQgEAAgEgCgAieAZQgDgBgEgDIgDgHIgBgJIABgHIADgHQACgCAFgCIAIgCIAIACQAEABADADIADAHIABAHIgBAJIgDAHQgEADgDABQgDACgFAAQgEAAgEgCgAifgFQgCAEAAAGQAAAIACAEQADADAGAAQAGAAADgDQADgFAAgHQAAgFgDgFQgDgEgGAAQgGAAgDAEgAk5AaIgIgDIgDgDIACgDIABAAIACAAIACACIADABIAEABIAEgBIADgBIACgDIAAgDQAAgDgCgBQgCgCgFAAIgFAAIAAgFIAFAAQAEAAACgCQADgBAAgCIgBgCIgBgCIgDgBIgEgBIgDABIgGACIgBAAIgBAAIgCgEIAFgDQACgCAGAAIAHABIAFACIADAEIABAEIAAADIgCABIgCACIgEACQADABADADQACACAAAEIAAAFIgEAEIgLAEgAliAZQgDgBgDgDQgDgCgCgFIgBgJIABgHIAFgHIAFgEIAIgCQAFAAADACQADAAACADIAEAGIAAAHIAAACIgBABIgbAAIABAGIACAFIAFADIAEAAIAFAAIADgBIADgCIACAAIABAAIACADIgDADIgIADIgFABQgEAAgEgCgAligGQgDACgBAFIAWAAIgBgDIgCgEIgDgCIgFgBQgEAAgDADgAmQAZQgDgBgDgDQgDgEgBgDQgCgEABgFIABgHQABgDADgEQACgDAEgBIAIgCIAIACQAEABADADQADAEAAADIACAHQAAAFgCAEQAAADgDAEQgEADgDABQgDACgFAAQgDAAgFgCgAmRgFQgCAFAAAFQAAAHACAFQADADAGAAQAFAAAEgDQADgFAAgHQAAgFgDgFQgEgEgFAAQgGAAgDAEgAFSAaIAAgcIABgCIgBACIgBABIgBABIgSAYIgBABIgCABIgFAAIAAgoIAIAAIAAAeIACgEIATgYIABgBIACgBIAEAAIAAAogADoAaIAAgFIAUgTIAIgIIABgEIABgFIgBgFQAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgEgBIgFABQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIgCADIgCADQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgCAAIgDAAIABgIIAEgFIAHgDIAHgBIAHABQADABABADIAFAFIABAGIgBAHIgDAFQgCADgCABIgTAUIAGgBIATAAIACAAIABACIAAAFgADCAaIAAgeIAAACIgBABIgBABIgSAYIgBABIgBABIgFAAIAAgoIAHAAIAAAcIAAACIABgDIACgBIACgDIADgEIAMgRIACgBIACgBIAEAAIAAAogACUAaIAAgeIgBACIAAABIgBABIgSAYIgDACIgFAAIAAgoIAIAAIAAAeIABgDIABgBIASgYIABgBIACgBIAEAAIAAAogABtAaIgEgBIgCgCIgKgPIgCAAIgFAAIAAASIgIAAIAAgoIAIAAIAAAQIAEAAIADAAIABgCIAJgMIABgBIADgBIAGAAIgNARIgCACIADABIAMAUgAAVAaIAAgTIgTAAIAAATIgHAAIAAgoIAHAAIAAAPIATAAIAAgPIAHAAIAAAogAgYAaIAAgcIAAgCIgBADIgBABIgCACIgEAEIgMASIgBABIgCABIgEAAIAAgoIAHAAIAAAeIABgDIABgBIASgYIACgBIABgBIAFAAIAAAogAjVAaIAAg5IASAAQAGAAAEABQAFACACACIAEAGIABAHIgBAIQgDAEgCABQgCACgEABQgEACgGAAIgJAAIAAAVgAjMgBIAPgBIAEgDIACgDIACgFIgCgFIgCgDIgDgDIgQAAgAnbAaIAAgyIgcAAIAAAyIgJAAIAAg5IAuAAIAAA5gAHmAYQgDAAgDgDQgEgDAAgCQgCgDAAgEQAAgFADgEQADgDAGgCQgFAAgCgEQgCgDAAgFIABgHIADgEIAGgEIAHgBIAHABIAGAEIADAEIACAHQgBAFgCADQgDAEgDAAQAFACACADQAEADAAAGIgBAHQgCAEgDABQgCACgEABIgIABgAHpgBIgDACIgDACIgBAGIABAEIACADIAEACIAFABIAFgBIAEgCIACgDIABgEIgBgGIgCgCIgFgCIgEAAgAHqgaIgDACIgCADIgBAEIABADQAAABAAAAQAAAAAAABQAAAAABAAQAAABABAAIACADIAFAAIAEAAIAEgDIACgDIAAgDIAAgEIgDgDIgDgCIgEgBgAG2AZIgBgBIgCgCIAAgEIACgCIABgBIAFAAIABABIABACIABACIgBACIgBACIgBABIgCAAgAEYAFIAAgGIAUAAIAAAGgAFEgUIgEgDIgDgCIAAgEIAAgBIABgBIAFAAIAAADIACADIABABIAGAAIACgBIABgGIAEAAIACABIAAABIgBAEIgDACIgDADIgFAAgAC0gUIgGgFIgBgEIAAgBIABgBIAFAAIAAADIACADIABABIAGAAIACgBIABgDIAAgDIAEAAIACABIAAABIgBAEQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAgBAAIgDADIgFAAgAkbg1IAAgNIguAAIAAALIAAACIgCAAIgFAAIAAgUIAGAAQAAAAAAAAQABAAAAgBQAAAAABAAQAAgBAAAAIADgEIACgHIACgJIACgeIAjAAIAAA0IAJAAIAAASIgBACIgBAAgAk4hlIgFAWIgEAGIAcAAIAAgtIgTAAgALqg5IAAAAIgBgBIACgBIAAgBIACgCIABgCIAAgCIAAAAIgCgBIgBgBIgCgCIAAgCIACgDIADgBIACAAIACABIABACIAAACIAAAFIgCADIgFAHgAFlg5IAAgBIABgBIAEgFIAAgCIgCgBIgBgBIgCgCIgBgCIADgDQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIACAAIACABIABAEIgBAFIgEAHIgDADgALGhCIgEgDIgCgDIgBgFIABgEIAFgFIAHgCIANgCIAAgDQAAgDgDgEQgCgCgDAAIgFAAIgHAEIgCAAIgBgBIgBgDQADgDAFgCIAJgBIAGABIAEADIADAFIABAGIAAAbIgEAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIgBgBIgBgEIgEADIgGADIgFAAgALQhUIgGABIgDADIAAADIAAACIACACIABABIADABIAEgBIACgBIAGgEIAAgIgAJShEQgCAAgEgEIgDgGQgCgDAAgGQAAgGACgCIADgHIAGgFIAIgBIAJABIAFAEIgCADIgBABIgCAAIgCgBIgCgCIgEAAIgGABIgDADQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAIgCAHIACAGIACAFIADADIAFABIAFgBIACgBIADgBIABgBIACABIABADIgDADIgIADIgEAAQgEAAgDgCgAIlhEQgEAAgDgEQgCgCgBgFQgCgDAAgFIACgJQABgEACgCQACgDAFgCIAIgBIAIABQAEACACADIAEAGQABADABAGQgBAGgBACQgBAFgDACQgEAEgCAAQgDACgFAAQgFAAgDgCgAIkhiQgDADAAAIQAAAIADADQADAEAGAAQAGAAADgEQADgEAAgHQAAgHgDgEQgDgEgGAAQgHAAgCAEgAGshCIgCgCIgBgBIAAgCIABgEIACgBIAEAAIACABIABACIAAAEIgBABIgCACIgCAAgAC1hCIgIgEIgDgCIADgEIABAAIAFABQAAABAAAAQABAAAAAAQABABAAAAQAAAAABAAIAEABIAGgBIAEgDIADgEIABgGIgBgFIgDgDIgEgCIgGgCQgDAAgGACIgEgBIAEgcIAcAAIAAAEIgBADIgDABIgTAAIgBAOIAIgBQAEAAAEACQADAAACADQADADABADIABAHQAAAFgCADQAAADgEADQgFAEgCAAQgDACgFAAgAAEhCIgBgCIgBgDIABgEIABgBIAFAAIACABIAAACIABACIgBACIAAABIgCACIgCAAgAgxhCIgCgCIAAgBIgBgCIABgCIAAgCIACgBIAFAAIABABIABACIAAAEIgCADIgDAAgAiChCIgCgDIAAgCIAAgCIABgCIABgBIAFAAIABABIABACIAAACIAAACIgCADIgDAAgAiqhEQgFgBgEgFQgFgEgBgGQgCgFAAgGQAAgHACgFIAGgKQADgDAGgDQAHgCAEAAQAGAAAFACQAFACADADIgCAEIgBABIgBAAIgCgBIgCgBIgFgCIgGgBIgIABIgGAFQgCACgCAFQgCAFAAAFQAAAFACAEQACAFACACQACACAEACQACACAGAAIAEAAIAHgDIAEgCIABgBIABAAIADAEQgDAEgFADQgFACgHAAQgHAAgEgCgApfhEQgEgBgFgFQgFgGgBgEQgCgHAAgEQAAgFACgHQACgGAEgEQADgDAGgDQAHgCAEAAQAFAAAIACQAGADADADQADADACAHQADAEAAAIQAAAHgDAEQgBAGgEAEQgFAFgEABQgGACgHAAQgGAAgFgCgApbh1IgHAFIgEAHIgCAKQABAFABAEQABADADAEQAEADADABIAHACIAJgCIAGgEQADgCACgFIABgJIgBgKIgFgHIgGgFIgJgBgAqghEQgEgCgFgEQgEgGgCgEQgCgEAAgHQAAgIACgEQACgGAEgEQACgDAHgDQAHgCAFAAQAEAAAIACQAGADADADQAEAEABAGQADAHAAAFQAAAEgDAHQgBAEgEAGQgEAEgFACQgFACgHAAQgHAAgFgCgAqch1IgHAFIgEAHIgBAKIABAJQACAFACACIAHAEIAIACIAIgCQADgBAEgDQADgEAAgDQACgEAAgFIgCgKQgBgEgCgDIgHgFIgIgBgArghEQgFgBgEgFQgFgEgBgGQgDgEABgHQgBgIADgEQADgHADgDQACgDAHgDQAHgCAEAAQAFAAAHACQAGADADADQACADAEAHQACAFgBAHQABAGgCAFIgGAKQgGAFgDABQgEACgIAAQgGAAgFgCgArdh1IgHAFIgEAHIAAAKIAAAJQACAFACACIAHAEIAIACIAIgCIAHgEQADgEABgDQABgEAAgFIgBgKQgBgEgDgDIgHgFIgIgBgAKahCIAAgpIAVAAIAFACIADADIAAAEIAAADIgBADIgCACIgFACQAFABADACQADACgBAEIgBAGQAAACgDACIgFACIgGABgAKhhIIAJAAQACAAAEgCQACgCAAgDIAAgCIgCgCIgCgBIgEgBIgJAAgAKhhaIAIAAIADgBIACgBQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIAAgCIAAgDIgBgBIgCgCIgEAAIgIAAgAKOhCIgDgBIgCgCIgHgMQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAIgEgBIgDAAIAAATIgIAAIAAgpIAIAAIAAARIADAAIADgBIADgBIAIgOIABgBIACAAIAGAAIgMARIgDACIAEABIACADIALASgAIJhCIAAgsIAAgCIgUAjIgBACIgCAAIgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgVgkIAAAvIgGAAIAAg7IAFAAIACABIABABIAWAnIAAgCIAUglIACgBIACgBIAGAAIAAA7gAGNhCIAAgpIAbAAIAAAFIgTAAIAAAkgAE9hCIATgcIgEADIgGABIgGgBIgFgEIgEgFIgBgHIABgHIAEgGIAGgEQAEgBAEAAQAEAAAEABIAGAEIADAGIABAIIAAAEIgDAJIgRAZIgDACgAFFh2QgBAAgBABQAAAAgBAAQAAABgBAAQAAAAAAABIgDADIgBAFQABAFACADQAEADAEAAIAGgBIADgCIACgEIACgEIgCgFIgCgDIgDgDIgFgBgAENhCIAAgGIAMAAIAAgqIgJAIIgBAAIgCAAIgBAAIgDgEIASgPIAGAAIAAA1IALAAIAAAGgADyhCIAAgPIgaAAIgBgBIgBgBIgBgEIAcgmIAHAAIAAAlIAJAAIAAAFIgBABIgBABIgHAAIAAAPgADdhYIAVAAIAAgZIAAgCgACAhCIAAgGIANAAIAAgqIgKAIIgCAAIgBAAIAAAAIgDgEIASgPIAFAAIAAA1IALAAIAAAGgABShCIAAgGIAMAAIAAgqIgKAIIgBAAIgBAAIgBAAIgDgEIARgPIAHAAIAAA1IALAAIAAAGgAgehCIAAg7IAiAAIAAAHIgaAAIAAA0gAhHhCIAAgbIgfAAIAAAbIgJAAIAAg7IAJAAIAAAaIAfAAIAAgaIAIAAIAAA7gAjjhCIAAgxIgBAEIgdArIgCACIgHAAIAAg7IAJAAIAAApIgBAEIAAAEIABgEIAcgqIACgCIACgBIAGAAIAAA7gAlghCIAAgbIgfAAIAAAbIgJAAIAAg7IAJAAIAAAaIAfAAIAAgaIAIAAIAAA7gAmUhCQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgBgCIgFgNIgZAAIgGANIgBACIgCABIgGAAIAXg7IAJAAIAWA7gAmrhxIgKAZIAWAAIgIgXIgCgCIgBgEgAnNhCIgDgBIgBgCIgPgVIgCgCIgDgBIgHAAIAAAbIgJAAIAAg7IAJAAIAAAaIAIAAIACgBIAQgWIACgCIABgBIAHAAIgQAYQgDADgCABIADACIAUAdgAAjhJIgCgCIABgBIAGgLIABgBIAAAAIgBgCIgGgKIgBgCIACgBIADgBIAJAQIAAAAIgJAQgAAWhJIgBgCIABgBIAHgLIABgBIgBAAIAAgCIgHgKIgBgCIABgBIAEgBIAJAQIAAAAIgJAQgAoPhYIAAAAIAKgQIAEABIABABIgBACIgHAMIABABIAGALIABABIgBACIgEABgAoahYIAAAAIAKgQIACABIABABIAAACIgIAMIACABIAGALIAAABIgBACIgCABg");
	this.shape.setTransform(-0.7,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal, new cjs.Rectangle(-79.6,-17.9,157.2,34.7), null);


(lib.butt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYAvIAAhdIAxAAIAAARIggAAIAAAWIAfAAIAAAPIgfAAIAAAWIAgAAIAAARg");
	this.shape.setTransform(47.0311,0.8162,1.3333,1.3333);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAvIAAhdIAxAAIAAARIggAAIAAAWIAfAAIAAAPIgfAAIAAAWIAgAAIAAARg");
	this.shape_1.setTransform(38.1978,0.8162,1.3333,1.3333);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARAvIAAgoIghAAIAAAoIgSAAIAAhdIASAAIAAAmIAhAAIAAgmIASAAIAABdg");
	this.shape_2.setTransform(27.9645,0.8162,1.3333,1.3333);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfAvIAAhdIA2AAIAAARIgkAAIAAATIAOAAQATAAAIAMQAEAHAAAJQAAANgJAIQgIAIgOAAgAgNAeIAOAAQAGAAAEgEQAEgDAAgFQAAgFgDgCQgEgFgHAAIgOAAg");
	this.shape_3.setTransform(17.3979,0.8162,1.3333,1.3333);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiAjQgPgOAAgVQAAgTAPgOQAOgPAUAAQAVAAAPAPQANAOAAATQAAAVgNAOQgPAOgVAAQgUAAgOgOgAgWgWQgJAKAAAMQAAANAJAKQAJAJANAAQANAAAKgJQAKgKgBgNQABgMgKgKQgJgJgOAAQgNAAgJAJg");
	this.shape_4.setTransform(4.8979,0.8495,1.3333,1.3333);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdAvIAAhdIAaAAQASAAAKAMQAFAHAAALQAAALgHAHQgIAKgSgBIgJAAIAAAkgAgMgFIALAAQAOAAgBgMQABgMgOAAIgLAAg");
	this.shape_5.setTransform(-6.502,0.8162,1.3333,1.3333);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAiA4IAAgSIhDAAIAAASIgRAAIAAgjIAJAAIAihMIAPAAIAiBMIAJAAIAAAjgAgWAVIAtAAIgXg0g");
	this.shape_6.setTransform(-18.602,1.9829,1.3333,1.3333);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgiAjQgPgOAAgVQAAgTAPgOQAOgPAUAAQAVAAAOAPQAOAOABATQgBAVgOAOQgOAOgVAAQgUAAgOgOgAgWgWQgJAKAAAMQAAANAJAKQAKAJAMAAQAOAAAJgJQAKgKgBgNQAAgMgJgKQgJgJgOAAQgMAAgKAJg");
	this.shape_7.setTransform(-32.7019,0.8495,1.3333,1.3333);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AARAvIAAhMIghAAIAABMIgSAAIAAhdIBEAAIAABdg");
	this.shape_8.setTransform(-45.5686,0.8162,1.3333,1.3333);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7E0").s().p("An6CDIAAkFIP1AAIAAEFg");
	this.shape_9.setTransform(0.0313,-0.0505,1.3333,1.3333);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.butt, new cjs.Rectangle(-67.5,-17.4,135.1,34.9), null);


// stage content:
(lib._160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(219));

	// t5
	this.instance = new lib.t5();
	this.instance.parent = this;
	this.instance.setTransform(79.7,404.15,0.7663,0.7662,0,0,0,0.2,0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(159).to({_off:false},0).to({regX:0.1,scaleX:0.9578,scaleY:0.9578,y:404.2,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.2,scaleX:0.7663,scaleY:0.7662,y:404.15,alpha:0},6,cjs.Ease.get(1)).wait(1));

	// t3
	this.instance_1 = new lib.t3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(79.7,404.15,0.7663,0.7662,0,0,0,0.2,0.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(106).to({_off:false},0).to({regX:0.1,regY:0,scaleX:0.9578,scaleY:0.9578,y:404.1,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.2,regY:0.1,scaleX:0.7663,scaleY:0.7662,y:404.15,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(53));

	// t2
	this.instance_2 = new lib.t2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(79.7,404.15,0.7663,0.7662,0,0,0,0.2,0.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(53).to({_off:false},0).to({regX:0.1,regY:0,scaleX:0.9578,scaleY:0.9578,y:404.1,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.2,regY:0.1,scaleX:0.7663,scaleY:0.7662,y:404.15,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(106));

	// t1
	this.instance_3 = new lib.t1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(79.65,405.6,0.7663,0.7662,0,0,0,0.1,0.1);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({regX:0,regY:0,scaleX:0.9578,scaleY:0.9578,x:79.6,y:404.1,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.1,regY:0.1,scaleX:0.7663,scaleY:0.7662,x:79.65,y:404.15,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(159));

	// 5.jpg
	this.instance_4 = new lib.pic5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(120,245);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(159).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).wait(1));

	// 3.jpg
	this.instance_5 = new lib.pic3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(120,245);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(106).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(53));

	// 2.jpg
	this.instance_6 = new lib.pic2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(120,245);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(53).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(106));

	// 1.jpg
	this.instance_7 = new lib.pic1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(120,245);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(159));

	// Слой 3
	this.instance_8 = new lib.butt();
	this.instance_8.parent = this;
	this.instance_8.setTransform(80.5,482.9);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(159).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).wait(1));

	// fon
	this.instance_9 = new lib.legal();
	this.instance_9.parent = this;
	this.instance_9.setTransform(81.4,562.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00A7E0").s().p("ApDBSQgqgmAZg3QAWgzBFgdQBNggB9AAQAcAAAZADIAhAEIANADIgSAgQgngKghAAQhAAAgzASQhHAZgKAyQgHAdAWAbQAcAiA8gDQAUgBAkgMQAtgQAagVIBAg3IAMgHQAIgDAKAAIBEAAIAWBcIAqhcIBLAAIArBHIAghHIBFAAIg9CDIhGAAIgthMIghBMIgsAAIAAAAIhRAAIgDgXIhKAAIgYAWIgwAAQg5AUhJAAQhpAAgugqgAjGA3IAsAAIgEglgAGFB1IAsgsIgshjIBDAAIATA1IA3g1IBNAAIiFCEQgGAGgFACIgQADgAD9BpIhuAAIA8iDIBuAAQA2AAATAaQAQATgMAaQgLAYgdAQQgkAUg6AAIgDAAgADoBIIATAAQAXAAARgGQAcgIAGgVQAIgfg1AAIgTAAg");
	this.shape_1.setTransform(84.8487,73.0496);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.instance_9}]}).wait(219));

	// bg
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	this.shape_2.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(219));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(79.5,299.5,81,301);
// library properties:
lib.properties = {
	id: 'E2D568E3DB4C37498E3AB62754AAC479',
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/160x600_atlas_.jpg", id:"160x600_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E2D568E3DB4C37498E3AB62754AAC479'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;