(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [
		{name:"300x600_atlas_P_", frames: [[0,0,302,153],[304,0,46,45]]},
		{name:"300x600_atlas_NP_", frames: [[0,0,300,520],[302,0,300,520]]}
];


// symbols:



(lib._1Ресурс5 = function() {
	this.spriteSheet = ss["300x600_atlas_P_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._1Ресурс6 = function() {
	this.spriteSheet = ss["300x600_atlas_P_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._1 = function() {
	this.spriteSheet = ss["300x600_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["300x600_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhABGQgcgdAAgpQAAgoAcgdQAdgdApAAQAcAAAYAQQAXAPAMAbIgoAAQgJgLgMgGQgMgGgOAAQgcAAgRATQgSATAAAZQAAAbASATQATATAaAAQANAAAMgGQAMgFAJgLIAoAAQgMAagXAPQgWAPgeAAQgpAAgcgdg");
	this.shape.setTransform(74.9,18.3,0.78,0.78);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA2BfIgTgxIhFAAIgTAxIgnAAIBPi9IAbAAIBPC9gAgVAMIArAAIgWg3g");
	this.shape_1.setTransform(60.1,18.2,0.78,0.78);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAeBfIAAhIIgfAAQgQAAgMgDQgLgDgHgGQgJgHgEgKQgEgKAAgRIAAg9IAjAAIAAA4QAAAKABAEQADAGADACQADADAFACIAsABIAAhUIAjAAIAAC9g");
	this.shape_2.setTransform(46.3,18.2,0.78,0.78);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAqB2IAAiEIhTCEIgjAAIAAi9IAjAAIAACEIBTiEIAjAAIAAC9gAgehbQgMgKgDgQIAdAAQABAGAFAEQAEADAGAAQAHAAAEgDQAEgEACgGIAdAAQgDAQgMAKQgNAKgSAAQgSAAgMgKg");
	this.shape_3.setTransform(33,16.4,0.78,0.78);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgyBfIAAi9IBlAAIAAAiIhCAAIAAAsIA/AAIAAAhIg/AAIAAAsIBCAAIAAAig");
	this.shape_4.setTransform(20.5,18.2,0.78,0.78);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhABGQgcgcAAgqQAAgoAcgdQAdgdAoAAQAdAAAYAQQAYAPALAbIgoAAQgJgLgMgGQgMgGgOAAQgcAAgRATQgSATAAAZQAAAbASATQATATAaAAQANAAAMgGQAMgFAJgLIAoAAQgMAagXAPQgWAPgeAAQgpAAgcgdg");
	this.shape_5.setTransform(7.5,18.3,0.78,0.78);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhGBGQgdgcAAgqQAAgnAdgeQAegdAoAAQApAAAeAdQAdAeAAAnQAAAqgdAcQgdAdgqAAQgpAAgdgdgAgtgtQgTAUAAAZQAAAaATAUQATATAaAAQAbAAATgTQATgTAAgbQAAgagTgTQgSgSgcAAQgbAAgSASg");
	this.shape_6.setTransform(-13.4,18.3,0.78,0.78);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABBBfIAAiNIgyCNIgdAAIgyiNIAACNIgjAAIAAi9IAvAAIA0CQIA1iQIAvAAIAAC9g");
	this.shape_7.setTransform(-30.9,18.2,0.78,0.78);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAdBfIAAhKIgBAAIgyBKIgpAAIA1hGQgXgCgOgQQgOgOAAgZQAAgcASgRQASgRAiAAIA3AAIAAC9gAgRg0QgJAHAAANQAAAPAIAGQAJAIARAAIAVAAIAAg5IgVAAQgRAAgIAIg");
	this.shape_8.setTransform(-46.4,18.2,0.78,0.78);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag7BfIAAi9IA1AAQAeAAATAQQARAQAAAbQAAAbgRAPQgQAQghAAIgSAAIAABIgAgYgKIAUAAQAOAAAHgGQAIgGAAgNQAAgMgHgGQgIgHgOAAIgUAAg");
	this.shape_9.setTransform(-57.2,18.2,0.78,0.78);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAjBfIAAibIhFAAIAACbIgjAAIAAi9ICKAAIAAC9g");
	this.shape_10.setTransform(-70,18.2,0.78,0.78);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("ApXF7IAAgUIhFAAIAAhoIATAAIAABWIAmAAIAAhWIATAAIAABWIAMAAIAAAmgAHEFiQgMgHgHgMQgIgMAAgQQAAgOAIgNQAHgMAMgHQAMgHAQgBQAPABAMAHQANAHAHAMQAHANAAAOQAAAQgHAMQgHAMgNAHQgMAIgPgBQgQABgMgIgAHNEVQgIAFgEAHQgEAIgBAKQABAKAEAIQAEAJAIAEQAJAFAJAAQALAAAIgFQAIgFAEgIQAFgIAAgKQAAgKgFgIQgEgHgIgFQgIgEgKgBQgKABgJAEgAD6FlQgKgGgHgIQgGgIgEgKQgDgJgBgJQABgJADgJQAEgJAGgJQAHgHAKgFQAKgGAOAAQAKAAAKAFQAJADAHAHQAIAHAEAKIgWAAIgGgGIgJgFQgFgCgGAAQgKABgJAEQgHAFgEAIQgFAIAAAJQAAAKAFAIQAEAIAIAFQAIAFAKAAQAHAAAHgDQAGgDAFgGIAWAAQgEAJgHAHQgGAHgKAEQgJADgMAAQgNAAgKgEgAuYFlQgKgGgHgIQgGgIgEgKQgDgJgBgJQABgJADgJQAEgJAGgJQAHgHAKgFQAKgGAOAAQAKAAAKAFQAJADAHAHQAIAHAEAKIgWAAIgGgGIgJgFQgFgCgGAAQgKABgJAEQgHAFgEAIQgFAIAAAJQAAAKAFAIQAEAIAIAFQAIAFAKAAQAHAAAHgDQAGgDAFgGIAWAAQgEAJgHAHQgHAHgJAEQgJADgMAAQgNAAgKgEgAMKFnIAAgoIAAAAIgcAoIgWAAIAdgmQgJgBgGgEQgGgEgEgHQgDgHAAgJIABgKQABgFAEgFQAEgGAIgEQAHgEAOAAIAdAAIAABogALzEVQgEACgCADQgCAEABADQgBAEACAEQACADAEADQAEABAIABIALAAIAAgfIgLAAQgIAAgEADgAK3FnIAAhJIgvBJIgTAAIAAhoIATAAIAABJIAvhJIATAAIAABogAIkFnIAAhoIAZAAIAGAAIAJACQAFACAFACQAFAEADAFQADAFAAAHQAAAHgDAEQgBAEgDACIgFAEQAJADAFAGQAEAHAAAIQAAAIgDAHQgDAHgKAFQgIAFgRAAgAI3FVIAMAAIAEgBIAFgBQADgCADgCQACgDAAgFIgBgFQgBgDgEgDQgDgCgIAAIgMAAgAI3EoIAJAAQAHgBADgCIADgEIAAgEQABgGgDgBQgCgDgEgBIgFAAIgJAAgAGTFnIgchNIgdBNIgUAAIAohoIARAAIAqBogACbFnIAMgaIgnhOIAXAAIAcA3IAXg3IAVAAIgvBogAAeFnIAAhoIA4AAIAAATIglAAIAAAYIAjAAIAAASIgjAAIAAAZIAlAAIAAASgAgGFnIAAhoIASAAIAABogAhWFnIAAhoIATAAIAAApIAQAAQAMgBAIAFQAHAFADAHQAEAIAAAHQAAAJgFAIQgEAHgHAEQgIAEgKAAgAhDFVIAQAAQAGgBAEgDQAEgDABgHQgBgGgEgEQgEgDgGAAIgQAAgAh8FnIAAgrIgmAAIAAArIgTAAIAAhoIATAAIAAAqIAmAAIAAgqIATAAIAABogAkGFnIAAhoIATAAIAAApIAPAAQAOgBAHAFQAIAFADAHQADAIAAAHQAAAJgEAIQgFAHgIAEQgHAEgLAAgAjzFVIAPAAQAHgBAFgDQADgDAAgHQAAgGgDgEQgFgDgHAAIgPAAgAkmFnIgchNIgcBNIgWAAIAqhoIARAAIAoBogAmKFnIgLgaIgnAAIgKAaIgVAAIArhoIAPAAIArBogAmcE6IgMgfIgMAfIAYAAgAn4FnIAAhJIgvBJIgTAAIAAhoIATAAIAABJIAvhJIATAAIAABogArlFnIAAhoIA3AAIAAATIgkAAIAAAYIAjAAIAAASIgjAAIAAAZIAkAAIAAASgAsLFnIAAhVIgmAAIAABVIgTAAIAAhoIBMAAIAABogAFYjKIAAgcIhrAAIAAAcIgbAAIAAg2IAPAAIA2h5IAYAAIA3B5IAOAAIAAA2gAFIkAIglhUIglBUIBKAAgAOcjmIAAhnIhCBnIgcAAIAAiTIAcAAIAABnIBChnIAbAAIAACTgALmjmIAAiTIBKAAIAAAaIguAAIAAB5gAJyjmIAAiTIAcAAIAAA4IAWAAQASAAALAHQAKAHAGALQAEAKAAALQAAAOgGAKQgHAKgKAGQgMAFgOAAgAKOkAIAWAAQAKAAAGgFQAFgFAAgJQAAgJgFgFQgGgFgKAAIgWAAgAI8jmIAAg+Ig2AAIAAA+IgcAAIAAiTIAcAAIAAA7IA2AAIAAg7IAbAAIAACTgAGDjmIAAiTIBPAAIAAAaIg0AAIAAAjIAyAAIAAAaIgyAAIAAAiIA0AAIAAAag");
	this.shape_11.setTransform(7.4,20.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4, new cjs.Rectangle(-124,-24,248.1,82.5), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkBfIAWgxIhIiMIAqAAIAxBkIAshkIAmAAIhWC9g");
	this.shape.setTransform(68.1,18.5,0.79,0.79);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABEBxIAAgkIiHAAIAAAkIgjAAIAAhGIASAAIBGiaIAdAAIBHCaIARAAIAABGgAguArIBdAAIgvhqg");
	this.shape_1.setTransform(52.7,19.9,0.79,0.79);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhGBGQgdgcAAgqQAAgnAdgeQAdgdApAAQAqAAAdAdQAdAdAAAoQAAApgdAdQgdAdgqAAQgqAAgcgdgAgtgtQgTATAAAaQAAAbATATQATATAaAAQAbAAATgTQATgUAAgaQAAgagTgTQgTgTgbAAQgaAAgTATg");
	this.shape_2.setTransform(36,18.5,0.79,0.79);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AguBfIAAi9IBdAAIAAAiIg6AAIAACbg");
	this.shape_3.setTransform(23.7,18.5,0.79,0.79);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ABBBfIAAiNIgyCNIgdAAIgyiNIAACNIgjAAIAAi9IAvAAIA0CQIA1iQIAvAAIAAC9g");
	this.shape_4.setTransform(4.6,18.5,0.79,0.79);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhGBGQgdgcAAgqQAAgoAdgdQAdgdApAAQAqAAAdAdQAdAeAAAnQAAAqgdAcQgdAdgqAAQgpAAgdgdgAgtgtQgTATAAAaQAAAbATATQATATAaAAQAbAAATgTQATgTAAgbQAAgagTgTQgTgTgbAAQgaAAgTATg");
	this.shape_5.setTransform(-13.2,18.5,0.79,0.79);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag8BfIAAi9IAtAAQAhAAAPAOQARANAAAXQAAAMgGAKQgFAJgKAFQAQAGAIALQAIAMAAAQQAAAcgTAPQgSAPglAAgAgZA9IAWAAQAOAAAHgHQAIgGAAgLQAAgLgHgHQgJgHgNAAIgWAAgAgZgVIAQAAQALAAAGgFQAHgGAAgIQAAgKgHgFQgFgFgMAAIgQAAg");
	this.shape_6.setTransform(-27.2,18.5,0.79,0.79);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhGBGQgdgcAAgqQAAgnAdgeQAdgdApAAQAqAAAdAdQAdAdAAAoQAAAqgdAcQgdAdgqAAQgpAAgdgdgAgtgtQgTATAAAaQAAAbATATQATATAaAAQAbAAATgTQATgUAAgaQAAgZgTgUQgTgTgbAAQgaAAgTATg");
	this.shape_7.setTransform(-41.9,18.5,0.79,0.79);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAiBfIAAhQIhEAAIAABQIgjAAIAAi9IAjAAIAABMIBEAAIAAhMIAjAAIAAC9g");
	this.shape_8.setTransform(-57.3,18.5,0.79,0.79);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag9BfIAAi9IAuAAQAgAAAQAOQARANAAAXQAAANgGAJQgFAJgKAFQAQAGAHALQAKAMgBAQQAAAcgTAPQgTAPgkAAgAgaA9IAYAAQANAAAHgHQAIgGAAgLQAAgLgIgHQgHgHgNAAIgYAAgAgagVIARAAQAKAAAHgFQAHgFAAgJQAAgKgHgFQgGgFgLAAIgRAAg");
	this.shape_9.setTransform(-74.3,18.5,0.79,0.79);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AGQFqQgNgHgHgMQgHgMAAgQQAAgPAHgMQAHgMANgHQAMgIAQAAQAPAAAMAIQANAHAHAMQAHAMAAAPQAAAQgHAMQgHAMgNAHQgMAHgPAAQgQAAgMgHgAGZEdQgIAEgEAIQgFAIAAAKQAAAKAFAIQAEAIAIAFQAIAFAKAAQALAAAIgFQAIgFAEgIQAFgIAAgKQAAgKgFgIQgEgIgIgEQgIgFgKAAQgLAAgIAFgAC6FqQgNgHgHgMQgHgMAAgQQAAgPAHgMQAHgMANgHQAMgIAQAAQAPAAAMAIQANAHAHAMQAHAMAAAPQAAAQgHAMQgHAMgNAHQgMAHgPAAQgQAAgMgHgADDEdQgIAEgEAIQgFAIAAAKQAAAKAFAIQAEAIAIAFQAIAFAKAAQALAAAIgFQAIgFAEgIQAFgIAAgKQAAgKgFgIQgEgIgIgEQgIgFgKAAQgLAAgIAFgAmqFqQgNgHgHgMQgHgMAAgQQAAgPAHgMQAHgMANgHQAMgIAQAAQAPAAAMAIQANAHAHAMQAHAMAAAPQAAAQgHAMQgHAMgNAHQgMAHgPAAQgQAAgMgHgAmhEdQgIAEgEAIQgFAIAAAKQAAAKAFAIQAEAIAIAFQAIAFAKAAQALAAAIgFQAIgFAEgIQAFgIAAgKQAAgKgFgIQgEgIgIgEQgIgFgKAAQgLAAgIAFgAsPFsQgKgFgHgIQgHgIgDgKQgEgJAAgJQAAgJAEgJQADgKAHgIQAHgIAKgFQAKgFAOAAQAKAAAKAEQAJAEAHAHQAHAHAFAKIgWAAIgGgHIgJgEQgFgCgGAAQgLAAgIAFQgHAFgFAIQgEAIAAAJQAAAKAEAIQAFAIAIAFQAIAFAKAAQAHAAAGgDQAHgDAFgGIAWAAQgEAJgHAHQgHAHgJADQgJAEgMAAQgNAAgKgFgALBFvIAMgbIgohNIAYAAIAbA3IAYg3IAVAAIgvBogAKIFvIAAgsIgmAAIAAAsIgTAAIAAhoIATAAIAAAqIAmAAIAAgqIATAAIAABogAIpFvIAAgsIgmAAIAAAsIgTAAIAAhoIATAAIAAAqIAmAAIAAgqIATAAIAABogAFfFvIgchNIgdBNIgVAAIAphoIARAAIApBogACKFvIghguIAAAuIgTAAIAAhoIATAAIAAAtIAhgtIAXAAIgnAzIAnA1gAgaFvIAAhoIAZAAIAFAAIAJACQAFABAFADQAFADADAFQADAFAAAIQAAAHgDAEQgCAEgDACIgEADQAJADAEAHQAFAGAAAJQAAAIgDAHQgEAHgJAFQgJAFgPAAgAgHFcIALAAIAEAAIAFgCQADgBADgCQACgDAAgFIgBgFQgBgDgEgDQgDgCgIAAIgLAAgAgHEvIAIAAQAGAAADgCIAEgFIAAgEQAAgFgCgCQgDgCgDgBIgFAAIgIAAgAhaFvIgLgbIgmAAIgLAbIgVAAIArhoIAQAAIArBogAhsFBIgMgeIgMAeIAYAAgAjGFvIggguIAAAuIgTAAIAAhoIATAAIAAAtIAggtIAXAAIgnAzIAnA1gAlKFvIAAhoIAZAAIAGAAIAJACQAFABAFADQAFADADAFQADAFAAAIQAAAHgDAEQgCAEgDACIgEADQAJADAEAHQAFAGAAAJQAAAIgDAHQgEAHgJAFQgJAFgQAAgAk3FcIAMAAIAEAAIAFgCQADgBADgCQACgDAAgFIgBgFQgBgDgEgDQgDgCgIAAIgMAAgAk3EvIAJAAQAGAAADgCIAEgFIAAgEQAAgFgCgCQgDgCgDgBIgFAAIgJAAgAnmFvIAAgsIgmAAIAAAsIgTAAIAAhoIATAAIAAAqIAmAAIAAgqIATAAIAABogAo+FvIgLgbIgmAAIgLAbIgVAAIArhoIAQAAIArBogApQFBIgMgeIgMAeIAYAAgAqxFvIAAhVIgTAAIAAgTIA5AAIAAATIgTAAIAABVgAtuFvIAMgbIgohNIAYAAIAbA3IAYg3IAVAAIgvBogAMVjgQgSgLgKgRQgKgRAAgWQAAgWAKgRQAKgSASgKQARgKAXAAQAWAAASAKQARAKAKASQALARAAAWQAAAWgLARQgKARgSALQgRAKgWAAQgXAAgRgKgAMjlPQgMAHgGALQgHALAAAOQAAAPAHALQAGAMAMAGQALAHAPAAQAOAAAMgHQALgHAHgLQAGgMAAgOQAAgOgGgLQgHgLgLgHQgMgHgOAAQgPAAgLAHgAIvjdQgPgIgJgLQgKgMgFgNQgEgOAAgNQAAgMAEgOQAFgNAKgLQAJgMAPgHQAPgHATAAQAPAAAOAFQANAFAKAKQAKAKAHAPIgfAAIgJgJQgGgFgHgCQgHgDgJAAQgPAAgLAHQgLAHgGAMQgHALAAANQAAAOAHAMQAHALALAHQALAHAPAAQAKAAAJgEQAJgEAHgJIAgAAQgGANgKAKQgKAKgNAFQgNAGgQAAQgUAAgOgHgAK2jaIAAh5IgbAAIAAgbIBSAAIAAAbIgbAAIAAB5gAGjjaIAAiUIBQAAIAAAbIg0AAIAAAiIAyAAIAAAbIgyAAIAAAiIA0AAIAAAagAFtjaIAAhvIgoBvIgXAAIgnhvIAABvIgcAAIAAiUIAmAAIApBxIAphxIAlAAIAACUg");
	this.shape_10.setTransform(6.7,19.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-116.7,-24,233.4,80.4), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkBfIAWgxIhIiMIAqAAIAxBkIAshkIAmAAIhWC9g");
	this.shape.setTransform(68.2,6.3,0.79,0.79);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABEBxIAAgkIiHAAIAAAkIgjAAIAAhGIASAAIBGiaIAdAAIBHCaIARAAIAABGgAguArIBdAAIgvhqg");
	this.shape_1.setTransform(52.8,7.7,0.79,0.79);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhGBGQgdgcAAgqQAAgnAdgeQAdgdApAAQAqAAAdAdQAdAdAAAoQAAApgdAdQgdAdgqAAQgqAAgcgdgAgtgtQgTATAAAaQAAAbATATQATATAaAAQAbAAATgTQATgUAAgaQAAgagTgTQgTgTgbAAQgaAAgTATg");
	this.shape_2.setTransform(36.1,6.4,0.79,0.79);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AguBfIAAi9IBdAAIAAAiIg6AAIAACbg");
	this.shape_3.setTransform(23.8,6.3,0.79,0.79);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ABBBfIAAiNIgyCNIgdAAIgyiNIAACNIgjAAIAAi9IAvAAIA0CQIA1iQIAvAAIAAC9g");
	this.shape_4.setTransform(4.7,6.3,0.79,0.79);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhGBGQgdgcAAgqQAAgoAdgdQAdgdApAAQAqAAAdAdQAdAeAAAnQAAAqgdAcQgdAdgqAAQgpAAgdgdgAgtgtQgTATAAAaQAAAbATATQATATAaAAQAbAAATgTQATgTAAgbQAAgagTgTQgTgTgbAAQgaAAgTATg");
	this.shape_5.setTransform(-13.1,6.4,0.79,0.79);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag8BfIAAi9IAtAAQAhAAAPAOQARANAAAXQAAAMgGAKQgFAJgKAFQAQAGAIALQAIAMAAAQQAAAcgTAPQgSAPglAAgAgZA9IAWAAQAOAAAHgHQAIgGAAgLQAAgLgHgHQgJgHgNAAIgWAAgAgZgVIAQAAQALAAAGgFQAHgGAAgIQAAgKgHgFQgFgFgMAAIgQAAg");
	this.shape_6.setTransform(-27.1,6.3,0.79,0.79);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhGBGQgdgcAAgqQAAgnAdgeQAdgdApAAQAqAAAdAdQAdAdAAAoQAAAqgdAcQgdAdgqAAQgpAAgdgdgAgtgtQgTATAAAaQAAAbATATQATATAaAAQAbAAATgTQATgUAAgaQAAgZgTgUQgTgTgbAAQgaAAgTATg");
	this.shape_7.setTransform(-41.8,6.4,0.79,0.79);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAiBfIAAhQIhEAAIAABQIgjAAIAAi9IAjAAIAABMIBEAAIAAhMIAjAAIAAC9g");
	this.shape_8.setTransform(-57.2,6.3,0.79,0.79);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag9BfIAAi9IAuAAQAgAAAQAOQARANAAAXQAAANgGAJQgFAJgKAFQAQAGAHALQAKAMgBAQQAAAcgTAPQgTAPgkAAgAgaA9IAYAAQANAAAHgHQAIgGAAgLQAAgLgIgHQgHgHgNAAIgYAAgAgagVIARAAQAKAAAHgFQAHgFAAgJQAAgKgHgFQgGgFgLAAIgRAAg");
	this.shape_9.setTransform(-74.2,6.3,0.79,0.79);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AA4HgQgKgFgHgIQgGgJgEgJQgDgJAAgKQAAgIADgKQAEgJAGgIQAHgIAKgFQAKgFAOAAQALAAAJAEQAJADAIAIQAHAGAEALIgWAAIgGgHIgJgEQgFgDgGAAQgKABgIAFQgIAFgEAHQgFAJAAAIQAAALAFAHQAEAIAIAGQAIAEAKAAQAHAAAHgCQAGgEAFgFIAXAAQgFAJgHAHQgGAGgKAEQgJAEgLAAQgOAAgKgFgAqMHgQgKgFgHgIQgGgJgEgJQgDgJAAgKQAAgIADgKQAEgJAGgIQAHgIAKgFQAKgFAOAAQALAAAJAEQAJADAIAIQAHAGAEALIgWAAIgGgHIgJgEQgFgDgGAAQgKABgIAFQgIAFgEAHQgFAJAAAIQAAALAFAHQAEAIAIAGQAIAEAKAAQAHAAAHgCQAGgEAFgFIAXAAQgFAJgHAHQgGAGgKAEQgJAEgLAAQgOAAgKgFgAITHjIAAhJIgvBJIgTAAIAAhoIATAAIAABJIAvhJIATAAIAABogAGuHjIghguIAAAuIgTAAIAAhoIATAAIAAAtIAhgtIAXAAIgnAzIAnA1gADuHjIAAhoIATAAIAABVIAgAAIAAhVIATAAIAABVIAgAAIAAhVIATAAIAABogACgHjIAMgbIgohNIAXAAIAcA3IAXg3IAVAAIguBogAgmHjIAAhJIgvBJIgTAAIAAhoIATAAIAABJIAvhJIATAAIAABogAiuHjIAAhJIgvBJIgTAAIAAhoIATAAIAABJIAvhJIATAAIAABogAkTHjIghguIAAAuIgTAAIAAhoIATAAIAAAtIAhgtIAXAAIgnAzIAnA1gAmVHjIAAhoIAdAAQAMAAAIAEQAHADAEAGQADAEACAGIABAJIgCAKQgBAHgEAEQgEAFgIADQgHADgLABIgKAAIAAAngAmCGpIALAAIAHgBQAEgBADgDQADgDAAgGQAAgGgDgDQgDgDgEgBIgHAAIgLAAgAm7HjIAAhJIgvBJIgTAAIAAhoIATAAIAABJIAvhJIATAAIAABogAotHjIAAhVIgTAAIAAgTIA5AAIAAATIgTAAIAABVgAIiDxQgNgIgHgMQgHgLAAgQQAAgPAHgMQAHgMANgHQAMgIAQAAQAPAAAMAIQANAHAHAMQAHAMAAAPQAAAQgHALQgHAMgNAIQgMAHgPAAQgQAAgMgHgAIrCkQgIAEgEAIQgFAIAAAKQAAAKAFAIQAEAIAIAEQAIAGAKAAQALAAAIgGQAIgFAEgHQAFgJAAgJQAAgKgFgIQgEgIgIgEQgIgFgKgBQgLABgIAFgAEvDzQgKgFgHgIQgHgIgDgKQgEgJAAgJQAAgJAEgJQADgKAHgIQAHgIAKgFQAKgFAOAAQAKAAAKAEQAJADAHAIQAHAHAFAJIgWAAIgGgGIgJgFQgFgCgGAAQgLABgIAFQgHAEgFAIQgEAJAAAJQAAAJAEAJQAFAHAIAFQAIAGAKAAQAHAAAGgDQAHgEAFgFIAWAAQgEAIgHAHQgHAIgJADQgJAEgMAAQgNAAgKgFgAqTDxQgMgIgHgMQgHgLgBgQQABgPAHgMQAHgMAMgHQAMgIAQAAQAQAAAMAIQAMAHAHAMQAIAMAAAPQAAAQgIALQgHAMgMAIQgMAHgQAAQgQAAgMgHgAqJCkQgIAEgFAIQgEAIAAAKQAAAKAEAIQAFAIAIAEQAIAGAKAAQAKAAAIgGQAIgFAFgHQAEgJAAgJQAAgKgEgIQgFgIgIgEQgIgFgKgBQgKABgIAFgALDD2IAAhJIguBJIgTAAIAAhoIATAAIAABIIAuhIIATAAIAABogAG+D2IAAhoIAdAAQAMAAAIAEQAHADAEAGQADAFACAFIABAJIgCALQgBAFgEAFQgEAFgIADQgHADgLAAIgKAAIAAAogAHRC7IALAAIAHAAQAEgBADgCQADgDAAgHQAAgGgDgDQgDgDgEgBIgHgBIgLAAgAGND2IAAhWIgTAAIAAgSIA5AAIAAASIgTAAIAABWgADwD2IAAhoIATAAIAABogACgD2IAAhoIATAAIAAAoIAQAAQANAAAHAEQAIAFADAHQADAIAAAHQAAAKgEAHQgFAIgHADQgIAFgKAAgACzDjIAQAAQAHAAAEgEQAEgDAAgHQAAgFgEgEQgEgEgHABIgQAAgABMD2IAAhoIA9AAIAAASIgqAAIAAAWIARAAQAKAAAGADQAHACADAFQAEAEACAEIACAJIAAAEQAAAKgEAHQgEAIgIADQgIAFgKAAgABfDjIARAAQAFAAAEgCIAFgFQABgDAAgEIgBgFQgBgDgEgCQgDgCgGAAIgRAAgAAGD2IAAhoIATAAIAABogAhJD2IAAhoIATAAIAAAoIAQAAQANAAAHAEQAIAFADAHQADAIAAAHQAAAKgEAHQgFAIgHADQgIAFgKAAgAg2DjIAQAAQAHAAAEgEQAEgDAAgHQAAgFgEgEQgEgEgHABIgQAAgAhvD2IAAhOIgcBOIgQAAIgchOIAABOIgTAAIAAhoIAaAAIAdBPIAdhPIAaAAIAABogAjwD2IAAhOIgcBOIgQAAIgchOIAABOIgTAAIAAhoIAaAAIAdBPIAdhPIAaAAIAABogAlqD2IgLgbIgmAAIgLAbIgVAAIArhoIAQAAIArBogAl8DIIgMgeIgMAeIAYAAgAn1D2IAAhoIAdAAQAMAAAIAEQAHADAEAGQADAFACAFIABAJIgCALQgBAFgEAFQgEAFgIADQgHADgLAAIgKAAIAAAogAniC7IALAAIAHAAQAEgBADgCQADgDAAgHQAAgGgDgDQgDgDgEgBIgHgBIgLAAgAozD2IAAhoIA0AAIAAASIghAAIAABWgAr3D2IAAhoIAdAAQANAAAHAEQAIADADAGQAEAFABAFIABAJIgBALQgCAFgEAFQgEAFgHADQgIADgLAAIgKAAIAAAogArkC7IAMAAIAGAAQAEgBADgCQADgDAAgHQAAgGgDgDQgDgDgEgBIgGgBIgMAAgAsdD2IAAhWIgmAAIAABWIgTAAIAAhoIBMAAIAABogAKgCFQgGgCgDgEQgDgEgBgHIAQAAQABAFACABQADACADgBQADABADgCQADgBAAgFIAQAAQgBAHgDAEQgDAEgGACQgFADgHABQgHgBgFgDgAM7lQIAAg5IAAAAIgoA5IggAAIApg2QgLgCgJgGQgJgFgFgKQgGgKAAgMIACgPQACgHAFgIQAGgIALgGQALgFATAAIArAAIAACUgAManGQgGADgCAFQgCAFAAAGQAAAFACAFQACAFAGADQAGAEALgBIAQAAIAAgsIgQAAQgLAAgGAEgALDlQIAAhvIgnBvIgXAAIgohvIAABvIgbAAIAAiUIAlAAIApBxIAphxIAmAAIAACUgAHalQIAAiUIBPAAIAAAaIg0AAIAAAjIAyAAIAAAaIgyAAIAAAiIA0AAIAAAbgAFqlQIAAiUIApAAQASAAALAFQAKAFAFAIQAGAIACAHIABANQAAAIgCAHQgCAIgGAHQgGAHgKAEQgLAFgQAAIgOAAIAAA4gAGFmiIAQAAIAKgBQAFgCAEgEQAFgEAAgJQAAgJgFgEQgEgFgFAAIgKgCIgQAAgAD2lQIAAiUIAjAAIAJAAIAOADQAHABAGAEQAHAFAEAHQAFAHAAAMQAAAJgDAGQgEAGgDADIgGAEQAMAFAGAJQAHAKAAAMQAAALgFAKQgFALgNAGQgNAGgXABgAERlrIASAAIAFAAQAEAAAEgCQAEgCADgEQADgDAAgHQABgDgCgFQgBgEgFgEQgFgDgLAAIgSAAgAERmrIANAAQAJAAAEgDQAEgDABgDQACgEgBgCQAAgIgDgDQgEgDgEAAIgIgCIgNAAg");
	this.shape_10.setTransform(6.4,19.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-115.9,-36,232,103.8), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEjF9IAAhoIATAAIAABogADTF9IAAhoIATAAIAAAoIAQAAQANAAAHAEQAIAGADAHQADAHABAHQgBAKgEAHQgEAIgIADQgIAFgKAAgADmFqIAQAAQAHAAAEgEQAEgDAAgHQAAgFgEgEQgEgEgHABIgQAAgACtF9IAAgsIglAAIAAAsIgTAAIAAhoIATAAIAAAqIAlAAIAAgqIATAAIAABogABOF9IAAhJIguBJIgTAAIAAhoIATAAIAABIIAuhIIAUAAIAABogAh+F9IAAhoIATAAIAABVIAgAAIAAhVIATAAIAABVIAgAAIAAhVIATAAIAABogAieF9IgKgbIgmAAIgLAbIgVAAIArhoIAQAAIAqBogAiwFPIgLgeIgMAeIAXAAgAkMF9IAAhOIgbBOIgRAAIgbhOIAABOIgTAAIAAhoIAaAAIAdBPIAchPIAaAAIAABogAn+A3QgPgHgJgMQgKgMgEgNQgFgMAAgNQAAgNAFgNQAEgOAKgLQAJgMAPgHQAPgHAUAAQAOAAAOAFQANAGALAKQAJAJAHAPIgfAAIgJgJQgGgFgGgCQgIgCgIgBQgPAAgLAIQgMAHgGALQgGALgBAOQABANAGALQAHALALAIQALAGAPAAQAKAAAJgEQAJgEAIgIIAfAAQgGANgJAJQgKAKgOAGQgNAFgQAAQgTAAgPgHgAKVA7IAAiTIBQAAIAAAaIg0AAIAAAiIAyAAIAAAbIgyAAIAAAhIA0AAIAAAbgAJfA7IAAiTIAbAAIAACTgAHuA7IAAiTIAbAAIAAA5IAWAAQASgBALAIQALAGAFALQAEAJAAALQAAANgGALQgHAKgKAFQgLAHgPAAgAIJAgIAWAAQAKAAAGgFQAFgFAAgJQAAgJgFgEQgGgFgKAAIgWAAgAG3A7IAAg+Ig2AAIAAA+IgcAAIAAiTIAcAAIAAA7IA2AAIAAg7IAcAAIAACTgADyA7IAAiTIAbAAIAAA5IAWAAQASgBALAIQALAGAFALQAEAJAAALQAAANgGALQgHAKgKAFQgLAHgPAAgAENAgIAWAAQAKAAAGgFQAFgFAAgJQAAgJgFgEQgGgFgKAAIgWAAgADFA7IgphtIgoBtIgfAAIA7iTIAYAAIA7CTgAArA7IAAhoIhBBoIgcAAIAAiTIAcAAIAABmIBBhmIAcAAIAACTgAj5A7IAAiTIAbAAIAAB4IAtAAIAAh4IAbAAIAAB4IAtAAIAAh4IAcAAIAACTgAlqA7IARgmIg4htIAhAAIAnBOIAihOIAeAAIhDCTgAqGA7IAAhoIhDBoIgbAAIAAiTIAbAAIAABmIBDhmIAbAAIAACTgApxjoQgOgIgJgMQgKgLgFgNQgFgOAAgNQAAgNAFgNQAFgOAKgLQAJgLAOgIQAPgHAUAAQAPAAANAGQAOAFAKAKQAKAKAHAOIggAAIgJgJQgFgEgHgDQgHgCgJAAQgPAAgLAHQgLAHgHALQgGAMAAANQAAAOAGAMQAHALALAHQAMAHAOAAQALAAAIgEQAKgEAHgJIAgAAQgHANgJAJQgKALgNAFQgOAGgQgBQgTAAgPgGgAIWjlIAAiUIBQAAIAAAaIg0AAIAAAjIAyAAIAAAaIgyAAIAAAiIA0AAIAAAbgAHgjlIAAiUIAbAAIAACUgAFujlIAAiUIAcAAIAAA5IAWAAQASAAALAHQAKAHAGAKQAEALAAALQAAANgGALQgHAJgKAGQgLAGgPAAgAGKkAIAWAAQAKABAGgGQAFgEAAgJQAAgJgFgGQgGgEgKAAIgWAAgAE4jlIAAg+Ig2AAIAAA+IgcAAIAAiUIAcAAIAAA7IA2AAIAAg7IAbAAIAACUgAByjlIAAiUIAcAAIAAA5IAWAAQASAAALAHQAKAHAGAKQAEALAAALQAAANgGALQgGAJgLAGQgLAGgPAAgACOkAIAWAAQAKABAGgGQAFgEAAgJQAAgJgFgGQgGgEgKAAIgWAAgABFjlIgohuIgoBuIgeAAIA6iUIAYAAIA7CUgAhKjlIgPgmIg2AAIgQAmIgdAAIA9iUIAWAAIA+CUgAhjklIgRgsIgRAsIAiAAgAkQjlIAAiUIApAAQASAAALAFQAKAFAGAIQAFAIACAHIACANQAAAIgCAHQgDAIgGAHQgFAHgLAEQgKAFgRAAIgOAAIAAA4gAj1k3IAQAAIAKgBQAFgCAEgEQAFgEAAgJQAAgJgFgEQgEgFgFAAIgKgCIgQAAgAlHjlIAAhoIhCBoIgbAAIAAiUIAbAAIAABoIBChoIAcAAIAACUgAnpjlIAAh6IgcAAIAAgaIBSAAIAAAaIgbAAIAAB6g");
	this.shape.setTransform(2.5,7.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-79.7,-37.4,159.5,82.7), null);


(lib.p4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1Ресурс6();
	this.instance.parent = this;
	this.instance.setTransform(96,-24);

	this.instance_1 = new lib._2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-120,-170);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.p4, new cjs.Rectangle(-120,-170,300,520), null);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-120,-170);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1, new cjs.Rectangle(-120,-170,300,520), null);


(lib.knowmore = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AgPAeIAAg7IAfAAIAAAKIgUAAIAAAOIATAAIAAAKIgTAAIAAAOIAUAAIAAALg");
	this.shape.setTransform(31.1,0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00A7E0").s().p("AgiAeIAAg7IALAAIAAAwIASAAIAAgwIAKAAIAAAwIATAAIAAgwIAMAAIAAA7g");
	this.shape_1.setTransform(24.9,0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00A7E0").s().p("AgTAeIAAg7IALAAIAAAXIAIAAQAIAAAEADQAEACACAEQACAEAAAFQAAAFgCAEQgDAFgEACQgFACgGAAgAgIATIAIAAQAEAAACgCQADgCAAgDQAAgEgDgCQgCgCgEAAIgIAAg");
	this.shape_2.setTransform(18.6,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00A7E0").s().p("AAQAeIgQgsIgPAsIgNAAIAYg7IAJAAIAYA7g");
	this.shape_3.setTransform(13.1,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00A7E0").s().p("AgPAbQgIgEgEgHQgEgHAAgJQAAgIAEgHQAEgHAIgEQAHgEAIgBQAJABAHAEQAIAEADAHQAFAHAAAIQAAAJgFAHQgEAHgHAEQgHAFgJAAQgIAAgHgFgAgKgRQgEADgDAFQgDAEAAAFQAAAGADAFQADAEAEADQAFADAFAAQAGAAAFgDQAFgDACgFQADgEAAgGQAAgFgDgEQgCgFgFgDQgFgDgGAAQgFAAgFADg");
	this.shape_4.setTransform(6.7,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00A7E0").s().p("AgUAeIAAg7IAjAAIAAAKIgXAAIAAANIAJAAQAFAAAEACQAEABACADIADAEIACAEIAAAEQgBAFgCAEQgCAFgFACQgEACgGAAgAgIATIAJAAIAEgBIADgDIACgDIgCgEIgCgDQgCgBgDAAIgJAAg");
	this.shape_5.setTransform(0.9,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00A7E0").s().p("AgTAeIAAg7IALAAIAAAXIAIAAQAIAAAEADQAEACACAEQACAEAAAFQAAAFgCAEQgDAFgEACQgFACgGAAgAgIATIAIAAQAEAAACgCQADgCAAgDQAAgEgDgCQgCgCgEAAIgIAAg");
	this.shape_6.setTransform(-5.8,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00A7E0").s().p("AgFAeIAAgxIgLAAIAAgKIAhAAIAAAKIgLAAIAAAxg");
	this.shape_7.setTransform(-10.1,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7E0").s().p("AARAeIgGgPIgVAAIgGAPIgNAAIAag7IAIAAIAZA7gAAHAEIgHgRIgGARIANAAg");
	this.shape_8.setTransform(-14.4,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7E0").s().p("AALAeIAAgZIgVAAIAAAZIgLAAIAAg7IALAAIAAAYIAVAAIAAgYIALAAIAAA7g");
	this.shape_9.setTransform(-20.3,0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00A7E0").s().p("AgKAdQgEgCgDgFQgDgEABgGIALAAIABADQAAABAAAAQAAABAAAAQABABAAAAQABABAAAAQACABADABIAGgBIADgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAgDIgDgDQgBAAAAgBQgBAAAAAAQgBAAgBAAQAAgBgBAAIgFAAIAAgKIAEAAQAEAAACgBQACgCAAgDIgCgFQgCgCgEgBQgCAAgCACQgCABAAADIgLAAQAAgEACgEQACgEAEgCQAEgCAFgBQAGABAEACQAEACACADQADAEAAAFQAAAFgDADQgCAEgEACIAFABIAEAFQACADAAAEQAAAGgDAEQgDAEgEACQgFACgGAAQgFABgFgDg");
	this.shape_10.setTransform(-25.4,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00A7E0").s().p("AgLAeIAIgPIgYgsIAOAAIAPAfIAOgfIAMAAIgcA7g");
	this.shape_11.setTransform(-30.2,0.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AlzBLIAAiVILnAAIAACVg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.knowmore, new cjs.Rectangle(-37.2,-7.5,74.5,15.1), null);


(lib.eko = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAKBUQgWgNgMgWQgNgWAAgaQAAgbANgWQAMgWAWgMQAWgNAbAAQAdAAAWANQAWAMAMAWQANAWAAAbQAAAagNAWQgNAWgWANQgVAMgdAAQgbAAgWgMgAAbg1QgOAIgJAOQgGAOgBARQABARAGAPQAJAOAOAIQAOAJASAAQASAAAPgJQAPgIAIgPQAHgOAAgRQAAgRgHgOQgIgOgPgIQgPgJgSAAQgSAAgOAJgAlxBUQgXgNgMgWQgNgWAAgaQAAgbANgWQAMgWAXgMQAVgNAcAAQAcAAAXANQAVAMANAWQANAWAAAbQAAAagNAWQgMAWgXANQgVAMgdAAQgcAAgVgMgAlgg1QgOAIgJAOQgHAOgBARQABARAHAPQAJAOAOAIQAPAJARAAQATAAAOgJQAPgIAHgPQAJgOgBgRQABgRgJgOQgHgOgPgIQgOgJgTAAQgRAAgPAJgAq/BZQgRgHgMgMQgNgMgHgQIAoAAQAHAKANAGQAMAFAOAAQANAAANgGQALgFAKgLQAJgKADgPIhUAAIAAggIBTAAQgDgMgIgLQgHgLgLgGQgNgGgQAAQgFgBgIACQgJABgJAFQgJAFgIALIgoAAQAMgbAXgOQAXgPAeAAQAZAAARAIQASAJAMAOQALAOAHARQAFAQAAARQAAAQgFAQQgGASgMAOQgMAPgSAIQgSAJgYAAQgVAAgQgHgAKPBcIAAi4IBkAAIAAAhIhCAAIAAArIA/AAIAAAgIg/AAIAAArIBCAAIAAAhgAI5BcIAAiXIgjAAIAAghIBnAAIAAAhIgiAAIAACXgAGcBcIAAi4IAhAAIAABHIAcAAQAXAAANAJQAOAIAGAMQAGANgBAOQABARgJANQgHAMgOAHQgOAIgSAAgAG9A7IAcAAQAMAAAIgHQAHgGAAgLQAAgLgHgHQgIgGgMAAIgcAAgAFXBcIAAiKIgxCKIgdAAIgxiKIAACKIgjAAIAAi4IAvAAIA0CMIAziMIAvAAIAAC4gAhgBcIAAhOIhDAAIAABOIgiAAIAAi4IAiAAIAABKIBDAAIAAhKIAjAAIAAC4gAnHBcIg5hRIAABRIgjAAIAAi4IAjAAIAABQIA5hQIAqAAIhHBbIBHBdg");
	this.shape.setTransform(75.5,9.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.eko, new cjs.Rectangle(0,0,150.9,19.3), null);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(305));

	// Слой 1
	this.instance = new lib.eko();
	this.instance.parent = this;
	this.instance.setTransform(102.3,95.6,1,1,0,0,0,75.5,9.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(75).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(215).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// t4
	this.instance_1 = new lib.t4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(148.6,107.8,1.25,1.25);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(225).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// t3
	this.instance_2 = new lib.t3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(148.6,107.8,1.25,1.25);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(150).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(75));

	// t2
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(148.6,122.8,1.25,1.25);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(75).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(150));

	// t1
	this.instance_4 = new lib.t1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(398.6,121.6,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:148.6},11,cjs.Ease.get(1)).wait(61).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(225));

	// Слой 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ApGBTQgqgmAYg4QAWgzBGgdQBOghB9AAQAcAAAaADIAgAFIANADIgSAgQgogLggAAQhAAAg0ATQhHAZgKAxQgHAeAWAbQAcAiA9gDQATAAAlgNQAtgPAbgVIA/g3IANgIQAIgEAKAAIBEAAIAWBeIArhdIBLAAIArBIIAghIIBFAAIg8CDIhHAAIgthMIgiBMIgrAAIAAABIhSAAIgDgYIhKAAIgZAWIgwAAQg5AVhJAAQhqAAgugqgAjHA4IArgBIgDglgAGHB2IAsgsIgshkIBEAAIASA1IA4g2IBNAAIiFCFQgHAHgFABIgQAEgAD+BpIhvAAIA9iDIBvAAQA1AAAUAZQAPAUgLAbQgLAYgdAPQglAUg6AAIgDAAgADpBIIATAAQBBAAAJgjQAFgSgSgIQgLgFgUAAIgUAAg");
	this.shape_1.setTransform(151.1,46.3,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(305));

	// Слой 2
	this.instance_5 = new lib._1Ресурс5();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,2);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(305));

	// fg
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AuTBxIAAgRQgGAAgGgCQgFgCgDgDQgEgEgCgEQgBgFgBgGQABgFABgFQACgFAEgDQADgEAFgCIAMgCIAAgUIAIAAIAAAUIALACQAFACAEAEQAEADACAFQABAFAAAFQAAAGgBAFQgCAEgEAEQgEADgFACQgFACgGAAIAAARgAuLBZQAFAAADgBIAFgEIAEgGIABgIIgBgHIgEgGQgCgDgDgBIgIgCgAugA5QgFAFAAAIQAAAJAFAFQAEAFAJAAIAAgmQgJABgEAFgAyRBxIAAgRIgrAAIAAAOIAAACIgCABIgGAAIAAgYIADAAIADgBIADgCIACgFIADgIIACgMIABgQIAhAAIAAAsIAJAAIAAAVIAAACIgDABgAwVBsIAAgBIgBgBIABgBIABgBIACgDIABgCIABgDIgBAAIgBgBIgCgBIgCgCIgBgDQAAAAABgBQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAgBQABAAAAAAQABAAABgBQAAAAABAAIACABIADACIABACIABADIgBAFIgCAEIgEAFIgDAEgAzvBsIAAgBIgBgBIABgBIACgBIACgDIABgCIAAgDIAAAAIgCgBIgCgBIgCgCIAAgDQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABgBQAAAAABAAQAAAAABgBQABAAAAAAIADABIACACIACACIAAADIgBAFIgCAEIgDAFIgEAEgAVqBfIgIgEIgFgGIgDgHIAFgCIADAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIABAEIAEADIADADIAHABIAHgBIAEgDQACgCAAgCIABgFIAAgFIgDgEQgCgCgEgBIgJgBIAAgGIAIgBIAGgDIACgEIABgFIgBgFIgCgEIgEgCIgFgBIgFABIgEACIgDADIgCAFIgBACIgDAAIgFAAQABgFACgEQACgEACgDQAEgCAEgBQAEgCAFAAQAEAAAEACQAEABADACQADADABADQABADAAAFIgBAGQAAACgCACIgDAEIgGACQAHACADAEQAEAFAAAGQAAAFgCAEQgCAEgDADQgEADgDABQgFACgFAAQgFAAgEgCgAUwBgIgFgCIgGgCIgDgDIADgEQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIADABIACACIAFACIAFAAIAHgBQADgBACgCIAEgFIABgHIgBgGIgEgFIgEgCIgHgBQgGAAgFACIgHgCIAHgiIAiAAIAAAEQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAQAAAAgBAAIgWAAIgDASIAKgBQAFAAAFABQAEACADADQADADACAEQABAEAAAEQAAAGgCAFQgCAEgEAEQgDADgFACQgEACgGAAIgGgBgAQNBfQgEgCgEgDQgDgDgBgFQgCgFAAgFQAAgFADgFQACgGAEgGIASgYIACgBIADgBIAIAAIgVAbIgCACIgBACQACgCADAAIAHgBQAEAAAEABQADABADADQADADACAEQACAEAAAFQAAAFgCAEQgCAFgDADIgIAFQgFACgFAAQgGAAgEgCgAQRA8IgEADIgDAFIgBAGIABAGIACAEIAEAEIAHABIAHgBIAEgEIAEgEIABgGIgBgGIgEgFIgEgDIgHgBQgDAAgDABgAE0BgIgFgCIgFgCIgDgDIADgEQAAgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIACABIADACIAEACIAGAAIAHgBQADgBABgCIAEgFIABgHIgBgGIgDgFIgEgCIgHgBQgGAAgGACIgGgCIAGgiIAiAAIAAAEQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgXAAIgDASIAKgBQAGAAAEABQAFACADADQACADACAEQACAEAAAEQAAAGgDAFQgBAEgEAEQgDADgFACQgFACgFAAIgHgBgAASBgIgGgCIgEgCIgEgDIADgEQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAIABABIADACIAFACIAGAAIAGgBQADgBACgCIADgFIABgHIgBgGIgCgFIgFgCIgHgBQgFAAgHACIgFgCIAFgiIAjAAIAAAEQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAQAAAAgBAAIgWAAIgDASIAKgBQAGAAAEABQAFACACADQADADABAEQACAEAAAEQAAAGgCAFQgCAEgDAEQgEADgEACQgGACgFAAIgGgBgAxDBfQgEgBgDgDIgGgGQgBgEAAgFQAAgHADgEQAEgFAGgCQgFgCgDgEQgDgEAAgGQAAgEABgDIAFgGIAHgEQAEgCAFAAQAFAAAEACIAHAEIAFAGQABADAAAEQAAAGgDAEQgDAEgFACQAGACAEAFQAEAEgBAHQAAAFgCAEQgBADgDADQgDADgFABQgEACgGAAQgFAAgFgCgAw/A/QgCABgCACIgEAEIAAAGIAAAFIADAEQACACADABIAGABIAGgBQADgBACgCIACgEIABgFIgBgGIgDgEQgCgCgDgBIgFgBIgGABgAw/AfIgDADIgDAEIgBAEIABAFIADAEIADADIAGABIAGgBIAEgDIACgEIAAgFIAAgEIgCgEIgFgDIgFAAIgGAAgAS7BeQgEgCgEgEQgDgFgCgHQgCgHAAgJQAAgKACgGQACgHADgFQAEgEAEgDQAFgCAGAAQAFAAAFACQAFADADAEQADAFACAHQACAGAAAKQAAAJgCAHQgCAHgDAFQgDAEgFACQgFACgFAAQgGAAgFgCgATAAhIgGAEIgDAJQgCAGAAAIQAAAIACAFQABAGACADQADAEADABQACACAEAAIAFgCQADgBADgEQACgDABgGQACgFAAgIQAAgIgCgGIgDgJIgGgEIgFgCQgEAAgCACgARGBeQgEgCgDgEQgEgFgCgHQgCgHAAgJQAAgKACgGQACgHAEgFQADgEAEgDQAGgCAFAAQAGAAAEACQAFADAEAEQADAFACAHQACAGAAAKQAAAJgCAHQgCAHgDAFQgEAEgFACQgEACgGAAQgFAAgGgCgARLAhIgGAEIgDAJQgCAGABAIQgBAIACAFQACAGABADQADAEADABQADACADAAIAGgCQADgBADgEQACgDABgGQABgFAAgIQAAgIgBgGIgDgJIgGgEIgGgCQgDAAgDACgALqBeQgEgCgEgEQgEgFgCgHQgCgHAAgJQAAgKACgGQACgHAEgFQAEgEAEgDQAFgCAGAAQAFAAAFACQAEADAEAEQADAFADAHQACAGAAAKQAAAJgCAHQgDAHgDAFQgEAEgEACQgFACgFAAQgGAAgFgCgALuAhIgFAEIgEAJQgBAGAAAIQAAAIABAFQACAGACADQACAEADABQADACAEAAIAGgCQACgBADgEQACgDACgGQABgFAAgIQAAgIgBgGIgEgJIgFgEIgGgCQgEAAgDACgAGOBeQgGgDgEgFQgFgFgDgGQgDgHABgIQgBgIADgHQADgHAFgFQAEgEAGgDQAHgDAIAAQAIAAAGADQAHADAFAEQAEAFADAHQADAHAAAIQAAAIgDAHQgDAGgEAFQgFAFgHADQgGACgIAAQgIAAgHgCgAGTAiQgFACgDAEQgDADgCAFQgCAFAAAHQAAAGACAFQACAGADADQADAEAFACQAEACAGAAQAGAAAFgCQAEgCAEgEQACgDACgGQACgFAAgGQAAgHgCgFQgCgFgCgDQgEgEgEgCQgFgCgGAAQgGAAgEACgAC/BeQgEgCgEgEQgDgFgCgHQgCgHAAgJQAAgKACgGQACgHADgFQAEgEAEgDQAFgCAGAAQAGAAAEACQAFADADAEQAEAFACAHQACAGAAAKQAAAJgCAHQgCAHgEAFQgDAEgFACQgEACgGAAQgGAAgFgCgADEAhIgGAEIgDAJQgCAGAAAIQAAAIACAFQABAGACADQADAEADABQADACADAAIAGgCQADgBADgEQABgDACgGQACgFgBgIQABgIgCgGIgDgJIgGgEIgGgCQgDAAgDACgAhiBeQgEgCgEgEQgEgFgCgHQgCgHAAgJQAAgKACgGQACgHAEgFQAEgEAEgDQAFgCAGAAQAFAAAEACQAFADAEAEQAEAFACAHQACAGAAAKQAAAJgCAHQgCAHgEAFQgEAEgFACQgEACgFAAQgGAAgFgCgAheAhIgFAEIgEAJQgBAGAAAIQAAAIABAFQACAGACADQACAEADABQADACAEAAIAGgCQADgBACgEQACgDACgGQABgFAAgIQAAgIgBgGIgEgJIgFgEIgGgCQgEAAgDACgApiBeQgFgCgDgEQgEgFgCgHQgCgHAAgJQAAgKACgGQACgHAEgFQADgEAFgDQAEgCAGAAQAFAAAFACQAFADADAEQAEAFACAHQACAGAAAKQAAAJgCAHQgCAHgEAFQgDAEgFACQgFACgFAAQgGAAgEgCgApeAhIgFAEIgEAJQgBAGgBAIQABAIABAFQACAGACADQACAEADABQACACAEAAIAGgCQADgBACgEQACgDACgGQABgFABgIQgBgIgBgGIgEgJIgFgEIgGgCQgEAAgCACgAqdBeQgEgCgEgEQgDgFgCgHQgCgHAAgJQAAgKACgGQACgHADgFQAEgEAEgDQAFgCAGAAQAFAAAFACQAFADADAEQADAFACAHQACAGAAAKQAAAJgCAHQgCAHgDAFQgDAEgFACQgFACgFAAQgGAAgFgCgAqYAhIgGAEIgDAJQgCAGAAAIQAAAIACAFQABAGACADQADAEADABQACACAEAAIAFgCQADgBADgEQACgDABgGQACgFAAgIQAAgIgCgGIgDgJIgGgEIgFgCQgEAAgCACgAshBfIgHgFQgDgEgCgFQgCgEAAgHQABgFABgFQABgFAEgDQADgEAFgCQAEgCAGAAQAFAAAEACIAIAFIgDADIgBABIgBABIgCgBIgCgBIgDgCIgFAAIgHABIgEAEIgDAFIgBAIIABAIIADAGIAEAEIAHABIAFgBIAEgBIABgCIACgBIADABIACAEIgEADIgEADIgGABIgFAAQgFAAgEgBgAvZBfQgFgCgDgEQgDgDgBgFQgCgFAAgGQAAgGACgFQABgEADgEQADgDAFgCQAEgCAGAAQAFAAAFACQAEACADADQAEAEACAEQABAFAAAGQAAAGgBAFQgCAFgEADQgDAEgEACQgFABgFAAQgGAAgEgBgAvaA5QgEAFABAIQgBAJAEAFQADAFAIAAQAHAAAEgFQADgFABgJQgBgIgDgFQgEgFgHAAQgIAAgDAFgAx+BgIgCgBIgBgCIAAgDIAAgDIABgCIACgBIADgBIADABIACABIABACIABADIgBADIgBACIgCABIgDAAIgDAAgAUHBgIAAgTIggAAIgCAAIAAgCIgBgFIAjguIAIAAIAAAuIALAAIAAAFIgBACIgBAAIgJAAIAAATgATuBGIAZAAIAAgdIAAgDIABgDgAR5BgIAeg7IAEgEIglAAIgCgBIgBgCIAAgGIAxAAIAAAEIAAADIgBACIgeA7IgCADIgCABgAPNBgIAVgdIADgCIACgDIgHADIgHABIgIgBIgGgEIgFgGQgBgEAAgFQAAgFACgEQACgEADgDIAIgFQAEgCAFAAQAFAAAFACIAHAFQADADABAEQACAEAAAFIgBAGIgBAGIgDAFIgEAGIgRAZIgCABIgCABgAPXAgIgEADQgDACgBADIgBAFQABAHADAEQAEADAHAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIgGABgAORBgIAeg7IADgEIglAAIgBgBIgBgCIAAgGIAwAAIAAAEIAAADIAAACIgeA7IgCADIgDABgANXBgIAeg7IADgEIglAAIgCgBIAAgCIAAgGIAxAAIAAAEIAAADIgCACIgdA7IgCADIgDABgAM2BgIAAgTIggAAIgCAAIgBgCIgBgFIAjguIAJAAIAAAuIAKAAIAAAFIAAACIgCAAIgIAAIAAATgAMdBGIAZAAIAAgdIAAgDIAAgDgAKqBgIAAgHIAOAAIAAgwIAAgFIgLALIgCABIgBAAIgCgBIAAgBIgDgEIAVgSIAIAAIAABBIAOAAIAAAHgAJwBgIAAghIglAAIAAAhIgKAAIAAhIIAKAAIAAAgIAlAAIAAggIALAAIAABIgAIDBgIAAhIIAWAAQAHAAAFACQAFABAEADIAEAHQACAEAAAFQAAAFgCAFQgCAEgDADQgEADgEACQgGABgGAAIgMAAIAAAbgAINA9IAMAAIAHgBQAEgBACgCIACgFIABgGIgBgGIgCgEIgGgDIgHgBIgMAAgAHOBgIAAhIIArAAIAAAIIghAAIAABAgAD0BgIAAgHIAPAAIAAgwIAAgFIgNALIgBABIgBAAIgBgBIgBgBIgDgEIAWgSIAHAAIAABBIAOAAIAAAHgAB3BgIAAgEIABgCIABgBIAXgXIAFgGIAEgFQACgDAAgDIABgFIgBgGIgCgEIgEgCIgFgBIgFABIgDACIgDADIgDAFIgBACIgDAAIgFAAQAAgFADgEQABgEAEgDQADgCAEgBQAEgCAFAAQAEAAAEACQAEABADADQADACABAEQACAEAAAEQAAAEgBAEIgDAGIgFAGIgFAGIgTATIAEgBIAEAAIAXAAIADABIAAACIAAAGgABFBgIAAgHIAPAAIAAgwIAAgFIgMALIgBABIgCAAIgBgBIgBgBIgCgEIAVgSIAHAAIAABBIAPAAIAAAHgAgWBgIAAgTIggAAIgBAAIgCgCIgBgFIAjguIAJAAIAAAuIAKAAIAAAFIAAACIgCAAIgIAAIAAATgAgvBGIAZAAIAAgdIAAgDIAAgDgAijBgIAeg7IACgEIglAAIgBgBIAAgCIAAgGIAwAAIAAAEIAAADIgBACIgdA7IgCADIgEABgAjeBgIAeg7IAEgEIglAAIgCgBIgBgCIAAgGIAxAAIAAAEIAAADIgBACIgeA7IgCADIgCABgAkWBgIAAghIglAAIAAAhIgLAAIAAhIIALAAIAAAgIAlAAIAAggIALAAIAABIgAliBgIAAghIgmAAIAAAhIgKAAIAAhIIAKAAIAAAgIAmAAIAAggIALAAIAABIgAmuBgIAAgyIAAgFIAAgFIgBAEIgCAEIghAwIgCADIgDABIgHAAIAAhIIAKAAIAAAyIAAAEIAAAGIABgFIACgDIAhgxIACgCIACgBIAIAAIAABIgAouBgIAAgHIAOAAIAAgwIAAgFIgMALIgBABIgBAAIgBgBIgBgBIgDgEIAWgSIAHAAIAABBIAOAAIAAAHgArdBgIAAgHIAPAAIAAgwIAAgFIgMALIgCABIgBAAIgBgBIgBgBIgCgEIAVgSIAIAAIAABBIAOAAIAAAHgAtDBgIAAgiIAAgCIAAgCIAAACIgBABIgBACIgDADIgEAGIgFAFIgLAQIgCACIgBABIgGAAIAAgzIAJAAIAAAiIAAACIAAACIACgDIABgCIADgEIADgFIAFgGIALgQIACgBIACgBIAGAAIAAAzgA0FBgIAAgiIAAgCIAAgCIgBACIAAABIgCACIgDADIgDAGIgFAFIgMAQIgBACIgCABIgGAAIAAgzIAKAAIAAAiIAAACIgBACIACgDIABgCIAEgEIADgFIAFgGIALgQIABgBIACgBIAGAAIAAAzgA2KBgIAAgEIAAgCIACgBIAXgXIAEgGIAFgFQACgDAAgDIABgFIgBgGIgCgEIgFgCIgEgBIgGABIgDACIgDADIgCAFIgCACIgCAAIgGAAQABgFACgEQACgEADgDQADgCAEgBQAEgCAFAAQAFAAAEACQADABAEADQADACABAEQACAEAAAEQAAAEgCAEIgCAGIgGAGIgFAGIgSATIADgBIAFAAIAXAAIACABIABACIAAAGgA1OBGIAAgIIAZAAIAAAIgA0XAlIgFgCIgDgEIgBgEIABgCIABgBIAGAAIAAAEIABADIACABIAEABIADgBIACgBIACgDIAAgEIAFAAIACABIABACIgBAEIgDAEIgFACIgGABIgGgBgAQrgWIAAgSIhEAAIAAgyIAJAAIAAArIAUAAIAAgrIAJAAIAAArIAUAAIAAgrIAKAAIAAArIAJAAIAAAWIgBACIgCABgANIgWIAAgSIgqAAIAAAPIgBACIgCABIgFAAIAAgZIACAAIADAAIAEgDIACgFIACgHIACgMIACgQIAgAAIAAArIAJAAIAAAWIAAACIgCABgAsxgWIAAgSIg5AAIAAAPIgBACIgCABIgGAAIAAgaIAHAAIADgCIADgFIACgIIADgLIACgQIABgVIArAAIAAA/IALAAIAAAXIAAACIgCABgAtWhSIgCAPIgEAMIgEAHIAjAAIAAg3IgYAAIgBAVgAJJgXIAAhDIAFAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAABAAIABAGQADgEAEgCQAEgCAGAAQAEAAADABQADACADADQADAEABAEQABAFABAHQgBAFgBAFQgCAFgDADQgCAEgEACQgEACgGAAQgEAAgEgCIgFgEIAAAWgAJYhSQgDACgDAEIAAAYQADADACABQADACADAAQAIAAADgFQAEgFAAgJIgBgJIgDgFQgBgDgCgBIgGgBQgEAAgDACgAHOgcIgBAAIAAgBIABgCIABgBIACgCIABgDIABgDIAAAAIgDAAIgCgCIgBgCIgBgCQAAgBABAAQAAgBAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABgBAAAAQABAAABAAQAAAAABAAIADABIABABIACACIAAADIgBAFIgCAFIgCAFIgFAEgAgTgcIgBAAIgBgBIACgCIABgBIACgCIAAgDIABgDIAAAAIgCAAIgCgCIgCgCIAAgCQAAgBAAAAQAAgBABgBQAAAAAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAIADABIACABIACACIAAADIgBAFIgCAFIgDAFIgEAEgAGhgoIgEgCQgCgCgBgDQgBgCgBgDQAAgEACgCIAFgFIAKgEQAGgBAJAAIAAgEQAAgGgDgDQgCgDgFAAIgFABIgEACIgDACIgDAAIgBAAIgBgBIgCgDQAEgEAGgCQAEgCAGAAQAFAAADABQADABACADIAEAGIABAIIAAAgIgEAAIgDAAIAAgCIgBgEIgFADIgDACIgFACIgFAAIgGgBgAGug9IgHACIgEACIgCAEIABADIACADIADABIADAAIAEAAIADgBIAEgCIADgDIAAgKIgKABgAjvgoIgFgBIgFgDIgEgDIADgEQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIACABIAEABIAEACIAGABIAGgBQADgBACgDIAEgFIABgHIgBgGIgEgEIgEgDIgHgBQgGAAgFACIgGgCIAGghIAiAAIAAAEQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAIgWAAIgDASIAKgBQAFAAAFACIAHAEQADADACAEQABAEAAAFQAAAGgCAEQgCAFgDADQgEAEgEABQgFACgGAAIgGgBgAqngqQgGgCgFgFQgEgFgDgHQgCgHAAgIQAAgIACgGQADgHAFgFQAEgFAHgDQAGgCAIAAQAIAAAGACQAFADAFAEIgDAFIgBAAIgCABIgBgBIgEgCIgFgCIgIgBQgFAAgEACQgFABgEAEQgCAEgDAFQgCAFAAAGQAAAHACAFQADAFACAEQAEADAFACQAEACAFAAIAGAAIAEgBIAEgCIAEgDIAAgBIABAAIACABIAEAEQgEAFgGADQgHADgIAAQgJAAgGgDgAS6gpIgHgFQgDgDgCgFQgBgFAAgGQgBgGACgFQACgEADgEQADgDAEgCQAFgCAFAAQAGAAAEABIAHAFIgCAEIgBABIgBAAIgCgBIgCgBIgDgBIgFgBIgGABIgFAEIgDAGIAAAIIABAIIACAGIAFADIAFACIAGgBIADgCIADgCIACAAIABABIADADIgEAEIgFACIgEABIgGABQgFAAgEgCgAO6gpQgFgCgDgDQgDgEgCgEQgCgFAAgGQAAgGACgFQACgFADgDQADgEAFgBQAEgCAGAAQAFAAAEACQAFABADAEQAEADABAFQACAFAAAGQAAAGgCAFQgBAEgEAEQgDADgFACQgEACgFAAQgGAAgEgCgAO5hPQgEAFAAAJQAAAJAEAFQADAFAIAAQAGAAAEgFQAEgFAAgJQAAgJgEgFQgEgFgGAAQgIAAgDAFgAL3goIgEgBIgFgCIgEgEIADgDIABgBIACAAIADACIADACIAGABIAEgBIAEgCIADgDIAAgDQAAgEgDgCQgDgCgGAAIgGAAIAAgGIAGAAQAGAAADgCQADgDAAgDIgBgDIgCgCIgEgBIgEgBIgFABIgDABIgDABIgCABIgBAAIgBgCIgCgDIAHgFQAEgBAGAAIAJABIAFADIAEAEIABAFIAAADIgCADIgDADIgEACQAEACAEADQACADAAAFQAAADgBADIgFAFIgGADIgHABIgGgBgALFgpQgEgCgDgDQgEgDgCgGQgCgFABgGIABgKIAFgIQADgDAFgCQAEgCAGAAQAEAAAEABQADACADADQAEADABAEQABAEABAFIgBADIgBABIgiAAIABAIIAEAGQACACACABQADACAEAAIAFgBIAFgCIACgCIACAAIACABIADADIgEAEIgFACIgGABIgFABQgGAAgEgCgALFhRQgEAEgBAGIAbAAIgBgFIgCgFIgEgCIgFgBQgHAAgDADgAKMgpQgFgCgDgDQgDgEgBgEQgCgFAAgGQAAgGACgFQABgFADgDQADgEAFgBQAEgCAGAAQAGAAAEACQAEABADAEQAEADACAFQABAFAAAGQAAAGgBAFQgCAEgEAEQgDADgEACQgEACgGAAQgGAAgEgCgAKLhPQgEAFABAJQgBAJAEAFQADAFAIAAQAHAAAEgFQADgFABgJQgBgJgDgFQgEgFgHAAQgIAAgDAFgAERgpIgHgFQgCgDgCgFQgCgFAAgGQAAgGACgFQABgEADgEQADgDAFgCQAEgCAGAAQAFAAAEABIAIAFIgDAEIAAABIgBAAIgCgBIgDgBIgCgBIgGgBIgGABIgFAEIgCAGIgBAIIABAIIACAGIAFADIAGACIAGgBIADgCIACgCIACAAIACABIACADIgDAEIgFACIgFABIgGABQgEAAgFgCgADZgpQgEgCgEgDQgDgEgBgEQgCgFAAgGQAAgGACgFQABgFADgDQAEgEAEgBQAFgCAFAAQAGAAAEACQAFABADAEQAEADABAFQABAFABAGQgBAGgBAFQgBAEgEAEQgDADgFACQgEACgGAAQgFAAgFgCgADZhPQgEAFAAAJQAAAJAEAFQADAFAHAAQAIAAADgFQAEgFAAgJQAAgJgEgFQgDgFgIAAQgHAAgDAFgABDgoIgCgBIgBgCIAAgDIAAgCIABgCIACgCIADAAIADAAIABACIACACIAAACIAAADIgCACIgBABIgDABIgDgBgAnKgoIgCgBIgCgCIAAgDIAAgCIACgCIACgCIACAAIADAAIACACIACACIAAACIAAADIgCACIgCABIgDABIgCgBgAoQgoIgBgBIgBgCIgBgDIABgCIABgCIABgCIADAAIADAAIACACIABACIABACIgBADIgBACIgCABIgDABIgDgBgAp0goIgBgBIgBgCIgBgDIABgCIABgCIABgCIADAAIADAAIACACIACACIAAACIAAADIgCACIgCABIgDABIgDgBgAzDgqQgGgCgFgFQgEgFgDgHQgCgHgBgIQABgIACgGQADgHAEgFQAFgFAGgDQAHgCAIAAQAIAAAHACQAGADAFAFQAFAFACAHQACAGABAIQgBAIgCAHQgCAHgFAFQgFAFgGACQgHADgIAAQgIAAgHgDgAy+hlQgFABgDAEQgEAEgBAFQgCAFAAAGQAAAHACAFQABAFAEAEQADADAFACQAFACAFAAQAGAAAEgCQAFgCAEgDQACgEADgFQABgFAAgHQAAgGgBgFQgDgFgCgEQgEgEgFgBQgEgCgGAAQgFAAgFACgA0TgqQgGgCgFgFQgEgFgDgHQgCgHgBgIQABgIACgGQADgHAEgFQAFgFAGgDQAHgCAIAAQAIAAAHACQAGADAFAFQAFAFACAHQACAGAAAIQAAAIgCAHQgCAHgFAFQgFAFgGACQgHADgIAAQgIAAgHgDgA0OhlQgFABgDAEQgEAEgBAFQgCAFAAAGQAAAHACAFQABAFAEAEQADADAFACQAFACAFAAQAGAAAEgCQAFgCADgDQAEgEACgFQABgFAAgHQAAgGgBgFQgCgFgEgEQgDgEgFgBQgEgCgGAAQgFAAgFACgA1igqQgHgCgFgFQgFgFgCgHQgCgHgBgIQABgIACgGQACgHAFgFQAFgFAHgDQAGgCAIAAQAIAAAHACQAGADAFAFQAEAFADAHQADAGgBAIQABAIgDAHQgDAHgEAFQgFAFgGACQgHADgIAAQgIAAgGgDgA1ehlQgFABgDAEQgEAEgBAFQgCAFAAAGQAAAHACAFQABAFAEAEQADADAFACQAEACAGAAQAGAAAEgCQAFgCADgDQADgEADgFQABgFAAgHQAAgGgBgFQgDgFgDgEQgDgEgFgBQgEgCgGAAQgGAAgEACgAVugoIAAghIAAgDIAAgCIgBACIAAACIgBABIgDAEIgEAFIgEAGIgMAQIgCACIgCAAIgFAAIAAgyIAKAAIAAAhIAAACIgBADIACgEIABgBIADgEIAEgFIAEgGIALgQIACgCIACAAIAGAAIAAAygAU1goIAAghIAAgDIAAgCIgBACIAAACIgCABIgDAEIgDAFIgFAGIgMAQIgBACIgCAAIgGAAIAAgyIAKAAIAAAhIAAACIgBADIACgEIABgBIAEgEIADgFIAFgGIALgQIABgCIACAAIAHAAIAAAygAUFgoIgFgBIgCgCIgJgQIgEgCIgDgBIgGAAIAAAWIgJAAIAAgyIAJAAIAAAVIAFAAIADgBIADgCIALgQIABgCIADAAIAHAAIgMATIgDADIgDACIAEACIADADIANAVgASYgoIAAgXIgXAAIAAAXIgKAAIAAgyIAKAAIAAAUIAXAAIAAgUIAKAAIAAAygARggoIAAghIAAgDIAAgCIgBACIgBACIgBABIgCAEIgFAFIgEAGIgMAQIgBACIgCAAIgGAAIAAgyIAKAAIAAAhIAAACIgBADIADgEIABgBIACgEIAEgFIAEgGIAMgQIABgCIADAAIAFAAIAAAygAN1goIAAhHIAWAAQAHAAAFABQAEACAEADIAFAHQACAEAAAFQgBAFgCAEQgBAEgDADQgEADgFACQgFACgGAAIgMAAIAAAagAN/hLIAMAAIAGgBQAEgBACgCIADgEIABgGIgBgGIgDgFIgFgCIgHgBIgMAAgAIugoIAAg/IgjAAIAAA/IgKAAIAAhHIA3AAIAABHgAFqgoIAAgyIATAAIAIAAIAGADIADAEIABAFIgBADIgBAEIgDACIgFADQAGABADADQADADAAAFQAAADgCADQgBADgCACIgHACIgHABgAFzguIALAAQAFAAACgDQADgCAAgEIAAgDIgCgCIgDgCIgFgBIgLAAgAFzhFIAKAAIAEAAIADgCIACgDIABgDIgBgDIgCgCIgCgCIgFAAIgKAAgAFcgoIgEgBIgCgCIgKgQIgDgCIgEgBIgFAAIAAAWIgKAAIAAgyIAKAAIAAAVIAFAAIADgBIADgCIAKgQIACgCIACAAIAIAAIgNATIgDADIgCACIADACIAEADIAMAVgAC2goIAAgzIAAgDIABgCIgZAsIgBACIgCAAIgBAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAIgZgsIABACIAAADIAAAzIgJAAIAAhHIAHAAIACAAIABABIAZAsIACAFIABgDIABgCIAZgsIABgBIACAAIAHAAIAABHgAAcgoIAAgyIAhAAIAAAHIgYAAIAAArgAhHgoIAVgcIACgDIADgCIgHADIgHABIgIgBIgGgEIgFgHQgBgEAAgFQAAgEACgEQABgFAEgDIAIgFQAEgBAFAAQAFAAAFABIAGAFQAEADABAFQACAEAAAFIgBAGIgBAFIgDAGIgEAFIgRAZIgCACIgCAAgAg9hnIgFADQgCABgBADIAAAGQAAAGADAEQAEAEAHAAIAFgBIAFgEIADgEIABgFIgBgGIgDgFIgFgCIgFgBIgGABgAiCgoIAAgHIAPAAIAAgwIAAgEIgMAKIgCABIgBAAIgBAAIgBgBIgCgEIAVgTIAHAAIAABBIAPAAIAAAHgAikgoIAAgSIggAAIgBgBIgBgCIgBgEIAigvIAJAAIAAAuIALAAIAAAGIgBABIgCABIgIAAIAAASgAi9hCIAZAAIAAgcIAAgDIABgEgAkwgoIAAgHIAPAAIAAgwIAAgEIgMAKIgCABIgBAAIgBAAIAAgBIgEgEIAWgTIAIAAIAABBIANAAIAAAHgAlrgoIAAgHIAPAAIAAgwIAAgEIgLAKIgCABIgCAAIgBAAIAAgBIgDgEIAVgTIAIAAIAABBIAOAAIAAAHgAn4goIAAhHIAsAAIAAAIIghAAIAAA/gAosgoIAAggIglAAIAAAgIgLAAIAAhHIALAAIAAAfIAlAAIAAgfIAKAAIAABHgArsgoIAAgyIAAgEIABgFIgDAEIgCAEIggAwIgCACIgDABIgIAAIAAhHIALAAIAAAxIgBAFIAAAFIACgEIACgEIAggwIADgCIADgBIAHAAIAABHgAuIgoIAAggIglAAIAAAgIgLAAIAAhHIALAAIAAAfIAlAAIAAgfIALAAIAABHgAvIgoIgCAAIgBgCIgHgRIggAAIgGARIgCACIgCAAIgIAAIAdhHIAKAAIAdBHgAvjhiIgCADIgKAdIAaAAIgLgdIgBgDIgBgEIgBAEgAwOgoIgDgBIgBgCIgTgaIgCgDIgFAAIgJAAIAAAgIgKAAIAAhHIAKAAIAAAfIAIAAIACgBIACAAIACgBIABgCIASgZIACgCIADAAIAIAAIgVAdQgCADgEACIAFACIADAEIAVAfgAmlgwIgBgBIABgDIAHgMIABgBIABgBIgBgBIgBgBIgHgNIgBgCIABgCIADgBIANATIAAABIgNAUgAm0gwIgBgBIAAgDIAIgMIABgBIAAgBIAAgBIgBgBIgIgNIAAgCIABgCIAEgBIAMATIAAABIgMAUgAxfhCIAAgBIANgTIADABIABACIAAACIgIANIgBACIABACIAIAMIAAADIgBABIgDACgAxthCIAAgBIAMgTIADABIACACIgBACIgHANIgCACIACACIAHAMIABADIgCABIgDACgAVchjIgEgCIgEgDIgBgFIABgCIACAAIAFAAIAAADIACADIACACIADAAIAEAAIACgCIACgDIAAgDIAFAAIACAAIABACIgBAFIgEADIgEACIgHABIgGgBg");
	this.shape_2.setTransform(150.6,576.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1E88BD").s().p("Ay8E5IAApxMAl5AAAIAAJxg");
	this.shape_3.setTransform(151,40,1.236,1.279);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(305));

	// knowmore
	this.instance_6 = new lib.knowmore();
	this.instance_6.parent = this;
	this.instance_6.setTransform(223.1,200.7,1.375,1.375);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(239).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(51).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// p4
	this.instance_7 = new lib.p4();
	this.instance_7.parent = this;
	this.instance_7.setTransform(120,260);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(225).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(64).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// p1
	this.instance_8 = new lib.p1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(120,260);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(305));

	// Слой 4
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1E88BD").s().p("A3TGkIAAtHMAunAAAIAANHg");
	this.shape_4.setTransform(150.3,82);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(305));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149.5,299.5,494.8,610.5);
// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x600_atlas_P_.png?1607200032327", id:"300x600_atlas_P_"},
		{src:"images/300x600_atlas_NP_.jpg?1607200032327", id:"300x600_atlas_NP_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;