(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [
		{name:"120x600_atlas_P_", frames: [[0,0,212,28],[0,57,215,20],[0,30,215,25]]},
		{name:"120x600_atlas_NP_", frames: [[0,0,160,600],[162,0,160,446],[162,448,160,446]]}
];


// symbols:



(lib._110 = function() {
	this.spriteSheet = ss["120x600_atlas_P_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.asd = function() {
	this.spriteSheet = ss["120x600_atlas_P_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.bg = function() {
	this.spriteSheet = ss["120x600_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bg2 = function() {
	this.spriteSheet = ss["120x600_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.bg3 = function() {
	this.spriteSheet = ss["120x600_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.shans = function() {
	this.spriteSheet = ss["120x600_atlas_P_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.z = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg2();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.z, new cjs.Rectangle(0,0,160,446), null);


(lib.y = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAbBFIABiCIgBAAQgCAPgCAHIgrBsIgWAAIAAiJIAPAAIAAB/IAAAAIAGgTIAqhsIAWAAIAACJg");
	this.shape.setTransform(64.7,0,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIABiCIgBAAIghCCIgRAAIghiCIgBAAIABCCIgPAAIAAiJIAaAAIAbBrQADAIAAAMIAAAAIADgVIAbhqIAbAAIAACJg");
	this.shape_1.setTransform(49.6,0,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaBFIAAg7IgUAAIgdA7IgRAAIAfg9QgbgIABgdQAAgnAoAAIAkAAIAACJgAgMgxQgIAGABAOQAAAPAJAHQAHAFAQAAIANAAIAAg0IgRAAQgOAAgHAFg");
	this.shape_2.setTransform(34.6,0,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgmBFIAAiJIAPAAIAAA7IATAAQArAAAAAnQAAAngoAAgAgXA3IASAAQAOAAAGgFQAIgGAAgOQAAgQgJgGQgHgFgRAAIgNAAg");
	this.shape_3.setTransform(23.5,0,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAaBFIAAhCIgzAAIAABCIgQAAIAAiJIAQAAIAAA7IAzAAIAAg7IAQAAIAACJg");
	this.shape_4.setTransform(10.7,0,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgiBFIAAiJIBEAAIAAAOIg1AAIAAAtIAyAAIAAAMIgyAAIAAA0IA1AAIAAAOg");
	this.shape_5.setTransform(-1,0,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmBFIAAiJIAkAAQAlAAAAAjQAAAYgUAGQAKABAHAIQAHAKAAANQAAATgLALQgKAKgSAAgAgXA3IAXAAQAXAAAAgaQAAgagYAAIgWAAgAgXgJIATAAQALAAAGgFQAGgGAAgMQAAgWgWAAIgUAAg");
	this.shape_6.setTransform(-12.5,0,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglAyQgHgQAAgiQAAhHAsAAQAtAAAABHQAAAigHAQQgKAWgcAAQgaAAgLgWgAgcgCQAAAgAFANQAGAPARAAQASAAAGgPQAGgNAAggQAAg3geAAQgcAAAAA3g");
	this.shape_7.setTransform(-25.3,0,1.176,1.176);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAaBFIAAhCIgzAAIAABCIgPAAIAAiJIAPAAIAAA7IAzAAIAAg7IAQAAIAACJg");
	this.shape_8.setTransform(-38.5,0,1.176,1.176);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgfBFIAAiJIA/AAIAAAOIgwAAIAAB7g");
	this.shape_9.setTransform(-49.1,0,1.176,1.176);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAqBFIABiCIgBAAIgFASIgdBwIgRAAIghiCIABCCIgPAAIAAiJIAbAAIAbBrIACAUIADgVIAbhqIAbAAIAACJg");
	this.shape_10.setTransform(-63,0,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.y, new cjs.Rectangle(-69.8,-8.4,139.6,16.9), null);


(lib.xcvbcxvb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAFAUIgFgOIgDANIgFAJIgMgHIAGgJIAJgIIgMACIgLAAIAAgLIALAAIANADIgKgKIgFgJIALgGIAFAJIADAMIAEgMIAFgJIALAFIgGAKIgJAKIAOgDIAKAAIAAALIgKAAIgNgCIAKAKIAEAIIgKAHg");
	this.shape.setTransform(76.1,-11);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPBhIAAgiIAfAAIAAAigAgJAvIgGg+IAAhRIAfAAIAABRIgEA+g");
	this.shape_1.setTransform(65.2,-2.1,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBhIgchIIgcBIIgpAAIAvhjIgsheIAqAAIAYA/IAag/IAqAAIgwBeIAyBjg");
	this.shape_2.setTransform(53.6,-2.1,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAbBhIAAhKQAAgrAFgXIg1CMIgoAAIAAjBIAjAAIAABJQAAAugFAVIA1iMIAoAAIAADBg");
	this.shape_3.setTransform(36.1,-2.1,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag+AjIAAhFQAAhCA+AAQA/AAAABCIAABFQAAAkgRAQQgQAOgeAAQg+AAAAhCgAgYgmIAABPQAAAeAYAAQAZAAAAgeIAAhOQAAgQgGgJQgHgIgMgBQgYABAAAgg");
	this.shape_4.setTransform(18.5,-2,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag6BhIAAjBIBDAAQAYAAAMAOQALANAAAUQAAAPgHAMQgHAOgMACQAdAKAAAkQAAAagLAPQgLAQgWAAgAgWBFIAXAAQAUABAAgfQAAgdgUAAIgXAAgAgWgRIAUAAQAWAAAAgaQAAgZgWAAIgUAAg");
	this.shape_5.setTransform(1.6,-2.1,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAoB0IAAgmIhPAAIAAAmIgkAAIAAhEIAMAAQAKgXAEgTQAEgXAAgmIAAg9IBtAAIAACkIAMAAIAABEgAgJgqQAAAfgEAVQgEASgJAUIA1AAIAAiGIgkAAg");
	this.shape_6.setTransform(-16.8,0.2,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAfBhIgJgyIgpAAIgLAyIgoAAIAxjBIAxAAIArDBgAgOASIAfAAIgPhZg");
	this.shape_7.setTransform(-42.7,-2.1,1.176,1.176);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAYBhIAAhaIgvAAIAABaIglAAIAAjBIAlAAIAABKIAvAAIAAhKIAlAAIAADBg");
	this.shape_8.setTransform(-60,-2.1,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.1,-13.9,146.1,27.8);


(lib.w = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.asd();
	this.instance.parent = this;
	this.instance.setTransform(-107.5,-10);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.w, new cjs.Rectangle(-107.5,-10,215,20), null);


(lib.vb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg3();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.vb, new cjs.Rectangle(0,0,160,446), null);


(lib.u = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAcBFIAAiCIAAAAQgDAPgDAHIgqBsIgWAAIAAiJIAPAAIAAB/IAAAAIAGgTIAqhsIAWAAIAACJg");
	this.shape.setTransform(43.9,-0.1,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIABiCIgBAAIgiCCIgRAAIghiCIABCCIgPAAIAAiJIAbAAIAbBqQABAFABAQIADgVIAchqIAbAAIAACJg");
	this.shape_1.setTransform(28.8,-0.1,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBFIAAiCIAAAAQgCANgEAJIgpBsIgXAAIAAiJIAQAAIgBB/IABAAQACgMADgHIAqhsIAWAAIAACJg");
	this.shape_2.setTransform(13.6,-0.1,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBFIAAiJIAQAAIAAB7IAqAAIAAh7IAPAAIAAB7IArAAIAAh7IAPAAIAACJg");
	this.shape_3.setTransform(-2.6,-0.1,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAYBFIAAhDQgMABgNAAQgTAAgIgGQgKgJAAgTIAAglIAPAAIAAAjQAAAOAFAFQAFAEAOAAQAQAAAHgBIAAg5IAPAAIAACJg");
	this.shape_4.setTransform(-18.3,-0.1,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgbBFIAAgOQADACAHAAQAIAAADgNIgohxIAQAAIAgBeIAdheIAQAAIgmBxQgFAPgFAGQgFAFgJAAQgJAAgDgBg");
	this.shape_5.setTransform(-29.9,0,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgwBFIAAgOIAGABQAKAAADgQQACgMAAglIAAg8IBMAAIAACJIgPAAIAAh7IgtAAIAAA2QgBAggDAOQgGAZgSAAg");
	this.shape_6.setTransform(-43.2,-0.1,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.u, new cjs.Rectangle(-49,-8.2,98,16.6), null);


(lib.t = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAPAAIAAA7IASAAQArAAABAnQgBAngoAAgAgpA3IASAAQAOAAAHgFQAHgGAAgOQAAgPgIgGQgIgFgQAAIgOAAg");
	this.shape.setTransform(21.5,0,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIABiCIgBAAIghCCIgRAAIgiiCIABCCIgQAAIAAiJIAbAAIAbBrIADAUIADgUIAbhrIAbAAIAACJg");
	this.shape_1.setTransform(4.7,0,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBFIAAiCIAAAAQgCAOgDAJIgrBrIgWAAIAAiJIAPAAIAAB/IAAAAIAGgTIAqhsIAWAAIAACJg");
	this.shape_2.setTransform(-10.5,0,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgpAaIAPAAQABAQAFAHQAHAJAOAAQAaAAAAgdQAAgKgHgIQgHgIgLAAIgMAAIAAgNIAKAAQAVAAAAgXQAAgYgVAAQgKAAgHAHQgGAHgBALIgQAAQADgSAKgKQALgLAQAAQAQAAALAKQAKAKAAAOQAAAZgVAIQAMADAHAIQAHAJAAAPQAAAPgIALQgLAPgXAAQgnAAgCgug");
	this.shape_3.setTransform(-23.3,0,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t, new cjs.Rectangle(-28.2,-8.4,56.5,16.9), null);


(lib.s = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAcBVIAAiCIAAAAQgDAPgDAHIgqBsIgWAAIAAiJIAPAAIAAB/QADgMADgHIAqhsIAWAAIAACJgAgShCQgHgGAAgMIAHAAQAEANAOAAQAOAAACgNIAIAAQAAAYgZAAQgKAAgHgGg");
	this.shape.setTransform(38.2,0,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgBFIgLgoIgqAAIgLAoIgQAAIAniJIATAAIAnCJgAgSAPIAkAAIgShIIAAAAg");
	this.shape_1.setTransform(25.4,1.9,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnBFIAAiJIAmAAQApAAAAAnQAAAngsAAIgUAAIAAA7gAgYgCIAPAAQARAAAHgFQAJgGAAgQQAAgOgIgGQgHgFgNAAIgUAAg");
	this.shape_2.setTransform(13.3,1.9,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfBFIAAiJIBAAAIAAAOIgxAAIAAB7g");
	this.shape_3.setTransform(2.8,1.9,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAcBFIAAiCQgDAPgDAHIgqBsIgWAAIAAiJIAPAAIAAB/IAAAAQADgMADgHIAqhsIAWAAIAACJg");
	this.shape_4.setTransform(-9.4,1.9,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAPAAIAAA6IASAAQAsAAAAAoQAAAngoAAgAgpA3IASAAQAOAAAIgFQAGgGAAgOQAAgQgIgGQgIgFgQAAIgOAAg");
	this.shape_5.setTransform(-24.5,1.9,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmBFIAAiJIAkAAQAlAAAAAiQAAAZgUAFIAAABQAKABAHAIQAHAJAAAOQAAAognAAgAgXA3IAXAAQAXAAAAgaQAAgagYAAIgWAAgAgXgKIATAAQALAAAGgFQAGgFAAgNQAAgVgVAAIgVAAg");
	this.shape_6.setTransform(-38.6,1.9,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.s, new cjs.Rectangle(-43.1,-9.9,86.4,19.9), null);


(lib.p = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgiBFIAAiJIBEAAIAAAOIg0AAIAAAtIAxAAIAAANIgxAAIAAAzIA1AAIAAAOg");
	this.shape.setTransform(48.6,-1.7,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAQAAIAAA7IASAAQArAAAAAnQAAAngpAAgAgoA3IARAAQAOAAAHgFQAHgGAAgOQAAgPgIgGQgHgFgSAAIgMAAg");
	this.shape_1.setTransform(34.5,-1.7,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaBFIAAhBIg0AAIAABBIgOAAIAAiJIAOAAIAAA7IA0AAIAAg7IAQAAIAACJg");
	this.shape_2.setTransform(19.5,-1.7,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAnBVIAAggIhNAAIAAAgIgPAAIAAguIAJAAQAJgPADgWQADgQAAgjIAAgjIBIAAIAAB7IALAAIAAAugAgOgiQAAAugNAbIA3AAIAAhtIgqAAg");
	this.shape_3.setTransform(6.2,0.2,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglAyQgHgQAAgiQAAhHAsAAQAbAAALAYQAIARAAAeQAAAigIAQQgKAWgcAAQgaAAgLgWgAgdgCQAAAfAGANQAHAQAQAAQARAAAHgQQAFgNABgfQAAgagHgNQgGgQgRAAQgdAAAAA3g");
	this.shape_4.setTransform(-7.2,-1.6,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAdBFIgdg6IgdA6IgRAAIAmhGIglhDIARAAIAcA2IAdg2IARAAIglBDIAmBGg");
	this.shape_5.setTransform(-19.7,-1.7,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAPAAIAAA7IATAAQArAAAAAnQAAAngoAAgAgpA3IASAAQAPAAAGgFQAHgGAAgOQAAgPgIgGQgHgFgSAAIgNAAg");
	this.shape_6.setTransform(-34,-1.7,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgmBFIAAiJIAkAAQASAAAKAKQAJAJAAAQQAAAYgUAGIAAAAQAKABAHAIQAHAKAAAOQAAAngnAAgAgXA3IAXAAQAXAAAAgaQAAgZgYAAIgWAAgAgXgJIATAAQAXAAAAgXQAAgWgVAAIgVAAg");
	this.shape_7.setTransform(-48.1,-1.7,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.p, new cjs.Rectangle(-52.7,-10.1,105.4,20.3), null);


(lib.o = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAbBhIAAhJQAAgsAFgXIg1CMIgoAAIAAjBIAiAAIAABJQAAAugEAVIAAAAIA1iMIAoAAIAADBg");
	this.shape.setTransform(84,-21.2,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBhIAAhJQAAgsAFgXIg1CMIgoAAIAAjBIAjAAIAABJQAAAugFAVIA1iMIAoAAIAADBg");
	this.shape_1.setTransform(66.3,-21.2,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAoB0IAAgnIhQAAIAAAnIgjAAIAAhEIAMAAQAKgXADgUQAEgWABgmIAAg8IBtAAIAACjIALAAIAABEgAgJgqQAAAggFAUQgEASgIAUIA1AAIAAiGIgkAAg");
	this.shape_2.setTransform(47.6,-18.9,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAYBhIAAhaIgvAAIAABaIglAAIAAjBIAlAAIAABLIAvAAIAAhLIAlAAIAADBg");
	this.shape_3.setTransform(29,-21.2,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAfBhIgJgzIgpAAIgLAzIgoAAIAxjBIAxAAIArDBgAgOASIAfAAIgPhag");
	this.shape_4.setTransform(11.7,-21.2,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhFBgIAAgbQAEABAIAAQAJAAADgMQADgOAAgxIAAhcIBwAAIAADAIglAAIAAijIgmAAIAABJQAAAxgKAWQgJAWgWAAQgOAAgJgCg");
	this.shape_5.setTransform(-6.8,-21,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAYBhIAAijIgvAAIAACjIglAAIAAjBIB5AAIAADBg");
	this.shape_6.setTransform(-24.2,-21.2,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAfBhIgJgzIgpAAIgLAzIgoAAIAxjBIAxAAIArDBgAgOASIAfAAIgPhag");
	this.shape_7.setTransform(-41.5,-21.2,1.176,1.176);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhFBgIAAgbQAEABAIAAQAJAAADgMQAEgOgBgxIAAhcIBwAAIAADAIglAAIAAijIgmAAIAABJQAAAxgKAWQgJAWgWAAQgOAAgJgCg");
	this.shape_8.setTransform(-60,-21,1.176,1.176);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag6BhIAAjBIBCAAQAZAAAMAPQALAMAAAUQAAAPgGAMQgIAOgMACQAdALAAAiQAAAbgLAPQgLAQgWAAgAgVBFIAWAAQAUAAAAgeQAAgegUAAIgWAAgAgVgRIATAAQAWAAgBgbQAAgYgUAAIgUAAg");
	this.shape_9.setTransform(-84.3,-21.2,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.o, new cjs.Rectangle(-91.2,-32.6,182.5,27.4), null);


(lib.i = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag6BhIAAjBIAlAAIAABLIAeAAQAWAAAOASQAOAQAAAWQAAAcgMARQgNARgWAAgAgVBFIAVAAQAVAAAAgeQAAgOgGgJQgFgJgKAAIgVAAg");
	this.shape.setTransform(61.4,-2.1,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag6AkIAAhGQAAhCA7AAQAdAAAPAPQAOAPAAAbIAAAJIgkAAIAAgEQAAgSgFgIQgFgHgMAAQgLAAgFAHQgFAIAAASIAABLQAAAUAFAHQAFAHALAAQAWABAAgjIAAgKIAkAAIAAAIQAABCg6AAQg7AAAAhBg");
	this.shape_1.setTransform(44.5,-2,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBhIAAhJQAAgvAEgUIAAAAIg1CMIgoAAIAAjBIAjAAIAABJQAAAugFAVIABAAIA0iMIAoAAIAADBg");
	this.shape_2.setTransform(27.3,-2.1,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhFBgIAAgbQAEACAIgBQAJAAADgLQADgPAAgwIAAheIBwAAIAADBIglAAIAAijIgmAAIAABKQAAAxgKAVQgJAXgXgBQgMAAgKgCg");
	this.shape_3.setTransform(8.5,-1.9,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgzBhIAAjBIBnAAIAAAeIhCAAIAAAtIA8AAIAAAcIg8AAIAAA8IBCAAIAAAeg");
	this.shape_4.setTransform(-7.4,-2.1,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAoB0IAAgnIhPAAIAAAnIgkAAIAAhEIAMAAQAKgWAEgVQAEgVAAgnIAAg8IBtAAIAACjIAMAAIAABEgAgJgqQAAAggFAUQgDASgKAUIA2AAIAAiGIgkAAg");
	this.shape_5.setTransform(-24.9,0.2,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag+AjIAAhFQAAhCA+AAQA/AAAABCIAABFQAAAkgRAQQgQAOgeAAQg+AAAAhCgAgYgmIAABOQAAAfAYAAQAZAAAAgfIAAhNQAAgQgGgJQgHgIgMgBQgYABAAAgg");
	this.shape_6.setTransform(-43.5,-2,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAYBhIAAijIgvAAIAACjIglAAIAAjBIB5AAIAADBg");
	this.shape_7.setTransform(-61.1,-2.1,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.i, new cjs.Rectangle(-68.3,-13.8,136.6,27.8), null);


(lib.f = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._110();
	this.instance.parent = this;
	this.instance.setTransform(-113,-12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.f, new cjs.Rectangle(-113,-12,212,28), null);


(lib.e = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.shans();
	this.instance.parent = this;
	this.instance.setTransform(-107.5,-12.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.e, new cjs.Rectangle(-107.5,-12.5,215,25), null);


(lib.cbcf = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFvLuQgFgCgEgDQgDgFgCgFQgCgGAAgHQAAgGACgGQACgGAEgDQADgEAGgDQAFgCAHAAQAHAAAFACQAFACAEAFQADAEACAGQACAFAAAGQAAAHgCAHQgCAFgEAEQgDAEgGACQgFACgGAAQgIAAgFgDgAFvLCQgFAGAAAKIABAIIADAHIAFAGQAEACAFAAQARAAAAgXIgBgIIgDgGIgFgGQgEgBgEAAQgJAAgEAFgAE2LvQgFgCgDgEQgDgEgCgGQgBgFAAgIQAAgOAHgIQAHgIANAAIAKABIAIACIgCAJIgHgDIgHAAQgSAAAAAVIABAJIADAGIAGAGQADACAFAAQAFgBADgBIAGgDIADAHQgDADgGACQgFABgFAAQgIAAgFgCgAEPLvQgCgCAAgDQAAgEACgBQACgCADAAQAEAAACACQACABAAAEQAAADgCACQgCACgEAAQgDAAgCgCgADaLuQgFgDgEgFQgDgFgCgIQgBgHAAgJQAAgTAHgLQAHgKANAAQAPAAAHAKQAGAKAAAUQAAATgHALQgHAKgOAAQgHAAgFgDgADZKyQgEAHAAAQIABANIADAJQACAFAEACQADACAEAAQAJAAAEgHQAFgJAAgPIgBgMIgDgKQgCgFgEgCQgDgCgFAAQgJAAgEAIgAgZLtQgDgFAAgJIAAghIgKAAIAAgIIAKAAIAAgMIAKgCIAAAOIASAAIAAAIIgSAAIAAAeQAAAHACACQACAEAEAAIAFgBIAFgBIACAGIgHADIgJABQgHAAgEgEgAihLwQgDgCgDgDQgDgCgBgFQgBgFAAgHIAAgiIAKAAIAAAgIABAIIACAFQAAABAAABQABAAAAABQABAAAAAAQABABAAAAQADABAEABQAGAAAFgFQAEgDACgGIAAglIAKAAIAAApIAAAJIABAIIgGAAIgDgKIgBAAQgDAFgFADQgFADgIAAIgJgBgAjDLxQgGAAgDgDQgEgDAAgHIAAhBIAKAAIAAA9QAAAEACADQABAAAAAAQABABAAAAQABAAAAAAQABABABAAIADgBIAEAAIABAHIgCABIgEABIgDAAIgDAAgAjtLvQgCgCAAgDQAAgEACgBQACgCADAAQAEAAACACQACABAAAEQAAADgCACQgCACgEAAQgDAAgCgCgAATLvQgDgBgCgCIgEgFQgCgDAAgEQAAgFACgDQACgEAEgDIAIgDIAIgBIAGAAIAEABIADAAIACAAIAAgDIAAgDIgBgFIgCgEIgEgBIgGgBIgEAAIgGABIgFACIgEACIgDgIQAKgGAPAAQAGABAEABQAEACADADIADAFIAAAHIAAAMIgBAOIABAIIABAHIgHAAIgDgJIgBAAIgDADIgEADIgGADIgHABQgEAAgEgCgAAXLXQgEACAAAGQAAAFADABQADADAFAAIAHgBIAEgDIAEgDIACgDIAAgIIgCgBIgDAAIgDAAIgFAAQgHAAgEACgAkILxIgRglIgCgLIgTAwIgFAAIgWg7IALAAIAMAhIACALIABAAIADgMIANggIAIAAIARAsIABAAIADgLIAKghIAKAAIgVA7gAllLxIgQglIgDgLIgTAwIgFAAIgWg7IALAAIAMAhIADALIABAAIADgMIANggIAIAAIAOAhIADALIABAAIACgLIALghIAKAAIgVA7gAnBLxIgRglIgCgLIgTAwIgFAAIgWg7IALAAIAMAhIACALIABAAIADgMIANggIAIAAIAOAhIADALIABAAIADgLIAKghIAKAAIgVA7gAHzLwIAAghIgBgIIgCgGQAAAAAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAIgGgBQgHAAgDADQgEAEgCAGIAAAmIgKAAIAAggIAAgJIgCgFQgBgCgDgCQgCgBgEAAQgFAAgEADQgEAEgCAEIAAAoIgKAAIAAg6IAHAAIACAHIABAAQADgDAFgDQAFgDAHAAQAGAAAEACQAEADACAGQADgFAFgDQAFgDAGAAQAGAAADABQAEABACAEQADADABAEIABAOIAAAhgACRLwIAAgJIAQAAIAAg0IACgHIgFAGIgNAJIgFgHIAbgTIAFAAIAABGIAQAAIAAAJgABPLwIAAgJIARAAIAAg0IABgHIgFAGIgNAJIgEgHIAagTIAFAAIAABGIARAAIAAAJgAg8LwIAAggIgBgJIgCgGIgEgDIgHgBIgGABIgFADIgEAEIgCAFIAAAmIgKAAIAAhNIAKAAIAAAaIABAAQAEgEAEgDQAFgCAHAAQAFAAAEABQAEABACAEQADADABAEQABAFAAAIIAAAigAB3J3IAAhQIAHAAIACAHIABAAQADgDAEgDQAFgCAGgBQANAAAGAIQAGAGAAAQQAAAHgCAGQgCAGgEAEQgEAEgFADQgGACgGAAIgEAAIgEgBIgDgBIgDgBIAAAXgACGIxQgDAEgCAHIAAAaIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgGQgDgGgJAAQgHAAgEADgAm0J3IAAhQIAHAAIACAHIABAAQADgDAEgDQAFgCAGgBQANAAAGAIQAGAGAAAQQAAAHgCAGQgCAGgEAEQgEAEgFADQgGACgGAAIgEAAIgEgBIgDgBIgDgBIAAAXgAmlIxQgDAEgCAHIAAAaIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgGQgDgGgJAAQgHAAgEADgAECJhQgCgCAAgEQAAgDACgBQACgDADAAQADAAACADQACABAAADQAAAEgCACQgCACgDAAQgDAAgCgCgADJJhQgGgCgDgFQgDgEgCgFQgCgGAAgHQAAgOAIgJQAHgIAOAAIAIABQAEABAEADQADADACAEQADAFAAAHIgBAEIAAAFIgpAAQAAAJAFAGQAEAFALAAIAJgBQAEgCADgDIADAIQgDADgGACQgGABgHABQgHAAgFgCgADJIyQgEAEgBAIIAgAAQAAgIgEgEQgEgEgGAAQgIAAgFAEgAA+JgQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAFACAEAEQADAEACAGQACAGAAAGQAAAHgCAGQgCAGgEADQgDAFgGACQgFACgGAAQgIgBgFgCgAA+I0QgFAFAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAntJgQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAFACAEAEQADAEACAGQACAGAAAGQAAAHgCAGQgCAGgEADQgDAFgGACQgFACgGAAQgIgBgFgCgAntI0QgFAFAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAg3JhQgDgCgCgCIgEgEQgCgDAAgFQAAgEACgEQACgEAEgCIAIgDIAIgBIAGAAIAEAAIADABIACAAIAAgDIAAgEIgBgEIgCgEIgEgCIgGgBIgEABIgGABIgFABIgEADIgDgJQAKgFAPAAQAGAAAEACQAEABADADIADAGIAAAGIAAANIgBANIABAIIABAHIgHAAIgDgIIgBAAIgDACIgEAEIgGACIgHABQgEAAgEgBgAgzJIQgEADAAAGQAAAEADACQADACAFABIAHgBIAEgDIAEgDIACgDIAAgJIgCAAIgDgBIgDAAIgFAAQgHAAgEACgAhzJiIgHgDIACgIIAHACIAJABQAQAAAAgKQAAgFgEgCQgEgBgJAAIgGAAIAAgIIAIAAIAFgBIAEgCIADgDIABgDQAAgFgEgCQgDgBgHAAIgJABIgHACIgCgHQAHgFAOAAQAKAAAGAEQAFADAAAIIgBADIgCAEIgDAEIgFABIAAACQAHABADAEQADAEAAAFIgBAHQgCADgDACIgJAEIgLABIgLAAgAk5JhQgEgCgCgCIgEgEQgBgDAAgFQAAgEACgEQACgEADgCIAIgDIAJgBIAGAAIAEAAIACABIACAAIABgDIAAgEIgBgEIgCgEIgEgCIgGgBIgFABIgFABIgFABIgEADIgDgJQAKgFAOAAQAHAAAEACQAEABACADIADAGIABAGIgBANIAAANIAAAIIABAHIgHAAIgDgIIgBAAIgDACIgEAEIgFACIgIABQgEAAgDgBgAk1JIQgFADAAAGQAAAEAEACQADACAFABIAGgBIAFgDIADgDIACgDIAAgJIgCAAIgCgBIgEAAIgFAAQgHAAgDACgAAMJhIAAgxIgTAAIAAgJIAxAAIAAAJIgUAAIAAAxgAiUJhIAAghIACgLIgBAAIgGALIgbAhIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA6gAjZJhIAAgZIgdAAIAAAZIgKAAIAAg6IAKAAIAAAYIAdAAIAAgYIAKAAIAAA6gAlvJhIAAg6IAmAAIAAAJIgbAAIAAAxgAECI1QgCgCAAgDQAAgDACgCQACgCADAAQADAAACACQACACAAADQAAADgCACQgCACgDAAQgDAAgCgCgAlLHhIgCgOIgxAAIAAg6IAKAAIAAAxIAcAAIAAgxIAKAAIAAAxIAJAAIAAAXgAAjHSQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAHgIAOAAIAJABQAEABADADQAEACACAFQACAEAAAIIAAADIgBAFIgpAAQAAAKAFAGQAFAEALAAIAJgBQAEgCACgCIAEAIQgEADgGACQgFABgHAAQgHAAgGgCgAAkGkQgFADAAAIIAfAAQABgIgEgDQgEgFgHAAQgIAAgEAFgAgdHSQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAHgIAOAAIAJABQAEABADADQADACACAFQACAEAAAIIAAADIgBAFIgoAAQAAAKAFAGQAFAEALAAIAJgBQAEgCABgCIAEAIQgEADgFACQgFABgHAAQgHAAgGgCgAgcGkQgFADAAAIIAfAAQABgIgEgDQgEgFgHAAQgIAAgEAFgAnzHSQgEgBgCgCIgEgFQgBgDAAgEQAAgFACgEQACgDADgCIAIgEIAJgBIAGAAIAEAAIACABIACAAIABgDIAAgDIgBgFIgCgDIgEgCIgGgBIgFAAIgFABIgFACIgEACIgDgIQAKgFAOgBQAHAAAEADQAEABACACIADAHIABAGIgBAMIAAANIAAAIIABAIIgHAAIgDgJIgBAAIgDADIgEAEIgFACIgIAAQgEAAgDgBgAnvG5QgFADAAAGQAAAFAEACQADACAFAAIAGgBIAFgCIADgEIACgDIAAgIIgCgBIgCAAIgEAAIgFAAQgHAAgDABgAhmHTIAAgiIABgLIgBAAIgFALIgbAiIgIAAIAAg6IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA6gAjLHTIAAgiIABgLIgBAAIgFALIgbAiIgIAAIAAg6IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA6gAkRHTIAAgiIACgLIgBAAIgGALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA6gAmVHTIgVgaIgGAAIAAAaIgKAAIAAg6IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAEIAHAGIAVAagAA2GRQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABgBABAAQABAAAAABQABAAAAAAQABAAAAABQABAAAAABQABAAAAAAQAAABAAAAQABABAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAgAAfGRQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAgBABAAQAAAAABAAQABgBAAAAQABAAAAABQABAAABAAQAAAAABABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAkZFaIAAhPIAHAAIACAGIABAAQADgEAEgCQAFgDAGAAQANABAGAGQAGAIAAAPQAAAHgCAGQgCAGgEAEQgEAEgFACQgGACgGAAIgEAAIgEAAIgDgBIgDgBIAAAXgAkKEVQgDADgCAHIAAAaIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgJgEgGQgDgGgJAAQgHAAgEAEgAAhFTIgBgPIgwAAIgCAPIgHAAIAAgYIAIAAIACgEIAEgJIADgPIABgUIAmAAIAAAwIAJAAIAAAYgAAAEeIgBAKIgCALIgEAIIAcAAIAAgoIgUAAIgBALgABBFDQgGgBgDgFQgDgDgCgHQgCgFAAgHQAAgOAIgJQAHgHAOgBIAIACQAEABAEACQADADACAEQADAFAAAHIgBAEIAAAEIgpAAQAAALAFAFQAEAFALAAIAJgCQAEgBADgCIADAIQgDACgGACQgGACgHgBQgHAAgFgCgABBEVQgEAEgBAIIAgAAQAAgIgEgEQgEgEgGAAQgIAAgFAEgAhCFDQgGgBgDgFQgDgDgCgHQgCgFAAgHQAAgOAIgJQAHgHAOgBIAIACQAEABAEACQADADACAEQADAFAAAHIgBAEIAAAEIgpAAQAAALAFAFQAEAFALAAIAJgCQAEgBADgCIADAIQgDACgGACQgGACgHgBQgHAAgFgCgAhCEVQgEAEgBAIIAgAAQAAgIgEgEQgEgEgGAAQgIAAgFAEgAjHFDQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgGQACgGAEgDQADgEAGgCQAFgCAHgBQAHAAAFADQAFACAEAEQADAFACAFQACAFAAAHQAAAHgCAGQgCAFgEAEQgDAFgGABQgFACgGAAQgIABgFgDgAjHEWQgFAGAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAFgAmyFDQgGgBgDgFQgDgDgCgHQgCgFAAgHQAAgOAIgJQAHgHAOgBIAIACQAEABAEACQADADACAEQADAFAAAHIgBAEIAAAEIgpAAQAAALAFAFQAEAFALAAIAJgCQAEgBADgCIADAIQgDACgGACQgGACgHgBQgHAAgFgCgAmyEVQgEAEgBAIIAgAAQAAgIgEgEQgEgEgGAAQgIAAgFAEgAiEFEIgJAAIAAAAIgBAAIAAg6IAEAAIAIAAIAJgBQANAAAGAEQAFAEAAAGQAAAEgCAEQgDAEgGACIAAABQAHACAEADQADADAAAGQAAAIgHAFQgIAEgOAAIgJgBgAiEE8IAFAAIAFAAQAJAAAEgBQAEgDAAgFIgBgEIgCgDIgFgCIgIgBIgLAAgAiEEiIANAAIAEAAIAEgCIADgCIABgEQAAgFgDgBQgDgCgIgBIgFABIgGAAgAEjFEIAAgXIgLACIgQAVIgNAAIAPgTIAGgEQgIgBgEgEQgFgFAAgGQAAgGACgDQACgFAEgBQAEgDAFgBQAFgCAGAAIAJABIAJACIAAA5gAEOEUQgEACAAAHQAAAFAFADQAFACAIAAIAHAAIAAgVIgEgBIgEAAQgJAAgEADgADjFEIAAghIABgMIgBAAIgFALIgbAiIgIAAIAAg5IAKAAIAAAhIgBALIABAAIAGgLIAaghIAIAAIAAA5gACeFEIAAgZIgdAAIAAAZIgLAAIAAg5IALAAIAAAXIAdAAIAAgXIAKAAIAAA5gAk3FEIAAgxIgcAAIAAAxIgKAAIAAg5IAxAAIAAA5gAnVFEIgUgaIgGAAIAAAaIgLAAIAAg5IALAAIAAAaIAGgDIATgXIALAAIgSAVIgGAFIAHAFIAUAagAn6DLIACgIIADAAIAEAAIADgDIADgEIACgGIgZg6IAMAAIASAvIABAAIADgLIAMgkIAKAAIgTA0IgEALIgFAJQgCADgDACQgDADgFAAIgHgBgADgDMIAAhQIAHAAIACAHIABAAQADgEAEgCQAFgDAGAAQANAAAGAHQAGAHAAAQQAAAGgCAGQgCAHgEADQgEAEgFADQgGACgGAAIgEAAIgEgBIgDgBIgDgBIAAAYgADvCGQgDAEgCAGIAAAaIAFADIAIABQAJAAAFgFQAFgGAAgLQAAgKgEgGQgDgFgJAAQgHAAgEADgAgBDBQADgCACgDQACgDAAgDQgDABgCgCQgBgBAAgDQAAgEABgCQACgBADAAQAEAAACACQADADAAAFQAAAEgCADIgDAFIgEAEIgFACgAGWDEIgBgPIgxAAIgCAPIgHAAIAAgXIAIAAIACgEIAEgKIADgPIABgUIAnAAIAAAxIAJAAIAAAXgAF1CPIgCALIgCAKIgEAJIAdAAIAAgoIgUAAIgBAKgACnC0QgFgBgEgFQgDgDgCgHQgCgFAAgHQAAgGACgGQACgGAEgDQADgEAGgDQAFgCAHAAQAHAAAFADQAFACAEAEQADAEACAGQACAFAAAGQAAAIgCAFQgCAGgEAEQgDAEgGACQgFACgGAAQgIAAgFgDgACnCIQgFAFAAALIABAJIADAHIAFAEQAEACAFAAQARABAAgXIgBgIIgDgHIgFgEQgEgCgEAAQgJgBgEAGgAk8C0QgFgBgDgFQgEgDgBgHQgCgFAAgHQAAgGACgGQACgGADgDQAEgEAFgDQAFgCAHAAQAHAAAFADQAGACADAEQAEAEABAGQACAFAAAGQAAAIgCAFQgCAGgDAEQgEAEgFACQgFACgHAAQgHAAgGgDgAk8CIQgEAFAAALIABAJIADAHIAFAEQADACAFAAQARABAAgXIgBgIIgDgHIgFgEQgDgCgFAAQgIgBgFAGgAm1C1QgFgDgDgEQgDgDgCgGQgBgGAAgHQAAgOAHgIQAHgIANAAIAKABIAIACIgCAJIgHgCIgHgBQgSgBAAAWIABAJIADAHIAGAEQADACAFAAQAFAAADgBIAGgDIADAIQgDACgGABQgFACgFAAQgIAAgFgCgAj5C2IgIgBIgBAAIgBAAIAAg5IAFAAIAHgBIAKAAQANAAAFADQAGAEAAAHQAAAEgDADQgDAEgFADIAAABQAHABADADQADAEAAAFQAAAJgHAEQgHAFgPgBIgJAAgAj4CtIAEABIAGAAQAJAAAEgCQADgDAAgFIAAgDIgDgDIgFgCIgHgBIgLAAgAj4CUIAMAAIAFgBIAEgCIACgCIABgDQAAgGgDgBQgDgCgHAAIgFABIgGAAgAmPC2IgDgBIACgKIADABQACAAADgCQACgCABgFIADgOIABgZIAmAAIAAA5IgKAAIAAgwIgTAAIAAACIgCAUQgBAJgCAGQgCAGgDADQgDADgFAAIgFAAgAFIC1IAAgWIgLABIgQAVIgNAAIAPgTIAGgDQgIgBgEgFQgFgFAAgGQAAgFACgEQACgEAEgCQAEgDAFAAQAFgCAGAAIAJABIAJABIAAA5gAEzCGQgEACAAAGQAAAGAFACQAFADAIgBIAHAAIAAgUIgEgBIgEAAQgJAAgEADgAB9C1IAAgwIgcAAIAAAwIgLAAIAAg5IAxAAIAAA5gAgWC1IgNgQIgFgIIgEAIIgNAQIgLAAIAWgdIgVgcIANAAIALAOIAEAIIAFgIIALgOIAMAAIgVAcIALAPIALAOgAhbC1IAAgWIgLABIgQAVIgNAAIAPgTIAGgDQgIgBgEgFQgFgFAAgGQAAgFACgEQACgEAEgCQAEgDAFAAQAFgCAGAAIAJABIAJABIAAA5gAhwCGQgEACAAAGQAAAGAFACQAFADAIgBIAHAAIAAgUIgEgBIgEAAQgJAAgEADgAibC1IAAggIABgMIgBAAIgFALIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gAGnCaIAAgJIAdAAIAAAJgAjSA9IAAhPIAHAAIACAIIABAAQADgFAEgCQAFgDAGABQANgBAGAIQAGAGAAAPQAAAHgCAGQgCAGgEAEQgEAEgFACQgGACgGABIgEAAIgEgBIgDgBIgDgBIAAAXgAjDgIQgDAEgCAFIAAAbIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgFQgDgGgJAAQgHAAgEADgAlSA9IAAgWIgFACIgEAAQgMAAgGgIQgGgHAAgQQAAgNAHgIQAGgIANAAIADAAIAEABIAAgTIAKAAIAAATIAEgBIAEAAQAMAAAGAHQAHAHAAAOQAAAHgCAGIgFAKQgDAEgFACQgFADgGAAIgDAAIgEgCIAAAWgAlJgKIAAAqIAEABIADAAQAIgBAEgGQAEgGAAgLIAAgJQgBgCgCgDQgCgDgEgBIgIgBIgCAAIgEAAgAllgGQgEAGAAAKIABAJIADAHQACADADABQADADAEAAIADAAIAEgBIAAgqIgDAAIgDAAQgIAAgFAEgAA3A1IgCgOIgxAAIAAg5IALAAIAAAwIAbAAIAAgwIAKAAIAAAwIAKAAIAAAXgAE4AgQgHgJAAgSIABgQQABgGADgGQACgEADgCQADgEAEgBIAIgCIAJgBIALgBQADAAADgDIABAJIgHADIgMABIgJACIgHACQgDACgCAFQgCAEgBAGIABABQAEgGAGgCQAFgCAHAAQAMAAAGAHQAHAGAAANQAAAHgCAHQgCAFgEAEQgEADgFACQgFACgGABQgPAAgHgJgAFBgCQgFAEAAAJIABAIIADAHIAGAEQADACAEAAQASAAAAgVIgBgIIgDgFQgCgCgDgCQgDgBgEgBQgKAAgEAGgAD7AmQgFgCgEgEQgDgEgCgGQgCgFAAgHQAAgHACgEQACgHAEgDQADgEAGgDQAFgBAHAAQAHgBAFADQAFACAEAFQADAEACAFQACAFAAAGQAAAHgCAGQgCAGgEAEQgDADgGACQgFACgGABQgIAAgFgDgAD7gGQgFAGAAAKIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgGIgFgFQgEgCgEAAQgJAAgEAFgAkLAmQgFgCgEgEQgDgEgCgGQgCgFAAgHQAAgHACgEQACgHAEgDQADgEAGgDQAFgBAHAAQAHgBAFADQAFACAEAFQADAEACAFQACAFAAAGQAAAHgCAGQgCAGgEAEQgDADgGACQgFACgGABQgIAAgFgDgAkLgGQgFAGAAAKIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgGIgFgFQgEgCgEAAQgJAAgEAFgAg0AmQgDgBgCgCIgEgFQgCgDAAgDQAAgGACgDQACgDAEgDIAIgDIAIgBIAGAAIAEAAIADABIACAAIAAgEIAAgCIgBgFIgCgDIgEgBIgGgBIgEAAIgGABIgFABIgEACIgDgIQAKgFAPAAQAGAAAEACQAEACADACIADAGIAAAHIAAAKIgBAOIABAIIABAHIgHAAIgDgJIgBAAIgDAEIgEADIgGACIgHABQgEAAgEgCgAgwAOQgEACAAAHQAAAEADACQADADAFAAIAHgCIAEgCIAEgDIACgEIAAgIIgCgBIgDAAIgDAAIgFAAQgHAAgEACgACyAnIAAgXIgLACIgQAVIgNAAIAPgTIAGgEQgIgBgEgFQgFgEAAgGQAAgEACgFQACgEAEgCQAEgCAFgBQAFgCAGABIAJAAIAJABIAAA5gACdgIQgEADAAAFQAAAFAFADQAFADAIgBIAHAAIAAgUIgEAAIgEAAQgJgBgEADgAByAnIAAghIABgLIgBAAIgFALIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gAhXAnIABgsIgCAAIgFAIIgPAXIgDAAIgQgXIgEgIIgBAAIABALIAAAhIgKAAIAAg5IALAAIARAZIAEAIIAVghIALAAIAAA5gAmNAnIAAgZIgdAAIAAAZIgKAAIAAg5IAKAAIAAAXIAdAAIAAgXIAKAAIAAA5gAnSAnIAAghIACgLIgBAAIgGALIgbAhIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA5gAkhhRIAAhPIAHAAIACAHIABAAQADgEAEgDQAFgCAGAAQANAAAGAHQAGAHAAAPQAAAHgCAHQgCAFgEAFQgEAEgFACQgGACgGAAIgEAAIgEAAIgDgBIgDgCIAAAXgAkSiWQgDADgCAHIAAAaIAFAEIAIABQAJAAAFgHQAFgFAAgMQAAgJgEgFQgDgHgJABQgHAAgEADgAk0hYIgCgOIgxAAIgCAOIgGAAIAAgXIAHAAIADgFIADgJIADgPIACgUIAmAAIAAAxIAKAAIAAAXgAlViNIgCALIgDALIgDAIIAcAAIAAgpIgTAAIgBALgAiShtQgHgJAAgSIABgRQABgHADgFQACgEADgDQADgDAEgCIAIgCIAJgBIALAAQADgBADgCIABAJIgHADIgMAAIgJACIgHADQgDACgCAEQgCAFgBAGIABAAQAEgFAGgCQAFgDAHAAQAMAAAGAHQAHAHAAANQAAAIgCAGQgCAGgEAEQgEADgFACQgFACgGAAQgPAAgHgIgAiJiRQgFAGAAAJIABAIIADAGIAGAFQADABAEABQASAAAAgWIgBgHIgDgGQgCgDgDgCQgDgBgEAAQgKAAgEAFgAjPhoQgFgCgEgDQgDgFgCgFQgCgGAAgHQAAgGACgGQACgGAEgDQADgEAGgDQAFgCAHAAQAHAAAFACQAFACAEAFQADAEACAFQACAGAAAGQAAAHgCAHQgCAFgEAEQgDAEgGACQgFACgGAAQgIAAgFgDgAjPiUQgFAGAAAKIABAIIADAIIAFAFQAEACAFAAQARAAAAgXIgBgIIgDgGIgFgGQgEgBgEAAQgJAAgEAFgAmehoQgFgCgEgDQgDgFgCgFQgCgGAAgHQAAgGACgGQACgGAEgDQADgEAGgDQAFgCAHAAQAHAAAFACQAFACAEAFQADAEACAFQACAGAAAGQAAAHgCAHQgCAFgEAEQgDAEgGACQgFACgGAAQgIAAgFgDgAmeiUQgFAGAAAKIABAIIADAIIAFAFQAEACAFAAQARAAAAgXIgBgIIgDgGIgFgGQgEgBgEAAQgJAAgEAFgAgFhnQgEgBgCgCIgEgFQgBgDAAgEQAAgFACgDQACgEADgDIAIgDIAIgBIAGAAIAEABIACAAIACAAIABgDIAAgDIgBgFIgCgEIgEgBIgGgBIgFAAIgEABIgFACIgEACIgDgIQAKgGANABQAHgBAEACQAEACACADIADAFIABAHIgBAMIAAAOIAAAIIABAHIgHAAIgDgJIgBAAIgDADIgEADIgFADIgIABQgDAAgDgCgAgBh/QgFACAAAGQAAAFAEABQACADAFAAIAGgBIAFgDIADgCIACgEIAAgIIgCgBIgCAAIgEAAIgFAAQgHAAgCACgABVhmIAAgYIgKACIgRAWIgMAAIAOgUIAGgEQgHgBgFgEQgEgEAAgHQAAgFACgEQACgEADgCQAEgCAFgCQAGgBAGAAIAJABIAIABIAAA6gABBiXQgEADAAAGQAAAFAEADQAFADAIgBIAHAAIAAgVIgEAAIgEAAQgIAAgEACgAgphmIAAgZIgdAAIAAAZIgKAAIAAg6IAKAAIAAAYIAdAAIAAgYIAKAAIAAA6gAnJhmIAAhEIglAAIAABEIgLAAIAAhOIA7AAIAABOgAjBjfIAAhQIAHAAIACAHIABAAQADgDAFgDQAFgCAGgBQAMAAAGAIQAGAGAAAQQAAAHgCAGQgCAGgDAEQgEAEgGADQgFACgHAAIgEAAIgDgBIgDgBIgDgBIAAAXgAixklQgEAEgBAHIAAAaIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgGQgEgGgJAAQgGAAgEADgAGmjnIgCgOIgxAAIgCAOIgGAAIAAgWIAHAAIADgFIADgKIADgOIACgVIAmAAIAAAyIAKAAIAAAWgAGFkcIgCAMIgDAKIgDAJIAcAAIAAgpIgTAAIgBAKgAH3j1QgDgCAAgEQAAgDADgBQACgDADAAQADAAACADQACABAAADQAAAEgCACQgCACgDAAQgDAAgCgCgAE8j2QgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAFACAEAEQADAEACAGQACAGAAAGQAAAHgCAGQgCAGgEADQgDAFgGACQgFACgGAAQgIgBgFgCgAE8kiQgFAFAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAAvj2QgFgDgEgFQgDgGgCgHQgBgIAAgJQAAgTAHgKQAHgLANAAQAPAAAHALQAGAKAAATQAAATgHALQgHALgOAAQgHAAgFgDgAAukzQgEAIAAAPIABANIADAKQACAEAEADQADACAEAAQAJgBAEgHQAFgIAAgQIgBgMIgDgKQgCgEgEgCQgDgCgFgBQgJABgEAHgAkCj8QgHgIAAgTIABgRQABgHACgEQACgFADgDQADgCAEgCIAIgCIAKgBIAKgBQAEAAACgCIABAJIgGACIgMABIgKABIgHAEQgDACgCAEQgCAEAAAHIABAAQAEgFAFgDQAFgCAIAAQALAAAHAGQAGAIAAANQAAAIgCAFQgCAGgDAEQgEAEgFACQgFACgHAAQgOAAgHgJgAj6kfQgEAFAAAKIABAIIADAGIAFAFQADABAFAAQARAAAAgVIgBgIIgDgGQgBgDgEgBQgDgCgEAAQgKABgEAFgAntj2QgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAFACAEAEQADAEACAGQACAGAAAGQAAAHgCAGQgCAGgEADQgDAFgGACQgFACgGAAQgIgBgFgCgAntkiQgFAFAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAG/j1QgDgCgCgCIgEgEQgCgDAAgFQAAgEACgEQACgEAEgCIAIgEIAIAAIAGAAIAEAAIADAAIACAAIAAgCIAAgEIgBgEIgCgEIgEgCIgGgBIgEABIgGABIgFABIgEADIgDgJQAKgFAPAAQAGAAAEACQAEABADADIADAGIAAAGIAAANIgBANIABAIIABAHIgHAAIgDgIIgBAAIgDACIgEAEIgGACIgHABQgEAAgEgBgAHDkOQgEADAAAGQAAAEADACQADACAFABIAHgBIAEgDIAEgDIACgDIAAgJIgCAAIgDgBIgDAAIgFAAQgHAAgEACgAECj1IAAg6IAmAAIAAAJIgbAAIAAAxgACqj1IAeg/IAFgGIgHABIghAAIAAgJIAzAAIAAADIgjBKgABpj1IAAgJIAQAAIAAg0IACgGIgFAGIgNAIIgFgHIAbgTIAFAAIAABGIAQAAIAAAJgAgfj1IAAgEIAHgGIAHgIIAIgJIAHgLIAEgKQACgFAAgEQAAgGgDgDQgCgDgHAAIgJABIgHAFIgFgHIALgHQAFgCAHAAQAKABAFAFQAGAGAAAIQAAAFgCAGIgGANIgIALIgJALIgGAFIAAAAIAIgBIAZAAIAAAJgAhZj1IAAgXIgKABIgRAWIgMAAIAOgTIAGgEQgHgBgFgEQgEgFAAgHQAAgEACgFQACgDADgCQAEgDAFgBQAGgBAGgBIAJABIAIABIAAA6gAhtklQgEADAAAFQAAAGAEACQAFADAIAAIAHAAIAAgVIgEgBIgEAAQgIABgEACgAkkj1IAAgXIgKABIgRAWIgMAAIAOgTIAGgEQgHgBgFgEQgEgFAAgHQAAgEACgFQACgDADgCQAEgDAFgBQAGgBAGgBIAJABIAIABIAAA6gAk4klQgEADAAAFQAAAGAEACQAFADAIAAIAHAAIAAgVIgEgBIgEAAQgIABgEACgAluj1IAAgxIgUAAIAAgJIAyAAIAAAJIgUAAIAAAxgAmPj1IgVgaIgGAAIAAAaIgKAAIAAg6IAKAAIAAAaIAGgCIAUgYIALAAIgTAXIgGAEIAHAFIAVAagAA1luIAAhPIAHAAIACAHIABAAQADgEAEgCQAFgDAGAAQANAAAGAHQAGAHAAAQQAAAHgCAFQgCAGgEAEQgEAEgFADQgGACgGAAIgEAAIgEgBIgDAAIgDgBIAAAWgABEmzQgDADgCAHIAAAbIAFADIAIAAQAJABAFgHQAFgFAAgLQAAgKgEgFQgDgHgJAAQgHABgEADgAHOmFQgFgCgDgGQgEgFgBgIQgCgHAAgJQAAgTAHgLQAHgKAOAAQAOAAAHAKQAHALAAATQAAATgHALQgHAKgOAAQgHAAgGgDgAHOnCQgEAJAAAPIABAMIADAKQACAEADADQADACAFAAQAJAAAEgIQAEgHAAgQIgBgNIgDgJQgCgEgDgDQgDgCgFAAQgJAAgEAHgAGLmDIgIgCIADgJIAGACIAJABIAHgBIAGgDQADgCABgDQABgDAAgDQAAgIgEgDQgFgEgJABIgJAAIAAgFIARgWIAFgFIgfAAIAAgJIAsAAIAAAFIgTAZIgEADIAEAAQAEgBAEACQAEABADAEIAFAGQACAEAAAFQAAAGgDAFQgCAEgEADQgEAEgFACQgFABgGAAIgKgBgAEqmEQgFgDgEgEQgDgEgCgGQgCgFAAgGQAAgIACgFQACgGAEgEQADgEAGgCQAFgCAHAAQAHAAAFADQAFABAEAFQADAEACAFQACAGAAAHQAAAHgCAFQgCAGgEAEQgDAEgGACQgFACgGAAQgIAAgFgCgAEqmxQgFAGAAALIABAIIADAGIAFAGQAEABAFAAQARAAAAgVIgBgIIgDgIIgFgFQgEgCgEAAQgJABgEAFgAgMmLQgHgIAAgTIABgRQABgGADgFQACgEADgDQADgDAEgBIAHgDIAJgBIALgBQADAAADgCIABAJIgHACIgMABIgJACIgGADQgDACgCAFQgCAEgBAGIABABQAEgGAFgCQAFgCAHAAQAMgBAGAHQAHAHAAAOQAAAHgCAGQgCAFgEAEQgEAEgFACQgFACgGAAQgOAAgHgJgAgDmuQgFAGAAAJIABAIIADAGIAFAFQADACAEgBQASAAAAgUIgBgIIgDgHQgCgCgDgBQgDgCgEAAQgKAAgDAFgAj8mEQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAHgIAOAAIAJABQAEABADADQAEACACAFQACAEAAAIIAAADIgBAFIgpAAQAAAKAFAGQAFAEALAAIAJgBQAEgCACgCIAEAIQgEADgGACQgFABgHAAQgHAAgGgCgAj7myQgFADAAAIIAfAAQABgIgEgDQgEgFgHAAQgIAAgEAFgAk0mEQgFgDgEgEQgDgDgBgGQgCgGAAgGQAAgPAHgIQAIgIANAAIAKABIAIADIgDAIIgGgDIgIgBQgSAAAAAXIABAIIADAGIAGAGQAEABAFAAQAEABAEgCIAGgDIADAHQgEAEgFABQgFABgGAAQgHAAgFgCgAnumEQgFgDgEgEQgDgDgBgGQgCgGAAgGQAAgPAHgIQAIgIANAAIAKABIAIADIgDAIIgGgDIgIgBQgSAAAAAXIABAIIADAGIAGAGQAEABAFAAQAEABAEgCIAGgDIADAHQgEAEgFABQgFABgGAAQgHAAgFgCgAEAmDIAAgyIgcAAIAAAyIgLAAIAAg6IAxAAIAAA6gACdmDIAAgYIgLACIgQAWIgNAAIAPgTIAGgFQgIAAgEgFQgFgFAAgGQAAgFACgEQACgEAEgCQAEgCAFgCQAFgBAGAAIAJAAIAJACIAAA6gACImzQgEACAAAGQAAAFAFADQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgJAAgEADgAgtmDIAAgYIgLACIgQAWIgNAAIAPgTIAGgFQgIAAgEgFQgFgFAAgGQAAgFACgEQACgEAEgCQAEgCAFgCQAFgBAGAAIAJAAIAJACIAAA6gAhCmzQgEACAAAGQAAAFAFADQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgJAAgEADgAh3mDIAAgyIgUAAIAAgIIAyAAIAAAIIgUAAIAAAygAifmDIAAgaIgdAAIAAAaIgKAAIAAg6IAKAAIAAAXIAdAAIAAgXIAKAAIAAA6gAmDmDIAAgYIglAAIAAgEIAogzIAHAAIAAAuIAOAAIAAAJIgOAAIAAAYgAmGm7IgRAUIgGAEIAJgBIARAAIAAgVIABgJgAm2n8IAAhPIAHAAIACAGIABAAQADgEAFgCQAFgDAGAAQAMABAGAGQAGAIAAAPQAAAHgCAGQgCAGgDAEQgEAEgGACQgFACgHAAIgEAAIgDAAIgDgBIgDgBIAAAXgAmmpBQgEADgBAHIAAAaIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgJgEgGQgEgGgJAAQgGAAgEAEgAFxoDIgCgPIgxAAIAAg5IALAAIAAAwIAbAAIAAgwIAKAAIAAAwIAKAAIAAAYgAh6oDIgCgPIgxAAIgCAPIgGAAIAAgYIAHAAIADgEIADgJIADgPIACgUIAmAAIAAAwIAKAAIAAAYgAibo4IgCAKIgDALIgDAIIAcAAIAAgoIgTAAIgBALgAhboTQgFgBgDgFQgEgDgBgHQgCgFAAgHQAAgOAHgJQAHgHAOgBIAJACQAEABADACQAEADACAEQACAFAAAHIAAAEIgBAEIgpAAQAAALAFAFQAFAFALAAIAJgCQAEgBACgCIAEAIQgEACgGACQgFACgHgBQgHAAgGgCgAhapBQgFAEAAAIIAfAAQABgIgEgEQgEgEgHAAQgIAAgEAEgAjfoTQgFgBgDgFQgEgDgBgHQgCgFAAgHQAAgOAHgJQAHgHAOgBIAJACQAEABADACQAEADACAEQACAFAAAHIAAAEIgBAEIgpAAQAAALAFAFQAFAFALAAIAJgCQAEgBACgCIAEAIQgEACgGACQgFACgHgBQgHAAgGgCgAjepBQgFAEAAAIIAfAAQABgIgEgEQgEgEgHAAQgIAAgEAEgAlkoTQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgHACgGQACgGADgDQAEgEAFgCQAFgCAHgBQAHAAAFADQAGACADAEQAEAFABAFQACAFAAAHQAAAHgCAGQgCAFgDAEQgEAFgFABQgFACgHAAQgHABgGgDgAlkpAQgEAGAAALIABAIIADAHIAFAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgDgCgFAAQgIAAgFAFgADJoTQgDAAgCgCIgEgGQgCgCAAgFQAAgFACgDQACgEAEgCIAIgEIAIgBIAGAAIAEABIADAAIACAAIAAgDIAAgCIgBgGIgCgDIgEgBIgGgCIgEABIgGABIgFACIgEABIgDgIQAKgFAPAAQAGAAAEACQAEABADADIADAGIAAAHIAAAMIgBANIABAIIABAHIgHAAIgDgJIgBAAIgDADIgEAEIgGACIgHABQgEAAgEgCgADNorQgEADAAAFQAAAFADACQADADAFgBIAHgBIAEgCIAEgDIACgEIAAgIIgCgBIgDAAIgDAAIgFAAQgHAAgEACgAkhoSIgIAAIgBAAIgBAAIAAg6IAFAAIAHAAIAKgBQANAAAFAEQAGAEAAAGQAAAEgDAEQgDAEgFACIAAABQAHACADADQADADAAAGQAAAIgHAFQgHAEgPAAIgJgBgAkgoaIAEAAIAGAAQAJAAAEgCQADgCAAgFIAAgEIgDgDIgFgCIgHgBIgLAAgAkgo0IAMAAIAFAAIAEgCIACgCIABgEQAAgFgDgBQgDgCgHgBIgFABIgGAAgAHxoSIAAghIACgMIgBAAIgGALIgbAiIgIAAIAAg5IALAAIAAAhIgBALIABAAIAFgLIAbghIAHAAIAAA5gAGsoSIAAghIABgMIgBAAIgFALIgbAiIgIAAIAAg5IAKAAIAAAhIgBALIABAAIAGgLIAaghIAIAAIAAA5gAEnoSIgUgaIgGAAIAAAaIgLAAIAAg5IALAAIAAAaIAGgDIATgXIALAAIgSAVIgGAFIAHAFIAUAagACGoSIAAgXIgKACIgRAVIgMAAIAOgTIAGgEQgHgBgFgEQgEgFAAgGQAAgGACgDQACgFADgCQAEgCAFgBQAGgCAGAAIAJABIAIACIAAA5gABypCQgEACAAAHQAAAFAEADQAFACAIAAIAHAAIAAgVIgEgBIgEAAQgIAAgEADgABGoSIAAghIACgMIgBAAIgGALIgbAiIgIAAIAAg5IALAAIAAAhIgBALIABAAIAFgLIAbghIAHAAIAAA5gAABoSIAAgZIgcAAIAAAZIgKAAIAAg5IAKAAIAAAXIAcAAIAAgXIAKAAIAAA5gAnToSIAAgxIgcAAIAAAxIgLAAIAAg5IAxAAIAAA5gAAUqKIAAhQIAHAAIACAHIABAAQADgEAEgCQAFgDAGAAQANAAAGAHQAGAHAAAQQAAAGgCAGQgCAHgEADQgEAEgFADQgGACgGAAIgEAAIgEgBIgDgBIgDgBIAAAYgAAjrQQgDAEgCAGIAAAaIAFADIAIABQAJAAAFgFQAFgGAAgLQAAgKgEgGQgDgFgJAAQgHAAgEADgAj9qSIgCgPIgxAAIAAg5IAKAAIAAAxIAcAAIAAgxIAKAAIAAAxIAJAAIAAAXgABmqiQgFgBgEgFQgDgDgCgHQgCgFAAgHQAAgGACgGQACgGAEgDQADgEAGgDQAFgCAHAAQAHAAAFADQAFACAEAEQADAEACAGQACAFAAAGQAAAIgCAFQgCAGgEAEQgDAEgGACQgFACgGAAQgIAAgFgDgABmrOQgFAFAAALIABAJIADAHIAFAEQAEACAFAAQARABAAgXIgBgIIgDgHIgFgEQgEgCgEAAQgJgBgEAGgAgcqiQgHgCgFgFQgFgEgDgIQgDgHAAgLQAAgLADgHQAEgIAFgEQAFgGAHgBQAGgDAHAAIAMABIAHACIgDAKQgEgDgLAAQgFAAgFACQgEABgEADQgEAEgCAGQgCAFAAAJQAAAHACAGQACAGAEADQADAFAFABQAFACAGAAIAKgBQADgBACgBIADAIQgEADgEABIgMABQgHAAgHgDgAhnqhQgDgCAAgDQAAgDADgCQACgCADAAQADAAACACQACACAAADQAAADgCACQgCACgDAAQgDAAgCgCgAEDqhIAAggIABgMIgBAAIgFALIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gADEqhIgVgaIgGAAIAAAaIgKAAIAAg5IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAFIAHAEIAVAagAiDqhIAAgWIgKABIgRAVIgMAAIAOgTIAGgDQgHgBgFgFQgEgFAAgGQAAgFACgEQACgEADgCQAEgDAFAAQAGgCAGAAIAJABIAIABIAAA5gAiXrQQgEACAAAGQAAAGAEACQAFADAIgBIAHAAIAAgUIgEgBIgEAAQgIAAgEADgAjDqhIAAggIACgMIgBAAIgGALIgbAhIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA5gAlHqhIgVgaIgGAAIAAAaIgKAAIAAg5IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAFIAHAEIAVAagAmCqhIgJgUIgeAAIgIAUIgLAAIAghNIAFAAIAgBNgAmdrTIgJAVIAYAAIgJgVIgDgNgAnsrWIgCgHIgCAGIgDAGIgHgEIAEgEIAFgGIgHACIgGAAIAAgHIAGAAIAHACIgFgGIgDgEIAGgEIADAFIACAGIACgGIADgFIAGADIgDAFIgGAGIAIgCIAGAAIAAAHIgFAAIgIgCIAGAGIACAEIgGAEg");
	this.shape.setTransform(-64.2,55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AFvLvQgFgDgEgDQgDgEgCgGQgCgGAAgHQAAgGACgGQACgGAEgDQADgEAGgDQAFgCAHAAQAHAAAFACQAFACAEAFQADAEACAFQACAGAAAGQAAAHgCAHQgCAFgEAEQgDAEgGACQgFACgGAAQgIAAgFgCgAFvLCQgFAGAAAKIABAIIADAHIAFAGQAEACAFAAQARAAAAgXIgBgHIgDgHIgFgGQgEgCgEABQgJAAgEAFgAE2LvQgFgDgDgDQgDgEgCgGQgBgFAAgIQAAgOAHgIQAHgIANAAIAKABIAIACIgCAJIgHgDIgHAAQgSAAAAAVIABAJIADAGIAGAGQADACAFAAQAFgBADgBIAGgDIADAHQgDADgGACQgFABgFAAQgIAAgFgCgAEPLvQgCgCAAgDQAAgEACgBQACgCADAAQAEAAACACQACABAAAEQAAADgCACQgCACgEAAQgDAAgCgCgADaLuQgFgCgEgGQgDgFgCgIQgBgHAAgJQAAgTAHgLQAHgKANAAQAPAAAHAKQAGAKAAAUQAAATgHALQgHAKgOAAQgHAAgFgDgADZKyQgEAHAAAQIABANIADAJQACAFAEACQADACAEAAQAJAAAEgIQAFgIAAgPIgBgMIgDgKQgCgFgEgCQgDgCgFAAQgJAAgEAIgAgZLtQgDgEAAgKIAAghIgKAAIAAgIIAKAAIAAgMIAKgCIAAAOIASAAIAAAIIgSAAIAAAeQAAAHACADQACADAEAAIAFgBIAFgBIACAGIgHADIgJABQgHAAgEgEgAihLwQgDgCgDgDQgDgCgBgFQgBgFAAgHIAAgiIAKAAIAAAgIABAIIACAFQAAABAAABQABAAAAABQABAAAAAAQABABAAAAQADABAEABQAGAAAFgFQAEgDACgGIAAglIAKAAIAAApIAAAJIABAIIgGAAIgDgKIgBAAQgDAFgFADQgFADgIAAIgJgBgAjDLxQgGAAgDgDQgEgDAAgHIAAhCIAKAAIAAA+QAAAFACACQABAAAAAAQABABAAAAQABAAAAAAQABABABAAIADgBIAEAAIABAHIgCABIgEABIgDAAIgDAAgAjtLvQgCgCAAgDQAAgEACgBQACgCADAAQAEAAACACQACABAAAEQAAADgCACQgCACgEAAQgDAAgCgCgAATLvQgDgBgCgCIgEgFQgCgDAAgEQAAgFACgEQACgDAEgDIAIgDIAIgBIAGAAIAEABIADAAIACAAIAAgDIAAgDIgBgFIgCgEIgEgBIgGgBIgEAAIgGABIgFACIgEACIgDgIQAKgGAPAAQAGAAAEACQAEACADADIADAFIAAAHIAAAMIgBANIABAJIABAHIgHAAIgDgJIgBAAIgDADIgEADIgGADIgHABQgEgBgEgBgAAXLXQgEACAAAGQAAAEADADQADACAFAAIAHgBIAEgDIAEgDIACgDIAAgIIgCgBIgDAAIgDAAIgFAAQgHAAgEACgAkILxIgRglIgCgLIgTAwIgFAAIgWg7IALAAIAMAhIACALIABAAIADgMIANggIAIAAIARAsIABAAIADgLIAKghIAKAAIgVA7gAllLxIgQglIgDgLIgTAwIgFAAIgWg7IALAAIAMAhIADALIABAAIADgMIANggIAIAAIAOAhIADALIABAAIACgLIALghIAKAAIgVA7gAnBLxIgRglIgCgLIgTAwIgFAAIgWg7IALAAIAMAhIACALIABAAIADgMIANggIAIAAIAOAhIADALIABAAIADgLIAKghIAKAAIgVA7gAHzLwIAAghIgBgJIgCgEQAAgBAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAIgGgBQgHAAgDADQgEAEgCAHIAAAlIgKAAIAAggIAAgJIgCgFQgBgDgDgBQgCgBgEAAQgFAAgEADQgEAEgCAEIAAAoIgKAAIAAg6IAHAAIACAHIABAAQADgDAFgDQAFgDAHAAQAGAAAEACQAEADACAGQADgFAFgDQAFgDAGAAQAGAAADABQAEABACAEQADACABAGIABANIAAAhgACRLwIAAgJIAQAAIAAg0IACgHIgFAGIgNAJIgFgHIAbgTIAFAAIAABGIAQAAIAAAJgABPLwIAAgJIARAAIAAg0IABgHIgFAGIgNAJIgEgHIAagTIAFAAIAABGIARAAIAAAJgAg8LwIAAghIgBgIIgCgFIgEgEIgHgBIgGABIgFADIgEAEIgCAGIAAAlIgKAAIAAhOIAKAAIAAAbIABAAQAEgEAEgDQAFgCAHAAQAFAAAEABQAEABACAEQADADABAEQABAFAAAIIAAAigAB3J3IAAhQIAHAAIACAHIABAAQADgEAEgCQAFgCAGgBQANAAAGAHQAGAIAAAPQAAAHgCAGQgCAGgEAEQgEAEgFADQgGABgGABIgEAAIgEgBIgDgBIgDgBIAAAXgACGIyQgDADgCAHIAAAaIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgGQgDgGgJAAQgHAAgEAEgAm0J3IAAhQIAHAAIACAHIABAAQADgEAEgCQAFgCAGgBQANAAAGAHQAGAIAAAPQAAAHgCAGQgCAGgEAEQgEAEgFADQgGABgGABIgEAAIgEgBIgDgBIgDgBIAAAXgAmlIyQgDADgCAHIAAAaIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgGQgDgGgJAAQgHAAgEAEgAECJhQgCgDAAgDQAAgDACgBQACgCADgBQADABACACQACABAAADQAAADgCADQgCABgDABQgDgBgCgBgADJJhQgGgDgDgEQgDgEgCgGQgCgFAAgHQAAgOAIgJQAHgHAOgBIAIABQAEABAEADQADACACAFQADAFAAAHIgBAEIAAAFIgpAAQAAAKAFAFQAEAFALAAIAJgBQAEgCADgDIADAIQgDADgGACQgGABgHABQgHgBgFgBgADJIyQgEADgBAJIAgAAQAAgJgEgDQgEgEgGAAQgIAAgFAEgAA+JgQgFgCgEgEQgDgEgCgGQgCgFAAgHQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAFACAEAEQADAFACAFQACAGAAAGQAAAHgCAGQgCAGgEADQgDAEgGADQgFABgGABQgIgBgFgCgAA+I0QgFAFAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAntJgQgFgCgEgEQgDgEgCgGQgCgFAAgHQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAFACAEAEQADAFACAFQACAGAAAGQAAAHgCAGQgCAGgEADQgDAEgGADQgFABgGABQgIgBgFgCgAntI0QgFAFAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAg3JhQgDgBgCgDIgEgEQgCgEAAgEQAAgEACgEQACgEAEgCIAIgEIAIAAIAGAAIAEAAIADAAIACAAIAAgCIAAgEIgBgEIgCgEIgEgCIgGgBIgEABIgGABIgFACIgEACIgDgJQAKgFAPAAQAGAAAEACQAEABADADIADAGIAAAGIAAANIgBANIABAIIABAHIgHAAIgDgIIgBAAIgDACIgEAEIgGACIgHABQgEAAgEgBgAgzJIQgEADAAAFQAAAFADACQADACAFAAIAHAAIAEgDIAEgDIACgDIAAgJIgCAAIgDgBIgDAAIgFAAQgHAAgEACgAhzJiIgHgDIACgIIAHACIAJAAQAQAAAAgJQAAgFgEgCQgEgCgJAAIgGAAIAAgIIAIAAIAFAAIAEgCIADgCIABgEQAAgEgEgDQgDgBgHAAIgJABIgHACIgCgHQAHgFAOAAQAKAAAGAEQAFADAAAIIgBADIgCAEIgDADIgFACIAAACQAHABADAEQADADAAAGIgBAHQgCADgDACIgJAEIgLABIgLAAgAk5JhQgEgBgCgDIgEgEQgBgEAAgEQAAgEACgEQACgEADgCIAIgEIAJAAIAGAAIAEAAIACAAIACAAIABgCIAAgEIgBgEIgCgEIgEgCIgGgBIgFABIgFABIgFACIgEACIgDgJQAKgFAOAAQAHAAAEACQAEABACADIADAGIABAGIgBANIAAANIAAAIIABAHIgHAAIgDgIIgBAAIgDACIgEAEIgFACIgIABQgEAAgDgBgAk1JIQgFADAAAFQAAAFAEACQADACAFAAIAGAAIAFgDIADgDIACgDIAAgJIgCAAIgCgBIgEAAIgFAAQgHAAgDACgAAMJhIAAgxIgTAAIAAgJIAxAAIAAAJIgUAAIAAAxgAiUJhIAAghIACgLIgBAAIgGAKIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA6gAjZJhIAAgZIgdAAIAAAZIgKAAIAAg6IAKAAIAAAYIAdAAIAAgYIAKAAIAAA6gAlvJhIAAg6IAmAAIAAAJIgbAAIAAAxgAECI1QgCgCAAgDQAAgDACgCQACgCADAAQADAAACACQACACAAADQAAADgCACQgCACgDAAQgDAAgCgCgAlLHhIgCgPIgxAAIAAg5IAKAAIAAAxIAcAAIAAgxIAKAAIAAAxIAJAAIAAAXgAAjHSQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAHgIAOAAIAJABQAEABADADQAEACACAFQACAEAAAIIAAADIgBAFIgpAAQAAAKAFAGQAFAEALAAIAJgBQAEgCACgCIAEAIQgEACgGACQgFACgHAAQgHAAgGgCgAAkGkQgFADAAAIIAfAAQABgIgEgDQgEgFgHAAQgIAAgEAFgAgdHSQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAHgIAOAAIAJABQAEABADADQADACACAFQACAEAAAIIAAADIgBAFIgoAAQAAAKAFAGQAFAEALAAIAJgBQAEgCABgCIAEAIQgEACgFACQgFACgHAAQgHAAgGgCgAgcGkQgFADAAAIIAfAAQABgIgEgDQgEgFgHAAQgIAAgEAFgAnzHSQgEgBgCgCIgEgFQgBgDAAgEQAAgFACgEQACgDADgCIAIgEIAJgBIAGAAIAEAAIACABIACAAIABgDIAAgDIgBgFIgCgDIgEgCIgGgBIgFAAIgFACIgFABIgEACIgDgJQAKgEAOgBQAHABAEACQAEABACACIADAHIABAGIgBAMIAAANIAAAIIABAHIgHAAIgDgIIgBAAIgDADIgEAEIgFABIgIABQgEABgDgCgAnvG5QgFADAAAGQAAAFAEACQADACAFAAIAGgBIAFgCIADgEIACgDIAAgJIgCAAIgCAAIgEAAIgFAAQgHgBgDACgAhmHSIAAghIABgLIgBAAIgFALIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gAjLHSIAAghIABgLIgBAAIgFALIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gAkRHSIAAghIACgLIgBAAIgGALIgbAhIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA5gAmVHSIgVgaIgGAAIAAAaIgKAAIAAg5IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAFIAHAEIAVAagAA2GRQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAAAQABgBAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABAAABAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAAAQAAABAAAAQABABAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAgAAfGRQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAkZFaIAAhPIAHAAIACAHIABAAQADgEAEgDQAFgCAGAAQANAAAGAGQAGAIAAAPQAAAHgCAGQgCAGgEAEQgEAEgFACQgGACgGAAIgEAAIgEAAIgDgBIgDgBIAAAXgAkKEVQgDADgCAGIAAAbIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgJgEgGQgDgGgJAAQgHAAgEAEgAAhFTIgBgPIgwAAIgCAPIgHAAIAAgYIAIAAIACgEIAEgJIADgPIABgUIAmAAIAAAwIAJAAIAAAYgAAAEeIgBAKIgCALIgEAIIAcAAIAAgoIgUAAIgBALgABBFDQgGgBgDgFQgDgDgCgHQgCgFAAgHQAAgPAIgIQAHgHAOAAIAIABQAEAAAEADQADADACAEQADAFAAAHIgBAEIAAAEIgpAAQAAALAFAFQAEAFALAAIAJgCQAEgBADgCIADAIQgDACgGACQgGABgHAAQgHAAgFgCgABBEVQgEAEgBAIIAgAAQAAgIgEgEQgEgEgGAAQgIAAgFAEgAhCFDQgGgBgDgFQgDgDgCgHQgCgFAAgHQAAgPAIgIQAHgHAOAAIAIABQAEAAAEADQADADACAEQADAFAAAHIgBAEIAAAEIgpAAQAAALAFAFQAEAFALAAIAJgCQAEgBADgCIADAIQgDACgGACQgGABgHAAQgHAAgFgCgAhCEVQgEAEgBAIIAgAAQAAgIgEgEQgEgEgGAAQgIAAgFAEgAjHFDQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgFQACgHAEgDQADgEAGgCQAFgCAHAAQAHAAAFACQAFACAEAFQADAEACAFQACAGAAAGQAAAHgCAGQgCAFgEAEQgDAFgGABQgFACgGAAQgIAAgFgCgAjHEWQgFAGAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAFgAmyFDQgGgBgDgFQgDgDgCgHQgCgFAAgHQAAgPAIgIQAHgHAOAAIAIABQAEAAAEADQADADACAEQADAFAAAHIgBAEIAAAEIgpAAQAAALAFAFQAEAFALAAIAJgCQAEgBADgCIADAIQgDACgGACQgGABgHAAQgHAAgFgCgAmyEVQgEAEgBAIIAgAAQAAgIgEgEQgEgEgGAAQgIAAgFAEgAiEFEIgJAAIAAAAIgBAAIAAg6IAEAAIAIAAIAJgBQANAAAGAEQAFAEAAAGQAAAFgCADQgDAEgGACIAAABQAHABAEAEQADADAAAGQAAAIgHAFQgIAEgOAAIgJgBgAiEE8IAFAAIAFAAQAJAAAEgCQAEgCAAgFIgBgEIgCgDIgFgCIgIgBIgLAAgAiEEiIANAAIAEAAIAEgCIADgCIABgEQAAgFgDgBQgDgCgIAAIgFAAIgGAAgAEjFEIAAgXIgLACIgQAVIgNAAIAPgTIAGgEQgIgBgEgEQgFgFAAgGQAAgGACgDQACgFAEgCQAEgCAFgBQAFgBAGAAIAJAAIAJACIAAA5gAEOEUQgEADAAAGQAAAFAFADQAFACAIAAIAHAAIAAgVIgEAAIgEAAQgJAAgEACgADjFEIAAghIABgMIgBAAIgFALIgbAiIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gACeFEIAAgZIgdAAIAAAZIgLAAIAAg5IALAAIAAAXIAdAAIAAgXIAKAAIAAA5gAk3FEIAAgxIgcAAIAAAxIgKAAIAAg5IAxAAIAAA5gAnVFEIgUgaIgGAAIAAAaIgLAAIAAg5IALAAIAAAaIAGgDIATgXIALAAIgSAVIgGAFIAHAFIAUAagAn6DLIACgIIADAAIAEAAIADgCIADgFIACgGIgZg6IAMAAIASAvIABAAIADgLIAMgkIAKAAIgTA0IgEALIgFAJQgCADgDADQgDACgFAAIgHgBgADgDMIAAhQIAHAAIACAHIABAAQADgEAEgCQAFgDAGAAQANAAAGAHQAGAHAAAPQAAAIgCAFQgCAGgEAFQgEAEgFACQgGACgGAAIgEAAIgEgBIgDgBIgDgBIAAAYgADvCGQgDADgCAHIAAAaIAFADIAIACQAJgBAFgFQAFgGAAgMQAAgJgEgGQgDgFgJAAQgHgBgEAEgAgBDBQADgCACgDQACgDAAgDQgDABgCgCQgBgBAAgDQAAgDABgDQACgBADAAQAEAAACACQADADAAAEQAAAFgCADIgDAGIgEADIgFACgAGWDEIgBgPIgxAAIgCAPIgHAAIAAgXIAIAAIACgEIAEgKIADgPIABgUIAnAAIAAAxIAJAAIAAAXgAF1CPIgCALIgCAKIgEAJIAdAAIAAgoIgUAAIgBAKgACnC0QgFgBgEgEQgDgFgCgGQgCgFAAgHQAAgGACgGQACgGAEgDQADgEAGgDQAFgCAHAAQAHAAAFADQAFACAEAEQADAEACAGQACAFAAAGQAAAIgCAGQgCAFgEAEQgDAEgGACQgFACgGAAQgIAAgFgDgACnCIQgFAFAAALIABAIIADAIIAFAEQAEACAFABQARAAAAgXIgBgIIgDgHIgFgEQgEgCgEAAQgJgBgEAGgAk8C0QgFgBgDgEQgEgFgBgGQgCgFAAgHQAAgGACgGQACgGADgDQAEgEAFgDQAFgCAHAAQAHAAAFADQAGACADAEQAEAEABAGQACAFAAAGQAAAIgCAGQgCAFgDAEQgEAEgFACQgFACgHAAQgHAAgGgDgAk8CIQgEAFAAALIABAIIADAIIAFAEQADACAFABQARAAAAgXIgBgIIgDgHIgFgEQgDgCgFAAQgIgBgFAGgAm1C1QgFgCgDgEQgDgEgCgGQgBgFAAgIQAAgOAHgIQAHgIANAAIAKABIAIACIgCAJIgHgCIgHgBQgSgBAAAWIABAJIADAHIAGAEQADACAFABQAFAAADgCIAGgDIADAIQgDACgGABQgFACgFAAQgIAAgFgCgAj5C2IgIgBIgBAAIgBAAIAAg5IAFAAIAHgBIAKAAQANAAAFADQAGAEAAAHQAAAEgDADQgDAFgFACIAAAAQAHACADAEQADADAAAGQAAAIgHAEQgHAFgPgBIgJAAgAj4CtIAEABIAGAAQAJAAAEgCQADgCAAgGIAAgEIgDgCIgFgCIgHgBIgLAAgAj4CUIAMAAIAFAAIAEgDIACgCIABgDQAAgFgDgCQgDgCgHAAIgFABIgGAAgAmPC2IgDgBIACgKIADABQACAAADgCQACgCABgFIADgOIABgZIAmAAIAAA5IgKAAIAAgwIgTAAIAAACIgCAUQgBAJgCAGQgCAGgDADQgDADgFAAIgFAAgAFIC1IAAgWIgLABIgQAVIgNAAIAPgTIAGgDQgIgBgEgFQgFgFAAgGQAAgFACgEQACgEAEgCQAEgCAFgBQAFgCAGAAIAJABIAJABIAAA5gAEzCFQgEADAAAGQAAAGAFACQAFADAIgBIAHAAIAAgUIgEgBIgEAAQgJAAgEACgAB9C1IAAgwIgcAAIAAAwIgLAAIAAg5IAxAAIAAA5gAgWC1IgNgQIgFgIIgEAIIgNAQIgLAAIAWgdIgVgcIANAAIALAPIAEAHIAFgHIALgPIAMAAIgVAbIALAQIALAOgAhbC1IAAgWIgLABIgQAVIgNAAIAPgTIAGgDQgIgBgEgFQgFgFAAgGQAAgFACgEQACgEAEgCQAEgCAFgBQAFgCAGAAIAJABIAJABIAAA5gAhwCFQgEADAAAGQAAAGAFACQAFADAIgBIAHAAIAAgUIgEgBIgEAAQgJAAgEACgAibC1IAAggIABgMIgBAAIgFALIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gAGnCaIAAgJIAdAAIAAAJgAjSA9IAAhPIAHAAIACAIIABAAQADgEAEgDQAFgDAGABQANgBAGAIQAGAHAAAOQAAAHgCAGQgCAGgEAEQgEAEgFACQgGADgGAAIgEAAIgEgBIgDgBIgDgBIAAAXgAjDgIQgDAEgCAFIAAAbIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgJgEgFQgDgGgJAAQgHAAgEADgAlSA9IAAgVIgFABIgEAAQgMAAgGgIQgGgHAAgQQAAgNAHgIQAGgIANAAIADAAIAEABIAAgTIAKAAIAAATIAEgBIAEAAQAMAAAGAHQAHAHAAAOQAAAHgCAGIgFAKQgDAEgFACQgFADgGAAIgDAAIgEgBIAAAVgAlJgKIAAAqIAEABIADAAQAIAAAEgHQAEgFAAgMIAAgJQgBgDgCgCQgCgDgEgCIgIAAIgCAAIgEAAgAllgGQgEAGAAAKIABAJIADAHQACADADACQADACAEAAIADAAIAEgBIAAgqIgDAAIgDAAQgIAAgFAEgAA3A1IgCgOIgxAAIAAg5IALAAIAAAxIAbAAIAAgxIAKAAIAAAxIAKAAIAAAWgAE4AgQgHgIAAgTIABgQQABgGADgFQACgFADgCQADgDAEgCIAIgCIAJgBIALgBQADgBADgBIABAJIgHACIgMABIgJABIgHADQgDADgCAEQgCAEgBAGIABABQAEgGAGgCQAFgCAHAAQAMAAAGAGQAHAIAAAMQAAAHgCAHQgCAFgEAEQgEAEgFABQgFADgGAAQgPAAgHgJgAFBgCQgFAEAAAJIABAIIADAHIAGAFQADABAEAAQASAAAAgVIgBgIIgDgFQgCgDgDgBQgDgBgEgBQgKAAgEAGgAD7AmQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgEQACgGAEgEQADgEAGgDQAFgBAHAAQAHgBAFADQAFACAEAFQADADACAGQACAEAAAHQAAAHgCAGQgCAFgEAFQgDADgGACQgFADgGAAQgIAAgFgDgAD7gGQgFAGAAAKIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgGIgFgFQgEgCgEAAQgJAAgEAFgAkLAmQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgEQACgGAEgEQADgEAGgDQAFgBAHAAQAHgBAFADQAFACAEAFQADADACAGQACAEAAAHQAAAHgCAGQgCAFgEAFQgDADgGACQgFADgGAAQgIAAgFgDgAkLgGQgFAGAAAKIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgGIgFgFQgEgCgEAAQgJAAgEAFgAg0AmQgDgBgCgCIgEgEQgCgEAAgDQAAgFACgEQACgDAEgDIAIgDIAIgBIAGAAIAEAAIADABIACAAIAAgEIAAgCIgBgEIgCgEIgEgCIgGAAIgEAAIgGABIgFABIgEACIgDgIQAKgFAPAAQAGAAAEACQAEACADACIADAGIAAAGIAAALIgBAOIABAIIABAHIgHAAIgDgIIgBAAIgDADIgEADIgGACIgHABQgEAAgEgCgAgwAOQgEACAAAHQAAAEADACQADADAFAAIAHgBIAEgDIAEgDIACgDIAAgJIgCAAIgDgBIgDAAIgFAAQgHAAgEACgACyAnIAAgXIgLABIgQAWIgNAAIAPgTIAGgEQgIgBgEgFQgFgEAAgGQAAgFACgEQACgDAEgDQAEgCAFgBQAFgCAGABIAJAAIAJABIAAA5gACdgIQgEADAAAFQAAAFAFADQAFACAIAAIAHAAIAAgUIgEAAIgEAAQgJgBgEADgAByAnIAAghIABgKIgBAAIgFAKIgbAhIgIAAIAAg5IAKAAIAAAiIgBAJIABAAIAGgJIAagiIAIAAIAAA5gAhXAnIABgrIgCAAIgFAIIgPAVIgDAAIgQgVIgEgIIgBAAIABAKIAAAhIgKAAIAAg5IALAAIARAZIAEAIIAVghIALAAIAAA5gAmNAnIAAgZIgdAAIAAAZIgKAAIAAg5IAKAAIAAAXIAdAAIAAgXIAKAAIAAA5gAnSAnIAAghIACgKIgBAAIgGAKIgbAhIgIAAIAAg5IALAAIAAAiIgBAJIABAAIAFgJIAbgiIAHAAIAAA5gAkhhRIAAhPIAHAAIACAHIABAAQADgEAEgDQAFgCAGAAQANAAAGAHQAGAHAAAPQAAAHgCAHQgCAGgEAEQgEADgFADQgGACgGAAIgEAAIgEAAIgDgBIgDgBIAAAWgAkSiWQgDAEgCAGIAAAaIAFAEIAIABQAJAAAFgHQAFgFAAgMQAAgJgEgFQgDgHgJAAQgHABgEADgAk0hYIgCgOIgxAAIgCAOIgGAAIAAgXIAHAAIADgFIADgJIADgOIACgVIAmAAIAAAxIAKAAIAAAXgAlViNIgCALIgDALIgDAIIAcAAIAAgpIgTAAIgBALgAiShtQgHgJAAgSIABgSQABgGADgFQACgEADgDQADgDAEgCIAIgCIAJgBIALgBQADAAADgCIABAJIgHADIgMAAIgJACIgHADQgDACgCAEQgCAFgBAGIABABQAEgGAGgCQAFgCAHgBQAMAAAGAHQAHAHAAANQAAAIgCAGQgCAGgEADQgEAEgFACQgFACgGAAQgPAAgHgIgAiJiRQgFAFAAAKIABAIIADAGIAGAFQADABAEABQASgBAAgUIgBgIIgDgHQgCgCgDgBQgDgCgEAAQgKAAgEAFgAjPhnQgFgDgEgDQgDgEgCgGQgCgGAAgHQAAgGACgGQACgGAEgEQADgDAGgDQAFgCAHAAQAHAAAFACQAFACAEAFQADAEACAFQACAGAAAGQAAAHgCAHQgCAFgEAEQgDAEgGACQgFACgGAAQgIAAgFgCgAjPiUQgFAGAAAKIABAIIADAHIAFAGQAEACAFAAQARAAAAgXIgBgHIgDgHIgFgGQgEgBgEgBQgJABgEAFgAmehnQgFgDgEgDQgDgEgCgGQgCgGAAgHQAAgGACgGQACgGAEgEQADgDAGgDQAFgCAHAAQAHAAAFACQAFACAEAFQADAEACAFQACAGAAAGQAAAHgCAHQgCAFgEAEQgDAEgGACQgFACgGAAQgIAAgFgCgAmeiUQgFAGAAAKIABAIIADAHIAFAGQAEACAFAAQARAAAAgXIgBgHIgDgHIgFgGQgEgBgEgBQgJABgEAFgAgFhnQgEgBgCgCIgEgFQgBgDAAgEQAAgFACgDQACgEADgDIAIgDIAIgBIAGAAIAEABIACAAIACAAIABgDIAAgDIgBgFIgCgEIgEgBIgGgBIgFAAIgEABIgFACIgEACIgDgIQAKgGANAAQAHAAAEACQAEACACADIADAFIABAHIgBAMIAAANIAAAJIABAHIgHAAIgDgJIgBAAIgDADIgEADIgFADIgIABQgDgBgDgBgAgBh/QgFACAAAGQAAAEAEADQACACAFAAIAGgBIAFgDIADgDIACgDIAAgIIgCgBIgCAAIgEAAIgFAAQgHAAgCACgABVhmIAAgYIgKACIgRAWIgMAAIAOgTIAGgFQgHgBgFgEQgEgFAAgGQAAgFACgEQACgEADgCQAEgDAFgBQAGgBAGAAIAJAAIAIACIAAA6gABBiXQgEADAAAGQAAAFAEADQAFADAIgBIAHAAIAAgVIgEAAIgEAAQgIAAgEACgAgphmIAAgZIgdAAIAAAZIgKAAIAAg6IAKAAIAAAYIAdAAIAAgYIAKAAIAAA6gAnJhmIAAhEIglAAIAABEIgLAAIAAhOIA7AAIAABOgAjBjfIAAhQIAHAAIACAHIABAAQADgEAFgCQAFgCAGgBQAMAAAGAIQAGAHAAAPQAAAHgCAGQgCAGgDAEQgEAEgGADQgFABgHAAIgEAAIgDAAIgDgBIgDgBIAAAXgAixkkQgEADgBAHIAAAaIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgGQgEgGgJAAQgGAAgEAEgAGmjnIgCgOIgxAAIgCAOIgGAAIAAgWIAHAAIADgFIADgKIADgOIACgVIAmAAIAAAyIAKAAIAAAWgAGFkbIgCALIgDAKIgDAJIAcAAIAAgpIgTAAIgBALgAH3j1QgDgDAAgDQAAgDADgBQACgCADgBQADABACACQACABAAADQAAADgCADQgCABgDAAQgDAAgCgBgAE8j2QgFgCgEgEQgDgEgCgGQgCgFAAgHQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAFACAEAEQADAFACAFQACAGAAAGQAAAHgCAGQgCAGgEADQgDAEgGADQgFABgGAAQgIAAgFgCgAE8kiQgFAFAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAAvj2QgFgDgEgFQgDgGgCgHQgBgIAAgIQAAgTAHgLQAHgLANAAQAPAAAHALQAGAKAAAUQAAATgHAKQgHALgOgBQgHABgFgDgAAukzQgEAIAAAQIABAMIADAJQACAFAEADQADABAEABQAJgBAEgHQAFgIAAgPIgBgNIgDgKQgCgEgEgCQgDgCgFgBQgJABgEAHgAkCj8QgHgJAAgSIABgRQABgHACgEQACgFADgDQADgDAEgBIAIgCIAKgBIAKgBQAEAAACgCIABAJIgGACIgMABIgKABIgHAEQgDACgCAEQgCAEAAAHIABAAQAEgFAFgDQAFgCAIAAQALAAAHAGQAGAIAAANQAAAIgCAFQgCAGgDAEQgEAEgFACQgFABgHAAQgOAAgHgIgAj6kgQgEAGAAAKIABAIIADAGIAFAFQADABAFAAQARAAAAgVIgBgIIgDgGQgBgDgEgBQgDgBgEAAQgKAAgEAEgAntj2QgFgCgEgEQgDgEgCgGQgCgFAAgHQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAFACAEAEQADAFACAFQACAGAAAGQAAAHgCAGQgCAGgEADQgDAEgGADQgFABgGAAQgIAAgFgCgAntkiQgFAFAAALIABAIIADAHIAFAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAG/j1QgDgBgCgDIgEgEQgCgEAAgEQAAgEACgEQACgEAEgCIAIgEIAIgBIAGAAIAEABIADAAIACAAIAAgCIAAgEIgBgEIgCgEIgEgCIgGgBIgEABIgGABIgFACIgEACIgDgJQAKgFAPAAQAGAAAEACQAEABADADIADAGIAAAGIAAANIgBANIABAIIABAHIgHAAIgDgIIgBAAIgDACIgEAEIgGACIgHABQgEAAgEgBgAHDkOQgEADAAAFQAAAFADACQADACAFABIAHgBIAEgDIAEgDIACgDIAAgJIgCAAIgDgBIgDAAIgFAAQgHAAgEACgAECj1IAAg6IAmAAIAAAJIgbAAIAAAxgACqj1IAeg/IAFgGIgHABIghAAIAAgJIAzAAIAAADIgjBKgABpj1IAAgJIAQAAIAAg0IACgGIgFAFIgNAJIgFgHIAbgTIAFAAIAABGIAQAAIAAAJgAgfj1IAAgEIAHgGIAHgIIAIgJIAHgLIAEgKQACgFAAgEQAAgFgDgEQgCgDgHAAIgJABIgHAFIgFgIIALgGQAFgCAHAAQAKABAFAFQAGAGAAAIQAAAFgCAHIgGAMIgIALIgJALIgGAFIAAAAIAIgBIAZAAIAAAJgAhZj1IAAgXIgKABIgRAWIgMAAIAOgTIAGgEQgHgBgFgEQgEgFAAgHQAAgEACgFQACgEADgBQAEgDAFgBQAGgBAGgBIAJABIAIABIAAA6gAhtklQgEACAAAGQAAAGAEACQAFAEAIgBIAHAAIAAgVIgEgBIgEAAQgIABgEACgAkkj1IAAgXIgKABIgRAWIgMAAIAOgTIAGgEQgHgBgFgEQgEgFAAgHQAAgEACgFQACgEADgBQAEgDAFgBQAGgBAGgBIAJABIAIABIAAA6gAk4klQgEACAAAGQAAAGAEACQAFAEAIgBIAHAAIAAgVIgEgBIgEAAQgIABgEACgAluj1IAAgxIgUAAIAAgJIAyAAIAAAJIgUAAIAAAxgAmPj1IgVgaIgGAAIAAAaIgKAAIAAg6IAKAAIAAAaIAGgCIAUgYIALAAIgTAXIgGAEIAHAFIAVAagAA1luIAAhPIAHAAIACAHIABAAQADgEAEgCQAFgDAGAAQANAAAGAHQAGAHAAAQQAAAHgCAFQgCAHgEADQgEAFgFACQgGACgGAAIgEAAIgEgBIgDAAIgDgBIAAAWgABEmzQgDADgCAHIAAAbIAFACIAIABQAJAAAFgFQAFgGAAgLQAAgKgEgGQgDgFgJgBQgHAAgEAEgAHOmFQgFgCgDgGQgEgFgBgHQgCgIAAgJQAAgTAHgLQAHgKAOAAQAOAAAHAKQAHALAAATQAAATgHAKQgHALgOAAQgHAAgGgDgAHOnCQgEAJAAAPIABAMIADAKQACAEADADQADACAFAAQAJAAAEgIQAEgHAAgQIgBgNIgDgJQgCgFgDgBQgDgDgFAAQgJAAgEAHgAGLmDIgIgCIADgJIAGACIAJABIAHgBIAGgDQADgCABgDQABgDAAgDQAAgIgEgDQgFgDgJAAIgJAAIAAgFIARgWIAFgFIgfAAIAAgJIAsAAIAAAFIgTAZIgEADIAEgBQAEABAEABQAEABADAEIAFAGQACAEAAAFQAAAGgDAFQgCAEgEADQgEAEgFACQgFABgGAAIgKgBgAEqmEQgFgCgEgFQgDgDgCgHQgCgFAAgGQAAgIACgFQACgGAEgEQADgEAGgCQAFgCAHAAQAHAAAFADQAFACAEAEQADAEACAFQACAGAAAHQAAAGgCAGQgCAGgEAEQgDAEgGACQgFACgGAAQgIAAgFgCgAEqmxQgFAGAAALIABAIIADAGIAFAFQAEACAFAAQARAAAAgVIgBgIIgDgIIgFgEQgEgDgEAAQgJAAgEAGgAgMmLQgHgIAAgTIABgRQABgGADgFQACgFADgCQADgDAEgBIAHgCIAJgCIALgBQADAAADgCIABAJIgHACIgMABIgJACIgGADQgDACgCAFQgCAEgBAGIABABQAEgGAFgDQAFgBAHAAQAMAAAGAGQAHAHAAAOQAAAHgCAGQgCAFgEAEQgEAEgFACQgFACgGAAQgOAAgHgJgAgDmuQgFAGAAAJIABAIIADAHIAFAEQADACAEgBQASAAAAgUIgBgJIgDgGQgCgCgDgBQgDgCgEAAQgKAAgDAFgAj8mEQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAHgIAOAAIAJABQAEABADADQAEACACAFQACAEAAAHIAAAEIgBAFIgpAAQAAAKAFAGQAFAEALAAIAJgBQAEgCACgCIAEAIQgEACgGADQgFABgHAAQgHAAgGgCgAj7myQgFADAAAIIAfAAQABgIgEgDQgEgFgHAAQgIAAgEAFgAk0mEQgFgCgEgFQgDgDgBgGQgCgGAAgGQAAgPAHgIQAIgIANAAIAKABIAIADIgDAIIgGgDIgIgBQgSAAAAAXIABAIIADAGIAGAFQAEACAFAAQAEABAEgCIAGgDIADAIQgEADgFABQgFABgGAAQgHAAgFgCgAnumEQgFgCgEgFQgDgDgBgGQgCgGAAgGQAAgPAHgIQAIgIANAAIAKABIAIADIgDAIIgGgDIgIgBQgSAAAAAXIABAIIADAGIAGAFQAEACAFAAQAEABAEgCIAGgDIADAIQgEADgFABQgFABgGAAQgHAAgFgCgAEAmDIAAgxIgcAAIAAAxIgLAAIAAg6IAxAAIAAA6gACdmDIAAgYIgLACIgQAWIgNAAIAPgTIAGgFQgIAAgEgFQgFgEAAgHQAAgFACgEQACgEAEgCQAEgCAFgBQAFgCAGAAIAJAAIAJACIAAA6gACImzQgEACAAAGQAAAGAFACQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgJAAgEADgAgtmDIAAgYIgLACIgQAWIgNAAIAPgTIAGgFQgIAAgEgFQgFgEAAgHQAAgFACgEQACgEAEgCQAEgCAFgBQAFgCAGAAIAJAAIAJACIAAA6gAhCmzQgEACAAAGQAAAGAFACQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgJAAgEADgAh3mDIAAgxIgUAAIAAgJIAyAAIAAAJIgUAAIAAAxgAifmDIAAgaIgdAAIAAAaIgKAAIAAg6IAKAAIAAAXIAdAAIAAgXIAKAAIAAA6gAmDmDIAAgYIglAAIAAgEIAogzIAHAAIAAAuIAOAAIAAAJIgOAAIAAAYgAmGm7IgRATIgGAGIAJgCIARAAIAAgWIABgIgAm2n8IAAhPIAHAAIACAHIABAAQADgEAFgDQAFgCAGAAQAMAAAGAGQAGAIAAAPQAAAHgCAGQgCAGgDAEQgEAEgGACQgFACgHAAIgEAAIgDAAIgDgBIgDgBIAAAXgAmmpBQgEADgBAGIAAAbIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgJgEgGQgEgGgJAAQgGAAgEAEgAFxoDIgCgPIgxAAIAAg5IALAAIAAAwIAbAAIAAgwIAKAAIAAAwIAKAAIAAAYgAh6oDIgCgPIgxAAIgCAPIgGAAIAAgYIAHAAIADgEIADgJIADgPIACgUIAmAAIAAAwIAKAAIAAAYgAibo4IgCAKIgDALIgDAIIAcAAIAAgoIgTAAIgBALgAhboTQgFgBgDgFQgEgDgBgHQgCgFAAgHQAAgPAHgIQAHgHAOAAIAJABQAEAAADADQAEADACAEQACAFAAAHIAAAEIgBAEIgpAAQAAALAFAFQAFAFALAAIAJgCQAEgBACgCIAEAIQgEACgGACQgFABgHAAQgHAAgGgCgAhapBQgFAEAAAIIAfAAQABgIgEgEQgEgEgHAAQgIAAgEAEgAjfoTQgFgBgDgFQgEgDgBgHQgCgFAAgHQAAgPAHgIQAHgHAOAAIAJABQAEAAADADQAEADACAEQACAFAAAHIAAAEIgBAEIgpAAQAAALAFAFQAFAFALAAIAJgCQAEgBACgCIAEAIQgEACgGACQgFABgHAAQgHAAgGgCgAjepBQgFAEAAAIIAfAAQABgIgEgEQgEgEgHAAQgIAAgEAEgAlkoTQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgHACgFQACgHADgDQAEgEAFgCQAFgCAHAAQAHAAAFACQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAGQgCAFgDAEQgEAFgFABQgFACgHAAQgHAAgGgCgAlkpAQgEAGAAALIABAIIADAHIAFAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgDgCgFAAQgIAAgFAFgADJoTQgDgBgCgBIgEgGQgCgCAAgFQAAgFACgDQACgDAEgDIAIgEIAIgBIAGAAIAEABIADAAIACAAIAAgDIAAgCIgBgGIgCgDIgEgBIgGgBIgEAAIgGABIgFACIgEABIgDgIQAKgFAPAAQAGAAAEACQAEABADADIADAGIAAAHIAAALIgBAOIABAIIABAHIgHAAIgDgJIgBAAIgDAEIgEADIgGACIgHABQgEAAgEgCgADNorQgEADAAAFQAAAFADACQADACAFAAIAHgBIAEgCIAEgDIACgEIAAgIIgCgBIgDAAIgDAAIgFAAQgHAAgEACgAkhoSIgIAAIgBAAIgBAAIAAg6IAFAAIAHAAIAKgBQANAAAFAEQAGAEAAAGQAAAFgDADQgDAEgFACIAAABQAHACADADQADADAAAGQAAAIgHAFQgHAEgPAAIgJgBgAkgoaIAEAAIAGAAQAJAAAEgCQADgCAAgFIAAgEIgDgDIgFgCIgHgBIgLAAgAkgo0IAMAAIAFAAIAEgCIACgCIABgEQAAgFgDgBQgDgCgHAAIgFAAIgGAAgAHxoSIAAghIACgMIgBAAIgGALIgbAiIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA5gAGsoSIAAghIABgMIgBAAIgFALIgbAiIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gAEnoSIgUgaIgGAAIAAAaIgLAAIAAg5IALAAIAAAaIAGgDIATgXIALAAIgSAVIgGAFIAHAFIAUAagACGoSIAAgXIgKACIgRAVIgMAAIAOgTIAGgEQgHgBgFgFQgEgEAAgGQAAgGACgDQACgFADgCQAEgCAFgBQAGgBAGAAIAJAAIAIACIAAA5gABypCQgEADAAAGQAAAFAEADQAFACAIAAIAHAAIAAgVIgEAAIgEAAQgIAAgEACgABGoSIAAghIACgMIgBAAIgGALIgbAiIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA5gAABoSIAAgZIgcAAIAAAZIgKAAIAAg5IAKAAIAAAXIAcAAIAAgXIAKAAIAAA5gAnToSIAAgxIgcAAIAAAxIgLAAIAAg5IAxAAIAAA5gAAUqKIAAhQIAHAAIACAHIABAAQADgEAEgDQAFgCAGAAQANAAAGAHQAGAHAAAPQAAAIgCAFQgCAGgEAFQgEAEgFACQgGACgGAAIgEAAIgEgBIgDgBIgDgBIAAAYgAAjrQQgDADgCAHIAAAaIAFADIAIACQAJgBAFgFQAFgGAAgMQAAgJgEgGQgDgFgJAAQgHgBgEAEgAj9qSIgCgPIgxAAIAAg5IAKAAIAAAxIAcAAIAAgxIAKAAIAAAxIAJAAIAAAXgABmqiQgFgCgEgDQgDgFgCgGQgCgFAAgHQAAgGACgGQACgGAEgDQADgEAGgDQAFgCAHAAQAHAAAFACQAFADAEAEQADAEACAGQACAFAAAGQAAAIgCAGQgCAFgEAEQgDAEgGACQgFACgGAAQgIAAgFgDgABmrOQgFAFAAALIABAIIADAIIAFAEQAEACAFABQARAAAAgXIgBgIIgDgHIgFgEQgEgCgEAAQgJgBgEAGgAgcqiQgHgCgFgFQgFgFgDgHQgDgIAAgKQAAgLADgIQAEgHAFgEQAFgGAHgBQAGgDAHAAIAMABIAHACIgDAJQgEgCgLAAQgFAAgFACQgEABgEADQgEAEgCAGQgCAFAAAJQAAAIACAFQACAGAEAEQADADAFACQAFACAGAAIAKgBQADgBACgCIADAJQgEADgEABIgMABQgHAAgHgDgAhnqhQgDgCAAgDQAAgDADgCQACgCADAAQADAAACACQACACAAADQAAADgCACQgCACgDAAQgDAAgCgCgAEDqhIAAggIABgMIgBAAIgFALIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gADEqhIgVgaIgGAAIAAAaIgKAAIAAg5IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAFIAHAEIAVAagAiDqhIAAgWIgKABIgRAVIgMAAIAOgTIAGgDQgHgBgFgFQgEgFAAgGQAAgFACgEQACgEADgCQAEgCAFgBQAGgCAGAAIAJABIAIABIAAA5gAiXrRQgEADAAAGQAAAGAEACQAFADAIgBIAHAAIAAgUIgEgBIgEAAQgIAAgEACgAjDqhIAAggIACgMIgBAAIgGALIgbAhIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA5gAlHqhIgVgaIgGAAIAAAaIgKAAIAAg5IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAFIAHAEIAVAagAmCqhIgJgUIgeAAIgIAUIgLAAIAghNIAFAAIAgBNgAmdrTIgJAVIAYAAIgJgVIgDgNgAnsrWIgCgHIgCAGIgDAGIgHgEIAEgFIAFgFIgHACIgGAAIAAgHIAGAAIAHACIgFgGIgDgEIAGgEIADAEIACAHIACgGIADgFIAGADIgDAFIgGAGIAIgCIAGAAIAAAHIgFAAIgIgCIAGAGIACAFIgGADg");
	this.shape_1.setTransform(-63.2,56);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.cbcf, new cjs.Rectangle(-117.8,-25.6,107.9,156.9), null);


(lib.cvb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AumCbQhBhAAAhbQAAhaBBhAQBAhBBbAAQBbAABABBQBBBAAABaQAABbhBBAQhABBhbAAQhbAAhAhBgAslhNQgNALgFAMIgpB0ICEAAQAUAAAPgLQAMgJABgJIiFAAIAph5IgCAAQgMAAgPALgAhpAzQgXgPAAgkIAAhhIA+AAIAABfQAAAOAJAGQAHAGARAAQAPAAAIgGQAIgGAAgOIAAhfIA+AAIAABhQAAAkgXAPQgWAOgwAAQgyAAgWgOgAOlA7IgGgSIhBAAIgGASIhDAAIBEicIBLAAIBECcgANsACIAlAAIgSg0IgBAAgAI/A7IAAh1Ig6AAIAAgnICyAAIAAAnIg6AAIAAB1gAFKA7IAAg+IhGAAIAAA+Ig/AAIAAicIA/AAIAAA3IBGAAIAAg3IA+AAIAACcgAmbA7IAAicIA+AAIAAByIBgAAIAAAqg");
	this.shape.setTransform(0,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.cvb, new cjs.Rectangle(-100,-20.9,200,44), null);


(lib.a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghBFIAAiJIBDAAIAAAOIg0AAIAAAtIAxAAIAAAMIgxAAIAAA0IA0AAIAAAOg");
	this.shape.setTransform(52.3,0,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAPAAIAAA7IATAAQArAAAAAnQAAAngpAAgAgpA3IASAAQAOAAAHgFQAHgGAAgOQAAgQgIgGQgHgFgSAAIgNAAg");
	this.shape_1.setTransform(38.2,0,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAbBFIAAhCIg0AAIAABCIgQAAIAAiJIAQAAIAAA7IA0AAIAAg7IAOAAIAACJg");
	this.shape_2.setTransform(23.2,0,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAYBFIAAhDQgLABgOAAQgTAAgIgGQgKgJAAgTIAAglIAPAAIAAAjQAAAOAFAFQAFAFAOAAIAXgCIAAg5IAPAAIAACJg");
	this.shape_3.setTransform(10.4,0,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglAyQgHgQAAgiQAAhHAsAAQAtAAAABHQAAAigHAQQgLAWgbAAQgaAAgLgWgAgcgCQAAAgAFANQAGAPARAAQASAAAGgPQAGgNAAggQAAg3geAAQgcAAAAA3g");
	this.shape_4.setTransform(-2.4,0,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgfA7QgJgLgBgXIAPAAQABARAFAIQAHAIAOAAQAaAAAAgcQAAgLgHgHQgHgJgLAAIgMAAIAAgNIAKAAQAVAAAAgXQAAgYgVAAQgKAAgHAHQgGAHgBALIgQAAQADgSAKgKQALgLAQAAQAQAAALAKQAKAKAAAOQAAAZgVAIQAMADAHAHQAHALAAAPQAAAOgIALQgKAOgYAAQgUAAgLgMg");
	this.shape_5.setTransform(-15.1,0,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAgBFIgKgoIgrAAIgKAoIgRAAIAniJIAUAAIAmCJgAgSAPIAkAAIgShIIAAAAg");
	this.shape_6.setTransform(-27.3,0,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAZBFIgjhEIgRAUIAAAwIgPAAIAAiJIAPAAIAABGIAyhGIATAAIgrA6IAsBPg");
	this.shape_7.setTransform(-38.8,0,1.176,1.176);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgiAvQgGgQAAggQAAhGAqAAQATAAALANQAJAMAAATIgPAAQAAgegZAAQgQAAgGAVQgDAMAAAXQAAAbAEANQAGATAPAAQAOAAAFgLQAEgIACgUIAPAAQgBAagIAMQgJAPgVAAQgaAAgKgZg");
	this.shape_8.setTransform(-51.5,0,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.a, new cjs.Rectangle(-56.3,-8.4,112.7,16.9), null);


(lib.xcvbxcv = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bg3.jpg
	this.instance = new lib.vb();
	this.instance.parent = this;
	this.instance.setTransform(120,148.5,1,1,0,0,0,120,148.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(60).to({_off:false},0).to({alpha:1},29).to({alpha:0},30).wait(1));

	// bg2.jpg
	this.instance_1 = new lib.z();
	this.instance_1.parent = this;
	this.instance_1.setTransform(120,148.5,1,1,0,0,0,120,148.5);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},29).to({alpha:0},30).to({_off:true},1).wait(60));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,446);


// stage content:
(lib._120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 6
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgJSguyISlAAMAAABdlIylAAg");
	this.shape.setTransform(60,300.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(259));

	// Слой 5
	this.instance = new lib.cvb();
	this.instance.parent = this;
	this.instance.setTransform(60,315.5,0.534,0.053,0,0,0,0.5,6.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(205).to({_off:false},0).to({regY:0.6,scaleY:0.53},6,cjs.Ease.get(1)).wait(41).to({regY:6.5,scaleY:0.05},6,cjs.Ease.get(1)).wait(1));

	// Символ 17
	this.instance_1 = new lib.w();
	this.instance_1.parent = this;
	this.instance_1.setTransform(69.1,100.9,0.854,0.854,0,0,0,0.2,0.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(186).to({_off:false},0).to({regX:0.4,x:60.6,alpha:1},8,cjs.Ease.get(1)).wait(54).to({regX:0.3,x:52.1,alpha:0},6,cjs.Ease.get(1)).wait(5));

	// Слой 9
	this.instance_2 = new lib.f();
	this.instance_2.parent = this;
	this.instance_2.setTransform(72.3,127.3,0.515,0.515,0,0,0,0.8,0.7);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(196).to({_off:false},0).to({regX:0.7,x:64.6,alpha:1},8,cjs.Ease.get(1)).wait(45).to({regX:0.5,regY:0.5,scaleX:0.69,scaleY:0.69},0).to({regX:0.2,x:57.6,alpha:0},6,cjs.Ease.get(1)).wait(4));

	// Символ 18
	this.instance_3 = new lib.e();
	this.instance_3.parent = this;
	this.instance_3.setTransform(70,156,0.854,0.854,0,0,0,0.3,0.3);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(189).to({_off:false},0).to({x:61.5,alpha:1},8,cjs.Ease.get(1)).wait(53).to({x:52.9,alpha:0},6,cjs.Ease.get(1)).wait(3));

	// Символ 16
	this.instance_4 = new lib.t();
	this.instance_4.parent = this;
	this.instance_4.setTransform(67.6,166.7,0.776,0.776,0,0,0,0.1,0.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(123).to({_off:false},0).to({x:59.9,alpha:1},8,cjs.Ease.get(1)).wait(45).to({regX:0.3,x:52.2,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(76));

	// Символ 15
	this.instance_5 = new lib.y();
	this.instance_5.parent = this;
	this.instance_5.setTransform(67.8,145.9,0.776,0.776,0,0,0,0.1,0.3);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(118).to({_off:false},0).to({x:60,alpha:1},8,cjs.Ease.get(1)).wait(49).to({regX:0.3,x:52.4,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(77));

	// Символ 14
	this.instance_6 = new lib.u();
	this.instance_6.parent = this;
	this.instance_6.setTransform(67.3,125,0.776,0.776,0,0,0,0.2,0.1);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(112).to({_off:false},0).to({regX:0.1,x:59.6,alpha:1},8,cjs.Ease.get(1)).wait(54).to({regX:0.3,x:51.9,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(78));

	// Символ 13
	this.instance_7 = new lib.i();
	this.instance_7.parent = this;
	this.instance_7.setTransform(67.7,93.1,0.776,0.776);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(97).to({_off:false},0).to({regX:0.1,regY:0.1,x:60,y:93.2,alpha:1},9,cjs.Ease.get(1)).wait(67).to({regX:0.3,x:52.4,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(79));

	// Слой 11
	this.instance_8 = new lib.cbcf();
	this.instance_8.parent = this;
	this.instance_8.setTransform(135.7,249.1);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(42).to({_off:false},0).to({x:124.7,alpha:1},9,cjs.Ease.get(1)).wait(39).to({x:115.7,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(162));

	// Слой 17
	this.instance_9 = new lib.xcvbcxvb("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(70.1,180,0.589,0.589,0,0,0,0.3,0.3);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(35).to({_off:false},0).to({x:60.1,alpha:1},9,cjs.Ease.get(1)).wait(44).to({startPosition:0},0).to({x:50.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(164));

	// Символ 12
	this.instance_10 = new lib.o();
	this.instance_10.parent = this;
	this.instance_10.setTransform(66,168.8,0.589,0.589,0,0,0,0.3,0.1);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(31).to({_off:false},0).to({x:60.1,alpha:1},9,cjs.Ease.get(1)).wait(47).to({x:54.2,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(165));

	// Символ 11
	this.instance_11 = new lib.p();
	this.instance_11.parent = this;
	this.instance_11.setTransform(68.2,122.3,0.8,0.8);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(10).to({_off:false},0).to({x:60.2,alpha:1},8,cjs.Ease.get(1)).wait(68).to({x:52.2,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(166));

	// Символ 10
	this.instance_12 = new lib.a();
	this.instance_12.parent = this;
	this.instance_12.setTransform(68,99.4,0.8,0.8);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(6).to({_off:false},0).to({x:60,alpha:1},8,cjs.Ease.get(1)).wait(71).to({x:52,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(167));

	// Символ 9
	this.instance_13 = new lib.s();
	this.instance_13.parent = this;
	this.instance_13.setTransform(67.9,76.4,0.8,0.8);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(2).to({_off:false},0).to({x:59.9,alpha:1},8,cjs.Ease.get(1)).wait(74).to({x:51.9,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(168));

	// Слой 4
	this.instance_14 = new lib.f();
	this.instance_14.parent = this;
	this.instance_14.setTransform(63,313.5,0.502,0.05,0,0,0,0,1);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(96).to({_off:false},0).to({regY:0,scaleY:0.5},6,cjs.Ease.get(1)).wait(71).to({regY:1,scaleY:0.05},6,cjs.Ease.get(1)).to({_off:true},1).wait(79));

	// Слой 2
	this.instance_15 = new lib.xcvbxcv();
	this.instance_15.parent = this;
	this.instance_15.setTransform(100,148.5,1,1,0,0,0,120,148.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(259));

	// Слой 1
	this.instance_16 = new lib.bg();
	this.instance_16.parent = this;
	this.instance_16.setTransform(-20,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(259));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(40,299.6,160,601);
// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/120x600_atlas_P_.png?1504527823721", id:"120x600_atlas_P_"},
		{src:"images/120x600_atlas_NP_.jpg?1504527823722", id:"120x600_atlas_NP_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;