(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"970x250_atlas_P_", frames: [[608,0,46,45],[0,0,606,187]]},
		{name:"970x250_atlas_NP_", frames: [[0,252,365,250],[0,0,365,250]]}
];


// symbols:



(lib._1Ресурс6 = function() {
	this.spriteSheet = ss["970x250_atlas_P_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._1Ресурс82x = function() {
	this.spriteSheet = ss["970x250_atlas_P_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._1 = function() {
	this.spriteSheet = ss["970x250_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["970x250_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.white = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2191CC").s().p("A3fEMIAAoXMAu/AAAIAAIXg");
	this.shape.setTransform(150.5,26.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.white, new cjs.Rectangle(0,0,300.9,53.6), null);


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglApQgRgRAAgYQAAgXARgRQARgRAXAAQASAAANAJQAOAKAHAPIgXAAQgHgHgGgDQgHgEgIAAQgQAAgKALQgLALAAAPQAAAPALAMQALALAPAAQAIAAAGgDQAIgDAEgHIAYAAQgGAPgOAJQgOAJgRAAQgXAAgRgRg");
	this.shape.setTransform(54.3,7.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgA3IgLgdIgpAAIgLAdIgXAAIAvhuIAPAAIAvBugAgMAHIAZAAIgNggg");
	this.shape_1.setTransform(43.2,7.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AASA3IAAgpIgSAAQgLAAgGgDQgFgBgFgDQgFgFgDgFQgCgGAAgKIAAgkIAUAAIAAAhIABAJQABACACACQACACADAAIAIABIASAAIAAgxIAUAAIAABug");
	this.shape_2.setTransform(32.8,7.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAZBFIAAhNIgxBNIgUAAIAAhuIAUAAIAABNIAxhNIAUAAIAABugAgRg1QgIgGgBgJIARAAQAAADADACQADACADAAQAEAAADgCQACgCABgDIARAAQgCAJgHAGQgHAGgLAAQgKAAgHgGg");
	this.shape_3.setTransform(22.8,6.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdA3IAAhuIA7AAIAAAUIgmAAIAAAaIAkAAIAAATIgkAAIAAAZIAmAAIAAAUg");
	this.shape_4.setTransform(13.5,7.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AglApQgRgRAAgYQAAgXARgRQARgRAXAAQASAAANAJQAOAKAHAPIgYAAQgFgHgHgDQgHgEgIAAQgQAAgKALQgLALAAAPQAAAPALAMQALALAPAAQAIAAAGgDQAIgDAEgHIAYAAQgHAQgNAIQgOAJgRAAQgXAAgRgRg");
	this.shape_5.setTransform(3.7,7.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgpApQgRgSABgXQAAgXAQgRQARgRAYAAQAZAAARARQARARAAAXQAAAXgRASQgRARgZAAQgXAAgSgRgAgagaQgLAMAAAOQAAAQALALQALALAPAAQAQAAALgLQALgMAAgPQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_6.setTransform(-12,7.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAmA3IAAhSIgdBSIgRAAIgdhSIAABSIgVAAIAAhuIAcAAIAeBUIAfhUIAcAAIAABug");
	this.shape_7.setTransform(-25.2,7.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AARA3IAAgrIgBAAIgcArIgYAAIAegoQgNgCgIgJQgJgJAAgNQAAgSALgJQAKgJAUgBIAgAAIAABugAgKgeQgFAEAAAIQAAAIAFAEQAFAEAJAAIANAAIAAghIgNAAQgJAAgFAFg");
	this.shape_8.setTransform(-36.9,7.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAgAAQATABAJAJQAKAJAAAQQABAPgLAJQgKAKgSAAIgKAAIAAApgAgNgGIALAAQAIAAAEgDQAFgDAAgIQAAgHgFgEQgDgEgJAAIgLAAg");
	this.shape_9.setTransform(-45,7.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAUA3IAAhaIgnAAIAABaIgVAAIAAhuIBRAAIAABug");
	this.shape_10.setTransform(-54.6,7.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVFnQgPgPAAgUQAAgVAPgPQAOgPAVAAQAVAAAPAPQAOAPAAAVQAAAUgOAPQgPAPgVAAQgVAAgOgPgAgJEsQgJAKAAANQAAAOAJAKQAJAJAOAAQAOAAAJgJQAKgLAAgNQAAgMgKgLQgJgJgOAAQgOAAgJAJgAjVFnQgOgPAAgVQAAgUAOgPQAQgPAUAAQAQAAALAIQAMAIAGAOIgUAAQgEgGgHgDQgGgDgIAAQgOAAgJAJQgJAKAAANQAAAOAJAKQAKAJAOAAQAGAAAGgCQAGgDAFgGIAUAAQgGANgLAIQgMAIgPAAQgVAAgPgPgAEjFzIAAglIAAAAIgaAlIgVAAIAbgjQgMgCgHgHQgHgIAAgMQAAgPAJgIQAJgJASAAIAcAAIAABggAELEoQgEAEAAAHQAAAHAEADQAFAEAJAAIAKAAIAAgdIgKAAQgJAAgFAEgADVFzIAAhDIgrBDIgSAAIAAhgIASAAIAABEIArhEIASAAIAABggABNFzIAAhgIAXAAQARAAAIAHQAJAHAAALQAAAHgDAFQgDAFgFACQAIADAEAGQAEAGAAAIQAAAOgJAIQgKAHgTAAgABfFiIALAAQAIAAAEgDQAEgDAAgGQAAgFgEgEQgEgDgIgBIgLAAgABfE4IAIAAQAGAAADgDQAEgCAAgFQAAgEgEgDQgDgDgGAAIgIAAgAg4FzIgbhHIgaBHIgUAAIAmhgIAQAAIAmBggAkfFzIALgYIgkhIIAVAAIAZAzIAXgzIATAAIgrBggAibDSIAAgTIhAAAIAAhgIASAAIAABPIAjAAIAAhPIASAAIAABPIALAAIAAAkgAnTCzQgOgPAAgVQAAgUAOgPQAQgPAUAAQAQAAALAIQAMAIAGAOIgVAAQgEgGgGgDQgGgDgIAAQgOAAgJAJQgJAKAAANQAAAOAJAKQAJAJAOAAQAHAAAGgCQAGgDAFgGIAUAAQgGANgLAIQgMAIgPAAQgVAAgPgPgAGuC/IAAhgIA0AAIAAARIgiAAIAAAXIAhAAIAAARIghAAIAAAWIAiAAIAAARgAGLC/IAAhgIASAAIAABggAFBC/IAAhgIASAAIAAAlIAOAAQAQAAAIAIQAIAIAAAOQAAANgJAIQgIAIgPAAgAFTCuIAOAAQAGAAAEgDQAEgDAAgGQAAgGgEgDQgEgEgGAAIgOAAgAEeC/IAAgoIgjAAIAAAoIgSAAIAAhgIASAAIAAAnIAjAAIAAgnIARAAIAABggACdC/IAAhgIASAAIAAAlIAOAAQAQAAAIAIQAIAIAAAOQAAANgJAIQgIAIgPAAgACvCuIAPAAQAFAAAFgDQAEgDAAgGQgBgHgDgCQgFgEgFAAIgPAAgACAC/IgahHIgbBHIgTAAIAmhgIAPAAIAmBggAAiC/IgJgZIgjAAIgKAZIgTAAIAnhgIAOAAIAoBggAgDCVIAVAAIgLgcgAhDC/IAAhDIgrBDIgSAAIAAhgIASAAIAABEIArhEIASAAIAABggAkeC/IAAhgIAzAAIAAARIgiAAIAAAXIAhAAIAAARIghAAIAAAWIAiAAIAAARgAlCC/IAAhPIgjAAIAABPIgSAAIAAhgIBHAAIAABggAisjoIAAgWIhVAAIAAAWIgWAAIAAgsIALAAIAshhIATAAIAsBhIALAAIAAAsgAj0kUIA7AAIgdhCgAEjj+IAAhUIg1BUIgWAAIAAh3IAWAAIAABTIA1hTIAWAAIAAB3gACSj+IAAh3IA7AAIAAAWIglAAIAABhgAA1j+IAAh3IAWAAIAAAuIARAAQASAAALAKQALAKAAAQQAAAQgLALQgMAKgRAAgABLkUIASAAQAIAAAEgEQAFgDAAgIQAAgHgFgEQgEgEgIAAIgSAAgAAJj+IAAgyIgqAAIAAAyIgWAAIAAh3IAWAAIAAAwIAqAAIAAgwIAWAAIAAB3gAiKj+IAAh3IA/AAIAAAWIgpAAIAAAbIAoAAIAAAVIgoAAIAAAbIApAAIAAAWg");
	this.shape_11.setTransform(0,20.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4, new cjs.Rectangle(-58.7,-16.5,118.6,74.8), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUA4IANgcIgrhTIAZAAIAcA7IAag7IAWAAIgyBvg");
	this.shape.setTransform(54.9,7.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBCIAAgVIhPAAIAAAVIgUAAIAAgpIAKAAIAphaIARAAIApBaIAKAAIAAApgAgaAZIA2AAIgcg+g");
	this.shape_1.setTransform(43.5,8.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoApQgSgQABgZQgBgXASgRQAQgRAYAAQAZAAARARQAQARABAXQgBAZgQAQQgQARgaAAQgYAAgQgRgAgagaQgLALAAAPQAAAQALALQALALAPAAQAPAAAMgLQALgLAAgQQAAgPgLgLQgMgLgPAAQgPAAgLALg");
	this.shape_2.setTransform(31.1,7.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA4IAAhvIA3AAIAAAVIgiAAIAABag");
	this.shape_3.setTransform(21.9,7.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAnA4IAAhSIgfBSIgPAAIgehSIAABSIgVAAIAAhvIAcAAIAeBUIAfhUIAcAAIAABvg");
	this.shape_4.setTransform(4.3,7.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpApQgRgQAAgZQAAgXARgRQARgRAYAAQAZAAARARQAQARAAAXQABAZgSAQQgQARgZAAQgYAAgRgRgAgagaQgLAMAAAOQAAAPALAMQALALAPAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgOAAgMALg");
	this.shape_5.setTransform(-8.9,7.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA4IAAhvIAbAAQASACAKAGQAKAIAAAOQAAAHgEAGQgDAEgGAEQAKAEAEAFQAFAHAAAKQAAAQgLAJQgKAJgWAAgAgOAkIANAAQAHAAAFgEQAEgEAAgGQAAgHgEgEQgFgDgHAAIgNAAgAgOgMIAKAAQAFAAAEgDQAEgCAAgGQAAgGgEgDQgEgCgFAAIgKAAg");
	this.shape_6.setTransform(-19.3,7.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgoApQgSgQABgZQgBgXASgRQAQgRAYAAQAZAAARARQARARAAAXQAAAZgRAQQgQARgaAAQgYAAgQgRgAgagaQgLAMAAAOQAAAPALAMQALALAPAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgOAAgMALg");
	this.shape_7.setTransform(-30.2,7.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUA4IAAgvIgoAAIAAAvIgUAAIAAhvIAUAAIAAAtIAoAAIAAgtIAVAAIAABvg");
	this.shape_8.setTransform(-41.6,7.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA4IAAhvIAbAAQASACAKAGQAKAIAAAOQAAAHgEAGQgCAEgHAEQAKAEAEAFQAFAHAAAKQAAAQgLAJQgKAJgWAAgAgOAkIANAAQAHAAAFgEQAEgEAAgGQAAgHgEgEQgFgDgHAAIgNAAgAgOgMIAKAAQAFAAAEgDQAEgCAAgGQAAgGgEgDQgEgCgFAAIgKAAg");
	this.shape_9.setTransform(-54.3,7.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AASFrQgOgPAAgUQAAgVAOgPQAPgPAWAAQAUAAAQAPQAOAPAAAVQAAAUgOAPQgPAOgVAAQgXAAgOgOgAAfEwQgJAJAAAOQAAAOAJAJQAKAKANAAQAOAAAKgKQAJgKAAgNQAAgOgJgJQgJgKgOAAQgPAAgJAKgAi0FrQgOgPAAgUQAAgVAOgPQAPgPAVAAQAWAAAPAPQAOAPAAAVQABAUgQAPQgOAOgWAAQgVAAgPgOgAinEwQgJAJAAAOQAAAOAJAJQAKAKANAAQAOAAAKgKQAJgJAAgOQAAgOgJgJQgKgKgOAAQgOAAgJAKgAE4F3IAMgZIglhIIAWAAIAZA0IAWg0IATAAIgrBhgAEDF3IAAgoIgjAAIAAAoIgSAAIAAhhIASAAIAAAoIAjAAIAAgoIASAAIAABhgACqF3IAAgoIgiAAIAAAoIgSAAIAAhhIASAAIAAAoIAiAAIAAgoIASAAIAABhgAgQF3IgahIIgaBIIgUAAIAmhhIAQAAIAlBhgAjWF3IgegrIAAArIgSAAIAAhhIASAAIAAAqIAegqIAVAAIgkAwIAkAxgAlvF3IAAhhIAXAAQARABAIAGQAJAIAAALQAAAHgDAEQgDAEgFADQAHACAFAHQAEAHAAAIQAAAOgKAHQgJAIgTAAgAldFlIALAAQAHAAAEgCQAEgDABgGQgBgHgEgCQgDgEgIAAIgLAAgAldE7IAIAAQAGAAADgCQADgCABgFQAAgFgDgCQgFgDgFAAIgIAAgAAvC3QgPgPAAgUQAAgVAPgPQAPgPAVAAQAVAAAPAPQAOAPAAAVQAAAUgOAPQgPAOgVAAQgWAAgOgOgAA7B8QgJAJAAAOQAAAOAJAJQAKAKAOAAQAOAAAJgKQAJgJAAgOQAAgOgJgJQgJgKgOAAQgPAAgJAKgAkgC3QgOgOAAgWQAAgVAOgOQAPgPAVAAQAPAAAMAHQAMAJAFANIgUAAQgFgGgFgDQgHgDgHAAQgOAAgJAKQgJAJAAAOQAAANAJAKQAJAKAOAAQAHAAAGgDQAGgCAEgHIAVAAQgGAOgMAHQgKAIgQAAQgWAAgOgOgAFxDDIgKgZIgkAAIgJAZIgUAAIAohhIAOAAIApBhgAFKCYIAXAAIgMgcgAENDDIgegrIAAArIgSAAIAAhhIASAAIAAAqIAegqIAWAAIgkAwIAkAxgACSDDIAAhhIAXAAQAQABAJAGQAJAHAAAMQgBAHgCAEQgCAEgGADQAHACAFAHQAFAHAAAIQAAANgKAIQgKAIgTAAgACkCxIALAAQAIAAADgCQAFgDAAgGQAAgHgFgCQgDgEgIAAIgLAAgACkCHIAIAAQAHAAADgCQACgCABgFQAAgFgDgCQgEgDgGAAIgIAAgAACDDIAAgoIgjAAIAAAoIgRAAIAAhhIARAAIAAAoIAjAAIAAgoIARAAIAABhgAhQDDIgKgZIgkAAIgJAZIgUAAIAphhIANAAIApBhgAh3CYIAXAAIgMgcgAi6DDIAAhPIgSAAIAAgSIA2AAIAAASIgSAAIAABPgAlqDDIALgZIglhIIAWAAIAaA0IAVg0IAUAAIgsBhgAC6kOQgRgSgBgaQABgaARgRQATgTAaAAQAaAAASATQASARAAAaQAAAagSASQgRARgbAAQgaAAgTgRgADKlXQgLAMAAAQQAAARALANQAMALARABQARgBAMgLQAMgNAAgRQAAgQgMgMQgMgMgRABQgRgBgMAMgAgBkPQgSgRAAgbQAAgaASgRQARgSAaAAQASAAAPAKQAOAJAIARIgZAAQgFgGgIgFQgIgDgJAAQgRgBgLAMQgMANAAAPQAAASAMAMQALALARABQAIgBAIgDQAJgEAEgHIAZAAQgHARgOAJQgOAJgTAAQgaABgRgTgAB7j/IAAhiIgWAAIAAgUIBCAAIAAAUIgWAAIAABigAhgj/IAAh2IBAAAIAAAUIgqAAIAAAcIAoAAIAAAWIgoAAIAAAbIAqAAIAAAVgAiLj/IAAhZIggBZIgTAAIgfhZIAABZIgWAAIAAh2IAeAAIAgBaIAhhaIAeAAIAAB2g");
	this.shape_10.setTransform(0,20.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-57.9,-17.1,118,75.4), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVA3IANgcIgqhSIAZAAIAcA7IAag7IAWAAIgyBug");
	this.shape.setTransform(54.9,-1.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBCIAAgVIhPAAIAAAVIgVAAIAAgpIALAAIAphaIARAAIApBaIALAAIAAApgAgaAZIA2AAIgcg+g");
	this.shape_1.setTransform(43.5,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpApQgRgRABgYQAAgWAQgSQARgRAYAAQAZAAARARQARASAAAWQAAAYgRARQgRARgZAAQgXAAgSgRgAgagaQgLAMAAAOQAAAQALALQALALAPAAQAQAAALgLQALgLAAgQQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_2.setTransform(31,-1.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA3IAAhuIA3AAIAAAUIgiAAIAABag");
	this.shape_3.setTransform(21.9,-1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAmA3IAAhSIgdBSIgRAAIgdhSIAABSIgVAAIAAhuIAcAAIAeBUIAfhUIAcAAIAABug");
	this.shape_4.setTransform(4.2,-1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpApQgQgQAAgZQAAgWAQgSQARgRAYAAQAZAAARARQARARAAAXQAAAZgRAQQgSARgYAAQgYAAgRgRgAgagaQgLALAAAPQAAAQALALQAKALAQAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgQAAgKALg");
	this.shape_5.setTransform(-8.9,-1.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAaAAQATABAKAHQAJAIAAANQAAAIgDAGQgEAFgFADQAJADAFAGQAFAHAAAKQAAAQgLAJQgLAIgVAAgAgOAjIANAAQAIABAEgEQAFgEgBgGQABgHgFgEQgEgDgIgBIgNAAgAgOgMIAJAAQAGAAAEgDQADgDAAgFQAAgGgDgCQgEgEgGAAIgJAAg");
	this.shape_6.setTransform(-19.3,-1.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgpApQgQgQAAgZQAAgWAQgSQARgRAYAAQAaAAAQARQAQARABAXQgBAZgQAQQgRARgZAAQgYAAgRgRgAgagaQgLALAAAPQAAAQALALQALALAPAAQAQAAALgLQALgMAAgPQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_7.setTransform(-30.2,-1.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUA3IAAguIgnAAIAAAuIgVAAIAAhuIAVAAIAAAtIAnAAIAAgtIAVAAIAABug");
	this.shape_8.setTransform(-41.7,-1.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAbAAQASABAKAHQAJAIAAANQAAAIgDAGQgEAFgFADQAJADAFAGQAFAHAAAKQAAAQgLAJQgLAIgVAAgAgOAjIANAAQAIABAEgEQAFgEgBgGQABgHgFgEQgEgDgIgBIgNAAgAgOgMIAJAAQAGAAAEgDQAEgDAAgFQAAgGgEgCQgEgEgGAAIgJAAg");
	this.shape_9.setTransform(-54.3,-1.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AASA7IAAguIgBAAIgeAuIgaAAIAhgrQgPgDgIgJQgJgIAAgPQAAgSALgLQAMgKAVAAIAiAAIAAB1gAgLggQgFAEAAAJQAAAJAFAEQAGAEAKAAIANAAIAAgjIgNAAQgKAAgGAFg");
	this.shape_10.setTransform(21,-19.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AApA7IAAhXIggBXIgRAAIgghXIAABXIgWAAIAAh1IAeAAIAgBZIAhhZIAeAAIAAB1g");
	this.shape_11.setTransform(9.1,-19.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgfA7IAAh1IA/AAIAAAVIgpAAIAAAbIAnAAIAAAVIgnAAIAAAbIApAAIAAAVg");
	this.shape_12.setTransform(-2.4,-19.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AglA7IAAh1IAhAAQATAAAMAKQALAJAAASQAAAQgLAJQgLAKgUAAIgLAAIAAAtgAgPgGIANAAQAIAAAFgEQAFgDAAgIQAAgIgFgEQgEgEgJAAIgNAAg");
	this.shape_13.setTransform(-10.7,-19.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AglA7IAAh1IAcAAQATAAALAIQAKAJAAAOQAAAHgDAHQgDAEgGAFQAJADAFAGQAFAJAAAJQABASgMAJQgMAJgXAAgAgPAmIAOAAQAIAAAEgEQAFgEABgHQgBgHgFgEQgEgEgIAAIgOAAgAgPgNIAKAAQAGAAAEgDQADgDACgGQAAgGgFgDQgEgDgGAAIgKAAg");
	this.shape_14.setTransform(-19.9,-19.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("ABkDXQgOgOAAgVQAAgVAPgPQAOgOAVAAQAPAAAMAHQAMAJAGANIgUAAQgFgGgGgCQgGgDgHAAQgPgBgJAKQgJAKAAANQAAAMAJALQAKAKAOAAQAGAAAGgDQAGgCAFgGIAUAAQgGANgLAIQgLAHgQAAQgVAAgPgPgAotDXQgPgOAAgVQAAgUAPgQQAPgOAVAAQAPAAALAHQAMAJAGANIgUAAQgFgFgGgDQgGgDgHAAQgOgBgKAKQgJAKAAANQAAAOAKAJQAIAKAPAAQAHAAAGgDQAGgCAEgGIAVAAQgGANgMAIQgMAHgPAAQgVAAgOgPgAIrDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAHNDkIgegqIAAAqIgSAAIAAhgIASAAIAAApIAegpIAVAAIgkAvIAkAxgAEbDkIAAhgIASAAIAABPIAeAAIAAhPIARAAIAABPIAeAAIAAhPIASAAIAABggADSDkIAMgYIglhIIAVAAIAaAzIAWgzIATAAIgrBggAAZDkIAAhDIgqBDIgSAAIAAhgIASAAIAABDIAqhDIASAAIAABggAhkDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAjCDkIgegqIAAAqIgSAAIAAhgIASAAIAAApIAegpIAVAAIgkAvIAkAxgAk6DkIAAhgIAaAAQARABAJAHQAJAIAAANQAAAOgJAIQgJAJgRgBIgJAAIAAAlgAkpCuIALAAQAHAAAEgDQAEgDAAgHQAAgFgEgEQgEgDgHAAIgLAAgAleDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAnIDkIAAhPIgRAAIAAgRIA1AAIAAARIgSAAIAABPgAB+AjQgOgOAAgVQAAgTAOgQQAQgOAVAAQAVAAAPAOQAOAQAAATQAAAVgOAOQgPAPgVAAQgWAAgPgPgACLgWQgJAJAAANQAAAOAJAKQAKAJANAAQAPAAAJgKQAJgJAAgOQAAgNgJgJQgJgKgOABQgPgBgJAKgAhmAjQgOgOAAgVQAAgTAOgQQAQgOAUAAQAQAAALAHQAMAJAGANIgVAAQgFgFgFgDQgGgDgIAAQgOgBgJAKQgJAKAAAMQAAAOAJAJQAJAKAOAAQAHAAAGgDQAGgCAFgGIAUAAQgGANgLAIQgMAHgPAAQgWAAgOgPgAEfAwIAAhCIgrBCIgSAAIAAhfIASAAIAABCIArhCIARAAIAABfgAAsAwIAAhfIAbAAQARABAIAHQAJAIAAANQAAAOgJAHQgIAJgRgBIgJAAIAAAlgAA+gFIAKAAQAIAAADgDQAEgDAAgHQAAgFgEgEQgDgDgIAAIgKAAgAAAAwIAAhOIgSAAIAAgRIA0AAIAAARIgRAAIAABOgAiTAwIAAhfIASAAIAABfgAjcAwIAAhfIARAAIAAAlIAPAAQAOgBAJAJQAJAHAAANQAAANgJAJQgKAIgNAAgAjLAfIAPAAQAGgBAEgDQAEgDAAgGQAAgGgEgDQgEgDgGAAIgPAAgAkqAwIAAhfIA4AAIAAARIgnAAIAAAUIAQAAQAQgBAIAKQAIAIAAALQAAANgJAJQgKAIgNAAgAkZAfIAQAAQAGgBAEgDQAEgDAAgGQAAgFgEgEQgEgDgGAAIgQAAgAD5g5QgGgGgBgIIAPAAQAAADACACQADACADAAQAEAAACgCQACgCABgDIAPAAQgCAIgGAGQgGAEgKAAQgKAAgGgEgAjqiQQgPgNAAgWQAAgUAPgQQAPgOAVAAQAWAAAOAOQAPAPAAAVQAAAVgPAOQgOAPgWAAQgWAAgOgPgAjdjKQgKAJAAAOQAAAOAKAKQAKAJANAAQAOAAAKgKQAJgJAAgOQAAgNgJgKQgKgKgOABQgOgBgJAKgAGJiDIAAhgIASAAIAABggAE/iDIAAhgIASAAIAAAlIAOAAQAPgBAJAJQAIAHAAAOQAAANgJAJQgJAIgOAAgAFRiUIAPAAQAGgBAEgDQAEgDAAgGQgBgGgDgDQgEgDgGAAIgPAAgAEciDIAAhIIgaBIIgPAAIgZhIIAABIIgSAAIAAhgIAYAAIAbBJIAahJIAZAAIAABggACkiDIAAhIIgZBIIgPAAIgahIIAABIIgSAAIAAhgIAYAAIAbBJIAbhJIAYAAIAABggAAziDIgKgZIgkAAIgIAZIgUAAIAnhgIAOAAIAoBggAAMitIAWAAIgLgcgAhNiDIAAhgIAbAAQARABAIAHQAJAIAAANQAAAOgJAIQgIAJgRgBIgJAAIAAAlgAg7i5IAKAAQAIAAADgDQAEgDAAgHQAAgFgEgEQgDgDgIAAIgKAAgAiGiDIAAhgIAwAAIAAARIgfAAIAABPgAk9iDIAAhgIAbAAQARABAJAHQAJAIAAANQAAANgJAJQgJAJgRgBIgJAAIAAAlgAkri5IALAAQAHAAAEgDQADgDABgHQAAgFgEgEQgEgDgHAAIgLAAgAlgiDIAAhPIgjAAIAABPIgSAAIAAhgIBHAAIAABgg");
	this.shape_15.setTransform(0,42.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-57.9,-25.8,118,91.8), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmpCaQgRgSAAgaQAAgaASgSQARgSAbAAQASAAAOAKQAPAJAIARIgZAAQgHgHgHgEQgHgDgJAAQgRAAgMAMQgLALAAARQAAARALALQAMAMARAAQAJAAAHgDQAHgDAFgHIAaAAQgHAPgPAKQgPAKgSAAQgaAAgSgSgAIRCpIAAh3IBAAAIAAAWIgqAAIAAAbIAoAAIAAAVIgoAAIAAAbIAqAAIAAAWgAHmCpIAAh3IAWAAIAAB3gAGLCpIAAh3IAWAAIAAAuIARAAQASAAALAKQALAKAAAQQAAAQgLALQgMAKgRAAgAGhCTIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAFfCpIAAgyIgrAAIAAAyIgWAAIAAh3IAWAAIAAAwIArAAIAAgwIAWAAIAAB3gADBCpIAAh3IAWAAIAAAuIASAAQASAAALAKQAKAKAAAQQAAAQgLALQgLAKgRAAgADXCTIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgACdCpIgghYIghBYIgYAAIAvh3IATAAIAvB3gAAiCpIAAhTIgzBTIgWAAIAAh3IAWAAIAABUIAzhUIAWAAIAAB3gAjHCpIAAh3IAWAAIAABhIAkAAIAAhhIAWAAIAABhIAkAAIAAhhIAWAAIAAB3gAkhCpIAOgeIguhZIAbAAIAfA/IAbg/IAYAAIg1B3gAoFCpIAAhTIg1BTIgWAAIAAh3IAWAAIAABUIA1hUIAWAAIAAB3gAoEhBQgSgSAAgaQAAgZASgTQASgSAaAAQATAAAOAKQAOAJAIARIgZAAQgHgHgGgEQgHgDgKAAQgRAAgMAMQgLALAAARQAAARAMALQAMAMAQAAQAJAAAHgDQAHgDAGgHIAZAAQgHAPgPAKQgOAKgSAAQgaAAgSgSgAGsgyIAAh3IA/AAIAAAWIgpAAIAAAbIAoAAIAAAVIgoAAIAAAbIApAAIAAAWgAGAgyIAAh3IAWAAIAAB3gAElgyIAAh3IAWAAIAAAuIASAAQASAAALAKQAKAKAAAQQAAAQgLALQgLAKgRAAgAE7hIIASAAQAIAAAFgEQAEgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAD6gyIAAgyIgrAAIAAAyIgWAAIAAh3IAWAAIAAAwIArAAIAAgwIAWAAIAAB3gABcgyIAAh3IAWAAIAAAuIARAAQASAAALAKQALAKAAAQQAAAQgLALQgMAKgRAAgAByhIIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAA4gyIghhYIgfBYIgYAAIAuh3IATAAIAvB3gAg7gyIgMgfIgrAAIgMAfIgZAAIAyh3IARAAIAyB3gAhqhmIAbAAIgNgjgAjZgyIAAh3IAhAAQAUAAALAKQALAKAAARQAAAQgKALQgLAKgVAAIgLAAIAAAtgAjDh0IANAAQAIAAAFgEQAFgEAAgIQAAgIgFgDQgEgEgJAAIgNAAgAkFgyIAAhTIg1BTIgWAAIAAh3IAWAAIAABUIA1hUIAWAAIAAB3gAmHgyIAAhhIgWAAIAAgWIBCAAIAAAWIgWAAIAABhg");
	this.shape.setTransform(0,-13.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AElAwIAAhfIASAAIAABfgADcAwIAAhfIARAAIAAAlIAOAAQAPAAAJAIQAIAHABAOQAAANgKAIQgJAIgOAAgADtAfIAOAAQAHAAAEgEQADgDAAgFQAAgGgDgEQgEgDgHAAIgOAAgAC4AwIAAgoIgjAAIAAAoIgSAAIAAhfIASAAIAAAmIAjAAIAAgmIASAAIAABfgABfAwIAAhDIgrBDIgSAAIAAhfIASAAIAABCIArhCIASAAIAABfgAheAwIAAhfIASAAIAABOIAdAAIAAhOIARAAIAABOIAeAAIAAhOIARAAIAABfgAh7AwIgKgZIgkAAIgKAZIgUAAIAphfIAOAAIAoBfgAijAGIAXAAIgLgbgAjiAwIAAhHIgaBHIgOAAIgahHIAABHIgSAAIAAhfIAYAAIAbBIIAbhIIAYAAIAABfg");
	this.shape_1.setTransform(0,25.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-59.2,-30.4,118.6,61), null);


(lib.snow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1Ресурс82x();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.snow, new cjs.Rectangle(0,0,606,187), null);


(lib.p4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1Ресурс6();
	this.instance.parent = this;
	this.instance.setTransform(35,-87);

	this.instance_1 = new lib._2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-150,-99.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.p4, new cjs.Rectangle(-150,-99.5,365,250), null);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-99.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1, new cjs.Rectangle(-150,-99.5,365,250), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AoyBQQgpglAYg2QAVgxBDgcQBLggB6ABQAaAAAZADIAgAEIANADIgSAfQgmgLggAAQg9AAgzASQhEAYgKAwQgHAdAVAaQAbAhA7gDQATAAAkgNQArgPAagUIA9g1IAEgDIAIgEIAMgDIAGgBIBCAAIAVBbIAphaIBJAAIAqBFIAfhFIBCAAIg6B/IhEAAIgshJIghBJIgqAAIAAAAIhOAAIgDgWIhIAAIgYAVIgvAAQg2AThHAAQhnAAgsgogAjAA2IAqgBIgEgjgAF6ByIArgrIgrhgIBBAAIATA0IA1g1IBKAAIiACAQgHAHgEACIgQADgAD2BmIhrAAIA6h/IBsAAQAzAAATAZQAPATgLAZQgLAYgcAPQgjATg4AAIgDAAgADhBGIATAAQA/AAAJgiQAHgegzAAIgTAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-58.9,-12,117.9,24.1), null);


(lib.legal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ADCA3IgEgDIgDgDIgCgFIADgBQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAABAAIABABIACAEIADACIADAAIAEAAIADgCIABgCIABgDIgBgDIgBgCIgDgBIgGgCIAAgDIAFgBIADgBIABgCIABgDIgBgDQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAAAIgCgBIgDgBIgDABIgCABIgCACIgBACIgBABIgBAAIgDAAIABgFIADgEIAEgCIAFAAIAFAAIAEACIACAEIABAEIAAAEIgCACIgCACIgDABIAGAEIACAGQAAADgBACIgDAEIgEADIgGAAgAChA3IgDgBIgDgCIgCgBIACgCIABgBIACAAIABABIADABIADAAIAEAAIADgCIABgDIABgEIgBgDIgBgDIgDgCIgEAAIgGABIgEgBIAEgTIATAAIAAACIgBACIgCABIgNAAIgBAKIAFAAIAGABIAEACIADAEIAAAFIgBAGIgDAEIgFADIgFABgABfA2IgFgEQgDgDAAgEIgBgJIABgJQAAgDADgDIAFgFIAFAAIAGAAIAFAFIADAGIABAJIgBAJIgDAHIgFAEIgGABgABhATIgDADIgCAEIgBAIIABAIIACAFIADADIADAAIAEAAIADgDIACgFIABgIIgBgIIgCgEIgDgDIgEgBgAAcA2IgEgEQgCgCgBgFQgCgDAAgGQAAgFACgEQABgFACgBIAEgFIAGAAIAGAAQAEADABACIADAGIABAJIgBAJIgDAHQgBACgEACIgGABgAAfATIgDADIgCAEIgBAIIABAIIACAFIADADIADAAIAEAAIADgDIACgFIABgIIgBgIIgCgEIgDgDIgEgBgAgDA2IgFgDIgCgEIgBgGIABgGIAEgGIAJgOIABgBIAHAAIgMAPIgBACIAAAAIACgBIADAAIAFABIAEABIACAFIABAFIgBAFIgCAEIgFADIgGABIgEgBgAgBAiIgDACIgCADIAAADIAAAEIACADIADABIACAAIAEAAIADgBIABgDIABgEIgBgDIgBgDIgDgCIgDgBgAipA2IgFgEQgCgCgBgFIgBgJIABgJQABgFACgBIAFgFIAGAAIAGAAQADACABADIAEAGIABAJIgBAJIgEAHQgBADgDABIgGABgAinATIgDADIgCAEIAAAIIAAAIIACAFIADADIAEAAIADAAIADgDIACgFIABgIIgBgIIgCgEIgDgDIgDgBgACKA3IAAgLIgTAAIgBgBIAAgDIATgaIAFAAIAAAaIAGAAIAAAEIgGAAIAAALgAB7AoIAPAAIAAgUgAA6A3IAQghIACgDIgVAAIgBAAIAAgCIAAgDIAcAAIAAAEIgSAjIgBABIgCABgAgoA3IAMgQIACgEIgDADIgEAAIgEgBIgEgCIgDgEIAAgFIABgFIACgEIAFgDIAFAAIAGAAIAEADIACAEIABAFIgBAHIgBADIgMARIgBACgAgiATIgDABIgBADIgBADQAAADACADQACACAEAAIADgBIADgCIACgCIAAgDIgBgDIgBgDIgDgBIgDgBgAhKA3IATgkIgVAAIgBAAIAAgFIAbAAIAAAEIgRAjIgBABIgCABgAhrA3IATgkIgVAAIgBAAIAAgFIAbAAIAAAEIgRAjIgBABIgCABgAh+A3IAAgLIgTAAIAAgBIgBgDIAUgaIAFAAIAAAaIAGAAIAAAEIgGAAIAAALgAiMAoIAOAAIAAgUgAjOA3IAAgFIAJAAIAAgdIgHAGIgBAAIAAABIgBgBIAAgBIgCgCIAMgKIAEAAIAAAkIAIAAIAAAFgAICgDIAAgKIgGAAIgFgDIgDgFIgBgGIABgGIADgFIAFgDIAGgBIAAgMIAFAAIAAAMIAHABIAFADQACACABADIABAGIgBAGIgDAFIgFADIgHAAIAAAKgAIHgQIAFgCIADgCIACgDIAAgEIAAgEIgCgEIgDgCIgFgBgAH7gjQgDAEAAAEQAAAEADADQADADAFABIAAgWQgEAAgEADgAFygDIAAgKIgYAAIAAAJIAAAAIgBABIgEAAIAAgNIABAAIACgBIACgCIACgCIABgEIACgQIASAAIAAAYIAGAAIAAANIgBABgAFjgeIgDAKIgCAEIAOAAIAAgWIgJAAgAASgDIAAgKIgnAAIAAgcIAFAAIAAAYIAMAAIAAgYIAEAAIAAAYIAMAAIAAgYIAFAAIAAAYIAFAAIAAAOgAhwgDIAAgKIgYAAIAAAJIAAAAIgBABIgEAAIAAgNIABAAIACgBIACgCIACgCIABgEIACgQIASAAIAAAYIAGAAIAAANIgBABgAh/geIgDAKIgCAEIAOAAIAAgWIgJAAgAkCgDIAAgmIAEAAIABABIAAADIAFgEIAFgBIAFABIADACIACAGIABAFIgBAGIgCAGIgEADIgGAAIgEAAIgDgCIAAAMgAj5glQAAABgBAAQAAAAgBAAQAAABAAAAQgBABAAABIAAANIADADIADABQAEgBACgDQACgBAAgHIAAgEIgBgEIgDgBIgDgBQAAAAgBAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAwogDIAAgKIghAAIAAAJIAAAAIgCABIgDAAIAAgPIAEAAIACgBIABgDIADgKIACgWIAYAAIAAAkIAHAAIAAAOIgBAAIgBABgAw/gcIgCAGIgCAEIATAAIAAgfIgNAAgAG4gGIAAAAIABgDIABgBIABgBIABgCIgBAAIgBAAIgBAAIgBgDIABgDIACgBIACAAIABABIABACIAAAEIgCADIgBADIgDACgAE9gGIgBAAIAAAAIABgDIABgBIABgBIABgCIgBAAIgBAAIgBAAIgBgDIABgDIACgBIACAAIABABIABAEIAAACIgBADIgCADIgCACgAlHgGIgBAAIAAAAIABgDIABgBIABgBIABgCIgBAAIgBAAIgBAAIgBgDIABgDIACgBIACAAIABABIABACIAAAEIgBADIgFAFgApegGIAAAAIAAAAIAAgBIABgCIABgBIABgBIAAgCIgBAAIgBAAIgBgCIAAgBIABgDIACgBIACAAIABABIABAEIgBACIgBADIgBADIgDACgAS8gNIgDAAIgFgDIACgDIABgBIACAAIABABIADABIADABIAEgBIADgCIACgCIAAgFIAAgDIgCgCIgDgCIgEAAIgGABIgDgBIADgUIATAAIAAADIAAACIgDAAIgMAAIgCAKIAGAAIAFABIAEACIADAFIABAEIgBAGIgEAFIgEADIgGABgAQXgNIgDAAIgFgDIACgDIABgBIABAAIAFACIADABIAEgBIACgCIACgCIABgFIgBgDIgBgCIgDgCIgEAAIgGABIgEgBIAEgUIATAAIAAADIgBACIgCAAIgNAAIgCAKIAGAAIAGABIAEACIACAFIABAEIgBAGIgDAFIgFADIgFABgAGfgNIgFgCIgDgEIgBgFIACgHQADgCADgBIgFgEQgBgCAAgDIABgFIACgDIAEgCIAFgBIAFABIAEACIADADIABAFQAAADgCACIgFAEQADABADACIACAHIgBAFIgDAEQgCABgCABIgGABgAGegeIgBACIgBAEIABADIABACIADACIADABIAEgBIACgCIACgCIABgDIgBgEIgCgCIgDgBIgGAAgAGhgxIgCABIgBACIgBADIABADIABACIACABIADABIAEgBIACgBIABgCIAAgGIgBgCIgDgBIgDgBgAlhgNIgCgBIgCgCIgBgEIABgDIADgDIAGgCIAIgBIAAgCIgBgFQgBAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAIgDAAIgCABIgBABIgCABIgBAAIAAgBIgBgCIAFgDIAGgBIAEABIAEACIACADIAAAFIAAASIgCAAIgBAAIgBgBIgBgCIgCACIgFABIgDABgAlagZIgEABIgCACIgBACIABABIABACIADABIAEgBIACgBIACgCIAAgFgArbgNIgDAAIgFgDIACgDIACgBIABAAIAEACIADABIAEgBIADgCIACgCIAAgFIAAgDIgCgCIgDgCIgDAAIgHABIgDgBIADgUIATAAIAAADIAAACIgDAAIgMAAIgCAKIAGAAIAFABIAEACIADAFIABAEIgBAGIgEAFIgEADIgGABgAvagOIgGgEIgEgGQgBgEAAgFQAAgEABgEQACgFADgCQACgDAEgBIAIgCQAEAAAEACIAGADIgCADIgBAAIgBAAIgGgDIgEAAIgGABIgEADIgDAFIgBAHQAAADABADIADAFIAEADIAGABIADAAIADAAIACgCIACgBIABAAIAAgBIADADQgCAEgEABQgFACgEAAQgEAAgEgCgAVwgNIAAgSIgVAAIAAASIgGAAIAAgpIAGAAIAAASIAVAAIAAgSIAGAAIAAApgAUygNIAAgpIANAAIAGACIAFACIADAEIABAFIgBAFIgDAFIgFACIgGABIgHAAIAAAPgAU4ggIAHAAIAEgBIADgCIABgDIABgDIAAgEIgCgCIgDgCIgEAAIgHAAgAUUgNIAAgpIAYAAIAAAFIgSAAIAAAkgATvgOIgGgEQgDgDgBgDIgCgJQAAgEACgEQACgFACgCQADgDADgBQAEgCAFAAQAEAAAEACQAEABACADQACABACAGQACAEAAAEIgCAJQgBAEgDACIgGAEQgEABgEAAQgFAAgEgBgATygwIgFADIgDAFIgBAHIABAGIADAFIAFADIAGABIAGgBIAEgDIADgFIABgGIgBgHIgDgFIgEgDIgGgBgASXgNIAAgEIAJAAIAAgbIAAgDIgHAHIgBAAIAAAAIgBAAIgBgBIgBgCIAMgLIAEAAIAAAlIAIAAIAAAEgAR6gNIgFgFQgCgBgBgFIgBgJIABgJIADgHIAFgEIAGgBIAGABIAEAEQADADAAAEQACAEAAAFQAAAGgCADQAAAEgDACIgEAFIgGAAIgGAAgAR8gxIgDADIgCAFIgBAIIABAIIACAEIADADIAEABIADgBIADgDIACgEIABgIIgBgIIgCgFIgDgDIgDAAgARRgNIAAgCIABgCIAQgQIACgDIABgDIABgDIgBgEIgBgCIgDgBIgCAAIgDAAIgCABIgCACIgBADIgBABIgCAAIgDAAIACgGQAAAAABAAQAAgBAAAAQABgBAAAAQABgBAAAAIAEgDIAFAAIAFAAIAEADIACADIABAGIAAADIgCAFIgDADIgDADIgLALIAFgBIANAAIACAAIAAACIAAADgAQ0gNIAAgEIAJAAIAAgeIgHAHIgBAAIgBAAIgBgBIgBgCIAMgLIAEAAIAAAlIAIAAIAAAEgAQAgNIAAgKIgTAAIgBgBIAAgEIATgaIAFAAIAAAaIAGAAIAAAFIgGAAIAAAKgAPxgcIAPAAIAAgUgAPVgNIgFgFQgDgCAAgEQgCgDAAgGQAAgFACgEQAAgEADgDIAFgEIAFgBIAGABQADABACADIADAHIABAJIgBAJQgBAFgCABQgBADgEACIgGAAIgFAAgAPXgxIgDADIgCAFIgBAIIABAIIACAEIADADIADABIAEgBIADgDIACgEIABgIIgBgIIgCgFIgDgDIgEAAgAOvgNIARghIACgDIgVAAIgBAAIAAgBIAAgEIAcAAIAAADIgBACIgRAjIgBABIgCAAgAOOgNIARghIACgDIgVAAIgBAAIAAgBIAAgEIAcAAIAAADIgBACIgRAjIgBABIgCAAgANugNIAAgSIgVAAIAAASIgGAAIAAgpIAGAAIAAASIAVAAIAAgSIAGAAIAAApgANDgNIAAgSIgWAAIAAASIgGAAIAAgpIAGAAIAAASIAWAAIAAgSIAGAAIAAApgAMXgNIAAgiIgCAFIgSAcIgDABIgEAAIAAgpIAFAAIAAAiIACgEIAUgdIACgBIAEAAIAAApgALOgNIAAgEIAJAAIAAgeIgHAHIgBAAIgBAAIgDgDIANgLIAEAAIAAAlIAIAAIAAAEgAKwgNIgEgFQgDgCAAgEQgCgDAAgGQAAgFACgEQAAgEADgDIAEgEIAGgBIAGABQADABACADIADAHIABAJIgBAJQgBAFgCABQgBADgEACIgGAAIgGAAgAKzgxIgDADIgCAFIgBAIIABAIIACAEIADADIADABIAEgBIADgDIACgEIABgIIgBgIIgCgFIgDgDIgEAAgAKPgNIgEgFQgDgCAAgEQgCgDAAgGQAAgFACgEQAAgEADgDIAEgEIAGgBIAGABIAFAEIADAHIABAJIgBAJQgBAFgCABQgBACgEADIgGAAIgGAAgAKSgxIgDADIgCAFIgBAIIABAIIACAEIADADIADABIAEgBIADgDIACgEIABgIIgBgIIgCgFIgDgDIgEAAgAJrgNIAAgEIAIAAIAAgbIABgDIgIAHIAAAAIgBAAIgBgBIgCgCIAMgLIAFAAIAAAlIAIAAIAAAEgAJJgNIgFAAIgEgDIgDgFIgBgGIABgGIADgFIAEgDIAGgBIAFABIAFACIgCACIgBABIgBAAIgBgBIgFgBIgDABIgDACIgCAEIAAAEIAAAFIACACIADADIADABIADgBIACgBIABgBIABgBIABABIACACIgCADIgGABgAIxgNIAAgVIgCADIgNARIgBABIgBAAIgDAAIAAgcIAFAAIAAAVIABgCIABAAIABgDIAMgPIABgBIABAAIADAAIAAAcgAHbgNIgFgDQgCgDAAgCIgBgGIABgGIACgFIAFgDIAGgBIAFABIAFADIACAFIABAGIgBAGQAAACgCADIgFADIgFAAIgGAAgAHagjQgCACAAAGQAAAFACACQADADAEABQAEgBACgDQACgCAAgFQAAgGgCgCQgCgDgEAAQgEAAgDADgAF9gNIgBAAIgBgBIAAgCIAAgCIABgBIABgBIADAAIABABIABABIAAACIAAACIgBABIgBAAgAEwgNIAAgVIgCADIgNARIgBABIgBAAIgDAAIAAgcIAFAAIAAAVIABgCIABAAIANgSIABgBIABAAIADAAIAAAcgADkgNIAAgBIABgBIAAgCIATgTIABgDIABgDIgBgEIgCgCIgCgBIgDAAIgCAAIgDABIgBACIgBADIgBABIgCAAIgDAAIACgGIADgDIAEgDIAFAAIAFAAIAEADIACADIABAGIgCAIIgRARIAFgBIANAAIABAAIABACIAAADgADKgNIAAgVIgBADIgCABIgLAQIgBABIgBAAIgEAAIAAgcIAGAAIAAAVIABgCIAAAAIACgDIALgPIABgBIABAAIADAAIAAAcgACpgNIAAgVIgBADIgNARIgBABIgBAAIgDAAIAAgcIAFAAIAAAVIABgCIAAAAIANgSIABgBIABAAIAEAAIAAAcgACNgNIgCAAIgHgKIgBgCIgDAAIgDAAIAAAMIgFAAIAAgcIAFAAIAAAMIADAAIACgBIABgBIAGgJIABgBIACAAIAEAAIgHAKIgCACIgCABIADABIABADIAIALgABogNIgFAAIgEgDIgDgFIgBgGIABgGIACgFIAFgDIAGgBIAFABIAEACIgBACIgBABIgBAAIgCgBIgBgBIgDAAIgEABIgCACIgCAEIgBAEIABAFQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABAAIACADIAEABIADgBIACgBIABgBIABgBIABABIACACIgDADIgFABgABPgNIAAgNIgNAAIAAANIgGAAIAAgcIAGAAIAAALIANAAIAAgLIAGAAIAAAcgAAvgNIAAgVIgBADIgNARIgBABIgBAAIgEAAIAAgcIAGAAIAAAVIABgCIAAAAIACgDIALgPIABgBIABAAIAEAAIAAAcgAgvgNQgDgBgBgCQgCgDgBgCIgBgGIABgGIADgFQABgCADgBIAGgBIAGABIAEADIADAFIABAGIgBAGQgBACgCADIgEADIgGAAIgGAAgAgvgjQgCACAAAGQAAAFACACQACADAEABQAEgBACgDQACgCAAgFQAAgGgCgCQgCgDgEAAQgEAAgCADgAhXgNIAAgpIANAAIAHACIAEACIADAEIABAFIgBAFIgDAFIgFACIgGABIgHAAIAAAPgAhRggIAHAAIAEgBIADgCIACgDIAAgDIAAgEIgCgCIgDgCIgEAAIgHAAgAiegNIgFgBIgDgDIACgCIABgBIABABIABABIADABIACABIADgBIACgBIACgCIAAgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAIgFgBIgDAAIAAgEIADAAQADABACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAIgBgCIgBgBIgCgBIgDAAIgEABIgCABIgBAAIgBgBIgBgCIAEgCIAGgBIAEABIAEABIACACIAAAEIAAACIgBABIgBABIgDACIAFADIABAEIgBADIgCAEIgEABIgEAAgAi1gNIgGAAIgEgDQgCgDgBgCIgBgHIABgFIADgFIAEgDIAGgBIAEABIAEACIADAFIABAFIgBABIgBABIgTAAIABAFIACADIADACIADABIAEgBIAFgDIABABIABACIgCACIgDACIgDAAgAi7gkQgCADAAACIAPAAIgBgCIgBgDIgCgCIgDAAQgEAAgCACgAjbgNIgFgDQgCgDAAgCIgBgGIABgGIACgFIAFgDIAGgBIAFABIAFADIACAFIABAGIgBAGQAAACgCADIgFADIgFAAIgGAAgAjcgjQgCACAAAGQAAAFACACQADADAEABQAEgBACgDQACgCAAgFQAAgGgCgCQgCgDgEAAQgEAAgDADgAkRgNIAAgkIgUAAIAAAkIgGAAIAAgpIAgAAIAAApgAmAgNIAAgcIALAAIAEAAIAEABIABACIABAEIAAABIgBACIgCACIgDABQAEABABACQABAAAAAAQAAABABAAQAAABAAABQAAAAAAABIgBADIgCADIgEACIgEAAgAl7gQIAGAAQABAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBIAAgBIgBgBIgCgBIgJAAgAl7gdIAGAAIACgBIACgBIABgBIAAgCIAAgCIgBgBIgCgBIgCAAIgGAAgAmIgNIgDAAIgGgKIgCgCIgCAAIgDAAIAAAMIgGAAIAAgcIAGAAIAAAMIACAAIACgBIACgBIAGgJIABgBIABAAIAFAAIgIAKIgBACIgCABIACABIACADIAHALgAmugNIgFAAIgEgDIgDgFIgBgGIABgGIADgFIAEgDIAGgBIAGABIAEACIgCACIgBABIgBAAIgBgBIgCgBIgDAAIgDABIgDACIgCAEIAAAEIAAAFIACACIADADIADABIADgBIACgBIABgBIABgBIABABIACACIgCADIgGABgAnTgNQgDgBgBgCIgDgFIgBgGIABgGIADgFQABgCADgBIAGgBIAGABIAEADIADAFIABAGIgBAGQgBACgCADIgEADIgGAAIgGAAgAnTgjQgCACAAAGQAAAFACACQABADAFABQAEgBACgDQACgDAAgEQAAgEgCgEQgCgDgEAAQgFAAgBADgAnogNIAAgeIABgCIgOAZIgBABIgBAAIgBAAIgCgBIgOgZIAAAgIgFAAIAAgpIAFAAIABACIAPAbIABgCIABgBIANgYIABgCIAGAAIAAApgAopgNIgBAAIgBgBIAAgCIAAgCIABgBIABgBIADAAIABABIABABIAAACIAAACIgBABIgBAAgApCgNIAAgcIATAAIAAADIgOAAIAAAZgAp7gNIAOgTIgDACIgEAAIgEAAIgEgCIgDgEIgBgFIABgFIADgEQACgCADgBIAFgBIAFABIAFADIACAEIABAFIAAADIgDAHIgLARIgCABIgBAAgAp1gxIgDABIgCADIAAAEQAAACACADQACADAEAAIADgBIADgCQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBIABgCIgBgEIgBgDIgDgBIgDAAgAqcgNIAAgEIAIAAIAAgeIgHAHIgBAAIAAAAIgBgBIgCgCIAMgLIAFAAIAAAlIAIAAIAAAEgAqwgNIAAgKIgTAAIAAgBIgBgEIAUgaIAFAAIAAAaIAGAAIAAAFIgGAAIAAAKgAq+gcIAOAAIAAgUgAsAgNIAAgEIAJAAIAAgeIgHAHIgBAAIAAAAIgBAAIgBgBIgBgCIAMgLIAEAAIAAAlIAIAAIAAAEgAshgNIAAgEIAJAAIAAgbIAAgDIgHAHIgBAAIgBAAIgBgBIgBgCIAMgLIAEAAIAAAlIAIAAIAAAEgAtXgNIgCgBIAAgEIACgCIADAAIACACIAAAEIgCABgAt2gNIAAgpIAZAAIAAAFIgTAAIAAAkgAuDgNIgCgBIgBgCIABgCIACgCIADAAIACACIAAAEIgCABgAuUgNIAAgSIgVAAIAAASIgGAAIAAgpIAGAAIAAASIAVAAIAAgSIAGAAIAAApgAu8gNIgCAAIAAgBIgBgCIABgCIAAgBIACgBIADAAIABABIAAABIABACIgBACIAAABIgBAAgAwBgNIAAgfIAAgDIgBADIgUAeIgBABIgBAAIgFAAIAAgpIAGAAIAAAgIAAACIACgEIAUgdIABgBIAFAAIAAApgAxagNIAAgSIgVAAIAAASIgGAAIAAgpIAGAAIAAASIAVAAIAAgSIAGAAIAAApgAx/gNIgBAAIgFgKIgSAAIgDAJIgBABIgBAAIgFAAIAQgpIAGAAIARApgAyPgsIgGAQIAPAAIgGgQIgBgCIgBgCgAyngNIgBAAIgMgRIgBgBIgDAAIgEAAIAAASIgGAAIAAgpIAGAAIAAASIAGAAIACgCIAKgOIABgBIACgBIAFAAIgNARQAAABAAAAQAAAAgBABQAAAAgBAAQgBABAAAAIACABIAPAUgA0OgOIgGgEIgEgGIgCgJQAAgEACgEIAEgHQADgDADgBQAEgCAFAAQAEAAAEACQADABADADIAEAHQACAEAAAEIgCAJIgEAGIgGAEQgEABgEAAQgFAAgEgBgA0LgwIgFADQgCACgBADIgBAHIABAGQABADACACQACADADAAIAGABIAFgBQADAAACgDQACgCABgDIABgGIgBgHQgBgDgCgCQgBgBgEgCIgFgBgA07gOIgHgEQgCgCgCgEIgBgJQAAgEABgEQACgGACgBQACgDAFgBIAIgCQAFAAADACQAEABADADIAEAHQABAEAAAEIgBAJIgEAGIgHAEQgDABgFAAIgIgBgA05gwIgFADIgCAFIgBAHIABAGIACAFIAFADIAGABIAGgBIAEgDIADgFIABgGIgBgHIgDgFIgEgDIgGgBgA1pgOIgGgEQgDgDgCgDIgBgJQAAgEABgEQACgFADgCQACgDAEgBQAEgCAEAAQAFAAADACQAFABACADQACABACAGQABAEAAAEIgBAJQgCAEgCACIgHAEQgDABgFAAQgEAAgEgBgA1ngwIgEADIgDAFIgBAHIABAGIADAFIAEADIAGABIAGgBIAFgDIACgFIABgGIgBgHIgCgFIgFgDIgGgBgAtCgRIgBgBIAAgCIAFgHIABgBIgBAAIAAgBIgFgHIAAgCIABgBIACgBIAHAMIAAAAIgHAMgAtLgRIAAgBIAAgCIAEgHIABgBIAAAAIgBgBIgEgHIAAgCIAAgBIACgBIAHAMIAAAAIgHAMgAzVgcIAAAAIAHgMIACABIABABIAAACIgFAHIgBABIABABIAFAHIAAACIgBABIgCABgAzdgcIAAAAIAHgMIACABIAAABIAAACIgEAHIgBABIABABIAEAHIAAACIAAABIgCABgAEGgcIAAgEIAPAAIAAAEgAElguIgCgCQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgBgDIABgBIABgBIADAAIAAADIABABIABABIACAAIACAAIABgBIABgEIADAAIABABIAAABIAAADIgCABIgDACIgDAAgADAguIgDgCIgCgBIAAgDIAAgBIABgBIADAAIAAADIABABIABABIACAAIACAAIACgBIAAgBIAAgDIAEAAIAAABIABABIgBADIgBABIgDACIgEAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal, new cjs.Rectangle(-139.8,-5.5,279.7,11), null);


(lib.know = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AgXAtIAAhZIAvAAIAAAQIgeAAIAAAVIAdAAIAAAPIgdAAIAAAVIAeAAIAAAQg");
	this.shape.setTransform(46,0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00A7E0").s().p("Ag0AtIAAhZIARAAIAABJIAbAAIAAhJIAQAAIAABJIAcAAIAAhJIAQAAIAABZg");
	this.shape_1.setTransform(36.7,0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00A7E0").s().p("AgdAtIAAhZIARAAIAAAjIAMAAQAOAAAIAHQAIAGAAANQAAANgJAHQgIAIgNAAgAgMAdIAMAAQAGAAADgDQAEgDAAgGQAAgFgEgDQgDgDgGAAIgMAAg");
	this.shape_2.setTransform(27.4,0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00A7E0").s().p("AAZAtIgZhCIgXBCIgTAAIAkhZIANAAIAkBZg");
	this.shape_3.setTransform(19.2,0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00A7E0").s().p("AghAhQgNgNAAgUQAAgSANgOQAOgOATAAQAUAAAOAOQANAOAAASQAAAUgNANQgNAOgVAAQgTAAgOgOgAgVgVQgJAJAAAMQAAANAJAIQAJAKAMgBQAOABAIgKQAJgIAAgNQAAgMgJgJQgIgIgOgBQgMABgJAIg");
	this.shape_4.setTransform(9.7,0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00A7E0").s().p("AgeAtIAAhZIA0AAIAAAQIgiAAIAAATIAMAAQAQAAAHAIQAIAGAAAMQAAANgJAHQgIAIgOAAgAgMAdIAMAAQAHAAADgDQADgDABgGQAAgFgDgDQgFgDgGAAIgMAAg");
	this.shape_5.setTransform(1.2,0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00A7E0").s().p("AgdAtIAAhZIARAAIAAAjIAMAAQAOAAAIAHQAIAGAAANQAAANgIAHQgIAIgOAAgAgMAdIAMAAQAGAAAEgDQADgDAAgGQAAgFgDgDQgEgDgGAAIgMAAg");
	this.shape_6.setTransform(-8.7,0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00A7E0").s().p("AgHAtIAAhJIgRAAIAAgQIAxAAIAAAQIgRAAIAABJg");
	this.shape_7.setTransform(-15,0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7E0").s().p("AAZAtIgJgXIggAAIgJAXIgSAAIAlhZIANAAIAlBZgAgKAGIAUAAIgKgag");
	this.shape_8.setTransform(-21.5,0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7E0").s().p("AAQAtIAAgmIgfAAIAAAmIgRAAIAAhZIARAAIAAAkIAfAAIAAgkIARAAIAABZg");
	this.shape_9.setTransform(-30.1,0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00A7E0").s().p("AgVAnQgJgIABgOIARAAQAAAGADADQADAFAGAAQAHAAADgEQAEgDAAgFQAAgGgDgDQgEgDgFAAIgIAAIAAgQIAGAAQAGABACgDQADgDAAgFQAAgFgDgDQgDgCgEAAQgFAAgCACQgDADAAAEIgRAAQAAgLAHgHQAHgHANgBQALAAAIAIQAIAGAAAMQAAAGgEAFQgDAFgGADQAHABAFAGQAEAGAAAIQAAAMgJAIQgJAGgNAAQgNAAgIgHg");
	this.shape_10.setTransform(-37.6,0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00A7E0").s().p("AgRAtIALgXIgihCIAUAAIAWAvIAVgvIATAAIgqBZg");
	this.shape_11.setTransform(-44.8,0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AolBvIAAjdIRKAAIAADdg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.know, new cjs.Rectangle(-54.9,-11.1,109.9,22.3), null);


(lib.eko = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAsQgSgSAAgaQAAgZASgSQAQgSAbAAQAaAAATASQARASABAZQAAAZgTATQgSASgaAAQgbAAgQgSgAAJgcQgLAMAAAQQAAARALALQAMAMARAAQARAAALgMQAMgMAAgQQAAgQgMgMQgKgLgSAAQgSAAgLALgAj5AsQgSgSAAgaQAAgZASgSQASgSAbAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgbAAgSgSgAjpgcQgMANAAAPQAAARAMALQALAMASAAQAQAAANgMQALgMAAgQQAAgPgLgNQgMgLgRAAQgSAAgLALgAnMA0QgOgJgHgQIAaAAQAFAHAHADQAIADAKAAQAOAAAKgIQAKgIADgOIg1AAIAAgUIA1AAQgDgPgKgHQgKgHgOAAQgLAAgHADQgJAEgEAHIgaAAQAHgQAPgKQAPgKATAAQAZAAASASQASARAAAaQAAAagSASQgRASgbAAQgSAAgPgKgAGjA7IAAh2IA/AAIAAAWIgpAAIAAAbIAnAAIAAAUIgnAAIAAAbIApAAIAAAWgAFrA7IAAhgIgVAAIAAgWIBCAAIAAAWIgXAAIAABggAEHA7IAAh2IAWAAIAAAuIARAAQATAAAKAKQALAJAAAQQAAAQgLALQgMAKgRAAgAEdAlIARAAQAJAAAEgEQAFgEAAgHQgBgGgEgFQgFgEgIAAIgRAAgADbA7IAAhYIgfBYIgTAAIgfhYIAABYIgWAAIAAh2IAeAAIAgBaIAhhaIAeAAIAAB2gAg9A7IAAgyIgrAAIAAAyIgXAAIAAh2IAXAAIAAAwIArAAIAAgwIAVAAIAAB2gAkjA7Iglg0IAAA0IgWAAIAAh2IAWAAIAAA0IAlg0IAaAAIgtA7IAtA7g");
	this.shape.setTransform(48.3,6.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.eko, new cjs.Rectangle(0,0,96.5,12.4), null);


(lib.blue = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2191CC").s().p("Egl9ATiMAAAgnDMBL7AAAMAAAAnDg");
	this.shape.setTransform(243,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blue, new cjs.Rectangle(0,0,485.9,250), null);


(lib.text = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// know
	this.instance = new lib.know();
	this.instance.parent = this;
	this.instance.setTransform(0,70.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(237).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(53).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// Слой 1
	this.instance_1 = new lib.eko();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,-43,1,1,0,0,0,48.3,6.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(74).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(216).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// t4
	this.instance_2 = new lib.t4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,-10.7);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(225).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// t3
	this.instance_3 = new lib.t3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,-10.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(150).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(75));

	// t2
	this.instance_4 = new lib.t2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-1.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(75).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(150));

	// t1
	this.instance_5 = new lib.t1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,-19.2);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(225));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59.2,-49.7,118.6,61);


(lib.snow2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(33,145,204,0)","#2191CC"],[0,1],-20.4,0,20.5,0).s().p("AjMOYIAA8vIGZAAIAAcvg");
	this.shape.setTransform(246.5,92);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A1ZUAMAAAgn/MAqzAAAMAAAAn/g");
	mask.setTransform(129,119.1);

	// Слой 1
	this.instance = new lib.snow();
	this.instance.parent = this;
	this.instance.setTransform(606,0,1,1,0,0,180);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.snow2, new cjs.Rectangle(0,0,267,187), null);


(lib.pics = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A8RTcMAAAgm3MA4jAAAMAAAAm3g");
	mask.setTransform(-1.9,-0.5);

	// p4
	this.instance = new lib.p4();
	this.instance.parent = this;
	this.instance.setTransform(-33,-25.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(225).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// p1
	this.instance_1 = new lib.p1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-33,-25.5);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(305));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-182.9,-124.9,362,248.9);


// stage content:
(lib._970x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		
		var white = this.white;
		var blue = this.blue;
		var legal = this.legal;
		var text = this.text;
		var logo = this.logo;
		var pics = this.pics;
		var snow2 = this.snow2;
		
		function res() {
			
			var wdt = stage.canvas.width;
			var hgt = stage.canvas.height;
			
			var sc = wdt/300;
		
			
				text.scaleX = 1.4;
				text.scaleY = 1.4;
				text.x = wdt*0.82;
				text.y = 80;
				
				logo.scaleX = 1.5;		
				logo.scaleY = 1.5;
				logo.x = wdt*0.18;
				logo.y = 125;
				
				pics.x = 510;
				pics.y = 125;
				
				pics.scaleX = 1;
				pics.scaleY = 1;
				
				white.x = 0;
				white.y = 0;
				white.scaleX = sc/4;
				white.scaleY = 5;
				
				blue.x = 0;
				blue.y = 0;
				blue.scaleX = sc;
				
				legal.x = wdt*0.8 - 140;
				
				snow2.x = 0;
				snow2.y = 0;
				snow2.scaleX = 1;
				snow2.scaleY = 1;
		}
		
		res();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EhLsgTcMCXZAAAMAAAAm5MiXZAAAg");
	this.shape.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// logo
	this.logo = new lib.logo();
	this.logo.name = "logo";
	this.logo.parent = this;
	this.logo.setTransform(152,27.3);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

	// text
	this.text = new lib.text();
	this.text.name = "text";
	this.text.parent = this;
	this.text.setTransform(238,118,1,1,0,0,0,0,-19.3);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(1));

	// snow2
	this.snow2 = new lib.snow2();
	this.snow2.name = "snow2";
	this.snow2.parent = this;
	this.snow2.setTransform(-354.9,-300);

	this.timeline.addTween(cjs.Tween.get(this.snow2).wait(1));

	// white
	this.white = new lib.white();
	this.white.name = "white";
	this.white.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.white).wait(1));

	// legal
	this.legal = new lib.legal();
	this.legal.name = "legal";
	this.legal.parent = this;
	this.legal.setTransform(10.9,235.7,1,1,0,0,0,-139.8,-5.5);

	this.timeline.addTween(cjs.Tween.get(this.legal).wait(1));

	// pics
	this.pics = new lib.pics();
	this.pics.name = "pics";
	this.pics.parent = this;
	this.pics.setTransform(147,149,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.pics).wait(1));

	// blue
	this.blue = new lib.blue();
	this.blue.name = "blue";
	this.blue.parent = this;
	this.blue.setTransform(-95,0);

	this.timeline.addTween(cjs.Tween.get(this.blue).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(122.1,-183.9,1333.5,559.5);
// library properties:
lib.properties = {
	id: '2138A65B9025B84A912883EE1BCC19F6',
	width: 970,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/970x250_atlas_P_.png", id:"970x250_atlas_P_"},
		{src:"images/970x250_atlas_NP_.jpg", id:"970x250_atlas_NP_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['2138A65B9025B84A912883EE1BCC19F6'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;