(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"320x100_atlas_", frames: [[0,402,303,94],[302,0,30,30],[0,0,300,199],[0,201,300,199]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib._1Ресурс3 = function() {
	this.spriteSheet = ss["320x100_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._1Ресурс4 = function() {
	this.spriteSheet = ss["320x100_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._1 = function() {
	this.spriteSheet = ss["320x100_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["320x100_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglApQgRgRAAgYQAAgXARgRQARgRAXAAQASAAANAJQAOAKAHAPIgXAAQgHgHgGgDQgHgEgIAAQgQAAgKALQgLALAAAPQAAAPALAMQALALAPAAQAIAAAGgDQAIgDAEgHIAYAAQgGAPgOAJQgOAJgRAAQgXAAgRgRg");
	this.shape.setTransform(54.3,7.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgA3IgLgdIgpAAIgLAdIgXAAIAvhuIAPAAIAvBugAgMAHIAZAAIgNggg");
	this.shape_1.setTransform(43.2,7.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AASA3IAAgpIgSAAQgLAAgGgDQgFgBgFgDQgFgFgDgFQgCgGAAgKIAAgkIAUAAIAAAhIABAJQABACACACQACACADAAIAIABIASAAIAAgxIAUAAIAABug");
	this.shape_2.setTransform(32.8,7.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAZBFIAAhNIgxBNIgUAAIAAhuIAUAAIAABNIAxhNIAUAAIAABugAgRg1QgIgGgBgJIARAAQAAADADACQADACADAAQAEAAADgCQACgCABgDIARAAQgCAJgHAGQgHAGgLAAQgKAAgHgGg");
	this.shape_3.setTransform(22.8,6.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdA3IAAhuIA7AAIAAAUIgmAAIAAAaIAkAAIAAATIgkAAIAAAZIAmAAIAAAUg");
	this.shape_4.setTransform(13.5,7.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AglApQgRgRAAgYQAAgXARgRQARgRAXAAQASAAANAJQAOAKAHAPIgYAAQgFgHgHgDQgHgEgIAAQgQAAgKALQgLALAAAPQAAAPALAMQALALAPAAQAIAAAGgDQAIgDAEgHIAYAAQgHAQgNAIQgOAJgRAAQgXAAgRgRg");
	this.shape_5.setTransform(3.7,7.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgpApQgRgSABgXQAAgXAQgRQARgRAYAAQAZAAARARQARARAAAXQAAAXgRASQgRARgZAAQgXAAgSgRgAgagaQgLAMAAAOQAAAQALALQALALAPAAQAQAAALgLQALgMAAgPQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_6.setTransform(-12,7.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAmA3IAAhSIgdBSIgRAAIgdhSIAABSIgVAAIAAhuIAcAAIAeBUIAfhUIAcAAIAABug");
	this.shape_7.setTransform(-25.2,7.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AARA3IAAgrIgBAAIgcArIgYAAIAegoQgNgCgIgJQgJgJAAgNQAAgSALgJQAKgJAUgBIAgAAIAABugAgKgeQgFAEAAAIQAAAIAFAEQAFAEAJAAIANAAIAAghIgNAAQgJAAgFAFg");
	this.shape_8.setTransform(-36.9,7.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAgAAQATABAJAJQAKAJAAAQQABAPgLAJQgKAKgSAAIgKAAIAAApgAgNgGIALAAQAIAAAEgDQAFgDAAgIQAAgHgFgEQgDgEgJAAIgLAAg");
	this.shape_9.setTransform(-45,7.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAUA3IAAhaIgnAAIAABaIgVAAIAAhuIBRAAIAABug");
	this.shape_10.setTransform(-54.6,7.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVFUQgPgPAAgVQAAgVAPgOQAOgPAVAAQAVAAAPAPQAOAOAAAVQAAAVgOAPQgPAOgVAAQgVAAgOgOgAgJEZQgJAJAAAOQAAAOAJAJQAJAKAOAAQAOAAAJgKQAKgKAAgNQAAgNgKgKQgJgKgOAAQgOAAgJAKgAjVFUQgOgPAAgVQAAgUAOgQQAQgOAUAAQAQAAALAIQAMAHAGAOIgUAAQgEgFgHgEQgGgDgIAAQgOAAgJAKQgJAKAAANQAAAOAJAJQAKAKAOAAQAGAAAGgDQAGgDAFgFIAUAAQgGANgLAHQgMAIgPAAQgVAAgPgOgAEjFgIAAgmIAAAAIgaAmIgVAAIAbgkQgMgBgHgIQgHgHAAgNQAAgOAJgJQAJgIASAAIAcAAIAABggAELEVQgEAEAAAGQAAAHAEAEQAFAEAJAAIAKAAIAAgdIgKAAQgJAAgFAEgADVFgIAAhEIgrBEIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggABNFgIAAhgIAXAAQARAAAIAGQAJAHAAAMQAAAGgDAFQgDAFgFACQAIAEAEAFQAEAHAAAIQAAAOgJAHQgKAIgTAAgABfFPIALAAQAIAAAEgEQAEgDAAgGQAAgFgEgEQgEgCgIgBIgLAAgABfElIAIAAQAGAAADgDQAEgCAAgFQAAgFgEgDQgDgCgGAAIgIAAgAg4FgIgbhIIgaBIIgUAAIAmhgIAQAAIAmBggAkfFgIALgZIgkhHIAVAAIAZAzIAXgzIATAAIgrBggAibC+IAAgSIhAAAIAAhgIASAAIAABPIAjAAIAAhPIASAAIAABPIALAAIAAAjgAnTCgQgOgPAAgVQAAgUAOgQQAQgOAUAAQAQAAALAIQAMAHAGAOIgVAAQgEgGgGgDQgGgDgIAAQgOAAgJAKQgJAKAAANQAAAOAJAJQAJAKAOAAQAHAAAGgDQAGgDAFgFIAUAAQgGANgLAHQgMAIgPAAQgVAAgPgOgAGuCsIAAhgIA0AAIAAARIgiAAIAAAWIAhAAIAAARIghAAIAAAXIAiAAIAAARgAGLCsIAAhgIASAAIAABggAFBCsIAAhgIASAAIAAAlIAOAAQAQAAAIAIQAIAHAAAOQAAAOgJAIQgIAIgPAAgAFTCbIAOAAQAGAAAEgEQAEgCAAgHQAAgGgEgDQgEgDgGAAIgOAAgAEeCsIAAgoIgjAAIAAAoIgSAAIAAhgIASAAIAAAmIAjAAIAAgmIARAAIAABggACdCsIAAhgIASAAIAAAlIAOAAQAQAAAIAIQAIAHAAAOQAAAOgJAIQgIAIgPAAgACvCbIAPAAQAFAAAFgEQAEgDAAgGQgBgGgDgDQgFgDgFAAIgPAAgACACsIgahIIgbBIIgTAAIAmhgIAPAAIAmBggAAiCsIgJgZIgjAAIgKAZIgTAAIAnhgIAOAAIAoBggAgDCCIAVAAIgLgcgAhDCsIAAhEIgrBEIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAkeCsIAAhgIAzAAIAAARIgiAAIAAAWIAhAAIAAARIghAAIAAAXIAiAAIAAARgAlCCsIAAhPIgjAAIAABPIgSAAIAAhgIBHAAIAABggAisjUIAAgXIhVAAIAAAXIgWAAIAAgsIALAAIAshhIATAAIAsBhIALAAIAAAsgAj0kAIA7AAIgdhDgAEjjrIAAhTIg1BTIgWAAIAAh2IAWAAIAABTIA1hTIAWAAIAAB2gACSjrIAAh2IA7AAIAAAVIglAAIAABhgAA1jrIAAh2IAWAAIAAAtIARAAQASAAALAKQALAKAAARQAAAQgLAKQgMAKgRAAgABLkAIASAAQAIAAAEgEQAFgEAAgHQAAgHgFgEQgEgEgIAAIgSAAgAAJjrIAAgxIgqAAIAAAxIgWAAIAAh2IAWAAIAAAvIAqAAIAAgvIAWAAIAAB2gAiKjrIAAh2IA/AAIAAAVIgpAAIAAAbIAoAAIAAAWIgoAAIAAAbIApAAIAAAVg");
	this.shape_11.setTransform(0,18.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4, new cjs.Rectangle(-58.7,-16.5,118.6,70.9), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUA4IANgcIgrhTIAZAAIAcA7IAag7IAWAAIgyBvg");
	this.shape.setTransform(54.9,7.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBCIAAgVIhPAAIAAAVIgUAAIAAgpIAKAAIAphaIARAAIApBaIAKAAIAAApgAgaAZIA2AAIgcg+g");
	this.shape_1.setTransform(43.5,8.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoApQgSgQABgZQgBgXASgRQAQgRAYAAQAZAAARARQAQARABAXQgBAZgQAQQgQARgaAAQgYAAgQgRgAgagaQgLALAAAPQAAAQALALQALALAPAAQAPAAAMgLQALgLAAgQQAAgPgLgLQgMgLgPAAQgPAAgLALg");
	this.shape_2.setTransform(31.1,7.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA4IAAhvIA3AAIAAAVIgiAAIAABag");
	this.shape_3.setTransform(21.9,7.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAnA4IAAhSIgfBSIgPAAIgehSIAABSIgVAAIAAhvIAcAAIAeBUIAfhUIAcAAIAABvg");
	this.shape_4.setTransform(4.3,7.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpApQgRgQAAgZQAAgXARgRQARgRAYAAQAZAAARARQAQARAAAXQABAZgSAQQgQARgZAAQgYAAgRgRgAgagaQgLAMAAAOQAAAPALAMQALALAPAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgOAAgMALg");
	this.shape_5.setTransform(-8.9,7.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA4IAAhvIAbAAQASACAKAGQAKAIAAAOQAAAHgEAGQgDAEgGAEQAKAEAEAFQAFAHAAAKQAAAQgLAJQgKAJgWAAgAgOAkIANAAQAHAAAFgEQAEgEAAgGQAAgHgEgEQgFgDgHAAIgNAAgAgOgMIAKAAQAFAAAEgDQAEgCAAgGQAAgGgEgDQgEgCgFAAIgKAAg");
	this.shape_6.setTransform(-19.3,7.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgoApQgSgQABgZQgBgXASgRQAQgRAYAAQAZAAARARQARARAAAXQAAAZgRAQQgQARgaAAQgYAAgQgRgAgagaQgLAMAAAOQAAAPALAMQALALAPAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgOAAgMALg");
	this.shape_7.setTransform(-30.2,7.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUA4IAAgvIgoAAIAAAvIgUAAIAAhvIAUAAIAAAtIAoAAIAAgtIAVAAIAABvg");
	this.shape_8.setTransform(-41.6,7.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA4IAAhvIAbAAQASACAKAGQAKAIAAAOQAAAHgEAGQgCAEgHAEQAKAEAEAFQAFAHAAAKQAAAQgLAJQgKAJgWAAgAgOAkIANAAQAHAAAFgEQAEgEAAgGQAAgHgEgEQgFgDgHAAIgNAAgAgOgMIAKAAQAFAAAEgDQAEgCAAgGQAAgGgEgDQgEgCgFAAIgKAAg");
	this.shape_9.setTransform(-54.3,7.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AASFrQgOgPAAgUQAAgVAOgPQAPgPAWAAQAUAAAQAPQAOAPAAAVQAAAUgOAPQgPAOgVAAQgXAAgOgOgAAfEwQgJAJAAAOQAAAOAJAJQAKAKANAAQAOAAAKgKQAJgKAAgNQAAgOgJgJQgJgKgOAAQgPAAgJAKgAi0FrQgOgPAAgUQAAgVAOgPQAPgPAVAAQAWAAAPAPQAOAPAAAVQABAUgQAPQgOAOgWAAQgVAAgPgOgAinEwQgJAJAAAOQAAAOAJAJQAKAKANAAQAOAAAKgKQAJgJAAgOQAAgOgJgJQgKgKgOAAQgOAAgJAKgAE4F3IAMgZIglhIIAWAAIAZA0IAWg0IATAAIgrBhgAEDF3IAAgoIgjAAIAAAoIgSAAIAAhhIASAAIAAAoIAjAAIAAgoIASAAIAABhgACqF3IAAgoIgiAAIAAAoIgSAAIAAhhIASAAIAAAoIAiAAIAAgoIASAAIAABhgAgQF3IgahIIgaBIIgUAAIAmhhIAQAAIAlBhgAjWF3IgegrIAAArIgSAAIAAhhIASAAIAAAqIAegqIAVAAIgkAwIAkAxgAlvF3IAAhhIAXAAQARABAIAGQAJAIAAALQAAAHgDAEQgDAEgFADQAHACAFAHQAEAHAAAIQAAAOgKAHQgJAIgTAAgAldFlIALAAQAHAAAEgCQAEgDABgGQgBgHgEgCQgDgEgIAAIgLAAgAldE7IAIAAQAGAAADgCQADgCABgFQAAgFgDgCQgFgDgFAAIgIAAgAAvC3QgPgPAAgUQAAgVAPgPQAPgPAVAAQAVAAAPAPQAOAPAAAVQAAAUgOAPQgPAOgVAAQgWAAgOgOgAA7B8QgJAJAAAOQAAAOAJAJQAKAKAOAAQAOAAAJgKQAJgJAAgOQAAgOgJgJQgJgKgOAAQgPAAgJAKgAkgC3QgOgOAAgWQAAgVAOgOQAPgPAVAAQAPAAAMAHQAMAJAFANIgUAAQgFgGgFgDQgHgDgHAAQgOAAgJAKQgJAJAAAOQAAANAJAKQAJAKAOAAQAHAAAGgDQAGgCAEgHIAVAAQgGAOgMAHQgKAIgQAAQgWAAgOgOgAFxDDIgKgZIgkAAIgJAZIgUAAIAohhIAOAAIApBhgAFKCYIAXAAIgMgcgAENDDIgegrIAAArIgSAAIAAhhIASAAIAAAqIAegqIAWAAIgkAwIAkAxgACSDDIAAhhIAXAAQAQABAJAGQAJAHAAAMQgBAHgCAEQgCAEgGADQAHACAFAHQAFAHAAAIQAAANgKAIQgKAIgTAAgACkCxIALAAQAIAAADgCQAFgDAAgGQAAgHgFgCQgDgEgIAAIgLAAgACkCHIAIAAQAHAAADgCQACgCABgFQAAgFgDgCQgEgDgGAAIgIAAgAACDDIAAgoIgjAAIAAAoIgRAAIAAhhIARAAIAAAoIAjAAIAAgoIARAAIAABhgAhQDDIgKgZIgkAAIgJAZIgUAAIAphhIANAAIApBhgAh3CYIAXAAIgMgcgAi6DDIAAhPIgSAAIAAgSIA2AAIAAASIgSAAIAABPgAlqDDIALgZIglhIIAWAAIAaA0IAVg0IAUAAIgsBhgAC6kOQgRgSgBgaQABgaARgRQATgTAaAAQAaAAASATQASARAAAaQAAAagSASQgRARgbAAQgaAAgTgRgADKlXQgLAMAAAQQAAARALANQAMALARABQARgBAMgLQAMgNAAgRQAAgQgMgMQgMgMgRABQgRgBgMAMgAgBkPQgSgRAAgbQAAgaASgRQARgSAaAAQASAAAPAKQAOAJAIARIgZAAQgFgGgIgFQgIgDgJAAQgRgBgLAMQgMANAAAPQAAASAMAMQALALARABQAIgBAIgDQAJgEAEgHIAZAAQgHARgOAJQgOAJgTAAQgaABgRgTgAB7j/IAAhiIgWAAIAAgUIBCAAIAAAUIgWAAIAABigAhgj/IAAh2IBAAAIAAAUIgqAAIAAAcIAoAAIAAAWIgoAAIAAAbIAqAAIAAAVgAiLj/IAAhZIggBZIgTAAIgfhZIAABZIgWAAIAAh2IAeAAIAgBaIAhhaIAeAAIAAB2g");
	this.shape_10.setTransform(0,20.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-57.9,-17.1,118,75.4), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVA3IANgcIgqhSIAZAAIAcA7IAag7IAWAAIgyBug");
	this.shape.setTransform(54.9,-1.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBCIAAgVIhPAAIAAAVIgVAAIAAgpIALAAIAphaIARAAIApBaIALAAIAAApgAgaAZIA2AAIgcg+g");
	this.shape_1.setTransform(43.5,-0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpApQgRgRABgYQAAgWAQgSQARgRAYAAQAZAAARARQARASAAAWQAAAYgRARQgRARgZAAQgXAAgSgRgAgagaQgLAMAAAOQAAAQALALQALALAPAAQAQAAALgLQALgLAAgQQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_2.setTransform(31,-1.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA3IAAhuIA3AAIAAAUIgiAAIAABag");
	this.shape_3.setTransform(21.9,-1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAmA3IAAhSIgdBSIgRAAIgdhSIAABSIgVAAIAAhuIAcAAIAeBUIAfhUIAcAAIAABug");
	this.shape_4.setTransform(4.2,-1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpApQgQgQAAgZQAAgWAQgSQARgRAYAAQAZAAARARQARARAAAXQAAAZgRAQQgSARgYAAQgYAAgRgRgAgagaQgLALAAAPQAAAQALALQAKALAQAAQAQAAALgLQALgLAAgQQAAgPgLgLQgLgLgQAAQgQAAgKALg");
	this.shape_5.setTransform(-8.9,-1.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAaAAQATABAKAHQAJAIAAANQAAAIgDAGQgEAFgFADQAJADAFAGQAFAHAAAKQAAAQgLAJQgLAIgVAAgAgOAjIANAAQAIABAEgEQAFgEgBgGQABgHgFgEQgEgDgIgBIgNAAgAgOgMIAJAAQAGAAAEgDQADgDAAgFQAAgGgDgCQgEgEgGAAIgJAAg");
	this.shape_6.setTransform(-19.3,-1.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgpApQgQgQAAgZQAAgWAQgSQARgRAYAAQAaAAAQARQAQARABAXQgBAZgQAQQgRARgZAAQgYAAgRgRgAgagaQgLALAAAPQAAAQALALQALALAPAAQAQAAALgLQALgMAAgPQAAgOgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_7.setTransform(-30.2,-1.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUA3IAAguIgnAAIAAAuIgVAAIAAhuIAVAAIAAAtIAnAAIAAgtIAVAAIAABug");
	this.shape_8.setTransform(-41.7,-1.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjA3IAAhuIAbAAQASABAKAHQAJAIAAANQAAAIgDAGQgEAFgFADQAJADAFAGQAFAHAAAKQAAAQgLAJQgLAIgVAAgAgOAjIANAAQAIABAEgEQAFgEgBgGQABgHgFgEQgEgDgIgBIgNAAgAgOgMIAJAAQAGAAAEgDQAEgDAAgFQAAgGgEgCQgEgEgGAAIgJAAg");
	this.shape_9.setTransform(-54.3,-1.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AASA7IAAguIgBAAIgeAuIgaAAIAhgrQgPgDgIgJQgJgIAAgPQAAgSALgLQAMgKAVAAIAiAAIAAB1gAgLggQgFAEAAAJQAAAJAFAEQAGAEAKAAIANAAIAAgjIgNAAQgKAAgGAFg");
	this.shape_10.setTransform(21,-19.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AApA7IAAhXIggBXIgRAAIgghXIAABXIgWAAIAAh1IAeAAIAgBZIAhhZIAeAAIAAB1g");
	this.shape_11.setTransform(9.1,-19.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgfA7IAAh1IA/AAIAAAVIgpAAIAAAbIAnAAIAAAVIgnAAIAAAbIApAAIAAAVg");
	this.shape_12.setTransform(-2.4,-19.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AglA7IAAh1IAhAAQATAAAMAKQALAJAAASQAAAQgLAJQgLAKgUAAIgLAAIAAAtgAgPgGIANAAQAIAAAFgEQAFgDAAgIQAAgIgFgEQgEgEgJAAIgNAAg");
	this.shape_13.setTransform(-10.7,-19.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AglA7IAAh1IAcAAQATAAALAIQAKAJAAAOQAAAHgDAHQgDAEgGAFQAJADAFAGQAFAJAAAJQABASgMAJQgMAJgXAAgAgPAmIAOAAQAIAAAEgEQAFgEABgHQgBgHgFgEQgEgEgIAAIgOAAgAgPgNIAKAAQAGAAAEgDQADgDACgGQAAgGgFgDQgEgDgGAAIgKAAg");
	this.shape_14.setTransform(-19.9,-19.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("ABkDXQgOgOAAgVQAAgVAPgPQAOgOAVAAQAPAAAMAHQAMAJAGANIgUAAQgFgGgGgCQgGgDgHAAQgPgBgJAKQgJAKAAANQAAAMAJALQAKAKAOAAQAGAAAGgDQAGgCAFgGIAUAAQgGANgLAIQgLAHgQAAQgVAAgPgPgAotDXQgPgOAAgVQAAgUAPgQQAPgOAVAAQAPAAALAHQAMAJAGANIgUAAQgFgFgGgDQgGgDgHAAQgOgBgKAKQgJAKAAANQAAAOAKAJQAIAKAPAAQAHAAAGgDQAGgCAEgGIAVAAQgGANgMAIQgMAHgPAAQgVAAgOgPgAIrDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAHNDkIgegqIAAAqIgSAAIAAhgIASAAIAAApIAegpIAVAAIgkAvIAkAxgAEbDkIAAhgIASAAIAABPIAeAAIAAhPIARAAIAABPIAeAAIAAhPIASAAIAABggADSDkIAMgYIglhIIAVAAIAaAzIAWgzIATAAIgrBggAAZDkIAAhDIgqBDIgSAAIAAhgIASAAIAABDIAqhDIASAAIAABggAhkDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAjCDkIgegqIAAAqIgSAAIAAhgIASAAIAAApIAegpIAVAAIgkAvIAkAxgAk6DkIAAhgIAaAAQARABAJAHQAJAIAAANQAAAOgJAIQgJAJgRgBIgJAAIAAAlgAkpCuIALAAQAHAAAEgDQAEgDAAgHQAAgFgEgEQgEgDgHAAIgLAAgAleDkIAAhDIgrBDIgSAAIAAhgIASAAIAABDIArhDIASAAIAABggAnIDkIAAhPIgRAAIAAgRIA1AAIAAARIgSAAIAABPgAB+AjQgOgOAAgVQAAgTAOgQQAQgOAVAAQAVAAAPAOQAOAQAAATQAAAVgOAOQgPAPgVAAQgWAAgPgPgACLgWQgJAJAAANQAAAOAJAKQAKAJANAAQAPAAAJgKQAJgJAAgOQAAgNgJgJQgJgKgOABQgPgBgJAKgAhmAjQgOgOAAgVQAAgTAOgQQAQgOAUAAQAQAAALAHQAMAJAGANIgVAAQgFgFgFgDQgGgDgIAAQgOgBgJAKQgJAKAAAMQAAAOAJAJQAJAKAOAAQAHAAAGgDQAGgCAFgGIAUAAQgGANgLAIQgMAHgPAAQgWAAgOgPgAEfAwIAAhCIgrBCIgSAAIAAhfIASAAIAABCIArhCIARAAIAABfgAAsAwIAAhfIAbAAQARABAIAHQAJAIAAANQAAAOgJAHQgIAJgRgBIgJAAIAAAlgAA+gFIAKAAQAIAAADgDQAEgDAAgHQAAgFgEgEQgDgDgIAAIgKAAgAAAAwIAAhOIgSAAIAAgRIA0AAIAAARIgRAAIAABOgAiTAwIAAhfIASAAIAABfgAjcAwIAAhfIARAAIAAAlIAPAAQAOgBAJAJQAJAHAAANQAAANgJAJQgKAIgNAAgAjLAfIAPAAQAGgBAEgDQAEgDAAgGQAAgGgEgDQgEgDgGAAIgPAAgAkqAwIAAhfIA4AAIAAARIgnAAIAAAUIAQAAQAQgBAIAKQAIAIAAALQAAANgJAJQgKAIgNAAgAkZAfIAQAAQAGgBAEgDQAEgDAAgGQAAgFgEgEQgEgDgGAAIgQAAgAD5g5QgGgGgBgIIAPAAQAAADACACQADACADAAQAEAAACgCQACgCABgDIAPAAQgCAIgGAGQgGAEgKAAQgKAAgGgEgAjqiQQgPgNAAgWQAAgUAPgQQAPgOAVAAQAWAAAOAOQAPAPAAAVQAAAVgPAOQgOAPgWAAQgWAAgOgPgAjdjKQgKAJAAAOQAAAOAKAKQAKAJANAAQAOAAAKgKQAJgJAAgOQAAgNgJgKQgKgKgOABQgOgBgJAKgAGJiDIAAhgIASAAIAABggAE/iDIAAhgIASAAIAAAlIAOAAQAPgBAJAJQAIAHAAAOQAAANgJAJQgJAIgOAAgAFRiUIAPAAQAGgBAEgDQAEgDAAgGQgBgGgDgDQgEgDgGAAIgPAAgAEciDIAAhIIgaBIIgPAAIgZhIIAABIIgSAAIAAhgIAYAAIAbBJIAahJIAZAAIAABggACkiDIAAhIIgZBIIgPAAIgahIIAABIIgSAAIAAhgIAYAAIAbBJIAbhJIAYAAIAABggAAziDIgKgZIgkAAIgIAZIgUAAIAnhgIAOAAIAoBggAAMitIAWAAIgLgcgAhNiDIAAhgIAbAAQARABAIAHQAJAIAAANQAAAOgJAIQgIAJgRgBIgJAAIAAAlgAg7i5IAKAAQAIAAADgDQAEgDAAgHQAAgFgEgEQgDgDgIAAIgKAAgAiGiDIAAhgIAwAAIAAARIgfAAIAABPgAk9iDIAAhgIAbAAQARABAJAHQAJAIAAANQAAANgJAJQgJAJgRgBIgJAAIAAAlgAkri5IALAAQAHAAAEgDQADgDABgHQAAgFgEgEQgEgDgHAAIgLAAgAlgiDIAAhPIgjAAIAABPIgSAAIAAhgIBHAAIAABgg");
	this.shape_15.setTransform(0,42.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-57.9,-25.8,118,91.8), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmpCaQgRgSAAgaQAAgaASgSQARgSAbAAQASAAAOAKQAPAJAIARIgZAAQgHgHgHgEQgHgDgJAAQgRAAgMAMQgLALAAARQAAARALALQAMAMARAAQAJAAAHgDQAHgDAFgHIAaAAQgHAPgPAKQgPAKgSAAQgaAAgSgSgAIRCpIAAh3IBAAAIAAAWIgqAAIAAAbIAoAAIAAAVIgoAAIAAAbIAqAAIAAAWgAHmCpIAAh3IAWAAIAAB3gAGLCpIAAh3IAWAAIAAAuIARAAQASAAALAKQALAKAAAQQAAAQgLALQgMAKgRAAgAGhCTIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAFfCpIAAgyIgrAAIAAAyIgWAAIAAh3IAWAAIAAAwIArAAIAAgwIAWAAIAAB3gADBCpIAAh3IAWAAIAAAuIASAAQASAAALAKQAKAKAAAQQAAAQgLALQgLAKgRAAgADXCTIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgACdCpIgghYIghBYIgYAAIAvh3IATAAIAvB3gAAiCpIAAhTIgzBTIgWAAIAAh3IAWAAIAABUIAzhUIAWAAIAAB3gAjHCpIAAh3IAWAAIAABhIAkAAIAAhhIAWAAIAABhIAkAAIAAhhIAWAAIAAB3gAkhCpIAOgeIguhZIAbAAIAfA/IAbg/IAYAAIg1B3gAoFCpIAAhTIg1BTIgWAAIAAh3IAWAAIAABUIA1hUIAWAAIAAB3gAoEhBQgSgSAAgaQAAgZASgTQASgSAaAAQATAAAOAKQAOAJAIARIgZAAQgHgHgGgEQgHgDgKAAQgRAAgMAMQgLALAAARQAAARAMALQAMAMAQAAQAJAAAHgDQAHgDAGgHIAZAAQgHAPgPAKQgOAKgSAAQgaAAgSgSgAGsgyIAAh3IA/AAIAAAWIgpAAIAAAbIAoAAIAAAVIgoAAIAAAbIApAAIAAAWgAGAgyIAAh3IAWAAIAAB3gAElgyIAAh3IAWAAIAAAuIASAAQASAAALAKQAKAKAAAQQAAAQgLALQgLAKgRAAgAE7hIIASAAQAIAAAFgEQAEgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAD6gyIAAgyIgrAAIAAAyIgWAAIAAh3IAWAAIAAAwIArAAIAAgwIAWAAIAAB3gABcgyIAAh3IAWAAIAAAuIARAAQASAAALAKQALAKAAAQQAAAQgLALQgMAKgRAAgAByhIIASAAQAIAAAEgEQAFgDAAgIQAAgGgFgFQgFgEgHAAIgSAAgAA4gyIghhYIgfBYIgYAAIAuh3IATAAIAvB3gAg7gyIgMgfIgrAAIgMAfIgZAAIAyh3IARAAIAyB3gAhqhmIAbAAIgNgjgAjZgyIAAh3IAhAAQAUAAALAKQALAKAAARQAAAQgKALQgLAKgVAAIgLAAIAAAtgAjDh0IANAAQAIAAAFgEQAFgEAAgIQAAgIgFgDQgEgEgJAAIgNAAgAkFgyIAAhTIg1BTIgWAAIAAh3IAWAAIAABUIA1hUIAWAAIAAB3gAmHgyIAAhhIgWAAIAAgWIBCAAIAAAWIgWAAIAABhg");
	this.shape.setTransform(0,6.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AElAwIAAhfIASAAIAABfgADcAwIAAhfIARAAIAAAlIAOAAQAPAAAJAIQAIAHABAOQAAANgKAIQgJAIgOAAgADtAfIAOAAQAHAAAEgEQADgDAAgFQAAgGgDgEQgEgDgHAAIgOAAgAC4AwIAAgoIgjAAIAAAoIgSAAIAAhfIASAAIAAAmIAjAAIAAgmIASAAIAABfgABfAwIAAhDIgrBDIgSAAIAAhfIASAAIAABCIArhCIASAAIAABfgAheAwIAAhfIASAAIAABOIAdAAIAAhOIARAAIAABOIAeAAIAAhOIARAAIAABfgAh7AwIgKgZIgkAAIgKAZIgUAAIAphfIAOAAIAoBfgAijAGIAXAAIgLgbgAjiAwIAAhHIgaBHIgOAAIgahHIAABHIgSAAIAAhfIAYAAIAbBIIAbhIIAYAAIAABfg");
	this.shape_1.setTransform(0,45.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-59.2,-11,118.6,61), null);


(lib.p4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1Ресурс4();
	this.instance.parent = this;
	this.instance.setTransform(-30,-93);

	this.instance_1 = new lib._2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-150,-99.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.p4, new cjs.Rectangle(-150,-99.5,300,199), null);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-99.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1, new cjs.Rectangle(-150,-99.5,300,199), null);


(lib.know = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AgXAtIAAhZIAvAAIAAAQIgeAAIAAAVIAdAAIAAAPIgdAAIAAAVIAeAAIAAAQg");
	this.shape.setTransform(39.9,0.4,0.91,0.91);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00A7E0").s().p("Ag0AtIAAhZIARAAIAABJIAbAAIAAhJIAQAAIAABJIAcAAIAAhJIAQAAIAABZg");
	this.shape_1.setTransform(31.4,0.4,0.91,0.91);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00A7E0").s().p("AgdAtIAAhZIARAAIAAAjIAMAAQAOAAAIAHQAIAGAAANQAAANgJAHQgIAIgNAAgAgMAdIAMAAQAGAAADgDQAEgDAAgGQAAgFgEgDQgDgDgGAAIgMAAg");
	this.shape_2.setTransform(23,0.4,0.91,0.91);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00A7E0").s().p("AAZAtIgZhCIgXBCIgTAAIAkhZIANAAIAkBZg");
	this.shape_3.setTransform(15.5,0.4,0.91,0.91);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00A7E0").s().p("AghAhQgNgNAAgUQAAgSANgOQAOgOATAAQAUAAAOAOQANAOAAASQAAAUgNANQgNAOgVAAQgTAAgOgOgAgVgVQgJAJAAAMQAAANAJAIQAJAKAMgBQAOABAIgKQAJgIAAgNQAAgMgJgJQgIgIgOgBQgMABgJAIg");
	this.shape_4.setTransform(6.9,0.4,0.91,0.91);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00A7E0").s().p("AgeAtIAAhZIA0AAIAAAQIgiAAIAAATIAMAAQAQAAAHAIQAIAGAAAMQAAANgJAHQgIAIgOAAgAgMAdIAMAAQAHAAADgDQADgDABgGQAAgFgDgDQgFgDgGAAIgMAAg");
	this.shape_5.setTransform(-0.8,0.4,0.91,0.91);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00A7E0").s().p("AgdAtIAAhZIARAAIAAAjIAMAAQAOAAAIAHQAIAGAAANQAAANgIAHQgIAIgOAAgAgMAdIAMAAQAGAAAEgDQADgDAAgGQAAgFgDgDQgEgDgGAAIgMAAg");
	this.shape_6.setTransform(-9.9,0.4,0.91,0.91);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00A7E0").s().p("AgHAtIAAhJIgRAAIAAgQIAxAAIAAAQIgRAAIAABJg");
	this.shape_7.setTransform(-15.6,0.4,0.91,0.91);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00A7E0").s().p("AAZAtIgJgXIggAAIgJAXIgSAAIAlhZIANAAIAlBZgAgKAGIAUAAIgKgag");
	this.shape_8.setTransform(-21.5,0.4,0.91,0.91);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7E0").s().p("AAQAtIAAgmIgfAAIAAAmIgRAAIAAhZIARAAIAAAkIAfAAIAAgkIARAAIAABZg");
	this.shape_9.setTransform(-29.3,0.4,0.91,0.91);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00A7E0").s().p("AgVAnQgJgIABgOIARAAQAAAGADADQADAFAGAAQAHAAADgEQAEgDAAgFQAAgGgDgDQgEgDgFAAIgIAAIAAgQIAGAAQAGABACgDQADgDAAgFQAAgFgDgDQgDgCgEAAQgFAAgCACQgDADAAAEIgRAAQAAgLAHgHQAHgHANgBQALAAAIAIQAIAGAAAMQAAAGgEAFQgDAFgGADQAHABAFAGQAEAGAAAIQAAAMgJAIQgJAGgNAAQgNAAgIgHg");
	this.shape_10.setTransform(-36.1,0.3,0.91,0.91);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00A7E0").s().p("AgRAtIALgXIgihCIAUAAIAWAvIAVgvIATAAIgqBZg");
	this.shape_11.setTransform(-42.7,0.4,0.91,0.91);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AolBvIAAjdIRKAAIAADdg");
	this.shape_12.setTransform(-1.9,0.1,0.91,0.91);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.know, new cjs.Rectangle(-51.9,-10,100,20.3), null);


(lib.eko = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAsQgSgSAAgaQAAgZASgSQAQgSAbAAQAaAAATASQARASABAZQAAAZgTATQgSASgaAAQgbAAgQgSgAAJgcQgLAMAAAQQAAARALALQAMAMARAAQARAAALgMQAMgMAAgQQAAgQgMgMQgKgLgSAAQgSAAgLALgAj5AsQgSgSAAgaQAAgZASgSQASgSAbAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgbAAgSgSgAjpgcQgMANAAAPQAAARAMALQALAMASAAQAQAAANgMQALgMAAgQQAAgPgLgNQgMgLgRAAQgSAAgLALgAnMA0QgOgJgHgQIAaAAQAFAHAHADQAIADAKAAQAOAAAKgIQAKgIADgOIg1AAIAAgUIA1AAQgDgPgKgHQgKgHgOAAQgLAAgHADQgJAEgEAHIgaAAQAHgQAPgKQAPgKATAAQAZAAASASQASARAAAaQAAAagSASQgRASgbAAQgSAAgPgKgAGjA7IAAh2IA/AAIAAAWIgpAAIAAAbIAnAAIAAAUIgnAAIAAAbIApAAIAAAWgAFrA7IAAhgIgVAAIAAgWIBCAAIAAAWIgXAAIAABggAEHA7IAAh2IAWAAIAAAuIARAAQATAAAKAKQALAJAAAQQAAAQgLALQgMAKgRAAgAEdAlIARAAQAJAAAEgEQAFgEAAgHQgBgGgEgFQgFgEgIAAIgRAAgADbA7IAAhYIgfBYIgTAAIgfhYIAABYIgWAAIAAh2IAeAAIAgBaIAhhaIAeAAIAAB2gAg9A7IAAgyIgrAAIAAAyIgXAAIAAh2IAXAAIAAAwIArAAIAAgwIAVAAIAAB2gAkjA7Iglg0IAAA0IgWAAIAAh2IAWAAIAAA0IAlg0IAaAAIgtA7IAtA7g");
	this.shape.setTransform(48.3,6.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.eko, new cjs.Rectangle(0,0,96.5,12.4), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AppHWIAAurITTAAIAAOrg");
	mask.setTransform(61.7,47);

	// Слой 1
	this.instance = new lib._1Ресурс3();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ1, new cjs.Rectangle(0,0,123.6,94), null);


// stage content:
(lib._320x100 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A46nuMAx1AAAIAAPdMgx1AAAg");
	this.shape.setTransform(160,50);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(305));

	// Слой 1
	this.instance = new lib.eko();
	this.instance.parent = this;
	this.instance.setTransform(263.9,14.5,0.72,0.72,0,0,0,48.3,6.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(74).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(216).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// t4
	this.instance_1 = new lib.t4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(263.9,37.2,0.72,0.72);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(224).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(66).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// t3
	this.instance_2 = new lib.t3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(263.9,37.5,0.72,0.72,0,0,0,0.1,0.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(149).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(66).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(75));

	// t2
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(263.9,43.8,0.72,0.72,0,0,0,0.1,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(74).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(66).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(150));

	// t1
	this.instance_4 = new lib.t1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(361.1,31.1,0.72,0.72,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:263.9},13,cjs.Ease.get(1)).wait(59).to({alpha:0},7,cjs.Ease.get(1)).to({_off:true},1).wait(225));

	// logo
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AoyBQQgpglAYg2QAVgxBDgcQBLggB6ABQAaAAAZADIAgAEIANADIgSAfQgmgLggAAQg9AAgzASQhEAYgKAwQgHAdAVAaQAbAhA7gDQATAAAkgNQArgPAagUIA9g1IAEgDIAIgEIAMgDIAGgBIBCAAIAVBbIAphaIBJAAIAqBFIAfhFIBCAAIg6B/IhEAAIgshJIghBJIgqAAIAAAAIhOAAIgDgWIhIAAIgYAVIgvAAQg2AThHAAQhnAAgsgogAjAA2IAqgBIgEgjgAF6ByIArgrIgrhgIBBAAIATA0IA1g1IBKAAIiACAQgHAHgEACIgQADgAD2BmIhrAAIA6h/IBsAAQAzAAATAZQAPATgLAZQgLAYgcAPQgjATg4AAIgDAAgADhBGIATAAQA/AAAJgiQAHgegzAAIgTAAg");
	this.shape_1.setTransform(63.5,46.1,0.679,0.68);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(305));

	// snow
	this.instance_5 = new lib.Символ1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(148.5,49.1,1,1,0,0,0,151.5,47);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(305));

	// legal
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AEmAaIAAgKIgGgBIgFgDIgDgEIgBgHIABgEIADgFIAFgDIAGgBIAAgMIAFAAIAAAMIAHABIAFADQACABABAEIABAEIgBAHIgDAEIgFADIgHABIAAAKgAErAMIAFgBIADgCIACgDIAAgFIAAgDIgCgEIgDgCIgFgBgAEfgGQgDAEAAADQAAAFADADQADADAFAAIAAgVQgEAAgEADgACWAaIAAgKIgYAAIAAAIIAAABIgBABIgEAAIAAgOIABAAIACgBIACgBIACgCIABgFIACgPIASAAIAAAXIAGAAIAAANIgBACgACHAAIgDAJIgCADIAOAAIAAgUIgJAAgAjJAaIAAgKIgoAAIAAgcIAFAAIAAAXIAMAAIAAgXIAFAAIAAAXIAMAAIAAgXIAFAAIAAAXIAFAAIAAAPgAlMAaIAAgKIgYAAIAAAIIAAABIgBABIgEAAIAAgOIABAAIACgBIACgBIACgCIABgFIACgPIASAAIAAAXIAGAAIAAANIgBACgAlbAAIgDAJIgCADIAOAAIAAgUIgJAAgAneAaIAAgmIAEAAIABABIAAADIAFgDIAFgBIAFABIADACIACAFIABAFIgBAGIgCAFIgEADIgGABIgEAAIgDgDIAAANgAnVgHQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAABIAAANIADACIADABQAEAAACgDQACgCAAgGIAAgDIgBgEIgDgCIgDgBQAAABgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAgADcAXIAAgBIABgCIABgBIABgCIABgBIgBAAIgBAAIgBgBIgBgDIABgCIACgBIACAAIABABIABABIAAAFIgCACIgBADIgDADgABhAXIgBAAIAAgBIABgCIABgBIABgCIABgBIgBAAIgBAAIgBgBIgBgDIABgCIACgBIACAAIABABIABADIAAADIgBACIgCADIgCADgADDAQIgFgDIgDgEIgBgEIACgGQADgDADgBIgFgDQgBgCAAgEIABgEIACgDIAEgDIAFgBIAFABIAEADIADADIABAEQAAAEgCACIgFADQADABADADIACAGIgBAEIgDAEQgCACgCABIgGABgADCAAIgBABIgBAEIABADIABACIADABIADABIAEgBIACgBIACgCIABgDIgBgEIgCgBIgDgCIgGAAgADFgUIgCACIgBACIgBACIABADIABACIACACIADAAIAEAAIACgCIABgCIAAgFIgBgCIgDgCIgDAAgAHyAQIAAgFIAJAAIAAgcIgHAGIgBABIgBAAIgDgEIANgKIAEAAIAAAjIAIAAIAAAFgAHUAPIgEgEQgDgCAAgEQgCgEAAgEQAAgGACgEQAAgDADgDIAEgFIAGgBIAGABQADACACADIADAGIABAKIgBAIQgBAEgCACQgBACgEACIgGABIgGgBgAHXgTIgDACIgCAGIgBAIIABAGIACAFIADADIADAAIAEAAIADgDIACgFIABgGIgBgIIgCgGIgDgCIgEgBgAGzAPIgEgEQgDgCAAgEQgCgEAAgEQAAgGACgEQAAgDADgDIAEgFIAGgBIAGABIAFAFIADAGIABAKIgBAIQgBAEgCACQgBACgEACIgGABIgGgBgAG2gTIgDACIgCAGIgBAIIABAGIACAFIADADIADAAIAEAAIADgDIACgFIABgGIgBgIIgCgGIgDgCIgEgBgAGPAQIAAgFIAIAAIAAgaIABgCIgIAGIAAABIgBAAIgBgBIgCgDIAMgKIAFAAIAAAjIAIAAIAAAFgAFtAQIgFgBIgEgDIgDgEIgBgHIABgEIADgGIAEgCIAGgBIAFABIAFACIgCACIgBABIgBgBIgBgBIgFgBIgDABIgDACIgCAEIAAADIAAAFIACADIADACIADABIADgBIACgBIABgBIABAAIABAAIACACIgCADIgGACgAFVAQIAAgVIgCADIgNARIgBABIgBAAIgDAAIAAgcIAFAAIAAAUIABgBIABgBIABgDIAMgNIABgBIABgBIADAAIAAAcgAD/APIgFgDQgCgCAAgCIgBgHIABgFIACgFIAFgCIAGgBIAFABIAFACIACAFIABAFIgBAHQAAACgCACIgFADIgFABIgGgBgAD+gGQgCADAAAEQAAAGACACQADADAEAAQAEAAACgDQACgCAAgGQAAgEgCgDQgCgDgEAAQgEAAgDADgAChAQIgBgBIgBgBIAAgCIAAgBIABgBIABgBIADAAIABABIABABIAAABIAAACIgBABIgBABgABUAQIAAgVIgCADIgNARIgBABIgBAAIgDAAIAAgcIAFAAIAAAUIABgBIABgBIANgQIABgBIABgBIADAAIAAAcgAAIAQIAAgCIABgBIAAgCIATgSIABgCIABgEIgBgDIgCgCIgCgBIgDgBIgCABIgDABIgBABIgBADIgBACIgCAAIgDgBIACgFIADgDIAEgDIAFgBIAFABIAEADIACADIABAFIgCAIIgRAQIAFgBIANAAIABABIABABIAAAEgAgRAQIAAgVIgBADIgCACIgLAPIgBABIgBAAIgEAAIAAgcIAGAAIAAAUIABgBIAAgBIACgDIALgNIABgBIABgBIADAAIAAAcgAgyAQIAAgVIgBADIgNARIgBABIgBAAIgDAAIAAgcIAFAAIAAAUIABgBIAAgBIANgQIABgBIABgBIAEAAIAAAcgAhOAQIgCAAIgHgLIgBgCIgDAAIgDAAIAAANIgFAAIAAgcIAFAAIAAAMIADAAIACAAIABgBIAGgJIABgBIACgBIAEAAIgHALIgCABIgCAAIADACIABACIAIAMgAhzAQIgFgBIgEgDIgDgEIgBgHIABgEIACgGIAFgCIAGgBIAFABIAEACIgBACIgBABIgBgBIgCgBIgBAAIgDgBIgEABIgCACIgCAEIgBADIABAFQAAABAAAAQAAABABAAQAAAAAAABQAAAAABAAIACACIAEABIADgBIACgBIABgBIABAAIABAAIACACIgDADIgFACgAiMAQIAAgOIgNAAIAAAOIgGAAIAAgcIAGAAIAAAMIANAAIAAgMIAGAAIAAAcgAisAQIAAgVIgBADIgNARIgBABIgBAAIgEAAIAAgcIAGAAIAAAUIABgBIAAgBIACgDIALgNIABgBIABgBIAEAAIAAAcgAkLAPQgDgBgBgCQgCgCgBgCIgBgHIABgFIADgFQABgBADgBIAGgBIAGABIAEACIADAFIABAFIgBAHQgBACgCACIgEADIgGABIgGgBgAkLgGQgCADAAAEQAAAGACACQACADAEAAQAEAAACgDQACgCAAgGQAAgEgCgDQgCgDgEAAQgEAAgCADgAkzAQIAAgoIANAAIAHABIAEADIADADIABAGIgBAFIgDAEIgFACIgGAAIgHAAIAAAQgAktgDIAHAAIAEAAIADgDIACgCIAAgDIAAgEIgCgDIgDgBIgEAAIgHAAgAl6AQIgFgCIgDgDIACgCIABAAIABAAIABABIADABIACABIADgBIACgBIACgBIAAgCQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAgBgBIgFgBIgDAAIAAgCIADAAQADAAACgBQAAgBABAAQAAAAAAgBQAAAAABgBQAAAAAAgBIgBgBIgBgBIgCgBIgDgBIgEABIgCABIgBABIgBgBIgBgCIAEgCIAGgBIAEAAIAEACIACACIAAADIAAACIgBACIgBABIgDAAIAFADIABAFIgBADIgCADIgEACIgEAAgAmRAQIgGgBIgEgDQgCgCgBgCIgBgIIABgEIADgFIAEgCIAGgBIAEABIAEACIADAEIABAFIgBABIgBAAIgTAAIABAFIACADIADACIADABIAEgBIAFgCIABAAIABACIgCADIgDABIgDABgAmXgHQgCADAAADIAPAAIgBgDIgBgDIgCgBIgDgBQgEAAgCACgAm3APIgFgDQgCgCAAgCIgBgHIABgFIACgFIAFgCIAGgBIAFABIAFACIACAFIABAFIgBAHQAAACgCACIgFADIgFABIgGgBgAm4gGQgCADAAAEQAAAGACACQADADAEAAQAEAAACgDQACgCAAgGQAAgEgCgDQgCgDgEAAQgEAAgDADgAntAQIAAgjIgUAAIAAAjIgGAAIAAgoIAgAAIAAAogAAqABIAAgDIAPAAIAAADgABJgRIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIgBgDIABgBIABAAIADAAIAAACIABACIABABIACAAIACAAIABgBIABgEIADAAIABAAIAAABIAAADIgCACIgDABIgDABgAgbgRIgDgBIgCgCIAAgDIAAgBIABAAIADAAIAAACIABACIABABIACAAIACAAIACgBIAAgCIAAgCIAEAAIAAAAIABABIgBADIgBACIgDABIgEABg");
	this.shape_2.setTransform(57.9,86.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ADAAUIgEgCIgDgDIgCgFIADgBQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIABABIACAEIADACIADAAIAEAAIADgCIABgDIABgCIgBgDIgBgCIgDgCIgGgBIAAgCIAFgBIADgBIABgDIABgCIgBgDQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIgCgBIgDAAIgDAAIgCABIgCACIgBADIgBABIgBAAIgDAAIABgFIADgEIAEgCIAFgBIAFABIAEACIACADIABAFIAAADIgCADIgCACIgDABIAGACIACAHQAAADgBACIgDAEIgEACIgGABgACfAVIgDgBIgDgCIgCgBIACgDIABgBIACABIABABIADABIADAAIAEAAIADgCIABgDIABgEIgBgEIgBgCIgDgBIgEAAIgGAAIgEAAIAEgTIATAAIAAACIgBACIgCABIgNAAIgBAKIAFgBIAGABIAEADIADADIAAAFIgBAGIgDAEIgFADIgFABgABdAUIgFgEQgDgEAAgDIgBgJIABgIQAAgDADgEIAFgEIAFgBIAGABIAFAEIADAHIABAIIgBAJIgDAHIgFAEIgGABgABfgPIgDADIgCAFIgBAHIABAIIACAFIADADIADAAIAEAAIADgDIACgFIABgIIgBgHIgCgFIgDgDIgEAAgAAaAUIgEgEQgCgCgBgFQgCgDAAgGQAAgEACgEQABgFACgCIAEgEIAGgBIAGABQAEADABABIADAHIABAIIgBAJIgDAHQgBABgEADIgGABgAAdgPIgDADIgCAFIgBAHIABAIIACAFIADADIADAAIAEAAIADgDIACgFIABgIIgBgHIgCgFIgDgDIgEAAgAgFAUIgFgDIgCgEIgBgGIABgGIAEgFIAJgOIABgBIAHAAIgMAPIgBABIAAABIADgBIACgBIAFABIAEACIACADIABAGIgBAFIgCAEIgFADIgFABIgFgBgAgDAAIgDACIgCADIAAADIAAADIACADIADACIADAAIADAAIADgCIABgDIABgDIgBgEIgBgCIgDgCIgDAAgAirAUIgFgEQgCgCgBgFIgBgJIABgIQABgFACgCIAFgEIAGgBIAGABQADACABACIAEAHIABAIIgBAJIgEAHQgBACgDACIgGABgAipgPIgDADIgCAFIAAAHIAAAIIACAFIADADIAEAAIADAAIADgDIACgFIABgIIgBgHIgCgFIgDgDIgDAAgACIAUIAAgKIgTAAIgBgBIAAgDIATgZIAFAAIAAAZIAGAAIAAAEIgGAAIAAAKgAB5AGIAPAAIAAgTgAA4AUIAQggIACgCIgVAAIgBgBIAAgBIAAgDIAcAAIAAAEIgSAiIgBABIgCAAgAgqAUIAMgQIACgDIgDACIgEABIgEgBIgEgCIgDgDIAAgFIABgFIACgEIAFgDIAFgBIAGABIAEADIACAEIABAFIgBAHIgBACIgMARIgBABgAgkgPIgDACIgBACIgBAEQAAADACADQACABAEAAIADAAIADgCIACgCIAAgDIgBgEIgBgCIgDgCIgDAAgAhMAUIATgiIgVAAIgBgBIAAgEIAbAAIAAAEIgRAiIgBABIgCAAgAhtAUIATgiIgVAAIgBgBIAAgEIAbAAIAAAEIgRAiIgBABIgCAAgAiAAUIAAgKIgTAAIAAgBIgBgDIAUgZIAFAAIAAAZIAGAAIAAAEIgGAAIAAAKgAiOAGIAOAAIAAgTgAjQAUIAAgEIAJAAIAAgcIgHAGIgBAAIAAAAIgBAAIAAgBIgCgCIAMgLIAEAAIAAAkIAIAAIAAAEg");
	this.shape_3.setTransform(92.9,93.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ACDAVIgDgBIgFgEIACgCIABgBIACAAIABABIADABIADABIAEgBIADgCIACgCIAAgFIAAgCIgCgDIgDgBIgEgBIgGABIgDgBIADgTIATAAIAAACIAAADIgDABIgMAAIgCAKIAGgBIAFABIAEACIADAEIABAEIgBAHIgEAEIgEADIgGABgAghAVIgDgBIgFgEIACgCIABgBIABAAIAFACIADABIAEgBIACgCIACgCIABgFIgBgCIgBgDIgDgBIgEgBIgGABIgEgBIAEgTIATAAIAAACIgBADIgCABIgNAAIgCAKIAGgBIAGABIAEACQAAABAAAAQABAAAAABQAAAAABAAQAAABAAABIABAEIgBAHIgDAEIgFADIgFABgAE3AVIAAgTIgVAAIAAATIgGAAIAAgpIAGAAIAAASIAVAAIAAgSIAGAAIAAApgAD5AVIAAgpIANAAIAGABIAFADIADAEIABAFIgBAFIgDAEIgFACIgGABIgHAAIAAAQgAD/ABIAHAAIAEgBIADgBIABgCIABgEIAAgEIgCgCIgDgBIgEgBIgHAAgADbAVIAAgpIAYAAIAAAFIgSAAIAAAkgAC2ATIgGgEQgDgDgBgEIgCgIQAAgDACgEQACgFACgCQADgDADgCQAEgBAFAAQAEAAAEABQAEACACADQACABACAGQACAEAAADIgCAIQgBAEgDADIgGAEQgEABgEABQgFgBgEgBgAC5gOIgFADIgDAFIgBAGIABAGIADAGIAFACIAGABIAGgBIAEgCIADgGIABgGIgBgGIgDgFIgEgDIgGgBgABeAVIAAgFIAJAAIAAgaIAAgCIgHAGIgBAAIAAAAIgBAAIgBgBIgBgCIAMgLIAEAAIAAAkIAIAAIAAAFgABBAUIgFgFQgCgCgBgEIgBgJIABgJIADgGIAFgEIAGgBIAGABIAEAEQADADAAADQACAFAAAEQAAAFgCAEQAAAEgDACIgEAFIgGABIgGgBgABDgOIgDACIgCAFIgBAHIABAHIACAGIADACIAEABIADgBIADgCIACgGIABgHIgBgHIgCgFIgDgCIgDgBgAAYAVIAAgEIABgBIAQgQIACgCIABgDIABgEIgBgDIgBgBIgDgCIgCAAIgDAAIgCABIgCACIgBACIgBACIgCAAIgDgBIACgEQAAgBABAAQAAgBAAAAQABgBAAAAQABgBAAAAIAEgDIAFAAIAFAAIAEADIACAEIABAEIAAAFIgCADIgDADIgDADIgLALIAFgBIANAAIACAAIAAACIAAAEgAgEAVIAAgFIAIAAIAAgcIgGAGIgBAAIgBAAIgBgBIgBgCIALgLIAEAAIAAAkIAIAAIAAAFgAg4AVIAAgLIgTAAIgBgCIAAgDIATgZIAFAAIAAAZIAGAAIAAAFIgGAAIAAALgAhHAFIAPAAIAAgSgAhjAUIgFgFQgDgCAAgEQgCgEAAgFQAAgEACgFQAAgDADgDIAFgEIAFgBIAGABQADACACACIADAGIABAJIgBAJQgBAEgCACQgBADgEACIgGABIgFgBgAhhgOIgDACIgCAFIgBAHIABAHIACAGIADACIADABIAEgBIADgCIACgGIABgHIgBgHIgCgFIgDgCIgEgBgAiJAVIARghIACgCIgVAAIgBgBIAAgBIAAgEIAcAAIAAADIgBACIgRAiIgBABIgCABgAiqAVIARghIACgCIgVAAIgBgBIAAgBIAAgEIAcAAIAAADIgBACIgRAiIgBABIgCABgAjKAVIAAgTIgVAAIAAATIgGAAIAAgpIAGAAIAAASIAVAAIAAgSIAGAAIAAApgAj1AVIAAgTIgWAAIAAATIgGAAIAAgpIAGAAIAAASIAWAAIAAgSIAGAAIAAApgAkhAVIAAghIgCAEIgSAbIgDACIgEAAIAAgpIAFAAIAAAhIACgEIAUgcIACgBIAEAAIAAApg");
	this.shape_4.setTransform(37.4,93.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AjMAZIAAgJIggAAIAAAIIgBABIgBAAIgEAAIAAgOIAEAAIACgBIABgDIADgKIACgVIAYAAIAAAjIAHAAIAAANIgBABIAAAAgAjjABIgCAGIgCAEIAUAAIAAgfIgOAAgAIUAWIgBAAIAAAAIABgCIACgBIABgCIAAgBIAAAAIgCgBIgBAAIgBgDIABgCIADgBIABAAIACABIAAACIAAADIgBAEIgFAEgAD9AWIAAAAIAAAAIAAgBIACgBIAAgBIABgCIABgBIgCgBIgBAAIgBgCIAAgBIABgCIADgBIABAAIABABIABADIgBACIAAAEIgCACIgCACgAH7AQIgDgCIgCgCIgBgEIABgDIADgCIAGgCIAIgBIAAgCIgBgEQgBgBAAAAQgBgBAAAAQgBAAAAAAQgBgBgBAAIgDABIgBABIgCABIgCABIgBAAIAAgBIgBgCIAFgEIAGgBIAFABIADACIACAEIABAEIAAASIgDAAIgBgBIgBgBIgBgCIgBACIgGACIgCAAgAIBAEIgDABIgCABIgBACIAAACIABACIADABIAFgBIACgBIABgDIAAgFgACBAQIgEgBIgEgDIACgCIABgBIABAAIAEACIAEABIADgBIADgCIACgDIAAgEIAAgCIgBgDIgEgBIgDgBIgHABIgDgBIADgTIATAAIAAACIAAACIgDABIgMAAIgCAKIAGgBIAGABIADADIADAEIABAEIgBAGIgEAFIgEACIgGABgAh+AOIgFgDIgFgHQgBgEAAgEQAAgEABgEQACgFADgCQADgDADgBIAIgBQAEAAAEABIAGADIgCAEIgBAAIgBAAIgFgDIgFgBIgFABIgFAEIgDAEIgBAHQAAAEACACIACAFIAFADIAFABIAEAAIACAAIACgCIACgCIABAAIAAAAIAEADQgDADgEABQgFACgEAAQgEAAgEgCgAHbAQIAAgcIALAAIAFAAIADACIABACIABADIAAABIgBACIgCACIgCABQADABABABQABAAAAABQABAAAAABQAAAAAAABQABABAAAAIgCAEIgCACIgDACIgFABgAHhAMIAFAAQABAAABAAQABAAAAAAQABgBAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBQAAAAABgBIgBgCIgBgBIgBgBIgJAAgAHhAAIAFAAIACAAIACgBIABgCIABgBIgBgCIgBgBIgBgBIgDgBIgFAAgAHTAQIgCgBIgHgKIgCgBIgCgBIgDAAIAAANIgFAAIAAgcIAFAAIAAAMIADAAIACAAIABgCIAGgJIABgBIABAAIAFAAIgHALIgCABIgCABIADABIABACIAIAMgAGtAQIgFgBIgEgCIgCgGIgBgFIABgGIACgFIAEgDIAGgBIAGABIAEADIgBACIgBABIgBAAIgCgBIgCgBIgDgBIgDACIgDACIgCADIAAAEIAAAEIACADIADADIADAAIADAAIADgBIABgBIABgBIABABIABACIgCACIgGACgAGJAPQgDAAgCgDIgDgFIgBgFIABgGIADgFQACgCADgBIAFgBIAGABIAFADIACAFIABAGIgBAFQgBADgBACIgFADIgGABIgFgBgAGIgFQgCACAAAFQAAAFACACQACADAEAAQAEAAACgDQACgDAAgEQAAgEgCgDQgCgDgEgBQgEABgCADgAF0AQIAAgeIAAgBIgOAXIgBACIgBAAIgBAAIgCgCIgOgXIAAAfIgFAAIAAgoIAFAAIABABIAQAbIAAgCIABgBIANgYIACgBIAFAAIAAAogAEyAQIgBgBIgBgBIAAgBIAAgCIABgBIABgBIADAAIACABIAAABIABACIgBABIAAABIgCABgAEZAQIAAgcIATAAIAAAEIgOAAIAAAYgADgAQIAPgTIgEACIgEABIgEgBIgEgCIgCgDIgBgGIABgEIACgFQACgCADAAIAFgBIAGABIAEACIADAFIABAEIgBAEIgDAGIgLAQIgBABIgCABgADmgUIgCACIgDADIAAADQAAADACADQACACAEAAIAEAAIACgCQAAgBABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIABgDIgBgDIgBgDIgCgCIgEAAgAC/AQIAAgEIAIAAIAAgdIgGAGIgBAAIgBAAIgBgBIgCgBIANgLIAEAAIAAAkIAIAAIAAAEgACrAQIAAgLIgTAAIAAgBIgBgDIAUgZIAFAAIAAAZIAGAAIAAAEIgGAAIAAALgACdABIAOAAIAAgTgABbAQIAAgEIAJAAIAAgdIgGAGIgBAAIgBAAIgBAAIgBgBIgBgBIANgLIADAAIAAAkIAJAAIAAAEgAA7AQIAAgEIAIAAIAAgaIABgDIgIAGIAAAAIgBAAIgBgBIgCgBIAMgLIAEAAIAAAkIAIAAIAAAEgAAEAQIgCgCIAAgDIACgCIADAAIACACIAAADIgCACgAgaAQIAAgoIAZAAIAAAEIgTAAIAAAkgAgnAQIgCgCIAAgBIAAgCIACgCIADAAIACACIAAADIgCACgAg3AQIAAgSIgWAAIAAASIgGAAIAAgoIAGAAIAAASIAWAAIAAgSIAGAAIAAAogAhgAQIgCgBIAAgBIgBgBIABgCIAAgBIACgBIADAAIABABIAAABIABACIgBABIAAABIgBABgAilAQIAAgeIABgDIgBADIgUAcIgCABIgBABIgEAAIAAgoIAFAAIAAAeIAAADIADgEIATgcIACgBIAEAAIAAAogAj9AQIAAgSIgWAAIAAASIgGAAIAAgoIAGAAIAAASIAWAAIAAgSIAGAAIAAAogAkiAQIgCgBIgFgKIgSAAIgDAJIgBABIgBABIgFAAIARgoIAGAAIAQAogAkzgOIgGAPIAPAAIgGgPIgBgCIgBgDgAlLAQIgBgBIgMgPIgBgCIgCAAIgFAAIAAASIgGAAIAAgoIAGAAIAAASIAGAAIACgDIAKgNIABgBIACgBIAFAAIgMARQgBAAAAAAQAAABgBAAQAAABgBAAQAAAAgBABIACAAIAPAUgAmyAOIgGgDIgEgHIgBgIQAAgEABgEIAEgHQADgDADgBQAEgBAFAAQAFAAADABQAEABADADIADAHQACAEAAAEIgCAIIgDAHIgHADQgDACgFAAQgFAAgEgCgAmvgTIgEAEQgCABgCADIgBAHIABAGQABACADADQABACADABIAGABIAGgBQACgBACgCQADgDAAgCIABgGIgBgHQgBgDgCgBQgBgCgDgCIgGgBgAnfAOIgHgDQgCgDgBgEIgCgIQAAgEACgEQABgFACgCQACgCAFgCIAIgBQAFAAAEABQADABADADIAEAHQACAEgBAEIgBAIIgEAHIgGADQgEACgFAAIgIgCgAndgTIgEAEIgDAEIgBAHIABAGIADAFIAEADIAGABIAGgBIAEgDIADgFIABgGIgBgHIgDgEIgEgEIgGgBgAoNAOIgGgDQgDgEgBgDIgCgIQAAgEACgEQABgFADgCQADgDADgBQAEgBAFAAQAEAAAEABQAEACACACQACACACAFQABAEAAAEIgBAIQgCAEgCADIgGADQgEACgEAAQgFAAgEgCgAoLgTIgEAEIgDAEIgBAHIABAGIADAFIAEADIAHABIAFgBIAFgDIACgFIABgGIgBgHIgCgEIgFgEIgFgBgAAZAMIgBgBIAAgCIAFgHIABgBIAAAAIgBgBIgFgGIAAgCIABgBIACgBIAHALIAAAAIgHALgAAQAMIAAgBIAAgCIAFgHIABgBIgBAAIAAgBIgFgGIAAgCIAAgBIACgBIAHALIAAAAIgHALgAl5ABIAAAAIAHgLIACABIABABIAAACIgEAGIgBABIABABIAEAHIAAACIgBABIgCAAgAmBABIAAAAIAHgLIACABIAAABIAAACIgEAGIgBABIABABIAEAHIAAACIAAABIgCAAg");
	this.shape_5.setTransform(59.7,79.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(305));

	// know
	this.instance_6 = new lib.know();
	this.instance_6.parent = this;
	this.instance_6.setTransform(264,89,0.7,0.7);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(237).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(53).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// p4
	this.instance_7 = new lib.p4();
	this.instance_7.parent = this;
	this.instance_7.setTransform(202.1,62.6,0.59,0.59,0,0,0,0.1,0.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(225).to({_off:false},0).to({alpha:1},7,cjs.Ease.get(1)).wait(65).to({alpha:0},7,cjs.Ease.get(1)).wait(1));

	// p1
	this.instance_8 = new lib.p1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(202.1,62.6,0.59,0.59,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(305));

	// fg
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2191CC").s().p("A3fEMIAAoXMAu/AAAIAAIXg");
	this.shape_6.setTransform(159.7,49.8,1.062,1.856);

	this.timeline.addTween(cjs.Tween.get(this.shape_6).wait(305));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(156.4,49.5,407.4,121.8);
// library properties:
lib.properties = {
	width: 320,
	height: 100,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/320x100_atlas_.png", id:"320x100_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;