(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [
		{name:"300x600_atlas_P_", frames: [[0,0,257,35],[0,64,215,20],[0,37,215,25]]},
		{name:"300x600_atlas_NP_", frames: [[604,0,300,600],[302,0,300,600],[0,0,300,600]]}
];


// symbols:



(lib._110 = function() {
	this.spriteSheet = ss["300x600_atlas_P_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bg = function() {
	this.spriteSheet = ss["300x600_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bg2 = function() {
	this.spriteSheet = ss["300x600_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.bg3 = function() {
	this.spriteSheet = ss["300x600_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.qwr = function() {
	this.spriteSheet = ss["300x600_atlas_P_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.shans = function() {
	this.spriteSheet = ss["300x600_atlas_P_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.xcv = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAcBVIAAiCIAAAAQgDAPgDAHIgqBsIgWAAIAAiJIAPAAIAAB/QADgMADgHIAqhsIAWAAIAACJgAgShCQgHgGAAgMIAHAAQAEANAOAAQAOAAACgNIAIAAQAAAYgZAAQgKAAgHgGg");
	this.shape.setTransform(38.2,0,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgBFIgLgoIgqAAIgLAoIgQAAIAniJIATAAIAnCJgAgSAPIAkAAIgShIIAAAAg");
	this.shape_1.setTransform(25.4,1.9,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnBFIAAiJIAmAAQApAAAAAnQAAAngsAAIgUAAIAAA7gAgYgCIAPAAQARAAAHgFQAJgGAAgQQAAgOgIgGQgHgFgNAAIgUAAg");
	this.shape_2.setTransform(13.3,1.9,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfBFIAAiJIBAAAIAAAOIgxAAIAAB7g");
	this.shape_3.setTransform(2.8,1.9,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAcBFIAAiCQgDAPgDAHIgqBsIgWAAIAAiJIAPAAIAAB/IAAAAQADgMADgHIAqhsIAWAAIAACJg");
	this.shape_4.setTransform(-9.4,1.9,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAPAAIAAA6IASAAQAsAAAAAoQAAAngoAAgAgpA3IASAAQAOAAAIgFQAGgGAAgOQAAgQgIgGQgIgFgQAAIgOAAg");
	this.shape_5.setTransform(-24.5,1.9,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmBFIAAiJIAkAAQAlAAAAAiQAAAZgUAFIAAABQAKABAHAIQAHAJAAAOQAAAognAAgAgXA3IAXAAQAXAAAAgaQAAgagYAAIgWAAgAgXgKIATAAQALAAAGgFQAGgFAAgNQAAgVgVAAIgVAAg");
	this.shape_6.setTransform(-38.6,1.9,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.xcv, new cjs.Rectangle(-43.1,-9.9,86.4,19.9), null);


(lib.www = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAbBhIAAhJQAAgsAFgXIg1CMIgoAAIAAjBIAiAAIAABJQAAAugEAVIAAAAIA1iMIAoAAIAADBg");
	this.shape.setTransform(84,-21.2,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBhIAAhJQAAgsAFgXIg1CMIgoAAIAAjBIAjAAIAABJQAAAugFAVIA1iMIAoAAIAADBg");
	this.shape_1.setTransform(66.3,-21.2,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAoB0IAAgnIhQAAIAAAnIgjAAIAAhEIAMAAQAKgXADgUQAEgWABgmIAAg8IBtAAIAACjIALAAIAABEgAgJgqQAAAggFAUQgEASgIAUIA1AAIAAiGIgkAAg");
	this.shape_2.setTransform(47.6,-18.9,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAYBhIAAhaIgvAAIAABaIglAAIAAjBIAlAAIAABLIAvAAIAAhLIAlAAIAADBg");
	this.shape_3.setTransform(29,-21.2,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAfBhIgJgzIgpAAIgLAzIgoAAIAxjBIAxAAIArDBgAgOASIAfAAIgPhag");
	this.shape_4.setTransform(11.7,-21.2,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhFBgIAAgbQAEABAIAAQAJAAADgMQADgOAAgxIAAhcIBwAAIAADAIglAAIAAijIgmAAIAABJQAAAxgKAWQgJAWgWAAQgOAAgJgCg");
	this.shape_5.setTransform(-6.8,-21,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAYBhIAAijIgvAAIAACjIglAAIAAjBIB5AAIAADBg");
	this.shape_6.setTransform(-24.2,-21.2,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAfBhIgJgzIgpAAIgLAzIgoAAIAxjBIAxAAIArDBgAgOASIAfAAIgPhag");
	this.shape_7.setTransform(-41.5,-21.2,1.176,1.176);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhFBgIAAgbQAEABAIAAQAJAAADgMQAEgOgBgxIAAhcIBwAAIAADAIglAAIAAijIgmAAIAABJQAAAxgKAWQgJAWgWAAQgOAAgJgCg");
	this.shape_8.setTransform(-60,-21,1.176,1.176);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag6BhIAAjBIBCAAQAZAAAMAPQALAMAAAUQAAAPgGAMQgIAOgMACQAdALAAAiQAAAbgLAPQgLAQgWAAgAgVBFIAWAAQAUAAAAgeQAAgegUAAIgWAAgAgVgRIATAAQAWAAgBgbQAAgYgUAAIgUAAg");
	this.shape_9.setTransform(-84.3,-21.2,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.www, new cjs.Rectangle(-91.2,-32.6,182.5,27.4), null);


(lib.wrq = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg3();
	this.instance.parent = this;
	this.instance.setTransform(-120,-200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.wrq, new cjs.Rectangle(-120,-200,300,600), null);


(lib.wqwqw = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.shans();
	this.instance.parent = this;
	this.instance.setTransform(-107.5,-12.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.wqwqw, new cjs.Rectangle(-107.5,-12.5,215,25), null);


(lib.wq = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAcBFIAAiCIAAAAQgDAPgDAHIgqBsIgWAAIAAiJIAPAAIAAB/IAAAAIAGgTIAqhsIAWAAIAACJg");
	this.shape.setTransform(43.9,-0.1,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIABiCIgBAAIgiCCIgRAAIghiCIABCCIgPAAIAAiJIAbAAIAbBqQABAFABAQIADgVIAchqIAbAAIAACJg");
	this.shape_1.setTransform(28.8,-0.1,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBFIAAiCIAAAAQgCANgEAJIgpBsIgXAAIAAiJIAQAAIgBB/IABAAQACgMADgHIAqhsIAWAAIAACJg");
	this.shape_2.setTransform(13.6,-0.1,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBFIAAiJIAQAAIAAB7IAqAAIAAh7IAPAAIAAB7IArAAIAAh7IAPAAIAACJg");
	this.shape_3.setTransform(-2.6,-0.1,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAYBFIAAhDQgMABgNAAQgTAAgIgGQgKgJAAgTIAAglIAPAAIAAAjQAAAOAFAFQAFAEAOAAQAQAAAHgBIAAg5IAPAAIAACJg");
	this.shape_4.setTransform(-18.3,-0.1,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgbBFIAAgOQADACAHAAQAIAAADgNIgohxIAQAAIAgBeIAdheIAQAAIgmBxQgFAPgFAGQgFAFgJAAQgJAAgDgBg");
	this.shape_5.setTransform(-29.9,0,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgwBFIAAgOIAGABQAKAAADgQQACgMAAglIAAg8IBMAAIAACJIgPAAIAAh7IgtAAIAAA2QgBAggDAOQgGAZgSAAg");
	this.shape_6.setTransform(-43.2,-0.1,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wq, new cjs.Rectangle(-49,-8.2,98,16.6), null);


(lib.w = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag6BhIAAjBIAlAAIAABLIAeAAQAWAAAOASQAOAQAAAWQAAAcgMARQgNARgWAAgAgVBFIAVAAQAVAAAAgeQAAgOgGgJQgFgJgKAAIgVAAg");
	this.shape.setTransform(61.4,-2.1,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag6AkIAAhGQAAhCA7AAQAdAAAPAPQAOAPAAAbIAAAJIgkAAIAAgEQAAgSgFgIQgFgHgMAAQgLAAgFAHQgFAIAAASIAABLQAAAUAFAHQAFAHALAAQAWABAAgjIAAgKIAkAAIAAAIQAABCg6AAQg7AAAAhBg");
	this.shape_1.setTransform(44.5,-2,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBhIAAhJQAAgvAEgUIAAAAIg1CMIgoAAIAAjBIAjAAIAABJQAAAugFAVIABAAIA0iMIAoAAIAADBg");
	this.shape_2.setTransform(27.3,-2.1,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhFBgIAAgbQAEACAIgBQAJAAADgLQADgPAAgwIAAheIBwAAIAADBIglAAIAAijIgmAAIAABKQAAAxgKAVQgJAXgXgBQgMAAgKgCg");
	this.shape_3.setTransform(8.5,-1.9,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgzBhIAAjBIBnAAIAAAeIhCAAIAAAtIA8AAIAAAcIg8AAIAAA8IBCAAIAAAeg");
	this.shape_4.setTransform(-7.4,-2.1,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAoB0IAAgnIhPAAIAAAnIgkAAIAAhEIAMAAQAKgWAEgVQAEgVAAgnIAAg8IBtAAIAACjIAMAAIAABEgAgJgqQAAAggFAUQgDASgKAUIA2AAIAAiGIgkAAg");
	this.shape_5.setTransform(-24.9,0.2,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag+AjIAAhFQAAhCA+AAQA/AAAABCIAABFQAAAkgRAQQgQAOgeAAQg+AAAAhCgAgYgmIAABOQAAAfAYAAQAZAAAAgfIAAhNQAAgQgGgJQgHgIgMgBQgYABAAAgg");
	this.shape_6.setTransform(-43.5,-2,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAYBhIAAijIgvAAIAACjIglAAIAAjBIB5AAIAADBg");
	this.shape_7.setTransform(-61.1,-2.1,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.w, new cjs.Rectangle(-68.3,-13.8,136.6,27.8), null);


(lib.rq = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.setTransform(-120,-200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.rq, new cjs.Rectangle(-120,-200,300,600), null);


(lib.qww = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAPAAIAAA7IASAAQArAAABAnQgBAngoAAgAgpA3IASAAQAOAAAHgFQAHgGAAgOQAAgPgIgGQgIgFgQAAIgOAAg");
	this.shape.setTransform(21.5,0,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIABiCIgBAAIghCCIgRAAIgiiCIABCCIgQAAIAAiJIAbAAIAbBrIADAUIADgUIAbhrIAbAAIAACJg");
	this.shape_1.setTransform(4.7,0,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBFIAAiCIAAAAQgCAOgDAJIgrBrIgWAAIAAiJIAPAAIAAB/IAAAAIAGgTIAqhsIAWAAIAACJg");
	this.shape_2.setTransform(-10.5,0,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgpAaIAPAAQABAQAFAHQAHAJAOAAQAaAAAAgdQAAgKgHgIQgHgIgLAAIgMAAIAAgNIAKAAQAVAAAAgXQAAgYgVAAQgKAAgHAHQgGAHgBALIgQAAQADgSAKgKQALgLAQAAQAQAAALAKQAKAKAAAOQAAAZgVAIQAMADAHAIQAHAJAAAPQAAAPgIALQgLAPgXAAQgnAAgCgug");
	this.shape_3.setTransform(-23.3,0,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.qww, new cjs.Rectangle(-28.2,-8.4,56.5,16.9), null);


(lib.qw = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAbBFIABiCIgBAAQgCAPgCAHIgrBsIgWAAIAAiJIAPAAIAAB/IAAAAIAGgTIAqhsIAWAAIAACJg");
	this.shape.setTransform(64.7,0,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIABiCIgBAAIghCCIgRAAIghiCIgBAAIABCCIgPAAIAAiJIAaAAIAbBrQADAIAAAMIAAAAIADgVIAbhqIAbAAIAACJg");
	this.shape_1.setTransform(49.6,0,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaBFIAAg7IgUAAIgdA7IgRAAIAfg9QgbgIABgdQAAgnAoAAIAkAAIAACJgAgMgxQgIAGABAOQAAAPAJAHQAHAFAQAAIANAAIAAg0IgRAAQgOAAgHAFg");
	this.shape_2.setTransform(34.6,0,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgmBFIAAiJIAPAAIAAA7IATAAQArAAAAAnQAAAngoAAgAgXA3IASAAQAOAAAGgFQAIgGAAgOQAAgQgJgGQgHgFgRAAIgNAAg");
	this.shape_3.setTransform(23.5,0,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAaBFIAAhCIgzAAIAABCIgQAAIAAiJIAQAAIAAA7IAzAAIAAg7IAQAAIAACJg");
	this.shape_4.setTransform(10.7,0,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgiBFIAAiJIBEAAIAAAOIg1AAIAAAtIAyAAIAAAMIgyAAIAAA0IA1AAIAAAOg");
	this.shape_5.setTransform(-1,0,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmBFIAAiJIAkAAQAlAAAAAjQAAAYgUAGQAKABAHAIQAHAKAAANQAAATgLALQgKAKgSAAgAgXA3IAXAAQAXAAAAgaQAAgagYAAIgWAAgAgXgJIATAAQALAAAGgFQAGgGAAgMQAAgWgWAAIgUAAg");
	this.shape_6.setTransform(-12.5,0,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglAyQgHgQAAgiQAAhHAsAAQAtAAAABHQAAAigHAQQgKAWgcAAQgaAAgLgWgAgcgCQAAAgAFANQAGAPARAAQASAAAGgPQAGgNAAggQAAg3geAAQgcAAAAA3g");
	this.shape_7.setTransform(-25.3,0,1.176,1.176);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAaBFIAAhCIgzAAIAABCIgPAAIAAiJIAPAAIAAA7IAzAAIAAg7IAQAAIAACJg");
	this.shape_8.setTransform(-38.5,0,1.176,1.176);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgfBFIAAiJIA/AAIAAAOIgwAAIAAB7g");
	this.shape_9.setTransform(-49.1,0,1.176,1.176);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAqBFIABiCIgBAAIgFASIgdBwIgRAAIghiCIABCCIgPAAIAAiJIAbAAIAbBrIACAUIADgVIAbhqIAbAAIAACJg");
	this.shape_10.setTransform(-63,0,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.qw, new cjs.Rectangle(-69.8,-8.4,139.6,16.9), null);


(lib.qrq = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg2();
	this.instance.parent = this;
	this.instance.setTransform(-120,-200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.qrq, new cjs.Rectangle(-120,-200,300,600), null);


(lib.fdgdf = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghBFIAAiJIBDAAIAAAOIg0AAIAAAtIAxAAIAAAMIgxAAIAAA0IA0AAIAAAOg");
	this.shape.setTransform(52.3,0,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAPAAIAAA7IATAAQArAAAAAnQAAAngpAAgAgpA3IASAAQAOAAAHgFQAHgGAAgOQAAgQgIgGQgHgFgSAAIgNAAg");
	this.shape_1.setTransform(38.2,0,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAbBFIAAhCIg0AAIAABCIgQAAIAAiJIAQAAIAAA7IA0AAIAAg7IAOAAIAACJg");
	this.shape_2.setTransform(23.2,0,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAYBFIAAhDQgLABgOAAQgTAAgIgGQgKgJAAgTIAAglIAPAAIAAAjQAAAOAFAFQAFAFAOAAIAXgCIAAg5IAPAAIAACJg");
	this.shape_3.setTransform(10.4,0,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglAyQgHgQAAgiQAAhHAsAAQAtAAAABHQAAAigHAQQgLAWgbAAQgaAAgLgWgAgcgCQAAAgAFANQAGAPARAAQASAAAGgPQAGgNAAggQAAg3geAAQgcAAAAA3g");
	this.shape_4.setTransform(-2.4,0,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgfA7QgJgLgBgXIAPAAQABARAFAIQAHAIAOAAQAaAAAAgcQAAgLgHgHQgHgJgLAAIgMAAIAAgNIAKAAQAVAAAAgXQAAgYgVAAQgKAAgHAHQgGAHgBALIgQAAQADgSAKgKQALgLAQAAQAQAAALAKQAKAKAAAOQAAAZgVAIQAMADAHAHQAHALAAAPQAAAOgIALQgKAOgYAAQgUAAgLgMg");
	this.shape_5.setTransform(-15.1,0,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAgBFIgKgoIgrAAIgKAoIgRAAIAniJIAUAAIAmCJgAgSAPIAkAAIgShIIAAAAg");
	this.shape_6.setTransform(-27.3,0,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAZBFIgjhEIgRAUIAAAwIgPAAIAAiJIAPAAIAABGIAyhGIATAAIgrA6IAsBPg");
	this.shape_7.setTransform(-38.8,0,1.176,1.176);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgiAvQgGgQAAggQAAhGAqAAQATAAALANQAJAMAAATIgPAAQAAgegZAAQgQAAgGAVQgDAMAAAXQAAAbAEANQAGATAPAAQAOAAAFgLQAEgIACgUIAPAAQgBAagIAMQgJAPgVAAQgaAAgKgZg");
	this.shape_8.setTransform(-51.5,0,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.fdgdf, new cjs.Rectangle(-56.3,-8.4,112.7,16.9), null);


(lib.ewe = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.qwr();
	this.instance.parent = this;
	this.instance.setTransform(-107.5,-10);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ewe, new cjs.Rectangle(-107.5,-10,215,20), null);


(lib.hjkkk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AroDrIAAhQIAIAAIABAIIABAAQADgEAFgDQAFgDAGABQANgBAFAIQAHAHAAAPQAAAHgCAGQgCAGgEAEQgEAEgGACQgFADgGAAIgFAAIgDgBIgDgBIgDgBIAAAXgArYClQgDAEgCAGIAAAbIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgKgEgFQgDgGgJAAQgHAAgEADgA0UDrIAAhQIAHAAIACAIIABAAQAEgEAEgDQAFgDAGABQANgBAFAIQAHAHgBAPQAAAHgBAGQgCAGgEAEQgEAEgGACQgFADgGAAIgFAAIgDgBIgDgBIgDgBIAAAXgA0EClQgEAEgBAGIAAAbIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgKgEgFQgDgGgKAAQgGAAgEADgAFGDUQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgFQADgGADgEQADgEAGgDQAFgBAHAAQAHgBAFADQAGACADAFQADADACAGQACAFAAAHQAAAHgCAGQgCAFgDAFQgEADgFACQgGADgGAAQgIAAgFgDgAFGCnQgFAGAAALIACAIIADAHIAEAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgDgCgFAAQgIAAgFAFgAEODUQgGgCgDgEQgDgEgCgFQgBgGAAgHQAAgPAHgHQAIgJAMABIAKAAIAIADIgCAIIgHgCIgHgBQgSAAAAAWIABAIIADAHIAGAFQADACAFAAQAFAAADgBIAHgEIACAIQgDADgGABQgEACgGAAQgIAAgEgDgADmDUQgCgCAAgCQAAgEACgCQACgCAEAAQADAAACACQACACAAAEQAAACgCACQgCADgDAAQgEAAgCgDgACxDTQgFgCgEgGQgDgFgBgHQgCgHAAgKQAAgSAHgLQAHgKAOAAQAOAAAHAKQAGAKABATQAAAUgIAKQgGALgOAAQgIAAgFgEgACwCXQgDAIAAAPIAAANIADAKQACAEAEACQADADAFAAQAIAAAEgIQAFgIAAgQIgBgMIgDgJQgCgFgDgCQgEgDgEABQgJAAgFAHgAhCDSQgDgEAAgJIAAghIgJAAIAAgJIAJAAIAAgLIAKgDIAAAOIASAAIAAAJIgSAAIAAAdQAAAIACACQACADAEAAIAGAAIAEgCIADAHIgHADIgJABQgIAAgEgFgAjKDWQgDgCgCgDQgEgDgBgFQgBgFAAgGIAAgjIAKAAIAAAgIABAIIACAGQAAABABAAQAAABAAAAQABABAAAAQABAAABABQACABAEAAQAGAAAFgEQAEgDACgGIAAgmIALAAIAAAqIAAAIIABAIIgHAAIgDgKIgBAAQgDAGgFACQgFAEgIAAIgJgBgAjsDXQgGAAgDgEQgDgCgBgIIAAhBIAKAAIAAA+QAAAEACACQABAAAAABQABAAAAAAQABABABAAQAAAAABAAIADAAIAFgBIABAHIgDABIgEABIgCABIgEAAgAkVDUQgDgCAAgCQAAgEADgCQABgCADAAQAEAAACACQACACAAAEQAAACgCACQgCADgEAAQgDAAgBgDgApdDUQgCgCAAgCQAAgEACgCQADgCADAAQADAAACACQACACAAAEQAAACgCACQgCADgDAAQgDAAgDgDgAqWDUQgFgCgDgDQgEgFgBgFQgCgGAAgHQAAgPAHgHQAIgJAOABIAIAAQAEACADACQAEACACAFQADAEgBAIIAAAEIgBAEIgoAAQAAAKAEAGQAFAFALAAIAJgBQAEgCADgDIADAIQgEADgFACQgGACgHAAQgHAAgGgDgAqVCmQgFADAAAJIAfAAQABgJgEgDQgEgEgGAAQgJAAgEAEgAsgDUQgGgCgDgEQgDgEgCgGQgCgGAAgGQAAgHACgFQACgGAEgEQADgEAGgDQAFgBAGAAQAIgBAEADQAGACADAFQAEADABAGQACAFAAAHQAAAHgCAGQgCAFgDAFQgEADgFACQgFADgHAAQgHAAgFgDgAsgCnQgFAGAAALIABAIIADAHIAFAFQAEACAEAAQARAAAAgWIAAgIIgDgHIgGgFQgDgCgFAAQgIAAgEAFgA1MDUQgFgCgEgEQgEgEgBgGQgCgGAAgGQAAgHACgFQACgGADgEQAEgEAFgDQAFgBAHAAQAHgBAGADQAFACAEAFQADADABAGQACAFAAAHQAAAHgCAGQgCAFgDAFQgDADgGACQgFADgHAAQgHAAgFgDgA1MCnQgFAGAAALIABAIIADAHIAFAFQADACAFAAQASAAgBgWIgBgIIgCgHIgGgFQgDgCgFAAQgIAAgEAFgAgVDUQgDgBgCgCIgEgEQgBgEgBgDQAAgFACgEQACgDAEgDIAIgDIAJgBIAFAAIAEAAIACABIACAAIAAgEIAAgDIgBgEIgCgEIgDgCIgGAAIgEAAIgFABIgGABIgDACIgDgIQAJgFAPAAQAFAAAEACQAEACADACIADAGIABAGIgBAMIgBAOIABAIIABAHIgHAAIgDgIIgBAAIgDADIgDADIgGACIgHABQgEAAgEgCgAgQC8QgFACAAAHQAAAEAEACQACADAGAAIAGgBIAEgDIADgDIACgDIAAgJIgCAAIgCgBIgDAAIgFAAQgHAAgDACgAkxDWIgQglIgDgLIgTAwIgFAAIgWg7IALAAIAMAhIACALIABAAIAEgLIAMghIAIAAIAPAiIACAKIABAAIADgLIALghIAKAAIgWA7gAmODWIgQglIgDgLIgTAwIgEAAIgXg7IALAAIANAhIACALIABAAIADgLIANghIAIAAIAOAiIADAKIABAAIACgLIALghIAKAAIgVA7gAnqDWIgRglIgCgLIgTAwIgFAAIgWg7IALAAIAMAhIADALIABAAIACgLIAOghIAIAAIANAiIADAKIACAAIACgLIAKghIAKAAIgUA7gAuWDUQgDgBgDgCIgDgEQgCgEAAgDQAAgFACgEQACgDADgDIAIgDIAJgBIAGAAIAEAAIACABIADAAIAAgEIAAgDIgBgEIgCgEIgEgCIgGAAIgEAAIgGABIgFABIgEACIgDgIQAKgFAPAAQAGAAAEACQAEACACACIAEAGIAAAGIAAAMIgBAOIABAIIABAHIgIAAIgCgIIgBAAIgEADIgDADIgGACIgIABQgEAAgDgCgAuSC8QgFACABAHQAAAEADACQADADAFAAIAHgBIAEgDIADgDIADgDIAAgJIgDAAIgCgBIgDAAIgGAAQgGAAgEACgAvSDWIgIgDIADgIIAHACIAJABQAQAAAAgKQAAgEgFgCQgDgCgJAAIgHAAIAAgIIAJAAIAFgBIADgCIAEgDIABgDQAAgFgEgCQgDgBgIAAIgJABIgGACIgDgIQAIgEAOAAQAKAAAFAEQAGADAAAIIgBADIgCAEIgEAEIgEABIAAACQAHABADAEQADADAAAGIgBAHQgCADgEACIgIAEIgMABIgKAAgAyYDUQgEgBgCgCIgEgEQgBgEAAgDQAAgFACgEQACgDADgDIAIgDIAIgBIAGAAIAEAAIADABIACAAIAAgEIAAgDIAAgEIgCgEIgFgCIgFAAIgFAAIgGABIgEABIgFACIgDgIQALgFAOAAQAHAAADACQAEACADACIADAGIAAAGIAAAMIgBAOIABAIIABAHIgHAAIgDgIIgBAAIgDADIgEADIgFACIgIABQgEAAgDgCgAyVC8QgEACAAAHQAAAEADACQADADAFAAIAHgBIAEgDIAEgDIACgDIAAgJIgCAAIgDgBIgDAAIgFAAQgHAAgEACgAHKDVIAAghIAAgIIgDgFQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBgBIgGAAQgHAAgDADQgEADgBAHIAAAlIgLAAIAAggIAAgIIgCgGQgBgCgCgBQgDgCgEABQgFAAgEADQgEADgCAFIAAAnIgKAAIAAg6IAHAAIACAIIABAAQADgEAFgDQAFgCAHAAQAGgBAEADQAEADACAFQADgFAFgDQAGgCAGAAQAFgBAEACQADABACADQADADABAFIABANIAAAhgABoDVIAAgJIAQAAIAAgzIACgHIgFAGIgNAIIgEgGIAagTIAFAAIAABFIAQAAIAAAJgAAmDVIAAgJIARAAIAAgzIABgHIgFAGIgNAIIgEgGIAagTIAFAAIAABFIARAAIAAAJgAhlDVIAAggIgBgIIgCgGIgEgEIgGAAIgHAAIgEADIgFAFIgCAFIAAAlIgKAAIAAhNIAKAAIAAAbIABAAQAEgEAEgDQAFgDAHABQAFgBAEACQAEABACADQADADABAEQACAGAAAHIAAAigAtTDVIAAgxIgTAAIAAgJIAxAAIAAAJIgUAAIAAAxgAvzDVIAAghIABgLIgBAAIgFALIgbAhIgIAAIAAg6IAKAAIAAAjIAAAJIAAAAIAGgJIAbgjIAHAAIAAA6gAw4DVIAAgZIgdAAIAAAZIgLAAIAAg6IALAAIAAAYIAdAAIAAgYIAKAAIAAA6gAzODVIAAg6IAlAAIAAAJIgbAAIAAAxgApdCpQgCgCAAgDQAAgDACgCQADgCADAAQADAAACACQACACAAADQAAADgCACQgCACgDAAQgDAAgDgCgA1aBwIADgJIACABIAEgBIAEgCIADgDIACgHIgZg6IAMAAIASAwIABAAIACgMIANgkIAKAAIgTA0IgEAKIgFAJQgDAFgDABQgDADgEAAIgIgBgAj0BwIAAhPIAHAAIACAHIABAAQADgEAEgCQAFgDAHAAQAMAAAGAHQAGAHAAAQQAAAHgCAFQgCAGgDAEQgFAEgFADQgFACgHAAIgEAAIgEgBIgDAAIgCgBIAAAWgAjlArQgDADgBAHIAAAbIAEACIAIABQAJABAGgHQAEgFAAgLQAAgKgDgFQgEgHgJAAQgGABgFADgAqeBwIAAhPIAHAAIACAHIABAAQADgEAEgCQAFgDAGAAQANAAAGAHQAGAHAAAQQAAAHgCAFQgCAGgEAEQgEAEgFADQgGACgGAAIgEAAIgEgBIgCAAIgEgBIAAAWgAqOArQgEADgCAHIAAAbIAGACIAIABQAIABAFgHQAGgFAAgLQAAgKgFgFQgDgHgJAAQgHABgDADgAtgBmQAEgBACgDQACgEAAgDQgDABgCgBQgCgCAAgEQAAgDACgBQABgCADAAQAEAAADADQACACAAAFQAAAEgBADIgDAFIgFAEIgEACgAIzBpIgCgOIgxAAIAAg6IALAAIAAAxIAbAAIAAgxIAKAAIAAAxIAJAAIAAAXgABHBpIgCgOIgxAAIgCAOIgHAAIAAgXIAIAAIACgFIAEgJIADgOIABgVIAnAAIAAAxIAJAAIAAAXgAAmA0IgCALIgDAKIgEAJIAdAAIAAgpIgUAAIAAALgAnoBpIgBgOIgxAAIgCAOIgGAAIAAgXIAHAAIACgFIAEgJIADgOIACgVIAmAAIAAAxIAJAAIAAAXgAoIA0IgCALIgDAKIgDAJIAcAAIAAgpIgTAAIgBALgAOiBaQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAIgIAOAAIAIABQAEABADADQAEACACAFQADAEgBAIIAAADIgBAFIgoAAQAAAKAEAGQAFAEALAAQAFABAEgCQAEgCADgCIADAIQgEADgFACQgGABgHAAQgHAAgGgCgAOjAsQgFADAAAIIAfAAQABgIgEgDQgEgFgGAAQgJAAgEAFgANiBaQgGgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAIgIANAAIAJABQAEABADADQAEACACAFQACAEAAAIIAAADIAAAFIgqAAQABAKAFAGQAEAEALAAQAEABAFgCQAEgCACgCIAEAIQgEADgFACQgGABgHAAQgHAAgFgCgANiAsQgEADgBAIIAgAAQAAgIgEgDQgEgFgHAAQgHAAgFAFgABmBaQgGgCgDgEQgDgEgBgGQgDgGAAgGQAAgPAIgIQAHgIAOAAIAIABQAFABADADQAEACACAFQACAEAAAIIgBADIAAAFIgpAAQAAAKAFAGQAEAEAMAAIAJgBQAEgCACgCIAEAIQgEADgGACQgFABgIAAQgGAAgGgCgABmAsQgEADAAAIIAfAAQABgIgEgDQgFgFgGAAQgIAAgFAFgAgdBaQgGgCgDgEQgDgEgBgGQgCgGAAgGQgBgPAIgIQAHgIAOAAIAJABQAEABADADQACACACAFQADAEAAAIIgBADIAAAFIgoAAQAAAKAFAGQAEAEALAAQAFABAEgCQAEgCACgCIADAIQgDADgFACQgGABgGAAQgIAAgFgCgAgdAsQgEADAAAIIAfAAQAAgIgEgDQgDgFgHAAQgIAAgFAFgAiiBaQgFgDgDgEQgEgEgCgGQgBgFAAgGQAAgIABgFQACgGAEgEQADgEAGgCQAFgCAHAAQAHAAAFADQAFABAEAFQADAEACAFQACAGAAAHQAAAHgCAFQgCAGgEAEQgDAEgGACQgFACgGAAQgHAAgGgCgAiiAtQgEAGgBALIABAIIAEAGIAEAGQAEABAFAAQARAAAAgVIgBgIIgDgIIgFgFQgEgCgEAAQgJABgEAFgAmNBaQgFgCgDgEQgEgEgCgGQgBgGAAgGQAAgPAHgIQAHgIAOAAIAJABQADABAEADQADACACAFQADAEAAAIIAAADIgBAFIgpAAQAAAKAFAGQAEAEALAAQAFABAEgCQAFgCACgCIADAIQgDADgGACQgGABgGAAQgIAAgFgCgAmMAsQgFADgBAIIAgAAQAAgIgEgDQgDgFgHAAQgIAAgEAFgArXBaQgFgDgDgEQgEgEgCgGQgCgFAAgGQAAgIACgFQACgGAEgEQAEgEAFgCQAFgCAHAAQAHAAAFADQAGABADAFQADAEACAFQACAGAAAHQAAAHgCAFQgCAGgDAEQgEAEgFACQgGACgGAAQgHAAgGgCgArXAtQgFAGAAALIABAIIAEAGIAEAGQAEABAFAAQARAAAAgVIgBgIIgDgIIgFgFQgEgCgEAAQgIABgFAFgAybBaQgFgDgDgEQgEgEgCgGQgBgFAAgGQAAgIABgFQACgGAEgEQADgEAGgCQAFgCAHAAQAHAAAFADQAFABAEAFQADAEACAFQACAGAAAHQAAAHgCAFQgCAGgEAEQgDAEgGACQgFACgGAAQgHAAgGgCgAybAtQgEAGgBALIABAIIAEAGIAEAGQAEABAFAAQARAAAAgVIgBgIIgDgIIgFgFQgEgCgEAAQgJABgEAFgA0UBaQgFgDgEgEQgDgDgBgGQgBgGAAgGQAAgPAGgIQAIgIANAAIAKABIAIADIgDAIIgGgDIgHgBQgTAAABAXIABAIIACAGIAHAGQADABAFAAQAFABADgCIAGgDIADAHQgDAEgGABQgFABgFAAQgIAAgFgCgAGLBaQgDgBgDgCIgDgFQgCgDAAgEQAAgFACgEQACgDADgCIAIgEIAJgBIAGAAIAEAAIACABIADAAIAAgDIAAgDIgBgFIgCgDIgEgCIgGgBIgEAAIgGABIgFACIgEACIgDgIQAKgFAPgBQAGAAAEADQAEABACACIAEAHIAAAGIAAAMIgBANIABAIIABAIIgIAAIgCgJIgBAAIgEADIgDAEIgGACIgIAAQgEAAgDgBgAGPBBQgFADABAGQAAAFADACQADACAFAAIAHgBIAEgCIADgEIADgDIAAgJIgDAAIgCAAIgDAAIgGAAQgGAAgEABgAhfBbIgJAAIAAAAIgBAAIAAg7IAEAAIAIAAIAJgBQANAAAGAFQAFADAAAHQAAAEgCAEQgDADgFACIAAACQAGABAEADQADAEAAAFQAAAJgHAEQgIAEgOAAIgJAAgAhfBSIAFABIAFAAQAJAAAFgCQADgDAAgFIgBgDIgCgEIgFgBIgIgBIgLAAgAhfA5IANAAIAEgBIAEgBIADgDIABgEQAAgEgDgCQgDgCgIAAIgEAAIgHAAgAxYBbIgJAAIAAAAIgBAAIAAg7IAEAAIAIAAIAJgBQANAAAGAFQAFADAAAHQAAAEgCAEQgDADgFACIAAACQAGABAEADQADAEAAAFQAAAJgHAEQgIAEgOAAIgJAAgAxYBSIAFABIAFAAQAJAAAFgCQADgDAAgFIgBgDIgCgEIgFgBIgIgBIgLAAgAxYA5IANAAIAEgBIAEgBIADgDIABgEQAAgEgDgCQgDgCgIAAIgEAAIgHAAgAzuBbIgDgBIABgJIAEAAQACAAACgCQACgBACgGIADgPIABgYIAmAAIAAA6IgKAAIAAgyIgTAAIAAAEIgCATQgBAJgCAGQgCAGgDADQgEADgEAAIgFAAgAMYBbIAAgiIACgLIgBAAIgGALIgbAiIgIAAIAAg6IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA6gAKzBbIAAgiIACgLIgBAAIgGALIgbAiIgIAAIAAg6IAKAAIAAAiIgBAKIABAAIAGgKIAbgiIAHAAIAAA6gAJuBbIAAgiIABgLIgBAAIgGALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAIAAIAAA6gAHpBbIgUgbIgHAAIAAAbIgKAAIAAg6IAKAAIAAAaIAHgCIATgYIALAAIgTAWIgGAEIAHAFIAVAbgAFIBbIAAgYIgLACIgQAWIgMAAIAOgTIAGgFQgHAAgFgFQgEgFgBgGQAAgFACgEQADgEADgCQAEgCAFgCQAGgBAFAAIAJAAIAJACIAAA6gAE0ArQgEACgBAGQAAAFAFADQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgJAAgDADgAEIBbIAAgiIABgLIgBAAIgFALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAagiIAIAAIAAA6gADDBbIAAgaIgdAAIAAAaIgLAAIAAg6IALAAIAAAXIAdAAIAAgXIAKAAIAAA6gAkSBbIAAgyIgcAAIAAAyIgKAAIAAg6IAxAAIAAA6gAmvBbIgVgbIgGAAIAAAbIgKAAIAAg6IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAEIAHAFIAUAbgAo2BbIAAgYIgKACIgRAWIgNAAIAPgTIAGgFQgHAAgFgFQgFgFABgGQAAgFABgEQADgEADgCQAEgCAFgCQAGgBAGAAIAJAAIAIACIAAA6gApLArQgEACAAAGQABAFAEADQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgIAAgFADgAsBBbIAAgyIgcAAIAAAyIgKAAIAAg6IAwAAIAAA6gAt2BbIgMgRIgFgIIgEAIIgNARIgMAAIAXgeIgVgcIANAAIALAOIAEAIIAFgIIALgOIALAAIgVAcIALAOIAMAQgAu6BbIAAgYIgLACIgQAWIgNAAIAPgTIAFgFQgHAAgFgFQgEgFAAgGQAAgFACgEQACgEADgCQAFgCAEgCQAGgBAGAAIAJAAIAJACIAAA6gAvPArQgEACAAAGQAAAFAEADQAGADAIAAIAHAAIAAgWIgFAAIgDAAQgJAAgEADgAv7BbIAAgiIACgLIgBAAIgFALIgbAiIgJAAIAAg6IALAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA6gAO1AZQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBABAAQAAgBAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABgBAAAAQABAAABAAQAAgBABAAQABAAAAABQABAAABAAQAAAAABABQAAAAAAABQABAAAAAAQAAABABAAQAAABAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBgBAAgAOeAZQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAgBABAAQAAAAABAAQABgBAAAAQABAAABABQAAAAABAAQAAAAABABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABQABAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAMlgJIAAhPIAHAAIACAHIABAAQAEgEAEgDQAFgCAGAAQANAAAFAGQAHAIgBAPQAAAHgBAGQgCAGgEAEQgEAEgGACQgFACgGAAIgFAAIgDAAIgDgBIgDgBIAAAXgAM1hPQgEAEgBAGIAAAbIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgJgEgGQgDgGgKAAQgGAAgEADgAKlgJIAAgWIgFABIgEAAQgLABgHgIQgFgHgBgQQABgOAGgIQAHgIANAAIADAAIADABIAAgTIAKAAIAAATIAFgBIADAAQANAAAGAHQAGAHABAPQgBAHgBAGIgFAKQgEAEgEACQgFACgGAAIgDAAIgFgBIAAAWgAKvhRIAAArIADABIAEAAQAIgBAEgFQAEgHAAgLIAAgJQgCgDgCgDQgCgDgDgBIgIgBIgDAAIgDAAgAKThNQgEAGAAALIABAJIADAHQACADADABQADACAEABIADAAIAEgCIAAgqIgDAAIgEAAQgHAAgFAEgABKgJIAAhPIAHAAIACAHIABAAQADgEAFgDQAFgCAFAAQANAAAGAGQAGAIAAAPQAAAHgCAGQgCAGgEAEQgDAEgGACQgFACgHAAIgEAAIgDAAIgEgBIgDgBIAAAXgABahPQgEAEgCAGIAAAbIAGADIAIABQAIAAAFgGQAFgFABgMQAAgJgFgGQgDgGgJAAQgGAAgEADgAt+gJIAAhPIAHAAIACAHIABAAQADgEAFgDQAFgCAGAAQAMAAAHAGQAFAIAAAPQAAAHgCAGQgCAGgDAEQgEAEgGACQgFACgHAAIgDAAIgEAAIgDgBIgDgBIAAAXgAtuhPQgEAEgBAGIAAAbIAFADIAIABQAJAAAFgGQAFgFAAgMQAAgJgEgGQgDgGgKAAQgGAAgEADgAQwgQIgCgPIgxAAIAAg5IAKAAIAAAwIAcAAIAAgwIAKAAIAAAwIAKAAIAAAYgAA3gQIgBgPIgyAAIgCAPIgFAAIAAgYIAGAAIADgEIAEgJIACgPIACgUIAnAAIAAAwIAJAAIAAAYgAAWhGIgCALIgCALIgEAIIAcAAIAAgoIgTAAIgBAKgAkWgQIgBgPIgyAAIgBAPIgHAAIAAgYIAHAAIADgEIAEgJIACgPIACgUIAmAAIAAAwIAKAAIAAAYgAk3hGIgCALIgCALIgEAIIAcAAIAAgoIgTAAIgBAKgAUxgmQgHgJAAgSIABgRQABgGACgGQACgEAEgCQADgEADgBIAIgCIAKgBIALgBQADgBACgCIABAJIgGADIgMABIgKACIgHACQgDACgBAFQgCAEgBAGIABABQAEgGAGgCQAEgCAIAAQAMAAAGAHQAGAGABAOQAAAHgCAHQgCAFgEAEQgEADgFACQgFACgGAAQgPABgHgJgAU5hJQgEAFAAAJIABAIIADAHIAGAEQADACAEAAQASAAAAgVIgBgIIgEgGQgBgCgDgCQgEgBgDgBQgKAAgFAGgAT0ggQgGgCgDgEQgDgEgCgGQgCgGAAgGQAAgHACgFQACgHAEgDQADgEAGgCQAEgCAHAAQAIAAAEACQAGACADAFQAEAEACAFQABAGAAAGQAAAHgBAGQgCAFgEAFQgDADgGACQgFACgHAAQgHAAgFgCgAT0hNQgFAGAAALIABAIIADAHIAFAFQAEACAEAAQARAAABgWIgBgIIgEgHIgEgFQgEgCgFAAQgIAAgEAFgALtggQgFgCgEgEQgEgEgBgGQgCgGAAgGQAAgHACgFQACgHADgDQAEgEAFgCQAFgCAHAAQAHAAAGACQAFACAEAFQADAEABAFQACAGAAAGQAAAHgCAGQgCAFgDAFQgDADgGACQgFACgHAAQgHAAgFgCgALthNQgFAGAAALIABAIIADAHIAFAFQADACAFAAQASAAgBgWIgBgIIgCgHIgGgFQgDgCgFAAQgIAAgEAFgADagmQgIgJAAgSIABgRQABgGADgGQACgEADgCQADgEAEgBIAIgCIAKgBIAKgBQAEgBACgCIABAJIgHADIgLABIgKACIgHACQgDACgCAFQgCAEgBAGIABABQAFgGAFgCQAFgCAIAAQALAAAHAHQAGAGAAAOQAAAHgCAHQgCAFgDAEQgFADgEACQgGACgGAAQgPABgGgJgADihJQgFAFAAAJIABAIIAEAHIAFAEQADACAEAAQASAAAAgVIgBgIIgDgGQgCgCgDgCQgDgBgEgBQgKAAgEAGgACcggQgFgCgEgEQgDgEgBgGQgDgGAAgGQAAgHADgFQABgHAEgDQADgEAGgCQAFgCAHAAQAHAAAFACQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAGQgCAFgDAFQgEADgFACQgGACgGAAQgIAAgFgCgACchNQgFAGABALIABAIIACAHIAGAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAFgAgyggQgFgCgEgEQgDgEgBgGQgDgGAAgGQAAgHADgFQABgHAEgDQADgEAGgCQAFgCAHAAQAHAAAFACQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAGQgCAFgDAFQgEADgFACQgGACgGAAQgIAAgFgCgAgyhNQgFAGABALIABAIIACAHIAGAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAFgAjFggQgDgCAAgCQAAgEADgCQACgBADAAQAEAAACABQABACAAAEQAAACgBACQgCACgEAAQgDAAgCgCgAmAggQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgFQADgHADgDQADgEAGgCQAFgCAHAAQAHAAAFACQAGACADAFQADAEACAFQACAGAAAGQAAAHgCAGQgCAFgDAFQgEADgFACQgGACgGAAQgIAAgFgCgAmAhNQgFAGAAALIACAIIADAHIAEAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgDgCgFAAQgIAAgFAFgAqNghQgFgCgEgGQgDgEgBgIQgCgHAAgKQAAgSAHgLQAHgLANABQAPgBAHALQAHAKAAATQgBATgGALQgIALgOgBQgGAAgGgDgAqOhdQgDAIAAAPIABANIACAJQADAFADACQADACAEAAQAKABAEgIQAEgIAAgQIgBgMIgDgJQgCgFgEgCQgCgCgGAAQgIgBgFAIgAu/gmQgHgJAAgSIABgRQABgGADgGQABgEADgCQAEgEADgBIAIgCIAKgBIAKgBQAEgBADgCIAAAJIgGADIgMABIgJACIgIACQgCACgCAFQgDAEAAAGIABABQAEgGAFgCQAGgCAHAAQAMAAAGAHQAHAGAAAOQgBAHgCAHQgCAFgDAEQgEADgFACQgFACgHAAQgOABgHgJgAu3hJQgEAFAAAJIABAIIADAHIAGAEQADACAEAAQARAAAAgVIgBgIIgCgGQgCgCgEgCQgDgBgDgBQgLAAgEAGgAyqggQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgFQADgHADgDQADgEAGgCQAFgCAHAAQAHAAAFACQAGACADAFQADAEACAFQACAGAAAGQAAAHgCAGQgCAFgDAFQgEADgFACQgGACgGAAQgIAAgFgCgAyqhNQgFAGAAALIACAIIADAHIAEAFQAEACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgDgCgFAAQgIAAgFAFgA0NghQgFgCgEgGQgDgEgCgIQgBgHAAgKQAAgSAHgLQAHgLANABQAPgBAHALQAHAKgBATQAAATgGALQgIALgOgBQgGAAgGgDgA0NhdQgEAIgBAPIACANIADAJQACAFADACQADACAEAAQAJABAFgIQAEgIAAgQIgBgMIgDgJQgCgFgEgCQgCgCgGAAQgIgBgEAIgA1RgfIgHgCIADgJIAGACIAJABIAHgBIAGgDQACgBABgEQACgCAAgDQAAgIgFgDQgFgEgIAAIgJAAIAAgEIAQgXIAGgEIgfAAIAAgJIArAAIAAAEIgTAZIgDADIADAAQAFAAAEABQAEACADADIAFAHQABADABAGQgBAGgCAFQgCAEgEADQgEADgFACQgGABgFAAIgLgBgAPEggQgEgBgCgBIgDgGQgCgDAAgDQAAgGACgDQACgDADgDIAIgDIAJgCIAGAAIAEABIADABIACAAIAAgEIAAgCIgBgGIgCgDIgEgBIgGgBIgFAAIgFABIgFABIgEACIgDgIQAKgFAPAAQAGAAAEACQAEACADACIACAGIABAHIgBALIAAAOIAAAIIABAHIgHAAIgDgJIAAAAIgDAEIgFADIgFACIgHABQgEAAgEgCgAPIg4QgFACABAGQgBAFAEACQADACAFAAIAHgBIAEgCIAEgDIACgEIAAgIIgCgBIgDAAIgEAAIgFAAQgGAAgEACgAFmggQgDgBgCgBIgFgGQgBgDAAgDQAAgGACgDQACgDADgDIAIgDIAJgCIAGAAIAEABIACABIADAAIAAgEIAAgCIgBgGIgCgDIgEgBIgGgBIgEAAIgGABIgFABIgEACIgDgIQAKgFAOAAQAHAAAEACQAEACACACIAEAGIAAAHIAAALIgBAOIABAIIABAHIgIAAIgCgJIgBAAIgEAEIgDADIgGACIgIABQgEAAgDgCgAFqg4QgFACAAAGQAAAFAEACQADACAFAAIAGgBIAFgCIADgDIADgEIAAgIIgDgBIgCAAIgDAAIgGAAQgGAAgEACgAj8ggQgEgBgCgBIgEgGQgCgDAAgDQAAgGADgDQABgDAEgDIAIgDIAIgCIAHAAIADABIADABIACAAIABgEIAAgCIgBgGIgDgDIgDgBIgHgBIgEAAIgGABIgEABIgFACIgCgIQAKgFAOAAQAGAAAFACQAEACACACIADAGIABAHIgBALIAAAOIAAAIIABAHIgHAAIgDgJIgBAAIgDAEIgEADIgGACIgHABQgEAAgDgCgAj5g4QgEACAAAGQAAAFAEACQACACAGAAIAGgBIAEgCIAEgDIACgEIAAgIIgCgBIgDAAIgDAAIgFAAQgHAAgEACgASqgfIAAgXIgKACIgRAVIgMAAIAPgTIAFgEQgHgBgFgFQgEgEAAgGQAAgFACgEQACgEADgDQAFgCAEgBQAGgBAGAAIAJAAIAJACIAAA5gASWhPQgEADAAAGQAAAFAEADQAGADAIgBIAGAAIAAgVIgEAAIgDAAQgJAAgEACgARqgfIAAghIACgMIgBAAIgFAMIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAHAAIAAA5gAOhgfIAAgtIgBAAIgFAJIgPAXIgDAAIgQgXIgFgJIAAAAIAAAMIAAAhIgJAAIAAg5IAKAAIASAZIAEAIIAVghIAKAAIAAA5gAJrgfIAAgZIgdAAIAAAZIgLAAIAAg5IALAAIAAAXIAdAAIAAgXIAKAAIAAA5gAImgfIAAghIABgMIAAAAIgGAMIgbAhIgIAAIAAg5IALAAIAAAiIgCAKIACAAIAFgKIAagiIAIAAIAAA5gAHCgfIAAgXIgLACIgQAVIgNAAIAPgTIAGgEQgIgBgFgFQgEgEAAgGQAAgFACgEQACgEAEgDQADgCAGgBQAFgBAGAAIAJAAIAJACIAAA5gAGthPQgEADAAAGQAAAFAEADQAFADAJgBIAHAAIAAgVIgFAAIgDAAQgJAAgEACgAFDgfIAAgZIgeAAIAAAZIgKAAIAAg5IAKAAIAAAXIAeAAIAAgXIAKAAIAAA5gAhdgfIAAhDIglAAIAABDIgLAAIAAhNIA8AAIAABNgAm5gfIAAg5IAlAAIAAAIIgbAAIAAAxgAoRgfIAdg/IAGgFIgHABIgiAAIAAgKIAzAAIAAADIgjBKgApTgfIAAgJIAQAAIAAgzIACgHIgFAFIgNAJIgFgGIAbgTIAFAAIAABFIAQAAIAAAJgArcgfIAAgEIAHgGIAIgJIAIgJIAHgKIAEgKQACgFAAgEQAAgFgDgEQgDgDgGAAIgJACIgIAEIgEgIIAKgFQAGgCAGAAQALgBAGAGQAFAGABAIQAAAGgDAFIgGAMIgIAMIgJALIgHAEIAAABIAJgBIAZAAIAAAJgAsVgfIAAgXIgLACIgQAVIgNAAIAOgTIAHgEQgIgBgFgFQgEgEAAgGQAAgFACgEQACgEAEgDQADgCAGgBQAFgBAGAAIAJAAIAIACIAAA5gAsqhPQgEADAAAGQAAAFAFADQAFADAHgBIAIAAIAAgVIgFAAIgEAAQgIAAgEACgAvhgfIAAgXIgKACIgRAVIgMAAIAPgTIAFgEQgHgBgEgFQgFgEAAgGQAAgFACgEQACgEADgDQAFgCAEgBQAGgBAGAAIAJAAIAIACIAAA5gAv1hPQgEADAAAGQAAAFAEADQAFADAJgBIAGAAIAAgVIgDAAIgFAAQgIAAgEACgAwrgfIAAgxIgTAAIAAgIIAxAAIAAAIIgUAAIAAAxgAxMgfIgVgaIgGAAIAAAaIgKAAIAAg5IAKAAIAAAaIAGgCIAUgYIALAAIgTAVIgFAFIAHAFIAUAagAQ5iEIAAhPIAHAAIACAHIABAAQADgEAFgDQAFgCAFAAQANAAAGAHQAGAHAAAPQAAAHgCAHQgCAGgDAEQgEADgGADQgGACgGAAIgEAAIgDAAIgEgBIgDgBIAAAWgARJjJQgEAEgCAGIAAAaIAGAEIAHABQAKAAAEgHQAFgFABgMQgBgJgEgFQgDgHgJAAQgGABgEADgAnaiEIAAhPIAHAAIACAHIAAAAQADgEAFgDQAFgCAGAAQAMAAAGAHQAHAHAAAPQAAAHgCAHQgDAGgDAEQgEADgFADQgGACgGAAIgFAAIgDAAIgDgBIgDgBIAAAWgAnLjJQgDAEgCAGIAAAaIAFAEIAIABQAJAAAFgHQAFgFAAgMQAAgJgEgFQgEgHgIAAQgHABgEADgAtLiEIAAhPIAIAAIABAHIABAAQADgEAFgDQAFgCAGAAQANAAAFAHQAHAHAAAPQAAAHgCAHQgCAGgEAEQgEADgGADQgFACgGAAIgFAAIgDAAIgDgBIgDgBIAAAWgAs7jJQgDAEgCAGIAAAaIAFAEIAIABQAJAAAFgHQAFgFAAgMQAAgJgEgFQgDgHgJAAQgHABgEADgAFNiLIgDgOIgxAAIAAg6IALAAIAAAxIAbAAIAAgxIAKAAIAAAxIAKAAIAAAXgAifiLIgBgOIgyAAIgCAOIgGAAIAAgXIAHAAIADgFIAEgJIACgOIACgVIAnAAIAAAxIAJAAIAAAXgAjAjAIgCALIgCALIgEAIIAdAAIAAgpIgUAAIgBALgAxciLIgDgOIgwAAIAAg6IAKAAIAAAxIAbAAIAAgxIAKAAIAAAxIAKAAIAAAXgAUuiaQgFgDgEgDQgDgEgBgGQgDgGAAgHQAAgGADgGQABgGAEgEQADgDAGgDQAFgCAHAAQAHAAAFACQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAHQgCAFgDAEQgEAEgFACQgGACgGAAQgIAAgFgCgAUujHQgFAGABAKIABAIIADAHIAFAGQADACAFAAQARAAAAgXIgBgHIgDgHIgFgGQgDgCgFAAQgJABgEAFgAP4igQgIgJABgSIABgSQABgGACgFQACgEADgDQADgDAEgCIAIgCIAKgBIAKgBQADAAADgCIABAJIgGACIgNABIgJACIgHADQgDACgCAEQgCAFAAAGIABABQADgGAGgCQAFgCAHgBQAMAAAGAHQAHAHAAANQAAAIgCAGQgCAGgEADQgDAEgGACQgEACgHAAQgPAAgGgIgAQAjEQgEAFgBAKIABAIIADAGIAGAFQADABAFABQARgBAAgUIgBgIIgDgHQgBgCgEgBQgDgCgEAAQgKAAgEAFgAMIiaQgGgCgDgEQgEgEgBgGQgCgFAAgIQAAgOAHgIQAIgIANAAIAJABQAEABADADQAEACACAEQACAFAAAIIAAADIAAAFIgqAAQABAKAFAFQAEAGALAAIAJgCQAEgCACgCIAEAIQgEADgFACQgGABgHAAQgHAAgFgCgAMIjJQgEAEgBAJIAgAAQAAgJgEgEQgEgEgHAAQgHAAgFAEgALPiaQgFgDgDgDQgEgEgBgGQgBgFgBgIQAAgOAIgIQAHgIANAAIAKABIAIACIgCAJIgHgDIgIgBQgRABgBAVIABAJIAEAGIAFAGQAEACAFAAQAEgBAEgBIAGgDIADAHQgEADgFACQgFABgGAAQgHAAgFgCgAIViaQgFgDgEgDQgCgEgCgGQgCgFAAgIQABgOAGgIQAIgIANAAIAKABIAIACIgDAJIgGgDIgHgBQgTABABAVIABAJIACAGIAHAGQADACAFAAQAEgBAEgBIAGgDIADAHQgEADgFACQgFABgGAAQgHAAgFgCgAiAiaQgFgCgDgEQgDgEgCgGQgCgFAAgIQAAgOAIgIQAGgIAPAAIAIABQAEABAEADQADACACAEQADAFAAAIIgBADIgBAFIgoAAQAAAKAEAFQAFAGALAAIAJgCQAEgCADgCIADAIQgDADgHACQgFABgHAAQgHAAgGgCgAh/jJQgFAEAAAJIAfAAQABgJgEgEQgEgEgGAAQgJAAgEAEgAkDiaQgGgCgDgEQgDgEgCgGQgCgFAAgIQAAgOAIgIQAGgIAOAAIAJABQAEABADADQAEACACAEQACAFABAIIgBADIAAAFIgqAAQAAAKAGAFQAEAGALAAIAJgCQAEgCACgCIAEAIQgDADgGACQgGABgHAAQgHAAgFgCgAkDjJQgEAEgBAJIAgAAQAAgJgEgEQgEgEgHAAQgHAAgFAEgAmJiaQgEgDgEgDQgEgEgBgGQgCgGAAgHQAAgGACgGQACgGADgEQAEgDAFgDQAFgCAHAAQAHAAAGACQAFACAEAFQADAEABAFQACAGABAGQgBAHgCAHQgCAFgDAEQgDAEgGACQgFACgHAAQgHAAgGgCgAmJjHQgEAGAAAKIABAIIADAHIAFAGQADACAFAAQASAAgBgXIgBgHIgCgHIgGgGQgDgCgFAAQgIABgFAFgAr5iaQgEgDgEgDQgEgEgBgGQgCgGAAgHQAAgGACgGQACgGADgEQAEgDAFgDQAGgCAHAAQAHAAAFACQAFACAEAFQADAEABAFQADAGAAAGQAAAHgDAHQgBAFgEAEQgDAEgGACQgFACgGAAQgIAAgGgCgAr5jHQgEAGAAAKIABAIIADAHIAFAGQADACAGAAQAQAAAAgXIgBgHIgDgHIgFgGQgDgCgEAAQgJABgFAFgAt7iaQgHgDgFgEQgFgGgDgHQgDgIAAgKQAAgLADgIQADgHAGgFQAFgEAHgDQAGgCAGAAIAMABIAIACIgCAJQgGgCgLAAQgEAAgFABQgEACgFAEQgDADgCAGQgDAGAAAIQAAAHADAGQACAGADAEQAEADAFADQAFACAGAAIAJgBQAEgCADgCIACAJQgDADgGABIgMABQgGAAgHgCgAvHiaQgCgCAAgDQAAgEACgBQADgCADAAQADAAACACQACABAAAEQAAADgCACQgCACgDAAQgDAAgDgCgACkiaQgDgBgCgCIgEgFQgCgDABgEQAAgFABgEQADgDADgDIAIgDIAIgBIAGAAIAFABIACAAIACAAIAAgDIAAgDIgBgFIgBgEIgFgBIgFgBIgFAAIgFABIgGACIgDACIgEgIQAKgGAPAAQAHAAADACQAEACADADIADAFIAAAHIAAAMIgBANIABAJIABAHIgHAAIgDgJIgBAAIgDADIgEADIgFADIgIABQgEgBgEgBgACoiyQgEACAAAGQAAAEADADQAEACAEAAIAHgBIAEgDIAEgDIACgDIAAgIIgCgBIgCAAIgEAAIgFAAQgHAAgEACgAlGiZIgIAAIgBAAIgBAAIAAg7IAFAAIAIAAIAJgBQANAAAGAFQAFADAAAHQAAAEgDAEQgDADgFACIAAABQAHACADAEQAEADAAAGQgBAIgGAEQgIAEgPABIgJgBgAlFihIAEAAIAGAAQAJAAAEgCQADgDAAgEIAAgFIgDgDIgEgBIgIgBIgLAAgAlFi7IANAAIAEAAIAEgCIACgDIABgEQAAgEgCgCQgDgCgIAAIgFAAIgGAAgAUEiZIAAgyIgcAAIAAAyIgLAAIAAg6IAyAAIAAA6gAShiZIAAgYIgLACIgQAWIgNAAIAPgTIAGgFQgHgBgFgEQgFgFAAgGQABgFACgEQACgEADgCQAEgDAFgBQAFgBAHAAIAJAAIAIACIAAA6gASMjKQgDADAAAGQgBAFAFADQAFADAIgBIAHAAIAAgVIgEAAIgEAAQgJAAgEACgAPWiZIAAgYIgKACIgRAWIgNAAIAPgTIAGgFQgHgBgFgEQgEgFAAgGQAAgFABgEQACgEAEgCQAEgDAFgBQAGgBAFAAIAJAAIAJACIAAA6gAPCjKQgFADAAAGQABAFAEADQAFADAIgBIAHAAIAAgVIgEAAIgEAAQgIAAgEACgAOMiZIAAgyIgUAAIAAgIIAyAAIAAAIIgUAAIAAAygANkiZIAAgZIgdAAIAAAZIgKAAIAAg6IAKAAIAAAYIAdAAIAAgYIAKAAIAAA6gAKAiZIAAgYIglAAIAAgEIAogzIAHAAIAAAuIAPAAIAAAJIgPAAIAAAYgAJ9jSIgQAVIgHAEIAJgBIARAAIAAgVIABgJgAHNiZIAAgiIABgLIgBAAIgGALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA6gAGHiZIAAgiIABgLIgBAAIgFALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAagiIAIAAIAAA6gAECiZIgUgaIgGAAIAAAaIgLAAIAAg6IALAAIAAAaIAGgCIATgYIAMAAIgTAWIgGAEIAHAGIAVAagABiiZIAAgYIgLACIgQAWIgNAAIAPgTIAFgFQgHgBgFgEQgEgFAAgGQAAgFACgEQACgEADgCQAFgDAEgBQAGgBAGAAIAJAAIAJACIAAA6gABNjKQgEADAAAGQAAAFAEADQAGADAIgBIAHAAIAAgVIgFAAIgDAAQgJAAgEACgAAhiZIAAgiIACgLIgBAAIgFALIgbAiIgIAAIAAg6IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA6gAgiiZIAAgZIgdAAIAAAZIgLAAIAAg6IALAAIAAAYIAdAAIAAgYIAKAAIAAA6gAn4iZIAAgyIgcAAIAAAyIgLAAIAAg6IAyAAIAAA6gApbiZIAAgiIABgLIgBAAIgGALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA6gAqaiZIgVgaIgGAAIAAAaIgLAAIAAg6IALAAIAAAaIAGgCIATgYIAMAAIgTAWIgGAEIAHAGIAUAagAviiZIAAgYIgLACIgQAWIgMAAIAOgTIAGgFQgHgBgFgEQgEgFgBgGQAAgFACgEQADgEADgCQAEgDAFgBQAGgBAFAAIAJAAIAJACIAAA6gAv2jKQgEADgBAGQAAAFAFADQAFADAIgBIAHAAIAAgVIgEAAIgEAAQgJAAgDACgAwiiZIAAgiIABgLIgBAAIgFALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAagiIAIAAIAAA6gAyniZIgUgaIgGAAIAAAaIgLAAIAAg6IALAAIAAAaIAGgCIATgYIALAAIgSAWIgGAEIAHAGIAVAagAzhiZIgJgVIgeAAIgIAVIgLAAIAghPIAFAAIAgBPgAz8jNIgJAWIAYAAIgJgWIgDgLgA1LjPIgCgHIgCAHIgEAEIgGgDIAEgFIAEgEIgGABIgHAAIAAgHIAHAAIAHACIgFgFIgDgGIAFgDIAEAEIACAHIACgGIADgFIAFADIgCAGIgGAFIAIgCIAGAAIAAAHIgGAAIgHgBIAGAFIACAFIgGADg");
	this.shape.setTransform(25.2,63.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AroDrIAAhQIAIAAIABAHIABAAQADgDAFgDQAFgCAGgBQANAAAFAIQAHAGgBAQQAAAHgBAGQgCAGgEAEQgEAEgGADQgFACgGAAIgFAAIgDgBIgDgBIgDgBIAAAXgArYClQgDAEgCAGIAAAbIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgGQgDgGgKAAQgGAAgEADgA0UDrIAAhQIAHAAIACAHIABAAQADgDAFgDQAFgCAGgBQAMAAAHAIQAFAGAAAQQAAAHgCAGQgCAGgDAEQgEAEgGADQgFACgHAAIgDAAIgEgBIgDgBIgDgBIAAAXgA0EClQgEAEgBAGIAAAbIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgJgEgGQgDgGgKAAQgGAAgEADgAFGDUQgFgCgEgEQgDgEgBgGQgDgGAAgGQAAgHADgGQABgFAEgEQADgEAGgDQAFgCAHAAQAHABAFACQAGACADAEQAEAEABAGQACAFAAAHQAAAHgCAGQgCAGgDAEQgEADgFADQgGACgGAAQgIgBgFgCgAFGCoQgFAFABALIABAIIACAHIAGAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAGgAEODVQgFgDgEgEQgDgEgCgFQgBgGAAgHQAAgPAHgHQAHgJANAAIAKABIAIADIgCAIIgHgCIgHgBQgSAAAAAWIABAIIADAHIAGAFQADACAFAAQAFAAADgBIAGgEIADAIQgDADgGABQgFABgFABQgIAAgEgCgADmDVQgCgDAAgDQAAgDACgCQADgCACAAQAEAAACACQACACAAADQAAADgCADQgCACgEAAQgCAAgDgCgACxDTQgFgCgDgFQgEgGgCgHQgBgIAAgJQAAgTAHgKQAHgKAOAAQAOAAAHAKQAGAKAAATQABAUgIAKQgGALgOAAQgIAAgFgEgACwCXQgEAIAAAPIABANIADAKQADAEADADQADACAFAAQAJAAADgIQAFgIAAgQIgBgMIgDgJQgCgFgDgCQgDgDgFABQgJAAgFAHgAhCDSQgDgEAAgJIAAghIgKAAIAAgJIAKAAIAAgLIAKgDIAAAOIASAAIAAAJIgSAAIAAAdQAAAIACACQACADAEAAIAGAAIAEgCIADAHIgHADIgJABQgIAAgEgFgAjKDWQgDgCgCgDQgEgDgBgFQgBgEAAgIIAAgiIAKAAIAAAgIABAIIACAGQAAABABAAQAAABAAAAQABABAAAAQABAAABABQACABAEAAQAHAAAEgEQAEgEACgFIAAgmIALAAIAAAqIAAAIIABAIIgHAAIgDgJIgBAAQgDAEgFADQgFAEgIAAIgJgBgAjrDXQgHAAgDgEQgDgCgBgIIAAhBIAKAAIAAA+QAAAEACACQABAAAAABQABAAAAAAQABABABAAQAAAAABAAIADAAIAFgBIABAIIgDAAIgEABIgCABIgDAAgAkVDVQgDgDAAgDQAAgDADgCQABgCADAAQAEAAACACQACACAAADQAAADgCADQgCACgEAAQgDAAgBgCgApcDVQgDgDAAgDQAAgDADgCQABgCAEAAQADAAACACQACACAAADQAAADgCADQgCACgDAAQgEAAgBgCgAqWDVQgFgDgDgDQgDgEgCgGQgCgGAAgHQAAgPAHgHQAIgJAOAAIAIABQAEACADACQAEACACAFQACAFAAAHIAAAEIgBAFIgoAAQAAAJAEAGQAFAFALAAIAJgBQAEgCADgDIADAIQgEADgGACQgFABgHABQgHAAgGgCgAqVCmQgFAEAAAIIAfAAQABgIgEgEQgEgEgGAAQgJAAgEAEgAsgDUQgFgCgEgEQgDgEgCgGQgCgGAAgGQAAgHACgGQACgFAEgEQADgEAGgDQAFgCAGAAQAHABAGACQAFACAEAEQADAEABAGQACAFAAAHQAAAHgCAGQgCAGgDAEQgEADgFADQgFACgHAAQgHgBgFgCgAsgCoQgFAFAAALIABAIIADAHIAFAFQAEACAEAAQARAAAAgWIgBgIIgCgHIgGgFQgDgCgFAAQgIAAgEAGgA1NDUQgEgCgEgEQgEgEgBgGQgCgGAAgGQAAgHACgGQACgFADgEQAEgEAFgDQAFgCAHAAQAHABAGACQAFACAEAEQADAEABAGQACAFABAHQgBAHgCAGQgCAGgDAEQgDADgGADQgFACgHAAQgHgBgGgCgA1NCoQgEAFAAALIABAIIADAHIAFAFQADACAFAAQASAAgBgWIgBgIIgCgHIgGgFQgDgCgFAAQgIAAgFAGgAgVDVQgDgCgCgCIgEgEQgBgEgBgDQAAgFACgEQADgEADgCIAIgDIAJgBIAGAAIACAAIADABIACAAIABgDIAAgEIgCgEIgCgEIgDgCIgGgBIgEABIgGABIgFABIgEADIgCgJQAJgFAPAAQAFAAAFACQAEACACACIADAGIABAGIgBAMIAAAOIAAAIIABAHIgHAAIgDgIIgBAAIgDACIgDAEIgGACIgHABQgEAAgEgBgAgQC8QgFADAAAGQAAAEAEACQACACAGABIAGgBIAEgDIADgDIACgDIAAgJIgCAAIgDgBIgCAAIgFAAQgHAAgDACgAkxDWIgRglIgCgLIgTAwIgFAAIgWg7IALAAIAMAhIACALIACAAIADgLIAMghIAIAAIAPAiIACAKIABAAIADgLIALghIAKAAIgWA7gAmNDWIgRglIgDgLIgTAwIgEAAIgXg7IAMAAIAMAhIACALIABAAIADgLIANghIAIAAIAOAiIADAKIABAAIACgLIALghIAKAAIgVA7gAnqDWIgRglIgCgLIgTAwIgFAAIgWg7IALAAIAMAhIADALIAAAAIADgLIAOghIAIAAIANAiIAEAKIABAAIACgLIAKghIAKAAIgUA7gAuWDVQgEgCgCgCIgDgEQgCgEAAgDQAAgFACgEQACgEADgCIAIgDIAJgBIAGAAIAEAAIADABIACAAIAAgDIAAgEIgBgEIgCgEIgEgCIgGgBIgEABIgGABIgFABIgEADIgDgJQAKgFAPAAQAGAAAEACQAEACADACIADAGIAAAGIAAAMIgBAOIABAIIAAAHIgHAAIgCgIIgBAAIgEACIgEAEIgFACIgHABQgFAAgDgBgAuSC8QgFADABAGQgBAEAEACQADACAFABIAHgBIAEgDIAEgDIACgDIAAgJIgCAAIgDgBIgDAAIgGAAQgGAAgEACgAvSDWIgIgDIADgIIAHACIAJABQAPAAAAgKQAAgEgDgDQgEgBgJAAIgHAAIAAgIIAJAAIAFgBIADgCIAEgDIABgDQgBgFgDgCQgDgBgIAAIgJABIgGACIgDgHQAIgFAOAAQAKAAAFAEQAGADAAAIIgBADIgCAEIgEAEIgEABIAAACQAHABADAEQADAEAAAFIgCAHQgBADgEACIgIAEIgMABIgKAAgAyZDVQgDgCgCgCIgEgEQgCgEABgDQAAgFABgEQADgEADgCIAIgDIAIgBIAGAAIAFAAIACABIACAAIAAgDIAAgEIgBgEIgBgEIgFgCIgFgBIgFABIgFABIgGABIgDADIgEgJQAKgFAPAAQAHAAADACQAEACADACIADAGIAAAGIAAAMIgBAOIABAIIABAHIgHAAIgDgIIgBAAIgDACIgEAEIgFACIgIABQgEAAgEgBgAyVC8QgEADAAAGQAAAEADACQAEACAEABIAHgBIAEgDIAEgDIACgDIAAgJIgCAAIgCgBIgEAAIgFAAQgHAAgEACgAHKDVIAAghIAAgIIgDgFQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBgBIgGgBQgHABgDADQgDADgCAHIAAAlIgKAAIAAggIgBgIIgCgFQgBgDgCgBQgCgBgFgBQgFABgEADQgEADgBAFIAAAnIgLAAIAAg6IAHAAIACAIIABAAQADgEAFgDQAFgDAHAAQAGABAEACQAEADACAFQADgEAFgEQAFgDAHAAQAFABAEABQADABACADQADADABAFIABANIAAAhgABoDVIAAgJIAQAAIAAgzIACgHIgFAGIgNAIIgEgHIAagSIAFAAIAABFIAQAAIAAAJgAAmDVIAAgJIARAAIAAgzIABgHIgEAGIgOAIIgEgHIAbgSIAEAAIAABFIARAAIAAAJgAhlDVIAAggIgBgIIgCgGIgEgEIgHgBIgGABIgEADIgFAFIgCAFIAAAlIgKAAIAAhNIAKAAIAAAaIABAAQAEgDAEgDQAFgCAHgBQAFABAEABQAEABACADQADADABAEQACAGAAAHIAAAigAtTDVIAAgxIgUAAIAAgJIAzAAIAAAJIgVAAIAAAxgAvzDVIAAghIACgLIgCAAIgFALIgbAhIgIAAIAAg6IAKAAIAAAiIgBAKIABAAIAGgKIAbgiIAHAAIAAA6gAw4DVIAAgZIgdAAIAAAZIgLAAIAAg6IALAAIAAAYIAdAAIAAgYIAKAAIAAA6gAzODVIAAg6IAlAAIAAAJIgbAAIAAAxgApcCpQgDgCAAgDQAAgDADgCQABgCAEAAQADAAACACQACACAAADQAAADgCACQgCACgDAAQgEAAgBgCgA1ZBwIACgJIACABIAFgBIADgCIADgDIACgHIgZg6IALAAIASAwIACAAIACgMIANgkIAKAAIgTA0IgEALIgFAJQgDADgDACQgDADgEAAIgHgBgAj0BwIAAhPIAHAAIACAHIABAAQADgEAFgCQAEgDAHAAQAMAAAGAHQAGAHAAAQQAAAHgCAFQgCAHgDADQgEAFgGACQgGACgGAAIgEAAIgEgBIgDgBIgCAAIAAAWgAjlArQgDADgBAHIAAAbIAEACIAIABQAJAAAGgFQAEgGAAgLQAAgKgDgGQgEgFgJgBQgGAAgFAEgAqeBwIAAhPIAHAAIACAHIABAAQADgEAEgCQAGgDAFAAQANAAAGAHQAGAHAAAQQAAAHgCAFQgCAHgEADQgEAFgFACQgGACgGAAIgEAAIgEgBIgCgBIgEAAIAAAWgAqPArQgDADgCAHIAAAbIAFACIAJABQAJAAAEgFQAGgGgBgLQAAgKgDgGQgEgFgJgBQgHAAgEAEgAtgBmQAEgBACgDQACgEAAgDQgDABgCgCQgDgBABgEQAAgDABgBQACgCAEAAQAEAAACACQADADAAAFQAAAEgCADIgDAFIgEAEIgFACgAIzBpIgCgPIgxAAIAAg5IALAAIAAAxIAbAAIAAgxIAKAAIAAAxIAJAAIAAAXgABHBpIgCgPIgxAAIgCAPIgHAAIAAgXIAIAAIACgEIAEgKIADgOIABgVIAnAAIAAAxIAJAAIAAAXgAAlA0IgBALIgDAKIgEAJIAdAAIAAgoIgUAAIgBAKgAnnBpIgCgPIgxAAIgCAPIgHAAIAAgXIAIAAIACgEIAEgKIADgOIABgVIAnAAIAAAxIAJAAIAAAXgAoIA0IgCALIgDAKIgEAJIAdAAIAAgoIgUAAIAAAKgAOiBaQgFgCgDgEQgDgEgCgGQgCgGAAgGQAAgPAHgIQAIgIAOAAIAIABQAEABADADQAEACACAFQACAEAAAHIAAAEIgBAFIgoAAQAAAKAEAGQAFAEALAAIAJgBQAEgCADgCIADAIQgEACgGACQgFACgHAAQgHAAgGgCgAOjAsQgFADAAAIIAfAAQABgIgEgDQgEgFgGAAQgJAAgEAFgANhBaQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAIgIANAAIAJABQAEABADADQAEACACAFQADAEgBAHIAAAEIgBAFIgpAAQABAKAEAGQAFAEALAAIAJgBQAEgCACgCIAEAIQgEACgFACQgGACgHAAQgHAAgGgCgANiAsQgFADAAAIIAfAAQABgIgEgDQgEgFgHAAQgHAAgFAFgABmBaQgGgCgDgEQgDgEgBgGQgCgGgBgGQAAgPAIgIQAHgIAOAAIAJABQAEABADADQADACACAFQADAEAAAHIgBAEIAAAFIgpAAQAAAKAFAGQAEAEAMAAIAJgBQADgCADgCIADAIQgDACgGACQgGACgGAAQgIAAgFgCgABmAsQgEADAAAIIAfAAQABgIgEgDQgFgFgGAAQgIAAgFAFgAgdBaQgFgCgDgEQgEgEgCgGQgBgGAAgGQAAgPAHgIQAHgIAOAAIAJABQADABAEADQACACACAFQADAEAAAHIAAAEIgBAFIgoAAQAAAKAFAGQAEAEALAAIAJgBQAFgCABgCIADAIQgDACgFACQgGACgGAAQgIAAgFgCgAgcAsQgFADgBAIIAgAAQAAgIgEgDQgDgFgHAAQgIAAgEAFgAiiBaQgFgCgDgFQgEgDgCgHQgCgFAAgGQAAgIACgFQACgGAEgEQAEgEAFgCQAFgCAHAAQAHAAAFADQAFACAEAEQADAEACAFQACAGAAAHQAAAGgCAGQgCAGgEAEQgDAEgGACQgFACgGAAQgHAAgGgCgAiiAtQgEAGgBALIABAIIAEAGIAEAFQAEACAFAAQARAAAAgVIgBgIIgDgIIgFgEQgEgDgEAAQgIAAgFAGgAmNBaQgFgCgDgEQgEgEgCgGQgBgGAAgGQAAgPAHgIQAHgIAOAAIAIABQAEABAEADQAEACABAFQADAEAAAHIAAAEIgBAFIgpAAQAAAKAFAGQAFAEAKAAIAJgBQAEgCADgCIADAIQgDACgGACQgGACgHAAQgGAAgGgCgAmMAsQgFADgBAIIAgAAQABgIgFgDQgEgFgGAAQgIAAgEAFgArXBaQgFgCgEgFQgDgDgCgHQgCgFAAgGQAAgIACgFQADgGADgEQADgEAGgCQAFgCAHAAQAHAAAFADQAGACADAEQADAEACAFQACAGAAAHQAAAGgCAGQgCAGgDAEQgEAEgFACQgGACgGAAQgIAAgFgCgArXAtQgFAGAAALIACAIIADAGIAEAFQAEACAFAAQARAAAAgVIgBgIIgDgIIgFgEQgDgDgFAAQgIAAgFAGgAybBaQgFgCgDgFQgEgDgCgHQgCgFAAgGQAAgIACgFQACgGAEgEQAEgEAFgCQAFgCAHAAQAHAAAFADQAFACAEAEQADAEACAFQACAGAAAHQAAAGgCAGQgCAGgEAEQgDAEgGACQgFACgGAAQgHAAgGgCgAybAtQgEAGgBALIABAIIAEAGIAEAFQAEACAFAAQARAAAAgVIgBgIIgDgIIgFgEQgEgDgEAAQgIAAgFAGgA0UBaQgFgCgEgFQgDgDgBgGQgBgGAAgGQAAgPAGgIQAIgIANAAIAKABIAIADIgDAIIgGgDIgHgBQgSAAAAAXIAAAIIADAGIAGAFQAEACAFAAQAFABADgCIAGgDIADAIQgDADgGAAQgFACgFAAQgIAAgFgCgAGLBaQgEgBgCgCIgDgFQgCgDAAgEQAAgFACgEQACgDADgCIAIgEIAJgBIAGAAIAEAAIADABIACAAIAAgDIAAgDIgBgFIgCgDIgEgCIgGgBIgEAAIgGACIgFABIgEACIgDgJQAKgEAPgBQAGABAEACQAEABADACIADAHIAAAGIAAAMIgBANIABAIIAAAHIgHAAIgCgIIgBAAIgEADIgEAEIgFABIgHABQgFABgDgCgAGPBBQgFADABAGQgBAFAEACQADACAFAAIAHgBIAEgCIAEgEIACgDIAAgJIgCAAIgDgBIgDAAIgGAAQgGAAgEACgAhfBbIgJgBIAAAAIgBAAIAAg5IAFAAIAHgBIAJgBQAOABAFAEQAFADAAAHQABAEgDAEQgDADgFADIAAABQAGABAEADQADAEAAAFQAAAJgHAEQgHAEgPAAIgJAAgAhfBSIAFABIAFAAQAJAAAFgCQADgDAAgFIgBgDIgCgEIgFgBIgIgBIgLAAgAhfA5IANAAIAEgBIAFgCIACgCIABgEQAAgFgDgBQgDgCgIAAIgEAAIgHAAgAxYBbIgJgBIAAAAIgBAAIAAg5IAFAAIAHgBIAJgBQAOABAFAEQAFADAAAHQABAEgDAEQgDADgFADIAAABQAGABAEADQADAEAAAFQAAAJgHAEQgHAEgPAAIgJAAgAxYBSIAFABIAFAAQAJAAAFgCQADgDAAgFIgBgDIgCgEIgFgBIgIgBIgLAAgAxYA5IANAAIAEgBIAFgCIACgCIABgEQAAgFgDgBQgDgCgIAAIgEAAIgHAAgAzuBbIgDgBIABgJIAEAAQACAAACgCQACgBACgGIADgPIABgYIAmAAIAAA5IgKAAIAAgwIgTAAIAAADIgCATQgBAJgCAGQgCAGgDADQgEADgFAAIgEAAgAMYBaIAAghIABgLIAAAAIgGALIgbAhIgIAAIAAg5IALAAIAAAiIgCAKIACAAIAFgKIAagiIAIAAIAAA5gAKzBaIAAghIACgLIgBAAIgGALIgbAhIgIAAIAAg5IAKAAIAAAiIgBAKIABAAIAGgKIAbgiIAHAAIAAA5gAJuBaIAAghIABgLIgBAAIgGALIgbAhIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA5gAHpBaIgUgaIgHAAIAAAaIgKAAIAAg5IAKAAIAAAaIAHgCIATgYIALAAIgTAWIgFAFIAGAEIAVAagAFIBaIAAgXIgLACIgQAVIgMAAIAOgSIAGgFQgHAAgFgFQgFgEAAgHQAAgFADgEQABgEAEgCQAEgCAFgBQAFgCAGAAIAJAAIAJACIAAA5gAEzArQgDACAAAGQgBAGAFACQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgJAAgEADgAEIBaIAAghIABgLIgBAAIgFALIgbAhIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAFgKIAagiIAIAAIAAA5gADDBaIAAgZIgdAAIAAAZIgLAAIAAg5IALAAIAAAXIAdAAIAAgXIAKAAIAAA5gAkSBaIAAgwIgcAAIAAAwIgKAAIAAg5IAxAAIAAA5gAmvBaIgVgaIgGAAIAAAaIgKAAIAAg5IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAFIAHAEIAUAagAo2BaIAAgXIgKACIgRAVIgNAAIAPgSIAGgFQgHAAgFgFQgEgEAAgHQAAgFABgEQACgEAEgCQAEgCAFgBQAGgCAFAAIAJAAIAJACIAAA5gApKArQgFACAAAGQABAGAEACQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgIAAgEADgAsBBaIAAgwIgcAAIAAAwIgLAAIAAg5IAxAAIAAA5gAt2BaIgMgQIgFgIIgEAIIgNAQIgMAAIAXgdIgVgcIANAAIALAOIAEAIIAEgIIAMgOIAMAAIgWAcIALAOIAMAPgAu6BaIAAgXIgLACIgQAVIgNAAIAPgSIAGgFQgIAAgFgFQgEgEAAgHQAAgFACgEQACgEAEgCQADgCAGgBQAFgCAGAAIAJAAIAJACIAAA5gAvPArQgEACAAAGQAAAGAEACQAFADAJAAIAHAAIAAgWIgFAAIgDAAQgJAAgEADgAv6BaIAAghIABgLIgBAAIgGALIgbAhIgIAAIAAg5IALAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA5gAO1AZQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBABAAQAAgBAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAAAQAAABABAAQAAABAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBgBAAgAOeAZQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABQABAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAMlgJIAAhQIAHAAIACAIIABAAQADgFAFgCQAFgDAGABQAMgBAHAIQAFAGAAAQQAAAHgCAGQgCAGgDAEQgEAEgGACQgFACgHABIgDAAIgEgBIgDgBIgDgBIAAAXgAM1hPQgEAEgBAGIAAAbIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgKgEgFQgDgGgKAAQgGAAgEADgAKlgJIAAgWIgEACIgFAAQgLAAgHgIQgFgHgBgQQABgOAGgIQAHgIANAAIADAAIADABIAAgTIAKAAIAAATIAFgBIADAAQANAAAGAHQAGAHABAPQgBAHgBAGIgFAKQgEAEgEACQgFADgGAAIgDAAIgFgCIAAAWgAKvhRIAAArIAEABIADAAQAIgBAEgGQAEgGAAgLIAAgJQgCgDgCgDQgCgDgDgBIgIgBIgCAAIgEAAgAKThNQgEAGAAALIABAJIACAHQADADADABQADADAEAAIADAAIAEgBIAAgrIgDAAIgEAAQgHAAgFAEgABKgJIAAhQIAHAAIACAIIABAAQADgFAEgCQAFgDAGABQANgBAGAIQAGAGAAAQQAAAHgCAGQgCAGgEAEQgDAEgGACQgFACgHABIgEAAIgDgBIgDgBIgEgBIAAAXgABahPQgEAEgCAGIAAAbIAGADIAIABQAIAAAFgGQAGgGAAgLQAAgKgFgFQgDgGgJAAQgGAAgEADgAt+gJIAAhQIAHAAIACAIIACAAQADgFAEgCQAFgDAGABQAMgBAHAIQAFAGAAAQQAAAHgCAGQgCAGgDAEQgEAEgGACQgFACgHABIgDAAIgEgBIgDgBIgDgBIAAAXgAtuhPQgEAEgBAGIAAAbIAFADIAIABQAJAAAFgGQAFgGAAgLQAAgKgEgFQgDgGgKAAQgGAAgEADgAQwgRIgCgOIgxAAIAAg6IAKAAIAAAxIAcAAIAAgxIAKAAIAAAxIAKAAIAAAXgAA3gRIgBgOIgyAAIgCAOIgFAAIAAgXIAGAAIADgEIAEgJIACgPIACgVIAnAAIAAAxIAJAAIAAAXgAAWhGIgCALIgCALIgEAIIAdAAIAAgoIgUAAIgBAKgAkWgRIgBgOIgyAAIgCAOIgGAAIAAgXIAHAAIADgEIAEgJIACgPIACgVIAnAAIAAAxIAJAAIAAAXgAk3hGIgCALIgCALIgEAIIAcAAIAAgoIgTAAIgBAKgAUxgmQgHgJAAgSIABgRQABgGACgGQADgEADgCQACgEAFgBIAHgCIAKgBIALgBQADAAACgDIABAJIgGADIgMABIgKABIgGADQgEACgBAFQgDAEAAAGIABABQAEgGAGgCQAEgCAIAAQALAAAHAHQAGAGABAOQAAAHgCAHQgCAFgEAEQgEADgFACQgFACgGABQgPAAgHgJgAU5hJQgEAFAAAJIABAIIADAHIAGAEQACACAFAAQASAAAAgVIgBgIIgEgGQgBgCgDgCQgDgBgFgBQgJAAgFAGgAT0ggQgGgCgDgEQgDgEgCgGQgCgFAAgHQAAgHACgFQACgHAEgDQADgEAGgDQAFgBAGAAQAIgBAEADQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAGQgCAGgDAEQgEADgFACQgFACgHABQgHAAgFgDgAT0hNQgFAGAAALIABAIIADAHIAFAFQAEACAEAAQARAAAAgWIAAgIIgDgHIgFgFQgEgCgFAAQgIAAgEAFgALsggQgEgCgEgEQgEgEgBgGQgCgFAAgHQAAgHACgFQACgHADgDQAEgEAFgDQAFgBAHAAQAHgBAGADQAFACAEAFQADAEABAFQACAGABAGQgBAHgCAGQgCAGgDAEQgDADgGACQgFACgHABQgHAAgGgDgALshNQgEAGAAALIABAIIADAHIAFAFQADACAFAAQASAAgBgWIgBgIIgCgHIgGgFQgDgCgFAAQgIAAgFAFgADZgmQgHgJAAgSIABgRQABgGADgGQACgEADgCQADgEAEgBIAIgCIAJgBIALgBQADAAADgDIABAJIgHADIgLABIgKABIgHADQgDACgCAFQgCAEgBAGIABABQAEgGAGgCQAFgCAIAAQALAAAHAHQAGAGAAAOQAAAHgCAHQgCAFgDAEQgFADgEACQgGACgGABQgOAAgIgJgADihJQgFAFAAAJIACAIIADAHIAFAEQADACAEAAQASAAAAgVIgBgIIgDgGQgCgCgDgCQgDgBgEgBQgKAAgEAGgACcggQgFgCgEgEQgDgEgBgGQgCgFgBgHQABgHACgFQACgHADgDQADgEAGgDQAFgBAHAAQAHgBAFADQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAGQgCAGgDAEQgEADgFACQgFACgHABQgHAAgGgDgACchNQgFAGABALIABAIIACAHIAGAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAFgAgyggQgFgCgEgEQgDgEgBgGQgCgFgBgHQABgHACgFQACgHADgDQADgEAGgDQAFgBAHAAQAHgBAFADQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAGQgCAGgDAEQgEADgFACQgFACgHABQgHAAgGgDgAgyhNQgFAGABALIABAIIACAHIAGAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAFgAjFggQgCgCAAgCQAAgEACgCQACgCADAAQADAAACACQACACAAAEQAAACgCACQgCACgDABQgDgBgCgCgAmAggQgFgCgEgEQgDgEgBgGQgDgFAAgHQAAgHADgFQABgHAEgDQADgEAGgDQAFgBAHAAQAHgBAFADQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAGQgCAGgDAEQgEADgFACQgGACgGABQgIAAgFgDgAmAhNQgFAGABALIABAIIACAHIAGAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAFgAqNghQgFgCgEgGQgDgEgBgIQgCgHAAgKQAAgSAHgLQAHgKAOAAQAOAAAHAKQAHAKAAATQgBAUgGAKQgIALgNAAQgIgBgFgDgAqOhdQgDAIAAAPIABANIACAKQACAEAEACQADACAFABQAIAAAEgIQAFgIAAgQIgBgMIgDgJQgCgFgEgCQgDgCgEAAQgKgBgEAIgAu/gmQgHgJAAgSIABgRQABgGADgGQABgEADgCQAEgEADgBIAIgCIAKgBIAKgBQAEAAACgDIABAJIgGADIgMABIgKABIgHADQgCACgCAFQgCAEgBAGIABABQAEgGAGgCQAFgCAHAAQAMAAAGAHQAHAGAAAOQAAAHgDAHQgBAFgEAEQgEADgFACQgFACgGABQgPAAgHgJgAu3hJQgEAFAAAJIABAIIADAHIAGAEQADACAEAAQARAAAAgVIgBgIIgDgGQgBgCgEgCQgDgBgDgBQgLAAgEAGgAyqggQgFgCgEgEQgDgEgBgGQgDgFAAgHQAAgHADgFQABgHAEgDQADgEAGgDQAFgBAHAAQAHgBAFADQAGACADAFQAEAEABAFQACAGAAAGQAAAHgCAGQgCAGgDAEQgEADgFACQgGACgGABQgIAAgFgDgAyqhNQgFAGABALIABAIIACAHIAGAFQADACAFAAQARAAAAgWIgBgIIgDgHIgFgFQgEgCgEAAQgJAAgEAFgA0NghQgFgCgEgGQgDgEgBgIQgCgHAAgKQAAgSAHgLQAHgKANAAQAPAAAHAKQAHAKAAATQgBAUgGAKQgIALgOAAQgGgBgGgDgA0OhdQgDAIAAAPIABANIACAKQADAEADACQADACAEABQAKAAAEgIQAEgIAAgQIgBgMIgDgJQgCgFgEgCQgCgCgGAAQgIgBgFAIgA1QgfIgIgCIACgJIAHACIAJACIAHgCIAGgDQACgCACgCQABgDAAgDQAAgIgFgDQgFgEgIAAIgJAAIAAgEIARgXIAFgEIgfAAIAAgJIAsAAIAAAEIgUAZIgEADIAEAAQAFAAAEACQAEABADADIAFAHQABADABAGQgBAGgCAEQgCAFgEADQgEAEgFABQgFACgGAAIgKgCgAPEggQgEgBgCgCIgDgFQgCgDAAgDQAAgGACgDQACgDAEgDIAHgDIAJgBIAGAAIAEAAIADABIABAAIABgEIAAgDIgBgFIgCgDIgEgBIgGgBIgFAAIgFABIgFABIgEACIgDgIQAKgFAPAAQAGAAAEACQAEACADACIACAGIABAHIgBALIAAAOIAAAIIABAHIgHAAIgDgJIgBAAIgCAEIgFADIgFACIgHABQgFAAgDgCgAPIg4QgEACAAAHQAAAEADACQADADAFAAIAHgCIAEgCIAEgDIABgEIAAgIIgBgBIgDAAIgEAAIgEAAQgIAAgDACgAFmggQgDgBgDgCIgDgFQgCgDAAgDQAAgGACgDQACgDADgDIAIgDIAJgBIAGAAIAEAAIACABIADAAIAAgEIAAgDIgBgFIgCgDIgEgBIgGgBIgEAAIgGABIgFABIgEACIgDgIQAKgFAPAAQAGAAAEACQAEACACACIAEAGIAAAHIAAALIgBAOIABAIIABAHIgIAAIgCgJIgBAAIgEAEIgDADIgGACIgIABQgEAAgDgCgAFqg4QgFACABAHQAAAEADACQADADAFAAIAHgCIAEgCIADgDIADgEIAAgIIgDgBIgCAAIgDAAIgGAAQgGAAgEACgAj8ggQgEgBgCgCIgEgFQgCgDAAgDQABgGACgDQACgDADgDIAIgDIAIgBIAHAAIADAAIADABIACAAIABgEIAAgDIgBgFIgDgDIgEgBIgGgBIgEAAIgGABIgEABIgFACIgCgIQAKgFAOAAQAGAAAFACQAEACACACIADAGIABAHIgBALIAAAOIAAAIIABAHIgHAAIgDgJIgBAAIgDAEIgEADIgGACIgHABQgEAAgDgCgAj5g4QgEACAAAHQAAAEADACQAEADAFAAIAGgCIAEgCIAEgDIACgEIAAgIIgCgBIgDAAIgDAAIgFAAQgHAAgEACgASrgfIAAgXIgLABIgQAWIgNAAIAPgTIAFgEQgHgBgFgFQgEgEAAgHQAAgEACgFQACgEADgCQAFgCAEgBQAGgCAGABIAJAAIAJABIAAA6gASWhPQgEADAAAFQAAAGAEADQAGADAIgBIAHAAIAAgVIgFAAIgDAAQgJgBgEADgARqgfIAAghIACgMIgBAAIgFAMIgbAhIgJAAIAAg6IALAAIAAAjIgBAKIABAAIAGgKIAagjIAIAAIAAA6gAOggfIABgtIgBAAIgFAJIgPAXIgDAAIgQgXIgFgJIgBAAIABAMIAAAhIgJAAIAAg6IAKAAIASAaIAEAIIAVgiIAKAAIAAA6gAJrgfIAAgZIgdAAIAAAZIgLAAIAAg6IALAAIAAAYIAdAAIAAgYIAKAAIAAA6gAImgfIAAghIABgMIgBAAIgFAMIgbAhIgIAAIAAg6IALAAIAAAjIgBAKIABAAIAFgKIAagjIAIAAIAAA6gAHCgfIAAgXIgLABIgQAWIgNAAIAOgTIAHgEQgIgBgFgFQgEgEAAgHQAAgEACgFQACgEAEgCQADgCAGgBQAFgCAGABIAJAAIAJABIAAA6gAGthPQgEADAAAFQAAAGAFADQAEADAIgBIAIAAIAAgVIgFAAIgDAAQgJgBgEADgAFDgfIAAgZIgeAAIAAAZIgKAAIAAg6IAKAAIAAAYIAeAAIAAgYIAKAAIAAA6gAhdgfIAAhDIglAAIAABDIgLAAIAAhNIA8AAIAABNgAm5gfIAAg6IAlAAIAAAJIgbAAIAAAxgAoRgfIAdg/IAGgFIgIABIghAAIAAgKIAzAAIAAADIgjBKgApTgfIAAgJIAQAAIAAgzIACgHIgFAGIgNAIIgFgGIAbgTIAFAAIAABFIAQAAIAAAJgArcgfIAAgEIAHgGIAHgJIAJgJIAHgKIAEgKQACgFAAgEQAAgGgDgDQgDgDgHAAIgJACIgHAEIgEgHIAKgGQAGgCAGAAQALgBAFAGQAGAGABAIQAAAGgDAFIgGAMIgIAMIgJALIgHAEIAAABIAIgBIAaAAIAAAJgAsWgfIAAgXIgKABIgRAWIgMAAIAOgTIAHgEQgIgBgEgFQgFgEAAgHQAAgEACgFQACgEAEgCQAEgCAFgBQAFgCAGABIAJAAIAIABIAAA6gAsqhPQgEADAAAFQAAAGAFADQAFADAHgBIAHAAIAAgVIgDAAIgFAAQgIgBgEADgAvhgfIAAgXIgKABIgRAWIgMAAIAPgTIAFgEQgHgBgFgFQgEgEAAgHQAAgEACgFQACgEADgCQAFgCAEgBQAGgCAGABIAJAAIAJABIAAA6gAv1hPQgEADAAAFQAAAGAEADQAGADAIgBIAGAAIAAgVIgEAAIgDAAQgJgBgEADgAwrgfIAAgxIgUAAIAAgJIAzAAIAAAJIgVAAIAAAxgAxMgfIgVgaIgFAAIAAAaIgLAAIAAg6IALAAIAAAbIAFgCIAUgZIALAAIgSAWIgGAFIAHAFIAUAagAQ5iEIAAhPIAHAAIACAHIABAAQADgEAFgDQAFgCAFAAQANAAAGAHQAGAHAAAPQAAAHgCAHQgCAFgEAEQgDAEgGADQgFACgHAAIgEAAIgDAAIgEgBIgDgBIAAAWgARJjJQgEAEgCAGIAAAbIAGADIAIAAQAIABAFgHQAFgFABgMQAAgJgFgFQgDgHgJAAQgGABgEADgAnbiEIAAhPIAIAAIABAHIABAAQADgEAFgDQAFgCAGAAQANAAAFAHQAHAHAAAPQAAAHgCAHQgCAFgEAEQgEAEgGADQgFACgGAAIgFAAIgDAAIgDgBIgDgBIAAAWgAnLjJQgDAEgCAGIAAAbIAFADIAIAAQAJABAFgHQAFgFAAgMQAAgJgEgFQgDgHgJAAQgHABgEADgAtLiEIAAhPIAIAAIABAHIABAAQADgEAFgDQAFgCAGAAQANAAAFAHQAHAHgBAPQAAAHgBAHQgCAFgEAEQgEAEgGADQgFACgGAAIgFAAIgDAAIgDgBIgDgBIAAAWgAs7jJQgDAEgCAGIAAAbIAFADIAIAAQAJABAFgHQAFgFAAgMQAAgJgEgFQgDgHgKAAQgGABgEADgAFNiLIgCgOIgyAAIAAg6IALAAIAAAxIAbAAIAAgxIAKAAIAAAxIAKAAIAAAXgAifiLIgBgOIgyAAIgCAOIgGAAIAAgXIAHAAIADgFIADgJIADgOIACgVIAnAAIAAAxIAJAAIAAAXgAjAjAIgCALIgCALIgEAIIAdAAIAAgpIgUAAIgBALgAxciLIgDgOIgxAAIAAg6IALAAIAAAxIAbAAIAAgxIAKAAIAAAxIAKAAIAAAXgAUuiaQgFgCgEgFQgDgEgBgFQgCgGgBgGQABgIACgFQACgGADgEQADgDAGgDQAFgCAHAAQAHAAAFACQAGADADAEQAEAEABAFQACAGAAAHQAAAHgCAFQgCAGgDAEQgEAEgFACQgFACgHAAQgHAAgGgCgAUujHQgFAGABALIABAHIACAHIAGAGQADABAFAAQARAAAAgVIgBgIIgDgHIgFgGQgEgCgEAAQgJABgEAFgAP4ihQgIgIABgTIAAgRQACgGACgFQACgEADgDQADgDAEgBIAIgDIAKgBIAKgBQAEAAACgCIABAJIgGACIgMABIgKACIgHADQgDACgCAEQgCAFAAAGIAAABQAEgGAGgCQAFgCAHAAQAMgBAGAHQAHAHAAAOQAAAHgCAGQgCAGgEADQgDAEgGACQgFACgGAAQgPAAgGgJgAQAjEQgEAGgBAJIABAIIAEAGIAFAFQADABAEAAQASAAAAgUIgBgIIgDgHQgBgCgEgBQgDgCgEAAQgKAAgEAFgAMHiaQgFgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAIgIANAAIAJABQAEABADADQAEACACAEQADAFgBAIIAAADIgBAFIgpAAQABAKAEAFQAFAGALgBIAJgBQAEgCACgCIAEAIQgEADgFACQgGABgHAAQgHAAgGgCgAMIjIQgFADAAAJIAfAAQABgJgEgDQgEgFgHAAQgHAAgFAFgALPiaQgFgDgDgEQgDgDgCgGQgBgGgBgGQAAgPAIgIQAHgIANAAIAKABIAIADIgCAIIgHgDIgIgBQgSAAAAAXIABAIIAEAGIAFAGQAEABAFAAQAFAAADgBIAGgDIADAHQgDAEgGABQgFABgGAAQgHAAgFgCgAIViaQgFgDgEgEQgDgDgBgGQgCgGAAgGQABgPAGgIQAIgIANAAIAKABIAIADIgDAIIgGgDIgHgBQgTAAABAXIABAIIACAGIAHAGQADABAFAAQAFAAADgBIAGgDIADAHQgDAEgGABQgFABgGAAQgHAAgFgCgAh/iaQgGgCgDgEQgDgEgCgGQgCgGAAgGQAAgPAIgIQAGgIAOAAIAJABQAEABAEADQADACACAEQADAFAAAIIgBADIAAAFIgqAAQAAAKAGAFQAEAGALgBIAJgBQAEgCACgCIAEAIQgDADgHACQgFABgHAAQgHAAgFgCgAh/jIQgEADgBAJIAgAAQAAgJgEgDQgEgFgHAAQgIAAgEAFgAkDiaQgGgCgDgEQgEgEgBgGQgCgGAAgGQAAgPAHgIQAIgIANAAIAJABQAEABADADQAEACACAEQACAFAAAIIAAADIAAAFIgqAAQABAKAFAFQAEAGALgBIAJgBQAEgCACgCIAEAIQgEADgFACQgGABgHAAQgHAAgFgCgAkDjIQgEADgBAJIAgAAQAAgJgEgDQgEgFgHAAQgHAAgFAFgAmJiaQgEgCgEgFQgEgEgBgFQgCgGAAgGQAAgIACgFQACgGADgEQAEgDAFgDQAGgCAHAAQAHAAAFACQAFADAEAEQADAEABAFQADAGAAAHQAAAHgDAFQgBAGgEAEQgDAEgGACQgFACgGAAQgIAAgGgCgAmJjHQgEAGAAALIABAHIADAHIAFAGQADABAGAAQAQAAAAgVIgBgIIgDgHIgFgGQgDgCgEAAQgJABgFAFgAr5iaQgEgCgEgFQgDgEgCgFQgCgGAAgGQAAgIACgFQACgGADgEQAEgDAFgDQAGgCAHAAQAHAAAEACQAGADADAEQAEAEACAFQACAGAAAHQAAAHgCAFQgDAGgDAEQgDAEgGACQgFACgGAAQgIAAgGgCgAr5jHQgEAGAAALIABAHIADAHIAFAGQADABAGAAQARAAAAgVIgCgIIgDgHIgEgGQgEgCgEAAQgJABgFAFgAt7iaQgHgDgFgEQgFgFgDgIQgDgIAAgKQAAgLADgIQAEgHAFgFQAFgFAHgCQAGgCAGAAIANABIAHACIgCAJQgGgCgLAAQgFAAgEABQgFACgEAEQgDADgCAGQgCAFgBAJQABAIACAFQACAGADADQAEAFAFACQAFACAGAAIAKgBQAEgBACgDIADAJQgEADgFABIgNABQgGAAgHgCgAvHiaQgCgCAAgDQAAgEACgBQACgCAEAAQADAAACACQACABAAAEQAAADgCACQgCACgDAAQgEAAgCgCgACkiaQgDgBgCgCIgEgFQgCgDABgEQAAgFABgEQACgDAEgDIAIgDIAJgBIAFAAIAFAAIACABIACAAIAAgDIAAgDIgBgFIgBgEIgFgBIgFgBIgFAAIgFABIgGACIgDACIgEgIQAKgGAPAAQAGAAAEACQAFACACADIADAGIAAAGIAAAMIgBANIABAIIABAIIgHAAIgDgJIgBAAIgDADIgEAEIgFACIgIABQgEgBgEgBgACpizQgFADAAAGQAAAFADACQAEACAEAAIAHgBIAFgCIADgEIACgDIAAgIIgCgBIgCAAIgEAAIgFAAQgHAAgDABgAlFiZIgJAAIAAAAIgCAAIAAg7IAFAAIAIAAIAJgBQANAAAGAFQAFADAAAHQAAAEgDAEQgDADgFACIAAABQAHACADADQAEAEAAAFQAAAJgIAEQgHAEgOABIgJgBgAlFihIAEAAIAGAAQAJAAAEgCQAEgDAAgEIgBgFIgDgDIgEgBIgIgBIgLAAgAlFi7IAMAAIAFgBIAEgBIACgDIABgEQAAgEgDgCQgCgCgIAAIgFAAIgGAAgAUEiZIAAgyIgcAAIAAAyIgLAAIAAg6IAyAAIAAA6gAShiZIAAgYIgLACIgQAWIgNAAIAPgTIAGgFQgIgBgEgEQgFgFABgGQAAgFACgEQACgEADgCQAEgDAFgBQAFgBAHAAIAJAAIAIACIAAA6gASMjKQgDADAAAGQgBAFAFADQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgIAAgFACgAPWiZIAAgYIgKACIgRAWIgMAAIAOgTIAGgFQgIgBgEgEQgEgFgBgGQAAgFACgEQACgEAEgCQAEgDAFgBQAGgBAFAAIAJAAIAJACIAAA6gAPCjKQgFADAAAGQABAFAEADQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgJAAgDACgAOMiZIAAgyIgUAAIAAgIIAyAAIAAAIIgUAAIAAAygANkiZIAAgaIgdAAIAAAaIgKAAIAAg6IAKAAIAAAXIAdAAIAAgXIAKAAIAAA6gAKAiZIAAgYIglAAIAAgEIAogzIAHAAIAAAuIAPAAIAAAJIgPAAIAAAYgAJ9jRIgQAUIgHAEIAJgBIARAAIAAgVIABgJgAHMiZIAAgiIACgLIgBAAIgGALIgbAiIgHAAIAAg6IAKAAIAAAiIgBAKIABAAIAFgKIAbgiIAHAAIAAA6gAGHiZIAAgiIABgLIgBAAIgFALIgbAiIgIAAIAAg6IAKAAIAAAiIAAAKIAAAAIAGgKIAbgiIAHAAIAAA6gAEDiZIgVgaIgGAAIAAAaIgLAAIAAg6IALAAIAAAaIAGgCIATgYIAMAAIgTAWIgGAEIAHAGIAUAagABiiZIAAgYIgLACIgQAWIgNAAIAPgTIAGgFQgIgBgFgEQgEgFAAgGQAAgFACgEQACgEAEgCQADgDAGgBQAFgBAGAAIAJAAIAJACIAAA6gABNjKQgEADAAAGQAAAFAEADQAFADAJAAIAHAAIAAgWIgFAAIgDAAQgJAAgEACgAAiiZIAAgiIABgLIgBAAIgGALIgbAiIgHAAIAAg6IAKAAIAAAiIgBAKIABAAIAGgKIAagiIAIAAIAAA6gAgiiZIAAgaIgdAAIAAAaIgLAAIAAg6IALAAIAAAXIAdAAIAAgXIAJAAIAAA6gAn4iZIAAgyIgcAAIAAAyIgLAAIAAg6IAyAAIAAA6gApbiZIAAgiIABgLIgBAAIgGALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAbgiIAIAAIAAA6gAqaiZIgVgaIgGAAIAAAaIgKAAIAAg6IAKAAIAAAaIAGgCIAUgYIALAAIgTAWIgGAEIAHAGIAUAagAviiZIAAgYIgLACIgQAWIgMAAIAOgTIAGgFQgHgBgFgEQgFgFAAgGQAAgFADgEQABgEAEgCQAEgDAFgBQAFgBAGAAIAJAAIAJACIAAA6gAv3jKQgDADAAAGQgBAFAFADQAFADAIAAIAHAAIAAgWIgEAAIgEAAQgJAAgEACgAwiiZIAAgiIABgLIgBAAIgFALIgbAiIgIAAIAAg6IALAAIAAAiIgBAKIABAAIAFgKIAagiIAIAAIAAA6gAyniZIgUgaIgGAAIAAAaIgLAAIAAg6IALAAIAAAaIAGgCIATgYIAMAAIgTAWIgGAEIAHAGIAVAagAzhiZIgJgUIgeAAIgIAUIgLAAIAfhPIAGAAIAgBPgAz8jNIgJAWIAYAAIgJgWIgDgLgA1LjPIgCgHIgCAHIgEAEIgGgDIADgFIAGgEIgHABIgHAAIAAgHIAHAAIAHACIgGgFIgCgGIAFgDIAEAEIACAHIACgGIADgFIAFADIgCAGIgGAFIAIgCIAGAAIAAAHIgGAAIgHgBIAGAFIACAEIgGAEg");
	this.shape_1.setTransform(26.2,64.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.hjkkk, new cjs.Rectangle(-269.8,-93.6,433.8,181.1), null);


(lib.dfgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgiBFIAAiJIBEAAIAAAOIg0AAIAAAtIAxAAIAAANIgxAAIAAAzIA1AAIAAAOg");
	this.shape.setTransform(48.6,-1.7,1.176,1.176);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAQAAIAAA7IASAAQArAAAAAnQAAAngpAAgAgoA3IARAAQAOAAAHgFQAHgGAAgOQAAgPgIgGQgHgFgSAAIgMAAg");
	this.shape_1.setTransform(34.5,-1.7,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaBFIAAhBIg0AAIAABBIgOAAIAAiJIAOAAIAAA7IA0AAIAAg7IAQAAIAACJg");
	this.shape_2.setTransform(19.5,-1.7,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAnBVIAAggIhNAAIAAAgIgPAAIAAguIAJAAQAJgPADgWQADgQAAgjIAAgjIBIAAIAAB7IALAAIAAAugAgOgiQAAAugNAbIA3AAIAAhtIgqAAg");
	this.shape_3.setTransform(6.2,0.2,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglAyQgHgQAAgiQAAhHAsAAQAbAAALAYQAIARAAAeQAAAigIAQQgKAWgcAAQgaAAgLgWgAgdgCQAAAfAGANQAHAQAQAAQARAAAHgQQAFgNABgfQAAgagHgNQgGgQgRAAQgdAAAAA3g");
	this.shape_4.setTransform(-7.2,-1.6,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAdBFIgdg6IgdA6IgRAAIAmhGIglhDIARAAIAcA2IAdg2IARAAIglBDIAmBGg");
	this.shape_5.setTransform(-19.7,-1.7,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAqBFIAAiJIAPAAIAACJgAg4BFIAAiJIAPAAIAAA7IATAAQArAAAAAnQAAAngoAAgAgpA3IASAAQAPAAAGgFQAHgGAAgOQAAgPgIgGQgHgFgSAAIgNAAg");
	this.shape_6.setTransform(-34,-1.7,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgmBFIAAiJIAkAAQASAAAKAKQAJAJAAAQQAAAYgUAGIAAAAQAKABAHAIQAHAKAAAOQAAAngnAAgAgXA3IAXAAQAXAAAAgaQAAgZgYAAIgWAAgAgXgJIATAAQAXAAAAgXQAAgWgVAAIgVAAg");
	this.shape_7.setTransform(-48.1,-1.7,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.dfgd, new cjs.Rectangle(-52.7,-10.1,105.4,20.3), null);


(lib.dfd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAEATIgEgNIgEAMIgEAJIgMgFIAGgJIAJgJIgMACIgMAAIAAgLIAMAAIANADIgKgJIgGgKIAMgHIAFAJIADAMIAEgMIAGgJIAKAHIgGAJIgKAKIAPgDIAKAAIAAALIgJAAIgPgCIAKAKIAFAIIgKAGg");
	this.shape.setTransform(74,-11.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPBhIAAgiIAfAAIAAAigAgJAvIgGg+IAAhRIAfAAIAABRIgEA+g");
	this.shape_1.setTransform(65.2,-2.1,1.176,1.176);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBhIgchIIgcBIIgpAAIAvhjIgsheIAqAAIAYA/IAag/IAqAAIgwBeIAyBjg");
	this.shape_2.setTransform(53.6,-2.1,1.176,1.176);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAbBhIAAhKQAAgrAFgXIg1CMIgoAAIAAjBIAjAAIAABJQAAAugFAVIA1iMIAoAAIAADBg");
	this.shape_3.setTransform(36.1,-2.1,1.176,1.176);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag+AjIAAhFQAAhCA+AAQA/AAAABCIAABFQAAAkgRAQQgQAOgeAAQg+AAAAhCgAgYgmIAABPQAAAeAYAAQAZAAAAgeIAAhOQAAgQgGgJQgHgIgMgBQgYABAAAgg");
	this.shape_4.setTransform(18.5,-2,1.176,1.176);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag6BhIAAjBIBDAAQAYAAAMAOQALANAAAUQAAAPgHAMQgHAOgMACQAdAKAAAkQAAAagLAPQgLAQgWAAgAgWBFIAXAAQAUABAAgfQAAgdgUAAIgXAAgAgWgRIAUAAQAWAAAAgaQAAgZgWAAIgUAAg");
	this.shape_5.setTransform(1.6,-2.1,1.176,1.176);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAoB0IAAgmIhPAAIAAAmIgkAAIAAhEIAMAAQAKgXAEgTQAEgXAAgmIAAg9IBtAAIAACkIAMAAIAABEgAgJgqQAAAfgEAVQgEASgJAUIA1AAIAAiGIgkAAg");
	this.shape_6.setTransform(-16.8,0.2,1.176,1.176);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAfBhIgJgyIgpAAIgLAyIgoAAIAxjBIAxAAIArDBgAgOASIAfAAIgPhZg");
	this.shape_7.setTransform(-42.7,-2.1,1.176,1.176);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAYBhIAAhaIgvAAIAABaIglAAIAAjBIAlAAIAABKIAvAAIAAhKIAlAAIAADBg");
	this.shape_8.setTransform(-60,-2.1,1.176,1.176);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.1,-14.3,144.1,28.2);


(lib.cv = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._110();
	this.instance.parent = this;
	this.instance.setTransform(-129,-18);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cv, new cjs.Rectangle(-129,-18,257,35), null);


(lib.sdd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AumCbQhBhAAAhbQAAhaBBhAQBAhBBbAAQBbAABABBQBBBAAABaQAABbhBBAQhABBhbAAQhbAAhAhBgAslhNQgNALgFAMIgpB0ICEAAQAUAAAPgLQAMgJABgJIiFAAIAph5IgCAAQgMAAgPALgAhpAzQgXgPAAgkIAAhhIA+AAIAABfQAAAOAJAGQAHAGARAAQAPAAAIgGQAIgGAAgOIAAhfIA+AAIAABhQAAAkgXAPQgWAOgwAAQgyAAgWgOgAOlA7IgGgSIhBAAIgGASIhDAAIBEicIBLAAIBECcgANsACIAlAAIgSg0IgBAAgAI/A7IAAh1Ig6AAIAAgnICyAAIAAAnIg6AAIAAB1gAFKA7IAAg+IhGAAIAAA+Ig/AAIAAicIA/AAIAAA3IBGAAIAAg3IA+AAIAACcgAmbA7IAAicIA+AAIAAByIBgAAIAAAqg");
	this.shape.setTransform(0,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.sdd, new cjs.Rectangle(-100,-20.9,200,44), null);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 6
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(257));

	// Слой 5
	this.instance = new lib.sdd();
	this.instance.parent = this;
	this.instance.setTransform(149.9,273.4,1.2,0.12,0,0,0,0.1,0.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(203).to({_off:false},0).to({regX:0,regY:0,scaleY:1.2,x:149.8},6,cjs.Ease.get(1)).wait(41).to({regX:0.1,regY:0.8,scaleY:0.12,x:149.9},6,cjs.Ease.get(1)).wait(1));

	// Символ 17
	this.instance_1 = new lib.ewe();
	this.instance_1.parent = this;
	this.instance_1.setTransform(162.4,98.2,1.2,1.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(184).to({_off:false},0).to({x:150.4,alpha:1},8,cjs.Ease.get(1)).wait(54).to({x:138.4,alpha:0},6,cjs.Ease.get(1)).wait(5));

	// Слой 9
	this.instance_2 = new lib.cv();
	this.instance_2.parent = this;
	this.instance_2.setTransform(160.8,136.8);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(194).to({_off:false},0).to({regX:0.1,regY:0.1,x:148.8,alpha:1},8,cjs.Ease.get(1)).wait(45).to({regX:0,regY:0},0).to({x:136.8,alpha:0},6,cjs.Ease.get(1)).wait(4));

	// Символ 18
	this.instance_3 = new lib.wqwqw();
	this.instance_3.parent = this;
	this.instance_3.setTransform(163.6,175.6,1.2,1.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(187).to({_off:false},0).to({x:151.6,alpha:1},8,cjs.Ease.get(1)).wait(53).to({x:139.6,alpha:0},6,cjs.Ease.get(1)).wait(3));

	// Символ 16
	this.instance_4 = new lib.qww();
	this.instance_4.parent = this;
	this.instance_4.setTransform(161.5,232.4,1.2,1.2);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(121).to({_off:false},0).to({x:149.5,alpha:1},8,cjs.Ease.get(1)).wait(45).to({x:137.5,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(76));

	// Символ 15
	this.instance_5 = new lib.qw();
	this.instance_5.parent = this;
	this.instance_5.setTransform(161.8,200,1.2,1.2);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(116).to({_off:false},0).to({x:149.8,alpha:1},8,cjs.Ease.get(1)).wait(49).to({x:137.8,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(77));

	// Символ 14
	this.instance_6 = new lib.wq();
	this.instance_6.parent = this;
	this.instance_6.setTransform(161,167.9,1.2,1.2);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(110).to({_off:false},0).to({x:149,alpha:1},8,cjs.Ease.get(1)).wait(54).to({x:137,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(78));

	// Символ 13
	this.instance_7 = new lib.w();
	this.instance_7.parent = this;
	this.instance_7.setTransform(161.8,118.8,1.2,1.2);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(95).to({_off:false},0).to({x:149.8,alpha:1},9,cjs.Ease.get(1)).wait(67).to({x:137.8,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(79));

	// Слой 11
	this.instance_8 = new lib.hjkkk();
	this.instance_8.parent = this;
	this.instance_8.setTransform(135.7,249.1);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(42).to({_off:false},0).to({x:124.7,alpha:1},9,cjs.Ease.get(1)).wait(36).to({x:115.7,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(163));

	// Слой 17
	this.instance_9 = new lib.dfd("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(159.8,256.2,1.2,1.2);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(35).to({_off:false},0).to({x:149.8,alpha:1},9,cjs.Ease.get(1)).wait(42).to({startPosition:0},0).to({x:139.8,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(164));

	// Символ 12
	this.instance_10 = new lib.www();
	this.instance_10.parent = this;
	this.instance_10.setTransform(161.8,233.7,1.2,1.2);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(31).to({_off:false},0).to({x:149.8,alpha:1},9,cjs.Ease.get(1)).wait(45).to({x:137.8,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(165));

	// Символ 11
	this.instance_11 = new lib.dfgd();
	this.instance_11.parent = this;
	this.instance_11.setTransform(162.1,164,1.2,1.2);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(10).to({_off:false},0).to({x:150.1,alpha:1},8,cjs.Ease.get(1)).wait(66).to({x:138.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(166));

	// Символ 10
	this.instance_12 = new lib.fdgdf();
	this.instance_12.parent = this;
	this.instance_12.setTransform(161.8,129.6,1.2,1.2);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(6).to({_off:false},0).to({x:149.8,alpha:1},8,cjs.Ease.get(1)).wait(69).to({x:137.8,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(167));

	// Символ 9
	this.instance_13 = new lib.xcv();
	this.instance_13.parent = this;
	this.instance_13.setTransform(161.7,95,1.2,1.2);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(2).to({_off:false},0).to({x:149.7,alpha:1},8,cjs.Ease.get(1)).wait(72).to({x:137.7,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(168));

	// Слой 4
	this.instance_14 = new lib.cv();
	this.instance_14.parent = this;
	this.instance_14.setTransform(147.6,511.6,1,0.119,0,0,0,0.1,0.8);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(50).to({_off:false},0).to({regY:0.1,scaleY:1},6,cjs.Ease.get(1)).wait(115).to({regY:0.8,scaleY:0.12},6,cjs.Ease.get(1)).to({_off:true},1).wait(79));

	// bg3.jpg
	this.instance_15 = new lib.wrq();
	this.instance_15.parent = this;
	this.instance_15.setTransform(120,200);
	this.instance_15.alpha = 0;
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(183).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(66));

	// bg2.jpg
	this.instance_16 = new lib.qrq();
	this.instance_16.parent = this;
	this.instance_16.setTransform(120,200);
	this.instance_16.alpha = 0;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(94).to({_off:false},0).to({alpha:1},8,cjs.Ease.get(1)).wait(155));

	// bg.jpg
	this.instance_17 = new lib.rq();
	this.instance_17.parent = this;
	this.instance_17.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(257));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149.5,299.5,301,601);
// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x600_atlas_P_.png?1504474853134", id:"300x600_atlas_P_"},
		{src:"images/300x600_atlas_NP_.jpg?1504474853135", id:"300x600_atlas_NP_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;