(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"160x600_atlas_P_", frames: [[0,247,296,221],[0,0,299,245]]},
		{name:"160x600_atlas_NP_", frames: [[0,0,240,200],[242,0,180,178],[0,202,240,200]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib._1 = function() {
	this.spriteSheet = ss["160x600_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["160x600_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._3 = function() {
	this.spriteSheet = ss["160x600_atlas_P_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._4 = function() {
	this.spriteSheet = ss["160x600_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib._5 = function() {
	this.spriteSheet = ss["160x600_atlas_P_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.text5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#4A4A49").s().p("AlbBFIAAgaIhWAAIAAAWIgBADIgDABIgKAAIAAgmIALAAIAFgEIAEgHIAEgLIAEgRIACgYIABgfIBBAAIAABeIARAAIAFgBQADgBACgDQADgEADgGIAEgQIAEgaIABglIBBAAIAABqIgPAAIAAheIgiAAIgEAkIgEAYQgCALgEAHQgDAHgDAEQgFADgEACIgJABIgCAAIAAAVQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgDABgAmTgUIgEAXIgFARQgCAHgEAEIA0AAIAAhSIgiAAIgDAfgAC3AsQgBgBAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgKIAFAAIAEAAIAEgBIACgDIAEgFIAEgKIgkg/IgxAAIAABeIgQAAIAAhqIBJAAIADABIACACIAZAvIAFALIACgFIACgGIAXgvIABgCIADgBIAOAAIgsBcIgEAIIgGAEIgGADIgGAAIgHAAgAGxArIAAhqIAPAAIAABqgAFTArIAAhqIAQAAIAAAuIAUAAQAKAAAHACQAIACAEAEQAFAEACAFQACAFAAAGQAAAHgDAGQgCAGgFAEQgEAFgIACQgHACgJAAgAFjAfIAUAAIAKgBQAFgCACgCQADgDACgDIABgIIgBgHIgEgFQgDgDgEgBQgEgBgHAAIgUAAgAEDArIAAhqIAhAAQAKAAAHACQAIACAEAFQAFAEADAGQACAHAAAHQAAAIgCAGQgDAGgFAFQgFAEgHACQgIACgJAAIgSAAIAAAogAESgIIASAAQAFAAAFgCIAIgEQADgDABgEQADgEAAgFQAAgFgDgEQgBgEgDgDQgDgCgFgCQgFgBgFAAIgSAAgABGArIAAhKIABgHIAAgHIgCAGIgDAGIgxBHIgDAEIgEABIgLAAIAAhqIAPAAIAABKIAAAGIgBAIIADgHIADgFIAxhIIACgDIAFgBIALAAIAABqgAhGArIAAgNQgKAAgJgDQgJgEgFgGQgGgGgEgIQgEgGAAgJQAAgJAEgIQAEgIAGgFQAFgGAJgEQAJgDAKgBIAAgMIAOAAIAAAMQAKABAJADQAIAEAHAGQAFAFAEAIQAEAIgBAJQABAJgEAGQgEAIgFAGQgHAGgIAEQgJADgKAAIAAANgAg4ASQAHAAAGgDQAGgCAEgEQADgEACgFQADgGAAgGQAAgHgDgFQgCgGgDgEQgEgEgGgDQgGgCgHAAgAhTgpQgGADgEAEQgDAEgDAGQgCAFAAAHQAAAGACAGQADAFADAEQAEAEAGACQAGADAHAAIAAg9QgHAAgGACgAioArIAAgtIgQAAIgDABIgEABIgCABIgDAEIgXAhIgEAEQgDABgDAAIgLAAIAbgnQAFgFAGgDQgHgCgEgCQgGgDgCgDQgDgEgCgFQgBgEgBgGQABgGACgGQADgGAEgEQAFgEAIgCQAHgCAIAAIAkAAIAABqgAjIgyQgFACgCACQgDACgBAEQgCADABAEQgBAFACADQABAEADACIAHAEIAKABIAWAAIAAglIgWAAQgFAAgFABg");
	this.shape.setTransform(0,45.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#4A4A49").s().p("ADzBEIAAgaIhVAAIAAAVIgBAEIgEABIgKAAIAAgaIhAAAIAAhrIBDAAIAAAMIgzAAIAAAjIApAAIAAANIgpAAIAAAiIAzAAIAAABIAJAAIAEgFIAFgHIADgLIAEgRIADgYIABgfIBBAAIAABfIAQAAIAmhfIAQAAIArBrIgNAAIgCgBIgCgDIgKgZIgwAAIgKAZIgCADIgDABIgGAAIAAAVQAAABAAAAQAAAAAAABQAAAAAAABQgBAAAAABIgDABgAC7gVIgDAWIgGARQgCAHgDAFIAzAAIAAhTIgiAAIgDAggAEsgtIgBAFIgRApIAnAAIgQgpIgCgFIgBgFIgCAFgAi6AnQgJgEgHgGIAAgBIAEgHIACgCIACAAIACABIADACIAEADIAFACIAGACIAJABQALgBAHgEQAGgGAAgKQAAgEgBgDQgCgCgDgDQgDgDgFgBIgJgBIgPAAIAAgNIAOAAIAIgBQAEgBADgCQADgCABgDQACgDAAgFQAAgDgCgDIgDgFIgIgEIgJgBQgFABgFABIgHADIgEACIgEABIgCAAIgBgBIgFgIQAHgGAIgDQAIgCAKAAQAJgBAHADQAGACAFAEQAFADACAGQACAEAAAHQAAAHgDAGQgEAHgIAEIAIAEIAGAFIADAGIABAHQAAAIgCAGQgDAGgFAFQgEAEgIADQgHACgKAAQgLAAgJgDgAAAAqIAAhrIAfAAQALAAAHACQAIACAEAFQAFAFADAFQACAHAAAIQAAAHgCAGQgDAHgFAEQgFAEgHADQgIABgKAAIgRAAIAAApgAAOgKIARAAQAGAAAFgBIAIgFQADgDACgDQACgFAAgEQAAgGgCgDQgCgFgDgCQgDgDgFgCQgFgBgGAAIgRAAgAhXAqIAAhrIAiAAQALAAAGACQAHACAGAEQAEADACAGQACAEABAHQgBAEgBAEIgEAHIgGAFQgDACgFACQALACAGAHQAGAFAAAJQAAAHgCAHQgDAFgFAEQgFAEgHACQgHACgJABgAhIAdIAXAAIAKgBQAFgBADgDIADgGIABgIQABgIgGgEQgFgEgMgBIgXAAgAhIgRIASAAQAHAAAEgCIAHgDIAFgGQABgDAAgEQAAgKgGgDQgFgFgMAAIgTAAgAkMAqIAAhrIBCAAIAAAMIgzAAIAAAjIApAAIAAANIgpAAIAAAiIAzAAIAAANgAlgAqIAAhrIBGAAIAAAMIg2AAIAAAiIAUAAQAKAAAHACQAIACAEAEQAFAEACAFQADAFAAAGQgBAHgDAHQgCAGgFAEQgEAEgIACQgHACgJABgAlQAdIAUAAIAKgBQAFgBACgDQADgDACgDIABgIIgBgHIgEgFQgDgCgEgBQgEgCgHAAIgUAAgAjKAdg");
	this.shape_1.setTransform(0,23.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#4A4A49").s().p("Ag0AzQgKgEgHgHQgHgIgEgJQgDgLAAgMQAAgLADgKQAEgKAHgIQAHgGAKgEQAKgFAMAAQAMAAAKAFQAIAEAHAGQAHAIAEAKQAEAKAAALQAAAMgEALQgEAJgHAIQgHAHgIAEQgKAEgMAAQgMAAgKgEgAgugmQgHADgEAFQgFAGgDAIQgDAHAAAJQAAAKADAHQADAJAFAFQAEAFAHADQAHADAJgBQAIABAHgDQAHgDAFgFQAEgFADgJQACgHAAgKQAAgJgCgHQgDgIgEgGQgFgFgHgDQgHgCgIAAQgJAAgHACgAjwAzQgKgEgHgHQgHgIgEgJQgEgLAAgMQAAgLAEgKQAEgKAHgIQAHgGAKgEQAJgFAMAAQAMAAAKAFQAKAEAHAGQAHAIAEAKQAEAKAAALQAAAMgEALQgEAJgHAIQgHAHgKAEQgKAEgMAAQgMAAgJgEgAjqgmQgHADgFAFQgFAGgCAIQgDAHAAAJQAAAKADAHQACAJAFAFQAFAFAHADQAHADAIgBQAJABAHgDQAHgDAFgFQAFgFACgJQADgHAAgKQAAgJgDgHQgCgIgFgGQgFgFgHgDQgHgCgJAAQgIAAgHACgAFEA2IAAhMIAAgEIAAgEIgkBBIgCADIgDABIgDAAQgDAAgCgEIglhBIAAAEIAAAEIAABMIgNAAIAAhqIALAAIADAAIACACIAlBAIADAIIACgEIACgEIAkhAIACgCIADAAIALAAIAABqgADAA2IAAhKIAAgHIABgHIgDAGIgDAGIgxBHIgDADIgEACIgLAAIAAhqIAPAAIAABKIAAAGIgBAHIADgGIADgFIAxhIIADgDIAEgBIALAAIAABqgAAgA2IAAhqIAjAAQAKAAAHACQAHACAFADQAFADACAGQACAFAAAHQAAAEgBADIgEAHIgGAGQgEACgFABQAMACAGAGQAGAGAAAKQAAAHgDAGQgCAFgFAFQgFADgHACQgHADgJAAgAAwApIAWAAIALAAQAEgCADgCIAEgGIABgIQAAgJgFgEQgGgFgMAAIgWAAgAAwgEIASAAQAGgBAFgBIAHgEIAEgFQACgEAAgDQAAgKgGgEQgFgEgMAAIgTAAgAiEA2IAAheIgiAAIAAgMIBUAAIAAAMIgjAAIAABegAlQA2IAAhqIBBAAIAAAMIgyAAIAABeg");
	this.shape_2.setTransform(0,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#4A4A49").s().p("ADMAzQgKgEgHgIQgHgHgEgJQgEgLABgMQgBgLAEgKQAEgKAHgHQAHgHAKgFQAJgEANAAQALAAALAEQAJAFAHAHQAHAHAEAKQAEAKAAALQAAAMgEALQgEAJgHAHQgHAIgJAEQgLAEgLAAQgNAAgJgEgADSglQgHACgEAGQgGAFgCAHQgDAJAAAIQAAAKADAHQACAJAGAEQAEAGAHADQAHADAJAAQAIAAAHgDQAHgDAFgGQAFgEACgJQADgHAAgKQAAgIgDgJQgCgHgFgFQgFgGgHgCQgHgDgIgBQgJABgHADgAAHAzQgIgEgGgHQgIgIgDgJQgDgLgBgMQABgLADgKQAEgLAHgGQAHgIAIgEQAKgEAMAAQALAAAJAEQAKAEAGAGIgFAHIgCABIgBABIgDgCIgGgDIgIgDQgEgCgHAAQgIABgHADQgHACgEAGQgEAFgDAHQgDAJAAAIQAAAKADAIQADAIAEAFQAFAFAGADQAHADAIAAIAIAAIAHgDIAGgDIAGgDIABgBIABgBIACABIAHAHQgHAHgKAFQgJAEgNAAQgMAAgKgEgAhbA2QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBgBAAIAAgKIAGAAIADAAIAEgBIAEgEIACgEIAGgKIgphGIgdAmQgDAFgGADQAEAAADACIAFAHIAhAuIgPAAIgDgBIgDgEIgcgnIgEgEIgHgBIgMAAIAAAxIgQAAIAAhrIAQAAIAAAvIALAAIADAAIADgBIACgCIACgCIAbglIAEgEIADgBIAWAAIADABIACADIAaAvIAEAKIACgGIADgEIAVgvIADgDIADgBIAMAAIgrBdIgFAHIgFAFIgFACIgIABIgGgBgACSA2IAAgwIg5AAIAAAwIgPAAIAAhrIAPAAIAAAwIA5AAIAAgwIAPAAIAABrgAkWA2IAAhrIAiAAQALAAAHACQAHACAFAEQAEAEACAFQADAFAAAGQAAAFgCADIgDAHIgHAFQgDADgFACQAMABAFAGQAHAGgBAKQAAAHgCAGQgDAGgEADQgFAEgHADQgIACgIAAgAkHAqIAXAAIALgBQAEgCADgDIAEgGIABgHQAAgJgFgEQgGgFgMAAIgXAAgAkHgFIATAAQAGAAAEgBIAIgDIAEgGQABgDABgFQgBgJgFgEQgGgFgMAAIgTAAg");
	this.shape_3.setTransform(0,-21.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text5, new cjs.Rectangle(-44.8,-27,89.6,79.4), null);


(lib.text4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#4B4A4A").s().p("AhVA2IgBgBIgIAAIgCgBIgCgCIgdgsIAAABIgBACIgbApIgCACIgCABIgPAAIAlg2Igjg0IAPAAIACAAIACACIAbAqIABgBIABgCIAagnQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAIAPAAIgkAzIAdArIADAAIAGgBQADgBACgDQADgEADgGIAEgRIAEgZIABglIBAAAIAABqIgOAAIAAheIgiAAIgEAkIgEAYQgCALgEAHQgDAHgDAEQgFADgEACIgJABIgGAAgABlA1IAAhqIBGAAIAAAMIg3AAIAAAiIAVAAQAKAAAHACQAHACAFADQAFAEACAFQACAGAAAGQAAAHgDAGQgCAGgFAEQgFAFgHACQgHACgJAAgAB0ApIAVAAIAKgBQAFgCACgCQADgDABgDIABgIIgBgHIgDgGQgEgDgDgBQgFgBgGAAIgVAAgAAYA1IAAhqIBDAAIAAAMIgzAAIAAAjIApAAIAAALIgpAAIAAAkIAzAAIAAAMg");
	this.shape.setTransform(0,22.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#4B4A4A").s().p("AleBQIAAgaIhWAAIAAAWIAAADIgEABIgKAAIAAgmIAMAAIAEgEIAFgHIADgLIAEgSIADgXIABgfIBBAAIAABeIARAAIAAAiQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAIgDABgAmWgJIgDAXIgGARQgCAHgDAEIAzAAIAAhSIgiAAIgDAfgAkvAzQgLgEgGgHQgIgHgDgKQgEgKAAgNQAAgLAEgKQADgKAIgHQAGgHALgEQAJgFAMAAQAMAAAKAFQAKAEAGAHQAHAHAFAKQADAKAAALQAAANgDAKQgFAKgHAHQgGAHgKAEQgKAEgMAAQgMAAgJgEgAkqglQgGADgFAFQgFAFgDAIQgCAIAAAIQAAAKACAIQADAIAFAFQAFAFAGADQAIADAIAAQAIAAAIgDQAGgDAFgFQAFgFADgIQADgIgBgKQABgIgDgIQgDgIgFgFQgFgFgGgDQgIgDgIAAQgIAAgIADgAGzA2IAAhKIABgHIAAgHIgCAGIgEAGIgwBHIgDAEIgFABIgLAAIAAhqIAQAAIAABKIAAAGIgCAIIAEgHIACgFIAyhIIACgDIAEgBIAMAAIAABqgAFKA2IAAhKIAAgHIABgHIgDAGIgCAGIgyBHIgCAEIgFABIgLAAIAAhqIAQAAIAABKIAAAGIgBAIIACgHIADgFIAyhIIACgDIAEgBIAMAAIAABqgADhA2IAAgwIg5AAIAAAwIgPAAIAAhqIAPAAIAAAvIA5AAIAAgvIAPAAIAABqgAACA2IAAhqIAPAAIAABeIAsAAIAAheIAQAAIAABeIAsAAIAAheIAPAAIAABqgAgNA2IgDgBIgCgCIgKgaIgwAAIgJAaIgCACIgEABIgMAAIAshqIAPAAIArBqgAg2ggIgBAFIgRApIAoAAIgRgpIgBgFIgBgGIgDAGgAh4A2IAAhMIAAgEIABgDIgkBBIgCACIgDABIgDAAQgDAAgCgDIglhCIAAAEIAAAEIAABMIgOAAIAAhqIAMAAIADAAIACACIAkBAIAEAIIACgEIACgEIAkhAIABgCIAEAAIALAAIAABqgAGHg/QgGgEAAgIIABgDQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIAJAAIAAAGIACAEIADACIAGAAIAEAAIAEgCIACgEIAAgGIAJAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIAAADQAAAIgFAEQgGAEgKAAQgLAAgGgEg");
	this.shape_1.setTransform(0,0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#4B4A4A").s().p("AD0BQIAAgaIiJAAIAAhqIAPAAIAABeIAsAAIAAheIAQAAIAABeIAsAAIAAheIAPAAIAABeIARAAIAAAiQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgDABgAhDAzQgKgEgHgHQgHgHgEgKQgEgKAAgNQAAgLAEgKQAEgKAHgHQAHgHAKgEQAJgFAMAAQAMAAALAFQAJAEAHAHQAHAHADAKQAEAKAAALQAAANgEAKQgDAKgHAHQgHAHgJAEQgLAEgMAAQgMAAgJgEgAg9glQgHADgFAFQgFAFgCAIQgDAIAAAIQAAAKADAIQACAIAFAFQAFAFAHADQAHADAIAAQAJAAAHgDQAHgDAFgFQAFgFACgIQADgIAAgKQAAgIgDgIQgCgIgFgFQgFgFgHgDQgHgDgJAAQgIAAgHADgAjtAzQgKgEgGgHQgHgHgEgKQgDgKAAgNQAAgLADgKQAEgKAHgHQAIgHAJgFQAKgEAMAAQALAAAJAEQAHADAFAFIAAgKIBVAAIAAANIgjAAIAABdIgPAAIAAhdIgfAAIgGAGIgBACIgCAAIgDgBIgFgEIgIgDQgFgBgGAAQgJAAgGADQgHADgFAFQgFAFgCAIQgDAIgBAIQABAKADAIQACAIAGAFQAEAFAHADQAGADAIAAIAIAAIAHgCIAHgDIAFgEIACgBIABgBIACABIAGAHQgGAIgKAEQgJAEgOAAQgLAAgKgEgAG7A2IAAhKIAAgHIABgHIgDAGIgDAGIgxBHIgDAEIgEABIgLAAIAAhqIAPAAIAABKIAAAGIgBAIIADgHIADgFIAxhIIADgDIADgBIAMAAIAABqgAFSA2IAAhKIAAgHIAAgHIgCAGIgDAGIgxBHIgDAEIgEABIgMAAIAAhqIAQAAIAABKIAAAGIgBAIIADgHIADgFIAxhIIADgDIADgBIAMAAIAABqgABLA2IAAguIgPAAIgDABIgEABIgDACIgDAEIgXAhIgDAEQgDABgDAAIgMAAIAcgnQAEgGAGgDQgGgCgFgCQgFgCgDgDQgDgEgCgFQgBgEAAgGQAAgGADgGQACgGAFgEQAFgEAHgCQAHgCAJAAIAkAAIAABqgAArgnQgEACgCACQgEACgBAEQgBADAAAEQAAAFABADQABAEAEACIAGAEIALABIAVAAIAAglIgVAAQgGAAgFABgAkUA2IgDgBIgCgCIgKgaIgvAAIgKAaIgCACIgEABIgLAAIArhqIAPAAIArBqgAk9ggIgBAFIgRApIAoAAIgQgpIgCgFIgCgGIgCAGgAmBA2IAAgwIg5AAIAAAwIgPAAIAAhqIAPAAIAAAvIA5AAIAAgvIAPAAIAABqgAGPg/QgHgEAAgIIABgDQABAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAJAAIAAAGIADAEIADACIAFAAIAFAAIAEgCIABgEIABgGIAIAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIABADQAAAIgGAEQgGAEgKAAQgLAAgFgEg");
	this.shape_2.setTransform(0,-21.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#4B4A4A").s().p("ACFBDQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIAAgKIAGAAIADAAIAEgCIADgDIADgEIAFgLIgrhLIAPAAIADABIABADIAaAuIAFALIACgGIACgFIAWguIACgDIADgBIANAAIgrBdIgFAHIgGAFIgFACIgHABIgHgBgAgqBAQgKgEgHgIQgHgHgEgKQgDgKgBgMQABgMADgJQAEgKAHgIQAHgHAKgEQAJgEAMAAQANAAAJAEQAJAEAHAHQAHAIAEAKQAEAJAAAMQAAAMgEAKQgEAKgHAHQgHAIgJAEQgJAEgNAAQgMAAgJgEgAgkgZQgHADgFAFQgEAGgDAHQgDAHAAAKQAAAKADAHQADAIAEAFQAFAGAHADQAHACAIAAQAJAAAHgCQAGgDAFgGQAFgFADgIQACgHAAgKQAAgKgCgHQgDgHgFgGQgFgFgGgDQgHgDgJAAQgIAAgHADgAlNBAQgKgEgHgIQgHgHgEgKQgDgKAAgMQAAgMADgJQAEgKAHgIQAHgHAKgEQAKgEAMAAQALAAAKAEQAKAEAHAHQAHAIAEAKQAEAJAAAMQAAAMgEAKQgEAKgHAHQgHAIgKAEQgKAEgLAAQgMAAgKgEgAlHgZQgHADgEAFQgFAGgDAHQgDAHAAAKQAAAKADAHQADAIAFAFQAEAGAHADQAHACAJAAQAIAAAHgCQAHgDAFgGQAFgFADgIQACgHAAgKQAAgKgCgHQgDgHgFgGQgFgFgHgDQgHgDgIAAQgJAAgHADgAGJBDIAAhrIBDAAIAAANIgzAAIAAAhIAoAAIAAANIgoAAIAAAjIAzAAIAAANgAFSBDIAAheIgjAAIAAgNIBVAAIAAANIgjAAIAABegAEaBDIAAhKIAAgHIABgIIgDAHIgDAFIgxBIIgDADIgEACIgLAAIAAhrIAPAAIAABKIAAAHIgBAHIADgGIADgFIAxhIIADgDIADgCIAMAAIAABrgAAqBDIAAhrIBGAAIAAAMIg2AAIAAAhIAUAAQAJAAAIACQAHACAEAEQAGAEABAGQADAFAAAGQAAAIgDAGQgDAGgEAEQgFAEgHACQgHADgKAAgAA6A2IATAAIALgBQAEgBADgDQADgCACgEIABgHIgBgIIgFgGQgCgCgFgBQgEgCgGAAIgUAAgAiUBDIAAhrIAhAAQAKAAAIADQAHACAFAEQAFAFADAGQACAGAAAIQAAAGgCAGQgDAHgFAEQgFAFgIACQgIADgJAAIgRAAIAAAogAiEAPIARAAQAGAAAFgCIAIgEQADgDABgEQACgDAAgFQAAgFgCgEQgBgEgDgDQgEgDgEgBQgFgCgGAAIgRAAgAi0BDIAAhfIg0AAIAABfIgQAAIAAhrIBTAAIAABrgAmHBDIAAhfIg0AAIAABfIgQAAIAAhrIBUAAIAABrgADugzQgHgEAAgHIABgDQABgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAIAAIABAGIACAEIACACIAGABIAFgBIAEgCIABgEIABgGIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABADQAAAHgGAEQgFAEgLAAQgLAAgFgEg");
	this.shape_3.setTransform(0,-44.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text4, new cjs.Rectangle(-45.9,-51.5,91.9,79.5), null);


(lib.text3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#4B4A4A").s().p("AgTAzQgKgEgHgIQgHgGgEgLQgDgJAAgNQAAgLADgKQAEgKAHgHQAHgHAKgFQAKgEALAAQAMAAAKAEQAJAFAHAHQAHAHAEAKQAEAKAAALQAAANgEAJQgEALgHAGQgHAIgJAEQgKAEgMAAQgLAAgKgEgAgNglQgHACgEAGQgFAFgDAHQgDAJAAAIQAAAKADAIQADAHAFAFQAEAGAHADQAHADAIAAQAIAAAHgDQAHgDAFgGQAFgFADgHQACgIAAgKQAAgIgCgJQgDgHgFgFQgFgGgHgCQgHgEgIAAQgIAAgHAEgAEuA2IAAguIgPAAIgDABIgEABIgDACIgDAEIgWAgIgEAFQgDABgDAAIgNAAIgDgBIgCgCIgKgaIgwAAIgJAaIgCACIgEABIgMAAIArhrIAQAAIAnBiIAVgeQAEgGAGgDQgGgCgFgDQgFgBgDgEQgDgEgBgEQgCgFAAgFQAAgHADgGQACgFAFgEQAFgEAHgDQAHgCAJAAIAkAAIAABrgAC8ggIgBAFIgRApIAoAAIgRgpIgBgFIgCgGIgCAGgAEPgnQgFABgCADQgDACgBAEQgCADAAAEQAAAFACADQABADADADIAHADIAKABIAVAAIAAglIgVAAQgGAAgEACgABBA2IAAhrIAjAAQAKAAAHACQAHACAFAEQAFAEACAFQACAFAAAGQAAAEgBAEIgEAHIgGAFQgEADgFACQAMABAGAGQAGAHAAAJQAAAHgDAGQgCAGgFADQgFAFgHACQgHACgJAAgABRAqIAWAAIALgCQAEgBADgDIAEgGIABgHQAAgJgFgEQgGgFgMAAIgWAAgABRgFIASAAQAGAAAFgBIAHgDIAEgGQACgEAAgEQAAgJgGgEQgFgFgMAAIgTAAgAh8A2IAAhrIAgAAQAKABAIACQAIACAEAEQAFAFADAGQACAHAAAHQAAAIgCAFQgDAGgFAEQgFAFgIACQgHADgKAAIgRAAIAAAogAhtACIARAAQAGAAAFgCIAIgDQADgDABgEQACgEAAgFQAAgFgCgEQgBgEgDgDQgDgDgFgBQgFgCgGAAIgRAAgAiMA2IgDgBIgCgCIgKgaIgvAAIgKAaIgCACIgDABIgMAAIArhrIAPAAIArBrgAi0ggIgCAFIgQApIAnAAIgQgpIgCgFIgBgGIgCAGgAj4A2IAAhfIg1AAIAABfIgPAAIAAhrIBTAAIAABrg");
	this.shape.setTransform(0,0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#4B4A4A").s().p("AhOAzQgJgEgHgHQgHgIgDgJQgEgLAAgMQAAgLAEgKQADgLAHgGQAIgIAJgEQAKgEALAAQAMAAAJAEQAHADAGAEIAAgKIBSAAIAAAOIgiAAIAABdIgPAAIAAhdIgfAAIgEAGIgCABIgCABIgDgCIgFgDIgIgDQgEgCgIAAQgHABgHADQgHACgFAGQgFAFgDAHQgDAJAAAIQAAAKADAIQAEAIAEAFQAFAFAHADQAHADAHAAIAIAAIAIgDIAGgDIAFgDIABgBIABgBIADABIAGAHQgHAHgJAFQgKAEgNAAQgMAAgJgEgAEoA2IAAguIgPAAIgEAAIgDACIgDACIgDAEIgWAgIgFAFQgCABgDAAIgOAAIgCgBIgCgCIgKgaIgwAAIgKAaIgCACIgDABIgMAAIArhrIAQAAIAnBhIAUgdQAFgGAGgDQgGgCgFgDQgFgBgDgDQgDgFgBgEQgCgFAAgFQAAgGACgHQADgFAFgEQAFgEAHgDQAHgCAJAAIAkAAIAABrgAC2ggIgBAFIgRApIAnAAIgQgpIgCgFIgBgGIgCAGgAEJgnQgFABgDADQgCACgBAEQgCADAAAEQAAAEACAEQABADACADIAIADIAKACIAVAAIAAgmIgVAAQgGAAgEACgABCA2IAAhrIAgAAQAKABAIACQAIACAFAEQAEAFADAGQACAGABAIQgBAIgCAFQgDAGgEAFQgGAEgIACQgHADgKAAIgQAAIAAAogABSACIAQAAQAHAAAEgCIAIgDQADgDABgEQACgEAAgFQAAgFgCgEQgBgEgDgDQgDgDgEgBQgGgCgGAAIgQAAgAiGA2IAAhrIAPAAIAABrgAjjA2IAAhrIAQAAIAAAuIAUAAQAJAAAIACQAHADAEACQAGAEABAGQADAFAAAGQAAAIgDAGQgDAGgEAEQgFAFgHACQgHACgKAAgAjTAqIATAAIALgBQAEgCADgDQADgCACgEIABgHIgBgHIgFgHQgCgCgFgBQgEgBgGAAIgUAAgAk2A2IAAhrIBGAAIAAAMIg2AAIAAAiIAUAAQAKAAAHACQAHADAEACQAFAEADAGQACAFAAAGQAAAIgDAGQgDAGgEAEQgFAFgHACQgHACgJAAgAkmAqIAUAAIAKgBQAEgCADgDQADgCABgEIABgHIgBgHIgDgHQgEgCgEgBQgEgBgGAAIgUAAg");
	this.shape_1.setTransform(0,-21.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#4B4A4A").s().p("AAFAzQgIgEgHgHQgHgIgDgKQgEgJAAgNQAAgLAEgKQAEgKAHgIQAHgGAIgFQAKgEAMAAQALAAAJAEQAHADAGAEIAAgJIBUAAIAAAMIgjAAIAABeIgPAAIAAheIgfAAIgFAHIgCABIgCABIgDgCIgFgDIgIgDQgEgBgHgBQgIAAgHAEQgHADgFAEQgEAGgCAIQgDAHAAAJQAAAKADAIQADAHAEAGQAEAFAHADQAHADAHAAIAJgBIAHgCIAGgCIAFgFIACgBIABAAIACABIAGAHQgGAHgKAFQgJAEgNAAQgMAAgKgEgAkpAzQgKgEgHgIQgHgGgEgLQgDgJAAgNQAAgLADgKQAEgKAHgIQAHgGAKgFQAKgEAMAAQAMAAAKAEQAJAFAHAGQAHAIAEAKQAEAKAAALQAAANgEAJQgEALgHAGQgHAIgJAEQgKAEgMAAQgMAAgKgEgAkjglQgHADgEAEQgFAGgDAIQgDAHAAAJQAAAKADAIQADAHAFAFQAEAGAHADQAHACAJAAQAIAAAHgCQAHgDAFgGQAFgFADgHQACgIAAgKQAAgJgCgHQgDgIgFgGQgFgEgHgDQgHgEgIAAQgJAAgHAEgAE9A2IgDgBIgCgDIgKgZIgvAAIgKAZIgCADIgDABIgRAAIgEgBIgDgEIgbgnIgEgEIgHgBIgMAAIAAAxIgQAAIAAhqIAQAAIAAAuIALAAIADAAIACgBIADgBIACgDIAbgmIADgCIAEgBIANAAIggAsQgDAEgGADQAEABADABIAFAHIAaAmIAohiIAPAAIArBqgAEVggIgCAFIgQApIAnAAIgQgpIgCgFIgBgGIgCAGgAgyA2IAAhKIAAgHIABgHIgDAGIgDAFIgxBIIgDAEIgEABIgLAAIAAhqIAPAAIAABJIAAAHIgBAIIADgHIADgFIAxhIIADgDIAEgBIALAAIAABqgAibA2IAAguIgQADIgQACIgNgCQgFgCgFgEQgEgDgCgFQgDgGAAgIIAAgjIAQAAIAAAjQAAAHADAEQADAFAGABQAGABAJAAIAVgDIAAgyIAQAAIAABqg");
	this.shape_2.setTransform(0,22.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text3, new cjs.Rectangle(-32.9,-27,65.9,54.9), null);


(lib.text2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#4A4A49").s().p("Ao4AzQgJgEgGgHQgIgHgDgLQgDgKgBgMQABgLADgKQAEgKAHgIQAHgGAJgFQAKgEAMAAQALAAAJAEQAKAEAGAGIgFAHIgCACIgBAAIgDgBIgGgEIgIgDQgEgCgHABQgIAAgHACQgHADgEAFQgFAGgDAIQgDAHAAAJQAAAKADAIQADAIAFAFQAFAFAGADQAHADAIAAIAIgBIAHgBIAGgDIAGgFIABgBIABAAIACABIAGAHQgGAHgKAFQgJAEgNAAQgMAAgKgEgAJJA2IAAhMIAAgEIABgEIgkBBIgDADIgDABIgCAAQgEAAgCgEIglhBIABAEIAAAEIAABMIgOAAIAAhqIAMAAIACAAIACACIAlBAIAEAIIACgEIABgEIAkhAIACgCIAEAAIAKAAIAABqgAGaA2IAAhqIBCAAIAAAMIgzAAIAAAjIApAAIAAALIgpAAIAAAjIAzAAIAAANgAF4A2IAAhKIABgHIAAgHIgCAGIgDAGIgxBHIgDADIgEACIgMAAIAAhqIAQAAIAABKIAAAGIgBAHIADgGIADgFIAxhIIACgDIAFgBIALAAIAABqgAEQA2IAAgxIg5AAIAAAxIgPAAIAAhqIAPAAIAAAvIA5AAIAAgvIAPAAIAABqgAB7A2IAAhqIBDAAIAAAMIgzAAIAAAjIAoAAIAAALIgoAAIAAAjIAzAAIAAANgABaA2IAAgxIg5AAIAAAxIgPAAIAAhqIAPAAIAAAvIA5AAIAAgvIAPAAIAABqgAg6A2IAAhqIBCAAIAAAMIgyAAIAAAjIApAAIAAALIgpAAIAAAjIAyAAIAAANgAhYA2IAAhMIAAgEIABgEIgkBBIgDADIgDABIgCAAQgEAAgCgEIglhBIAAAEIAAAEIAABMIgNAAIAAhqIAMAAIACAAIACACIAlBAIAEAIIABgEIACgEIAkhAIACgCIAEAAIAKAAIAABqgAjcA2IAAhKIAAgHIABgHIgCAGIgEAGIgxBHIgCADIgFACIgLAAIAAhqIAQAAIAABKIAAAGIgBAHIADgGIACgFIAyhIIACgDIAEgBIAMAAIAABqgAl1A2IAAhqIAhAAQAKAAAIACQAHACAFAFQAFAEADAGQACAHAAAHQAAAHgCAHQgDAFgFAFQgFAEgIADQgIACgJAAIgRAAIAAAogAllACIARAAQAGAAAFgCIAIgDQADgDABgEQACgEAAgFQAAgFgCgEQgBgEgDgDQgEgCgEgCQgFgCgGABIgRAAgAmVA2IAAheIg0AAIAABeIgQAAIAAhqIBTAAIAABqg");
	this.shape.setTransform(0,18.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#4A4A49").s().p("ADJBDIAAgaIhWAAIAAAWIgBAEIgDAAIgJAAIAAglIALAAIAFgFIADgGIAEgMIAEgRIACgXIACggIBBAAIAABfIARAAIAAAhQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABIgDAAgACSgWIgFAXIgEARQgDAHgDAFIA0AAIAAhTIgjAAIgCAfgAAjAnQgIgDgHgHQgHgGgDgKQgEgJgBgJIgVAAIAAAuIgQAAIAAhqIAQAAIAAAvIAVAAQABgKAEgJQADgJAHgGQAHgHAIgEQAJgEAKAAQALABAKAEQAIAEAHAHQAGAIAEAKQADAJAAAMQAAAMgDAKQgEAKgGAHQgHAHgIAFQgKADgLAAQgKABgJgEgAAogyQgGADgEAFQgFAGgCAHQgDAIABAJQgBALADAGQACAIAFAGQAEAFAGACQAGAEAIAAQAIAAAGgEQAGgCAEgFQAFgGADgIQACgGAAgLQAAgJgCgIQgDgHgFgGQgEgFgGgDQgGgDgIgBQgIABgGADgAiPAqQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAIAAgKIAGAAIAFgBQADgBADgEQADgEADgGIADgQIAEgaIACglIBBAAIAABqIgQAAIAAheIgiAAIgDAkIgEAYQgDALgDAHQgEAHgDAEQgEADgFACIgJABIgGAAgAjWApIAAhqIBFAAIAAAMIg2AAIAAAiIAVAAQAJAAAHACQAIACAEAEQAFAEACAFQACAFABAGQAAAIgEAFQgCAGgEAEQgGAFgHACQgGADgKgBgAjHAdIAUAAIALgBQAEgBACgDQAEgDABgDIABgHIgBgIIgEgFQgDgDgEAAQgEgCgGAAIgVAAg");
	this.shape_1.setTransform(0,-1.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#4A4A49").s().p("ACGA2QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAgKIAGAAIAFgBQADgBADgEQADgDACgHIAEgRIAEgZIACglIBBAAIAABrIgQAAIAAheIgiAAIgDAkIgFAYQgCALgDAGQgEAHgDAFQgEADgFABIgJACIgGgBgAgaAzQgKgEgHgHQgHgIgEgJQgEgKAAgNQAAgLAEgKQAEgKAHgHQAHgIAKgDQAJgFAMAAQALAAAKAFQAKADAHAIQAHAHAEAKQAEAKAAALQAAANgEAKQgEAJgHAIQgHAHgKAEQgKAEgLAAQgMAAgJgEgAgUglQgHACgFAGQgFAFgCAHQgDAJAAAIQAAAKADAHQACAIAFAGQAFAFAHADQAHACAIABQAIgBAHgCQAHgDAFgFQAFgGACgIQADgHAAgKQAAgIgDgJQgCgHgFgFQgFgGgHgCQgHgDgIAAQgIAAgHADgAjXAzQgKgEgHgHQgHgIgEgJQgDgKAAgNQAAgLADgKQAEgKAHgHQAHgIAKgDQAKgFAMAAQAMAAAKAFQAJADAHAIQAHAHAEAKQAEAKAAALQAAANgEAKQgEAJgHAIQgHAHgJAEQgKAEgMAAQgMAAgKgEgAjRglQgHACgEAGQgFAFgDAHQgDAJAAAIQAAAKADAHQADAIAFAGQAEAFAHADQAHACAJABQAIgBAHgCQAHgDAFgFQAFgGADgIQACgHAAgKQAAgIgCgJQgDgHgFgFQgFgGgHgCQgHgDgIAAQgJAAgHADgAITA2IAAhrIBDAAIAAANIgzAAIAAAiIApAAIAAAMIgpAAIAAAkIAzAAIAAAMgAHyA2IAAhKIABgHIAAgIIgCAHIgDAGIgxBHIgDADIgEACIgMAAIAAhrIAQAAIAABLIAAAGIgBAHIADgGIADgFIAxhIIACgDIAEgCIAMAAIAABrgAGJA2IAAgwIg4AAIAAAwIgQAAIAAhrIAQAAIAAAwIA4AAIAAgwIAQAAIAABrgAD1A2IAAhrIBCAAIAAANIgzAAIAAAiIApAAIAAAMIgpAAIAAAkIAzAAIAAAMgAA6A2IAAhrIAiAAQALAAAHACQAHADAFADQAEADACAGQADAFAAAGQAAAEgCAEIgDAHIgHAGQgDACgFABQALACAGAGQAGAHAAAJQAAAHgCAGQgDAFgFAEQgFAFgHACQgHACgJAAgABJAqIAXAAIAKgBQAFgCADgDIAEgFIABgIQAAgIgGgFQgFgFgMAAIgXAAgABJgEIATAAQAGAAAEgCIAIgEIAEgFQABgDAAgEQAAgKgFgEQgGgFgMABIgTAAgAhqA2IAAhdIgjAAIAAgOIBUAAIAAAOIgiAAIAABdgAk3A2IAAhrIBBAAIAAANIgxAAIAABegAlYA2IAAhKIABgHIAAgIIgCAHIgDAGIgxBHIgDADIgEACIgMAAIAAhrIAQAAIAABLIAAAGIgBAHIADgGIADgFIAxhIIACgDIAEgCIAMAAIAABrgAnwA2IAAhrIAgAAQAKABAIACQAIACAEAEQAFAFADAGQACAGAAAIQAAAIgCAFQgDAGgFAFQgFAEgIACQgHADgKAAIgRAAIAAAogAnhACIARAAQAGAAAFgCIAIgDQADgDABgEQACgEAAgFQAAgFgCgEQgBgEgDgDQgDgDgFgBQgFgBgGAAIgRAAgAoRA2IAAheIg0AAIAABeIgQAAIAAhrIBUAAIAABrg");
	this.shape_2.setTransform(0,-25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#4A4A49").s().p("AAnA2IgDgBIgCgDIgKgZIgvAAIgJAZIgCADIgEABIgMAAIArhrIAPAAIArBrgAgBggIgBAEIgRAqIAnAAIgRgqIgBgEIgCgGIgBAGg");
	this.shape_3.setTransform(-4.3,40.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#4A4A49").s().p("ACoA2IgDgBIgCgDIgKgZIgvAAIgKAZIgCADIgDABIgMAAIArhrIAPAAIArBrgACAggIgCAEIgQAqIAnAAIgQgqIgCgEIgBgGIgCAGgAAMA2IAAhrIAgAAQAKAAAIADQAIACAEAEQAFAFADAGQACAGAAAIQAAAHgCAGQgDAGgFAEQgFAFgIACQgHADgKAAIgRAAIAAAogAAbACIARAAQAGAAAFgCIAIgDQADgDABgEQACgEAAgFQAAgFgCgEQgBgEgDgDQgDgDgFgBQgFgCgGAAIgRAAgAhvA2IAAhfIg1AAIAABfIgPAAIAAhrIBTAAIAABrg");
	this.shape_4.setTransform(0,40.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text2, new cjs.Rectangle(-59.8,-30.5,119.7,76.8), null);


(lib.text1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#4A4A49").s().p("AhnAzQgJgEgIgHQgGgIgEgKQgEgKAAgMQAAgLAEgKQAEgKAGgIQAIgGAJgEQAKgFAMAAQAMAAAKAFQAJAEAIAGQAHAIAEAKQADAKAAALQAAAMgDAKQgEAKgHAIQgIAHgJAEQgKAEgMAAQgMAAgKgEgAhggmQgIADgEAFQgFAGgCAIQgEAHAAAJQAAAKAEAHQACAJAFAFQAEAFAIADQAGADAJgBQAJABAGgDQAIgDAEgFQAGgFACgJQADgHAAgKQAAgJgDgHQgCgIgGgGQgEgFgIgDQgGgCgJAAQgJAAgGACgADbA2IAAguIgQAAIgDAAIgEACIgCACIgDAEIgXAhIgEADQgDACgDAAIgNAAIgDgBIgCgDIgKgZIgvAAIgKAZIgCADIgDABIgMAAIAqhqIAQAAIAoBgIAUgdQAFgHAFgDQgGgBgEgCQgGgCgCgEQgDgDgCgFQgBgFgBgFQABgGACgGQACgGAFgEQAFgEAIgCQAHgCAIAAIAkAAIAABqgABoggIgBAEIgRAqIAoAAIgQgqIgCgEIgCgGIgCAGgAC7gnQgFACgCACQgDACgBADQgCAEABAEQgBAFACADQABAEADACIAHAEIAKAAIAWAAIAAgkIgWAAQgGgBgEACgAgSA2IAAhqIAiAAQALAAAGACQAHACAGADQAEADACAGQADAFAAAHQAAAEgCADIgEAHIgGAGQgDACgGABQAMACAGAGQAGAGAAAKQAAAHgCAGQgDAFgFAFQgFADgHACQgHADgJAAgAgCApIAWAAIAKgBQAEgBAEgCIADgGIABgIQABgJgGgEQgFgFgMAAIgWAAgAgCgEIARAAQAHgBAEgBIAHgEIAFgFQABgEAAgDQAAgKgGgEQgFgEgMAAIgSAAgAigA2IAAgxIg5AAIAAAxIgPAAIAAhqIAPAAIAAAvIA5AAIAAgvIAPAAIAABqg");
	this.shape.setTransform(0,-26.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#4A4A49").s().p("Ai5AzQgJgEgHgHQgHgIgDgKQgEgJAAgNQAAgLAEgKQAEgLAHgGQAHgIAJgEQAKgEAMAAQALAAAJAEQAJADAHAHIgFAHIgCABIgCABIgDgCIgFgDIgIgDQgEgCgHAAQgIAAgHAEQgHACgFAGQgFAFgCAHQgDAJAAAIQAAAKADAIQADAHAFAGQAEAFAHADQAHADAHAAIAJAAIAHgDIAGgDIAFgDIACgCIABAAIACABIAGAHQgGAHgKAFQgJAEgNAAQgMAAgKgEgADJA2IAAguIgPAAIgEABIgDABIgDACIgDAEIgXAgIgEAFQgCABgDAAIgMAAIAbgnQAFgGAGgDQgHgCgEgDQgFgBgDgEQgDgEgCgEQgBgFAAgFQAAgHACgGQADgFAFgEQAEgEAIgDQAHgCAJAAIAkAAIAABrgACpgnQgEABgDADQgDACgBAEQgBADAAAEQAAAFABADQABADADADIAHADIALABIAVAAIAAglIgVAAQgGAAgFACgABuA2IAAhKIAAgHIABgIIgDAHIgDAFIgxBIIgDAEIgEABIgLAAIAAhrIAPAAIAABKIAAAHIgBAIIADgHIADgFIAxhIIADgDIAEgCIALAAIAABrgAgqA2IAAhrIAhAAQAJABAHACQAIACAFAEQAFAFACAGQADAHAAAHQAAAIgDAFQgCAGgFAEQgFAFgIACQgHADgJAAIgRAAIAAAogAgaACIARAAQAGAAADgCIAIgDQADgDACgEQACgEAAgFQAAgFgCgEQgCgEgDgDQgDgDgEgBQgEgCgGAAIgRAAgAh2A2IAAhrIBCAAIAAANIgzAAIAAAiIApAAIAAAMIgpAAIAAAkIAzAAIAAAMg");
	this.shape_1.setTransform(0,-4.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#4A4A49").s().p("Aj5BDIAAgaIhWAAIAAAWIgBADIgDABIgJAAIAAglIALAAIAEgEIAFgHIADgMIAEgQIACgYIACggIBBAAIAABfIARAAIAAAhQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAIgDABgAkwgWIgFAXIgEARQgDAHgDAFIA0AAIAAhTIgjAAIgCAfgAgfAnQgJgEgIgIQgGgHgEgKQgEgKAAgMQAAgMAEgJQAEgLAGgHQAIgHAJgEQAKgEAMgBQALABAKAEQAJAEAIAHQAHAHAEALQADAJAAAMQAAAMgDAKQgEAKgHAHQgIAIgJAEQgKADgLAAQgMAAgKgDgAgYgyQgIADgEAFQgFAFgCAIQgEAIAAAJQAAAKAEAHQACAIAFAFQAEAFAIAEQAGACAJAAQAJAAAFgCQAIgEAEgFQAGgFACgIQADgHAAgKQAAgJgDgIQgCgIgGgFQgEgFgIgDQgFgDgJAAQgJAAgGADgAjbAqQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgJIAFAAIAEAAIADgCIAEgDIADgFIAEgKIgqhLIAOAAIADABIACADIAaAvIAEAKIACgFIADgFIAVgvIACgDIAEgBIAUAAIADAAIABACIAcAqIABgBIABgCIAagnQAAgBAAAAQABAAAAAAQABgBAAAAQAAAAABAAIAPAAIgjAzIAkA3IgQAAIgCgBIgBgBIgdgsIgBABIgBACIgbApIgCABIgCABIgPAAIAlg2IgeguIgpBXIgEAHIgGAEIgFADIgHAAIgHAAgAFOApIgDgBIgBgBIgdgsIAAABIgBACIgbApIgCABIgDABIgOAAIAlg2Igjg0IAPAAIADAAIABACIAbAqIABgBIABgCIAagnQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIAOAAIgjAzIAkA3gADqApIAAhqIAPAAIAABqgACNApIAAhqIAQAAIAAAuIAUAAQAJAAAIACQAHACAEAEQAGAEABAFQADAFAAAGQAAAIgDAFQgDAHgEADQgFAFgHACQgHACgKAAgACdAdIATAAIALgBQAEgCADgCQADgDACgDIABgHIgBgIIgFgFQgCgCgFgBQgEgCgGAAIgUAAgAA1ApIAAhqIAjAAQALAAAGACQAIACAFADQAEAEACAFQADAGAAAGQAAAEgCADIgEAHIgGAGQgDADgGABQAMADAGAFQAGAGAAAKQAAAGgCAGQgDAGgFAEQgFAEgHACQgHACgJAAgABFAdIAXAAIAKgBQAEgCAEgCIADgGIABgHQABgJgGgEQgFgEgMAAIgXAAgABFgRIASAAQAHAAAEgBIAHgEIAFgFQABgEAAgEQAAgJgGgFQgFgEgMAAIgTAAg");
	this.shape_2.setTransform(0,18.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#4A4A49").s().p("ACZA1QgKgEgHgIQgHgHgEgKQgEgKAAgMQAAgLAEgKQAEgKAHgIQAHgHAKgEQAJgEAMAAQAMAAAKAEQAKAEAHAHQAHAIAEAKQAEAKAAALQAAAMgEAKQgEAKgHAHQgHAIgKAEQgKAEgMAAQgMAAgJgEgACfgkQgHADgFAFQgFAGgCAHQgDAIAAAJQAAAKADAHQACAIAFAFQAFAGAHADQAHACAIAAQAJAAAHgCQAHgDAFgGQAFgFACgIQADgHAAgKQAAgJgDgIQgCgHgFgGQgFgFgHgDQgHgDgJAAQgIAAgHADgADuA4IAAhrIAiAAQALAAAHACQAHACAFAEQAEADACAGQADAFAAAGQAAAEgCAEIgDAHIgHAFQgDADgFAAQALADAGAGQAGAGAAAKQAAAHgCAGQgDAFgFAEQgFAEgHACQgHADgJAAgAD9ArIAXAAIAKgBQAFgBADgDIAEgGIABgHQAAgJgGgEQgFgFgMAAIgXAAgAD9gDIATAAQAGAAAEgBIAIgEIAEgFQABgEAAgEQAAgJgFgEQgGgFgMAAIgTAAgAA6A4IAAgNQgKAAgJgEQgIgDgGgGQgGgGgEgIQgDgIAAgIQAAgJADgHQAEgIAGgGQAGgGAIgDQAJgEAKAAIAAgNIAPAAIAAANQAKAAAIAEQAJADAGAGQAGAGADAIQAEAHAAAJQAAAIgEAIQgDAIgGAGQgGAGgJADQgIAEgKAAIAAANgABJAfQAGgBAGgCQAGgCAEgFQAEgEACgGQACgFAAgGQAAgGgCgGQgCgFgEgFQgEgEgGgCQgGgDgGAAgAAtgcQgFACgEAEQgEAFgDAFQgCAGAAAGQAAAGACAFQADAGAEAEQAEAFAFACQAGACAHABIAAg+QgHAAgGADgAAEA4IgDgBIgBgDIgKgZIgvAAIgKAZIgCADIgDABIgRAAIgEgBIgDgEIgbgnIgEgEIgHgBIgMAAIAAAxIgQAAIAAhrIAQAAIAAAvIALAAIADAAIACgBIADgCIACgCIAbgmIADgDIAEgBIANAAIggAsQgDAFgGACQAEAAADADIAFAGIAaAmIAohiIAPAAIAqBrgAgjgeIgCAEIgQAqIAnAAIgQgqIgCgEIgBgGIgCAGgAk5A4IAAhrIAPAAIAABfIAsAAIAAhfIAQAAIAABfIAsAAIAAhfIAPAAIAABrg");
	this.shape_3.setTransform(0,39.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text1, new cjs.Rectangle(-34.9,-32,69.9,77.3), null);


(lib.stext4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#28387B").s().p("AAwA7IgNhJIgZBJIgTAAIgZhJIgNBJIgWAAIAVh1IAWAAIAaBRIAchRIAWAAIAUB1g");
	this.shape.setTransform(31.9,25.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#28387B").s().p("AgrAsQgSgTAAgZQAAgQAIgPQAIgNAPgJQAPgJAPABQAZAAASASQATASAAAaQAAAZgSASQgSATgagBQgZAAgSgSgAgbgcQgLAMAAARQAAATAOAMQALAJANgBQAQAAAMgLQALgMAAgRQAAgQgLgMQgMgLgQAAQgQAAgLALg");
	this.shape_1.setTransform(17.5,25.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#28387B").s().p("AgiA7IAAh1IAYAAQARAAAKADQAIAEAFAIQAFAIAAALQAAAMgGAJQgHAHgLADQgGACgRAAIAAAygAgMgMIASgBQAEgCABgCQACgCAAgFQAAgHgFgDQgEgDgJAAIgHAAg");
	this.shape_2.setTransform(6.2,25.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#28387B").s().p("AAiA7IgKgYIgvAAIgKAYIgXAAIAuh1IAWAAIAtB1gAgPANIAfAAIgQgog");
	this.shape_3.setTransform(-4.8,25.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#28387B").s().p("AAUA7IAAhgIgnAAIAABgIgWAAIAAh1IBTAAIAAB1g");
	this.shape_4.setTransform(-16.5,25.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#28387B").s().p("AgnAsQgRgRAAgbQAAgRAHgOQAJgOAOgIQAQgJAQABQANgBAPAHQAOAGAJALIgPAQQgQgRgUgBQgRAAgLAMQgMAMAAAQQAAAMAGAJQAEAJAKAFQAIAGAMgBQALAAAHgDQAIgEAKgKIAPARQgOANgLAFQgMAEgOAAQgbABgSgTg");
	this.shape_5.setTransform(-33.1,25.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#28387B").s().p("AAVA7IAAhJIgrBJIgUAAIAAh1IAXAAIAABLIArhLIATAAIAAB1g");
	this.shape_6.setTransform(46.5,2.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#28387B").s().p("AARA7Igkg1IAAA1IgXAAIAAh1IAXAAIAAAoIAfgoIAbAAIgoA1IAsBAg");
	this.shape_7.setTransform(36.3,2.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#28387B").s().p("AgkA7IAAh1IATAAQAPgBAHADQAKACAHAIQAGAJAAAJQAAAIgCAFQgDAFgHAFQALAFAFAGQAFAKAAAIQAAAKgFAJQgFAIgIAEQgIAEgOAAgAgOAmIAGAAQANAAAFgEQAFgDAAgHQAAgIgGgEQgGgFgMAAIgFAAgAgOgMIAFAAQAJAAADgDQAEgEAAgFQAAgHgEgCQgEgEgHAAIgGAAg");
	this.shape_8.setTransform(26.1,2.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#28387B").s().p("AgrAsQgSgTAAgZQAAgQAJgPQAIgNAOgJQAPgJAPABQAZAAASASQATASAAAaQAAAZgSASQgSATgagBQgZAAgSgSgAgbgcQgLALAAASQAAATAOAMQALAJANgBQAQAAAMgLQALgMAAgRQAAgQgLgMQgLgLgRAAQgQAAgLALg");
	this.shape_9.setTransform(14.1,2.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#28387B").s().p("AAbA7IgbgqIgaAqIgaAAIAog8Iglg5IAZAAIAYAmIAZgmIAZAAIglA5IAoA8g");
	this.shape_10.setTransform(1.6,2.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#28387B").s().p("AgyAsIAPgPQAJAKAIAAQAEAAADgCIAGgGIgqhbIAZAAIAbBCIAXhCIAXAAIggBUQgHAVgKAIQgJAIgLAAQgRAAgPgRg");
	this.shape_11.setTransform(-9.3,2.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#28387B").s().p("AApBEIAAgRIhRAAIAAARIgWAAIAAgnIAOAAIAlhgIAXAAIAmBgIAMAAIAAAngAgZAdIAzAAIgahBg");
	this.shape_12.setTransform(-21,3.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#28387B").s().p("AgTA6QgKgFgJgMIARgMQAKAMALAAQAHAAAFgEQAFgFAAgIQAAgHgFgFQgFgFgOAAIgFAAIAAgTIAFAAQAJAAAEgEQAEgEAAgHQAAgHgDgDQgFgEgFAAQgHAAgIAIIgOgPQAMgKAGgBQAHgCAHAAQANgBAKAJQAKAJAAANIgCANQgCAGgKAHQAUAIAAAWQAAASgLAJQgLALgRgBQgKAAgJgEg");
	this.shape_13.setTransform(-36.7,2.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#28387B").s().p("AAVA7IAAhJIgsBJIgTAAIAAh1IAWAAIAABLIAshLIATAAIAAB1g");
	this.shape_14.setTransform(-46.5,2.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.stext4, new cjs.Rectangle(-50.8,-3.4,101.6,35.5), null);


(lib.stext1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#28387B").s().p("AAwA7IgNhJIgZBJIgTAAIgZhJIgNBJIgWAAIAVh1IAWAAIAaBRIAchRIAWAAIAUB1g");
	this.shape.setTransform(18.2,22);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#28387B").s().p("AAiA7IgKgYIgvAAIgKAYIgXAAIAuh1IAVAAIAuB1gAgPANIAfAAIgQgog");
	this.shape_1.setTransform(4.7,22);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#28387B").s().p("AgfA7IAAh1IA/AAIAAAWIgpAAIAAAVIApAAIAAAVIgpAAIAAAfIApAAIAAAWg");
	this.shape_2.setTransform(-5.4,22);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#28387B").s().p("AgLA7IAAhfIgVAAIAAgWIBBAAIAAAWIgWAAIAABfg");
	this.shape_3.setTransform(-13.5,22);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#28387B").s().p("AgUA4QgJgFgHgOIATgMQAIAQAKAAQAFAAAFgDQAEgEAAgEQAAgFgDgDQgEgFgIgIQgTgOgGgJQgGgIAAgJQAAgNAKgIQAJgJANAAQAJgBAIAFQAIAEAJALIgRAOQgJgMgJAAQgDAAgDACQgDADAAADQAAAEACABIAgAdQAGAGADAHQADAGAAAIQAAAPgKAIQgLAKgPAAQgLABgKgHg");
	this.shape_4.setTransform(-21.5,22);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#28387B").s().p("AgLA7IAAhfIgVAAIAAgWIBBAAIAAAWIgWAAIAABfg");
	this.shape_5.setTransform(22.6,3.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#28387B").s().p("AANA7IgZgyIgCAAIAAAyIgXAAIAAh1IAYAAQASAAAJADQAIAEAGAIQAEAIAAALQAAAMgFAIQgFAGgMAEIAcA1gAgOgMIAHAAQAKAAADgDQAFgCAAgHQAAgDgCgEIgFgEQgEgCgIAAIgGAAg");
	this.shape_6.setTransform(14.8,3.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#28387B").s().p("AAiA7IgJgYIgwAAIgKAYIgXAAIAuh1IAVAAIAuB1gAgPANIAfAAIgPgog");
	this.shape_7.setTransform(3.4,3.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#28387B").s().p("AAwA7IgNhJIgZBJIgTAAIgZhJIgNBJIgWAAIAVh1IAWAAIAaBRIAchRIAWAAIAUB1g");
	this.shape_8.setTransform(-10.1,3.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#28387B").s().p("AgUA4QgJgFgHgOIATgMQAIAQAKAAQAFAAAFgDQAEgEAAgEQAAgFgDgDIgMgNQgTgOgGgJQgGgKAAgHQAAgNAKgIQAJgJANAAQAJgBAIAFQAHADAKAMIgRAOQgJgMgJAAQgDAAgDACQgDADAAADQAAAEACABIAgAdQAGAGADAHQADAGAAAIQAAAPgKAIQgLAKgPAAQgLABgKgHg");
	this.shape_9.setTransform(-22.1,3.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.stext1, new cjs.Rectangle(-25.8,-2.7,51.7,31), null);


(lib.pic5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._5();
	this.instance.parent = this;
	this.instance.setTransform(-118,-92,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic5, new cjs.Rectangle(-118,-92,224.3,183.8), null);


(lib.pic4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._4();
	this.instance.parent = this;
	this.instance.setTransform(-90,-75,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic4, new cjs.Rectangle(-90,-75,180,150), null);


(lib.pic2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._2();
	this.instance.parent = this;
	this.instance.setTransform(-68,-67,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic2, new cjs.Rectangle(-68,-67,135,133.5), null);


(lib.pic1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-90,-75,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic1, new cjs.Rectangle(-90,-75,180,150), null);


(lib.legal3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACvAaIgEgCIgCgDIgBgEIABgEIAEgDIAHgDIAKgBIAAgCQAAgEgCgBQgBgDgEAAIgEABIgDABIgBACIgCAAIgBAAIgBgBIgBgCQADgDADgCIAIgBIAGABIADADQACACAAACIABAFIAAAWIgDAAIgBAAIgBgBIAAgDIgDACIgDABIgDABIgEABIgDgBgAC3ALIgFABIgDACIAAADIAAACIABACIACABIACAAIADAAIACgBIADgCIACgBIAAgIIgHABgAgHAaIgEgCIgCgDIAAgEIABgEIADgDIAHgDIAJgBIAAgCQAAgEgBgBQgCgDgDAAIgDABIgDABIgBACIgDAAIgBAAIgBgBIgBgCQADgDAEgCIAHgBIAFABIAEADQABACABACIABAFIAAAWIgDAAIgBAAIgCgBIAAgDIgDACIgCABIgDABIgDABIgEgBgAABALIgEABIgDACIgBADIABACIABACIACABIABAAIADAAIACgBIACgCIACgBIAAgIIgGABgAgqAaIgEgCIgCgDIAAgEIABgEIAEgDIAGgDIAKgBIAAgCQAAgEgBgBQgCgDgDAAIgEABIgDABIgBACIgCAAIgCAAIgBgBIgBgCQADgDAEgCIAIgBIAFABIAEADQACACAAACIABAFIAAAWIgDAAIgBAAIgBgBIgBgDIgDACIgCABIgDABIgFABIgDgBgAghALIgGABIgCACIgBADIABACIABACIABABIACAAIAEAAIACgBIACgCIACgBIAAgIIgGABgACIAaIAAgiIANAAIAGAAIADACIADADIAAADIAAACIgBACIgCACIgDACQAEAAACACQACACAAAEIgBAEIgDAEIgEACIgGAAgACOAWIAHAAQAEAAACgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAgBAAAAIAAgCIgBgCIgDgBIgEgBIgHAAgACOAGIAHAAIACAAIADgCIABgBIABgDIAAgBIgCgBIgCgBIgDgBIgHAAgAB4AaIAAgXIAAgCIAAgBIgBABIAAABIgBABIgDADIgCADIgDAEIgIAMIgBABIgBAAIgFAAIAAgiIAHAAIAAAWIAAACIAAABIABgCIABgBIABgDIAEgDIADgEIAIgLIABgBIABAAIAEAAIAAAigABFAaIAAgdIgNAAIAAgFIAhAAIAAAFIgNAAIAAAdgAAxAaIgCAAIgCgCIgGgLIgCgCIgEgBIgDAAIAAAQIgHAAIAAgiIAHAAIAAAOIADAAIADgBIACgBIAHgKIABgCIACAAIAFAAIgJAMIgCACIgCACIADABIACADIAJAOgAhRAaIAAgiIAOAAIAFAAIAEACIACADIABADIgBACIgBACIgBACIgEACQAEAAACACQACACAAAEIgBAEIgDAEIgDACIgGAAgAhLAWIAIAAQADAAADgCQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAIgBgCIgBgCIgDgBIgDgBIgIAAgAhLAGIAIAAIACAAIACgCIACgBIAAgDIAAgBIgCgBIgCgBIgCgBIgIAAgAhbAaIgDAAIgBgCIgHgLIgCgCIgDgBIgEAAIAAAQIgGAAIAAgiIAGAAIAAAOIADAAIAEgBIABgBIAIgKIABgCIABAAIAGAAIgJAMIgCACIgDACIAEABIACADIAJAOgAiAAaIgBAAIgBgBIgFgMIgWAAIgFAMIgBABIgBAAIgFAAIAUgxIAHAAIAUAxgAiTgNIgBACIgHATIASAAIgHgTIgBgCIgBgDIgBADgAi6gDIAAgHIAAgBIAAgBIgBACIgGADIgCgDIAFgDIACgBIABAAIgDgBIgFgEIACgCIAGADIABACIAAgBIAAgCIAAgHIADAAIAAAHIAAACIAAAAIABgBIAHgDIABADIgGADIgBABIgCAAIADABIAGADIgBADIgHgDIgBgBIgBgBIABACIAAAHg");
	this.shape.setTransform(21.6,3.2,1.2,1.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal3, new cjs.Rectangle(-2,0,47.2,6.5), null);


(lib.legal2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AC9AnIAAg4IAEAAQABAAAAAAQAAAAAAAAQABABAAAAQAAABAAAAIAAAFQAEgEADgCQADgBAFAAQADgBAEACQACABACADQADADABADQABAFABAEQgBAFgBAEQgBAEgDADQgCADgDABQgEADgEAAQgEAAgDgCIgFgEIAAATgADJgJIgFAEIAAATQACADADABQACABADAAQAGAAADgEQADgEAAgIIAAgGIgDgFIgDgCQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQgEABgDACgAD2AXQgEgBgDgDQgDgCgBgEIgBgKIABgIQABgEADgDQADgCAEgCQADgCAFABQAEgBAFACQADACADACQACADACAEQACAEgBAEQABAFgCAFIgEAGQgDADgDABQgFADgEAAQgFAAgDgDgAD1gHQgDAEgBAGQABAIADAEQADAEAGAAQAGAAADgEQADgEAAgIQAAgGgDgEQgDgFgGAAQgGAAgDAFgACWAZIgDgDIgDgDIgBgFIACgFIAEgEQADgCAFgBIAMgBIAAgCQAAgFgCgCQgCgDgEgBQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAIgDABIgCACIgCAAIgCAAIAAgBIgBgDQADgDAEgCIAJgBQADgBADACIAFADQADACAAADIABAHIAAAaIgDAAIgCgBIgBgBIgBgEIgDADIgDABIgFACIgEABIgFgBgAChAHIgGABQgBAAAAABQgBAAAAAAQAAAAgBABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAIABADIACABQAAAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAIACABIAEgBIADgBIADgBIACgDIAAgJIgIACgAAvAYQgDgCgDgDIgEgGIgBgKIABgHQABgFACgDQADgDAEgBQAEgBAFAAQAEgBAEACIAFAEIgCADIgBABIAAAAIgBAAIgCgBIgDgCIgEgBQgDAAgDACQAAAAgBABQAAAAgBAAQAAABAAAAQgBAAAAABQgCACAAACIgCAGIACAHQAAADACACQAAAAABABQAAAAAAABQABAAAAAAQABABAAAAQADABADAAIAEAAIADgCIACgBIABgBIACABIACADIgEADIgDABIgEACIgFABQgEAAgDgCgAgUAZIgEgDIgCgDIgCgFIACgFIAEgEQAEgCAEgBIAMgBIAAgCQAAgFgBgCQgDgDgEgBQAAAAgBABQAAAAgBAAQAAAAgBAAQgBABAAAAIgDABIgDACIgCAAIgBAAIgBgBIgBgDQADgDAFgCQADgCAGABQADgBADACIAEADIACAFIABAHIAAAaIgDAAIgCgBIAAgBIgBgEIgDADIgDABQgBABAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAIgEABIgFgBgAgKAHIgFABQgBAAgBABQAAAAgBAAQAAAAAAABQAAAAgBAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAAAIAAADIACABQAAAAABABQAAAAAAAAQAAAAABAAQAAAAABAAIABABIAEgBIAEgBIACgBIACgDIAAgJIgIACgAiVAXQgDgBgDgDQgDgCgBgEQgBgFAAgFIABgIQABgEADgDQADgCADgCQAEgCAFABQAFgBAEACQADACADACIAEAHIABAIIgBAKIgEAGQgDADgDABQgEADgFAAQgFAAgEgDgAiVgHQgDAEAAAGQAAAIADAEQADAEAGAAQAGAAADgEQADgEAAgIQAAgGgDgEQgDgFgGAAQgGAAgDAFgAjvAXQgEgBgDgDQgCgCgBgEQgCgFAAgFIACgIQABgEACgDQADgCAEgCQAEgCAFABQAEgBAEACQAEACADACQACADABAEIACAIQAAAFgCAFIgDAGQgDADgEABQgEADgEAAQgFAAgEgDgAjwgHQgDAEAAAGQAAAIADAEQADAEAHAAQAFAAAEgEQACgEAAgIQAAgGgCgEQgEgFgFAAQgHAAgDAFgAFEAZIAAgbIABgCIAAgDIgPAYIgBABIgBABIAAAAIgCgBIgBgBIgOgYIAAADIAAACIAAAbIgHAAIAAgqIAGAAIABAAIACACIANAUIABADIABACIABgCIAAgDIANgUIACgCIACAAIAFAAIAAAqgAB/AZIAAgkIgUAAIAAAkIgIAAIAAgqIAkAAIAAAqgAglAZIgDgBIgCgCIgIgNIgCgCQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIgEAAIAAAUIgIAAIAAgqIAIAAIAAARIADAAIAEAAIACgBIAJgOIABgBIACgBIAHAAIgLARIgCABIgDABQABABAAAAQABAAAAAAQABAAAAABQAAAAABAAIACAEIAKARgAhuAZIAAgqIAQAAIAHABIAEACIADADIABAEIgBADIgBAEIgDABIgDABQAEABADACQACADABAEIgBAGIgFAEIgEACIgHABgAhnATIAJAAQAEABADgCQADgDgBgDIAAgCIgBgCIgDgCIgFgBIgJAAgAhnAAIAJAAIACAAIAEAAIABgDIABgDIAAgCIgCgBIgDgCIgDgBIgJAAgAi9AZIAAgkIgQAAIAAgGIAoAAIAAAGIgRAAIAAAkgAkkAZIAAg7IAkAAIAAAHIgbAAIAAA0gAlAgKIAAgIIAAgCIAAgCIgBADIgIADIgBgCIAHgFIACgBIABAAIgDgBIgHgFIABgDIAIAFIABACIAAgBIAAgDIAAgIIAEAAIAAAIIAAADIAAAAIACgBIAHgFIACAEIgHAEIgBABIgCAAIADABIAHAFIgCADIgHgEIgBgCIgCgBIABAEIAAAIg");
	this.shape.setTransform(31.2,3.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiPAnIAAgOIgkAAIAAgqIAIAAIAAAjIAUAAIAAgjIAIAAIAAAjIAHAAIAAASIAAACIgCABgAjyAnIAAgOIgjAAIAAAMIgBABIgCABIgEAAIAAgVIABAAIADAAIADgCIACgEIACgGIACgJIABgOIAbAAIAAAjIAIAAIAAASIgBACIgCABgAlxAnIAAg4IAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAFIAHgGQADgBAFAAIAGAAQADACACADIAEAGIABAJIgBAJIgEAGIgGAGIgIABIgGgBIgFgEIAAATgAlkgKIgFAFIAAAUIAEADIAFABQAGAAADgEQADgEAAgIIAAgGIgDgFQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAAAgBAAIgEgBQgDAAgDABgAGuAZIgEgDIgCgEIgBgEIABgFQACgDADgBQADgCAFgBQAFgBAHgBIAAgBQAAgFgCgDQgCgCgEAAIgFABIgDABIgCABIgCABIgCgBIgBgBIgBgCQAEgEAEgCIAJAAIAGAAIAFADQACADABADIABAHIAAAaIgEAAIgCgBIgBgBIAAgEIgDACIgEADIgEABIgEAAIgFAAgAG5AHIgGABIgDACIgCAEIABACIABACIADABIACABIAEgBIADgBIADgCIACgBIAAgJIgIABgAEuAYQgEgCgDgDQgDgDgBgEIgBgJIABgIQABgEADgCQADgEAEgCIAIAAIAJAAIAGAGIAFAGIABAIIgBAJIgFAHQgDADgDACQgEABgFAAQgEAAgEgBgAEtgIQgDAFAAAGQAAAIADAEQADAEAGAAQAGAAADgEQADgEAAgIQAAgGgDgFQgDgDgGAAQgGAAgDADgADTAYQgEgCgCgDQgDgDgBgEQgCgEAAgFQAAgEACgEQABgEADgCQACgEAEgCIAJAAIAIAAIAHAGIAEAGIABAIIgBAJIgEAHQgDADgEACQgDABgFAAQgFAAgEgBgADSgIQgDAFAAAGQAAAIADAEQADAEAHAAQAGAAADgEQADgEAAgIQAAgGgDgFQgDgDgGAAQgHAAgDADgABDAZQgBgBAAAAQgBAAgBAAQAAgBAAAAQgBgBAAAAIgDgEIgBgEIACgFQABgDADgBQADgCAFgBQAFgBAHgBIAAgBQAAgFgBgDQgDgCgEAAIgEABIgEABIgCABIgCABIgBgBIgBgBIgCgCIAIgGIAJAAIAHAAIAEADIADAGIABAHIAAAaIgDAAIgCgBIgBgBIgBgEIgDACIgEADIgDABIgFAAIgEAAgABNAHIgGABIgDACIgBAEIAAACIACACIACABIACABIAEgBIADgBIADgCIACgBIAAgJIgIABgAhGAYQgEgCgCgDQgDgDgBgEQgCgEAAgFQAAgEACgEQABgEADgCQACgEAEgCIAJAAIAIAAIAHAGIAEAGIABAIIgBAJIgEAHQgDADgEACQgDABgFAAQgFAAgEgBgAhHgIQgDAFAAAGQAAAIADAEQADAEAHAAQAGAAADgEQADgEAAgIQAAgGgDgFQgDgDgGAAQgHAAgDADgAk9AZQgDgBgCgCIgCgEQAAAAAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAgCACgDQABgDADgBQADgCAFgBQAFgBAHgBIAAgBQAAgFgCgDQgCgCgEAAIgEABIgEABIgCABIgCABIgBgBIgCgBIgBgCQAEgEAEgCIAJAAIAHAAIAEADQACADABADQABADAAAEIAAAaIgEAAIgBgBIgCgBIAAgEIgDACIgEADIgDABIgFAAIgEAAgAkzAHIgGABIgDACIgBAEIAAACIABACIADABIACABIAEgBIADgBIADgCIACgBIAAgJIgIABgAGeAZIgDgBIgDgDIgIgMIgCgCIgEgBIgEAAIAAATIgIAAIAAgqIAIAAIAAARIAEAAIADAAIACgBIAJgOIABgCIADAAIAGAAIgLAQIgCABIgDACIAEACIACADIALASgAFUAZIAAgqIAQAAIAHAAIAEADIADADIABAEIgBADIgBADIgCABIgEACQAEABADADQADACAAAEIgBAFIgEAEIgFADIgGABgAFcATIAJAAQAEAAACgCQADgCAAgDIgBgDIgBgCIgDgBIgEAAIgJAAgAFcAAIAIAAIADAAIADgBIABgBIABgEIAAgCIgCgCIgCgBIgEAAIgIAAgAEFAZIAAgkIgQAAIAAgGIAoAAIAAAGIgQAAIAAAkgACnAZIAAgqIAcAAIAAAGIgUAAIAAAkgAB/AZIAAgSIgDAAIgCAAIgCABIAAAAIgCABIgJAMIgBADIgDABIgGAAIAMgRQABgCADAAIgFgDIgEgCIgBgCQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIACgEQAAgCADgDIAEgCIAIgBIAPAAIAAAqgAB0gLQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIgCACIAAACQAAAEACABQADACAEAAIAGAAIAAgNIgHAAIgEAAgAArAZIAAgUIgUAAIAAAUIgIAAIAAgqIAIAAIAAARIAUAAIAAgRIAIAAIAAAqgAgEAZIAAgUIgTAAIAAAUIgIAAIAAgqIAIAAIAAARIATAAIAAgRIAHAAIAAAqgAhjAZIAAgbIAAgDIAAgBIgBABIAAABIgBACIgDACIgDAEIgDAFIgLAOIAAABIgCABIgFAAIAAgqIAIAAIAAAbIAAACIgBACIACgDIABgCIACgCIAEgFIADgDIAKgOIABgCIACAAIAFAAIAAAqgAjHAZIAAgbIAAgDIAAgBIAAABIgBABIgBACIgCACIgDAEIgEAFIgKAOIgBABIgCABIgEAAIAAgqIAHAAIAAAbIAAACIAAACIACgDIABgCIACgCIADgFIAEgDIAJgOIACgCIABAAIAFAAIAAAqgAmUAZIAAg0IgUAAIAAgIIAwAAIAAAIIgTAAIAAA0gAm9gKIAAgJIAAgBIAAgCIgBADIgIADIgCgDIAHgEIACgBIABAAIgDgCIgHgDIACgEIAIAFIABABIAAgBIAAgBIAAgJIAEAAIAAAJIAAABIAAABIACgBIAHgFIACAEIgHADIgCACIgBAAIADABIAHAEIgCAEIgHgEIgBgBIgCgCIABADIAAAJg");
	this.shape_1.setTransform(45.7,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal2, new cjs.Rectangle(-2,0,93.4,18.8), null);


(lib.legal1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglAnIAAg4IAFAAIACACIABAFQADgEADgCQAEgBAFAAQADgBADACQADABABADIAEAGIABAJIgBAJIgEAHQgBADgFABQgDADgEAAQgDAAgDgCIgGgEIAAATgAgXgJIgGAEIAAATIAFAEQACABADAAQAGAAADgEQADgEAAgIIAAgGIgDgFIgDgCQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAQgDABgDACgAA9AYQgDgCgCgDIgFgGIgBgKIABgHQABgFADgDQADgDADgBQAFgBAEAAQAFgBADACIAHAEIgDADIAAABIgBAAIgCAAIgCgBIgCgCIgFgBQgDAAgBACIgFADIgCAEQgBADAAADQAAAFABACIACAFIAFADQABABADAAIAFAAIADgCIABgBIACgBIACABIACADIgDADIgEABIgEACIgFABQgFAAgDgCgAhKAZIgEgDIgCgDQgCgCAAgDQAAgCACgDIAEgEQADgCAGgBIALgBIAAgCQAAgFgCgCQgCgDgEgBQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAIgDABIgDACIgCAAIgBAAIgBgBIgBgDQADgDAFgCQADgCAGABQADgBADACIAEADQACACABADQACADgBAEIAAAaIgDAAIgCgBIgCgBIAAgEIgDADIgDABIgEACIgFABIgEgBgAhAAHIgGABQgBAAAAABQgBAAAAAAQAAAAgBABQAAAAAAAAIgBAEIAAADIABABIADABIADABIADgBQABAAAAAAQAAAAABAAQAAAAAAAAQABgBAAAAIADgBIACgDIAAgJIgIACgAiyAXQgGgCgEgEQgDgEgCgFQgDgHAAgFQAAgHADgGQACgGAEgDQAEgFAFgCQAGgDAGABQAGgBAFADQAGACADAEIgDADIAAABQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgBgCIgDgBIgFgCIgGAAQgFAAgEABQgDABgDADQgDAEgBADQgCAFAAAGQAAAEACAEQABAFADACIAGAGIAJABIAFAAIADgBIADgCIAEgCIAAgBIACAAIAAABIAEAEQgEAEgFACQgGADgHAAQgGAAgFgDgADhAZIAAgbIAAgCIAAgDIgOAYIgBABIgCABIAAAAIgBgBIgCgBIgOgYIAAADIABACIAAAbIgIAAIAAgqIAGAAIACAAIABACIAOAUIAAADIABACIABgCIABgDIAMgUIABgCIADAAIAFAAIAAAqgAClAZIAAgcIAAgBIAAgCIgBABIgBABIgBACIgDACIgDAEIgDAFIgLAOIAAABIgCABIgEAAIAAgqIAIAAIAAAbIAAACIgBACIACgDIABgBIABgDIAEgFIAEgDIAKgOIABgBIABgBIAFAAIAAAqgABoAZIAAgkIgQAAIAAgGIApAAIAAAGIgRAAIAAAkgAAVAZIAAgkIgQAAIAAgGIApAAIAAAGIgQAAIAAAkgAhhAZIAAgbIAAgCIAAgDIgPAYIAAABIgBABIgBAAIgBgBIgBgBIgPgYIAAADIAAACIAAAbIgHAAIAAgqIAHAAIABAAIABACIAOAUIAAADIACACIAAgCIABgDIAMgUIACgCIACAAIAFAAIAAAqgAjcgKIAAgIIAAgCIAAgCIgBADIgIADIgBgCIAHgFIACgBIAAAAIgCgBIgHgFIABgDIAIAFIABACIAAgBIAAgDIAAgIIAFAAIAAAIIAAADIAAAAIABgBIAIgFIABAEIgHAEIgBABIgCAAIADABIAHAFIgBADIgIgEIgBgCIgCgBIACAEIAAAIg");
	this.shape.setTransform(21.2,3.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal1, new cjs.Rectangle(-2,0,46.3,7.8), null);


(lib.legal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABeC6IgFgDIgEgEIgCgGIADgBIADgBQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAABABIABACIACADIADACIAFABIAGgBIADgDIACgDIABgDIgBgFQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgEgDIgHAAIAAgGIAFgBQABAAABAAQABgBAAAAQABAAAAAAQABgBAAAAIACgDIABgEIgBgEIgCgDIgDgCIgEAAIgEAAIgDACIgDACIgBAEIgBACIgCAAIgFgBIACgHIAFgFIAFgDIAHgBIAHABQADABADACIADAEIABAHIAAAEIgCAFIgEACIgEACQAGACADADQADADgBAGQABADgCADQgCAEgCACQgCACgEABIgIACIgIgCgAAwC7IgEgBIgEgCIgCgCIABgEIACgBIADAAIACACIADACIAFAAIAFgBIAEgDQAAAAABAAQAAgBABAAQAAgBAAAAQAAgBAAgBIABgFIAAgFIgCgEIgFgCIgEgBIgKACIgFgCIAFgbIAcAAIAAAEIgBADIgEABIgSAAIgCAOIAIgBQAFAAADACIAFADQADADABADIABAGQAAAFgBAEQgCADgDADQgCADgEABQgEACgEAAIgGgBgAgsC6QgEgCgCgDQgDgEgCgFQgCgGAAgIQAAgHACgGQACgFADgEQACgEAEgCIAIgBQAEAAAFABIAGAGQADAEACAFQABAGAAAHQAAAIgBAGQgCAFgDAEIgGAFQgFACgEAAIgIgCgAgpCJIgEADIgDAHIgBALIABALIADAHIAEAEIAFABIAFgBQADgBABgDIADgHIABgLIgBgLQgBgEgCgDQgBgDgDAAIgFgBIgFABgAiJC6QgEgCgCgDQgEgEgBgFQgBgGAAgIQAAgHABgGQABgFAEgEQACgEAEgCIAIgBQAEAAAEABIAHAGQADAEABAFQACAGAAAHQAAAIgCAGQgBAFgDAEIgHAFQgEACgEAAIgIgCgAiGCJIgEADIgDAHIgBALIABALIADAHIAEAEIAFABIAFgBQADgBABgDIADgHIABgLIgBgLQgBgEgCgDQgBgDgDAAIgFgBIgFABgAi3C6IgGgEIgEgGQgBgDAAgFQAAgEABgEQACgFAEgEIAOgUIACgBIACgBIAHAAIgRAWIgBACIgCACIAFgCIAEgBQAEAAADABIAGADQACACABAEQABADAAAEQAAAEgBADIgEAGIgGAEIgIACIgIgCgAi0CeIgEADIgCAEIgBAEIABAFIACAEIAEADIAEABIAGgBIADgDIADgEIABgEIgBgGQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAIgDgDIgFgBIgFABgAmgC6QgEgCgCgDQgEgEgBgFQgBgGAAgIQAAgHABgGQABgFAEgEQACgEAEgCIAIgBQAEAAAEABIAHAGQADAEABAFQACAGAAAHQAAAIgCAGQgBAFgDAEIgHAFQgEACgEAAIgIgCgAmdCJIgEADIgDAHIgBALIABALIADAHIAEAEIAFABIAFgBQADgBABgDIADgHIABgLIgBgLQgBgEgCgDQgBgDgDAAIgFgBIgFABgAq2C5QgFgCgEgDQgDgEgDgGQgCgFAAgHQAAgGACgFQADgGADgEIAJgGQAFgCAHAAQAGAAAFACQAFACAEAEQAEAEACAGQACAFAAAGQAAAHgCAFQgCAGgEAEQgEADgFACQgFACgGABQgHgBgFgCgAqyCJQgEACgDADIgEAHQgBAEAAAFQAAAGABADIAEAHQADADAEACQADABAFABQAEgBAEgBQADgCADgDQADgCABgFQABgDAAgGQAAgFgBgEQgBgEgDgDQgDgDgDgCQgEgBgEAAQgFAAgDABgAAPC7IAAgPIgXAAIgCAAIgBgBIgBgFIAbglIAHAAIAAAlIAIAAIAAAFIAAABIgBAAIgHAAIAAAPgAgECmIATAAIAAgWIAAgDIABgDgAhgC7IAYgvIACgDIgdAAIgCgBIgBgBIAAgGIAoAAIAAAEIAAADIgBABIgYAvIgBACIgCABgAjrC7IARgXIACgCIACgCQgCACgDABIgGABIgGgBIgFgEQgCgCgBgDQgCgDAAgEIACgHIADgGIAGgEQAEgBAEAAQAFAAADABQADABACADQADADABADQABAEAAADIAAAGIgBADIgCAFIgDAEIgOAUIgBABIgDABgAjjCIIgDACIgCAEIgBAFQAAAFACADQAEADAFgBIAEAAIAFgCIABgEIABgEIgBgFIgCgEIgEgCIgEAAIgFAAgAkaC7IAYgvIACgDIgdAAIgCgBIAAgBIAAgGIAnAAIAAAEIgBADIAAABIgYAvIgBACIgCABgAlJC7IAYgvIADgDIgeAAIgBgBIgBgBIAAgGIAoAAIAAAEIgBADIAAABIgYAvIgCACIgCABgAlkC7IAAgPIgZAAIgBAAIgBgBIgBgFIAcglIAHAAIAAAlIAJAAIAAAFIAAABIgCAAIgHAAIAAAPgAl3CmIATAAIAAgWIAAgDIABgDgAnTC7IAAgGIALAAIAAgmIAAgEIgJAJIgBAAIgBAAIgBAAIgBgBIgCgCIARgQIAGAAIAAA0IALAAIAAAGgAoBC7IAAgaIgfAAIAAAaIgIAAIAAg6IAIAAIAAAaIAfAAIAAgaIAIAAIAAA6gApYC7IAAg6IARAAQAGABAEABQADABADADQADACABADQACAEgBADQABAEgCAEIgEAGIgHADQgEACgFAAIgJAAIAAAVgApQCfIAJAAIAFgBIAFgCIACgEIABgFIgBgEIgCgEIgEgCIgGgBIgJAAgAqEC7IAAg6IAjAAIAAAHIgaAAIAAAzgAhNBSIgEgBIgEgDIgDgCIACgDIACgBIACAAIADACIADABIAFAAIAEgBIAFgCQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAAAgBIABgFIAAgGIgDgDIgEgCIgFgBIgJACIgFgCIAFgbIAbAAIAAAEIgBACIgEABIgRAAIgDAPIAJgBQAEAAADABIAGADQADADABADIABAHQgBAEgBAFQgCADgDACQgCADgEACQgEABgEAAIgFAAgAiqBRQgEgCgDgEQgDgEgCgFQgBgFAAgIQAAgHABgHQACgFADgEQADgDAEgCIAIgCQAEAAAEACIAGAFQADAEACAFQABAHABAHQgBAIgBAFQgCAFgDAEIgGAGQgEABgEAAIgIgBgAinAfIgEAEIgEAHIgBALIABALIAEAHIAEADIAFABIAEgBQADgBACgCIADgHIABgLIgBgLQgBgEgCgDQgCgDgDgBIgEgBIgFABgAk2BSIgEgBIgEgDIgDgCIACgDIACgBIADAAIACACIADABIAFAAIAFgBIAEgCQAAAAABgBQAAAAABgBQAAAAAAgBQAAAAAAgBIABgFIAAgGIgCgDIgFgCIgEgBIgKACIgFgCIAFgbIAcAAIAAAEIgBACIgEABIgSAAIgCAPIAIgBQAFAAADABIAGADQACADABADIABAHQAAAEgBAFQgCADgDACQgCADgEACQgEABgEAAIgGAAgAmTBRQgEgCgDgEQgDgEgBgFQgCgFAAgIQAAgHACgHQABgFADgEQADgDAEgCIAIgCQAFAAAEACIAGAFQADAEACAFQABAHAAAHQAAAIgBAFQgCAFgDAEIgGAGQgEABgFAAIgIgBgAmQAfIgEAEIgDAHIgBALIABALIADAHIAEADIAFABIAFgBQACgBACgCIADgHIABgLIgBgLQgBgEgCgDQgCgDgCgBIgFgBIgFABgAiBBSIAAgHIAMAAIAAglIAAgEIgJAIIgCABIgBAAIgBgBIgBAAIgBgDIARgPIAFAAIAAAzIAMAAIAAAHgAjlBSIAAgDIABgCIABgCIASgSIAFgEIACgFIACgDIABgGIgBgDIgCgEIgDgCIgEAAIgDAAIgEACIgCADIgCADIgBACIgCAAIgEgBIACgHIAEgEIAGgEIAGgBIAHABIAGAEQADACAAADQACADAAADIgBAHIgCAEIgEAGIgFAEIgPAPIAEgBIADAAIASAAIACABIABACIAAAFgAkMBSIAAgHIALAAIAAglIAAgEIgJAIIgBABIgBAAIgBgBIgBAAIgCgDIARgPIAGAAIAAAzIALAAIAAAHgAlWBSIAAgQIgZAAIgCAAIgBgBIgBgEIAcglIAHAAIAAAkIAIAAIAAAFIAAABIgBAAIgHAAIAAAQgAlrA8IAVAAIAAgWIAAgCIAAgDgAnHBSIAYgvIACgEIgdAAIgCgBIgBgBIAAgFIAoAAIAAAEIAAACIgBABIgYAwIgBACIgCABgAn1BSIAXgvIADgEIgeAAIgCgBIAAgBIAAgFIAoAAIAAAEIgBACIAAABIgYAwIgBACIgDABgAojBSIAAgaIgeAAIAAAaIgIAAIAAg6IAIAAIAAAZIAeAAIAAgZIAJAAIAAA6gApgBSIAAgaIgeAAIAAAaIgIAAIAAg6IAIAAIAAAZIAeAAIAAgZIAIAAIAAA6gAqdBSIAAgpIAAgDIAAgFIgBAEIgCADIgaAnIgBACIgCABIgGAAIAAg6IAIAAIAAAoIAAADIAAAFIABgEIABgCIAagnIACgCIADgBIAFAAIAAA6gAJugJIAAgOIgiAAIAAALIAAACIgCABIgFAAIAAgUIACAAIADAAIACgCIACgEIADgGIABgKIABgMIAaAAIAAAiIAIAAIAAARIgBADIgCAAgACAgJIAAgOIg3AAIAAgoIAHAAIAAAiIAQAAIAAgiIAIAAIAAAiIAQAAIAAgiIAIAAIAAAiIAHAAIAAARIgBADIgCAAgAg2gJIAAgOIgiAAIAAALIgBACIgBABIgFAAIAAgUIACAAIADAAIACgCIACgEIACgGIABgKIACgMIAZAAIAAAiIAIAAIAAARIgBADIgBAAgAkDgJIAAg2IAEAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIABAEIAFgEQAEgCAEgBQAEAAADACIAEAEQACACACAFIABAJIgBAIIgEAGIgFAFQgEACgEgBIgGAAIgFgEIAAASgAj3g5IgFAFIAAATQACADACAAIAGABQAFAAADgDQADgEAAgHIgBgHIgCgFIgDgDIgEAAQgDAAgDABgAIigOIAAgBIABAAIABgCIACgBIABgDIAAgCIAAAAIgCAAIgBgBIgCgCIAAgCQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQAAAAABAAIACABIACABIABACIAAACIgBAEIgBAEIgDAEIgCADgAlmgOIAAgBIABAAIAAgCIACgBIABgDIABgCIgBAAIgCAAIgBgBIgBgCIAAgCQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAAAIADABIACABIABACIAAACIgBAEIgBAEIgDAEIgDADgAKtgXQgEgCgDgCIgDgFIgBgHQAAgFACgEQADgDAGgCQgFgCgCgDQgDgEAAgEIACgGIADgFIAGgDIAHgBIAHABIAFADIAEAFIABAGQAAAEgCAEQgDADgEACQAGACADADQACAEAAAFQAAAEgBADQgCADgDACQgCACgDACIgIAAIgIAAgAKwgxIgDACIgDADIgBAFIABAFIACACIAEADIAFAAIAEAAIAFgDIACgCIABgFIgBgFIgDgDIgEgCIgEgBIgFABgAKwhLIgDADIgBADIgBADIAAAEIACADIADACIAFABIAEgBIAEgCIABgDIABgEIgBgDIgCgDIgDgDIgEAAIgFAAgAJ+gXIgDgBIgBgBIAAgCIAAgDIABgCIADAAIACgBIABABIACAAIABACIAAADIAAACIgBABIgCABIgBAAIgCAAgADygYQgDgBgDgDQgDgCgBgEQgCgFAAgEQAAgFACgDQABgEADgEIAGgDQAEgCAEAAIAHABIAHAEIgCADIgBAAIgBABIgCgBIgCgBIgCgBIgDgBIgGABIgDAEIgDAEIgBAHIABAGQABABAAAAQAAABAAABQAAAAABABQAAAAABABIADACIAFABIAFAAIACgCIACgBIACAAIABAAIACADIgDADIgEACIgEABIgFAAIgGgBgAAkgYIgGgEIgEgGQgCgFAAgEQAAgFACgEQABgEADgDQADgDADgBIAJgBIAIABQADABACADQADADACAEIABAJIgBAJIgFAGIgFAEIgIABQgFABgEgCgAAkg2QgEADAAAIQAAAHAEAEQACADAHAAQAFAAADgDQADgEAAgHQAAgIgDgDQgDgFgFAAQgHAAgCAFgAh3gXIgEgBIgEgCIgDgDIACgDIACAAIABAAIACABIADACIAFAAIADAAIADgCIACgBIABgDQgBgDgCgCQgCgBgFgBIgFAAIAAgFIAFAAQAEAAACgCQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAAAIAAgDIgDgCIgCgBIgDgBIgFABIgCABIgCABIgBAAIgBAAIgCgBIgBgDIAGgDIAIgBIAGABIAFACIACADIABAFIAAACIgBACIgCACIgDADQADAAACADQACACABAFIgCAEIgDAFIgGACIgFAAIgEAAgAifgYIgHgEIgEgHQgBgEAAgFQAAgEABgEIAEgHQACgCAEgBQAEgCAEAAIAGABQADABADACQACADABADQACADAAAFIAAADIgCAAIgbAAIACAHQAAACACACQAAABABAAQAAAAABABQAAAAABAAQAAAAAAAAIAGABIAEAAIAEgCIACgBIABAAIACAAIACADIgDADIgEACIgFABIgEAAQgEABgDgCgAigg4QgDADgBAFIAWAAIAAgEIgCgEIgEgCIgEgBQgFABgDACgAjNgYIgHgEIgDgGQgCgFAAgEQAAgFACgEQABgEACgDQADgDAEgBIAIgBIAIABQAEABACADQACADACAEIABAJIgBAJIgEAGIgGAEIgIABQgEABgEgCgAjOg2QgDADAAAIQAAAHADAEQADADAGAAQAFAAAEgDQACgEAAgHQAAgIgCgDQgEgFgFAAQgGAAgDAFgAmJgXIgDgCIgDgEIgBgEIABgFQACgCADgCIAHgCIAMgCIAAgDQAAgFgCgCQgCgCgEAAIgEAAIgDACIgCACIgCAAIgBAAIgBgCIgCgCQADgDAEgBQAEgCAFgBQADAAADACQADABABACIAEAFIABAGIAAAaIgEAAIgCAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIgBgEIgCADIgEACIgDABIgFAAIgEAAgAl/gpIgGACIgDADIAAADIAAACIABACIACABIADABIADgBIADgBIADgCIACgCIAAgIIgIAAgAn8gYQgDgBgCgDQgDgCgCgEQgBgFAAgEQAAgFABgDQACgEACgEIAGgDQAEgCAEAAIAIABIAGAEIgCADIgBAAIgBABIgBgBIgCgBIgCgBIgEgBIgFABIgEAEIgCAEIgBAHIABAGQAAABAAAAQAAABABABQAAAAAAABQABAAAAABIAEACIAEABIAFAAIADgCIABgBIACAAIABAAIADADIgEADIgDACIgFABIgEAAIgHgBgAopgYIgGgEIgEgGQgCgFABgEQgBgFACgEQACgEACgDQACgDAEgBIAIgBIAIABQAEABADADQACADABAEIABAJIgBAJIgDAGIgHAEIgIABQgEABgEgCgAoqg2QgCADAAAIQAAAHACAEQAEADAFAAQAGAAADgDQADgEAAgHQAAgIgDgDQgDgFgGAAQgFAAgEAFgAqigXIgCgBIgBgBIAAgCIAAgDIABgCIACAAIACgBIACABIABAAIABACIABADIgBACIgBABIgBABIgCAAIgCAAgAIRgXIAAgbIAAgBIABgCIgCABIAAABIgBABIgCADIgDAFIgEAEIgJANIgCACIgBAAIgFAAIAAgoIAIAAIAAAbIAAABIAAACIABgDIABgBIADgDIACgEIAEgFIAKgMIABgCIABAAIAEAAIAAAogAGngXIAAgCIABgCIABgCIASgSIAEgEIADgFIACgEIAAgFIAAgEIgCgDIgEgCIgDgBIgEABIgEACIgBADIgCACIgBACIgDABIgDgBIABgHIAFgFIAFgDIAHgBIAHABIAFADQADACABAEQABADABADIgBAGIgDAFIgEAFIgEAFIgPAPIADgBIAEAAIASAAIACAAIAAADIAAAEgAGCgXIAAgbIAAgBIABgCIgBABIgBABIgBABIgDADIgCAFIgEAEIgJANIgCACIgBAAIgEAAIAAgoIAHAAIAAAbIAAABIAAACIACgDIAAgBIADgDIACgEIAEgFIAKgMIABgCIABAAIAEAAIAAAogAFUgXIAAgbIAAgBIABgCIgCABIAAABIgBABIgDADIgCAFIgEAEIgJANIgCACIgBAAIgFAAIAAgoIAIAAIAAAbIAAABIAAACIABgDIABgBIADgDIACgEIAEgFIAKgMIABgCIABAAIAEAAIAAAogAEtgXIgDAAIgCgCIgHgNIgDgDIgDAAIgEAAIAAASIgIAAIAAgoIAIAAIAAARIADAAIADgBIADgCIAIgMIABgCIACAAIAGAAIgKAPIgCADIgDABIADACIADACIALARgADXgXIAAgTIgUAAIAAATIgHAAIAAgoIAHAAIAAAPIAUAAIAAgPIAHAAIAAAogACqgXIAAgbIAAgBIAAgCIgBABIgBABIgBABIgCADIgDAFIgEAEIgJANIgBACIgCAAIgEAAIAAgoIAHAAIAAAbIAAABIAAACIACgDIABgBIACgDIADgEIAEgFIAJgMIABgCIACAAIAEAAIAAAogAgTgXIAAg5IARAAQAFAAAEABQAEABACACQADADACADQABAEAAAEQAAAEgBADIgFAFIgHAFQgDABgFAAIgJAAIAAAVgAgLgzIAJAAIAFAAIAFgDIACgEIABgEIgBgGIgCgDIgFgCIgFgBIgJAAgAkZgXIAAgzIgcAAIAAAzIgIAAIAAg5IAtAAIAAA5gAm1gXIAAgoIAPAAIAGAAIAFACIACADIABAEIAAADIgCACIgBADIgFACQAFAAACADQADADAAADIgBAFIgEAEIgEADIgGAAgAmtgdIAIAAQAEAAACgBQACgCAAgDIAAgDIgBgCIgEgBIgDgBIgIAAgAmtguIAHAAIADgBIACgBIACgCIABgDIAAgCIgCgCIgDgBIgDgBIgHAAgAnAgXIgEAAIgCgCIgHgNIgDgDIgCAAIgFAAIAAASIgIAAIAAgoIAIAAIAAARIAEAAIACgBIADgCIAIgMIABgCIADAAIAFAAIgKAPIgBADIgDABIADACIACACIALARgApGgXIAAgqIAAgBIAAgCIgTAjIgBABIgCABIgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAIgUgjIABACIAAABIAAAqIgIAAIAAg5IAHAAIABAAIABABIATAjIACAEIACgCIABgCIATgjIABgBIABAAIAHAAIAAA5gArFgXIAAgoIAbAAIAAAFIgTAAIAAAjgAHXgsIAAgGIAUAAIAAAGgAIDhGIgEgCIgDgDIgBgDIABgBIABgBIAFAAIAAADIABACIACABIACAAIAEAAIABgBIABgCIAAgDIAFAAIABABIABABIgBADIgDADIgDACIgGABIgEgBgAFzhGIgDgCIgDgDIgBgDIABgBIABgBIAFAAIAAADIABACIACABIADAAIADAAIABgBIABgCIAAgDIAFAAIABABIABABIgBADIgCADIgFACIgEABIgGgBgAj1hyIAAgPIguAAIAAAMIAAACIgCABIgFAAIAAgVIAGAAIACgCIADgEIACgGIABgJIACgNIABgRIAiAAIAAAzIAKAAIAAASIgBACIgCABgAkTiiIgBAMIgDAJIgEAGIAcAAIAAgsIgTAAIgBARgAGOh4IAAAAIABgBIAAgBIACgCIABgCIABgDIgBAAIgCAAIgBgBIgBgCIAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBAAAAIADABIACABIAAADIAAACIAAADIgBAFIgDADIgDAEgADfiBIgEgBIgEgCIgDgCIACgEIACgBIACABIACABIAEACIAEABIAGgBIADgDQABAAAAgBQABAAAAgBQAAAAABgBQAAAAAAgBIABgGIgBgEIgCgEIgEgCIgFgBIgKABIgEgBIAEgbIAcAAIAAADIgBADIgDABIgSAAIgDAOIAIgBQAFABADABIAGAEQADACAAADIABAHQAAAFgBADQgBAEgDADQgDACgEABQgEACgEAAIgFgBgAAwiBIgCgBIgBgBIAAgCIAAgCIABgCIACgBIACgBIACABIACABIABACIAAACIAAACIgBABIgCABIgCABIgCgBgAgNiBIgCgBIgBgBIAAgCIAAgCIABgCIACgBIACgBIACABIACABIABACIAAACIAAACIgBABIgCABIgCABIgCgBgAhdiBIgCgBIgBgBIAAgCIAAgCIABgCIACgBIACgBIACABIACABIAAACIABACIgBACIAAABIgCABIgCABIgCgBgAiGiCQgGgCgDgEQgEgEgCgGQgBgFAAgGQAAgGABgGQADgFAEgEQADgEAGgDQAEgBAHAAQAGAAAEABQAFACAEAEIgDADIAAABIgBAAIgDAAIgCgCIgEgBIgGgBQgFAAgDABQgEABgDADIgEAHQgBAEAAAGQAAAFABAEQACAEACADQADADAEABQAEACAEAAIAEAAIAEgBIADgCIADgCIABgBIABAAIABABIADADQgDAEgGADQgFACgHAAQgGAAgFgCgAo2iCQgFgCgEgEQgDgEgDgGQgCgFAAgGQAAgGACgGQADgFADgEIAJgHQAFgBAGAAQAHAAAFABQAGADADAEQAEAEACAFQACAGAAAGQAAAGgCAFQgCAGgEAEQgDAEgGACQgFACgHAAQgGAAgFgCgAoziyQgDABgDADIgEAHQgCAEABAGQgBAFACAEIAEAHQADADADABQAEACAEAAQAFAAAEgCQAEgBACgDQADgDABgEQACgEgBgFQABgGgCgEQgBgDgDgEQgCgDgEgBQgEgBgFAAQgEAAgEABgAp2iCQgFgCgEgEQgDgEgDgGQgCgFAAgGQAAgGACgGQADgFADgEIAJgHQAFgBAHAAQAGAAAFABQAFADAEAEQAEAEACAFQACAGAAAGQAAAGgCAFQgCAGgEAEQgEAEgFACQgFACgGAAQgHAAgFgCgApyiyQgEABgDADIgEAHQgBAEAAAGQAAAFABAEIAEAHQADADAEABQADACAFAAQAEAAAEgCQAEgBACgDQADgDABgEQACgEgBgFQABgGgCgEQgBgDgDgEQgCgDgEgBQgEgBgEAAQgFAAgDABgAq2iCQgFgCgEgEQgDgEgDgGQgCgFAAgGQAAgGACgGQADgFADgEIAJgHQAFgBAHAAQAGAAAFABQAFADAEAEQAEAEACAFQACAGAAAGQAAAGgCAFQgCAGgEAEQgEAEgFACQgFACgGAAQgHAAgFgCgAqyiyQgEABgDADIgEAHQgBAEAAAGQAAAFABAEIAEAHQADADAEABQADACAFAAQAEAAAEgCQADgBADgDQADgDABgEQABgEAAgFQAAgGgBgEQgBgDgDgEQgDgDgDgBQgEgBgEAAQgFAAgDABgAFliBIARgWIACgCIACgDQgCACgDABIgGABIgGgBIgFgDQgCgCgBgDQgCgEAAgDIACgIIADgGIAGgDQAEgCAEABQAEgBAEACQADABACACQADADABADQABAEABAEIgBAFIgBAEIgDAEIgCAFIgOATIgCACIgCAAgAFtizIgDACIgCADIgBAFQAAAGADADQACACAGAAIAEAAIAFgDIABgEIABgEIgBgFIgCgDIgEgCIgEgBIgFABgAE2iBIAAgFIANAAIAAgnIAAgDIgKAJIgCAAIgBAAIAAAAIgBgBIgCgDIARgPIAGAAIAAA0IAMAAIAAAFgAEbiBIAAgOIgZAAIgCgBIgBgBIAAgEIAbglIAIAAIAAAkIAIAAIAAAFIAAABIgBABIgHAAIAAAOgAEHiWIAUAAIAAgWIAAgDIAAgCgACriBIAAgFIAMAAIAAgnIAAgDIgJAJIgCAAIgBAAIAAAAIgBgBIgDgDIARgPIAHAAIAAA0IALAAIAAAFgAB9iBIAAgFIAMAAIAAgnIAAgDIgKAJIgBAAIgBAAIgBAAIgBgBIgCgDIARgPIAGAAIAAA0IALAAIAAAFgAAEiBIAAg5IAjAAIAAAHIgaAAIAAAygAgkiBIAAgaIgeAAIAAAaIgJAAIAAg5IAJAAIAAAaIAeAAIAAgaIAJAAIAAA5gAi+iBIAAgnIABgEIAAgFIgCAEIgCADIgaAnIgBABIgCABIgHAAIAAg5IAJAAIAAAoIAAAEIgBADIACgCIABgDIAagoIACgBIADgBIAFAAIAAA5gAk6iBIAAgaIgeAAIAAAaIgJAAIAAg5IAJAAIAAAaIAeAAIAAgaIAJAAIAAA5gAluiBIgBAAIgBgCIgGgNIgZAAIgFANIgBACIgCAAIgGAAIAWg5IAJAAIAXA5gAmDivIgBACIgJAXIAVAAIgIgXIgBgCIgBgDIgBADgAmliBIgCAAIgCgCIgPgVIgCgCIgEgBIgGAAIAAAaIgJAAIAAg5IAJAAIAAAZIAGAAIABAAIACAAIABgBIACgCIAOgUIABgBIADgBIAGAAIgQAYQgDADgDABIAEABIADAEIARAYgABOiHIgCgBIABgCIAGgLIABAAIAAgBIAAAAIgBgBIgGgKIgBgDIACgBIACgBIAKAQIAAABIgKAQgABCiHIgBgBIAAgCIAGgLIABAAIABgBIgBAAIgBgBIgGgKIAAgDIABgBIACgBIAKAQIAAABIgKAQgAnmiVIAAgBIAKgQIADABIAAABIAAADIgGAKIgBABIABABIAGALIAAACIAAABIgDACgAnyiVIAAgBIAKgQIADABIABABIgBADIgGAKIgBABIABABIAGALIABACIgBABIgDACg");
	this.shape.setTransform(73.6,79.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal, new cjs.Rectangle(0,0,236.1,98.6), null);


(lib.ClipGroup_17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AoRBrIAAjVIQjAAIAADVg");
	mask.setTransform(53,10.7);

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0DA8E1").s().p("AnxBHQgkghAVgvQATgsA7gZQBDgcBrABQAYAAAVACIAcAEIAMADIgQAbQgkgJgaAAQg2AAgtAQQg8AVgJAqQgGAaATAXQAYAdA0gDQAQgBAggKQAngNAWgSIA2gvIALgGQAHgEAJAAIA6AAIASBQIAlhPIBAAAIAlA9IAcg9IA6AAIgzBwIg8AAIgnhBIgdBBIhqAAIgDgUIhAAAIgVATIgpAAQgwASg/AAQhbAAgngkgAiqAwIAlgBIgDgfgAFOBlIAmgmIgmhVIA6AAIAQAuIAvgvIBCABIhyBxQgFAFgEACIgOADgADZBaIhfAAIA0hwIBfAAQAuAAAQAWQAOARgKAWQgKAVgYANQgfARgyAAIgDAAgADHA+IARAAQATAAAPgFQAYgHAFgSQAHgbgtAAIgRAAg");
	this.shape.setTransform(54,10.7);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_17, new cjs.Rectangle(1.9,0.1,104.2,21.3), null);


(lib.ClipGroup_4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AjXC0IAAlnIGvAAIAAFng");
	mask.setTransform(21.6,18);

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#25387A").s().p("AibAnQgEAAgDgEIgxg4QgGgHAHgHQADgCAEAAQAEAAADAEIAtA0IEuAAIAug0QAGgIAIAGQAHAHgGAHIgxA4QgDAEgFAAg");
	this.shape.setTransform(21.6,32.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#25387A").s().p("AAEB2QgRgNgMgXIAAgBIgFgNIgBAAQAAgEgEAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAABgBAAIgmAyQgGAHgJABQgNAAgJgKQgTgTgBgdQgCggAVgaQAPgSAZgKQAGgCAKgCQAAAAABAAQABgBAAAAQABAAAAgBQAAAAABAAIgCgDIg8gwIgBgBQgFgEgBgIQAAgKAGgGQAWgXAigCQAhgBAbAVQAQAOAJAXIADAMQACAGACAAQAEABAFgGIAqg1IABAAQAFgFAHgBQAIgBAGAFQAKAJAGALQAMAVgDAfQgCAVgMAQQgJAKgKAIQgHAFgXAKIgKAEQgFADgBADQAAADADACIAwAmQAHAFABAJQABAJgIAJQgVAXgiAAQgaAAgWgPgAggAtQAPACAFAOIAFAMQAIATAOAKQATANAWgCQAXgBANgPIACgDIgwgmQgMgJACgOQABgOAQgHIAKgFQARgHAJgFQAJgHAHgIQAIgLABgQQADgZgJgQQgFgIgGgFIgqAzQgMAPgPgDQgPgDgFgRIgDgKQgFgSgOgLQgVgRgbACQgZACgQARIAAAAIA7AwQAMAKgEANQgDANgQAEIgMADQgUAGgMAPQgRAWACAZQACAVANANIAEACIADABIAngyQAHgJAKAAIAEABg");
	this.shape_1.setTransform(22.2,14.1);

	var maskedShapeInstanceList = [this.shape,this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_4, new cjs.Rectangle(0.1,0.9,43,35.2), null);


(lib.ClipGroup_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AiaCUIAAknIE1AAIAAEng");
	mask.setTransform(15.5,14.8);

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#243878").s().p("AgcAqQgKgMACgQQACgKARgeIARgcIARAaQARAcACAOQADAQgLANQgLAMgRAAQgRAAgLgNg");
	this.shape.setTransform(27,24.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#243878").s().p("AgcAqQgKgMACgQQACgKARgeIARgcIARAaQARAcACAOQADAQgLANQgLAMgRAAQgRAAgLgNg");
	this.shape_1.setTransform(15.5,24.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#243878").s().p("AgcAqQgKgMACgQQACgKARgeIARgcIARAaQARAcACAOQADAQgLANQgLAMgRAAQgRAAgLgNg");
	this.shape_2.setTransform(3.9,24.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#243878").s().p("AgcAqQgKgMACgQQACgQAig0QAgAuAEAWQADAQgLAMQgLANgRAAQgRAAgLgNg");
	this.shape_3.setTransform(27,5.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#243878").s().p("AgcAqQgKgMACgQQACgQAig0QAhAuADAWQADAQgLAMQgLANgRAAQgRAAgLgNg");
	this.shape_4.setTransform(15.5,5.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#243878").s().p("AgcAqQgKgMACgQQACgQAig0QAgAuAEAWQADAQgLAMQgLANgRAAQgRAAgLgNg");
	this.shape_5.setTransform(3.9,5.5);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_2, new cjs.Rectangle(0.2,0,30.5,29.6), null);


(lib.ClipGroup_1_0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AidCwIAAlfIE7AAIAAFfg");
	mask.setTransform(15.8,17.6);

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#25387A").s().p("AhOAKQgRgPgIgVQgCgFACgEQACgFAFgBQAEgDAFADQAEACACAEQAHARANANQAaAYAjAAQAlAAAagYQAMgMAHgSQACgEAFgCQAEgCAFACQAEACACAEQACAFgCAEQgIAVgQAPQghAigvgBQguABgggig");
	this.shape.setTransform(16,30.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#25387A").s().p("AgoAqQgcgcAAgmQAAgTAHgSQACgEAFgCQAEgCAFACQAEACACAEQACAFgCAFQgFALAAAQQAAAcAUAVQAVAVAcAAQAOAAAOgGQAEgCAFACQAEACACAEQACAFgCAEQgBAFgFACQgSAHgTAAQgmAAgbgbg");
	this.shape_1.setTransform(6.9,18.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#25387A").s().p("Ag9A+QgEgCgCgFQgCgEACgFQACgEAFgCQAEgCAFACQANAGAOAAQAcAAAUgVQAWgVgBgcQABgOgGgNQgCgFACgFQABgEAFgCQAFgCAFACQAEACACAEQAHASAAATQABAmgcAcQgcAbgmAAQgTAAgSgHg");
	this.shape_2.setTransform(24.7,18.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#25387A").s().p("AgIBdQgDgEAAgEIAAioQAAgFADgEQAEgEAEABQAFgBADAEQAEAEAAAFIAACoQAAAEgEAEQgDADgFAAQgEAAgEgDg");
	this.shape_3.setTransform(15.8,9.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#25387A").s().p("AAOBVIgyiiQgBgFACgEQACgEAFgCQAFgBAEACQAFACABAFIAyCiQABAFgCAEQgCAEgFACIgEAAQgIAAgDgIg");
	this.shape_4.setTransform(21.9,9.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#25387A").s().p("AgcBdQgFgCgCgEQgCgEABgFIAyiiQABgFAFgCQAEgCAFABQAFACACAEQACAEgBAFIgyCiQgDAIgIAAg");
	this.shape_5.setTransform(9.2,9.5);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_1_0, new cjs.Rectangle(0,0.2,31.6,35.1), null);


(lib.ClipGroup_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AgJIXIAAwuIATAAIAAQug");
	mask.setTransform(9.6,53.6);

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(19.3,0,0,4).p("AAAoVIAAQr");
	this.shape.setTransform(9.6,53.6);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_1, new cjs.Rectangle(8.6,0,2,107.1), null);


(lib.stext3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#25387A").s().p("AAeA1IgJgWIgpAAIgJAWIgVAAIAphpIATAAIApBpgAgNALIAbAAIgOgjg");
	this.shape.setTransform(55.5,3.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#25387A").s().p("AgJA1IgmhpIAVAAIAaBKIAbhKIAUAAIglBpg");
	this.shape_1.setTransform(44.8,3.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#25387A").s().p("AgJA1IAAhpIATAAIAABpg");
	this.shape_2.setTransform(37.6,3.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#25387A").s().p("AgKA1IAAhVIgSAAIAAgUIA5AAIAAAUIgTAAIAABVg");
	this.shape_3.setTransform(32.4,3.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#25387A").s().p("AgiAoQgQgQAAgYQAAgPAHgMQAIgNAMgHQAOgIAOAAQANAAAMAGQANAGAIAKIgOANQgOgPgSAAQgOAAgLAKQgKALAAAOQAAALAFAIQAFAJAIAEQAIAEAJAAQAJAAAHgDQAIgEAIgIIAOAOQgLALgLAFQgLAFgNAAQgYAAgPgQg");
	this.shape_4.setTransform(23.6,3.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#25387A").s().p("AAeA1IgIgWIgqAAIgJAWIgVAAIAphpIATAAIApBpgAgNALIAcAAIgPgjg");
	this.shape_5.setTransform(12.4,3.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#25387A").s().p("AgTAxQgJgFgDgIQgEgKAAgRIAAg+IAVAAIAABDQAAAJABAEQABAEAEACQAFACADAAQAFAAADgDQAFgCABgEQACgDgBgLIAAhBIAVAAIAAA+QAAAOgCAIQgCAGgFAGQgGAGgGACQgGADgJAAQgLAAgIgFg");
	this.shape_6.setTransform(2.2,3.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#25387A").s().p("AAiA6IgKgLQgLAGgOAAQgXAAgQgQQgQgRAAgVQAAgQAHgNQAIgNAMgHQAOgIAOAAQAWAAAQARQAQAQAAAYQAAAUgOAQIASAXgAgagbQgKAKAAAQQAAAQANALQAJAHANABQAHgBAGgDIgSgXIAXAAIAJAMQAHgKAAgKQAAgPgKgLQgLgLgNABQgPAAgKAKg");
	this.shape_7.setTransform(-8.5,4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#25387A").s().p("AAeA1IgIgWIgqAAIgJAWIgVAAIAphpIATAAIApBpgAgNALIAbAAIgOgjg");
	this.shape_8.setTransform(-20.4,3.7);

	this.instance = new lib.ClipGroup_2();
	this.instance.parent = this;
	this.instance.setTransform(-45.2,5,1,1,0,0,0,15.5,14.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.stext3, new cjs.Rectangle(-60.7,-9.8,121.3,29.6), null);


(lib.stext2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ClipGroup_4();
	this.instance.parent = this;
	this.instance.setTransform(-27.6,44.1,1,1,0,0,0,21.6,18);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#25387A").s().p("AgQAeQgHgEgGgIQgEgJAAgJQAAgMAIgKQAKgMAQAAQAHAAAJADQAFADAHAGIgIAJQgJgIgLgBQgJABgHAGQgGAIAAAHQAAAJAHAHQAHAHAJAAQAGAAAFgDQAFgEACgFIgTAAIAAgLIAiAAIAAACQAAAJgFAIQgFAHgHAFQgHAEgJAAQgKAAgIgFg");
	this.shape.setTransform(39.9,54.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#25387A").s().p("AAOAhIgbgqIAAAqIgNAAIAAhBIANAAIAbArIAAgrIANAAIAABBg");
	this.shape_1.setTransform(32.5,54.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#25387A").s().p("AgFAhIAAhBIALAAIAABBg");
	this.shape_2.setTransform(27.8,54.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#25387A").s().p("AAJAhIgTgdIAAAdIgNAAIAAhBIANAAIAAAXIARgXIAPAAIgWAdIAYAkg");
	this.shape_3.setTransform(24,54.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#25387A").s().p("AgYAYQgKgKABgOQAAgIAEgIQAFgJAIgEQAJgFAIAAQANAAAKALQALAKAAAOQAAAOgLAKQgJAKgOAAQgOAAgLgLgAgPgPQgFAHgBAJQABAKAHAHQAGAEAIAAQAIAAAGgGQAHgGAAgKQAAgIgHgHQgGgGgJgBQgIABgHAGg");
	this.shape_4.setTransform(16.9,54.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#25387A").s().p("AgXAYQgLgKABgOQgBgIAFgIQAGgJAHgEQAIgFAIAAQAOAAAKALQAKAKAAAOQAAANgKALQgJAKgOAAQgOAAgKgLgAgOgPQgHAHAAAJQAAAKAIAHQAGAEAIAAQAIAAAGgGQAHgGAAgKQAAgIgHgHQgGgGgJgBQgIABgGAGg");
	this.shape_5.setTransform(9.2,54.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#25387A").s().p("AgVAZQgKgKAAgPQAAgJAEgHQAEgIAJgFQAJgFAIAAQAHAAAJADQAGADAHAHIgJAJQgJgKgLAAQgJABgGAGQgHAIAAAHQAAAHADAEQAEAGAFADQAFADAFAAQAFAAAFgCQAFgCAFgGIAJAJQgIAIgGACQgGADgJAAQgOAAgKgKg");
	this.shape_6.setTransform(1.7,54.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#25387A").s().p("AgOAhIAAhBIAMAAIAAA1IARAAIAAAMg");
	this.shape_7.setTransform(47.7,44.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#25387A").s().p("AATAhIgFgNIgaAAIgGANIgNAAIAZhBIANAAIAZBBgAgIAHIARAAIgJgVg");
	this.shape_8.setTransform(42,44.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#25387A").s().p("AAPAhIgcgrIAAArIgNAAIAAhBIAMAAIAcArIAAgrIANAAIAABBg");
	this.shape_9.setTransform(35.1,44.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#25387A").s().p("AgYAYQgKgKAAgOQABgIAEgIQAFgJAIgEQAJgFAHAAQAOAAALALQAJAKABAOQgBANgJALQgKAKgOAAQgOAAgLgLgAgPgPQgFAGgBAKQAAAKAIAHQAGAEAIAAQAJAAAGgGQAGgGAAgKQAAgJgGgGQgHgGgJgBQgIABgHAGg");
	this.shape_10.setTransform(27.8,44.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#25387A").s().p("AgFAhIAAhBIALAAIAABBg");
	this.shape_11.setTransform(22.6,44.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#25387A").s().p("AgFAhIAAg1IgNAAIAAgMIAlAAIAAAMIgNAAIAAA1g");
	this.shape_12.setTransform(19.4,44.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#25387A").s().p("AgFAhIAAhBIALAAIAABBg");
	this.shape_13.setTransform(16.2,44.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#25387A").s().p("AgZAhIAAhBIAPAAQANAAAHADQAIAFAEAHQAEAIAAAKQAAAHgCAHQgEAHgDADQgFAFgFABQgFACgMAAgAgNAVIAGAAQAHAAAFgCQAEgCACgFQACgEAAgHQAAgKgFgFQgHgGgKAAIgEAAg");
	this.shape_14.setTransform(11.8,44.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#25387A").s().p("AATAhIgGgNIgaAAIgFANIgNAAIAahBIALAAIAaBBgAgHAHIAQAAIgJgVg");
	this.shape_15.setTransform(5,44.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#25387A").s().p("AAHAhIgOgcIgBAAIAAAcIgMAAIAAhBIANAAQAKAAAFACQAEACADAFQADAEAAAGQAAAGgDAFQgDADgHADIAQAdgAgIgGIAEAAQAFAAACgCQADgBAAgEIgBgEIgDgCIgGgBIgEAAg");
	this.shape_16.setTransform(-0.8,44.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#25387A").s().p("AgFAhIAAg1IgMAAIAAgMIAjAAIAAAMIgMAAIAAA1g");
	this.shape_17.setTransform(-5.7,44.7);

	this.instance_1 = new lib.ClipGroup_1_0();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-22.8,-1.6,1,1,0,0,0,15.8,17.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#25387A").s().p("AgQAfQgIgFgFgIQgEgKAAgIQAAgMAJgKQAKgMAQAAQAHAAAIADQAGADAHAGIgJAJQgIgJgLAAQgJABgHAGQgGAGgBAJQABAJAGAHQAIAHAIAAQAHAAAEgDQAFgDADgFIgUAAIAAgMIAhAAIAAADQABAIgFAIQgFAHgGAFQgJAEgIAAQgJAAgJgEg");
	this.shape_18.setTransform(35.1,10.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#25387A").s().p("AAOAhIgbgrIAAArIgNAAIAAhBIANAAIAbArIAAgrIAMAAIAABBg");
	this.shape_19.setTransform(27.8,10.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#25387A").s().p("AgFAhIAAhBIALAAIAABBg");
	this.shape_20.setTransform(23.1,10.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#25387A").s().p("AAJAhIgUgdIAAAdIgMAAIAAhBIAMAAIAAAXIARgXIAQAAIgXAdIAZAkg");
	this.shape_21.setTransform(19.3,10.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#25387A").s().p("AgYAYQgJgJgBgPQAAgIAFgIQAEgIAIgFQAKgFAHAAQAPAAAJALQALAKAAAOQAAANgKALQgLAKgOAAQgOAAgKgLgAgPgPQgGAHAAAJQAAAKAIAHQAFAEAIAAQAJAAAHgGQAFgGAAgKQAAgIgFgHQgIgGgIgBQgIABgHAGg");
	this.shape_22.setTransform(12.2,10.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#25387A").s().p("AgYAYQgKgJAAgPQABgIAEgIQAEgJAIgEQAKgFAHAAQAPAAAJALQALAKAAAOQgBANgJALQgMAKgNAAQgOAAgKgLgAgPgPQgGAHAAAJQAAAKAIAHQAFAEAIAAQAJAAAHgGQAFgGAAgKQAAgIgFgHQgIgGgIgBQgIABgHAGg");
	this.shape_23.setTransform(4.5,10.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#25387A").s().p("AgVAZQgKgKAAgPQAAgJAEgHQAFgJAIgEQAJgFAIAAQAIAAAIADQAHAEAGAGIgJAJQgJgKgLAAQgJABgGAGQgGAGgBAJQAAAHADAFQACAEAGAEQAGADAFAAQAFAAAFgCQAEgCAGgGIAJAJQgIAIgGACQgHADgIAAQgPAAgJgKg");
	this.shape_24.setTransform(-3,10.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#25387A").s().p("AAbAhIgHgoIgOAoIgLAAIgNgoIgHAoIgNAAIAMhBIAMAAIAPAtIAPgtIAMAAIALBBg");
	this.shape_25.setTransform(26.3,0.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#25387A").s().p("AATAhIgGgNIgaAAIgFANIgNAAIAZhBIANAAIAZBBgAgIAHIARAAIgJgVg");
	this.shape_26.setTransform(18.8,0.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#25387A").s().p("AgRAhIAAhBIAjAAIAAAMIgXAAIAAAMIAXAAIAAAMIgXAAIAAARIAXAAIAAAMg");
	this.shape_27.setTransform(13.1,0.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#25387A").s().p("AgFAhIAAg1IgMAAIAAgMIAjAAIAAAMIgMAAIAAA1g");
	this.shape_28.setTransform(8.6,0.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#25387A").s().p("AgLAfQgFgEgEgGIALgHQAEAJAGAAQADAAACgCQABgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBIgBgEIgHgHQgLgIgDgEQgDgFAAgFQAAgHAFgFQAGgFAGAAQAFAAAFADQAEACAGAGIgKAIQgFgGgFgBIgDABIgBADIABAEIARAPQAEAEABADQACADAAAFQAAAIgGAGQgGAFgJAAQgFAAgGgEg");
	this.shape_29.setTransform(4.1,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.instance_1},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.stext2, new cjs.Rectangle(-49.2,-19.2,98.5,81.4), null);


(lib.pic3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkpAuIAAgMIg+AAIAAAMIgIAAIAAgTIAGAAIAghGIACAAIAgBGIAGAAIAAATgAlgAbIAwAAIgYg2gAClAWQgKgLAAgPQAAgSAMgLQAMgMASAAQALAAAIAFQAKAEAFAIIgGAFQgFgHgHgEQgIgDgIAAQgKAAgHAFQgIAEgEAIQgEAHgBAJQAAAOAKAJQAKAKAOAAQARAAALgNIAGAFQgGAHgJAEQgIAEgLAAQgUAAgMgOgABJAYQgMgMAAgQQAAgLAGgJQAFgKAJgFQAJgGAMAAQARAAAMAMQAMAMAAARQAAAQgMAMQgMAMgRAAQgRAAgMgMgABWghQgIAFgFAIQgEAHAAAJQAAANAJAKQALAJANAAQAJAAAHgEQAIgEAFgIQAEgIAAgIQAAgJgEgIQgFgHgIgFQgHgEgJAAQgJAAgHAEgAkNAYQgMgMAAgQQAAgLAGgJQAEgKAKgFQAKgGAKAAQASAAAMAMQAMAMAAARQAAAQgMAMQgMAMgRAAQgRAAgMgMgAkBghQgHAFgFAIQgEAHAAAJQAAANAKAKQAJAJANAAQAKAAAHgEQAIgEAFgIQADgIAAgIQAAgJgDgIQgFgHgIgFQgIgEgJAAQgIAAgIAEgAFCAiIAAhNIAtAAIAAAIIglAAIAAAYIAlAAIAAAIIglAAIAAAeIAlAAIAAAHgAEuAiIgag7IgbA7IgIAAIAihNIABAAIAiBNgAAlAiIAAhFIgmAAIAABFIgIAAIAAhNIA2AAIAABNg");
	this.shape.setTransform(4.3,11.5);

	this.instance = new lib.ClipGroup_1();
	this.instance.parent = this;
	this.instance.setTransform(-3.2,-14.9,0.75,0.75,0,0,0,9.6,53.6);

	this.instance_1 = new lib._3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-111,-93,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic3, new cjs.Rectangle(-111,-93,222,165.8), null);


// stage content:
(lib._160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(426));

	// legal
	this.instance = new lib.legal();
	this.instance.parent = this;
	this.instance.setTransform(122,506.6,1,1,0,0,0,118,12.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(426));

	// legal5
	this.instance_1 = new lib.legal1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(29.5,531.1,1,1,0,0,0,21.9,6.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(332).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(77).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(4));

	// legal3
	this.instance_2 = new lib.legal3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(29.8,531.1,1,1,0,0,0,22.2,6.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(166).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(77).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(170));

	// legal2
	this.instance_3 = new lib.legal2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(37.8,531.1,1,1,0,0,0,30.2,6.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(83).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(77).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(253));

	// legal1
	this.instance_4 = new lib.legal1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(29.5,531.1,1,1,0,0,0,21.9,6.2);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:1},6,cjs.Ease.get(1)).wait(77).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(336));

	// pic5
	this.instance_5 = new lib.pic5();
	this.instance_5.parent = this;
	this.instance_5.setTransform(79.7,367.5,0.9,0.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(336).to({_off:false},0).to({scaleX:1,scaleY:1,x:79.6,alpha:1},6,cjs.Ease.get(1)).wait(77).to({scaleX:0.9,scaleY:0.9,x:79.7,alpha:0},6,cjs.Ease.get(1)).wait(1));

	// pic4
	this.instance_6 = new lib.pic4();
	this.instance_6.parent = this;
	this.instance_6.setTransform(80.1,351.7,0.9,0.9);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(253).to({_off:false},0).to({scaleX:1,scaleY:1,x:80,y:350,alpha:1},6,cjs.Ease.get(1)).wait(77).to({scaleX:0.9,scaleY:0.9,x:80.1,y:351.7,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(83));

	// pic3
	this.instance_7 = new lib.pic3();
	this.instance_7.parent = this;
	this.instance_7.setTransform(83.7,365.6,0.9,0.9);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(170).to({_off:false},0).to({scaleX:1,scaleY:1,x:84,y:365.4,alpha:1},6,cjs.Ease.get(1)).wait(77).to({scaleX:0.9,scaleY:0.9,x:83.7,y:365.6,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(166));

	// pic2
	this.instance_8 = new lib.pic2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(80.1,350.9,0.9,0.9);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(87).to({_off:false},0).to({scaleX:1,scaleY:1,x:80,y:349.1,alpha:1},6,cjs.Ease.get(1)).wait(77).to({scaleX:0.9,scaleY:0.9,x:80.1,y:350.9,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(249));

	// pic1
	this.instance_9 = new lib.pic1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(80.5,351.7,0.9,0.9);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(4).to({_off:false},0).to({scaleX:1,scaleY:1,y:350,alpha:1},6,cjs.Ease.get(1)).wait(77).to({scaleX:0.9,scaleY:0.9,y:351.7,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(332));

	// stext5
	this.instance_10 = new lib.stext1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(100,199.9);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(334).to({_off:false},0).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(2));

	// stext4
	this.instance_11 = new lib.stext4();
	this.instance_11.parent = this;
	this.instance_11.setTransform(100,200.6);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(251).to({_off:false},0).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(85));

	// stext3
	this.instance_12 = new lib.stext3();
	this.instance_12.parent = this;
	this.instance_12.setTransform(99.9,201.2,1,1,0,0,0,-0.1,0);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(168).to({_off:false},0).to({x:79.9,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:59.9,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(168));

	// stext2
	this.instance_13 = new lib.stext2();
	this.instance_13.parent = this;
	this.instance_13.setTransform(100,198.2,1,1,0,0,0,0,-0.1);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(85).to({_off:false},0).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(251));

	// stext1
	this.instance_14 = new lib.stext1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(100,199.9);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(2).to({_off:false},0).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(334));

	// text5
	this.instance_15 = new lib.text5();
	this.instance_15.parent = this;
	this.instance_15.setTransform(100,121.3);
	this.instance_15.alpha = 0;
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(332).to({_off:false},0).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(4));

	// text4
	this.instance_16 = new lib.text4();
	this.instance_16.parent = this;
	this.instance_16.setTransform(100,143.8);
	this.instance_16.alpha = 0;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(249).to({_off:false},0).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(87));

	// text3
	this.instance_17 = new lib.text3();
	this.instance_17.parent = this;
	this.instance_17.setTransform(100,121.3);
	this.instance_17.alpha = 0;
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(166).to({_off:false},0).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(170));

	// text2
	this.instance_18 = new lib.text2();
	this.instance_18.parent = this;
	this.instance_18.setTransform(100,121.3);
	this.instance_18.alpha = 0;
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(83).to({_off:false},0).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(253));

	// text1
	this.instance_19 = new lib.text1();
	this.instance_19.parent = this;
	this.instance_19.setTransform(100,123.3);
	this.instance_19.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).to({x:80,alpha:1},6,cjs.Ease.get(1)).wait(77).to({x:60,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(336));

	// logo
	this.logo = new lib.ClipGroup_17();
	this.logo.parent = this;
	this.logo.setTransform(79.2,47.4,1,1,0,0,0,53.1,10.7);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(426));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#E6F4FC","#E3F3FB","#D9EEFA","#C7E6F7","#B0DCF3","#A3D6F1","#90CEEB","#8BCCEA","#31AED8"],[0,0.192,0.349,0.49,0.627,0.686,0.82,0.843,1],0,-322.8,0,118.2).s().p("EgIqApeMAAAhS7IRVAAMAAABS7g");
	this.shape_1.setTransform(80,300,1.441,1.13);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(426));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(79.5,299.5,161,601);
// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/160x600_atlas_P_.png", id:"160x600_atlas_P_"},
		{src:"images/160x600_atlas_NP_.jpg", id:"160x600_atlas_NP_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;