(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"120x600_atlas_", frames: [[0,192,160,190],[324,0,160,190],[162,0,160,190],[162,192,160,190],[0,0,160,190]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib._1 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._3 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib._4 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib._5 = function() {
	this.spriteSheet = ss["120x600_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.text2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AEeAeIAAg5IAFAAQAAAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABAFIAGgGQAEgCAFAAQADAAADACQAEABACADQACADABAEIABAKIgBAIIgEAHQgCADgEACIgIABIgGgBIgGgDIAAATgAEsgUIgGAEIAAAUQACADADABIAFABQAGAAAEgEQADgEAAgHQAAgFgBgCIgCgFIgEgDIgEgBQgDAAgDACgAl/AeIAAg5IAEAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIAAAFIAGgGQAFgCAEAAQAEAAACACQAEABACADQACADABAEQACAFAAAFQAAAFgCADIgDAHIgGAFIgJABIgGgBIgGgDIAAATgAlygUIgGAEIAAAUQADADACABIAGABQAGAAADgEQADgEAAgHIgBgHIgCgFQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgFgBQgDAAgDACgAFZAOIgHgFIgEgGQgCgEAAgFQAAgFACgEQACgFACgCQADgEAEgBIAJgBIAJABQADABADAEQADACABAFIABAJIgBAJQgBADgDADIgGAFIgJABIgJgBgAFYgSQgDAEAAAIQAAAHADAEQADAEAHAAQAGAAADgEQADgEAAgHQAAgIgDgEQgDgEgGAAQgHAAgDAEgAD3APQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBIgDgDIgBgFIABgEQABgDAEgBQADgCAFgBIANgCIAAgDQAAgFgCgDQgDgCgEAAIgEABIgEABIgDACIgBABIgCgBIAAgBIgCgDIAIgFQAEgCAFAAQAEAAACACQAEABACACQACACABAEIAAAGIAAAbIgDAAIgCgBQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIgBgDIgDADQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgEABIgEAAIgFAAgAECgDQgDAAgDACQgBAAAAABQgBAAAAAAQgBAAAAAAQAAAAAAAAIgCADQAAABAAAAQAAABABAAQAAAAAAABQAAAAABAAIAAADIADAAIADABIADgBIADAAIADgCIADgDIAAgHIgJAAgAgEAOIgHgFQgCgDgBgEQgCgDAAgFQAAgFACgEQABgEACgDQADgDAEgCIAIgBIAHABIAGAEIAEAGQABADAAAFIAAADIgCAAIgcAAIABAGIADAFIAEADIAEABIAGAAIADgCIACgBIACgBIACABIACADQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAABIgFACIgEABIgFAAIgIgBgAgEgUQgDADgBAGIAXAAIgBgEIgCgEIgEgDIgEAAQgFAAgDACgAhGAOIAAgFIACAAIADAAIADgCIADgEIACgGIACgLQABgGAAgHIAdAAIAAAqIgJAAIAAgkIgNAAIgCAOIgCAJIgDAHIgEADQgCACgCABIgFAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAgAiTAOQgEgCgDgDQgDgDgBgDQgCgEAAgFQAAgFACgEQABgFADgCQADgEAEgBIAJgBIAIABQAFABADAEQACACABAFQACAEAAAFQAAAFgCAEQgBADgCADQgDADgFACIgIABIgJgBgAiUgSQgDAEAAAIQAAAHADAEQAEAEAGAAQAGAAAEgEQADgEAAgHQAAgIgDgEQgEgEgGAAQgGAAgEAEgAjwAOIgHgFIgEgGIgBgJIABgJQACgFACgCQADgEAEgBIAKgBIAIABQAEABACAEQADACACAFIAAAJIAAAJQgCADgDADIgGAFIgIABIgKgBgAjxgSQgDAEAAAIQAAAHADAEQADAEAIAAQAFAAAEgEQADgEAAgHQAAgIgDgEQgEgEgFAAQgIAAgDAEgAGqAPIAAgbIAAgDIAAgDIgPAZIAAACIgDAAIgCAAIAAgCIgPgZIAAADIAAADIAAAbIgHAAIAAgqIAGAAIACAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIANAWIACACIABACIAAgCIACgCIAMgWQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIACAAIAGAAIAAAqgADfAPIAAglIgVAAIAAAlIgHAAIAAgqIAkAAIAAAqgACZAPIAAgSIgDAAIgDAAIAAACIgCAAIgBABIgJAMIgCACIgDABIgGAAIAMgPQACgDADgBIgFgCQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAIgCgDIgBgEIABgFQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABgBQABgCAEgBIAHAAIAPAAIAAAqgACLgUIgBADIgBACQAAAEACACIAIABIAGAAIAAgOIgHAAIgFAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAAAgABtAPIAAgcIAAgCIABgCIgBACIAAABIgCACIgCADIgDAEIgEAFIgKAMIgBACIgCABIgFAAIAAgqIAIAAIAAAbIAAACIAAACIACgDIAAgBIADgDIADgDIAEgGIAKgOIABgBIABAAIAGAAIAAAqgAA8APIAAgUIgVAAIAAAUIgIAAIAAgqIAIAAIAAAQIAVAAIAAgQIAIAAIAAAqgAhsAPIAAgqIAQAAIAHAAIAGACIACAEIABAEIAAADIgCADIgCACIgFACQAGABACADQADACAAADQAAADgCADIgDAEQgCACgDAAIgGABgAhkAJIAKAAQAEAAACgCQACgCAAgDIAAgCIgBgCIgDgBIgEgBIgKAAgAhkgJIAIAAIAEAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAIABgCIABgEIAAgBIgCgCIgDgCIgEAAIgIAAgAi9APIAAglIgQAAIAAgFIApAAIAAAFIgRAAIAAAlgAkdAPIAAgqIAcAAIAAAFIgUAAIAAAlgAkxAPIAAgcIAAgCIAAgCIgBACIAAABIgCACIgCADIgDAEIgEAFIgKAMIgBACIgCABIgFAAIAAgqIAIAAIAAAbIAAACIAAACIACgDIAAgBIADgDIADgDIAEgGIAKgOIABgBIACAAIAFAAIAAAqgAmTAPIAAglIgVAAIAAAlIgIAAIAAgqIAlAAIAAAqg");
	this.shape.setTransform(-1.3,9.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AjOAoIAAgOIgkAAIAAAMIgBABIgCABIgGAAIAAgUIADAAIADgCIADgBIACgFIABgHIAEgXIAcAAIAAAmIAIAAIAAATIgBABgAjpAPIgCAFIAUAAIAAggIgNAAgAE4AnIAAgPIgmAAIAAgqIAIAAIAAAkIAVAAIAAgkIAIAAIAAAkIAHAAIAAATIAAACIgBAAgABgAnIAAgPIgKgBIgHgFQgEgCgBgFQgCgDAAgGQAAgEACgEQABgEAEgDIAHgEIAKgBIAAgSIAIAAIAAASIAJABQAFACACACQAEADACAEIAAAIIAAAJQgCAFgEACQgCADgFACIgJABIAAAPgABmATIAIgBQADgBACgDIADgFIAAgHIAAgFIgDgFQgCgCgDgBQgDgBgFgBgABUgIQgDAFAAAFQAAAHADAFQAEAEAIABIAAggQgIABgEAEgACNAnIAIgSIgSgnIAHAAIACAAIAAACIALAZIACADIAAgBIABgCIALgZIABgCIACAAIAGAAIgYA4IgBAAIgCABgAGDAXIgIgEIgEgIIgBgJIABgIIAEgHQADgCAEgCIAIgBIAIAAIAFAEIAFAGQABADAAAFIgBACIgBAAIgeAAIACAIQAAACADACIAEAEIAGAAIAFAAIADgBIACgCIACgBIACABIACADIgEADIgDACIgGABIgFAAIgHgBgAGCgLQgDADgBAGIAXAAIAAgEIgCgDIgEgEIgFAAQgFAAgDACgAAVAXIgGgEQgDgCgCgFIgBgKIABgIIAFgHIAGgEIAJgBIAIAAQAEABADADIgCADIgBACIgBAAIgCAAIgCgCIgDgCIgEAAIgFABIgEAEQgCACgBADIAAAFIAAAHQABADACACIAEAEIAFAAIAFAAIACgBIACgCIADgBIABABIACADIgDADIgFACIgDABIgGAAIgHgBgAiYAXIAAgFIACAAIAEAAIADgBIACgFIADgHIABgKIABgNIAdAAIAAAqIgJAAIAAgkIgNAAQAAAIgCAGIgCAJIgDAHQgCADgCAAIgDADIgGAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQAAAAAAgBgAi1AXIgHgEQgEgDgCgFIgBgJIABgIIAGgHQABgCAFgCIAJgBIAGAAIAGAEQADADABADQACADAAAFIgBACIgCAAIgdAAIACAIQAAACADACIADAEIAHAAIAEAAIAEgBIADgCIABgBIABABIADADIgEADQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgFABIgEAAIgIgBgAi2gLQgEADAAAGIAXAAIAAgEIgCgDIgFgEIgDAAQgGAAgDACgAkdAXQgEgCgCgCIgFgHIgBgKIABgIQACgEADgDQACgEAEgBIAJAAIAJAAQAEABADAEQACADABAEQACAEAAAEQAAAFgCAFIgDAHIgHAEIgJABIgJgBgAkegIQgDAEAAAGQAAAJADADQAEAEAGAAQAHAAACgEQADgDABgJQgBgGgDgEQgCgFgHAAQgGAAgEAFgAHEAYIAAgcIAAgCIAAgBIgCABIAAABIAAACIgDADIgDADIgEAGIgKAMQAAABAAAAQAAABgBAAQAAAAAAAAQAAAAAAAAIgDABIgDAAIAAgqIAHAAIAAAcIAAABIAAACIACgCIAAgCIADgEIAEgDIADgFIAKgNIABgCIACAAIAFAAIAAAqgAFkAYIAAgcIAAgCIgBABIgBACIgDADQgBABgCACIgEAGIgKAMQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgCABIgFAAIAAgqIAIAAIAAAcIAAABIAAACIACgCIAAgCIAEgEIADgDIAEgFIAKgNIABgCIACAAIAEAAIAAAqgAEFAYIgCgBIgDgCIgIgNIgDgDIgCAAIgGAAIAAATIgIAAIAAgqIAIAAIAAASIAFAAIACAAIADgDIAIgNIADgCIABAAIAHAAIgLAQIgCACIgDACIADABIADACIAMATgADRAYIAAgVIgUAAIAAAVIgIAAIAAgqIAIAAIAAAQIAUAAIAAgQIAIAAIAAAqgAgYAYIgCgBIAAAAIgLgSIAAADIgBAAIgKAPIgBAAIgCABIgGAAIAOgWIgOgUIAJAAIABABIAKAPIACAAIAAgCIAJgNIAAgBIACAAIAHAAIgPAUIAQAWgAhIAYIAAgTIgDAAIgDAAIgBADIgBAAIAAABIgJAMIgCACIgEABIgFAAIALgQIAFgEIgFgCQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgBgEIABgFQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABgBQABgBAEgBIAHgBIAQAAIAAAqgAhWgLIgBADIgBACQAAAEACACIAHAAIAHAAIAAgNIgHAAIgEAAQgBABAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAgAk6AYIAAgbIAAgDIAAgCIgPAZIAAABIgBAAIgCAAIAAAAIgCgBIgPgZIAAACIABADIAAAbIgIAAIAAgqIAHAAIABAAIACACIAOAUIAAACIABADIABgDIABgCIANgUQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIABAAIAGAAIAAAqgAmlAYIAAgqIARAAIAHAAIAEADIADADIABAEIAAADIgDADQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgDACQAEAAADADQACACAAAEIAAAHIgEADQgCACgDAAIgHABgAmdASIAJAAQAEAAADgBQACgDAAgDIAAgCIgCgDIgDgBIgEgBIgJAAgAmdAAIAJAAIACAAQABAAAAAAQABAAAAgBQAAAAAAAAQABAAAAgBIACgCIAAgDIAAgCIgBgCIgDgCIgDAAIgJAAgAnAgMIAAgIIAAgCIABgCIgCADIgIAFIgBgFIAHgDIACgBIABgBIgDgBIgHgFIABgCIAIAEIACABIAAgBIgBgCIAAgIIAFAAIAAAIIAAACIAAABIABgBIAIgEIACADIgIAEIAAABIgCAAIACACIAIADIgCAFIgIgFIgBgBIgBgCIABAEIAAAIgAG0gZIgEgCIgCgDIgBgEIAAgBIACgBIAEAAIAAADIACACQAAABAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIACABIADgBIADgBIABgCIAAgDIAEAAIABABIABABIgBAEIgDADIgDACIgGABIgFgBg");
	this.shape_1.setTransform(-2.7,-2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text2, new cjs.Rectangle(-48.7,-6.1,91.9,18.5), null);


(lib.t5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AmnCwIAAgVIhQAAIAAAVIgVAAIAAgoIALAAIAphbIASAAIApBbIALAAIAAAogAm0CIIgbg/IgcA/IA3AAgACnCZQgKgGgIgJQgHgIgDgKQgEgLAAgJQAAgJAEgKQADgKAHgJQAIgIAKgGQALgGAPABQALAAAKADQAKAEAIAIQAIAIAFAKIgYAAQgDgDgEgDQgEgEgFgBQgFgCgHAAQgLgBgIAGQgJAFgFAJQgEAIAAAKQAAAKAEAJQAGAJAIAFQAIAFALAAQAIABAHgEQAHgDAFgGIAYAAQgFAJgHAIQgIAHgKAEQgJAEgMAAQgPAAgLgFgAicCXQgNgIgHgNQgJgNAAgRQAAgPAJgOQAHgNANgIQANgHARAAQARAAANAHQANAIAHANQAJAOgBAPQABARgJANQgHANgNAIQgOAHgQAAQgQAAgOgHgAiSBDQgIAGgFAIQgFAJAAAKQAAAKAFAJQAFAJAIAFQAJAFALAAQALAAAJgFQAIgFAFgJQAFgJAAgKQAAgKgFgJQgFgIgIgGQgJgEgLAAQgLAAgJAEgAlwCXQgOgIgHgNQgIgNAAgRQAAgPAIgOQAHgNAOgIQANgHARAAQAQAAANAHQANAIAIANQAIAOAAAPQAAARgIANQgIANgNAIQgNAHgQAAQgRAAgNgHgAlmBDQgIAGgGAIQgEAJAAAKQAAAKAEAJQAGAJAIAFQAJAFALAAQALAAAIgFQAIgFAGgJQAEgJAAgKQAAgKgEgJQgGgIgIgGQgIgEgLAAQgLAAgJAEgArRCZQgLgGgHgJQgIgIgDgKQgEgLABgJQgBgJAEgKQADgKAIgJQAHgIALgGQALgGAOABQAMAAAKADQAKAEAIAIQAHAIAFAKIgYAAQgCgDgEgDQgEgEgFgBQgGgCgHAAQgLgBgIAGQgJAFgEAJQgFAIAAAKQAAAKAFAJQAFAJAIAFQAJAFALAAQAHABAIgEQAGgDAFgGIAZAAQgFAJgHAIQgIAHgKAEQgKAEgMAAQgOAAgLgFgALeCbIAAgTIAUAAIAAATgAK1CbIAAhSIgeBSIgRAAIgehSIAABSIgUAAIAAhuIAcAAIAeBUIAghUIAcAAIAABugAIFCbIAAhuIA8AAIAAAUIgnAAIAAAZIAmAAIAAAUIgmAAIAAAaIAnAAIAAATgAHdCbIAAhOIgyBOIgUAAIAAhuIAUAAIAABNIAyhNIAVAAIAABugAE/CbIAAhuIAbAAIAHAAIAKABQAGACAEADQAFADADAFQAEAGAAAJQAAAGgDAFQgCAEgDADIgEADQAJADAFAHQAEAIABAJQAAAIgEAHQgEAJgJAFQgKAEgSAAgAFUCIIAOAAIADAAIAHgCQACgCADgDQACgCAAgGQAAgCgBgDQgBgDgEgDQgEgDgHAAIgOAAgAFUBXIAKAAQAGAAAEgCQADgDABgCIAAgEQAAgGgCgCQgDgCgEgBIgFAAIgKAAgAEMCbIAAhaIgUAAIAAgUIA+AAIAAAUIgVAAIAABagAA2CbIAAhuIAVAAIAAAqIAQAAQAOABAHAEQAJAFADAIQADAIABAIQAAALgGAHQgEAIgIAEQgJAEgKAAgABLCIIAQAAQAHgBAEgDQAFgEAAgHQAAgGgFgEQgEgEgHAAIgQAAgAAUCbIgehSIgeBSIgWAAIArhuIASAAIArBugAkKCbIAAhuIAbAAIAHAAIAKABQAFACAFADQAFADADAFQAEAGgBAJQABAGgDAFQgCAEgEADIgDADQAJADAEAHQAFAIAAAJQAAAIgDAHQgEAJgKAFQgKAEgRAAgAj1CIIANAAIAEAAIAGgCQADgCACgDQADgCAAgGQAAgCgBgDQgCgDgDgDQgEgDgIAAIgNAAgAj1BXIAJAAQAHAAADgCQADgDABgCIABgEQgBgGgCgCQgCgCgEgBIgGAAIgJAAgAo/CbIAMgcIgqhSIAYAAIAeA6IAZg6IAXAAIgyBugALeB/IAAhSIAUAAIAABSgADYgqIAAgUIhQAAIAAAUIgVAAIAAgoIALAAIAohcIASAAIAqBcIAKAAIAAAogADLhSIgcg/IgbA/IA3AAgAEOhEQgNgHgIgNQgHgNgBgQQABgRAHgNQAIgNANgIQANgHARgBQARABANAHQANAIAIANQAHANAAARQAAAQgHANQgIANgNAHQgNAIgRAAQgRAAgNgIgAEZiXQgJAFgFAJQgFAJAAAKQAAAKAFAKQAFAIAJAFQAIAFALABQALgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgJgJgFQgIgEgLgBQgLABgIAEgAlDhEQgNgHgIgNQgHgNgBgQQABgRAHgNQAIgNANgIQANgHARgBQARABANAHQANAIAIANQAHANAAARQAAAQgHANQgIANgNAHQgNAIgRAAQgRAAgNgIgAk4iXQgJAFgFAJQgFAJAAAKQAAAKAFAKQAFAIAJAFQAIAFALABQALgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgJgJgFQgIgEgLgBQgLABgIAEgAn5hEQgNgHgHgNQgIgNAAgQQAAgRAIgNQAHgNANgIQAOgHARgBQAQABANAHQANAIAIANQAIANAAARQAAAQgIANQgIANgNAHQgNAIgQAAQgRAAgOgIgAnuiXQgJAFgFAJQgEAJAAAKQAAAKAEAKQAFAIAJAFQAJAFALABQALgBAIgFQAJgFAEgJQAGgIgBgLQABgKgGgJQgEgJgJgFQgIgEgLgBQgLABgJAEgAJMg+IgLgdIgqAAIgLAdIgXAAIAuhwIARAAIAuBwgAI5hvIgNggIgMAgIAZAAgAHWg+IAAhTIgeBTIgRAAIgehTIAABTIgVAAIAAhwIAcAAIAgBWIAehWIAcAAIAABwgAALg+IAAhwIA7AAIAAAVIgmAAIAAAZIAlAAIAAAUIglAAIAAAaIAmAAIAAAUgAgng+IAAhbIgUAAIAAgVIA8AAIAAAVIgUAAIAABbgAiFg+IAAhwIAUAAIAAArIARAAQAOAAAHAGQAJAEADAIQADAIABAIQAAAKgGAIQgEAIgIAEQgIAEgLABgAhxhSIARAAQAHAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgHAAIgRAAgAjdg+IAAhwIAbAAIAHAAIAKADQAGABAEADQAFADAEAFQADAGAAAJQAAAGgDAFQgCAFgDACIgEADQAJADAFAHQAEAHABAKQAAAIgEAIQgEAHgJAFQgKAGgSAAgAjIhSIAOAAIADAAIAHgDQADgBACgCQACgEAAgFQAAgCgBgDQgBgEgEgCQgEgCgHgBIgOAAgAjIiDIAKAAQAGAAADgCQAEgDABgCIAAgEQAAgFgCgDQgDgDgEAAIgFAAIgKAAgAmKg+IAAhbIgVAAIAAgVIA+AAIAAAVIgVAAIAABbgApRg+IAAhwIA3AAIAAAVIgiAAIAABbg");
	this.shape.setTransform(-0.3,1.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t5, new cjs.Rectangle(-78.3,-21.9,156.6,43.8), null);


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AgECuQgLgFgHgJQgIgIgDgKQgEgLAAgJQAAgKAEgKQADgKAIgIQAHgJALgFQAKgGAOAAQAMAAAKAEQAKAEAHAIQAIAHAFALIgYAAQgCgEgEgDQgEgDgGgCQgFgCgHAAQgLAAgIAGQgIAFgEAIQgFAJAAAKQAAAKAFAJQAFAJAHAFQAJAFALAAQAHAAAHgDQAHgDAFgHIAYAAQgEAKgIAHQgHAIgKAEQgKAEgMAAQgPAAgJgGgAlSCsQgNgHgHgNQgIgNAAgRQAAgQAIgNQAHgNANgIQANgIARAAQARAAANAIQANAIAIANQAIANAAAQQAAARgIANQgIANgNAHQgNAIgRAAQgQAAgOgIgAlHBZQgJAFgFAJQgFAIAAALQAAAKAFAJQAFAJAJAFQAIAFALAAQALAAAJgFQAIgFAFgJQAFgJAAgKQAAgLgFgIQgFgJgIgFQgJgFgLAAQgLAAgIAFgAE9CxIgLgcIgpAAIgMAcIgWAAIAuhvIAQAAIAvBvgAEqCBIgNghIgMAhIAZAAgADKCxIgigwIAAAwIgVAAIAAhvIAVAAIAAAwIAigwIAZAAIgqA3IAqA4gABgCxIAAhbIgVAAIAAgUIA+AAIAAAUIgVAAIAABbgAhICxIAAhOIgxBOIgVAAIAAhvIAVAAIAABOIAxhOIAVAAIAABvgAi3CxIAAgqIgTAAIgOgBQgHgBgGgFQgEgEgDgEIgCgJIgBgJIAAgkIAVAAIAAAhIAAAGQABAEADADQACACAEABIAGAAIATAAIAAgxIAVAAIAABvgAFcBfIgHAOIgJgFIAIgNIgPABIAAgLIAPABIgIgNIAJgFIAHAOIAGgOIAJAGIgIAMIAPgBIAAALIgPgBIAIAMIgIAGgAkMgUIAAgVIhQAAIAAAVIgVAAIAAgpIALAAIAphbIASAAIApBbIAKAAIAAApgAkZg9Igbg+IgcA+IA3AAgAh/guQgNgHgHgNQgIgNAAgRQAAgQAIgNQAHgNANgIQANgIARAAQARAAANAIQANAIAIANQAIANAAAQQAAARgIANQgIANgNAHQgNAIgRAAQgQAAgOgIgAh0iBQgJAFgFAJQgFAIAAALQAAAKAFAJQAFAJAJAFQAIAFALAAQALAAAJgFQAIgFAFgJQAFgJAAgKQAAgLgFgIQgFgJgIgFQgJgFgLAAQgLAAgIAFgAFcgpIAAgrIAAAAIgeArIgYAAIAfgpQgJgBgHgEQgGgEgEgIQgEgHAAgKIABgKQABgGAFgGQAEgGAIgEQAJgEAOAAIAgAAIAABvgAFDiBQgEACgCAEQgCAEAAAEQAAAEACAEQACADAEADQAFACAIAAIAMAAIAAghIgMAAQgIAAgFADgAEJgpIgLgcIgpAAIgMAcIgWAAIAuhvIAQAAIAvBvgAD2hZIgNghIgMAhIAZAAgACTgpIAAguIgoAAIAAAuIgVAAIAAhvIAVAAIAAAtIAoAAIAAgtIAVAAIAABvgAAtgpIAAhOIgwBOIgVAAIAAhvIAVAAIAABOIAwhOIAVAAIAABvgAjtgpIAAhvIAbAAIAHAAIAKACQAFACAFADQAFADADAFQAEAGAAAIQAAAHgDAFQgCAEgDADIgEADQAJADAFAHQAEAHABAKQAAAIgEAHQgEAIgJAFQgKAFgSAAgAjYg9IANAAIAEAAIAGgCQADgBADgDQACgDAAgFQAAgCgBgDQgBgEgEgCQgEgDgIAAIgNAAgAjYhtIAKAAQAGAAADgCQADgDABgCIABgEQAAgGgDgCQgCgDgEAAIgFgBIgKAAgAAHihQgGgCgCgFQgEgFgBgGIARAAQAAAEADACQADACADAAQAEAAADgCQACgCABgEIARAAQgBAGgDAFQgEAFgFACQgGADgIAAQgHAAgGgDg");
	this.shape.setTransform(-0.4,-1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4, new cjs.Rectangle(-39.7,-21.9,79.4,43.8), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("ABcCgQgNgIgIgNQgIgNAAgQQAAgQAIgOQAIgNANgHQANgIARAAQARAAANAIQANAHAHANQAIAOAAAQQAAAQgIANQgHANgNAIQgOAHgQAAQgRAAgNgHgABmBNQgIAFgFAIQgFAJAAAKQAAALAFAJQAFAIAIAFQAJAFALABQALgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgIgJgFQgIgFgLAAQgLAAgJAFgAlgCiQgLgFgHgJQgHgJgEgKQgDgKAAgKQAAgJADgKQAEgKAHgJQAHgIALgGQALgFAPAAQALAAAKAEQAKAEAIAHQAIAIAEALIgXAAQgDgEgEgDQgEgDgFgCQgFgCgHAAQgLAAgJAFQgIAFgFAJQgFAIAAAKQAAALAFAIQAFAJAJAFQAIAFALABQAIAAAHgEQAHgDAFgGIAYAAQgFAJgHAIQgIAHgKAEQgJAEgMAAQgPAAgLgFgAEjClIAAhTIgdBTIgRAAIgehTIAABTIgVAAIAAhvIAcAAIAfBVIAfhVIAcAAIAABvgAgOClIAAhvIAeAAQANAAAIAEQAIADAEAGQAEAGACAGIABAJIgCAMQgCAGgEAFQgEAFgIADQgIAEgMAAIgKAAIAAAqgAAGBnIAMAAIAHgBQAEgBADgDQADgDAAgHQAAgHgDgDQgDgDgEgBIgHAAIgMAAgAgwClIgLgdIgpAAIgMAdIgWAAIAuhvIAQAAIAvBvgAhDB0IgNggIgMAgIAZAAgAimClIAAhbIgoAAIAABbIgVAAIAAhvIBSAAIAABvgAFkBSIgHAOIgJgEIAIgOIgPABIAAgKIAPABIgIgOIAJgEIAHANIAGgNIAJAFIgIANIAPgBIAAAKIgPgBIAIANIgIAFgAgng6QgNgIgIgNQgIgNAAgQQAAgQAIgOQAIgNANgHQANgIARAAQAQAAANAIQANAHAHANQAIAOAAAQQAAAQgIANQgHANgNAIQgOAHgPAAQgRAAgNgHgAgdiNQgIAFgFAIQgFAJAAAKQAAALAFAJQAFAIAIAFQAJAFALABQAKgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgIgJgFQgIgFgKAAQgLAAgJAFgAjdg6QgNgIgHgNQgIgNAAgQQAAgQAIgOQAHgNANgHQANgIARAAQARAAANAIQANAHAIANQAIAOAAAQQAAAQgIANQgIANgNAIQgNAHgRAAQgQAAgOgHgAjSiNQgJAFgFAIQgFAJAAAKQAAALAFAJQAFAIAJAFQAIAFALABQALgBAJgFQAIgFAFgJQAFgIAAgLQAAgKgFgJQgFgIgIgFQgJgFgLAAQgLAAgIAFgAIkg1IAAhvIA8AAIAAAUIgnAAIAAAZIAlAAIAAAUIglAAIAAAaIAnAAIAAAUgAH7g1IAAhOIgxBOIgVAAIAAhvIAVAAIAABOIAxhOIAVAAIAABvgAGNg1IAAgvIgpAAIAAAvIgVAAIAAhvIAVAAIAAAsIApAAIAAgsIAUAAIAABvgAEBg1IAAhvIA8AAIAAAUIgnAAIAAAZIAlAAIAAAUIglAAIAAAaIAnAAIAAAUgADgg1IgfhTIgeBTIgXAAIAshvIASAAIAsBvgAA+g1IAAhvIAbAAIAHAAIAKACQAFABAFADQAFADADAGQAEAFAAAJQAAAHgDAEQgCAFgDACIgEADQAJADAFAHQAEAIABAJQAAAIgEAIQgEAIgJAFQgKAFgSAAgABThJIANAAIAEAAIAGgCQADgBADgDQACgDAAgFQAAgCgBgEQgBgDgEgDQgEgCgIgBIgNAAgABTh6IAKAAQAGAAADgCQADgCABgDIABgEQAAgFgDgDQgCgCgEgBIgFAAIgKAAgAhug1IAAhbIgVAAIAAgUIA+AAIAAAUIgVAAIAABbgAk2g1IAAhvIA4AAIAAAUIgjAAIAABbgAlfg1IAAhOIgxBOIgVAAIAAhvIAVAAIAABOIAxhOIAVAAIAABvgAn5g1IAAhvIAfAAQAOAAAIAEQAIADAEAGQAEAGABAGIABAJIgBAMQgCAGgFAFQgEAFgIADQgIAEgMAAIgKAAIAAAqgAnkhzIAMAAIAHgBQAEgBADgDQAEgDAAgHQAAgHgEgDQgDgDgEgBIgHAAIgMAAgAohg1IAAhbIgpAAIAABbIgVAAIAAhvIBSAAIAABvg");
	this.shape.setTransform(0.1,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-63.8,-21.9,127.6,43.8), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AAXCwIAAgVIhPAAIAAAVIgVAAIAAgoIALAAIAohbIASAAIApBbIAKAAIAAAogAAKCIIgbg/IgbA/IA2AAgAirCXQgMgIgIgNQgIgNAAgRQAAgPAIgOQAIgNAMgIQAOgHAQAAQASAAANAHQANAIAHANQAIAOAAAPQAAARgIANQgHANgNAIQgOAHgRAAQgQAAgOgHgAigBDQgJAGgEAIQgGAJAAAKQAAAKAGAJQAEAJAJAFQAJAFAKAAQALAAAJgFQAJgFAEgJQAFgJABgKQgBgKgFgJQgEgIgJgGQgJgEgLAAQgKAAgJAEgAE2CbIAAhOIgxBOIgVAAIAAhuIAVAAIAABNIAxhNIAVAAIAABugADOCbIgehSIgfBSIgWAAIAshuIASAAIAsBugAA2CbIAAhuIA8AAIAAAUIgnAAIAAAZIAlAAIAAAUIglAAIAAAaIAnAAIAAATgAjqCbIAAhSIgeBSIgRAAIgehSIAABSIgVAAIAAhuIAcAAIAgBUIAehUIAcAAIAABugAAcgqIAAgUIhJAAIAAhwIAVAAIAABcIAoAAIAAhcIAUAAIAABcIAMAAIAAAogADBhEQgNgHgIgNQgHgNgBgQQABgRAHgNQAIgNANgIQANgHARgBQARABANAHQANAIAHANQAIANAAARQAAAQgIANQgHANgNAHQgNAIgRAAQgRAAgNgIgADMiXQgJAFgFAJQgFAJAAAKQAAAKAFAKQAFAIAJAFQAIAFALABQALgBAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgJQgFgJgJgFQgIgEgLgBQgLABgIAEgAlZhEQgOgHgHgNQgIgNAAgQQAAgRAIgNQAHgNAOgIQANgHARgBQAQABANAHQANAIAIANQAIANAAARQAAAQgIANQgIANgNAHQgNAIgQAAQgRAAgNgIgAlPiXQgIAFgGAJQgEAJAAAKQAAAKAEAKQAGAIAIAFQAJAFALABQALgBAIgFQAIgFAGgJQAEgIAAgLQAAgKgEgJQgGgJgIgFQgIgEgLgBQgLABgJAEgAJxg+IAAhwIA7AAIAAAVIgmAAIAAAZIAlAAIAAAUIglAAIAAAaIAmAAIAAAUgAJJg+IAAhwIAUAAIAABwgAH0g+IAAhwIAVAAIAAArIAQAAQAOAAAHAGQAJAEADAIQADAIABAIQAAAKgGAIQgEAIgIAEQgJAEgKABgAIJhSIAQAAQAHAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgHAAIgQAAgAHLg+IAAgvIgoAAIAAAvIgWAAIAAhwIAWAAIAAAtIAoAAIAAgtIAUAAIAABwgAFlg+IAAgvIgpAAIAAAvIgUAAIAAhwIAUAAIAAAtIApAAIAAgtIAUAAIAABwgACBg+IAAhPIgxBPIgVAAIAAhwIAVAAIAABOIAxhOIAVAAIAABwgAhPg+IgLgdIgpAAIgMAdIgWAAIAuhwIARAAIAuBwgAhihvIgMggIgNAgIAZAAgAjzg+IAAhwIAbAAIAHAAIAKADQAFABAFADQAFADADAFQAEAGgBAJQABAGgDAFQgCAFgEACIgDADQAJADAEAHQAFAHAAAKQAAAIgDAIQgEAHgKAFQgKAGgRAAgAjehSIANAAIAEAAIAGgDQADgBACgCQADgEAAgFQAAgCgBgDQgCgEgDgCQgEgCgIgBIgNAAgAjeiDIAJAAQAHAAADgCQADgDABgCIABgEQgBgFgCgDQgCgDgEAAIgGAAIgJAAgAmZg+IAAgvIgpAAIAAAvIgUAAIAAhwIAUAAIAAAtIApAAIAAgtIAVAAIAABwgAn/g+IAAgvIgoAAIAAAvIgWAAIAAhwIAWAAIAAAtIAoAAIAAgtIAUAAIAABwgAplg+IAAhPIgyBPIgVAAIAAhwIAVAAIAABOIAyhOIAUAAIAABwg");
	this.shape.setTransform(0.1,1.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-71.4,-21.9,142.9,43.8), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00A7E0").s().p("AEhETIgMgcIgpAAIgLAcIgXAAIAuhuIAQAAIAvBugAENDjIgNghIgMAhIAZAAgACtETIgigwIAAAwIgVAAIAAhuIAVAAIAAAvIAigvIAZAAIgqA2IAqA4gABNETIAAhNIgxBNIgVAAIAAhuIAVAAIAABOIAxhOIAVAAIAABugAghETIAAguIgoAAIAAAuIgVAAIAAhuIAVAAIAAAsIAoAAIAAgsIAVAAIAABugAiAETIgbgmIgaAmIgZAAIAng3Igng3IAZAAIAaAmIAbgmIAXAAIgmA3IAmA3gAkSETIAAhuIA7AAIAAATIgmAAIAAAaIAlAAIAAAUIglAAIAAAZIAmAAIAAAUgAlFETIAAhbIgVAAIAAgTIA+AAIAAATIgVAAIAABbgAhjAzQgNgHgHgNQgIgNAAgQQAAgPAIgOQAHgNANgIQANgHARgBQARABANAHQANAIAIANQAHAOABAPQgBAQgHANQgIANgNAHQgOAIgQAAQgRAAgNgIgAhZgfQgIAFgFAJQgFAIAAAKQAAAKAFAKQAFAIAIAFQAJAFALAAQALAAAIgFQAJgFAFgJQAFgIAAgLQAAgKgFgIQgFgJgJgFQgIgEgLAAQgLAAgJAEgAFvA5IAAgsIAAAAIgeAsIgYAAIAegqQgJAAgGgFQgGgEgFgHQgDgHAAgJIABgLQABgFAFgHQAEgFAIgFQAIgDAOAAIAhAAIAABugAFWgfQgEADgCADQgCAEAAAEQAAAEACAEQACADAEADQAFACAHAAIANAAIAAggIgNAAQgHgBgFADgAEcA5IgMgdIgoAAIgMAdIgWAAIAuhuIAQAAIAuBugAEIAIIgMgfIgMAfIAYAAgACmA5IAAgvIgoAAIAAAvIgVAAIAAhuIAVAAIAAAsIAoAAIAAgsIAVAAIAABugABAA5IAAgvIgoAAIAAAvIgWAAIAAhuIAWAAIAAAsIAoAAIAAgsIAUAAIAABugAidA5IgagnIgaAnIgYAAIAmg4Igmg2IAYAAIAaAmIAagmIAYAAIgmA2IAmA4gAk0A5IANgcIgrhSIAZAAIAdA5IAag5IAXAAIgzBugAlvA5IgigxIAAAxIgVAAIAAhuIAVAAIAAAwIAigwIAZAAIgqA1IAqA5gACkilQgLgFgHgIQgHgJgDgKQgEgKAAgKQAAgKAEgKQADgKAHgIQAHgIALgGQALgFAPgBQALAAAKAEQAKAFAIAHQAIAIAFALIgYAAQgDgFgEgDQgEgCgFgDQgFgCgHAAQgLABgIAFQgJAFgFAIQgEAJAAAKQAAAKAEAJQAGAJAIAFQAIAFALABQAIAAAHgEQAHgDAFgHIAYAAQgFAKgHAHQgIAIgKAEQgJAEgMAAQgPAAgLgGgAH7ihIAAgrIAAAAIgdArIgZAAIAfgqQgJgBgHgEQgGgEgEgIQgEgGAAgLIACgKQAAgFAFgGQAEgHAJgDQAIgFAOAAIAgAAIAABwgAHjj6QgFACgBAEQgCAEAAAEQAAAEACAEQABADAFADQAEADAIgBIAMAAIAAghIgMAAQgIAAgEADgAGoihIgLgdIgpAAIgMAdIgWAAIAuhwIAQAAIAvBwgAGVjSIgMggIgNAgIAZAAgAE1ihIgigxIAAAxIgVAAIAAhwIAVAAIAAAxIAigxIAZAAIgqA3IAqA5gABhihIAAgvIgpAAIAAAvIgUAAIAAhwIAUAAIAAAtIApAAIAAgtIAVAAIAABwgAgEihIAAgrIgBAAIgdArIgYAAIAfgqQgKgBgGgEQgHgEgDgIQgEgGgBgLIACgKQABgFAEgGQAFgHAIgDQAJgFANAAIAgAAIAABwgAgdj6QgEACgCAEQgCAEAAAEQAAAEACAEQACADAEADQAEADAIgBIANAAIAAghIgNAAQgIAAgEADgAiNihIAAhwIAWAAIAAArIAPAAQAOAAAJAGQAHAFAEAHQADAIAAAJQAAAKgEAIQgFAHgIAEQgJAFgLAAgAh3i2IAQAAQAHABAFgEQAEgEAAgGQAAgIgEgDQgFgEgHAAIgQAAgAiuihIgfhTIgeBTIgXAAIAshwIASAAIAsBwgAkaihIgMgdIgoAAIgMAdIgWAAIAthwIARAAIAuBwgAkujSIgMggIgMAgIAYAAgAmUihIAAhcIgVAAIAAgUIA9AAIAAAUIgUAAIAABcgAnJihIAAhOIgxBOIgVAAIAAhwIAVAAIAABPIAxhPIAVAAIAABwg");
	this.shape.setTransform(1.8,0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-57.6,-32.9,115.3,65.8), null);


(lib.pic5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._5();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic5, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._4();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic4, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._3();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic3, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._2();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic2, new cjs.Rectangle(-120,-100,160,190), null);


(lib.pic1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-120,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pic1, new cjs.Rectangle(-120,-100,160,190), null);


(lib.legal = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgDAIIAAAAIAAgBIABgBIAAgBIACgBIAAgDIAAgBIAAAAIgBAAIgBgBIgBgBIAAgCIABgDIACgBIACAAIABABIABACIAAACIAAADIgBACIgEAHg");
	this.shape.setTransform(-40.9,2.6,1.153,1.154);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgHASIgDgCIgCgDIgBgEIABgEIAEgEIAGgBIAKgBIAAgDQAAgDgCgDQgCgCgDAAIgDAAIgGAEIgBgBIgBgBIgCgCIAHgEIAHgBIAFAAIAEADIACAEIABAGIAAAWIgDAAIgBgBIgBgBIgBgDIgDACIgCACIgDABIgDAAgAAAACIgDACIgDACIgBACIABADIABABIACABIACABIACgBIACgBIAFgDIAAgHg");
	this.shape_1.setTransform(-43.9,0.5,1.153,1.154);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgMASIAAgjIAMAAIAFABIAEACIADACIAAAEIAAACIgCACIgCADIgDABQAEAAADACQACACAAADIgBAFQgBAAAAABQAAAAAAABQgBAAAAAAQgBABgBAAIgDACIgGABgAgHANIAHAAQADAAADgCQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgCIgBgCIgCgBIgEAAIgHAAgAgHgCIAHAAIACAAIACgBQAAAAABgBQAAAAAAAAQAAAAAAgBQABAAAAAAIAAgCIAAgCIgBgCIgCgBIgDAAIgHAAg");
	this.shape_2.setTransform(-47.7,0.5,1.153,1.154);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AALASIgDgBIgCgCIgGgKIgBgDIgDAAIgEAAIAAAQIgGAAIAAgjIAGAAIAAAPIADAAIADAAIACgCIAGgLIABgBIACgBIAFAAIgKAQIgDABIADAAIACADIAJAPg");
	this.shape_3.setTransform(-51.7,0.5,1.153,1.154);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgEARIgFgEIgDgFIgBgIIABgGIACgGIAGgEIAGgBIAHABIAFADIgCADIAAAAIgDAAIgBgBIgCgBIgDAAIgEABQAAAAgBAAQAAAAgBABQAAAAAAAAQgBABAAAAQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAAAIgBAFIABAFIACAFIADACIADABIAEgBIACgBIACgBIABAAIACAAIABADIgCACIgEACIgDABIgEAAIgFgBg");
	this.shape_4.setTransform(-55.9,0.5,1.153,1.154);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgGARQgCgBgEgDQgCgCgBgEQgBgDAAgEIABgHQABgDACgCIAGgEIAGgBIAHABQADABACADIAEAFIABAHIgBAHIgEAGQgDADgCABQgDABgEAAQgDAAgDgBgAgGgJQgDADAAAGQAAAHADADQACADAEAAQAFAAADgDQACgEABgGQgBgFgCgEQgDgDgFAAQgEAAgCADg");
	this.shape_5.setTransform(-60.2,0.5,1.153,1.154);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAUAZIAAglIAAgBIgRAdIgBACIgBAAIgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIgRgeIAAAnIgGAAIAAgxIAFAAIABAAIABABIASAhIABgCIARgfIABgBIACAAIAFAAIAAAxg");
	this.shape_6.setTransform(-66.1,-0.3,1.153,1.154);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgBAEIgBgBIgBgCIgBgBIABgBIABgBIABgBIADAAIACABIAAABIAAACIAAACIgCABIgCABg");
	this.shape_7.setTransform(-72.9,2.1,1.153,1.154);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgLASIAAgjIAXAAIAAAFIgQAAIAAAeg");
	this.shape_8.setTransform(-74.8,0.5,1.153,1.154);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAJAZIAAgaIgBABIAAABIgBABIgPAWIgBABIgBAAIgEAAIAAgiIAGAAIAAAYIAAABIABgCIABgBIACgDIADgDIAKgPIABgBIABAAIAEAAIAAAigAgDgPIgDgCIgCgCIgBgDIAAgBIABgBIAEAAIAAADIABACIACABIAEAAIABgBIABgCIAAgDIAEAAIABABIABABIgBADIgCACIgDACIgFABg");
	this.shape_9.setTransform(32.4,-0.2,1.153,1.154);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAJASIAAgaIgBABIAAABIgBABIgPAVIgBABIgBABIgEAAIAAgjIAGAAIAAAaIABgDIABgBIAPgUIABgBIABgBIAEAAIAAAjg");
	this.shape_10.setTransform(27.8,0.6,1.153,1.154);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AALASIgDgBIgCgCIgGgKIgBgDIgDAAIgEAAIAAAQIgGAAIAAgjIAGAAIAAAPIAEAAIACAAIACgCIAGgLIABgBIACgBIAGAAIgLAQIgDABIADAAIACADIAJAPg");
	this.shape_11.setTransform(23.6,0.6,1.153,1.154);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgEARIgFgEIgDgFIgCgIIACgGIADgGIAFgEIAGgBIAHABIAFADIgCADIgBAAIgCAAIgBgBIgCgBIgEAAIgDABIgDACIgCAEIgBAFIABAFIACAFIADACIADABIAHgCIABgBIABAAIABAAIADADIgEACIgCACIgEABIgEAAIgFgBg");
	this.shape_12.setTransform(19.4,0.6,1.153,1.154);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AAIASIAAgRIgPAAIAAARIgHAAIAAgjIAHAAIAAAOIAPAAIAAgOIAHAAIAAAjg");
	this.shape_13.setTransform(15.1,0.6,1.153,1.154);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAJASIAAgYIAAgCIgBABIAAABIgBABIgCADIgDADIgKAPIgBABIgBABIgEAAIAAgjIAGAAIAAAaIABgDIABgBIAPgUIABgBIABgBIAEAAIAAAjg");
	this.shape_14.setTransform(10.5,0.6,1.153,1.154);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AAVAYIAAgMIgvAAIAAgjIAGAAIAAAeIAOAAIAAgeIAGAAIAAAeIAOAAIAAgeIAHAAIAAAeIAGAAIAAAPIAAABIgCABg");
	this.shape_15.setTransform(4.9,1.3,1.153,1.154);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgGARQgCgBgDgDIgEgGIgBgHIABgHIAEgFIAFgEIAGgBIAHABQAEABACADIADAFIABAHIgBAHIgDAGQgEADgCABQgDABgEAAQgDAAgDgBgAgHgJQgCADAAAGQAAAHACADQADADAEAAQAFAAADgDQACgEAAgGQAAgFgCgEQgDgDgFAAQgEAAgDADg");
	this.shape_16.setTransform(-1.1,0.6,1.153,1.154);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgQAZIAAgxIAPAAQAEAAAEABQADABADACIADAFIABAHIgBAGIgEAEQgCACgDABQgEACgEAAIgIAAIAAASgAgJABIAMgBIAEgBIACgDIABgEIgBgFIgCgDIgDgCIgNAAg");
	this.shape_17.setTransform(-5.4,-0.2,1.153,1.154);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAPAYIAAgMIgcAAIAAAKIgBABIgCABIgDAAIAAgRIABAAIACgBIADgBIACgEIABgEIACgUIAWAAIAAAeIAGAAIAAAPIAAABIgBABgAgEgBIgCAEIgCAEIAQAAIAAgZIgKAAg");
	this.shape_18.setTransform(-12.7,1.3,1.153,1.154);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgDASIgDgBIgEgCIgCgCIACgDIABAAIABAAIACABIACABIAEABIACAAIADgCIACgCIAAgCQAAgBAAAAQAAgBAAgBQgBAAAAAAQgBgBAAAAQgCgCgDAAIgFAAIAAgDIAFAAQADAAABgCQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIgBgCIgBgCIgDgBIgCAAIgDAAIgEACIgBAAIgBAAIgCgDIAEgDIAHgBIAFAAIAEACIADADIABAEIgBACIgBACIgCACIgDACQADAAACACQACACAAADQAAABAAABQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgEACIgFABg");
	this.shape_19.setTransform(-17,0.6,1.153,1.154);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgFARIgFgEQgCgBgCgFIgBgHIABgHIAEgFIAFgEIAGgBIAGABQACAAADADIADAFIABAHIgBABIgBAAIgWAAIABAGIACAEIADACIAEABIAEgBIADgBIACgBIABAAIABAAIACADIgDACIgDACIgEABIgEAAIgGgBgAgFgKQgCACgBAFIASAAIgBgEIgBgDIgDgCIgEgBQgDAAgDADg");
	this.shape_20.setTransform(-20.9,0.6,1.153,1.154);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgGARIgFgEQgDgDgBgDQgBgDAAgEIABgHQABgCADgDIAFgEIAGgBIAHABIAFAEQADADABACIABAHQAAAEgBADQgBADgDADIgFAEQgDABgEAAIgGgBgAgHgJQgCAEAAAFQAAAGACAEQADADAEAAQAFAAADgDQACgEAAgGQAAgFgCgEQgDgDgFAAQgFAAgCADg");
	this.shape_21.setTransform(-25.3,0.6,1.153,1.154);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgPAYIAAgvIAEAAQABAAAAABQAAAAAAAAQABAAAAAAQAAAAAAABIAAAEQACgDAEgBQADgCACAAIAGABIAEADIADAGIABAIIgBAGIgDAGIgFAEQgDACgEAAIgEgCIgEgDIAAAQgAgEgRIgEAFIAAAQIADACIAFACQAEgBACgDQADgEAAgFIgBgGIgBgEIgDgCIgEgBQgCAAgCABg");
	this.shape_22.setTransform(-29.7,1.3,1.153,1.154);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AAMAZIAAgrIgXAAIAAArIgIAAIAAgxIAnAAIAAAxg");
	this.shape_23.setTransform(-35,-0.2,1.153,1.154);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgFAZIgEgBIgDgCIgDgCIACgDIABAAIACAAIACABIAEABIADABIAEgBIADgCIACgEIABgFIAAgEIgCgDIgDgBIgEgBIgJABIgDgBIADgXIAYAAIAAACIgBADIgDABIgOAAIgDANIAGgBQAEgBADACQADAAACADQACACABACIABAGIgBAHIgEAGQgDACgDABQgDABgDAAg");
	this.shape_24.setTransform(26.3,9.8,1.153,1.154);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgLAZIAAgFIALAAIAAgjIgJAHIgBAAIgCAAIAAAAIgCgDIAOgNIAFAAIAAAsIAKAAIAAAFg");
	this.shape_25.setTransform(21.7,9.8,1.153,1.154);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgGAYQgEgBgCgEQgCgCgCgGQgBgEAAgHQAAgGABgEQACgGACgCIAGgFQADgCADAAIAHACQADABADAEQACACACAGQABAEAAAGQAAAHgBAEQgCAGgCACQgCADgEACIgHACQgDAAgDgCgAgDgSIgEADIgDAHIAAASIADAGIAEADIADABIAEgBIAEgDIACgGIABgKIgBgIQAAgEgCgDIgEgDIgEgBg");
	this.shape_26.setTransform(17,9.8,1.153,1.154);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgQAZIAAgCIABgCIAAgBIATgUIADgCIACgEIAAgEIgBgEIgBgDIgDgBIgEgBIgCABIgDABIgCACIgBAEIgBABIgCABIgEgBIACgHIAEgEIAFgDIAFgBIAGABQACABADADIADAEIABAGIgBAFIgCAFIgDACIgQASIAFgBIAQAAIABAAIABACIAAAEg");
	this.shape_27.setTransform(12.3,9.8,1.153,1.154);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgLAZIAAgFIALAAIAAgjIgJAHIgBAAIgBAAIgBAAIgCgDIAOgNIAFAAIAAAsIAKAAIAAAFg");
	this.shape_28.setTransform(7.7,9.8,1.153,1.154);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgGAZIgDgBIgEgCIgCgCIACgDIABAAIADAAIACABIACABIAFABIADgBIAEgCIACgEIABgFIgBgEIgCgDIgEgBIgDgBIgIABIgFgBIAFgXIAWAAIAAACIgBADIgDABIgOAAIgCANIAGgBQAEgBADACQACAAADADQADACAAACIABAGQAAAEgCADQAAADgDADQgDACgDABQgDABgDAAg");
	this.shape_29.setTransform(2.9,9.8,1.153,1.154);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AAGAZIAAgNIgVAAIgCAAIAAgBIgBgEIAYgfIAGAAIAAAfIAHAAIAAAFIgCAAIgFAAIAAANgAgKAHIAQAAIAAgXg");
	this.shape_30.setTransform(-1.8,9.8,1.153,1.154);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgGAYQgDgBgDgEQgDgEgBgEQgBgEAAgHQAAgGABgEQABgEADgEIAGgFQADgCADAAIAHACQADABADAEQACACACAGQABAEAAAGQAAAHgBAEQgCAGgCACQgCADgEACIgHACQgDAAgDgCgAgDgSIgEADIgDAHIAAASIADAGIAEADIADABIAEgBIAEgDIACgGIABgKIgBgIQAAgEgCgDIgEgDIgEgBg");
	this.shape_31.setTransform(-6.4,9.8,1.153,1.154);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgMAZIAUgoIADgDIgZAAIgBAAIgBgCIAAgEIAhAAIAAAFIgBABIgTApIgBABIgDABg");
	this.shape_32.setTransform(-11.1,9.8,1.153,1.154);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgMAZIAUgoIADgDIgZAAIgBAAIgBgCIAAgEIAhAAIAAAFIgBABIgTApIgBABIgDABg");
	this.shape_33.setTransform(-15.7,9.8,1.153,1.154);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AANAZIAAgXIgZAAIAAAXIgIAAIAAgxIAIAAIAAAWIAZAAIAAgWIAIAAIAAAxg");
	this.shape_34.setTransform(-23.3,9.8,1.153,1.154);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAOAZIAAgXIgaAAIAAAXIgHAAIAAgxIAHAAIAAAWIAaAAIAAgWIAGAAIAAAxg");
	this.shape_35.setTransform(-29.4,9.8,1.153,1.154);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AANAZIAAgiIAAgDIAAgEIgBADIgXAkIgCABIgBABIgGAAIAAgxIAHAAIAAApIABgDIAZglIACgBIAGAAIAAAxg");
	this.shape_36.setTransform(-35.6,9.8,1.153,1.154);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgGAZQgCgBgDgCQgDgCAAgDQgCgCAAgEQAAgEADgEQACgDAFAAQgEgBgCgDQgCgDAAgEIABgGIADgEIAFgDIAFgBIAGABIAFADIADAEIABAGQAAAEgCADQgCADgEABQAGAAABADQADADAAAFIgBAGQgBAEgCABQgCACgEABIgHABgAgDACIgDACIgCADIgBAEIAAAEIADADIADACIADAAIAEAAIADgCIADgDIABgEIgBgEIgDgDIgDgCIgEAAgAgDgTIgCACIgCADIAAADIAAADIACADIACACIADAAIAEAAIADgCIABgDIABgDIgBgDIgCgDIgCgCIgEgBg");
	this.shape_37.setTransform(-44.1,9.8,1.153,1.154);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgBAEIgCgBIAAgCIAAgCIAAgCIACAAIADAAIABAAIABACIABABIgBABIgBACIgBABIgCAAg");
	this.shape_38.setTransform(-49.4,12.3,1.153,1.154);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AAOAYIAAgMIgbAAIAAAKIgBABIgBABIgFAAIAAgRIACAAIACgBIADgBIABgEIACgEIADgUIAVAAIAAAeIAHAAIAAAPIgBABIgBABgAgEgBIgCAEIgCAEIAQAAIAAgZIgKAAg");
	this.shape_39.setTransform(-52.9,11.4,1.153,1.154);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgDAIIAAgBIAAgBIABgBIABgBIABgEIAAAAIgBAAIgBgBIgBgBIAAgCIABgDQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAIACAAIABABIABACIAAACIAAADIgBACIgDAEIgCADg");
	this.shape_40.setTransform(-57.3,12.9,1.153,1.154);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AAIAZIAAgZIABgBIgBABIgBABIAAABIgPAWIgBABIgCAAIgDAAIAAgiIAGAAIAAAZIACgDIAPgVIABgBIACAAIADAAIAAAigAgDgPIgDgCIgDgCIAAgDIAAgBIACgBIAEAAIAAADIAAACIACABIAEAAIABgBIABgFIAFAAIABABIAAABIgBADIgCACIgEACIgDABg");
	this.shape_41.setTransform(-60.6,9.9,1.153,1.154);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgIADIAAgFIARAAIAAAFg");
	this.shape_42.setTransform(-64.4,10.4,1.153,1.154);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgQAZIAAgDIAQgRIAHgHIABgEIABgEIgBgEIgCgDQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgEgBIgCABQgBAAAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgCADIgBADQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAAAIgCAAIgEAAIACgHIAEgEIAFgDIAFgBIAGABQADABABADIAEAEIABAGIgBAFIgCAFIgEACIgQASIAGgBIAPAAIACAAIABADIAAADg");
	this.shape_43.setTransform(-68.3,9.9,1.153,1.154);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgGAZIgEgDIgEgEIgCgFIADgCIACAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIACAFIAEACIADABIAFgBIADgCIABgDIABgDIAAgEIgCgDIgEgBIgFgBIAAgEIAEgBIAEgBIACgDIAAgEIAAgDIgCgDIgDgBIgDgBIgCABIgEABIgCACIgBADIgBACIgCAAIgEAAIADgHIADgEIAFgDIAFgBIAGABIAFADIADAEIABAFIAAAFIgCADIgDACIgDACQAFAAACADQACAEAAAEQAAAEgBACIgEAFQgCACgDABIgHABg");
	this.shape_44.setTransform(19,19.8,1.153,1.154);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgGAZIgDgBIgDgCIgDgCIACgDIACAAIACAAIABABIADABIAFABIADgBIAEgCIACgEIAAgFIAAgEIgCgDIgEgBIgDgBIgJABIgDgBIADgXIAYAAIAAACIgBADIgEABIgOAAIgCANIAGgBQAEgBADACQADAAACADQACACABACIABAGIgBAHIgEAGQgDACgDABQgDABgDAAg");
	this.shape_45.setTransform(14.4,19.8,1.153,1.154);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AAGAZIAAgNIgVAAIgBAAIgBgBIgBgEIAXgfIAHAAIAAAfIAHAAIAAAFIgCAAIgFAAIAAANgAgLAHIARAAIAAgVIAAgCg");
	this.shape_46.setTransform(9.6,19.8,1.153,1.154);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgGAYQgDgBgDgEQgDgEgBgEQgBgEAAgHQAAgGABgEQABgEADgEIAGgFQADgCADAAIAHACQADABADAEQACACACAGQABAEAAAGQAAAHgBAEQgCAGgCACQgCADgEACIgHACQgDAAgDgCgAgDgSIgEADIgDAHIAAASIADAGIAEADIADABIAEgBIAEgDIACgGIABgKIgBgIQAAgEgCgDIgEgDIgEgBg");
	this.shape_47.setTransform(5.1,19.8,1.153,1.154);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgMAZIAVgoIACgDIgZAAIgBAAIgBgCIAAgEIAhAAIAAAFIgBABIgTApIgCABIgCABg");
	this.shape_48.setTransform(0.4,19.8,1.153,1.154);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgGAYQgEgBgCgEQgDgDgBgFQgBgEAAgHQAAgGABgEQABgFADgDQADgEADgBQADgCADAAQAEAAADACQADABADAEQADADABAFIABAKIgBALQgBAFgDADQgCAEgEABQgDACgEAAQgDAAgDgCgAgDgSIgEADQgCADAAAEIgBAIIABAKIACAGIAEADIADABIAEgBIAEgDIADgGIABgKIgBgIQgBgEgCgDIgEgDIgEgBg");
	this.shape_49.setTransform(-4.3,19.8,1.153,1.154);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgGAYQgDgBgCgCIgEgGQgBgDAAgEIABgHIAFgHIAMgRIABgBIADAAIAFAAIgNATIgCABIgBABIAEgCIADAAIAGABQADABACACIADADIABAHIgBAGIgEAGQgCACgDABQgDABgEAAQgDAAgDgBgAgDAAIgEACIgCADIAAAFIAAADIACAEIAEACIADABIAEgBIAEgCIACgEIAAgDIAAgFIgCgDIgDgCIgFAAg");
	this.shape_50.setTransform(-9,19.8,1.153,1.154);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgKAZIAPgWIACgBIgEACIgFABIgFgBIgFgDIgCgDIgBgHIABgGIADgFIAGgDQADgCACAAQAEAAADACQACAAADADQACACABADQABAEAAADIgBAIIgQAYIgBABIgCAAgAgDgSIgDACIgCADIgBAEQAAAFADACQADACADAAIAEAAIADgCIADgDIAAgEIgBgEIgCgDIgDgCIgEgBg");
	this.shape_51.setTransform(-13.7,19.8,1.153,1.154);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AgLAZIATgoIACgDIgZAAIgBAAIAAgCIAAgEIAhAAIAAAFIAAABIgUApIgCABIgCABg");
	this.shape_52.setTransform(-18.3,19.8,1.153,1.154);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AgLAZIATgoIACgDIgZAAIgBAAIAAgCIAAgEIAhAAIAAAFIAAABIgUApIgCABIgCABg");
	this.shape_53.setTransform(-23,19.8,1.153,1.154);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AAGAZIAAgNIgWAAIgBAAIAAgBIgBgEIAXgfIAGAAIAAAfIAIAAIAAAEIgBABIAAAAIgHAAIAAANgAgLAHIARAAIAAgVIAAgCg");
	this.shape_54.setTransform(-27.8,19.8,1.153,1.154);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgGAYQgEgCgCgDQgCgCgCgGQgBgEAAgHQAAgGABgEQACgGACgCQADgEADgBIAGgCIAHACIAGAFQACACACAGQABAEAAAGQAAAHgBAEQgCAGgCACQgCAEgEABIgHACIgGgCgAgDgSIgEADQgCADAAAEIgBAIIABAKIACAGIAEADIADABIAEgBIAEgDQABgCABgEIABgKIgBgIQgBgFgBgCIgEgDIgEgBg");
	this.shape_55.setTransform(-32.4,19.8,1.153,1.154);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgLAZIAAgFIAKAAIAAggIABgDIgJAHIgBAAIgCAAIAAAAIgCgDIAOgNIAFAAIAAAsIAKAAIAAAFg");
	this.shape_56.setTransform(-37,19.8,1.153,1.154);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AANAZIAAgXIgZAAIAAAXIgIAAIAAgxIAIAAIAAAWIAZAAIAAgWIAIAAIAAAxg");
	this.shape_57.setTransform(-44.5,19.8,1.153,1.154);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AgQAZIAAgxIAPAAQAEAAAEABQADABADACIADAFIABAHIgBAGIgEAEQgCACgDABQgEACgEAAIgIAAIAAASgAgJABIAMgBIAEgBIACgDIABgEIgBgFIgCgDIgDgCIgNAAg");
	this.shape_58.setTransform(-49.8,19.8,1.153,1.154);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgOAZIAAgxIAdAAIAAAGIgWAAIAAArg");
	this.shape_59.setTransform(-54.4,19.8,1.153,1.154);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AgJAYIgIgFQgEgFgBgEQgCgGAAgEQAAgDACgGQACgFADgDQADgDAFgDQAGgCADAAQAEAAAGACQAFADADADQADADACAFQACAEAAAFQAAAGgCAEQgBAEgEAFQgEAEgEABQgEACgGAAQgFAAgEgCgAgGgRIgFAEQgDACgBAEQgCAEAAADQAAAFACADQABADADADIAFAEIAGABIAHgBIAGgEIADgGIABgIIgBgHIgDgGIgGgEIgHgBg");
	this.shape_60.setTransform(-60.1,19.8,1.153,1.154);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgDAIIAAgBIABgBIABgBIABgBIAAgDIAAgBIgBAAIgBgBIgBgBIgBgCIACgDQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIACAAIABABIABAEIAAADIgDAGIgCADg");
	this.shape_61.setTransform(34.6,-6.6,1.153,1.154);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgKAZIARgXIgEACIgEABIgGgBIgEgDIgDgDIgBgHIABgFIADgGIAGgDQADgCACAAQAEAAADACIAFADIADAGIABAGIAAAEIgDAGIgNAWIgCABIgCAAgAgDgSIgDACIgCADIgBAEQAAAFADACQADACADAAIAEAAIADgCIACgDIABgEIgBgEIgCgDIgDgCIgEgBg");
	this.shape_62.setTransform(31.2,-9.6,1.153,1.154);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AgLAZIAAgFIALAAIAAgjIgJAHIgBAAIgCAAIAAAAIgCgDIAOgNIAFAAIAAAsIAKAAIAAAFg");
	this.shape_63.setTransform(26.7,-9.6,1.153,1.154);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AAFAZIAAgNIgUAAIgCAAIAAgBIgBgEIAXgfIAHAAIAAAfIAHAAIAAAEIAAABIgBAAIgGAAIAAANgAgLAHIAQAAIAAgVIABgCg");
	this.shape_64.setTransform(21.9,-9.6,1.153,1.154);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AgFAZIgEgBIgEgCIgCgCIACgDIABAAIAFABIACABIAFABIADgBIADgCIADgEIABgFIgBgEIgDgDIgDgBIgDgBIgIABIgFAAIAFgZIAWAAIAAADIgBADIgCABIgPAAIgCAMIAGgBQAEAAADACQACABADACQADACAAACIABAGQAAAEgCADQAAACgDAEIgGADQgDACgDAAg");
	this.shape_65.setTransform(17.2,-9.6,1.153,1.154);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AgLAZIAAgFIALAAIAAgjIgJAHIgBAAIgBAAIgBAAIgCgDIAOgNIAGAAIAAAsIAJAAIAAAFg");
	this.shape_66.setTransform(12.6,-9.6,1.153,1.154);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("AgLAZIAAgFIAKAAIAAgjIgIAHIgBAAIgBAAIgBAAIgCgDIAOgNIAGAAIAAAsIAJAAIAAAFg");
	this.shape_67.setTransform(7.9,-9.6,1.153,1.154);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AAAANIAAgCIAAgBIAFgJIABgBIAAAAIgBAAIgFgJIAAgCIAAgBIADgBIAIANIAAAAIgIAOgAgJANIgBgCIAAgBIAGgJIABgBIgBAAIAAAAIgGgJIAAgCIABgBIACgBIAIANIAAAAIgIAOg");
	this.shape_68.setTransform(1.8,-8.8,1.153,1.154);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AgBAEIgCgBIgBgDIABgCIACgBIADAAIABABIABABIAAABIAAABIgBACIgBABIgCABg");
	this.shape_69.setTransform(-0.9,-7.1,1.153,1.154);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AgOAZIAAgxIAdAAIAAAGIgWAAIAAArg");
	this.shape_70.setTransform(-3,-9.6,1.153,1.154);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AAAAEIgCgBIgBgCIgBgBIABgBIABgBIACgBIACAAIABABIABABIAAACIgBACIgBABIgCABg");
	this.shape_71.setTransform(-6.4,-7.1,1.153,1.154);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AAOAZIAAgXIgaAAIAAAXIgHAAIAAgxIAHAAIAAAWIAaAAIAAgWIAGAAIAAAxg");
	this.shape_72.setTransform(-10.4,-9.6,1.153,1.154);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AgBAEIgBgBIgBgCIAAgBIAAgBIABgBIABgBIADAAIABABIABABIABABIgBABIgBACIgBABIgCABg");
	this.shape_73.setTransform(-14.5,-7.1,1.153,1.154);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AgGAYQgDgBgEgEQgEgEgCgFQgBgEAAgGQAAgFABgEIAGgIQACgDAGgDQAFgCAEAAQAFAAAEACQAEACADADIgCADIgBABIgBAAIgBgBIgCgBIgFgCIgEAAIgGABIgGAEIgDAGQgCAEAAADQAAAFACADIADAGIAGAEIAFABIAEAAIAGgCIADgCIAAAAIACAAIADADQgDADgEADQgFACgGAAQgFAAgEgCg");
	this.shape_74.setTransform(-18,-9.6,1.153,1.154);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("AANAZIAAgpIgBADIgYAlIgCABIgGAAIAAgxIAIAAIAAAiIgBADIAAAEIABgDIAYgkIABgBIACgBIAGAAIAAAxg");
	this.shape_75.setTransform(-26,-9.6,1.153,1.154);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AAUAfIAAgMIgnAAIAAAKIgBACIgBAAIgEAAIAAgSIAEAAIADgBIACgEIACgFIACgHIABgaIAeAAIAAArIAHAAIAAAQIAAACIgCAAgAgFgKIgEASIgDAFIAXAAIAAglIgPAAg");
	this.shape_76.setTransform(-32.3,-8.9,1.153,1.154);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AANAZIAAgXIgZAAIAAAXIgIAAIAAgxIAIAAIAAAWIAZAAIAAgWIAIAAIAAAxg");
	this.shape_77.setTransform(-38.5,-9.6,1.153,1.154);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AASAZIgBAAIgBgCIgFgLIgVAAIgFALIgBACIgBAAIgGAAIAUgxIAHAAIAUAxgAAAgOIgBACIgHASIARAAIgHgSIgBgCIgBgDg");
	this.shape_78.setTransform(-44.3,-9.6,1.153,1.154);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AAOAZIgCAAIgBgCIgMgSIgCgCIgDgBIgGAAIAAAXIgHAAIAAgxIAHAAIAAAWIAHAAIACgBIANgTIABgCIACAAIAGAAIgPAUQgCADgCABIADAAIARAZg");
	this.shape_79.setTransform(-49.4,-9.6,1.153,1.154);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AAAAAIAAAAIAIgNIACABIABABIAAACIgHAJIABABIAGAJIAAABIgBACIgCABgAgKAAIAAAAIAIgNIACABIABABIgBACIgFAJIABABIAEAJIABABIgBACIgCABg");
	this.shape_80.setTransform(-54.3,-8.8,1.153,1.154);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AgJAYIgIgFQgEgFgBgEQgCgGAAgEQAAgDACgGQABgFAEgDQADgDAFgDQAGgCADAAIAKACQAFADADADQADACACAGQACAEAAAFQAAAGgCAEQgBAFgEAEQgDAEgFABQgEACgGAAQgFAAgEgCgAgGgRIgFAEQgDACgBAEQgBAEgBADQABAFABADQAAADAEADIAFAEIAGABIAIgBIAFgEIAEgGIAAgIIAAgHIgEgGIgFgEIgIgBg");
	this.shape_81.setTransform(-61.3,-9.6,1.153,1.154);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AgJAYQgEgCgEgDQgEgFgBgEQgCgEAAgGQAAgFACgEQACgFADgDQACgDAGgDQAGgCADAAQAEAAAGACQAGADACADQAEADABAFQACAGAAADQAAAEgCAGQgBAEgEAFQgDADgFACQgEACgGAAQgFAAgEgCgAgGgRIgGAEIgEAGIAAAHIAAAIIAEAGIAGAEIAGABIAHgBIAFgEQADgDABgDQABgDABgFQgBgDgBgEQgBgEgDgCIgFgEIgHgBg");
	this.shape_82.setTransform(-67.7,-9.6,1.153,1.154);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AgJAYQgEgBgEgEQgDgEgCgFQgCgEAAgGQAAgFACgEQACgGADgCQADgDAFgDIAJgCQAEAAAGACQAFADADADIAFAIQACAEAAAFQAAAGgCAEIgFAJIgIAFQgEACgGAAQgFAAgEgCgAgGgRIgGAEIgDAGIgBAHIABAIIADAGIAGAEIAGABIAHgBIAGgEQADgDAAgDQACgDAAgFQAAgDgCgEQgBgEgCgCIgGgEIgHgBg");
	this.shape_83.setTransform(-74.2,-9.6,1.153,1.154);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal, new cjs.Rectangle(-79.6,-17.9,157.2,40.7), null);


(lib.butt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYAvIAAhdIAxAAIAAARIggAAIAAAWIAfAAIAAAPIgfAAIAAAWIAgAAIAAARg");
	this.shape.setTransform(47,0.8,1.333,1.333);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAvIAAhdIAxAAIAAARIggAAIAAAWIAfAAIAAAPIgfAAIAAAWIAgAAIAAARg");
	this.shape_1.setTransform(38.2,0.8,1.333,1.333);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARAvIAAgoIghAAIAAAoIgSAAIAAhdIASAAIAAAmIAhAAIAAgmIASAAIAABdg");
	this.shape_2.setTransform(28,0.8,1.333,1.333);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfAvIAAhdIA2AAIAAARIgkAAIAAATIAOAAQATAAAIAMQAEAHAAAJQAAANgJAIQgIAIgOAAgAgNAeIAOAAQAGAAAEgEQAEgDAAgFQAAgFgDgCQgEgFgHAAIgOAAg");
	this.shape_3.setTransform(17.4,0.8,1.333,1.333);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiAjQgPgOAAgVQAAgTAPgOQAOgPAUAAQAVAAAPAPQANAOAAATQAAAVgNAOQgPAOgVAAQgUAAgOgOgAgWgWQgJAKAAAMQAAANAJAKQAJAJANAAQANAAAKgJQAKgKgBgNQABgMgKgKQgJgJgOAAQgNAAgJAJg");
	this.shape_4.setTransform(4.9,0.8,1.333,1.333);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdAvIAAhdIAaAAQASAAAKAMQAFAHAAALQAAALgHAHQgIAKgSgBIgJAAIAAAkgAgMgFIALAAQAOAAgBgMQABgMgOAAIgLAAg");
	this.shape_5.setTransform(-6.5,0.8,1.333,1.333);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAiA4IAAgSIhDAAIAAASIgRAAIAAgjIAJAAIAihMIAPAAIAiBMIAJAAIAAAjgAgWAVIAtAAIgXg0g");
	this.shape_6.setTransform(-18.6,2,1.333,1.333);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgiAjQgPgOAAgVQAAgTAPgOQAOgPAUAAQAVAAAOAPQAOAOABATQgBAVgOAOQgOAOgVAAQgUAAgOgOgAgWgWQgJAKAAAMQAAANAJAKQAKAJAMAAQAOAAAJgJQAKgKgBgNQAAgMgJgKQgJgJgOAAQgMAAgKAJg");
	this.shape_7.setTransform(-32.7,0.8,1.333,1.333);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AARAvIAAhMIghAAIAABMIgSAAIAAhdIBEAAIAABdg");
	this.shape_8.setTransform(-45.6,0.8,1.333,1.333);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00A7E0").s().p("An6CDIAAkFIP1AAIAAEFg");
	this.shape_9.setTransform(0,-0.1,1.333,1.333);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.butt, new cjs.Rectangle(-67.5,-17.4,135.1,34.9), null);


// stage content:
(lib._120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgJSguyISlAAMAAABdlIylAAg");
	this.shape.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(272));

	// t5
	this.instance = new lib.t5();
	this.instance.parent = this;
	this.instance.setTransform(60.6,404.1,0.575,0.575,0,0,0,0.3,0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(212).to({_off:false},0).to({regX:0.1,scaleX:0.72,scaleY:0.72,y:404.2,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.3,scaleX:0.57,scaleY:0.57,y:404.1,alpha:0},6,cjs.Ease.get(1)).wait(1));

	// t4
	this.instance_1 = new lib.t4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(60.6,404.1,0.575,0.575,0,0,0,0.3,0.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(159).to({_off:false},0).to({regX:0.1,scaleX:0.72,scaleY:0.72,y:404.2,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.3,scaleX:0.57,scaleY:0.57,y:404.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(53));

	// t3
	this.instance_2 = new lib.t3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(60.6,404.1,0.575,0.575,0,0,0,0.3,0.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(106).to({_off:false},0).to({regX:0.1,scaleX:0.72,scaleY:0.72,y:404.2,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.3,scaleX:0.57,scaleY:0.57,y:404.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(106));

	// t2
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(60.6,404.1,0.575,0.575,0,0,0,0.3,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(53).to({_off:false},0).to({regX:0.1,scaleX:0.72,scaleY:0.72,y:404.2,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.3,scaleX:0.57,scaleY:0.57,y:404.1,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(159));

	// t1
	this.instance_4 = new lib.t1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(60.5,405.2,0.575,0.575,0,0,0,0.1,0.1);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:0,regY:0,scaleX:0.72,scaleY:0.72,y:404.1,alpha:1},6,cjs.Ease.get(1)).wait(47).to({regX:0.1,regY:0.1,scaleX:0.57,scaleY:0.57,alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(212));

	// 5.jpg
	this.instance_5 = new lib.pic5();
	this.instance_5.parent = this;
	this.instance_5.setTransform(100,245);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(212).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).wait(1));

	// 4.jpg
	this.instance_6 = new lib.pic4();
	this.instance_6.parent = this;
	this.instance_6.setTransform(100,245);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(159).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(53));

	// 3.jpg
	this.instance_7 = new lib.pic3();
	this.instance_7.parent = this;
	this.instance_7.setTransform(100,245);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(106).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(106));

	// 2.jpg
	this.instance_8 = new lib.pic2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(100,245);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(53).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(159));

	// 1.jpg
	this.instance_9 = new lib.pic1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(100,245);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({alpha:0},6,cjs.Ease.get(1)).to({_off:true},1).wait(212));

	// Слой 3
	this.instance_10 = new lib.butt();
	this.instance_10.parent = this;
	this.instance_10.setTransform(60.5,482.9,0.75,0.75);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(212).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(47).to({x:80.5,alpha:0},6,cjs.Ease.get(1)).wait(1));

	// Слой 2
	this.instance_11 = new lib.text2();
	this.instance_11.parent = this;
	this.instance_11.setTransform(60.4,532);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(106).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(97).to({alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(57));

	// fon
	this.instance_12 = new lib.legal();
	this.instance_12.parent = this;
	this.instance_12.setTransform(81.4,562.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00A7E0").s().p("ApDBSQgqgmAZg3QAWgzBFgdQBNggB9AAQAcAAAZADIAhAEIANADIgSAgQgngKghAAQhAAAgzASQhHAZgKAyQgHAdAWAbQAcAiA8gDQAUgBAkgMQAtgQAagVIBAg3IAMgHQAIgDAKAAIBEAAIAWBcIAqhcIBLAAIArBHIAghHIBFAAIg9CDIhGAAIgthMIghBMIgsAAIAAAAIhRAAIgDgXIhKAAIgYAWIgwAAQg5AUhJAAQhpAAgugqgAjGA3IAsAAIgEglgAGFB1IAsgsIgshjIBDAAIATA1IA3g1IBNAAIiFCEQgGAGgFACIgQADgAD9BpIhuAAIA8iDIBuAAQA2AAATAaQAQATgMAaQgLAYgdAQQgkAUg6AAIgDAAgADoBIIATAAQAXAAARgGQAcgIAGgVQAIgfg1AAIgTAAg");
	this.shape_1.setTransform(61.8,73,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.instance_12}]}).wait(272));

	// bg
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("EgJXAu4MAAAhdvISvAAMAAABdvg");
	this.shape_2.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(272));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(40,299.5,160,601);
// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/120x600_atlas_.jpg", id:"120x600_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;