(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"240x400_atlas_", frames: [[0,170,240,168],[0,340,240,168],[0,0,240,168]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib._1 = function() {
	this.spriteSheet = ss["240x400_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._2 = function() {
	this.spriteSheet = ss["240x400_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib._3 = function() {
	this.spriteSheet = ss["240x400_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaDLQgNgHgHgNQgIgNAAgSQAAgRAHgOQAIgNAMgIQAMgIAPAAQAMAAAJAFQAJAFAGAKIABAAIAAgRIAYAAIAABvIgYAAIAAgOIgBAAQgGAIgIAEQgHAEgHABIgIABQgOAAgMgHgAgMB6QgHAEgEAIQgEAIgBAKQABAKAEAHQAEAHAHAFQAHAEAJAAQAPAAAIgJQAJgKAAgPQAAgKgEgIQgEgHgHgFQgHgDgKgBQgJAAgHAFgAGODOIAAhIIgxBIIgaAAIAAhvIAaAAIAABIIAxhIIAbAAIAABvgAESDOIAAhIIgxBIIgaAAIAAhvIAaAAIAABIIAxhIIAbAAIAABvgACdDOIgbhLIgcBLIgdAAIAthvIAYAAIAtBvgAhzDOIAAhWIgaAAIAAgZIBPAAIAAAZIgaAAIAABWgAi4DOIAAhnIhCBnIgcAAIAAiUIAcAAIAABpIBChpIAbAAIAACUgAmrDOIAAhvIAxAAQALABAHAEQAHAEAEAHQADAHAAAGQAAAIgFAHQgFAFgHAEQAKACAFAHQAGAIAAAJQAAAIgEAIQgEAHgJAFQgIAFgNgBgAmQC4IATAAQAFgBADgBQADgCABgDIABgEIgBgFQgBgDgDgBQgCgCgGgBIgTAAgAmQCLIARAAQAEgBADgCQAEgDAAgEQAAgEgCgEQgDgCgGAAIgRAAgAk5gYIAAiUIAYAAIAAAPIAAAAQAFgIAHgEQAGgEAHgBIALgBQAPAAANAHQAMAHAIANQAHAOABARQAAAMgEALQgEAKgHAIQgHAJgLAEQgKAGgNgBIgKAAQgGgCgGgDQgGgEgFgGIgBAAIAAAxgAkRiSQgHAEgEAIQgEAIAAAJQAAALAEAIQAEAHAHAFQAHADAJAAQAKABAHgFQAHgFAFgHQAEgIAAgKQAAgHgDgIQgEgHgHgGQgHgFgLAAQgKAAgHAEgAIwhBQgNgGgHgOQgIgNAAgRQAAgSAHgOQAIgNAMgHQAMgJAQABQAMAAAJAEQAJAGAGAJIABAAIAAgQIAYAAIAABvIgYAAIAAgPIgBAAQgGAJgIADQgHAFgHABIgJAAQgOABgMgIgAI+iSQgHAFgEAIQgEAHgBALQABAJAEAHQAEAIAHAEQAHAFAKgBQAPAAAIgJQAJgJAAgQQAAgJgEgIQgEgIgHgEQgHgEgKAAQgKAAgHAEgAE4hBQgNgGgHgOQgIgNAAgRQAAgSAHgOQAIgNAMgHQAMgJAQABQAMAAAJAEQAJAGAGAJIABAAIAAgQIAYAAIAABvIgYAAIAAgPIgBAAQgGAJgIADQgHAFgHABIgJAAQgOABgMgIgAFGiSQgHAFgEAIQgEAHgBALQABAJAEAHQAEAIAHAEQAHAFAKgBQAPAAAIgJQAJgJAAgQQAAgJgEgIQgEgIgHgEQgHgEgKAAQgKAAgHAEgABkhCQgNgHgHgNQgIgOAAgQQAAgQAIgOQAHgOANgHQAOgJARABQARgBANAJQANAHAIAOQAHAOABAQQgBAQgHAOQgIANgNAHQgNAJgRgBQgRABgOgJgAByiSQgIAFgEAIQgEAIAAAJQAAAJAEAHQAEAIAIAFQAHAEAKAAQAKAAAHgEQAHgFAEgIQAEgHAAgJQAAgJgEgIQgEgIgHgFQgHgEgKAAQgKAAgHAEgAgYg/QgKgEgGgIQgHgIgDgJQgDgJgBgKIgBgQQAAgXAGgQQAGgPAJgJQAJgJAKgDQAJgEAIgCIANgBIAqAAIAAAYIgrABIgNAAQgGACgHADQgIADgFAIQgFAGgCAMIAAAAQAHgJAKgGQALgFANAAQAPAAAMAGQAMAHAHAMQAGAMABAQQgBASgHANQgHANgOAIQgNAHgSAAQgPABgLgGgAgMiOQgHADgEAIQgEAGAAALQAAAOAIAJQAJAIANAAQAPAAAIgJQAJgIAAgOQAAgKgEgIQgEgHgHgDQgHgFgKAAQgIAAgHAFgAifhBQgNgGgHgOQgIgNAAgRQAAgSAHgOQAIgNAMgHQAMgJAQABQAMAAAJAEQAJAGAGAJIABAAIAAgQIAYAAIAABvIgYAAIAAgPIgBAAQgGAJgIADQgHAFgHABIgJAAQgOABgMgIgAiRiSQgHAFgEAIQgEAHgBALQABAJAEAHQAEAIAHAEQAHAFAKgBQAPAAAIgJQAJgJAAgQQAAgJgEgIQgEgIgHgEQgHgEgKAAQgKAAgHAEgAmHg9QgIgFgEgGQgFgFgCgIIgBgOIAaAAQAAAHAEAFQADAEAJAAIADAAQADAAADgDQADgCAAgGQAAgFgCgDQgCgDgDAAIgEgBIgHAAIAAgXIAFAAQAHAAADgDQACgEAAgDQAAgFgCgDQgCgCgDAAIgEgBQgGAAgDADQgDADgBAFIgaAAQAAgKAFgIQAEgIAJgGQAIgEAMAAQANAAAJAEQAIAEAEAIQAEAHAAAHQAAAJgFAGQgFAHgIACQAKADAFAHQAFAIAAAJQAAALgFAIQgFAIgJAFQgJAEgMAAQgNAAgIgDgAoDhBQgNgGgHgOQgIgNAAgRQAAgSAHgOQAIgNAMgHQAMgJAQABQAMAAAJAEQAJAGAGAJIABAAIAAgQIAYAAIAABvIgYAAIAAgPIgBAAQgGAJgIADQgHAFgHABIgJAAQgOABgMgIgAn1iSQgHAFgEAIQgEAHgBALQABAJAEAHQAEAIAHAEQAHAFAKgBQAPAAAIgJQAJgJAAgQQAAgJgEgIQgEgIgHgEQgHgEgKAAQgKAAgHAEgAHpg9IAAgvIgpAAIAAAvIgaAAIAAhvIAaAAIAAApIApAAIAAgpIAbAAIAABvgADfg9IAAhXIgaAAIAAgYIBPAAIAAAYIgaAAIAABXgAqHg9IAAiUIAqAAQARAAALAFQALAFAFAIQAFAHACAIIACANQAAAHgCAIQgDAIgGAHQgFAHgLAFQgKAEgQAAIgOAAIAAA4gApriQIAQAAIAJgBQAGgBAEgEQAEgEAAgJQAAgJgEgEQgEgFgGgBIgJgBIgQAAg");
	this.shape.setTransform(0.1,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-68.1,-27.3,136.2,54.8), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjFFpIAAiUIAYAAIAAAOIAAAAQAFgHAHgEQAGgEAHgBIALgCQAPABANAHQAMAHAIANQAHANABATQAAALgEAKQgEALgHAIQgHAJgLAFQgKAEgNAAIgKgBQgGgBgGgDQgGgEgFgGIgBAAIAAAxgAidDvQgHAFgEAHQgEAIAAAKQAAAKAEAIQAEAIAHAEQAHADAJAAQAKABAHgFQAHgEAFgIQAEgIAAgJQAAgJgDgHQgEgIgHgFQgHgFgLAAQgKAAgHAEgArIFpIAAiUIAYAAIAAAOIABAAQAFgHAGgEQAHgEAHgBIAKgCQAQABAMAHQANAHAHANQAIANAAATQAAALgEAKQgDALgIAIQgHAJgKAFQgKAEgOAAIgKgBQgGgBgGgDQgGgEgFgGIAAAAIAAAxgAqfDvQgIAFgEAHQgEAIAAAKQAAAKAEAIQAEAIAIAEQAHADAJAAQAJABAIgFQAHgEAEgIQAEgIAAgJQAAgJgDgHQgDgIgHgFQgHgFgLAAQgKAAgHAEgANhFCQgLgFgHgJQgHgJgEgKQgDgKAAgJQAAgLADgJQAEgLAHgJQAHgJAMgFQALgHAPAAQARAAAMAJQANAIAHAMQAIAOAAARIAAAFIgBAGIhXAAQADAKAIAHQAHAFALAAQAHAAAGgCQAHgCAFgGIAeAAQgGANgIAIQgIAHgIADIgPAEIgJAAQgPABgLgGgAOZEBQgDgLgIgFQgIgGgKAAQgLAAgJAGQgIAGgDAKIA8AAIAAAAgAHxFCQgLgFgHgJQgHgJgEgKQgDgKAAgJQAAgLADgJQAEgLAHgJQAHgJAMgFQALgHAPAAQARAAAMAJQANAIAHAMQAIAOAAARIAAAFIgBAGIhXAAQADAKAIAHQAHAFALAAQAHAAAGgCQAHgCAFgGIAeAAQgGANgIAIQgIAHgIADIgPAEIgJAAQgPABgLgGgAIpEBQgDgLgIgFQgIgGgKAAQgLAAgJAGQgIAGgDAKIA8AAIAAAAgADEE/QgNgHgHgNQgIgOAAgQQAAgQAIgOQAHgNANgIQAOgJARAAQARAAANAJQANAIAIANQAHAOABAQQgBAQgHAOQgIANgNAHQgNAJgRgBQgRABgOgJgADSDvQgIAFgEAIQgEAIAAAJQAAAJAEAIQAEAHAIAFQAHAEAKAAQAKAAAHgEQAHgFAEgHQAEgIAAgJQAAgJgEgIQgEgIgHgFQgHgEgKAAQgKAAgHAEgAm1FEQgIgFgFgFQgEgHgCgHIgCgNIAbAAQAAAGADAFQAEAEAIAAIAEAAQADAAADgDQADgDAAgFQAAgGgDgCQgCgCgDgBIgEgBIgGAAIAAgXIAFAAQAGAAADgDQADgEgBgEQAAgFgCgCQgCgCgCgBIgFAAQgFAAgEADQgDADAAAFIgbAAQABgKAEgIQAFgJAIgEQAJgGAMAAQANABAIAEQAJAEAEAIQADAGAAAJQAAAIgFAGQgFAGgIADQAKADAFAHQAFAHAAAKQAAALgFAIQgEAIgJAFQgKAFgMgBQgMAAgIgDgAooFCQgLgFgHgJQgIgJgDgKQgEgKAAgJQAAgLAEgJQADgLAIgJQAHgJALgFQALgHAPAAQARAAANAJQANAIAHAMQAHAOAAARIAAAFIAAAGIhXAAQADAKAHAHQAIAFALAAQAGAAAHgCQAHgCAFgGIAeAAQgGANgIAIQgIAHgJADIgPAEIgIAAQgPABgLgGgAnxEBQgDgLgIgFQgHgGgLAAQgLAAgIAGQgIAGgEAKIA8AAIAAAAgAssFCQgLgFgHgJQgIgJgDgKQgEgKAAgJQAAgLAEgJQADgLAIgJQAHgJALgFQALgHAPAAQARAAANAJQANAIAHAMQAHAOAAARIAAAFIAAAGIhXAAQADAKAHAHQAIAFALAAQAGAAAHgCQAHgCAFgGIAeAAQgGANgIAIQgIAHgJADIgPAEIgIAAQgPABgLgGgAr1EBQgDgLgIgFQgHgGgLAAQgLAAgIAGQgIAGgEAKIA8AAIAAAAgAMVFEIAAhIIgxBIIgaAAIAAhvIAaAAIAABIIAxhIIAbAAIAABvgAKZFEIAAguIgpAAIAAAuIgaAAIAAhvIAaAAIAAApIApAAIAAgpIAbAAIAABvgAGoFEIgkg1IAAA1IgaAAIAAg1IgkA1IggAAIApg6Igmg1IAfAAIAiAzIAAgzIAaAAIAAAzIAigzIAfAAIgmA1IAoA6gACEFEIgbhLIgcBLIgdAAIAthvIAYAAIAtBvgAAJFEIAAhIIgwBIIgaAAIAAhvIAaAAIAABIIAwhIIAbAAIAABvgAj2FEIAAhXIgpAAIAABXIgaAAIAAhvIBeAAIAABvgAt4FEIAAgmIgQAAQgRAAgJgFQgKgDgDgHQgEgGAAgIIgBgNIAAgfIAbAAIAAAfIABAJQAAADAEAEQAEACAIABIAQAAIAAgyIAaAAIAABvgAloBcIAAiSIAYAAIAAAOIAAAAQAFgIAHgEQAGgDAHgCIALgBQAPAAANAHQAMAIAIANQAHANABARQAAALgEALQgEALgHAIQgHAJgLAEQgKAFgNAAIgKgBQgGgBgGgDQgGgEgFgGIgBAAIAAAwgAlAgcQgHAEgEAIQgEAHAAAJQAAALAEAIQAEAHAHAEQAHAEAJAAQAKAAAHgFQAHgEAFgHQAEgIAAgKQAAgHgDgIQgEgHgHgFQgHgGgLAAQgKAAgHAFgApGBcIAVgvIgphjIAeAAIAaBGIAahGIAeAAIg/CSgAICA2QgLgGgHgJQgHgIgEgLQgDgKAAgJQAAgJADgKQAEgLAHgIQAHgJAMgGQALgGAPAAQARAAAMAIQANAIAHANQAIAOAAAPIAAAGIgBAGIhXAAQADAKAIAGQAHAGALAAQAHAAAGgCQAHgCAFgHIAeAAQgGAOgIAHQgIAIgIADIgPADIgJABQgPAAgLgFgAI6gKQgDgLgIgGQgIgFgKgBQgLAAgJAHQgIAFgDALIA8AAIAAAAgACSA2QgLgGgHgJQgHgIgEgLQgDgKAAgJQAAgJADgKQAEgLAHgIQAHgJAMgGQALgGAPAAQARAAAMAIQANAIAHANQAIAOAAAPIAAAGIgBAGIhXAAQADAKAIAGQAHAGALAAQAHAAAGgCQAHgCAFgHIAeAAQgGAOgIAHQgIAIgIADIgPADIgJABQgPAAgLgFgADKgKQgDgLgIgGQgIgFgKgBQgLAAgJAHQgIAFgDALIA8AAIAAAAgAjOA0QgNgHgHgNQgIgNAAgSQAAgRAHgNQAIgOAMgHQAMgIAQAAQAMAAAJAFQAJAFAGAJIABAAIAAgPIAYAAIAABuIgYAAIAAgQIgBAAQgGAJgIAEQgHAEgHABIgJABQgOAAgMgHgAjAgcQgHAEgEAIQgEAIgBAJQABAKAEAHQAEAIAHADQAHAFAKAAQAPgBAIgIQAJgKAAgPQAAgJgEgHQgEgIgHgEQgHgFgKAAQgKABgHAEgAG2A4IAAhIIgxBIIgaAAIAAhuIAaAAIAABHIAxhHIAbAAIAABugAE6A4IAAgvIgpAAIAAAvIgaAAIAAhuIAaAAIAAAoIApAAIAAgoIAbAAIAABugABNA4IgbhKIgcBKIgcAAIAshuIAYAAIAtBugAhgA4IAAhuIAwAAQAMAAAHAEQAHAEADAHQADAGAAAIQAAAHgFAGQgEAHgHACQAJADAGAHQAFAHAAAIQAAAKgEAGQgEAIgIAFQgJAEgMABgAhGAgIATAAQAGAAACgBQADgCABgCIABgGIAAgEQgBgDgDgCQgDgCgGAAIgTAAgAhGgMIASAAQAEAAADgCQADgDAAgFQAAgDgCgDQgCgEgGAAIgSAAgAmZA4IAAhXIgpAAIAABXIgaAAIAAhuIBeAAIAABugAA9i4IAAgcIhUAAIAAhvIAZAAIAABYIAqAAIAAhYIAaAAIAABYIARAAIAAAzgAqHi4IAAgcIhrAAIAAAcIgbAAIAAg3IAOAAIA3h5IAYAAIA3B5IAOAAIAAA3gAqXjvIglhTIglBTIBKAAgALjjWQgLgFgHgJQgHgIgEgLQgDgKAAgKQAAgKADgJQAEgLAHgJQAHgJAMgGQALgFAPgBQARABAMAHQANAJAHANQAIANAAAQIAAAHIgBAFIhXAAQADALAIAFQAHAHALAAQAHAAAGgCQAHgDAFgGIAeAAQgGANgIAIQgIAHgIADIgPAEIgJABQgPAAgLgGgAMbkXQgDgLgIgFQgIgGgKgBQgLABgJAGQgIAGgDAKIA8AAIAAAAgAJejYQgNgJgHgNQgIgNAAgQQAAgRAIgNQAHgNANgJQAOgHARgBQARABANAHQANAJAIANQAHANABARQgBAQgHANQgIANgNAJQgNAHgRABQgRgBgOgHgAJskoQgIAEgEAIQgEAHAAAKQAAAJAEAIQAEAHAIAEQAHAGAKAAQAKAAAHgGQAHgEAEgHQAEgIAAgJQAAgKgEgHQgEgIgHgEQgHgFgKgBQgKABgHAFgAD2jYQgNgJgHgNQgIgNAAgQQAAgRAIgNQAHgNANgJQAOgHARgBQARABANAHQANAJAIANQAHANABARQgBAQgHANQgIANgNAJQgNAHgRABQgRgBgOgHgAEEkoQgIAEgEAIQgEAHAAAKQAAAJAEAIQAEAHAIAEQAHAGAKAAQAKAAAHgGQAHgEAEgHQAEgIAAgJQAAgKgEgHQgEgIgHgEQgHgFgKgBQgKABgHAFgAj5jXQgNgIgHgMQgIgOAAgSQAAgRAHgNQAIgOAMgIQAMgHAQgBQAMABAJAEQAJAFAGAKIABAAIAAgQIAYAAIAABvIgYAAIAAgPIgBAAQgGAJgIAEQgHADgHABIgJACQgOgBgMgGgAjrkoQgHAEgEAHQgEAIgBAKQABAKAEAHQAEAIAHAEQAHAEAKABQAPgBAIgJQAJgJAAgQQAAgKgEgHQgEgHgHgFQgHgEgKgBQgKABgHAFgAnGjWQgMgFgHgJQgIgJgDgLQgEgKAAgKQAAgKADgKQAEgLAHgIQAIgJALgFQALgGAQAAQAOABALAEQALAFAIAKQAIAJAEAMIgeAAQgEgHgHgEQgHgFgIAAQgLABgHAFQgIAEgEAHQgEAIAAAJQAAAKAEAIQAEAHAIAEQAHAGALAAIAHgBQAEgBAGgDQAFgDAEgHIAeAAQgEAMgIAIQgIAKgKAEQgLAFgOABQgQAAgLgGgAIXjUIAAgvIgpAAIAAAvIgaAAIAAhvIAaAAIAAApIApAAIAAgpIAbAAIAABvgAGjjUIAAgvIgpAAIAAAvIgaAAIAAhvIAaAAIAAApIApAAIAAgpIAbAAIAABvgACvjUIAAhIIgxBIIgaAAIAAhvIAaAAIAABIIAxhIIAbAAIAABvgAhIjUIAAgvIgpAAIAAAvIgaAAIAAhvIAaAAIAAApIApAAIAAgpIAbAAIAABvgAlSjUIAAhXIgaAAIAAgYIBPAAIAAAYIgaAAIAABXgAoUjUIAAhIIgxBIIgaAAIAAhvIAaAAIAABIIAxhIIAbAAIAABvg");
	this.shape.setTransform(0,2.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-97.6,-40.8,195.2,81.6), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIwFSQgNgGgHgOQgIgNAAgRQAAgSAHgOQAIgNAMgHQAMgJAQAAQAMAAAJAGQAJAEAGAKIABAAIAAgQIAYAAIAABvIgYAAIAAgPIgBAAQgGAIgIAFQgHADgHABIgJABQgOABgMgIgAI+EBQgHAFgEAIQgEAHgBALQABAJAEAIQAEAHAHAEQAHAFAKgBQAPAAAIgJQAJgJAAgPQAAgKgEgIQgEgHgHgFQgHgEgKAAQgKAAgHAEgAG3FUQgMgFgHgJQgIgIgDgLQgEgLAAgKQAAgKADgKQAEgLAHgIQAIgIALgGQALgFAQgBQAOAAALAGQALAEAIAKQAIAJAEAMIgeAAQgEgHgHgFQgHgDgIAAQgLAAgHAEQgIAFgEAIQgEAHAAAJQAAAKAEAIQAEAHAIAFQAHAEALAAIAHgBQAEAAAGgDQAFgDAEgHIAeAAQgEAMgIAIQgIAJgKAGQgLAEgOAAQgQABgLgGgAEsFSQgNgGgHgOQgIgNAAgRQAAgSAHgOQAIgNAMgHQAMgJAQAAQAMAAAJAGQAJAEAGAKIABAAIAAgQIAYAAIAABvIgYAAIAAgPIgBAAQgGAIgIAFQgHADgHABIgJABQgOABgMgIgAE6EBQgHAFgEAIQgEAHgBALQABAJAEAIQAEAHAHAEQAHAFAKgBQAPAAAIgJQAJgJAAgPQAAgKgEgIQgEgHgHgFQgHgEgKAAQgKAAgHAEgAiDFUQgLgFgHgJQgHgJgEgKQgDgKAAgJQAAgLADgJQAEgLAHgJQAHgJAMgFQALgHAPAAQARAAAMAJQANAIAHAMQAIAOAAARIAAAFIgBAGIhXAAQADAKAIAHQAHAFALAAQAHAAAGgCQAHgCAFgGIAeAAQgGANgIAIQgIAHgIADIgPAEIgJAAQgPABgLgGgAhLETQgDgLgIgFQgIgGgKAAQgLAAgJAGQgIAGgDAKIA8AAIAAAAgAkDFUQgLgFgHgJQgHgJgEgKQgDgKAAgJQAAgLADgJQAEgLAHgJQAHgJAMgFQALgHAPAAQARAAAMAJQANAIAHAMQAIAOAAARIAAAFIgBAGIhXAAQADAKAIAHQAHAFALAAQAHAAAGgCQAHgCAFgGIAeAAQgGANgIAIQgIAHgIADIgPAEIgJAAQgPABgLgGgAjLETQgDgLgIgFQgIgGgKAAQgLAAgJAGQgIAGgDAKIA8AAIAAAAgAn3FUQgLgFgHgJQgHgJgEgKQgDgKAAgJQAAgLADgJQAEgLAHgJQAHgJAMgFQALgHAPAAQARAAAMAJQANAIAHAMQAIAOAAARIAAAFIgBAGIhXAAQADAKAIAHQAHAFALAAQAHAAAGgCQAHgCAFgGIAeAAQgGANgIAIQgIAHgIADIgPAEIgJAAQgPABgLgGgAm/ETQgDgLgIgFQgIgGgKAAQgLAAgJAGQgIAGgDAKIA8AAIAAAAgADlFWIAAgmIgPAAQgSAAgJgFQgJgDgEgHQgDgGgBgIIAAgNIAAgfIAbAAIAAAfQgBAFABAEQABADADAEQAEACAJABIAPAAIAAgyIAbAAIAABvgABCFWIAAhvIgfAoIgVgQIAwg9IAeAAIAACUgAlPFWIAAguIgpAAIAAAuIgaAAIAAhvIAaAAIAAApIApAAIAAgpIAbAAIAABvgApDFWIAAhRIgdBRIgWAAIgehRIAABRIgaAAIAAhvIAmAAIAdBPIAchPIAnAAIAABvgAqrBlIAAgbIhQAAIAAAbIgaAAIAAgzIAOAAIAohWIAYAAIApBWIANAAIAAAzgAq8AyIgXgyIgWAyIAtAAgAKUBHQgNgHgHgLQgIgLgCgOIgQAAIAAAuIgbAAIAAhuIAbAAIAAAmIARAAQADgLAIgKQAIgKAMgFQAMgGAOAAQASAAANAIQANAIAIAOQAHAMAAARQAAAQgIANQgHANgNAIQgNAIgSAAQgQAAgMgGgAKfgKQgHAEgEAHQgEAIAAAKQAAAJAEAHQAEAHAHAFQAHAFAKAAQAKAAAHgFQAIgFADgHQAEgHAAgJQAAgKgDgIQgEgGgIgFQgHgEgKgBQgKABgHAEgAEsBIQgLgGgIgJQgHgIgEgLQgEgKAAgKQAAgLAEgIQAEgLAHgJQAHgIAMgFQALgGAPAAQAPAAALAFQALAFAIAJQAIAKADALIgeAAQgEgHgGgEQgHgEgJAAQgLABgHAEQgHAEgEAHQgEAHAAAKQAAAKAEAHQAEAHAHAFQAIAFAKAAIAHgBQAFgBAFgDQAFgDAEgHIAeAAQgEAMgHAJQgIAJgLAFQgLAFgOAAQgPAAgMgFgACmBFQgNgIgIgNQgHgNgBgQQABgRAHgMQAIgOANgIQANgIARAAQARAAAOAIQANAIAHAOQAIAMAAARQAAAQgIANQgHANgOAIQgNAIgRAAQgRAAgNgIgACzgKQgHAEgEAHQgEAIAAAKQAAAJAEAHQAEAHAHAFQAHAFAKAAQAKAAAHgFQAIgFADgHQAEgHAAgJQAAgKgDgIQgEgHgIgEQgHgEgKgBQgKABgHAEgAkkBIQgLgGgHgJQgIgIgDgLQgEgKAAgJQAAgKAEgJQADgLAIgIQAHgJALgGQALgGAPAAQARAAANAIQANAIAHANQAHANAAAQIAAAGIAAAGIhXAAQADAKAHAGQAIAGALAAQAGAAAHgCQAHgCAFgHIAeAAQgGAOgIAHQgIAIgJADIgPADIgIABQgPAAgLgFgAjtAHQgDgKgIgGQgHgFgLgBQgLAAgIAHQgIAFgEAKIA8AAIAAAAgAHjBKIAAhuIAbAAIAAAlIAXAAQANAAAIAGQAJAEAEAJQAEAIAAAJQgBAMgEAIQgFAIgIAEQgJAEgLABgAH+AyIAVAAIAEgBQADAAADgDQADgDAAgGQAAgCgBgDQgBgDgDgCQgDgCgFAAIgVAAgAGhBKIAAhXIgbAAIAAgXIBQAAIAAAXIgbAAIAABXgABfBKIAAgvIgpAAIAAAvIgbAAIAAhuIAbAAIAAAnIApAAIAAgnIAaAAIAABugAhMBKIAAhuIAbAAIAAAlIAXAAQANAAAIAGQAIAEAEAJQAEAIAAAJQgBAMgEAIQgFAIgHAEQgJAEgLABgAgxAyIAVAAIAEgBQADAAADgDQADgDAAgGQAAgCgBgDQgBgDgDgCQgDgCgFAAIgVAAgAh1BKIgchKIgbBKIgeAAIAthuIAYAAIAtBugAmCBKIAAhXIgbAAIAAgXIBQAAIAAAXIgbAAIAABXgAnEBKIAAhJIgxBJIgbAAIAAhuIAbAAIAABHIAxhHIAaAAIAABugAo5BKIgchKIgbBKIgeAAIAthuIAYAAIAtBugAHvidIAAiUIAYAAIAAAOIAAAAQAFgHAHgEQAGgEAHgBIALgCQAPAAANAIQAMAHAIAOQAHANABARQAAAMgEAKQgEALgHAJQgHAIgLAEQgKAFgNABIgKgCQgGAAgGgEQgGgDgFgHIgBAAIAAAxgAIXkXQgHAFgEAHQgEAIAAAJQAAAMAEAHQAEAHAHAEQAHAFAJAAQAKgBAHgEQAHgFAFgHQAEgHAAgLQAAgIgDgHQgEgHgHgGQgHgFgLgBQgKABgHAEgACfidIAAiUIAYAAIAAAOIAAAAQAFgHAHgEQAGgEAHgBIALgCQAPAAANAIQAMAHAIAOQAHANABARQAAAMgEAKQgEALgHAJQgHAIgLAEQgKAFgNABIgKgCQgGAAgGgEQgGgDgFgHIgBAAIAAAxgADHkXQgHAFgEAHQgEAIAAAJQAAAMAEAHQAEAHAHAEQAHAFAJAAQAKgBAHgEQAHgFAFgHQAEgHAAgLQAAgIgDgHQgEgHgHgGQgHgFgLgBQgKABgHAEgAmLidIAAiUIAYAAIAAAOIABAAQAFgHAGgEQAHgEAHgBIAKgCQAQAAAMAIQANAHAHAOQAIANAAARQAAAMgEAKQgDALgIAJQgHAIgKAEQgKAFgOABIgKgCQgGAAgGgEQgGgDgFgHIAAAAIAAAxgAlikXQgIAFgEAHQgEAIAAAJQAAAMAEAHQAEAHAIAEQAHAFAJAAQAJgBAIgEQAHgFAEgHQAEgHAAgLQAAgIgDgHQgDgHgHgGQgHgFgLgBQgKABgHAEgAKJjFQgNgIgHgMQgIgOAAgSQAAgRAHgNQAIgOAMgIQAMgHAQgBQAMABAJAEQAJAFAGAKIABAAIAAgQIAYAAIAABvIgYAAIAAgPIgBAAQgGAJgIAEQgHADgHABIgJACQgOgBgMgGgAKXkWQgHAEgEAHQgEAIgBAKQABAKAEAHQAEAIAHAEQAHAEAKABQAPgBAIgJQAJgJAAgQQAAgKgEgHQgEgHgHgFQgHgEgKgBQgKABgHAFgAE5jGQgNgJgHgNQgIgNAAgQQAAgRAIgNQAHgNANgJQAOgHARgBQARABANAHQANAJAIANQAHANABARQgBAQgHANQgIANgNAJQgNAHgRABQgRgBgOgHgAFHkWQgIAEgEAIQgEAHAAAKQAAAJAEAIQAEAHAIAEQAHAGAKAAQAKAAAHgGQAHgEAEgHQAEgIAAgJQAAgKgEgHQgEgIgHgEQgHgFgKgBQgKABgHAFgApCjEQgLgFgIgJQgHgJgEgLQgEgKAAgKQAAgKAEgKQAEgLAHgIQAHgJAMgFQALgGAPAAQAPABALAEQALAFAIAKQAIAJADAMIgeAAQgEgHgGgEQgHgFgJAAQgLABgHAFQgHAEgEAHQgEAIAAAJQAAAKAEAIQAEAHAHAEQAIAGAKAAIAHgBQAFgBAFgDQAFgDAEgHIAeAAQgEAMgHAIQgIAKgLAEQgLAFgOABQgPAAgMgGgAtZjEQgLgEgGgIQgGgIgDgJQgEgJgBgJIgBgQQABgYAFgPQAGgQAJgJQAJgIAKgFQAKgEAIAAIANgBIAqgBIAAAXIgrABIgNACQgHAAgHAEQgHAEgFAGQgGAIgCALIABAAQAGgJALgGQAKgFAOAAQAQAAAMAHQALAGAHAMQAHAMAAAQQAAASgIANQgHAOgNAHQgOAIgSAAQgQgBgKgFgAtNkUQgHAEgFAHQgEAHAAAKQAAAQAJAIQAJAJAOAAQAOgBAJgIQAIgJAAgPQAAgKgEgHQgEgHgHgEQgHgDgJAAQgJAAgHADgAP+jCIAAhSIgdBSIgWAAIgehSIAABSIgaAAIAAhvIAmAAIAdBPIAchPIAnAAIAABvgANijCIAAhSIgdBSIgWAAIgehSIAABSIgaAAIAAhvIAmAAIAdBPIAchPIAnAAIAABvgAGjjCIAAhvIA+AAIAAAYIgkAAIAABXgABujCIAAhXIgpAAIAABXIgaAAIAAhvIBeAAIAABvgAgvjCIgXgkIgWAkIghAAIAlg5Igig2IAfAAIAVAiIAVgiIAfAAIgjA2IAmA5gAijjCIAAhvIAaAAIAABvgAkHjCIAAhvIAbAAIAAAnIAXAAQANAAAIAFQAJAFAEAIQAEAJAAAJQgBAMgEAHQgFAIgIAFQgJAEgLAAgAjsjZIAVAAIAEgBQADgBADgDQADgCAAgGQAAgDgBgCQgBgEgDgCQgDgBgFAAIgVAAgAnNjCIAAhXIgbAAIAAgYIBQAAIAAAYIgbAAIAABXgAqPjCIAAhvIAaAAIAABvgArzjCIAAhvIAbAAIAAAnIAXAAQANAAAIAFQAJAFAEAIQAEAJAAAJQgBAMgEAHQgFAIgIAFQgJAEgLAAgArYjZIAVAAIAEgBQADgBADgDQADgCAAgGQAAgDgBgCQgBgEgDgCQgDgBgFAAIgVAAgAwGjCIAigyIgEAAIgEABQgMgBgKgGQgKgFgGgMQgGgLAAgPQAAgOAGgMQAHgMALgHQALgGAQgBQAPAAAMAHQAMAHAGALQAGANAAAPQAAAJgCAHIgFANIgGAKIgnA7gAv3k4QgGAHAAAMQAAAIADAGQAEAFAFAEQAGACAGAAQAIAAAGgDQAFgDADgGQADgGAAgHQAAgMgHgHQgGgIgMAAQgLAAgHAIg");
	this.shape.setTransform(2,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-110,-40.8,220.1,81.6), null);


(lib.p3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._3();
	this.instance.parent = this;
	this.instance.setTransform(-120,-84);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p3, new cjs.Rectangle(-120,-84,240,168), null);


(lib.p2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._2();
	this.instance.parent = this;
	this.instance.setTransform(-120,-84);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p2, new cjs.Rectangle(-120,-84,240,168), null);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._1();
	this.instance.parent = this;
	this.instance.setTransform(-120,-84);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1, new cjs.Rectangle(-120,-84,240,168), null);


// stage content:
(lib._240x400 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Ayq/KMAlVAAAMAAAA+VMglVAAAg");
	this.shape.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(291));

	// p3
	this.instance = new lib.p3();
	this.instance.parent = this;
	this.instance.setTransform(140,176);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(190).to({_off:false},0).to({x:120},5,cjs.Ease.get(1)).wait(92).to({alpha:0.5},3,cjs.Ease.get(1)).wait(1));

	// p2
	this.instance_1 = new lib.p2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(140,176);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(95).to({_off:false},0).to({x:120},5,cjs.Ease.get(1)).to({_off:true},96).wait(95));

	// p1
	this.instance_2 = new lib.p1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(140,176);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:120},5,cjs.Ease.get(1)).to({_off:true},96).wait(190));

	// t3
	this.instance_3 = new lib.t3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(119.9,314.2,0.8,0.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(190).to({_off:false},0).to({scaleX:1,scaleY:1,y:314.1,alpha:1},5,cjs.Ease.get(0.99)).wait(90).to({scaleX:0.8,scaleY:0.8,y:314.2,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// t2
	this.instance_4 = new lib.t2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(120,312.9,0.8,0.8);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(95).to({_off:false},0).to({scaleX:1,scaleY:1,y:312.5,alpha:1},5,cjs.Ease.get(0.99)).wait(90).to({scaleX:0.8,scaleY:0.8,y:312.9,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(95));

	// t1
	this.instance_5 = new lib.t1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(118.4,314.3,0.8,0.8);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({scaleX:1,scaleY:1,x:118.1,alpha:1},5,cjs.Ease.get(0.99)).wait(90).to({scaleX:0.8,scaleY:0.8,x:118.4,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(190));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgFAPIgFgEIgDgFIgBgGIABgGIADgEIAFgEIAFgBIAGABIAFAEIACAEIABAGIgBAGIgCAFIgFAEIgGABIgFgBgAgFgHQgCADAAAEQAAAFACADQACADADAAQAEAAACgDQADgDAAgFQAAgEgDgDQgCgDgEAAQgDAAgCADg");
	this.shape_1.setTransform(38.8,368.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNAVIAAgoIAEAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIABAEIAFgEQACgBACgBIAFABIADADIADAGIAAAGIAAAFIgDAFIgEADQgDACgDAAIgDgBIgEgDIAAAOgAgDgOIgEAEIAAANIADADIAEAAQADAAADgCQACgEAAgEIAAgFIgCgDIgDgCIgDgBIgDABg");
	this.shape_2.setTransform(35.5,369.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAKAVIAAglIgUAAIAAAlIgGAAIAAgpIAhAAIAAApg");
	this.shape_3.setTransform(31.6,368.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgCAPIAAgZIgLAAIAAgEIAbAAIAAAEIgLAAIAAAZg");
	this.shape_4.setTransform(26.3,368.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgMAVIAAgoIADAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIABAEIAFgEQACgBACgBIAFABIADADIADAGIABAGIgBAFIgDAFIgEADQgCACgEAAIgDgBIgEgDIAAAOgAgDgOIgEAEIAAANIAEADIADAAQAEAAACgCQACgEAAgEIgBgFIgBgDIgCgCIgEgBIgDABg");
	this.shape_5.setTransform(23.2,369.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGAPIgDgBIgBgDIgBgDIABgEIADgDIAGgBIAIgBIAAgCQgBgEgBgBQAAgBgBAAQAAgBgBAAQAAAAgBAAQgBAAgBAAIgBAAIgDABIgCABIgBABIgBAAIgBgBIAAgCIAFgEIAFgBIAFABIADACIACAEIABAFIAAASIgDAAIgBAAIAAgBIgBgDIgCACIgDACIgCAAIgCABIgEgBgAAAACIgCABIgDACIgBACIAAACIABACIADAAIABABIABgBIADAAIACgCIACgBIAAgGIgHAAg");
	this.shape_6.setTransform(19.9,368.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAMAPIAAgSIAAgCIAAgCIgKARIgBABIgBAAIAAAAIAAAAIgBgBIgKgRIAAACIAAACIAAASIgFAAIAAgdIAEAAIACAAIABABIAJAOIAAACIAAABIABgBIAAgCIAJgOIABgBIABAAIAFAAIAAAdg");
	this.shape_7.setTransform(16.3,368.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFAUIgGgEQgDgDgCgEIgBgJQAAgEABgEIAFgHQACgDAFgBQADgCAEAAQAFAAADACIAGADIgCAEIAAAAIgBAAIgBAAIgDgCIgCgBIgFgBIgFABQgDABgCADIgDAFIgBAGIABAHIADAFIAFAEIAEABIAEAAIADgBIACgBIADgCIAAgBIABAAIABABIACADIgHAEQgDACgGAAQgEAAgDgCg");
	this.shape_8.setTransform(12.3,368.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAAAKIAAgGIAAgBIAAgBIgCABIgFADIgBgCIAFgDIABAAIABgBIgCAAIgFgDIABgCIAFADIACABIAAgBIAAgBIAAgGIABAAIAAAGIAAABIAAABIACgBIAFgDIABACIgFADIgBAAIgBAAIACABIAFADIgBACIgFgDIgBAAIgBgBIAAACIAAAGg");
	this.shape_9.setTransform(8.9,366.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgFAVIgEgCIgCgEIgDgEIADgCIACAAIABACIABACIACACIACABIADABIAEgBIADgBIABgDIABgDIgBgDIgBgCIgEgCIgEAAIAAgEIADAAIAEgBIACgDIAAgDIAAgDIgCgCIgDgBIgDgBIgBABIgCABIgDACIgBACIgBABIgBAAIgDAAQAAgDACgCIACgEIAFgCIAEgBIAFABIAEACIACAEIACAEIgBAEIgCADIgCABIgDACQAFAAABADQADACAAAEIgBAGIgEADIgEADIgGABIgFgBg");
	this.shape_10.setTransform(176,389.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgFAVIgDgBIgDgBIgCgCIACgCIABgBIACAAIABABIADABIADABIADgBIADgCIACgDIABgEIgBgEIgBgCIgDgBIgDgBIgHABIgEgBIAEgUIATAAIAAADIAAACIgDAAIgMAAIgCALIAFAAIAGABIAEACIADAEIABAFQAAADgCADIgDAFIgFADIgFABIgEgBg");
	this.shape_11.setTransform(172.5,389.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAFAWIAAgLIgSAAIgBgBIgBgBIAAgDIAUgaIAFAAIAAAaIAGAAIAAADIAAABIgBABIgFAAIAAALgAgJAGIAOAAIAAgRIAAgBIAAgCg");
	this.shape_12.setTransform(169,389.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgFAVQgDgCgCgDQgCgCgBgEQgCgFAAgFQAAgFACgEQABgEACgCQACgEADgBQADgBACAAIAGABQADABACAEIAEAGIABAJIgBAKIgEAGQgCADgDACIgGABQgCAAgDgBgAgDgPIgDADIgCAFIgBAHIABAIIACAGIADACIADABIAEgBIADgCIACgGIABgIIgBgHIgCgFIgDgDIgEgBIgDABg");
	this.shape_13.setTransform(165.5,389.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgKAWIARgiIACgDIgVAAIgBAAIgBgCIAAgDIAdAAIAAACIAAACIgBABIgRAjIgBABIgCABg");
	this.shape_14.setTransform(162.1,389.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgFAVQgDgCgCgDQgCgCgBgEQgCgFAAgFQAAgFACgEQABgEACgCQACgEADgBQADgBACAAIAGABQADABACAEIAEAGIABAJIgBAKIgEAGQgCADgDACIgGABQgCAAgDgBgAgDgPIgDADIgCAFIgBAHIABAIIACAGIADACIADABIAEgBIADgCIACgGIABgIIgBgHIgCgFIgDgDIgEgBIgDABg");
	this.shape_15.setTransform(158.5,389.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgFAVIgFgDIgDgFIgBgGIACgGIAEgGIAJgOIACgBIABgBIAFAAIgLAQIgBACIgBABIADgCIADAAIAFABIAEACIADADIABAGQAAADgCACIgDAFIgEADIgGABIgFgBgAgDAAIgDACIgCADIAAADIAAAEIACACIADACIADABIADgBIADgCIACgCIABgEIgBgEIgCgCIgCgCIgEAAIgDAAg");
	this.shape_16.setTransform(155.1,389.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgIAWIAMgRIABgCIABgBIgEACIgDAAIgFgBIgDgCIgDgDIgBgFIABgFIADgFIAEgDIAGgBIAFABIAFADIACAFIABAFIAAAEIgBADIgCACIgCADIgJAPIgBABIgCABgAgCgPIgDABIgCADIAAADQgBAEADADQACABADAAIADAAIAEgCIABgCIABgDIgBgEIgBgDIgEgBIgCgBIgDABg");
	this.shape_17.setTransform(151.5,389.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgKAWIARgiIACgDIgVAAIgBAAIgBgCIAAgDIAdAAIAAACIAAACIgBABIgRAjIgBABIgCABg");
	this.shape_18.setTransform(148.1,389.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgKAWIARgiIACgDIgVAAIgBAAIgBgCIAAgDIAdAAIAAACIAAACIgBABIgRAjIgBABIgCABg");
	this.shape_19.setTransform(144.6,389.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAFAWIAAgLIgSAAIgBgBIgBgBIAAgDIAUgaIAFAAIAAAaIAGAAIAAADIAAABIgBABIgFAAIAAALgAgJAGIAOAAIAAgRIAAgBIAAgCg");
	this.shape_20.setTransform(141,389.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgFAVQgDgCgCgDQgCgCgBgEQgCgFAAgFQAAgFACgEQABgEACgCQACgEADgBQADgBACAAIAGABQADABACAEIAEAGIABAJIgBAKIgEAGQgCADgDACIgGABQgCAAgDgBgAgDgPIgDADIgCAFIgBAHIABAIIACAGIADACIADABIAEgBIADgCIACgGIABgIIgBgHIgCgFIgDgDIgEgBIgDABg");
	this.shape_21.setTransform(137.5,389.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgJAWIAAgFIAJAAIAAgcIAAgCIgIAGIAAABIgBAAIgBAAIAAgBIgCgDIAMgKIAFAAIAAAlIAIAAIAAAFg");
	this.shape_22.setTransform(134.1,389.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAMAWIAAgUIgXAAIAAAUIgGAAIAAgqIAGAAIAAASIAXAAIAAgSIAFAAIAAAqg");
	this.shape_23.setTransform(128.5,389.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgOAWIAAgqIAOAAIAGAAIAEADIADAFIACAFIgCAFIgDAEIgEADIgGAAIgHAAIAAARgAgHAAIAHAAIACAAIAEgBIACgCIABgEIgBgEIgCgCIgEgCIgCAAIgHAAg");
	this.shape_24.setTransform(124.6,389.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgMAWIAAgqIAZAAIAAAFIgTAAIAAAlg");
	this.shape_25.setTransform(121.2,389.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgIAVIgHgFIgDgHQgCgEAAgFQAAgEACgEIADgHQADgDAEgCQAEgBAEAAQAFAAAEABQADACAEADQADADABAEQABAEAAAEQAAAFgBAEQgBAEgDADIgHAFQgEABgFAAQgEAAgEgBgAgFgOQgDAAgCADIgDAFIgBAGIABAHIADAFQACACADABIAFABIAGgBQADgBACgCIADgFIABgHIgBgGIgDgFQgCgDgDAAIgGgBIgFABg");
	this.shape_26.setTransform(117,389.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgFAVIgDgBIgDgBIgCgCIACgCIABgBIACAAIABABIADABIADABIADgBIADgCIACgDIABgEIgBgEIgBgCIgDgBIgDgBIgHABIgEgBIAEgUIATAAIAAADIAAACIgDAAIgMAAIgCALIAFAAIAGABIAEACIADAEIABAFQAAADgCADIgDAFIgFADIgFABIgEgBg");
	this.shape_27.setTransform(111.3,389.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgJAWIAAgFIAJAAIAAgcIAAgCIgIAGIAAABIgBAAIgBAAIAAgBIgCgDIAMgKIAFAAIAAAlIAIAAIAAAFg");
	this.shape_28.setTransform(107.8,389.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgFAVQgDgCgCgDQgCgCgBgEQgCgFAAgFQAAgFACgEQABgEACgCQACgEADgBQADgBACAAIAGABQADABACAEIAEAGIABAJIgBAKIgEAGQgCADgDACIgGABQgCAAgDgBgAgDgPIgDADIgCAFIgBAHIABAIIACAGIADACIADABIAEgBIADgCIACgGIABgIIgBgHIgCgFIgDgDIgEgBIgDABg");
	this.shape_29.setTransform(104.3,389.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgOAWIAAgCIABgBIABgCIAMgNIADgEIADgCIACgDIAAgEIAAgDIgCgCIgDgBIgDgBIgBABIgDABIgCACIgBACIAAACIgCAAIgEgBIACgFIAEgEIADgCIAFgBIAFABIAEACIADAEIABAFIgBAFIgCAEIgCACIgEAEIgKALIADAAIACgBIAMAAIACABIABABIAAAEg");
	this.shape_30.setTransform(100.8,389.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgJAWIAAgFIAJAAIAAgcIAAgCIgIAGIAAABIgBAAIgBAAIAAgBIgCgDIAMgKIAFAAIAAAlIAIAAIAAAFg");
	this.shape_31.setTransform(97.3,389.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgFAVIgDgBIgDgBIgCgCIACgCIABgBIACAAIABABIADABIADABIADgBIADgCIACgDIABgEIgBgEIgBgCIgDgBIgDgBIgHABIgEgBIAEgUIATAAIAAADIAAACIgDAAIgMAAIgCALIAFAAIAGABIAEACIADAEIABAFQAAADgCADIgDAFIgFADIgFABIgEgBg");
	this.shape_32.setTransform(93.8,389.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAFAWIAAgLIgSAAIgBgBIgBgBIAAgDIAUgaIAFAAIAAAaIAGAAIAAADIAAABIgBABIgFAAIAAALgAgJAGIAOAAIAAgRIAAgBIAAgCg");
	this.shape_33.setTransform(90.2,389.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgFAVQgDgCgCgDQgCgCgBgEQgCgFAAgFQAAgFACgEQABgEACgCQACgEADgBQADgBACAAIAGABQADABACAEIAEAGIABAJIgBAKIgEAGQgCADgDACIgGABQgCAAgDgBgAgDgPIgDADIgCAFIgBAHIABAIIACAGIADACIADABIAEgBIADgCIACgGIABgIIgBgHIgCgFIgDgDIgEgBIgDABg");
	this.shape_34.setTransform(86.8,389.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgKAWIARgiIACgDIgVAAIgBAAIgBgCIAAgDIAdAAIAAACIAAACIgBABIgRAjIgBABIgCABg");
	this.shape_35.setTransform(83.3,389.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgKAWIARgiIACgDIgVAAIgBAAIgBgCIAAgDIAdAAIAAACIAAACIgBABIgRAjIgBABIgCABg");
	this.shape_36.setTransform(79.8,389.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAMAWIAAgUIgXAAIAAAUIgFAAIAAgqIAFAAIAAASIAXAAIAAgSIAFAAIAAAqg");
	this.shape_37.setTransform(74.3,389.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAMAWIAAgUIgXAAIAAAUIgGAAIAAgqIAGAAIAAASIAXAAIAAgSIAFAAIAAAqg");
	this.shape_38.setTransform(69.7,389.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAMAWIAAgeIAAgCIAAgDIgCACIgBACIgTAdIAAABIgCABIgFAAIAAgqIAHAAIAAAcIAAADIAAADIAAgCIABgDIATgcIACgBIABAAIAEAAIAAAqg");
	this.shape_39.setTransform(65.1,389.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgJAVIAAgEIAJAAIAAgcIAAgCIgIAGIAAABIgBAAIgBAAIAAgBIgCgCIAMgMIAFAAIAAAmIAIAAIAAAEg");
	this.shape_40.setTransform(231.2,380);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgFAUQgDAAgCgDQgCgDgBgEQgCgEAAgGQAAgFACgEQABgEACgCQACgDADgCQADgBACAAIAGABQADACACADIAEAGIABAJIgBAKIgEAHQgCADgDAAIgGACQgCAAgDgCgAgDgPIgDACIgCAGIgBAHIABAIIACAFIADAEIADAAIAEAAIADgEIACgFIABgIIgBgHIgCgGIgDgCIgEgBIgDABg");
	this.shape_41.setTransform(227.6,380);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgFAUQgDAAgCgDQgCgDgBgEQgCgEAAgGQAAgFACgEQABgEACgCQACgDADgCQADgBACAAIAGABQADACACADIAEAGIABAJIgBAKIgEAHQgCADgDAAIgGACQgCAAgDgCgAgDgPIgDACIgCAGIgBAHIABAIIACAFIADAEIADAAIAEAAIADgEIACgFIABgIIgBgHIgCgGIgDgCIgEgBIgDABg");
	this.shape_42.setTransform(224.1,380);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgJAVIAAgEIAJAAIAAgcIAAgCIgIAGIAAABIgBAAIgBAAIAAgBIgCgCIAMgMIAFAAIAAAmIAIAAIAAAEg");
	this.shape_43.setTransform(220.7,380);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgDAPIgFgDIgCgFIgBgHIABgFIACgFIAFgEIAFgBIAGABIAEADIgCACIAAABIgBAAIgBAAIgBgBIgCgBIgDAAIgCAAIgDADIgCADIgBAEIABAFIACADIADADIACAAIADAAIACgBIABgBIABgBIABABIACACIgCACIgDACIgDAAIgDABIgEgBg");
	this.shape_44.setTransform(216.1,380.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAIAPIAAgTIAAgBIAAgCIgBACIAAAAIgBABIgCADIgCACIgCADIgHAKIAAABIgCAAIgDAAIAAgdIAGAAIAAATIAAABIgBACIACgCIAAgBIACgDIACgCIACgDIAHgKIABgBIABAAIADAAIAAAdg");
	this.shape_45.setTransform(212.8,380.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgCAbIAAgKIgGgCIgGgDIgDgFIgBgGIABgFIADgFIAGgDIAGgCIAAgMIAFAAIAAAMIAGACIAGADIADAFIABAFIgBAGIgDAFIgGADIgGACIAAAKgAADAMIAEgBIADgCIADgDIAAgFIAAgEIgDgDIgDgCIgEgBgAgJgGQgDADAAAEQAAAFADADQACADAGAAIAAgVQgGAAgCADg");
	this.shape_46.setTransform(209,380.5);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgFAPIgEgEIgEgFIgBgGIABgGIAEgEIAEgEIAFgBIAGABIAEAEIADAEIACAGIgCAGIgDAFIgEAEIgGABIgFgBgAgGgHQgCADABAEQgBAFACADQACADAEAAQAFAAACgDQACgDAAgFQAAgEgCgDQgCgDgFAAQgEAAgCADg");
	this.shape_47.setTransform(205.2,380.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgCAHIAAAAIAAgBIAAgBIABgBIABgBIAAgBIAAgCIAAAAIAAAAIgCAAIAAgCIgBgBIABgDIACgBIACABIABABIABABIAAACIAAACIgCADIgBACIgCADg");
	this.shape_48.setTransform(201.3,382.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgFAVIgEgCIgEgEIgBgFQAAgFADgCQACgDADAAQgDgBgBgDQgCgCAAgDIABgFIADgEIADgCIAFgBIAGABIAEACIACAEIABAFQAAADgCACQgCADgDABQAEAAACADQACACABAFIgCAFIgDAEIgEACIgGABIgFgBgAgCACIgDABIgCADIgBAEIABACIABADIADACIADABIADgBIAEgCIABgDIABgCIgBgEIgCgDIgDgBIgDAAIgCAAgAgCgQIgDABIgBACIgBAEIABACIABACIADACIACABIADgBIADgCIABgCIABgCIgBgEIgBgCIgDgBIgDAAIgCAAg");
	this.shape_49.setTransform(198.9,380);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AAAADIgBAAIgBgBIgBgCIABAAIABgCIABgBIAAAAIABAAIACABIAAACIABAAIgBACIAAABIgCAAIgBABIAAgBg");
	this.shape_50.setTransform(194.9,381.8);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AANAVIAAgLIgYAAIAAgBIACgBIACgCIAOAAIAAgVIgJAAIAAAIIgCAGIgBAEIgCADIgEAAIAAADIgBAAIgEAAIAAgDIAAADIAEAAIABAAIAAABIgGAAIAAgEIABAAIAAAAIABAAIAEAAIgEAAIACgBIACgBIABgDIACgEIABgHIABgKIASAAIAAAZIAGAAIAAAOIgBABIgBABgAgRAVIAAgLIAGAAIAAAJIgBABIgBABgAgLAJgAgLAGIAEAAIgCACIgCABgAgHAGIACgDIABgEIACgGIAAgIIAJAAIAAAVgAgHAGg");
	this.shape_51.setTransform(192.3,381.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgCAHIAAAAIAAgBIAAgBIABgBIABgBIAAgBIAAgCIAAAAIAAAAIgCAAIAAgCIgBgBIABgDIACgBIACABIABABIABABIAAACIAAACIgCADIgBACIgCADg");
	this.shape_52.setTransform(188.3,382.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAIAVIAAgTIAAgCIAAAAIgBAAIAAABIgBABIgCACIgCADIgCAEIgHAJIAAABIgCAAIgDAAIAAgdIAGAAIAAATIAAABIgBACIACgCIAAgBIACgCIACgEIACgDIAHgIIABgBIABgBIADAAIAAAdgAgCgNIgDgBIgCgCIAAgDIAAgBIABgBIADAAIAAADIABACIABABIABAAIACAAIACgBIABgCIAAgDIADAAIABABIAAABIAAADIgCACIgDABIgEAAIgCAAg");
	this.shape_53.setTransform(185.9,380);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgGADIAAgFIANAAIAAAFg");
	this.shape_54.setTransform(183.1,380.4);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgNAWIAAgCIAAgBIABgCIAMgNIAEgEIACgCIABgDIABgEIgBgDIgBgCIgCgBIgEgBIgBABIgDABIgCACIgBACIgBACIgCAAIgCgBIABgFIADgEIAFgCIAEgBIAFABIAEACIADAEIABAFIgBAFIgCAEIgDACIgDAEIgKALIADAAIACgBIANAAIABABIABABIAAAEg");
	this.shape_55.setTransform(180.2,380);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AAIAVIAAgTIAAgCIAAAAIgBAAIAAABIgBABIgCACIgCADIgCAEIgHAJIAAABIgCAAIgDAAIAAgdIAGAAIAAATIAAABIgBACIACgCIAAgBIACgCIACgEIACgDIAHgIIABgBIABgBIADAAIAAAdgAgCgNIgDgBIgCgCIAAgDIAAgBIABgBIADAAIAAADIABACIABABIABAAIACAAIACgBIABgCIAAgDIADAAIABABIAAABIAAADIgCACIgDABIgEAAIgCAAg");
	this.shape_56.setTransform(175.2,380);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AAIAPIAAgTIAAgBIAAgCIgBACIAAAAIgBABIgCADIgCACIgCADIgHAKIAAABIgCAAIgDAAIAAgdIAGAAIAAATIAAABIgBACIACgCIAAgBIACgDIACgCIACgDIAHgKIABgBIABAAIADAAIAAAdg");
	this.shape_57.setTransform(171.8,380.6);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AAJAPIgCAAIgBgCIgGgJIgBgCIgCAAIgDAAIAAANIgGAAIAAgdIAGAAIAAANIACAAIADgBIABgBIAFgKIABgBIACAAIAFAAIgIALIgCACIgCABIADABIABACIAIAMg");
	this.shape_58.setTransform(168.7,380.6);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgEAPIgDgDIgEgFIgBgHIABgFIADgFIAEgEIAGgBIAFABIAFADIgBACIgBABIgBAAIgBAAIgBgBIgCgBIgDAAIgDAAIgDADIgBADIAAAEIAAAFIABADIADADIADAAIADAAIACgBIABgBIACgBIABABIACACIgDACIgDACIgDAAIgDABIgFgBg");
	this.shape_59.setTransform(165.6,380.6);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AAHAPIAAgOIgNAAIAAAOIgGAAIAAgdIAGAAIAAAMIANAAIAAgMIAGAAIAAAdg");
	this.shape_60.setTransform(162.4,380.6);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AAIAPIAAgTIAAgBIAAgCIgBACIAAAAIgBABIgCADIgCACIgCADIgHAKIAAABIgCAAIgDAAIAAgdIAGAAIAAATIAAABIgBACIACgCIAAgBIACgDIACgCIACgDIAHgKIABgBIABAAIADAAIAAAdg");
	this.shape_61.setTransform(159,380.6);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AASAVIAAgLIgoAAIAAgeIAGAAIAAAZIAMAAIAAgZIAEAAIAAAZIAMAAIAAgZIAGAAIAAAZIAFAAIAAAOIAAABIgBABg");
	this.shape_62.setTransform(154.8,381.2);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AgFAPIgEgEIgDgFIgCgGIACgGIADgEIAEgEIAFgBIAGABIAEAEIAEAEIABAGIgBAGIgEAFIgEAEIgGABIgFgBgAgGgHQgCADAAAEQAAAFACADQACADAEAAQAFAAACgDQACgDAAgFQAAgEgCgDQgCgDgFAAQgEAAgCADg");
	this.shape_63.setTransform(150.4,380.6);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AgNAVIAAgqIAMAAIAGABIAGADIADAEIAAAGIAAAFIgDAEIgGACIgGABIgHAAIAAAQgAgIABIAHAAIAEgBIADgBIABgDIABgDIgBgEIgBgDIgDgBIgEAAIgHAAg");
	this.shape_64.setTransform(147.1,380);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AANAVIAAgLIgYAAIAAgBIACgBIACgCIAOAAIAAgVIgJAAIAAAIIgCAGIgBAEIgCADIgEAAIAAADIgBAAIgEAAIAAgDIAAADIAEAAIABAAIAAABIgGAAIAAgEIABAAIAAAAIABAAIAEAAIgEAAIACgBIACgBIABgDIACgEIABgHIABgKIASAAIAAAZIAGAAIAAAOIgBABIgBABgAgRAVIAAgLIAGAAIAAAJIgBABIgBABgAgLAJgAgLAGIAEAAIgCACIgCABgAgHAGIACgDIABgEIACgGIAAgIIAJAAIAAAVgAgHAGg");
	this.shape_65.setTransform(141.7,381.2);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgDAPIgDAAIgCgCIgCgCIABgCIABgBIABABIACABIACABIADAAIACAAIACgBIABgCIABgCQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAQgBgCgDAAIgEAAIAAgDIAEAAIADgBQABAAAAAAQABgBAAAAQAAgBAAAAQAAAAAAgBIAAgCIgBgBIgCgBIgCAAIgDAAIgCABIgCABIAAAAIgBAAIAAgBIgCgCIAEgDIAGgBIAEABIAEACIACACIABADIAAACIgBACIgCACIgDABQADAAACACQACACgBADIAAADIgDADIgEACIgEABIgDgBg");
	this.shape_66.setTransform(138.5,380.6);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgEAPIgEgEIgEgFIgBgGIABgGIADgEIAEgEIAGgBIAFABIAEADIACAEIABAGIAAABIgBAAIgTAAIABAFIACADIACADIAEAAIADAAIADgBIABgBIACgBIABABIABACIgCACIgDACIgEAAIgDABIgFgBgAgEgIQgCACgBAEIAQAAIgBgEIgCgCIgCgCIgDAAQgDAAgCACg");
	this.shape_67.setTransform(135.7,380.6);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AgFAPIgEgEIgDgFIgCgGIACgGIADgEIAEgEIAFgBIAGABIAEAEIAEAEIABAGIgBAGIgEAFIgEAEIgGABIgFgBgAgGgHQgCADAAAEQAAAFACADQACADAEAAQAFAAACgDQACgDAAgFQAAgEgCgDQgCgDgFAAQgEAAgCADg");
	this.shape_68.setTransform(132.4,380.6);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AgMAUIAAgnIADAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIABADIAEgDQADgBACAAIAFABIAEACIACAGIABAGIgBAFIgDAGIgEACQgDACgDAAIgDgBIgDgCIAAAMgAgDgOIgDAEIAAANIADADIADABQAEAAABgEQADgDAAgEIgBgFIgBgEIgCgCIgEAAIgDABg");
	this.shape_69.setTransform(129.1,381.1);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AAKAVIAAgkIgUAAIAAAkIgGAAIAAgqIAhAAIAAAqg");
	this.shape_70.setTransform(125.1,380);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AgCAHIAAAAIAAgBIAAgBIABgBIABgBIAAgBIAAgCIAAAAIAAAAIgCAAIAAgCIgBgBIABgDIACgBIACABIABABIABABIAAACIAAACIgCADIgBACIgCADg");
	this.shape_71.setTransform(120.7,382.2);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AgGAPIgCgBIgDgDIAAgDIABgEIADgDIAGgBIAHgBIAAgCQAAgEgBgBQAAgBgBAAQAAAAgBgBQAAAAgBAAQgBAAAAAAIgDAAIgCABIgBABIgCABIgBAAIAAgBIgCgCIAGgEIAGgBIAEABIAEACIACAEIAAAFIAAASIgCAAIgBAAIgCgBIAAgDIgDACIgBACIgDAAIgDABIgDgBgAABACIgEABIgCACIAAACIAAACIABACIABAAIACABIACgBIACAAIACgCIABgBIAAgGIgFAAg");
	this.shape_72.setTransform(118.5,380.6);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AgLAPIAAgdIALAAIAFAAIADACIACACIAAADIAAACIgBACIgCACIgDABQAEAAACACQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIgBAEIgDADIgDACIgFAAgAgFALIAFAAQABAAABAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgCIgBgBIgCgBIgDAAIgFAAgAgFgBIAFAAIACAAIACgBIABgCIAAgCIAAgCIgBgBIgCgBIgCAAIgFAAg");
	this.shape_73.setTransform(115.6,380.6);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AAJAPIgCAAIgBgCIgGgJIgBgCIgCAAIgDAAIAAANIgGAAIAAgdIAGAAIAAANIACAAIADgBIABgBIAFgKIABgBIACAAIAFAAIgIALIgCACIgCABIADABIABACIAIAMg");
	this.shape_74.setTransform(112.7,380.6);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgDAPIgFgDIgDgFIAAgHIAAgFIADgFIAFgEIAFgBIAFABIAFADIgCACIAAABIgBAAIgBAAIgBgBIgCgBIgDAAIgDAAIgCADIgCADIAAAEIAAAFIACADIACADIADAAIADAAIACgBIABgBIABgBIABABIADACIgDACIgDACIgDAAIgDABIgEgBg");
	this.shape_75.setTransform(109.6,380.6);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgFAPIgEgEIgEgFIgBgGIABgGIAEgEIAEgEIAFgBIAGABIAFAEIACAEIABAGIgBAGIgCAFIgFAEIgGABIgFgBgAgGgHQgBADAAAEQAAAFABADQADADADAAQAFAAABgDQADgDAAgFQAAgEgDgDQgBgDgFAAQgDAAgDADg");
	this.shape_76.setTransform(106.4,380.6);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AARAVIAAgdIAAgCIAAgCIgOAaIgBABIgBAAIgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBgBAAIgOgaIAAACIAAACIAAAdIgGAAIAAgqIAFAAIABAAIABABIAPAZIAAAEIABgCIABgCIAOgZIABgBIABAAIAEAAIAAAqg");
	this.shape_77.setTransform(101.9,380);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AgBADIAAAAIgBgBIgBgCIABAAIABgCIAAgBIABAAIABAAIACABIABACIAAAAIAAACIgBABIgCAAIgBABIgBgBg");
	this.shape_78.setTransform(96.9,381.8);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AgJAPIAAgdIATAAIAAAEIgNAAIAAAZg");
	this.shape_79.setTransform(95.1,380.6);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgCAHIAAAAIAAgBIAAgBIABgBIABgBIAAgBIAAgCIAAAAIAAAAIgCAAIAAgCIgBgBIABgDIACgBIACABIABABIABABIAAACIAAACIgCADIgBACIgCADg");
	this.shape_80.setTransform(91.5,382.2);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AgIAWIAMgRIABgCIABgBIgEACIgDAAIgFgBIgDgCIgDgDIgBgFIABgFIADgFIAEgDIAFgBIAGABIAEADIADAFIABAFIAAAEIgBADIgCACIgCADIgJAPIgBABIgCABgAgCgPIgDABIgCADIgBADQABAEACADQACABADAAIADAAIAEgCIABgCIABgDIgBgEIgBgDIgEgBIgDgBIgCABg");
	this.shape_81.setTransform(89.1,380);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AgJAVIAAgEIAJAAIAAgcIAAgCIgIAGIAAABIgBAAIgBAAIAAgBIgCgCIAMgMIAFAAIAAAmIAIAAIAAAEg");
	this.shape_82.setTransform(85.6,380);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AAFAVIAAgKIgSAAIgBgBIgBgBIAAgDIAUgbIAFAAIAAAbIAGAAIAAADIAAABIgBABIgFAAIAAAKgAgJAGIAOAAIAAgRIAAgBIAAgCg");
	this.shape_83.setTransform(82,380);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AgFAVIgDgBIgDgBIgCgCIACgCIABgBIACAAIABABIADABIADABIADgBIADgCIACgDIABgEIgBgEIgBgCIgDgBIgDgBIgHABIgEgBIAEgUIATAAIAAADIAAACIgDAAIgMAAIgCALIAFAAIAGABIAEACIADAEIABAFQAAADgCADIgDAFIgFADIgFABIgEgBg");
	this.shape_84.setTransform(78.6,380);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AgJAVIAAgEIAJAAIAAgcIAAgCIgIAGIAAABIgBAAIgBAAIAAgBIgCgCIAMgMIAFAAIAAAmIAIAAIAAAEg");
	this.shape_85.setTransform(75.1,380);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AgJAVIAAgEIAJAAIAAgcIAAgCIgIAGIAAABIgBAAIgBAAIAAgBIgCgCIAMgMIAFAAIAAAmIAIAAIAAAEg");
	this.shape_86.setTransform(71.6,380);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AAAALIAAAAIAAgCIAFgIIAAAAIAAgBIAAAAIAAAAIgFgIIAAgBIAAgBIACgBIAIALIAAABIgIALgAgIALIAAAAIAAgCIAFgIIAAAAIAAgBIAAAAIAAAAIgFgIIAAgBIAAgBIACgBIAHALIAAABIgHALg");
	this.shape_87.setTransform(67.1,380.6);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AgBADIgBAAIAAgBIgBgCIABAAIAAgCIABgBIABAAIABAAIACABIABACIAAAAIAAACIgBABIgCAAIgBABIgBgBg");
	this.shape_88.setTransform(65.1,381.8);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FFFFFF").s().p("AgMAVIAAgqIAZAAIAAAGIgTAAIAAAkg");
	this.shape_89.setTransform(63,380);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AgBADIgBAAIgBgBIAAgCIAAAAIABgCIABgBIABAAIACAAIABABIABACIAAAAIAAACIgBABIgBAAIgCABIgBgBg");
	this.shape_90.setTransform(60.4,381.8);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FFFFFF").s().p("AAMAVIAAgTIgWAAIAAATIgHAAIAAgqIAHAAIAAATIAWAAIAAgTIAFAAIAAAqg");
	this.shape_91.setTransform(57.4,380);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AAAADIgBAAIgBgBIgBgCIABAAIABgCIABgBIAAAAIABAAIACABIAAACIABAAIgBACIAAABIgCAAIgBABIAAgBg");
	this.shape_92.setTransform(54.4,381.8);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFFFFF").s().p("AgFAUIgGgEQgEgDgBgEIgBgJQAAgEABgEIAFgHQACgDAEgCQAEgBAEAAQAFAAADABIAGAFIgCACIAAABIgBAAIgCgBIgCgBIgCgBIgFAAIgFAAQgDACgCACIgDAFIgBAGIABAHIADAFIAFADIAEACIAEAAIADgCIACgBIADgBIAAgBIABAAIABABIACACIgHAFQgDACgGAAQgEAAgDgCg");
	this.shape_93.setTransform(51.8,380);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AAMAVIAAgcIAAgDIAAgEIgBADIgBADIgUAcIgBABIgBAAIgEAAIAAgqIAFAAIAAAeIAAACIAAADIABgDIABgBIATgcIACgCIABgBIAEAAIAAAqg");
	this.shape_94.setTransform(45.9,380);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("AARAbIAAgLIghAAIAAAJIgBABIgBABIgEAAIAAgQIAFAAIABgBIACgDIACgFIABgGIABgJIABgNIAZAAIAAAlIAHAAIAAAOIgBABIgBABgAgEgIIgCAIIgCAHIgCAEIAUAAIAAggIgNAAIgBANg");
	this.shape_95.setTransform(41.2,380.5);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AAMAVIAAgTIgXAAIAAATIgFAAIAAgqIAFAAIAAATIAXAAIAAgTIAGAAIAAAqg");
	this.shape_96.setTransform(36.6,380);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#FFFFFF").s().p("AAQAVIgCAAIAAgBIgEgKIgSAAIgEAKIgBABIgBAAIgFAAIARgqIAFAAIARAqgAAAgNIAAACIgHAQIAPAAIgHgQIAAgCIgBgCIAAACg");
	this.shape_97.setTransform(32.2,380);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#FFFFFF").s().p("AAMAVIgCAAIgBgBIgKgQIgCgBIgCgBIgFAAIAAATIgGAAIAAgqIAGAAIAAATIAEAAIABAAIABgBIABAAIABgBIAKgPIABgBIACgBIAFAAIgNASQAAABAAAAQgBAAAAABQgBAAAAAAQgBABAAAAIACABIADACIAMASg");
	this.shape_98.setTransform(28.4,380);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#FFFFFF").s().p("AAAABIAAgBIAHgLIACABIAAABIAAABIgEAIIgBAAIABABIAEAIIAAACIAAAAIgCABgAgJABIAAgBIAIgLIABABIAAABIAAABIgDAIIgBAAIABABIADAIIAAACIAAAAIgBABg");
	this.shape_99.setTransform(24.8,380.6);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#FFFFFF").s().p("AgHAUIgIgEIgDgHQgCgEgBgFQABgEACgEIADgHQAEgDAEgCQADgBAEAAQAFAAAEABQAEACADADQACADACAEQACAEgBAEQABAFgCAEQgCAEgCADIgHAEQgEACgFAAQgEAAgDgCgAgFgPQgDACgCACIgDAFIgBAGIABAHIADAFQACACADABIAFACIAGgCQADgBACgCIADgFIABgHIgBgGIgDgFQgCgCgDgCIgGAAIgFAAg");
	this.shape_100.setTransform(19.7,380);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#FFFFFF").s().p("AgHAUIgHgEIgFgHQgCgEAAgFQAAgEACgEIAFgHQACgDAFgCQAEgBADAAQAFAAAEABQADACADADQADADACAEQABAEABAEQgBAFgBAEQgCAEgDADIgGAEQgEACgFAAQgDAAgEgCgAgFgPQgDACgCACIgDAFIgBAGIABAHIADAFQACACADABIAFACIAGgCQADgBACgCIADgFIABgHIgBgGIgDgFQgCgCgDgCIgGAAIgFAAg");
	this.shape_101.setTransform(14.9,380);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#FFFFFF").s().p("AgIAUIgHgEIgEgHQgBgEAAgFQAAgEABgEIAEgHQAEgDADgCQAFgBADAAQAFAAAEABQAEACADADQADADABAEQACAEAAAEQAAAFgCAEQgBAEgDADIgHAEQgEACgFAAQgDAAgFgCgAgFgPQgDACgCACIgDAFIgBAGIABAHIADAFQACACADABIAFACIAGgCQADgBACgCIADgFIABgHIgBgGIgDgFQgCgCgDgCIgGAAIgFAAg");
	this.shape_102.setTransform(10.1,380);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#1899D6").s().p("AysK8IAA13MAlZAAAIAAV3g");
	this.shape_103.setTransform(120,330,1.002,1);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#FFFFFF").s().p("AgSADIgCgFIAnAAIACAFg");
	this.shape_104.setTransform(134.7,46.2);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#FFFFFF").s().p("AgIATIAKgmIAHAAIgKAmg");
	this.shape_105.setTransform(136.8,49.5);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#009FE3").s().p("AgPAMIAGgXIAZAAIgGAXg");
	this.shape_106.setTransform(134.5,49.4);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#1D1D1B").s().p("AglAiQgKgKACgQQACgVARgPQARgPAVAAQAQAAAKAJQAKAKgBARQgCAUgSAQQgRAPgVAAQgRAAgJgKgAgMgOQgJAJAAAKQgBAIAEAFQAFAFAIAAQAJAAAJgIQAJgJABgJQABgJgFgFQgEgFgJAAQgKAAgIAIg");
	this.shape_107.setTransform(150.3,52.4);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#1D1D1B").s().p("AgjArIAWhTIAWAAIgCAJQADgEAFgDQAGgEAFAAQAGAAAEACIgGAVQgFgBgFAAQgHAAgHAIQgFAHgBAIIgLAog");
	this.shape_108.setTransform(142.7,52.3);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#009FE3").s().p("AggA2IARg8IgOAAIAGgXIAOAAIAGgYIAZAAIgGAYIARAAIgGAXIgHAAIAAAAIgKAAIgQA8g");
	this.shape_109.setTransform(133.8,51.2);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#1D1D1B").s().p("Ag3BFIAliJIAnAAQARAAAJAHQAKAIgCAQQAAAFgBADQgFATgPAKQgOAIgUAAIgMAAIgQA9gAgGgOIALAAQAWAAACgTQACgMgSAAIgMAAg");
	this.shape_110.setTransform(136.1,49.7);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#1899D6").s().p("AgjArIAWhTIAWAAIgCAJQADgEAGgDQAFgEAFAAQAGAAAEACIgGAVQgFgBgFAAQgHAAgHAIQgFAHgBAIIgLAog");
	this.shape_111.setTransform(127.4,52.3);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#1899D6").s().p("AgrAiQgJgKACgQQACgUAQgQQARgQATAAQAQAAAFAMIACgJIAYAAIgVBTIgYAAIACgKQgKAMgRAAQgQAAgIgKgAgRgOQgIAIgBAKQgCAHAFAGQAFAHAIgBQAKAAAIgIQAJgJABgJQABgJgFgFQgFgGgIABQgJAAgJAIg");
	this.shape_112.setTransform(119.1,52.4);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#1899D6").s().p("AAfArIANguIABgGQABgMgLAAQgNgBgGAUIgMAtIgWAAIANg0QABgMgKAAQgOAAgGATIgMAtIgYAAIAWhTIAXAAIgCAKQAKgMAPAAQAQAAADAOQALgOAUAAQAMAAAGAGQAGAHgBALIgBAHIgPA2g");
	this.shape_113.setTransform(106.1,52.3);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#1899D6").s().p("AgmA0QgJgIACgPIABgIIAaAAIAAADQgCANALABQAHgBAEgEQAEgEABgHQABgGgJgGIgUgMQgKgIACgMQABgQAQgLQAMgKARAAQAPAAAHAHQAJAIgCANIgBAHIgaAAIABgEQABgJgKgBQgFAAgFAEQgCACgBAGQgBAGAJAHIATAMQAMAJgCAKIgCAGQgEARgOAKQgMAJgRAAQgQAAgIgIg");
	this.shape_114.setTransform(95.1,50.8);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#1899D6").s().p("AFRAvIAAgOIgzAAIAAAOIgJAAIAAgXIAFAAIAZhFIAJAAIAZBFIAFAAIAAAXgAE3ggIgUA4IAoAAIgUg4gAFpAWQgLgLAAgRQAAgQAMgMQALgMARAAQARAAALAMQAMALAAARQAAAQgLAMQgMAMgRAAQgRAAgMgMgAFwgcQgJAJAAANQAAAMAJAKQAIAJAOAAQANAAAJgJQAJgKAAgMQAAgNgKgJQgJgJgMAAQgNAAgJAJgAoHAWQgMgLAAgRQAAgQAMgMQAMgMAQAAQAZAAAKAVIgLAAQgJgMgPAAQgMAAgJAJQgJAKAAAMQAAAMAIAJQAJAKANAAQAPAAAJgMIALAAQgFAKgJAGQgKAFgLAAQgRAAgLgMgAJtAhIAAhOIApAAIAAAJIggAAIAAAaIAeAAIAAAIIgeAAIAAAaIAgAAIAAAJgAI3AhIAAhOIApAAIAAAJIggAAIAAAaIAeAAIAAAIIgeAAIAAAaIAgAAIAAAJgAIfAhIAAgjIgjAAIAAAjIgJAAIAAhOIAJAAIAAAiIAjAAIAAgiIAKAAIAABOgAG5AhIAAhOIAqAAIAAAJIghAAIAAAXIALAAQALAAAIAFQAIAHAAAKQAAAMgIAGQgIAGgLAAgAHCAYIALAAQASAAAAgPQAAgOgSAAIgLAAgADpAhIAHgOIgehAIAKAAIAYA1IAYg1IAKAAIgjBOgACiAhIAAgPIAIAAIAAAPgABoAhIAAhOIAoAAIAAAJIgfAAIAAAaIAdAAIAAAIIgdAAIAAAaIAfAAIAAAJgAAyAhIAAhOIAoAAIAAAJIgfAAIAAAaIAdAAIAAAIIgdAAIAAAaIAfAAIAAAJgAAaAhIAAgjIgiAAIAAAjIgJAAIAAhOIAJAAIAAAiIAiAAIAAgiIAJAAIAABOgAgpAhIAAhAIABgEIgBAAIgaBEIgHAAIgbhEIAAAAIAAADIAAAEIAAA9IgJAAIAAhOIAOAAIAZBAIAZhAIAOAAIAABOgAigAhIAGgOIgdhAIAJAAIAZA1IAXg1IAKAAIgjBOgAjnAhIAAgPIAHAAIAAAPgAkiAhIAAhOIApAAIAAAJIgfAAIAAAaIAdAAIAAAIIgdAAIAAAaIAfAAIAAAJgAlYAhIAAhOIApAAIAAAJIgfAAIAAAaIAdAAIAAAIIgdAAIAAAaIAfAAIAAAJgAmRAhIAAhOIAVAAQALAAAIAGQAHAFAAAMQAAAMgHAGQgIAEgLAAIgLAAIAAAhgAmHgHIAKAAQASAAAAgPQAAgOgSAAIgKAAgAmzAhIAAhFIgQAAIAAgJIAqAAIAAAJIgQAAIAABFgAonAhIAAhOIAJAAIAABOgApbAhIAAhOIAKAAIAAAgIAIAAQANAAAHAFQAIAHAAALQAAALgIAGQgIAGgMAAgApRAYIAIAAQASAAAAgPQAAgNgSAAIgIAAgAqVAhIAAhOIArAAIAAAJIgiAAIAAAXIALAAQAMAAAHAFQAIAGAAALQAAAMgIAGQgHAGgMAAgAqMAYIALAAQASAAAAgPQAAgOgSAAIgLAAg");
	this.shape_115.setTransform(122.7,75.2);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#1899D6").s().p("AmcB3QhlAAgrgoQgpgkAYg2QAVgwBDgcQBKggB4ABQAaAAAZADIAfAEIANADIgSAfQgkgLghAAQg9AAgxASQhEAYgKAvQgGAdAUAZQAbAhA6gDQATAAAjgMQArgPAZgUIA9g1QAGgEAGgDIAMgDIAGgBIBBAAIAVBaIAphZIBHAAIAqBFIAfhFIBBAAIg5B+IhEAAIgrhJIggBJIgqAAIAAAAIhOAAIgDgWIhHAAIgYAVIguAAQg1AThFAAgAi+A1IAqAAIgEgkgAF2BwIAqgpIgqhgIBBAAIASAzIA1g0IBJABIh/B+IgEAEQgEADgDABQgEACgLABgADzBlIhqAAIA6h+IBqAAQAzAAATAZQAPATgLAZQgLAXgbAPQgjATg4AAIgDAAgADfBFIATAAQAWAAAQgFQAbgIAFgVQAFgRgRgHQgLgFgUAAIgSAAg");
	this.shape_116.setTransform(122.7,24.9);

	this.text = new cjs.Text("", "12px 'TimesNewRomanPSMT'");
	this.text.lineHeight = 15;
	this.text.parent = this;
	this.text.setTransform(116.9,311);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.text},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(291));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(119.5,199.5,260.5,401);
// library properties:
lib.properties = {
	width: 240,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/240x400_atlas_.png", id:"240x400_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;